export default {
    "auriga_all": "منصة صانع",
    "extensionName": "منصة صانع",
    "extensionDescription": "مجموعة ملحقات الحارس mBot",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_PORT_0": "على متن منفذ المحرك1",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_PORT_1": "على متن منفذ المحرك2",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_ROTATE_0": "عكس اتجاه عقارب الساعة",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_ROTATE_1": "عكس عقارب الساعة",
    "auriga_run_board_encoder_motor": "[ICON]محرك الترميز [PORT] [ROTATE] تدور بقوة [POWER]%",
    "auriga_run_board_encoder_motor_speed": "[ICON]محرك الترميز [PORT] [ROTATE] يدور بسرعة [POWER] دورة/دقيقة",
    "auriga_run_board_encoder_motor_pos": "[ICON]محرك الترميز [PORT] [ROTATE] تدور حسب [DEGREE] درجة في سرعة[POWER] دورة/دقيقة",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_0": "port1",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_1": "port2",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_2": "port3",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_3": "port4",
    "AURIGA_RUN_ENCODER_MOTOR_SLOT_0": "الفتحة1",
    "AURIGA_RUN_ENCODER_MOTOR_SLOT_1": "الفتحة2",
    "AURIGA_RUN_ENCODER_MOTOR_ROTATE_0": "عكس اتجاه عقارب الساعة",
    "AURIGA_RUN_ENCODER_MOTOR_ROTATE_1": "عكس عقارب الساعة",
    "auriga_run_encoder_motor": "[ICON] محرك الترميز [PORT] [SLOT] [ROTATE] تدور حسب [DEGREE] درجة في سرعة [POWER] دورة/دقيقة",
    "auriga_encoder_motor_speed": "[ICON] محرك الترميز [PORT] سرعة تدوير (r/min)",
    "auriga_encoder_motor_pos": "[ICON] محرك الترميز [PORT] زاوية (°)",
    "auriga_run_motor": "[ICON] محرك بتيار مستمر [PORT] [ROTATE] تدور بقوة [POWER] %",
    "auriga_run_stepper_motor_pos": "[ICON] محرك الدوس [PORT] [ROTATE] تدور مع مسافة [DISTANCE] الخطوات، في سرعة [POWER] stp/min",
    "AURIGA_RUN_SERVO_PORT_0": "port6",
    "AURIGA_RUN_SERVO_PORT_1": "port7",
    "AURIGA_RUN_SERVO_PORT_2": "port8",
    "AURIGA_RUN_SERVO_PORT_3": "port9",
    "AURIGA_RUN_SERVO_PORT_4": "port10",
    "auriga_run_servo": "[ICON] سيرفو [PORT] [SLOT] تم وضعه في [DEGREE] زاويه",
    "AURIGA_RUN_FAN_FAN_ROTATE_0": "عكس اتجاه عقارب الساعة",
    "AURIGA_RUN_FAN_FAN_ROTATE_1": "عكس عقارب الساعة",
    "AURIGA_RUN_FAN_FAN_ROTATE_2": "توقف",
    "auriga_run_fan": "[ICON] مروحه [PORT] [FAN_ROTATE] تدور",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_0": "اضغط",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_1": "الإصدار",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_2": "تركيز",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_3": "التوقف عن التركيز",
    "auriga_run_shutter": "[ICON]مصراع [PORT] [SHUTTER_ACTION]",
    "auriga_run_smart_servo_to_zero": "[ICON] سيرفو الذكية [INDEX] تدوير إلى موضع البدء",
    "auriga_run_smart_servo": "[ICON]سيرفو الذكية [INDEX] [ROTATE]يدور بسرعة [POWER]",
    "auriga_run_smart_servo_absolute": "[ICON]سيرفو الذكية [INDEX] [ROTATE] تدور إلى [POSITION] درجة في سرعة [POWER]دورة/دقيقة",
    "auriga_run_smart_servo_to_relative": "[ICON] سيرفو الذكية [INDEX] [ROTATE] تدور حسب [DEGREE] درجة في سرعة [POWER]دورة/دقيقة",
    "AURIGA_RUN_SMART_SERVO_RGB_R_0": "0",
    "AURIGA_RUN_SMART_SERVO_RGB_R_1": "20",
    "AURIGA_RUN_SMART_SERVO_RGB_R_2": "60",
    "AURIGA_RUN_SMART_SERVO_RGB_R_3": "150",
    "AURIGA_RUN_SMART_SERVO_RGB_R_4": "255",
    "auriga_run_smart_servo_rgb": "[ICON] تعيين سيرفو الذكية [INDEX] أحمر LED [R] الاخضر [G] الازرق [B]",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_0": "تيار",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_1": "الجهد الكهربائي",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_2": "السرعة",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_3": "زاويه",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_4": "الحرارة",
    "auriga_run_smart_servo_detect": "[ICON] سيرفو الذكية [INDEX][OPTION]",
    "auriga_show_face_time": "[ICON]لوحة LED [PORT] يعرض الصورة [FACE_PANEL] من أجل [TIME] ثانيه",
    "auriga_show_face": "[ICON]لوحة LED [PORT] يعرض الصورة [FACE_PANEL]",
    "auriga_show_face_position": "[ICON] لوحة LED [PORT] يعرض الصورة [FACE_PANEL] في x: [X] y: [Y]",
    "auriga_show_text": "[ICON] لوحة LED [PORT] يعرض النص [TEXT] ",
    "auriga_show_text_position": "[ICON] لوحة LED[PORT] يعرض النص [TEXT] في x: [X] y: [Y]",
    "auriga_show_number": "[ICON] لوحة LED [PORT] يظهر الرقم[NUMBER]",
    "auriga_show_time": "[ICON] لوحة LED [PORT] يعرض الوقت [NUMBER1]：[NUMBER2]",
    "auriga_show_face_off": "[ICON] لوحة LED [PORT] مسح الشاشة",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "الكل",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "auriga_show_external_led_time": "[ICON]RGB LED [PORT]  تضيء[LED_POSTION] مع اللون [COLOR] من أجل [TIME] ثانيه",
    "auriga_show_external_led": "[ICON]RGB LED [PORT] تضيء [LED_POSTION]مع اللون [COLOR]",
    "auriga_show_external_led_rgb": "[ICON] RGB LED [PORT]  تضيء [LED_POSTION] مع اللون الأحمر [R] الاخضر[G] الازرق [B]",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "أحمر",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "برتقالي",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "أصفر",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "أخضر",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "سماوي",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "أزرق",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "الارجواني",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "أسود",
    "auriga_show_all_ledstrip_color": "[ICON]شريط LED [PORT] [SLOT] جميع تضيء مع اللون [COLOR_LIST]",
    "auriga_show_ledstrip_color": "[ICON]شريط LED [PORT] [SLOT] [POS] تضيء مع اللون [COLOR_LIST]",
    "auriga_show_ledstrip_rbg": "[ICON] شريط LED [PORT] [SLOT] [POS] تضيء مع اللون الأحمر [R] الاخضر [G] الازرق [B]",
    "auriga_show_7segments_number": "[ICON] سبعة قطاعات [PORT] يعرض الرقم [NUMBER]",
    "auriga_detect_external_ultrasonic": "[ICON] مستشعر بالموجات فوق الصوتية [PORT] المسافه",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_0": "port6",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_1": "port7",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_2": "port8",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_3": "port9",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_4": "port10",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_5": "على متن1",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_6": "على متن2",
    "auriga_detect_external_light": "[ICON] مستشعر الضوء[PORT] شدة الضوء",
    "auriga_detect_external_loudness": "[ICON] مستشعر الصوت [PORT] حجم",
    "auriga_detect_external_linefollower": "[ICON] استشعار تتبع الخط [PORT]  قيمه",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "الجانب الأيسر",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "الجانب الأيمن",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "الكل",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "لا شيء",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "أسود",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "أبيض",
    "auriga_event_external_linefollower": "[ICON] استشعار تتبع الخط[PORT] الكشف عن [LINEFOLLOW_STATE] يجري [BLACK_WHITE]",
    "auriga_detec_temperature": "[ICON] استشعار درجة الحرارة [PORT] [SLOT] درجة الحرارة (℃)",
    "AURIGA_DETECT_HUMITURE_TEMP_HUMITURE_0": "الرطوبة",
    "AURIGA_DETECT_HUMITURE_TEMP_HUMITURE_1": "الحرارة",
    "auriga_detect_humiture": "[ICON] مستشعر الطنين [PORT] [TEMP_HUMITURE]",
    "auriga_event_touch": "[ICON] مستشعر اللمس [PORT] لمست",
    "auriga_detect_compass": "[ICON] البوصلة الإلكترونية [PORT] نحو الشمال",
    "auriga_detect_flame": "[ICON] جهاز استشعار اللهب [PORT]  قيمه",
    "auriga_detect_gas": "[ICON]مستشعر الغاز[PORT]  قيمه",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_0": " محور X",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_1": "محور Y",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_2": "z-محور",
    "auriga_detect_board_gyro_angle": "[ICON] الدوران على متن [AXIS] زاويه",
    "auriga_detect_gyro_angle": "[ICON] جيروسكوب زاوية [AXIS] للخارج",
    "auriga_event_pir_motion": "[ICON] مستشعر PIR [PORT] يكتشف حركة الإنسان",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_0": "زر1",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_1": "زر2",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_2": "زر3",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_3": "زر4",
    "auriga_event_button_press": "[ICON] زر [PORT] [FOUR_KEY] مضغوط",
    "auriga_event_limit_switch": "[ICON] الحد التبديل [PORT] [SLOT] يتم الضغط عليه",
    "auriga_detect_potentiometer": "[ICON] الجهد [PORT] قيمه",
    "AURIGA_DETECT_JOYSTICK_AXIS_X_Y_0": "محور X",
    "AURIGA_DETECT_JOYSTICK_AXIS_X_Y_1": "محور Y",
    "auriga_detect_joystick": "[ICON] عصا اللعب [PORT] [AXIS_X_Y] قيمه",
    "auriga_detect_infrared": "[ICON] جهاز استقبال الأشعة تحت الحمراء [PORT] ",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_0": "LLL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_1": "LLH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_2": "LHL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_3": "LHH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_4": "HLL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_5": "HLH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_6": "HHL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_7": "HHH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SLOT_0": "منفذ المحرك1",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SLOT_1": "منفذ المحرك2",
    "auriga_encoder_motor_V2_motor": "[ICON] تعيين ترميز محرك V2 DIP التبديل [SWITCH] [SLOT] القوة ل[POWER]%",
    "auriga_encoder_motor_V2_speed": "[ICON] تعيين ترميز محرك V2 DIP التبديل [SWITCH] [SLOT] السرعة إلى [SPEED]دورة/دقيقة",
    "auriga_encoder_motor_V2_pos": "[ICON] تعيين ترميز محرك V2 DIP التبديل [SWITCH] [SLOT]للتدوير بواسطة [DEGREE]درجات بسرعة [SPEED]دورة/دقيقة",
    "auriga_encoder_motor_V2_minute": "[ICON]ترميز محرك V2 DIP التبديل [SWITCH] [SLOT]السرعة (دورة/دقيقة)",
    "auriga_encoder_motor_V2_angle": "[ICON]مفتاح محرك الترميز V2 DIP[SWITCH] [SLOT] زاوية (°)",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_0": "PM1.0",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_1": "PM2.5",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_2": "PM10",
    "auriga_detect_pm25_sensor": "[ICON] مستشعر جودة الهواء[PORT], [OPTION] (ميكروغرام/م3)",
    "BLOCK_1575275074292_DIRECT_0": "عكس اتجاه عقارب الساعة",
    "BLOCK_1575275074292_DIRECT_1": "عكس عقارب الساعة",
    "BLOCK_1575275074292": "محرك الترميز المعزز [PORT] [DIRECT] تدور بـ [DEGREE]درجات بسرعة[SPEED]دورة/دقيقة",
    "enhanced_encoder_motor_power": "[ICON] محرك ترميز معزز [PORT]تدور بقوة [POWER]%",
    "enhanced_encoder_motor_speed": "[ICON] محرك ترميز معزز [PORT]سرعة الدوران (دورة/دقيقة)",
    "enhanced_encoder_motor_pos": "[ICON]محرك ترميز معزز [PORT]زاوية (درجة)"
};