export default {
    "auriga_all": "Platforma výrobce",
    "extensionName": "Platforma výrobce",
    "extensionDescription": "kolekce rozšíření mBot Ranger",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_PORT_0": "motor na desce port1",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_PORT_1": "motor na desce port2",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_ROTATE_0": "po směru hodinových ručiček",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_ROTATE_1": "proti směru hodinových ručiček",
    "auriga_run_board_encoder_motor": "[ICON] enkodér motoru [PORT] [ROTATE] otáčení s výkonem [POWER]%",
    "auriga_run_board_encoder_motor_speed": "[ICON] enkodér motoru [PORT] [ROTATE] otáčení s rychlostí [POWER] ot./min",
    "auriga_run_board_encoder_motor_pos": "[ICON] enkodér motoru [PORT] [ROTATE] otáčet [DEGREE] stupňů rychlostí [POWER] ot./min",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_0": "port1",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_1": "port2",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_2": "port3",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_3": "port4",
    "AURIGA_RUN_ENCODER_MOTOR_SLOT_0": "slot1",
    "AURIGA_RUN_ENCODER_MOTOR_SLOT_1": "slot 2",
    "AURIGA_RUN_ENCODER_MOTOR_ROTATE_0": "po směru hodinových ručiček",
    "AURIGA_RUN_ENCODER_MOTOR_ROTATE_1": "proti směru hodinových ručiček",
    "auriga_run_encoder_motor": "[ICON] motor enkodéru [PORT] [SLOT] [ROTATE] rotuje [DEGREE] stupňů rychlostí [POWER] ot./min",
    "auriga_encoder_motor_speed": "[ICON] enkodér motoru [PORT] otáčky (ot/min)",
    "auriga_encoder_motor_pos": "[ICON] enkodér motoru [PORT] úhel (°)",
    "auriga_run_motor": "[ICON] stejnosměrný motor [PORT] [ROTATE] otáčení s výkonem [POWER] %",
    "auriga_run_stepper_motor_pos": "[ICON] krokový motor [PORT] [ROTATE] otáčí s vzdáleností [DISTANCE] kroků, rychlostí [POWER] kroků/min",
    "AURIGA_RUN_SERVO_PORT_0": "port6",
    "AURIGA_RUN_SERVO_PORT_1": "port7",
    "AURIGA_RUN_SERVO_PORT_2": "port8",
    "AURIGA_RUN_SERVO_PORT_3": "port9",
    "AURIGA_RUN_SERVO_PORT_4": "port10",
    "auriga_run_servo": "[ICON] servo [PORT] [SLOT] nastavit úhel [DEGREE]",
    "AURIGA_RUN_FAN_FAN_ROTATE_0": "po směru hodinových ručiček",
    "AURIGA_RUN_FAN_FAN_ROTATE_1": "proti směru hodinových ručiček",
    "AURIGA_RUN_FAN_FAN_ROTATE_2": "zastavit",
    "auriga_run_fan": "[ICON] ventrilátor [PORT] [FAN_ROTATE] otáčet",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_0": "stiskni",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_1": "uvolni",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_2": "zaostřit",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_3": "ukončit zaostřování",
    "auriga_run_shutter": "[ICON] Závěrka [PORT] [SHUTTER_ACTION]",
    "auriga_run_smart_servo_to_zero": "[ICON] chytrý servo [INDEX] se otočí do výchozí polohy",
    "auriga_run_smart_servo": "[ICON]smart servo [INDEX] [ROTATE]rotuje rychlostí [POWER]",
    "auriga_run_smart_servo_absolute": "[ICON]chytré servo [INDEX] [ROTATE] rotuje na [POSITION] stupňů rychlostí [POWER]ot./min",
    "auriga_run_smart_servo_to_relative": "[ICON]chytré servo [INDEX] [ROTATE] otočit na [DEGREE] stupňů rychlostí [POWER]ot./min",
    "AURIGA_RUN_SMART_SERVO_RGB_R_0": "0",
    "AURIGA_RUN_SMART_SERVO_RGB_R_1": "20",
    "AURIGA_RUN_SMART_SERVO_RGB_R_2": "60",
    "AURIGA_RUN_SMART_SERVO_RGB_R_3": "150",
    "AURIGA_RUN_SMART_SERVO_RGB_R_4": "255",
    "auriga_run_smart_servo_rgb": "[ICON] nastavit inteligentní servo [INDEX] LED červená [R] zelená [G] modrá [B]",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_0": "současný",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_1": "napětí",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_2": "rychlost",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_3": "úhel",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_4": "teplota",
    "auriga_run_smart_servo_detect": "[ICON] inteligentní servo [INDEX][OPTION]",
    "auriga_show_face_time": "[ICON] LED panel [PORT] zobrazit obrázek [FACE_PANEL] na [TIME] sekund",
    "auriga_show_face": "[ICON] LED panel [PORT] zobrazí obrázek [FACE_PANEL]",
    "auriga_show_face_position": "[ICON] Panel LED [PORT] zobrazí obrázek [FACE_PANEL] na pozici x: [X] Y: [Y]",
    "auriga_show_text": "[ICON] Panel LED [PORT] zobrazuje text [TEXT] ",
    "auriga_show_text_position": "[ICON] Panel LED [PORT] zobrazuje text [TEXT] na pozici x: [X] y: [Y]",
    "auriga_show_number": "[ICON] LED panel [PORT] zobrazí číslo [NUMBER]",
    "auriga_show_time": "[ICON] LED panel [PORT] zobrazí čas [NUMBER1]: [NUMBER2]",
    "auriga_show_face_off": "[ICON] LED panel [PORT] vymazat obrazovku",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "vše",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "auriga_show_external_led_time": "[ICON] RGB LED [PORT] rozsvítit [LED_POSTION] barvou [COLOR] na [TIME] sekund",
    "auriga_show_external_led": "[ICON] RGB LED [PORT] rozsvítit [LED_POSTION] barvou [COLOR]",
    "auriga_show_external_led_rgb": "[ICON] RGB LED [PORT] rozsvítit [LED_POSTION] barvou červená [R], zelená [G], modrá [B]",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "červená",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "oranžová",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "žlutá",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "zelená",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "azurová",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "modrá",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "purpurová",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "černá",
    "auriga_show_all_ledstrip_color": "[ICON] LED pásek [PORT] [SLOT] vše rozsvítit barvou [COLOR_LIST]",
    "auriga_show_ledstrip_color": "[ICON] LED pásek [PORT] [SLOT] [POS]se rozsvítí barvou [COLOR_LIST]",
    "auriga_show_ledstrip_rbg": "[ICON] LED pásek [PORT] [SLOT] [POS] se rozsvítí barvami červená [R], zelená [G] a modrá [B]",
    "auriga_show_7segments_number": "[ICON] sedmisegmentový displej [PORT] zobrazuje číslo [NUMBER]",
    "auriga_detect_external_ultrasonic": "[ICON] ultrazvukový senzor [PORT] vzdálenost",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_0": "port6",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_1": "port7",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_2": "port8",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_3": "port9",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_4": "port10",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_5": "onBoard1",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_6": "onBoard2",
    "auriga_detect_external_light": "[ICON] světelný senzor [PORT] Intenzita světla",
    "auriga_detect_external_loudness": "[ICON] senzor zvuku [PORT] hlasitost",
    "auriga_detect_external_linefollower": "[ICON] senzor sledování čáry [PORT]  hodnota",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "levá strana",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "pravá strana",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "vše",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "nic",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "černá",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "bílá",
    "auriga_event_external_linefollower": "[ICON] Detekuje senzor sledování čáry [PORT] zjistil [LINEFOLLOW_STATE] barvu [BLACK_WHITE]",
    "auriga_detec_temperature": "[ICON] teplotní senzor [PORT] [SLOT] teplota（℃）",
    "AURIGA_DETECT_HUMITURE_TEMP_HUMITURE_0": "vlhkost",
    "AURIGA_DETECT_HUMITURE_TEMP_HUMITURE_1": "teplota",
    "auriga_detect_humiture": "[ICON] senzor pocitové teploty [PORT] [TEMP_HUMITURE]",
    "auriga_event_touch": "[ICON] dotykové čidlo [PORT] je dotyk?",
    "auriga_detect_compass": "[ICON] Elektronický kompas [PORT] směrem na sever",
    "auriga_detect_flame": "[ICON] senzor plamene [PORT] hodnota",
    "auriga_detect_gas": "[ICON]plynový senzor[PORT]  hodnota",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_0": " osa-x",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_1": "osa-y",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_2": "osa-z",
    "auriga_detect_board_gyro_angle": "[ICON] palubní gyroskop [AXIS] úhel",
    "auriga_detect_gyro_angle": "[ICON]gyroskop směrem ven [AXIS] úhel",
    "auriga_event_pir_motion": "[ICON] Senzor PIR [PORT] detekuje lidský pohyb?",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_0": "tlačítko1",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_1": "tlačítko 2",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_2": "tlačítko 3",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_3": "tlačítko 4",
    "auriga_event_button_press": "[ICON]je tlačítko [PORT] [FOUR_KEY] stisknuto?",
    "auriga_event_limit_switch": "[ICON] je omezovací spínač [PORT] [SLOT] stisknut",
    "auriga_detect_potentiometer": "[ICON] potenciometr [PORT] hodnota",
    "AURIGA_DETECT_JOYSTICK_AXIS_X_Y_0": "osa-x",
    "AURIGA_DETECT_JOYSTICK_AXIS_X_Y_1": "osa-y",
    "auriga_detect_joystick": "[ICON] joystick [PORT] [AXIS_X_Y] hodnota",
    "auriga_detect_infrared": "[ICON] IR příjímač [PORT] ",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_0": "NNN",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_1": "NNV",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_2": "NVN",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_3": "NVV",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_4": "VNN",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_5": "VNV",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_6": "VVN",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_7": "VVV",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SLOT_0": "motor port1",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SLOT_1": "motor port2",
    "auriga_encoder_motor_V2_motor": "[ICON] nastavit motor enkodéru V2 DIP přepínač [SWITCH] [SLOT] na [POWER]%",
    "auriga_encoder_motor_V2_speed": "[ICON] nastavit motor enkodéru V2 DIP přepínač [SWITCH] [SLOT] na [SPEED]ot./min",
    "auriga_encoder_motor_V2_pos": "[ICON] nastavit přepínač V2 DIP motoru [SWITCH] [SLOT] na otáčení o [DEGREE]stupňů rychlostí [SPEED]ot./min",
    "auriga_encoder_motor_V2_minute": "[ICON] nastavit motor enkodéru V2 DIP přepínač [SWITCH] [SLOT] rychlost (ot./min)",
    "auriga_encoder_motor_V2_angle": "[ICON]enkodér motoru V2 DIP spínač[SWITCH] [SLOT] úhel (°)",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_0": "PM1.0",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_1": "PM2.5",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_2": "PM10",
    "auriga_detect_pm25_sensor": "[ICON] senzor kvality ovzduší[PORT], [OPTION] (μg/m³)",
    "BLOCK_1575275074292_DIRECT_0": "po směru hodinových ručiček",
    "BLOCK_1575275074292_DIRECT_1": "proti směru hodinových ručiček",
    "BLOCK_1575275074292": "encodér motoru [PORT] [DIRECT] se otáčí o [DEGREE] stupňů rycholstí [SPEED] r/min",
    "enhanced_encoder_motor_power": "[ICON] krokový motor [PORT] se otáčí s výkonem [POWER]%",
    "enhanced_encoder_motor_speed": "[ICON] enkodér motoru [PORT] otáčky (ot/min)",
    "enhanced_encoder_motor_pos": "[ICON]krokový motor [PORT] úhel (°)"
};