export default {
    "auriga_all": "メイカープラットフォーム",
    "extensionName": "メイカープラットフォーム",
    "extensionDescription": "mBot Ranger 拡張機能のコレクション",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_PORT_0": "ボード上のモーターポート1",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_PORT_1": "ボード上のモーターポート2",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_ROTATE_0": "時計回り",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_ROTATE_1": "反時計回り",
    "auriga_run_board_encoder_motor": "[ICON]エンコーダーモーター [PORT] [ROTATE] を[POWER] %の速さで回転する",
    "auriga_run_board_encoder_motor_speed": "[ICON]エンコーダー モーター [PORT] [ROTATE] を[POWER] r/minの速さで回転する",
    "auriga_run_board_encoder_motor_pos": "[ICON]エンコーダーモーター[PORT] [ROTATE] を[DEGREE] 角度と[POWER] r/minの速さで回転する",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_0": "ポート1",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_1": "ポート2",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_2": "ポート3",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_3": "ポート4",
    "AURIGA_RUN_ENCODER_MOTOR_SLOT_0": "スロット1",
    "AURIGA_RUN_ENCODER_MOTOR_SLOT_1": "スロット2",
    "AURIGA_RUN_ENCODER_MOTOR_ROTATE_0": "時計回り",
    "AURIGA_RUN_ENCODER_MOTOR_ROTATE_1": "反時計回り",
    "auriga_run_encoder_motor": "[ICON] エンコーダーモーター[PORT] [SLOT][ROTATE] を[DEGREE] の角度と[POWER] r/minの速さで回転する",
    "auriga_encoder_motor_speed": "[ICON] エンコーダーモーター [PORT] の回転速度(回転/分)",
    "auriga_encoder_motor_pos": "[ICON] エンコーダーモーター [PORT] の角度(°）",
    "auriga_run_motor": "[ICON] DCモーター [PORT] の速さを[POWER] %で[ROTATE] にする",
    "auriga_run_stepper_motor_pos": "[ICON]ステッピング モーター[PORT] [ROTATE] を [DISTANCE] 距離で、[POWER] stp/minの速さで回転する",
    "AURIGA_RUN_SERVO_PORT_0": "ポート6",
    "AURIGA_RUN_SERVO_PORT_1": "ポート7",
    "AURIGA_RUN_SERVO_PORT_2": "ポート8",
    "AURIGA_RUN_SERVO_PORT_3": "ポート9",
    "AURIGA_RUN_SERVO_PORT_4": "ポート10",
    "auriga_run_servo": "[ICON] サーボ[PORT] の[SLOT] の角度を[DEGREE] にする",
    "AURIGA_RUN_FAN_FAN_ROTATE_0": "時計回り",
    "AURIGA_RUN_FAN_FAN_ROTATE_1": "反時計回り",
    "AURIGA_RUN_FAN_FAN_ROTATE_2": "を止める",
    "auriga_run_fan": "[ICON] ファン [PORT] を[FAN_ROTATE] にする",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_0": "押す",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_1": "離す",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_2": "フォーカス",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_3": "フォーカスオフ",
    "auriga_run_shutter": "[ICON]カメラのシャッター [PORT] を[SHUTTER_ACTION]",
    "auriga_run_smart_servo_to_zero": "[ICON]スマート サーボ [INDEX] を開始位置に回転する",
    "auriga_run_smart_servo": "[ICON]スマート サーボ [INDEX] [ROTATE] を [POWER]の速さで回転する",
    "auriga_run_smart_servo_absolute": "[ICON]スマートサーボ [INDEX] [ROTATE] を [POSITION]の角度と[POWER]r/minの速さで回転する",
    "auriga_run_smart_servo_to_relative": "[ICON]スマート サーボ [INDEX] [ROTATE] を [DEGREE] の角度と [POWER]r/minの速さで回転する",
    "AURIGA_RUN_SMART_SERVO_RGB_R_0": "0",
    "AURIGA_RUN_SMART_SERVO_RGB_R_1": "20",
    "AURIGA_RUN_SMART_SERVO_RGB_R_2": "60",
    "AURIGA_RUN_SMART_SERVO_RGB_R_3": "150",
    "AURIGA_RUN_SMART_SERVO_RGB_R_4": "255",
    "auriga_run_smart_servo_rgb": "[ICON] スマートサーボの設定 [INDEX] LED 赤 [R] 緑 [G] 青 [B]",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_0": "電流",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_1": "電圧",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_2": "速さ",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_3": "角度",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_4": "温度",
    "auriga_run_smart_servo_detect": "[ICON] スマートサーボ [INDEX][OPTION]",
    "auriga_show_face_time": "[ICON]LEDパネル[PORT] に画像 [FACE_PANEL] を[TIME] 秒表示する",
    "auriga_show_face": "[ICON]LEDパネル[PORT] に画像[FACE_PANEL] を表示する",
    "auriga_show_face_position": "[ICON] LEDパネル[PORT] のx: [X] y: [Y] に画像[FACE_PANEL] を表示する",
    "auriga_show_text": "[ICON] LEDパネル[PORT] にテキスト[TEXT] を表示する ",
    "auriga_show_text_position": "[ICON] LEDパネル[PORT] のx: [X] y: [Y] にテキスト [TEXT] を表示する",
    "auriga_show_number": "[ICON] LEDパネル[PORT] に番号[NUMBER] を表示する",
    "auriga_show_time": "[ICON] LEDパネル[PORT] に時間[NUMBER1]：[NUMBER2] を表示する",
    "auriga_show_face_off": "[ICON]LED パネル [PORT] の画面をクリアする",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "全て",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "auriga_show_external_led_time": "[ICON]RGB LED [PORT] の[LED_POSTION] に[COLOR] 色を[TIME] 秒点灯する",
    "auriga_show_external_led": "[ICON]RGB LED [PORT] の[LED_POSTION] を[COLOR] 色で点灯する",
    "auriga_show_external_led_rgb": "[ICON] RGB LED [PORT] の[LED_POSTION] を赤 [R] 緑[G] 青 [B] で点灯する",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "赤",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "オレンジ",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "黄",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "緑",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "シアン",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "青",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "紫",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "黒",
    "auriga_show_all_ledstrip_color": "[ICON]LED ストリップ[PORT] の[SLOT] を[COLOR_LIST] 色で点灯する",
    "auriga_show_ledstrip_color": "[ICON] LED ストリップ[PORT] の[SLOT] の[POS] 番目を[COLOR_LIST] 色で点灯する",
    "auriga_show_ledstrip_rbg": "[ICON] LED ストリップ[PORT] の[SLOT] の[POS] 番目を赤 [R] 緑 [G] 青 [B] で点灯する",
    "auriga_show_7segments_number": "[ICON] 7セグメントディスプレイ[PORT] に[NUMBER] を表示する",
    "auriga_detect_external_ultrasonic": " [ICON]超音波センサー[PORT]の距離",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_0": "ポート6",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_1": "ポート7",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_2": "ポート8",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_3": "ポート9",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_4": "ポート10",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_5": "ボード1",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_6": "ボード2",
    "auriga_detect_external_light": "[ICON] 光センサー [PORT] の値",
    "auriga_detect_external_loudness": "[ICON]音声センサー [PORT] 値",
    "auriga_detect_external_linefollower": "[ICON] ライントレースセンサー [PORT] の値",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "左側",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "右側",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "全て",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "なし",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "黒",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "白",
    "auriga_event_external_linefollower": "[ICON] ライントレースセンサー [PORT] が[BLACK_WHITE] を[LINEFOLLOW_STATE]",
    "auriga_detec_temperature": "[ICON] 温度センサー[PORT] の[SLOT] の値 (℃)",
    "AURIGA_DETECT_HUMITURE_TEMP_HUMITURE_0": "湿度",
    "AURIGA_DETECT_HUMITURE_TEMP_HUMITURE_1": "温度",
    "auriga_detect_humiture": "[ICON]温湿度センサー[PORT] [TEMP_HUMITURE]",
    "auriga_event_touch": "[ICON]タッチセンサー [PORT]",
    "auriga_detect_compass": "[ICON] 電子コンパス [PORT] の値",
    "auriga_detect_flame": "[ICON] 火炎センサー [PORT] の値",
    "auriga_detect_gas": "[ICON]ガスセンサー [PORT] の値",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_0": " x軸",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_1": "y軸",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_2": "z軸",
    "auriga_detect_board_gyro_angle": "[ICON]ジャイロオンボード[AXIS] の角度",
    "auriga_detect_gyro_angle": "[ICON]ジャイロスコープ[AXIS] の角度",
    "auriga_event_pir_motion": "[ICON] PIRモーションセンサー[PORT]",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_0": "KEY1",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_1": "KEY2",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_2": "KEY3",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_3": "KEY4\n",
    "auriga_event_button_press": "[ICON] [PORT] の[FOUR_KEY] ボタンが押された",
    "auriga_event_limit_switch": "[ICON]リミットスイッチ[PORT] の[SLOT]",
    "auriga_detect_potentiometer": "[ICON]ポテンショメータ [PORT] の値を表示する",
    "AURIGA_DETECT_JOYSTICK_AXIS_X_Y_0": "x軸",
    "AURIGA_DETECT_JOYSTICK_AXIS_X_Y_1": "y軸",
    "auriga_detect_joystick": "[ICON] ジョイスティック[PORT]の[AXIS_X_Y] の値",
    "auriga_detect_infrared": "[ICON] 赤外線レシーバー [PORT] の値 ",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_0": "LLL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_1": "LLH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_2": "LHL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_3": "LHH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_4": "HLL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_5": "HLH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_6": "HHL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_7": "HHH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SLOT_0": "モーター ポート1",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SLOT_1": "モーター ポート2",
    "auriga_encoder_motor_V2_motor": "[ICON]エンコーダーモーターV2 DIPスイッチ[SWITCH] [SLOT]の電力を[POWER]％に設定する",
    "auriga_encoder_motor_V2_speed": "[ICON]エンコーダーモーターV2 DIPスイッチ[SWITCH] [SLOT]の速度を[SPEED]回転/分に設定する",
    "auriga_encoder_motor_V2_pos": "[ICON]エンコーダーモーターV2 DIPスイッチ[SWITCH] [SLOT]が[SPEED] 回転/分の速度で[DEGREE]度回転するように設定する",
    "auriga_encoder_motor_V2_minute": "[ICON]エンコーダーモーターV2 DIPスイッチ[SWITCH] [SLOT]の速度 (回転/分)",
    "auriga_encoder_motor_V2_angle": "[ICON]エンコーダーモーターV2 DIPスイッチ[SWITCH] [SLOT]の角度 (°)",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_0": "PM1.0",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_1": "PM2.5",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_2": "PM10",
    "auriga_detect_pm25_sensor": "[ICON] 空気品質センサー[PORT], [OPTION] (μg/m³)",
    "BLOCK_1575275074292_DIRECT_0": "時計回り",
    "BLOCK_1575275074292_DIRECT_1": "反時計回り",
    "BLOCK_1575275074292": "強化型エンコーダーモーター[PORT]  [DIRECT] を[DEGREE] の角度と[POWER] 回転/分の速さで回転する",
    "enhanced_encoder_motor_power": "[ICON] 強化型エンコーダモーター[PORT] の速さを [POWER]%で回転する",
    "enhanced_encoder_motor_speed": "[ICON] 強化型エンコーダモーター [PORT]の回転速度(回転/分)",
    "enhanced_encoder_motor_pos": "[ICON]強化型エンコーダモーター [PORT]の角度 (°）"
};