export default {
    "auriga_all": "វេទិការបស់អ្នកផលិត",
    "extensionName": "វេទិការបស់អ្នកផលិត",
    "extensionDescription": "បណ្ដុំនៃកម្មវិធីបន្ថែមរបស់ mBot Ranger",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_PORT_0": "ម៉ូទ័រនៅលើក្តារបញ្ជា ច្រក១",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_PORT_1": "ម៉ូទ័រនៅលើក្តារបញ្ជា ច្រក២",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_ROTATE_0": "ស្រប​ទិស​ទ្រនិច​នាឡិកា",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_ROTATE_1": "បញ្ច្រាសទិស​ទ្រនិច​នាឡិកា",
    "auriga_run_board_encoder_motor": "[ICON] ម៉ូទ័រអ៊ិនកូដឌ័រ [PORT] [ROTATE] វិលនៅថាមពល [POWER]%",
    "auriga_run_board_encoder_motor_speed": "[ICON] ម៉ូទ័រអ៊ិនកូដឌ័រ [PORT] [ROTATE] វិលនៅល្បឿន [POWER] ជុំ/នាទី",
    "auriga_run_board_encoder_motor_pos": "[ICON] ម៉ូទ័រអ៊ិនកូដឌ័រ [PORT] [ROTATE] វិលត្រឹម [DEGREE] ដឺក្រេ នៅល្បឿន [POWER] ជុំ/នាទី",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_0": "ច្រក១",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_1": "ច្រក២",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_2": "ច្រក៣",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_3": "ច្រក៤",
    "AURIGA_RUN_ENCODER_MOTOR_SLOT_0": "រន្ធដោត១",
    "AURIGA_RUN_ENCODER_MOTOR_SLOT_1": "រន្ធដោត២",
    "AURIGA_RUN_ENCODER_MOTOR_ROTATE_0": "ស្រប​ទិស​ទ្រនិច​នាឡិកា",
    "AURIGA_RUN_ENCODER_MOTOR_ROTATE_1": "បញ្ច្រាសទិស​ទ្រនិច​នាឡិកា",
    "auriga_run_encoder_motor": "[ICON] ម៉ូទ័រអ៊ិនកូដឌ័រ [PORT] [SLOT] [ROTATE] វិលត្រឹម [DEGREE] ដឺក្រេ នៅល្បឿន [POWER] ជុំ/នាទី",
    "auriga_encoder_motor_speed": "[ICON] ម៉ូទ័រអ៊ិនកូដឌ័រ [PORT] ល្បឿនបង្វិល (ជុំ/នាទី)",
    "auriga_encoder_motor_pos": "[ICON] ម៉ូទ័រអ៊ិនកូដឌ័រ [PORT] មុំ (°)",
    "auriga_run_motor": "[ICON] ម៉ូទ័រ DC [PORT] [ROTATE] វិលនៅថាមពល [POWER] %",
    "auriga_run_stepper_motor_pos": "[ICON] ម៉ូទ័រជំហាន [PORT] [ROTATE] វិលជាមួយចម្ងាយ [DISTANCE] ជំហាន, នៅល្បឿន [POWER] ជំហាន/នាទី",
    "AURIGA_RUN_SERVO_PORT_0": "ច្រក៦",
    "AURIGA_RUN_SERVO_PORT_1": "ច្រក៧",
    "AURIGA_RUN_SERVO_PORT_2": "ច្រក៨",
    "AURIGA_RUN_SERVO_PORT_3": "ច្រក៩",
    "AURIGA_RUN_SERVO_PORT_4": "ច្រក១០",
    "auriga_run_servo": "[ICON] ស៊ែរវូ [PORT] [SLOT] ទីតាំងនៅមុំ [DEGREE]",
    "AURIGA_RUN_FAN_FAN_ROTATE_0": "ស្រប​ទិស​ទ្រនិច​នាឡិកា",
    "AURIGA_RUN_FAN_FAN_ROTATE_1": "បញ្ច្រាសទិស​ទ្រនិច​នាឡិកា",
    "AURIGA_RUN_FAN_FAN_ROTATE_2": "បញ្ឈប់",
    "auriga_run_fan": "[ICON] កង្ហារ [PORT] [FAN_ROTATE] វិល",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_0": "ចុច",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_1": "ព្រលែង",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_2": "ផ្តោត",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_3": "បញ្ឈប់ការផ្តោត",
    "auriga_run_shutter": "[ICON] ចាប់យករូបភាព [PORT] [SHUTTER_ACTION]",
    "auriga_run_smart_servo_to_zero": "[ICON] ស៊ែរវូឆ្លាត [INDEX] វិលទៅទីតាំងចាប់ផ្ដើម",
    "auriga_run_smart_servo": "[ICON] ស៊ែរវូឆ្លាត [INDEX] [ROTATE] វិលនៅល្បឿន [POWER]",
    "auriga_run_smart_servo_absolute": "[ICON] ស៊ែរវូឆ្លាត [INDEX] [ROTATE] វិលទៅ [POSITION] ដឺក្រេ នៅល្បឿន [POWER] ជុំ/នាទី",
    "auriga_run_smart_servo_to_relative": "[ICON] ស៊ែរវូឆ្លាត [INDEX] [ROTATE] វិលត្រឹម [DEGREE] ដឺក្រេ នៅល្បឿន [POWER] ជុំ/នាទី",
    "AURIGA_RUN_SMART_SERVO_RGB_R_0": "0",
    "AURIGA_RUN_SMART_SERVO_RGB_R_1": "២០",
    "AURIGA_RUN_SMART_SERVO_RGB_R_2": "៦០",
    "AURIGA_RUN_SMART_SERVO_RGB_R_3": "១៥០",
    "AURIGA_RUN_SMART_SERVO_RGB_R_4": "២៥៥",
    "auriga_run_smart_servo_rgb": "[ICON] ដាក់ស៊ែរវូឆ្លាត [INDEX] អំពូល LED ពណ៌ក្រហម [R]​ បៃតង [G] ខៀវ [B]",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_0": "ចរន្ត",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_1": "តង់ស្យុង",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_2": "ល្បឿន",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_3": "មុំ",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_4": "សីតុណ្ហភាព",
    "auriga_run_smart_servo_detect": "[ICON] ស៊ែរវូឆ្លាត [INDEX][OPTION]",
    "auriga_show_face_time": "[ICON] អំពូលបន្ទះ LED [PORT] បង្ហាញរូបភាព [FACE_PANEL] សម្រាប់ [TIME] វិនាទី",
    "auriga_show_face": "[ICON] អំពូលបន្ទះ LED [PORT] បង្ហាញរូបភាព [FACE_PANEL]",
    "auriga_show_face_position": "[ICON] អំពូលបន្ទះ LED [PORT] បង្ហាញរូបភាព [FACE_PANEL] នៅទីតាំង x: [X] y: [Y]",
    "auriga_show_text": "[ICON] អំពូលបន្ទះ LED [PORT] បង្ហាញអត្ថបទ [TEXT] ",
    "auriga_show_text_position": "[ICON] អំពូលបន្ទះ LED [PORT] បង្ហាញអត្ថបទ [TEXT] នៅទីតាំង x: [X] y: [Y]",
    "auriga_show_number": "[ICON] អំពូលបន្ទះ LED [PORT] បង្ហាញលេខ [NUMBER]",
    "auriga_show_time": "[ICON] អំពូលបន្ទះ LED [PORT] បង្ហាញពេលវេលា [NUMBER1]：[NUMBER2]",
    "auriga_show_face_off": "[ICON] អំពូលបន្ទះ LED [PORT] លុបអេក្រង់",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "ទាំងអស់",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "១",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "២",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "៣",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "៤",
    "auriga_show_external_led_time": "[ICON] អំពូល RGB LED [PORT] ភ្លឺ [LED_POSTION] ជាមួយពណ៌ [COLOR] សម្រាប់ [TIME] វិនាទី",
    "auriga_show_external_led": "[ICON] អំពូល RGB LED [PORT] ភ្លឺ [LED_POSTION] ជាមួយពណ៌ [COLOR]",
    "auriga_show_external_led_rgb": "[ICON] អំពូល RGB LED [PORT] ភ្លឺ [LED_POSTION] ជាមួយពណ៌ក្រហម [R] បៃតង [G] ខៀវ [B]",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "ពណ៌ក្រហម",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "ពណ៌ទឹកក្រូច",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "ពណ៌លឿង",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "ពណ៌បៃតង",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "ពណ៌ផ្ទៃមេឃ",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "ពណ៌ខៀវ",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "ពណ៌ស្វាយ",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "ពណ៌ខ្មៅ",
    "auriga_show_all_ledstrip_color": "[ICON] បន្ទះអំពូល LED [PORT] [SLOT] ភ្លឺទាំងអស់ជាមួយពណ៌ [COLOR_LIST]",
    "auriga_show_ledstrip_color": "[ICON] អំពូលបន្ទះ LED [PORT][SLOT][POS] ភ្លឺទាំងអស់ជាមួយពណ៌ [COLOR_LIST]",
    "auriga_show_ledstrip_rbg": "[ICON] អំពូលបន្ទះ LED [PORT][SLOT][POS] ភ្លឺជាមួយពណ៌ក្រហម [R] បៃតង [G] ខៀវ [B]",
    "auriga_show_7segments_number": "[ICON] អំពូល seven-segments [PORT] បង្ហាញលេខ [NUMBER]",
    "auriga_detect_external_ultrasonic": "[ICON] ឧបករណ៍វាស់ចម្ងាយប្រើសំឡេងអ៊ុលត្រា [PORT] ចម្ងាយ",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_0": "ច្រក៦",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_1": "ច្រក៧",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_2": "ច្រក៨",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_3": "ច្រក៩",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_4": "ច្រក១០",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_5": "onboard1",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_6": "onboard2",
    "auriga_detect_external_light": "[ICON] ឧបករណ៍ចាប់ពន្លឺ [PORT] អាំងដង់ស៊ីតេពន្លឺ",
    "auriga_detect_external_loudness": "[ICON] ឧបករណ៍ចាប់សំឡេង [PORT] កម្រិតសំឡេង",
    "auriga_detect_external_linefollower": "[ICON] ឧបករណ៍តាមដានខ្សែបន្ទាត់ [PORT] តម្លៃ",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "ផ្នែកខាងឆ្វេង",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "ផ្នែក​ខាងស្តាំ",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "ទាំងអស់",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "គ្មាន",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "ពណ៌ខ្មៅ",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "ពណ៌ស",
    "auriga_event_external_linefollower": "[ICON] ឧបករណ៍តាមដានខ្សែបន្ទាត់ [PORT] រកឃើញ [LINEFOLLOW_STATE] មានពណ៌​ [BLACK_WHITE]？",
    "auriga_detec_temperature": "[ICON] ឧបករណ៍វាស់សីតុណ្ហភាព [PORT][SLOT] សីតុណ្ហភាព（℃）",
    "AURIGA_DETECT_HUMITURE_TEMP_HUMITURE_0": "សំណើម",
    "AURIGA_DETECT_HUMITURE_TEMP_HUMITURE_1": "សីតុណ្ហភាព",
    "auriga_detect_humiture": "[ICON] ឧបករណ៍វាស់សំណើមនិងសីតុណ្ហភាព [PORT]​ [TEMP_HUMITURE]",
    "auriga_event_touch": "[ICON] ឧបករណ៍ចាប់សញ្ញាការ​ប៉ះ​ [PORT]​ ត្រូវបានប៉ះ?",
    "auriga_detect_compass": "[ICON] ត្រីវិស័យអេឡិចត្រូនិច [PORT] តម្រង់ទៅទិសខាងជើង",
    "auriga_detect_flame": "[ICON] ឧបករណ៍ចាប់សញ្ញាអណ្ដាតភ្លើង [PORT] តម្លៃ",
    "auriga_detect_gas": "[ICON] ឧបករណ៍ចាប់ផ្សែង [PORT] តម្លៃ",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_0": " អ័ក្ស x",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_1": "អ័ក្ស y",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_2": "អ័ក្ស z",
    "auriga_detect_board_gyro_angle": "[ICON] បន្ទះបញ្ជា gyro [AXIS] មុំ",
    "auriga_detect_gyro_angle": "[ICON] gyroscope ខាងក្រៅ [AXIS] មុំ",
    "auriga_event_pir_motion": "[ICON] ឧបករណ៍ចាប់ចលនា PIR [PORT] រកឃើញចលនារបស់មនុស្ស？",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_0": "ប៊ូតុង១",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_1": "ប៊ូតុង២",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_2": "ប៊ូតុង៣",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_3": "ប៊ូតុង៤",
    "auriga_event_button_press": "[ICON] ប៊ូតុង [PORT] [FOUR_KEY] ត្រូវបានចុច?",
    "auriga_event_limit_switch": "[ICON] កុងតាក់ដែនកំណត់ [PORT] [SLOT] ត្រូវបានចុច?",
    "auriga_detect_potentiometer": "[ICON] ប៉ូតង់ស្យូមម៉ែត្រមួល​ ​[PORT] តម្លៃ",
    "AURIGA_DETECT_JOYSTICK_AXIS_X_Y_0": "អ័ក្ស x",
    "AURIGA_DETECT_JOYSTICK_AXIS_X_Y_1": "អ័ក្ស y",
    "auriga_detect_joystick": "[ICON] joystick [PORT] [AXIS_X_Y] តម្លៃ",
    "auriga_detect_infrared": "[ICON] ឧបករណ៍ទទួលពន្លឺអាំងហ្វ្រាក្រហម [PORT] ",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_0": "LLL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_1": "LLH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_2": "LHL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_3": "LHH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_4": "HLL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_5": "HLH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_6": "HHL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_7": "HHH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SLOT_0": "ម៉ូទ័រច្រក១",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SLOT_1": "ម៉ូទ័រច្រក២",
    "auriga_encoder_motor_V2_motor": "[ICON] ដាក់ម៉ូទ័រអ៊ិនកូដឌ័រ V2 កុងតាក់ DIP [SWITCH] [SLOT] ថាមពល [POWER]%",
    "auriga_encoder_motor_V2_speed": "[ICON] ម៉ូទ័រអ៊ិនកូដឌ័រ V2 កុងតាក់ DIP [SWITCH] [SLOT] ល្បឿន [SPEED] ជុំ/នាទី",
    "auriga_encoder_motor_V2_pos": "[ICON] ដាក់ម៉ូទ័រអ៊ិនកូដឌ័រ V2 កុងតាក់ DIP [SWITCH] [SLOT] វិលត្រឹម [DEGREE] ដឺក្រេ នៅល្បឿន [SPEED] ជុំ/នាទី",
    "auriga_encoder_motor_V2_minute": "[ICON] ម៉ូទ័រអ៊ិនកូដឌ័រ V2 កុងតាក់ DIP [SWITCH] [SLOT] ល្បឿន (ជុំ/នាទី)",
    "auriga_encoder_motor_V2_angle": "[ICON] ម៉ូទ័រអ៊ិនកូដឌ័រ V2 កុងតាក់ DIP [SWITCH] [SLOT] មុំ (°)",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_0": "PM1.0",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_1": "PM2.5",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_2": "PM10",
    "auriga_detect_pm25_sensor": "[ICON] ឧបករណ៍វាស់គុណភាពខ្យល់ [PORT], [OPTION] (μg/m³)",
    "BLOCK_1575275074292_DIRECT_0": "ស្រប​ទិស​ទ្រនិច​នាឡិកា",
    "BLOCK_1575275074292_DIRECT_1": "បញ្ច្រាសទិស​ទ្រនិច​នាឡិកា",
    "BLOCK_1575275074292": "ម៉ូទ័រអ៊ិនកូដឌ័រដែលប្រសើរឡើង [PORT] [DIRECT] វិលត្រឹម [DEGREE] ដឺក្រេ នៅល្បឿន [SPEED] ជុំ/នាទី",
    "enhanced_encoder_motor_power": "[ICON] ម៉ូទ័រអ៊ិនកូដឌ័រដែលប្រសើរឡើង [PORT] វិលនៅថាមពល [POWER]%",
    "enhanced_encoder_motor_speed": "[ICON] ម៉ូទ័រអ៊ិនកូដឌ័រដែលប្រសើរឡើង [PORT] ល្បឿនបង្វិល (ជុំ/នាទី)",
    "enhanced_encoder_motor_pos": "[ICON] ម៉ូទ័រអ៊ិនកូដឌ័រដែលប្រសើរឡើង [PORT] មុំ (°）"
};