export default {
    "auriga_all": "Мейкерська платформа",
    "extensionName": "Мейкерська платформа",
    "extensionDescription": "Колекція розширень для mBot Ranger",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_PORT_0": "мотор на платі порт 1",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_PORT_1": "мотор на платі порт 2",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_ROTATE_0": "за годинниковою стрілкою",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_ROTATE_1": "проти годинникової стрілки",
    "auriga_run_board_encoder_motor": "[ICON]енкодерний мотор [PORT] [ROTATE] поворот при владі[POWER]%",
    "auriga_run_board_encoder_motor_speed": "[ICON]енкодерний мотор [PORT] [ROTATE] обертається зі швидкістю [POWER] об/хв",
    "auriga_run_board_encoder_motor_pos": "[ICON]енкодерний мотор [PORT] [ROTATE] обертає на [DEGREE] ступінь у швидкості[POWER] об/хв",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_0": "порт 1",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_1": "порт 2",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_2": "порт 3",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_3": "порт 4",
    "AURIGA_RUN_ENCODER_MOTOR_SLOT_0": "роз'єм 1",
    "AURIGA_RUN_ENCODER_MOTOR_SLOT_1": "роз'єм 2",
    "AURIGA_RUN_ENCODER_MOTOR_ROTATE_0": "за годинниковою стрілкою",
    "AURIGA_RUN_ENCODER_MOTOR_ROTATE_1": "проти годинникової стрілки",
    "auriga_run_encoder_motor": "[ICON] енкодерний мотор [PORT] [SLOT] [ROTATE] обертає на [DEGREE] ступінь у швидкості [POWER] об/хв",
    "auriga_encoder_motor_speed": "[ICON] мотор з енкодером [PORT] швидкість обертання (об/хв)",
    "auriga_encoder_motor_pos": "[ICON] мотор з енкодером [PORT] кут(°）",
    "auriga_run_motor": "[ICON]Мотор постійного струму [PORT] обертати [ROTATE] зі швидкістю [POWER] %",
    "auriga_run_stepper_motor_pos": "[ICON] крокового двигуна [PORT] [ROTATE] обертає на відстані [DISTANCE] кроків, на швидкості [POWER] StP/хв",
    "AURIGA_RUN_SERVO_PORT_0": "порт 6",
    "AURIGA_RUN_SERVO_PORT_1": "порт 7",
    "AURIGA_RUN_SERVO_PORT_2": "порт 8",
    "AURIGA_RUN_SERVO_PORT_3": "порт 9",
    "AURIGA_RUN_SERVO_PORT_4": "порт 10",
    "auriga_run_servo": "[ICON] серво [PORT] [SLOT] стати під кутом [DEGREE] градусів",
    "AURIGA_RUN_FAN_FAN_ROTATE_0": "за годинниковою стрілкою",
    "AURIGA_RUN_FAN_FAN_ROTATE_1": "проти годинникової стрілки",
    "AURIGA_RUN_FAN_FAN_ROTATE_2": "зупинити",
    "auriga_run_fan": "[ICON] вентилятор [PORT] [FAN_ROTATE] обертів",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_0": "натиснуто",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_1": "відпущено",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_2": "фокусувати",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_3": "зупинити фокусування",
    "auriga_run_shutter": "[ICON] затвор [PORT] [SHUTTER_ACTION]",
    "auriga_run_smart_servo_to_zero": "[ICON] смарт-сервопривод [INDEX] поворот до початкової позиції",
    "auriga_run_smart_servo": "[ICON]смарт-сервопривод [INDEX] [ROTATE]обертається зі швидкістю [POWER]",
    "auriga_run_smart_servo_absolute": "[ICON]смарт-сервопривод [INDEX] [ROTATE] повертається до [POSITION] ступінь у швидкості [POWER]об/хв",
    "auriga_run_smart_servo_to_relative": "[ICON] смарт сервопривід [INDEX] [ROTATE] обертатися до [DEGREE] градусів зі швидкістю [POWER]об/хв",
    "AURIGA_RUN_SMART_SERVO_RGB_R_0": "0",
    "AURIGA_RUN_SMART_SERVO_RGB_R_1": "20",
    "AURIGA_RUN_SMART_SERVO_RGB_R_2": "60",
    "AURIGA_RUN_SMART_SERVO_RGB_R_3": "150",
    "AURIGA_RUN_SMART_SERVO_RGB_R_4": "255",
    "auriga_run_smart_servo_rgb": "[ICON] смарт серво [INDEX] LED червоний [R] зелений [G] синій [B]",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_0": "струм",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_1": "напруга",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_2": "швидкість",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_3": "кут",
    "AURIGA_RUN_SMART_SERVO_DETECT_OPTION_4": "температура",
    "auriga_run_smart_servo_detect": "[ICON] смарт серво [INDEX][OPTION]",
    "auriga_show_face_time": "[ICON]СВІТЛОДІОДНА панель [PORT] показує зображення[FACE_PANEL] Для[TIME] Сек",
    "auriga_show_face": "[ICON] LED панель [PORT] зображення[FACE_PANEL]",
    "auriga_show_face_position": "[ICON] LED панель [PORT] зображення [FACE_PANEL], зміщене по осі x: [X] y: [Y]",
    "auriga_show_text": "[ICON] СВІТЛОДІОДНА панель [PORT] показує текст [TEXT] ",
    "auriga_show_text_position": "[ICON] СВІТЛОДІОДНА панель[PORT] показує текст [TEXT] на x: [X] Y: [Y]",
    "auriga_show_number": "[ICON] LED панель [PORT] число [NUMBER]",
    "auriga_show_time": "[ICON] LED панель [PORT] час [NUMBER1]:[NUMBER2]",
    "auriga_show_face_off": "[ICON] LED панель [PORT] очистити екран",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "всі",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "auriga_show_external_led_time": "[ICON] LED стрічка [PORT] увімкнути світлодіод [LED_POSTION] колір [COLOR] на [TIME] сек",
    "auriga_show_external_led": "[ICON] LED стрічка [PORT] увімкнути світлодіод [LED_POSTION] колір [COLOR]",
    "auriga_show_external_led_rgb": "[ICON] LED стрічка [PORT] увімкнути світлодіод [LED_POSTION] колір червоний [R] зелений [G] синій [B]",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "червоний",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "помаранчевий",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "жовтий",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "зелений",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "блакитний",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "синій",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "фіолетовий",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "чорний",
    "auriga_show_all_ledstrip_color": "[ICON]СВІТЛОДІОДНА смуга [PORT] [SLOT] все горить з кольором [COLOR_LIST]",
    "auriga_show_ledstrip_color": "[ICON]СВІТЛОДІОДНА смуга [PORT] [SLOT] [POS] загоряється за кольором [COLOR_LIST]",
    "auriga_show_ledstrip_rbg": "[ICON] СВІТЛОДІОДНА смуга [PORT] [SLOT] [POS] загоряється червоним кольором [R] Зелений [G] Синій [B]",
    "auriga_show_7segments_number": "[ICON] 7-сегментний дисплей [PORT] вивести число [NUMBER]",
    "auriga_detect_external_ultrasonic": "[ICON] відстань ультразвукового датчика [PORT] см",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_0": "порт 6",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_1": "порт 7",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_2": "порт 8",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_3": "порт 9",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_4": "порт 10",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_5": "на платі 1",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_6": "на платі 2",
    "auriga_detect_external_light": "[ICON] датчик освітленості[PORT] інтенсивність світла",
    "auriga_detect_external_loudness": "[ICON] гучність датчика звуку [PORT]",
    "auriga_detect_external_linefollower": "[ICON] лінія послідовника сенсор [PORT]  Значення",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "ліва сторона",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "права сторона",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "всі",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "нічого",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "чорний",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "білий",
    "auriga_event_external_linefollower": "[ICON] датчик слідування за лінією [PORT] виявив [LINEFOLLOW_STATE], будучи на [BLACK_WHITE]",
    "auriga_detec_temperature": "[ICON] термометр [PORT] [SLOT] температура (℃)",
    "AURIGA_DETECT_HUMITURE_TEMP_HUMITURE_0": "вологість",
    "AURIGA_DETECT_HUMITURE_TEMP_HUMITURE_1": "температура",
    "auriga_detect_humiture": "[ICON] плечові датчики [PORT] [TEMP_HUMITURE]",
    "auriga_event_touch": "[ICON] спрацював датчик дотику[PORT] ?",
    "auriga_detect_compass": "[ICON]електронний компас [PORT] на північ",
    "auriga_detect_flame": "[ICON] датчик полум'я [PORT] значення",
    "auriga_detect_gas": "[ICON]газовий датчик[PORT]  Значення",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_0": " вісь х",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_1": "вісь y",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_2": "вісь z",
    "auriga_detect_board_gyro_angle": "[ICON] кут осі [AXIS] гіроскопа на платі",
    "auriga_detect_gyro_angle": "[ICON]Гіроскоп зовнішня [AXIS] Кут",
    "auriga_event_pir_motion": "[ICON]PIR сенсор [PORT] виявляє людський рух?",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_0": "кнопка 1",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_1": "кнопка 2",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_2": "кнопка 3",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_3": "кнопка 4",
    "auriga_event_button_press": "[ICON] натиснута кнопка [PORT] [FOUR_KEY] ?",
    "auriga_event_limit_switch": "[ICON]Обмежте перемикач[PORT] [SLOT] Натиснута?",
    "auriga_detect_potentiometer": "[ICON]Потенціометри [PORT] Значення",
    "AURIGA_DETECT_JOYSTICK_AXIS_X_Y_0": "вісь х",
    "AURIGA_DETECT_JOYSTICK_AXIS_X_Y_1": "вісь y",
    "auriga_detect_joystick": "[ICON]Джойстик [PORT] [AXIS_X_Y] Значення",
    "auriga_detect_infrared": "[ICON] ІЧ-приймач [PORT] ",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_0": "LLL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_1": "LLH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_2": "LHL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_3": "LHH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_4": "HLL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_5": "HLH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_6": "HHL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_7": "HHH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SLOT_0": "мотор порт 1",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SLOT_1": "мотор порт 2",
    "auriga_encoder_motor_V2_motor": "[ICON] енкодерний мотор V2 DIP перемикач [SWITCH] [SLOT] встановити потужність[POWER]%",
    "auriga_encoder_motor_V2_speed": "[ICON] енкодерний мотор V2 DIP перемикач[SWITCH] [SLOT] встановити швидкість[SPEED]об/хв",
    "auriga_encoder_motor_V2_pos": "[ICON] енкодерний мотор V2 DIP перемикач [SWITCH] [SLOT]обертати на [DEGREE]градусів зі швидкістю [SPEED]об/хв",
    "auriga_encoder_motor_V2_minute": "[ICON] енкодерний мотор V2 DIP перемикач [SWITCH] [SLOT] швидкість (об/хв)",
    "auriga_encoder_motor_V2_angle": "[ICON] мотор з енкодером V2 DIP перемикач [SWITCH] [SLOT] кут (°)",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_0": "PM 1.0",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_1": "PM2.5",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_2": "PM10",
    "auriga_detect_pm25_sensor": "[ICON] датчик якості повітря[PORT], [OPTION] (μg/м ³)",
    "BLOCK_1575275074292_DIRECT_0": "за годинниковою стрілкою",
    "BLOCK_1575275074292_DIRECT_1": "проти годинникової стрілки",
    "BLOCK_1575275074292": "енкодерний мотор високої потужності [PORT] [DIRECT] повернути на [DEGREE] градусів зі швидкістю [SPEED] об/хв",
    "enhanced_encoder_motor_power": "[ICON] енкодерний мотор високої потужності [PORT] обертатись з потужністю [POWER]%",
    "enhanced_encoder_motor_speed": "[ICON] енкодерний мотор високої потужності [PORT] швидкість обертання (об/хв)",
    "enhanced_encoder_motor_pos": "[ICON] енкодерний мотор високої потужності [PORT] кут(°）"
};