export default {
    "IoT": "IoT",
    "extensionName": "IoT",
    "extensionDescription": "Amenez Cody dans l'IoT pour qu'il réalise des choses plus amusantes.",
    "iot_connect_network_new": "[ICON] se connecter au Wi-Fi [SSID] mot de passe [PASSWORD]",
    "iot_if_connect_network": "[ICON] Connexion Wi-Fi ?",
    "widget_41f1f086": "géolocalisation",
    "IOT_WEATHER_WEATHER_TYPE_0": "température maximum °C",
    "IOT_WEATHER_WEATHER_TYPE_1": "température minimum °C",
    "IOT_WEATHER_WEATHER_TYPE_2": "température maximum °F",
    "IOT_WEATHER_WEATHER_TYPE_3": "température minimum °F",
    "IOT_WEATHER_WEATHER_TYPE_4": "météo",
    "IOT_WEATHER_WEATHER_TYPE_5": "humidité",
    "iot_weather": "[WEATHER_TYPE] à [LOCATION]",
    "widget_32649bd3": "position",
    "IOT_AIR_WEATHER_TYPE_0": "AQI",
    "IOT_AIR_WEATHER_TYPE_1": "PM2.5",
    "IOT_AIR_WEATHER_TYPE_2": "PM10 (en)",
    "IOT_AIR_WEATHER_TYPE_3": "CO (en)",
    "IOT_AIR_WEATHER_TYPE_4": "SO₂",
    "IOT_AIR_WEATHER_TYPE_5": "NO₂",
    "iot_air": "qualité de l'air [WEATHER_TYPE] à [LOCATION]",
    "IOT_SUN_WEATHER_TYPE_0": "lever du soleil",
    "IOT_SUN_WEATHER_TYPE_1": "coucher de soleil",
    "IOT_SUN_TIME_0": "temps",
    "IOT_SUN_TIME_1": "heure",
    "IOT_SUN_TIME_2": "minute",
    "iot_sun": "[WEATHER_TYPE][TIME] à [LOCATION]",
    "widget_d674d79b": "ajouter à liste de cloud",
    "data_addtolist_cloudlist": "ajouter [VALUE] à [ICON][CLOUD_VARIABLE]",
    "data_itemoflist_cloudlist": "objet [VALUE] de [ICON][CLOUD_VARIABLE]",
    "data_lengthoflist_cloudlist": "longueur de [ICON] [CLOUD_VARIABLE]",
    "widget_8dbf8cd4": "Aucun point d'accès Wi-Fi trouvé",
    "iot_connect_network": "Connecter au réseau WI-FI [SSID] mot de passe [PASSWORD]",
    "codey_wifi_user_broadcast": "[ICON] envoyer un message cloud utilisateur[message]",
    "codey_wifi_user_broadcast_with_value": "[ICON] envoyer un message cloud utilisateur [message] avec une valeur [value]",
    "codey_wifi_when_user_broadcast": "[ICON] lors de la réception du message cloud utilisateur [message]",
    "codey_wifi_user_broadcast_value": "[ICON] message cloud utilisateur [message] valeur reçue",
    "cate_b0f0c042": "L'IoT",
    "CHOOSE_CITY": "ville",
    "METEOROLOGICAL": "ville",
    "WIRELESS": "sans fil",
    "CLOUDLIST": "Liste des nuages"
};