export default {
    "IoT": "IoT",
    "extensionName": "IoT",
    "extensionDescription": "Daha eğlenceli şeyler elde etmek için Cody'yi, IoT'ye getirin.",
    "iot_connect_network_new": "[ICON] Wi-Fi'a bağlanma [SSID] Parola [PASSWORD]",
    "iot_if_connect_network": "[ICON] Wi-Fi bağlı mı?",
    "widget_41f1f086": "konum",
    "IOT_WEATHER_WEATHER_TYPE_0": "maksimum sıcaklık ℃",
    "IOT_WEATHER_WEATHER_TYPE_1": "minimum sıcaklık ℃",
    "IOT_WEATHER_WEATHER_TYPE_2": "maksimum sıcaklık ℉",
    "IOT_WEATHER_WEATHER_TYPE_3": "minimum sıcaklık ℉",
    "IOT_WEATHER_WEATHER_TYPE_4": "hava durumu",
    "IOT_WEATHER_WEATHER_TYPE_5": "Nem",
    "iot_weather": "[WEATHER_TYPE] içinde [LOCATION]",
    "widget_32649bd3": "Konum",
    "IOT_AIR_WEATHER_TYPE_0": "Aqi",
    "IOT_AIR_WEATHER_TYPE_1": "PM2.5",
    "IOT_AIR_WEATHER_TYPE_2": "PM10",
    "IOT_AIR_WEATHER_TYPE_3": "Co",
    "IOT_AIR_WEATHER_TYPE_4": "SO₂",
    "IOT_AIR_WEATHER_TYPE_5": "NO₂",
    "iot_air": "hava kalitesi [WEATHER_TYPE] [LOCATION]",
    "IOT_SUN_WEATHER_TYPE_0": "gündoğumu",
    "IOT_SUN_WEATHER_TYPE_1": "günbatımı",
    "IOT_SUN_TIME_0": "zaman",
    "IOT_SUN_TIME_1": "Saat",
    "IOT_SUN_TIME_2": "Dakika",
    "iot_sun": "[WEATHER_TYPE] [TIME] da [LOCATION]",
    "widget_d674d79b": "bulut veri listesi ekle",
    "data_addtolist_cloudlist": "ekle [VALUE] ye [ICON] [CLOUD_VARIABLE]",
    "data_itemoflist_cloudlist": "öge [VALUE] için [ICON] [CLOUD_VARIABLE]",
    "data_lengthoflist_cloudlist": "[ICON] [CLOUD_VARIABLE] uzunluğu",
    "widget_8dbf8cd4": "Wi-Fi bağlantı noktası bulunamadı",
    "iot_connect_network": "wi-Fi adı [SSID] şifre [PASSWORD] wi-fi' ye bağlan",
    "codey_wifi_user_broadcast": "[ICON] kullanıcı bulut iletisi gönderme[message]",
    "codey_wifi_user_broadcast_with_value": "[ICON] kullanıcı bulut iletisi gönderme [message] değeri ile [value]",
    "codey_wifi_when_user_broadcast": "[ICON] kullanıcı bulut iletisi alırken [message]",
    "codey_wifi_user_broadcast_value": "[ICON] kullanıcı bulut iletisi [message] alınan değer",
    "cate_b0f0c042": "Çok",
    "CHOOSE_CITY": "Şehir",
    "METEOROLOGICAL": "Şehir",
    "WIRELESS": "Kablosuz",
    "CLOUDLIST": "Bulut listesi"
};