export default {
    "IoT": "IoT",
    "extensionName": "IoT",
    "extensionDescription": "Đưa Cody vào IoT để làm cho nó có nhiều điều thú vị hơn.",
    "iot_connect_network_new": "[ICON] kết nối với Wi-Fi [SSID] Mật khẩu [PASSWORD]",
    "iot_if_connect_network": "[ICON] Kết nối Wi-Fi?",
    "widget_41f1f086": "vị trí",
    "IOT_WEATHER_WEATHER_TYPE_0": "nhiệt độ tối đa ° c",
    "IOT_WEATHER_WEATHER_TYPE_1": "nhiệt độ tối thiểu ° c",
    "IOT_WEATHER_WEATHER_TYPE_2": "nhiệt độ tối đa ° F",
    "IOT_WEATHER_WEATHER_TYPE_3": "nhiệt độ tối thiểu ° F",
    "IOT_WEATHER_WEATHER_TYPE_4": "thời tiết",
    "IOT_WEATHER_WEATHER_TYPE_5": "độ ẩm",
    "iot_weather": "[WEATHER_TYPE] tại [LOCATION]",
    "widget_32649bd3": "vị trí",
    "IOT_AIR_WEATHER_TYPE_0": "AQI",
    "IOT_AIR_WEATHER_TYPE_1": "PM 2.5",
    "IOT_AIR_WEATHER_TYPE_2": "PM10",
    "IOT_AIR_WEATHER_TYPE_3": "Khi CO",
    "IOT_AIR_WEATHER_TYPE_4": "Khí SO₂",
    "IOT_AIR_WEATHER_TYPE_5": "Khí NO₂",
    "iot_air": "chất lượng không khí [WEATHER_TYPE] Lúc [LOCATION]",
    "IOT_SUN_WEATHER_TYPE_0": "mặt trời mọc",
    "IOT_SUN_WEATHER_TYPE_1": "hoàng hôn",
    "IOT_SUN_TIME_0": "thời gian",
    "IOT_SUN_TIME_1": "giờ",
    "IOT_SUN_TIME_2": "phút",
    "iot_sun": "[WEATHER_TYPE] [TIME] tại [LOCATION]",
    "widget_d674d79b": "thêm danh sách đám mây",
    "data_addtolist_cloudlist": "thêm [VALUE] Để [ICON] [CLOUD_VARIABLE]",
    "data_itemoflist_cloudlist": "mục [VALUE] của [ICON] [CLOUD_VARIABLE]",
    "data_lengthoflist_cloudlist": "chiều dài của [ICON] [CLOUD_VARIABLE]",
    "widget_8dbf8cd4": "Không tìm thấy điểm truy cập Wi-Fi",
    "iot_connect_network": "kết nối với Wi-Fi [SSID] Mật khẩu [PASSWORD]",
    "codey_wifi_user_broadcast": "[ICON] gửi tin nhắn đám mây của người dùng[message]",
    "codey_wifi_user_broadcast_with_value": "[ICON] gửi tin nhắn người dùng [message] với giá trị [value]",
    "codey_wifi_when_user_broadcast": "[ICON] Khi nhận được thông tin chế độ tải lên [message]",
    "codey_wifi_user_broadcast_value": "[ICON] giá trị nhận được từ tin nhắn người dùng [message]",
    "cate_b0f0c042": "IoT",
    "CHOOSE_CITY": "Thành phố",
    "METEOROLOGICAL": "Thành phố",
    "WIRELESS": "Không dây",
    "CLOUDLIST": "Danh sách đám mây"
};