export default {
    "megapipro": "MegaPi Pro",
    "extensionName": "MegaPi Pro",
    "extensionDescription": "MegaPi Pro demo",
    "firmwares_version_e0a3fed5": "Firmware online",
    "UPDATE_FIRMWARE": "Aktualizace firmware",
    "settings_292995a5": "Nastavení nulové polohy inteligentního servomotoru",
    "connect_fail_e3b8aead": "Zkontrolujte, zda je kabel USB správně připojen k zařízení.",
    "connect_fail_0a8e963b": "Prosím ujistěte se, že připojované zařízení je zapnuté.",
    "connect_fail_c6b30a1c": "Ve stejném okamžiku může být k mBlock připojeno jen jedno zařízení. Připojením tohoto zařízení opojíte předchozí.",
    "connect_fail_9a8a4feb": " Režim nahrávání není k dispozici, když je zařízení připojeno přes Bluetooth4.0. Prosím použijte USB kabel pro připojení zařízení k mBlock před aktualizací firmwaru.",
    "connect_fail_671017f3": "Prosím ověřte, zda počítač podporuje Bluetooth 4.0 a že je Bluetooth 4.0 povolen.",
    "connect_fail_aad5f15d": "Prosím ujistěte se, že připojované zařízení je zapnuté.",
    "connect_fail_2df5ee83": "Ve stejném okamžiku může být k mBlock připojeno jen jedno zařízení. Připojením tohoto zařízení opojíte předchozí.",
    "upload_fail_c9f06d49": "Ověřte prosím soulad datového typu, typů parametrů a logiky bloků nebo kódu pro toto zařízení se standardy.",
    "upload_fail_3bd7dbc4": "Prosím zkontrolujte, zda je zařízení správně připojeno. Zkuste zařízení restartovat a znovu jej připojte.",
    "firmware_success_5a28c266": "Pro lepší zkušenosti doporučujeme, abyste po restartu zařízení znovu připojili.",
    "firmware_fail_e4b56cf5": "Zkontrolujte, zda je zařízení správně připojeno, zkuste zařízení restartovat a znovu jej propojit s mBlock. Potom opět aktualizujte firmware.",
    "timer": "stopky",
    "timer_reset": "vynuluj stopky",
    "MegaPi Pro": "MegaPi Pro",
    "SEG7_SHOW_NUMBER_PORT_0": "port6",
    "SEG7_SHOW_NUMBER_PORT_1": "port7",
    "SEG7_SHOW_NUMBER_PORT_2": "port8",
    "SEG7_SHOW_NUMBER_PORT_3": "port9",
    "SEG7_SHOW_NUMBER_PORT_4": "port10",
    "SEG7_SHOW_NUMBER_PORT_5": "port11",
    "SEG7_SHOW_NUMBER_PORT_6": "port12",
    "seg7_show_number": "sedmisegmentový displej [PORT] zobrazit číslo [NUMBER]",
    "mcore_show_face_time": "LED panel [PORT] zobrazit obrázek [FACE_PANEL] na[TIME] Sekund",
    "mcore_show_face": "LED panel [PORT] zobrazit obrázek [FACE_PANEL]",
    "mcore_show_face_position": "LED panel [PORT] zobrazit obrázek[FACE_PANEL] na pozici x: [X] y: [Y]",
    "mcore_show_text": "LED panel [PORT] zobrazit text[TEXT]",
    "mcore_show_text_position": "LED panel [PORT] zobrazit text [TEXT] na pozici x: [X] Y: [Y]",
    "mcore_show_number": "Panel LED[PORT]zobrazit číslo [NUMBER]",
    "mcore_show_time": "LED panel [PORT] zobrazit čas [NUMBER1]: [NUMBER2]",
    "display": "Vzhled",
    "LED_MODULE_SET_COLOR_LED_POSTION_0": "vše",
    "LED_MODULE_SET_COLOR_LED_POSTION_1": "1",
    "LED_MODULE_SET_COLOR_LED_POSTION_2": "2",
    "LED_MODULE_SET_COLOR_LED_POSTION_3": "3",
    "LED_MODULE_SET_COLOR_LED_POSTION_4": "4",
    "led_module_set_color": "LED modul[PORT] nastavit světlo[LED_POSTION] na červená [R], zelená[G], modrá [B]",
    "LED_STRIP_SET_COLOR_SLOT_0": "slot 1",
    "LED_STRIP_SET_COLOR_SLOT_1": "slot 2",
    "led_strip_set_color": "LED pásek [PORT] [SLOT] nastavit LED[POS] na barvu červená [R], zelená [G], modrá [B]",
    "soundandlight": "Světlo a zvuk",
    "ENCODER_MOTOR_POWER_PORT_0": "port1",
    "ENCODER_MOTOR_POWER_PORT_1": "port2",
    "ENCODER_MOTOR_POWER_PORT_2": "port3",
    "ENCODER_MOTOR_POWER_PORT_3": "port4",
    "encoder_motor_power": "kodér motoru [PORT] otočet při výkonu [POWER]%",
    "encoder_motor_pos": "enkodér motoru[PORT] otočit na [DEG] stupňů rychlostí [SPEED] ot./min",
    "encoder_motor_speed": "enkodér motoru[PORT] otáčet rychlostí [SPEED] ot./min",
    "encoder_motor_get_speed": "enkodér motoru [PORT] rychlost otáčení (ot./min)",
    "encoder_motor_get_pos": "úhel (°) motoru motoru [PORT]",
    "HP_ENCODER_MOTOR_POWER_SWITCH_0": "NNN",
    "HP_ENCODER_MOTOR_POWER_SWITCH_1": "NNV",
    "HP_ENCODER_MOTOR_POWER_SWITCH_2": "NVN",
    "HP_ENCODER_MOTOR_POWER_SWITCH_3": "NVV",
    "HP_ENCODER_MOTOR_POWER_SWITCH_4": "VNN",
    "HP_ENCODER_MOTOR_POWER_SWITCH_5": "VNV",
    "HP_ENCODER_MOTOR_POWER_SWITCH_6": "VVN",
    "HP_ENCODER_MOTOR_POWER_SWITCH_7": "VVV",
    "HP_ENCODER_MOTOR_POWER_SLOT_0": "motor port1",
    "HP_ENCODER_MOTOR_POWER_SLOT_1": "motor port2",
    "hp_encoder_motor_power": "vysokovýkonný enkodér motoru (DIP přepínač [SWITCH] [SLOT]) otáčet s výkonem [POWER]%",
    "hp_encoder_motor_pos": "vysocevýkonný enkodér (DIP přepínač [SWITCH] [SLOT]) otočit o [DEG] stupně rychlosti [SPEED] ot./min",
    "hp_encoder_motor_speed": "vysokovýkonný enkodér motoru (DIP přepínač [SWITCH] [SLOT]) otáčet při rychlosti [SPEED] ot./min",
    "hp_encoder_motor_get_speed": "vysokovýkonný enkodér motoru (DIP přepínač [SWITCH] [SLOT]) otáčet při rychlosti (ot./min)",
    "hp_encoder_motor_get_pos": "vysokovýkonný enkodér motoru (DIP přepínač [SWITCH] [SLOT]) úhel (°)",
    "stepper_motor_pos": "krokový motor [PORT] otáčet [STEP] kroky při rychlosti [SPEED] kroků/s",
    "enhanced_encoder_motor_power": "vylepšený motor enkodéru [PORT] otáčet při výkonu [POWER]%",
    "enhanced_encoder_motor_speed": "rozšířený enkodér motoru [PORT] rychlost otáčení (ot./min)",
    "enhanced_encoder_motor_pos": "rozšířený kodér motoru[PORT]současný úhel (°)",
    "DCMOTOR_POWER_1_PORT_0": "port1A",
    "DCMOTOR_POWER_1_PORT_1": "port1B",
    "DCMOTOR_POWER_1_PORT_2": "port2A",
    "DCMOTOR_POWER_1_PORT_3": "port2B",
    "DCMOTOR_POWER_1_PORT_4": "port3A",
    "DCMOTOR_POWER_1_PORT_5": "port3B",
    "DCMOTOR_POWER_1_PORT_6": "port4A",
    "DCMOTOR_POWER_1_PORT_7": "port4B",
    "DCmotor_power_1": "Stejnosmětný motor[PORT] se bude otáčet při [POWER]% výkonu",
    "DCMOTOR_POWER_2_PORT_0": "M9",
    "DCMOTOR_POWER_2_PORT_1": "M10",
    "DCMOTOR_POWER_2_PORT_2": "M11",
    "DCMOTOR_POWER_2_PORT_3": "M12",
    "DCmotor_power_2": "Stejnosmětný motor[PORT] se bude otáčet při [POWER]% výkonu",
    "BLmotor_lock": "odemknout bezkartáčový motor [PORT]",
    "BLmotor_power": "bezkartáčový motor[PORT] se bude otáčet při [POWER] % výkonu",
    "BLOCK_1577092133273_INDEX_0": "1",
    "BLOCK_1577092133273_INDEX_1": "2",
    "BLOCK_1577092133273_INDEX_2": "3",
    "BLOCK_1577092133273_INDEX_3": "4",
    "BLOCK_1577092133273_INDEX_4": "5",
    "BLOCK_1577092133273_INDEX_5": "6",
    "BLOCK_1577092133273": "chytré servo [INDEX]se otočí na nulovou pozici",
    "BLOCK_1577092158156": "chytré servo[INDEX] otáčet při výkonu [POWER]%",
    "BLOCK_1577092279792": "smart servo [INDEX] otočit na [DEG] stupně rychlostí [SPEED] ot./min",
    "BLOCK_1577094190142": "smart servo [INDEX] otočit na [DEG] stupně rychlostí [SPEED] ot./min",
    "BLOCK_1577094267367_OPTION_0": "současný",
    "BLOCK_1577094267367_OPTION_1": "napětí",
    "BLOCK_1577094267367_OPTION_2": "rychlost",
    "BLOCK_1577094267367_OPTION_3": "úhel",
    "BLOCK_1577094267367_OPTION_4": "teplota",
    "BLOCK_1577094267367": "smart servo[INDEX]  [OPTION]",
    "VALVE_STATUS_A_STATUS_0": "zapnout",
    "VALVE_STATUS_A_STATUS_1": "vypnout",
    "valve_status_a": "nastavit ventil solenoidu [PORT] na [STATUS]",
    "valve_status_b": "nastavit ventil solenoidu [PORT] na [STATUS]",
    "SMALL_FUN_FAN_ROTATE_0": "otočit ve směru hodinových ručiček pro vyfukování",
    "SMALL_FUN_FAN_ROTATE_1": "otočit proti směru hodinových ručiček pro nasávání",
    "SMALL_FUN_FAN_ROTATE_2": "zastavit",
    "small_fun": "ventilátor [PORT]  [FAN_ROTATE]",
    "power": "Napájení",
    "ultrasonic_dis": "ultrazvukový senzor [PORT] (CM)",
    "linefollower_status": "senzor sledování čáry [PORT] stav",
    "COLOR_SENSOR_READ_COLOR_0": "Č",
    "COLOR_SENSOR_READ_COLOR_1": "Z",
    "COLOR_SENSOR_READ_COLOR_2": "M",
    "color_sensor_read": "senzor barev [PORT] [COLOR] hodnota",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_0": "bílá",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_1": "červená",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_2": "žlutá",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_3": "zelená",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_4": "modrá",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_5": "černá",
    "color_sensor_color_detected": "barevný senzor [PORT] detekuje [COLOR]？",
    "JOYSTICK_AXIS_X_Y_0": "osa-x",
    "JOYSTICK_AXIS_X_Y_1": "osa-y",
    "joystick": "joystick [PORT][AXIS_X_Y]",
    "BUTTON_PRESSED_FOUR_KEY_0": "tlačítko1",
    "BUTTON_PRESSED_FOUR_KEY_1": "tlačítko 2",
    "BUTTON_PRESSED_FOUR_KEY_2": "tlačítko 3",
    "BUTTON_PRESSED_FOUR_KEY_3": "tlačítko 4",
    "button_pressed": "tlačítko [PORT] [FOUR_KEY] stisknuto?",
    "touch_sensor_touch_detected": "dotykový senzor [PORT] je stlačen?",
    "pointmeter": "potenciometr [PORT]",
    "limitswitch_read": "omezovač [PORT] [SLOT]",
    "light_sensor_read": "světelný senzor[PORT]",
    "LIGHT_SENSOR_STATUS_0": "vyp",
    "LIGHT_SENSOR_STATUS_1": "zap",
    "light_sensor": "světelný senzor [PORT] stav LED [STATUS]",
    "soundsensor_read": "senzor hlasitosti[PORT]",
    "IRSENSOR_READ_PORT_0": "port7",
    "IRSENSOR_READ_PORT_1": "port8",
    "IRSENSOR_READ_PORT_2": "port9",
    "IRSENSOR_READ_PORT_3": "port10",
    "IRsensor_read": "IR přijímač [PORT] (pouze v režimu Arduina)",
    "humanIR_read": "PIR senzor [PORT] detekoval pohyb člověka?",
    "tempsensor_read": "teplotní senzor [PORT] [SLOT] °C",
    "TEMP_MOISTURE_SENSOR_READ_TEMP_HUMITURE_0": "vlhkost",
    "TEMP_MOISTURE_SENSOR_READ_TEMP_HUMITURE_1": "teplota",
    "temp_moisture_sensor_read": "senzor pocitové teploty [PORT] [TEMP_HUMITURE]",
    "firesensor_read": "senzor plamene[PORT]",
    "gassensor_read": "plynový senzor [PORT]",
    "GYRO_SESOR_READ_AXIS_0": "osa-x",
    "GYRO_SESOR_READ_AXIS_1": "osa-y",
    "GYRO_SESOR_READ_AXIS_2": "osa-z",
    "gyro_sesor_read": "gyroskop (na jakémkoli bílém portu) [AXIS] úhel",
    "magsensor_read": "digitální kompas[PORT]",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_0": "stisknout klapkou",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_1": "uvolnit klapku",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_2": "začít se zaměřováním",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_3": "ukončit zaostřování",
    "shutter_set_fun": "nastavit závěrku kamery na [SHUTTER_ACTION]",
    "sensing": "Vnímání",
    "mpp_main": "Hlavní program MegaPi Pro",
    "match_in_automode": "konkurence na automatické scéně?",
    "SET_SMART_ZERO_TITLE": "nastavení nulové polohy inteligentního servomotoru",
    "SET_SMART_ZERO_BTN": "nastavit aktuální pozici jako nulovou pozici",
    "SET_SMART_ZERO_NO": "vyberte sériové číslo",
    "SET_SMART_ZERO_BTN_LOADING": "nastavení nulové pozice...",
    "SET_SMART_ZERO_SUCCESS": "Úspěch!",
    "SET_SMART_ZERO_FAIL": "Chyba."
};