export default {
    "megapipro": "MegaPi Pro",
    "extensionName": "MegaPi Pro",
    "extensionDescription": "MegaPi Pro demo",
    "firmwares_version_e0a3fed5": "Online firmware",
    "UPDATE_FIRMWARE": "Firmware-update",
    "settings_292995a5": "Stel Smart servo Zero positie",
    "connect_fail_e3b8aead": "Controleer of de USB-kabel goed is aangesloten op het apparaat.",
    "connect_fail_0a8e963b": "Controleer of het aangesloten apparaat is ingeschakeld.",
    "connect_fail_c6b30a1c": "Slechts een apparaat kan worden aangesloten op een moment in mBlock. Dus het aansluiten van dit apparaat zal leiden tot de afsluiting van de vorige.",
    "connect_fail_9a8a4feb": " Upload modus is niet beschikbaar wanneer het apparaat is aangesloten via Bluetooth 4.0. Gebruik een USB-kabel om uw apparaat aan te sluiten op mBlock voordat u de firmware bijwerkt.",
    "connect_fail_671017f3": "Zorg ervoor dat uw computer Bluetooth 4.0 ondersteunt en dat Bluetooth 4.0 al is ingeschakeld.",
    "connect_fail_aad5f15d": "Controleer of het aangesloten apparaat is ingeschakeld.",
    "connect_fail_2df5ee83": "Slechts een apparaat kan worden aangesloten op een moment in mBlock. Dus het aansluiten van dit apparaat zal leiden tot de afsluiting van de vorige.",
    "upload_fail_c9f06d49": "Zorg ervoor dat u het gegevenstype, het parametertype en de logica van blokken of code voor het apparaat aansluit op standaarden.",
    "upload_fail_3bd7dbc4": "Controleer of het apparaat goed is aangesloten. Probeer het apparaat opnieuw te starten en sluit het opnieuw aan.",
    "firmware_success_5a28c266": "Voor een betere ervaring raden wij u aan het apparaat opnieuw te verbinden nadat u het opnieuw hebt opgestart.",
    "firmware_fail_e4b56cf5": "Controleer of het apparaat goed is aangesloten. Probeer het apparaat opnieuw op te starten en sluit het opnieuw aan op mBlock. Dan update de firmware opnieuw.",
    "timer": "klok",
    "timer_reset": "zet tijdklok op nul",
    "MegaPi Pro": "MegaPi Pro",
    "SEG7_SHOW_NUMBER_PORT_0": "poort6",
    "SEG7_SHOW_NUMBER_PORT_1": "poort7",
    "SEG7_SHOW_NUMBER_PORT_2": "poort8",
    "SEG7_SHOW_NUMBER_PORT_3": "poort9",
    "SEG7_SHOW_NUMBER_PORT_4": "poort10",
    "SEG7_SHOW_NUMBER_PORT_5": "poort11",
    "SEG7_SHOW_NUMBER_PORT_6": "poort12",
    "seg7_show_number": "zeven-segmenten [PORT] geeft nummer [NUMBER]",
    "mcore_show_face_time": "LED-paneel [PORT] beeld wordt weergegeven [FACE_PANEL] Voor [TIME] Seconden",
    "mcore_show_face": "LED-paneel [PORT] beeld wordt weergegeven [FACE_PANEL]",
    "mcore_show_face_position": "LED-paneel [PORT] beeld wordt weergegeven [FACE_PANEL] bij x: [X] Y: [Y]",
    "mcore_show_text": "LED-paneel [PORT] geeft tekst weer [TEXT]",
    "mcore_show_text_position": "LED-paneel[PORT] geeft tekst weer [TEXT] bij x: [X] Y: [Y]",
    "mcore_show_number": "LED-paneel [PORT]geeft nummer [NUMBER]",
    "mcore_show_time": "LED-paneel [PORT]geeft de tijd weer[NUMBER1]: [NUMBER2]",
    "display": "Uiterlijk",
    "LED_MODULE_SET_COLOR_LED_POSTION_0": "alle",
    "LED_MODULE_SET_COLOR_LED_POSTION_1": "1",
    "LED_MODULE_SET_COLOR_LED_POSTION_2": "2",
    "LED_MODULE_SET_COLOR_LED_POSTION_3": "3",
    "LED_MODULE_SET_COLOR_LED_POSTION_4": "4",
    "led_module_set_color": "LED-module[PORT] Ingesteld [LED_POSTION] licht naar rood[R] Groene [G] Blauwe[B]",
    "LED_STRIP_SET_COLOR_SLOT_0": "slot1",
    "LED_STRIP_SET_COLOR_SLOT_1": "slot2",
    "led_strip_set_color": "LED strip [PORT] [SLOT] stelt de[POS]  licht naar rood [R] Groene [G] Blauwe [B]",
    "soundandlight": "Licht & geluid",
    "ENCODER_MOTOR_POWER_PORT_0": "poort1",
    "ENCODER_MOTOR_POWER_PORT_1": "poort2",
    "ENCODER_MOTOR_POWER_PORT_2": "poort3",
    "ENCODER_MOTOR_POWER_PORT_3": "poort4",
    "encoder_motor_power": "encoder motor [PORT] draait aan de macht [POWER]%",
    "encoder_motor_pos": "encoder motor [PORT] roteert door [DEG] graden bij snelheid van [SPEED] r/min",
    "encoder_motor_speed": "encoder motor [PORT]draait op snelheid van [SPEED]r/min",
    "encoder_motor_get_speed": "encoder motor [PORT] Rotatiesnelheid (r/min)",
    "encoder_motor_get_pos": "encoder motor [PORT] hoek (°)",
    "HP_ENCODER_MOTOR_POWER_SWITCH_0": "LLL",
    "HP_ENCODER_MOTOR_POWER_SWITCH_1": "LLH",
    "HP_ENCODER_MOTOR_POWER_SWITCH_2": "LHL",
    "HP_ENCODER_MOTOR_POWER_SWITCH_3": "LHH",
    "HP_ENCODER_MOTOR_POWER_SWITCH_4": "HLL",
    "HP_ENCODER_MOTOR_POWER_SWITCH_5": "HLH",
    "HP_ENCODER_MOTOR_POWER_SWITCH_6": "HHL",
    "HP_ENCODER_MOTOR_POWER_SWITCH_7": "HHH",
    "HP_ENCODER_MOTOR_POWER_SLOT_0": "motor poort1",
    "HP_ENCODER_MOTOR_POWER_SLOT_1": "motor poort2",
    "hp_encoder_motor_power": "krachtige encodermotor(DIP-schakelaar [SCHAKELAAR] [SLEUF]) draait op vermogen [POWER]%",
    "hp_encoder_motor_pos": "High-Power encoder motor (DIP-schakelaar [SWITCH] [SLOT]) roteert door [DEG] graden bij snelheid van [SPEED]r/min",
    "hp_encoder_motor_speed": "High-Power encoder motor (DIP-schakelaar [SWITCH] [SLOT]) draait op snelheid van [SPEED] r/min",
    "hp_encoder_motor_get_speed": "High-Power encoder motor (DIP-schakelaar [SWITCH] [SLOT]) rotatiesnelheid (r/min)",
    "hp_encoder_motor_get_pos": "High-Power encoder motor (DIP-schakelaar [SWITCH] [SLOT]) hoek (°)",
    "stepper_motor_pos": "Stepper Motor [PORT] Draait [STEP] stappen op snelheid van [SPEED] STP/SEC",
    "enhanced_encoder_motor_power": "Enhanced encoder motor [PORT] draait aan de macht[POWER]%",
    "enhanced_encoder_motor_speed": "Enhanced encoder motor [PORT] Rotatiesnelheid (r/min)",
    "enhanced_encoder_motor_pos": "Enhanced encoder motor[PORT]huidige hoek (°)",
    "DCMOTOR_POWER_1_PORT_0": "port1A",
    "DCMOTOR_POWER_1_PORT_1": "poort1B",
    "DCMOTOR_POWER_1_PORT_2": "poort2A",
    "DCMOTOR_POWER_1_PORT_3": "poort2B",
    "DCMOTOR_POWER_1_PORT_4": "poort3A",
    "DCMOTOR_POWER_1_PORT_5": "poort3B",
    "DCMOTOR_POWER_1_PORT_6": "poort4A",
    "DCMOTOR_POWER_1_PORT_7": "poort4B",
    "DCmotor_power_1": "DC motor [PORT] draait aan de macht [POWER]%",
    "DCMOTOR_POWER_2_PORT_0": "M9",
    "DCMOTOR_POWER_2_PORT_1": "M10",
    "DCMOTOR_POWER_2_PORT_2": "M11",
    "DCMOTOR_POWER_2_PORT_3": "M12",
    "DCmotor_power_2": "DC motor [PORT] draait aan de macht[POWER]%",
    "BLmotor_lock": "Unlock borstelloze motor[PORT]",
    "BLmotor_power": "borstelloze motor [PORT] draait aan de macht [POWER] %",
    "BLOCK_1577092133273_INDEX_0": "1",
    "BLOCK_1577092133273_INDEX_1": "2",
    "BLOCK_1577092133273_INDEX_2": "3",
    "BLOCK_1577092133273_INDEX_3": "4",
    "BLOCK_1577092133273_INDEX_4": "5",
    "BLOCK_1577092133273_INDEX_5": "6",
    "BLOCK_1577092133273": "smart servo [INDEX]draait naar nul positie",
    "BLOCK_1577092158156": "smart servo [INDEX] draait op[kracht] % vermogen",
    "BLOCK_1577092279792": "smart servo [INDEX] draait tot [DEG] graden op snelheid [SNELHEID] rpm",
    "BLOCK_1577094190142": "smart servo[INDEX]draait[DEG]graden op snelheid [SPEED] rpm",
    "BLOCK_1577094267367_OPTION_0": "huidige",
    "BLOCK_1577094267367_OPTION_1": "voltage",
    "BLOCK_1577094267367_OPTION_2": "snelheid",
    "BLOCK_1577094267367_OPTION_3": "hoek",
    "BLOCK_1577094267367_OPTION_4": "temperatuur",
    "BLOCK_1577094267367": "slimme servo[INDEX]  [OPTIE]",
    "VALVE_STATUS_A_STATUS_0": "macht op",
    "VALVE_STATUS_A_STATUS_1": "stroom uit",
    "valve_status_a": "set magneetventiel [PORT]status aan [STATUS]",
    "valve_status_b": "set magneetventiel [PORT] status aan [STATUS]",
    "SMALL_FUN_FAN_ROTATE_0": "Draai rechtsom om lucht te blazen",
    "SMALL_FUN_FAN_ROTATE_1": "spin linksom te zuigen lucht",
    "SMALL_FUN_FAN_ROTATE_2": "stop",
    "small_fun": "Fan [PORT]  [FAN_ROTATE]",
    "power": "Macht",
    "ultrasonic_dis": "ultrasone sensor [PORT] CM",
    "linefollower_status": "lijn-volgende sensor [PORT]Status",
    "COLOR_SENSOR_READ_COLOR_0": "R",
    "COLOR_SENSOR_READ_COLOR_1": "G",
    "COLOR_SENSOR_READ_COLOR_2": "B",
    "color_sensor_read": "kleur sensor[PORT] [COLOR]Waarde",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_0": "wit",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_1": "rood",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_2": "geel",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_3": "groen",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_4": "blauw",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_5": "zwart",
    "color_sensor_color_detected": "kleursensor [POORT] gedetecteerd [KLEUR]?",
    "JOYSTICK_AXIS_X_Y_0": "x-as",
    "JOYSTICK_AXIS_X_Y_1": "y-as",
    "joystick": "Joystick [PORT][AXIS_X_Y]",
    "BUTTON_PRESSED_FOUR_KEY_0": "knop1",
    "BUTTON_PRESSED_FOUR_KEY_1": "knop2",
    "BUTTON_PRESSED_FOUR_KEY_2": "knop3",
    "BUTTON_PRESSED_FOUR_KEY_3": "knop4",
    "button_pressed": "Knop [PORT] [FOUR_KEY] Ingedrukt?",
    "touch_sensor_touch_detected": "Touch sensor [PORT] wordt aangeraakt?",
    "pointmeter": "Potentiometer [PORT]",
    "limitswitch_read": "limiet schakelaar [PORT] [SLOT]",
    "light_sensor_read": "lichtsensor[PORT]",
    "LIGHT_SENSOR_STATUS_0": "uit",
    "LIGHT_SENSOR_STATUS_1": "aan",
    "light_sensor": "lichtsensor [PORT]LED-status als [STATUS]",
    "soundsensor_read": "volume sensor[PORT]",
    "IRSENSOR_READ_PORT_0": "poort7",
    "IRSENSOR_READ_PORT_1": "poort8",
    "IRSENSOR_READ_PORT_2": "poort9",
    "IRSENSOR_READ_PORT_3": "poort10",
    "IRsensor_read": "IR ontvanger [POORT] (alleen in Arduino modus)",
    "humanIR_read": "Passieve infraroodsensor [POORT] heeft menselijke beweging gedetecteerd?",
    "tempsensor_read": "Temperatuursensor[PORT] [SLOT]",
    "TEMP_MOISTURE_SENSOR_READ_TEMP_HUMITURE_0": "luchtvochtigheid",
    "TEMP_MOISTURE_SENSOR_READ_TEMP_HUMITURE_1": "temperatuur",
    "temp_moisture_sensor_read": "vocht- en temperatuursensor [PORT] [TEMP_HUMITURE]",
    "firesensor_read": "vlamsensor[PORT]",
    "gassensor_read": "gas sensor [PORT]",
    "GYRO_SESOR_READ_AXIS_0": "x-as",
    "GYRO_SESOR_READ_AXIS_1": "y-as",
    "GYRO_SESOR_READ_AXIS_2": "z-as",
    "gyro_sesor_read": "gyroscoop (op een witte poort) [AXIS] Hoek",
    "magsensor_read": "digitaal kompas[PORT]",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_0": "Druk op sluiter",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_1": "ontspanknop",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_2": "beginnen met scherpstellen",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_3": "stop scherpstellen",
    "shutter_set_fun": "set camera sluiter module om [SHUTTER_ACTION]",
    "sensing": "Waarnemen",
    "mpp_main": "MegaPi Pro hoofdprogramma",
    "match_in_automode": "concurrentie in de automatische fase?",
    "SET_SMART_ZERO_TITLE": "Stel Smart servo Zero positie",
    "SET_SMART_ZERO_BTN": "huidige positie als nul positie instellen",
    "SET_SMART_ZERO_NO": "kies een serienummer",
    "SET_SMART_ZERO_BTN_LOADING": "nul positie instellen...",
    "SET_SMART_ZERO_SUCCESS": "Succesvolle!",
    "SET_SMART_ZERO_FAIL": "Mislukt."
};