export default {
    "megapipro": "MegaPi Pro",
    "extensionName": "MegaPi Pro",
    "extensionDescription": "Демо MegaPi Pro",
    "firmwares_version_e0a3fed5": "Прошивка онлайн",
    "UPDATE_FIRMWARE": "Обновление прошивки",
    "settings_292995a5": "Установить ноль сервопривода",
    "connect_fail_e3b8aead": "Убедитесь, что кабель USB правильно подключен к устройству.",
    "connect_fail_0a8e963b": "Пожалуйста, убедитесь, что устройство, которое будет подключено, приведено в действие.",
    "connect_fail_c6b30a1c": "В mBlock может быть подключено только одно устройство. Таким образом, подключение этого устройства приведет к отключении предыдущего.",
    "connect_fail_9a8a4feb": " Режим загрузки недоступен, когда устройство подключено через Bluetooth 4.0. Пожалуйста, используйте USB-кабель для подключения устройства к mBlock перед обновлением прошивки.",
    "connect_fail_671017f3": "Пожалуйста, убедитесь, что ваш компьютер поддерживает Bluetooth 4.0 и Bluetooth 4.0 уже включен.",
    "connect_fail_aad5f15d": "Пожалуйста, убедитесь, что устройство, которое будет подключено, приведено в действие.",
    "connect_fail_2df5ee83": "В mBlock может быть подключено только одно устройство. Таким образом, подключение этого устройства приведет к отключении предыдущего.",
    "upload_fail_c9f06d49": "Пожалуйста, убедитесь, что вы выравнивать тип данных, тип параметра и логику блоков или код для устройства с стандартами.",
    "upload_fail_3bd7dbc4": "Пожалуйста, проверьте, правильно ли подключен устройство. Попробуйте перезапустить устройство и восстановить его.",
    "firmware_success_5a28c266": "Для лучшего опыта, мы рекомендуем вам восстановить устройство после перезагрузки.",
    "firmware_fail_e4b56cf5": "Пожалуйста, проверьте, правильно ли подключен устройство. Попробуйте перезапустить устройство и подключить его к mBlock. Затем обновите прошивку снова.",
    "timer": "таймер",
    "timer_reset": "обнулить таймер",
    "MegaPi Pro": "MegaPi Pro",
    "SEG7_SHOW_NUMBER_PORT_0": "порт6",
    "SEG7_SHOW_NUMBER_PORT_1": "порт7",
    "SEG7_SHOW_NUMBER_PORT_2": "порт8",
    "SEG7_SHOW_NUMBER_PORT_3": "порт9",
    "SEG7_SHOW_NUMBER_PORT_4": "порт10",
    "SEG7_SHOW_NUMBER_PORT_5": "порт11",
    "SEG7_SHOW_NUMBER_PORT_6": "порт12",
    "seg7_show_number": "семь сегментов [PORT] Отображает номер [NUMBER]",
    "mcore_show_face_time": "СВЕТОДИОДНЫЙ панель [PORT] Отображает изображение [FACE_PANEL] Для [TIME] Сек",
    "mcore_show_face": "СВЕТОДИОДНЫЙ панель [PORT] Отображает изображение [FACE_PANEL]",
    "mcore_show_face_position": "СВЕТОДИОДНЫЙ панель [PORT] Отображает изображение [FACE_PANEL] на х: [X] Y: [Y]",
    "mcore_show_text": "СВЕТОДИОДНЫЙ панель [PORT] Отображает текст [TEXT]",
    "mcore_show_text_position": "СВЕТОДИОДНЫЙ панель[PORT] Отображает текст [TEXT] на х: [X] Y: [Y]",
    "mcore_show_number": "СВЕТОДИОДНЫЙ панель [PORT]Отображает номер [NUMBER]",
    "mcore_show_time": "СВЕТОДИОДНЫЙ панель [PORT]Отображает время[NUMBER1]: [NUMBER2]",
    "display": "Внешность",
    "LED_MODULE_SET_COLOR_LED_POSTION_0": "все",
    "LED_MODULE_SET_COLOR_LED_POSTION_1": "1",
    "LED_MODULE_SET_COLOR_LED_POSTION_2": "2",
    "LED_MODULE_SET_COLOR_LED_POSTION_3": "3",
    "LED_MODULE_SET_COLOR_LED_POSTION_4": "4",
    "led_module_set_color": "СВЕТОДИОДНЫЙ модуль[PORT] Задает [LED_POSTION] свет на красный[R] Зеленый [G] Синий[B]",
    "LED_STRIP_SET_COLOR_SLOT_0": "слот1",
    "LED_STRIP_SET_COLOR_SLOT_1": "слот2",
    "led_strip_set_color": "СВЕТОДИОДНЫЙ стриптиз [PORT] [SLOT] устанавливает[POS]  свет на красный [R] Зеленый [G] Синий [B]",
    "soundandlight": "Свет и звук",
    "ENCODER_MOTOR_POWER_PORT_0": "порт1",
    "ENCODER_MOTOR_POWER_PORT_1": "порт2",
    "ENCODER_MOTOR_POWER_PORT_2": "порт3",
    "ENCODER_MOTOR_POWER_PORT_3": "порт4",
    "encoder_motor_power": "кодер Мотор [PORT] вращается у власти [POWER]%",
    "encoder_motor_pos": "кодер Мотор [PORT] вращается по [DEG] градусов на скорости [SPEED] р/мин",
    "encoder_motor_speed": "кодер Мотор [PORT]вращается со скоростью [SPEED]р/мин",
    "encoder_motor_get_speed": "кодер Мотор [PORT] скорость вращения (r/min)",
    "encoder_motor_get_pos": "двигатель с энкодером [PORT] угол(°)",
    "HP_ENCODER_MOTOR_POWER_SWITCH_0": "HLL",
    "HP_ENCODER_MOTOR_POWER_SWITCH_1": "LLH",
    "HP_ENCODER_MOTOR_POWER_SWITCH_2": "LHL",
    "HP_ENCODER_MOTOR_POWER_SWITCH_3": "LHH",
    "HP_ENCODER_MOTOR_POWER_SWITCH_4": "HLL",
    "HP_ENCODER_MOTOR_POWER_SWITCH_5": "HLL",
    "HP_ENCODER_MOTOR_POWER_SWITCH_6": "HHL",
    "HP_ENCODER_MOTOR_POWER_SWITCH_7": "HHH",
    "HP_ENCODER_MOTOR_POWER_SLOT_0": "порт двигателя 1",
    "HP_ENCODER_MOTOR_POWER_SLOT_1": "порт двигателя 2",
    "hp_encoder_motor_power": "high-power encoder motor (DIP switch [SWITCH] [SLOT]) rotates at power [POWER]%",
    "hp_encoder_motor_pos": "высокой мощности кодера двигателя (падение переключатель [SWITCH] [SLOT]) вращается по [DEG] градусов на скорости [SPEED]р/мин",
    "hp_encoder_motor_speed": "высокой мощности кодера двигателя (падение переключатель [SWITCH] [SLOT]) вращается со скоростью [SPEED] р/мин",
    "hp_encoder_motor_get_speed": "высокой мощности кодера двигателя (падение переключатель [SWITCH] [SLOT]) скорость вращения (r/min)",
    "hp_encoder_motor_get_pos": "высокой мощности кодер мотор (падение переключатель [SWITCH] [SLOT]) угол (°)",
    "stepper_motor_pos": "шаговых двигателя [PORT] Поворот [STEP] шаги на скорости [SPEED] СТС/сек",
    "enhanced_encoder_motor_power": "Улучшенный кодер Мотор [PORT] вращается у власти[POWER]%",
    "enhanced_encoder_motor_speed": "Улучшенный кодер Мотор [PORT] скорость вращения (r/min)",
    "enhanced_encoder_motor_pos": "Улучшенный кодер Мотор[PORT]текущий угол наклона (°)",
    "DCMOTOR_POWER_1_PORT_0": "порт1A",
    "DCMOTOR_POWER_1_PORT_1": "порт1B",
    "DCMOTOR_POWER_1_PORT_2": "port2A",
    "DCMOTOR_POWER_1_PORT_3": "порт2B",
    "DCMOTOR_POWER_1_PORT_4": "порт3A",
    "DCMOTOR_POWER_1_PORT_5": "порт3B",
    "DCMOTOR_POWER_1_PORT_6": "порт4A",
    "DCMOTOR_POWER_1_PORT_7": "порт4B",
    "DCmotor_power_1": "Двигатель DC [PORT] вращается у власти [POWER]%",
    "DCMOTOR_POWER_2_PORT_0": "M9",
    "DCMOTOR_POWER_2_PORT_1": "M10",
    "DCMOTOR_POWER_2_PORT_2": "M11",
    "DCMOTOR_POWER_2_PORT_3": "M12",
    "DCmotor_power_2": "Двигатель DC [PORT] вращается у власти[POWER]%",
    "BLmotor_lock": "разблокировать бесхвоя Мотор[PORT]",
    "BLmotor_power": "бесхвоя Мотор [PORT] вращается у власти [POWER] %",
    "BLOCK_1577092133273_INDEX_0": "1",
    "BLOCK_1577092133273_INDEX_1": "2",
    "BLOCK_1577092133273_INDEX_2": "3",
    "BLOCK_1577092133273_INDEX_3": "4",
    "BLOCK_1577092133273_INDEX_4": "5",
    "BLOCK_1577092133273_INDEX_5": "6",
    "BLOCK_1577092133273": "smart servo [INDEX]rotates to zero position",
    "BLOCK_1577092158156": "smart servo [INDEX] rotates at power[POWER]%",
    "BLOCK_1577092279792": "smart servo [INDEX] rotates to [DEG] degree at speed of [SPEED]r/min",
    "BLOCK_1577094190142": "smart servo[INDEX]rotates by[DEG]degrees at speed of [SPEED]r/min",
    "BLOCK_1577094267367_OPTION_0": "ток",
    "BLOCK_1577094267367_OPTION_1": "напряжение",
    "BLOCK_1577094267367_OPTION_2": "скорость",
    "BLOCK_1577094267367_OPTION_3": "угол",
    "BLOCK_1577094267367_OPTION_4": "температура",
    "BLOCK_1577094267367": "smart servo[INDEX]  [OPTION]",
    "VALVE_STATUS_A_STATUS_0": "власть на",
    "VALVE_STATUS_A_STATUS_1": "выключить питание",
    "valve_status_a": "набор соленоидных клапанов [PORT]статус, чтобы [STATUS]",
    "valve_status_b": "набор соленоидных клапанов [PORT] статус, чтобы [STATUS]",
    "SMALL_FUN_FAN_ROTATE_0": "спина по часовой стрелке, чтобы взорвать воздух",
    "SMALL_FUN_FAN_ROTATE_1": "спина против часовой стрелки, чтобы сосать воздух",
    "SMALL_FUN_FAN_ROTATE_2": "остановить",
    "small_fun": "Вентилятор [PORT]  [FAN_ROTATE]",
    "power": "Мощность",
    "ultrasonic_dis": "ультразвуковой датчик [PORT] СМ",
    "linefollower_status": "линия-следующий датчик [PORT]Статус",
    "COLOR_SENSOR_READ_COLOR_0": "R",
    "COLOR_SENSOR_READ_COLOR_1": "G",
    "COLOR_SENSOR_READ_COLOR_2": "B",
    "color_sensor_read": "датчик цвета[PORT] [COLOR]Значение",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_0": "белый",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_1": "красный",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_2": "жёлтый",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_3": "зелёный",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_4": "синий",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_5": "чёрный",
    "color_sensor_color_detected": "color sensor[PORT] detected[COLOR]？",
    "JOYSTICK_AXIS_X_Y_0": "ось-x",
    "JOYSTICK_AXIS_X_Y_1": "ось-y",
    "joystick": "Джойстик [PORT][AXIS_X_Y]",
    "BUTTON_PRESSED_FOUR_KEY_0": "кнопка1",
    "BUTTON_PRESSED_FOUR_KEY_1": "кнопка2",
    "BUTTON_PRESSED_FOUR_KEY_2": "кнопка3",
    "BUTTON_PRESSED_FOUR_KEY_3": "кнопка4",
    "button_pressed": "Кнопку [PORT] [FOUR_KEY] Нажата?",
    "touch_sensor_touch_detected": "сенсорный датчик [PORT] тронут?",
    "pointmeter": "Потенциометр [PORT]",
    "limitswitch_read": "предел переключатель [PORT] [SLOT]",
    "light_sensor_read": "Датчик освещенности[PORT]",
    "LIGHT_SENSOR_STATUS_0": "выключить",
    "LIGHT_SENSOR_STATUS_1": "включить",
    "light_sensor": "Датчик освещенности [PORT]СВЕТОДИОДНЫЙ статус как [STATUS]",
    "soundsensor_read": "датчик громкости[PORT]",
    "IRSENSOR_READ_PORT_0": "порт7",
    "IRSENSOR_READ_PORT_1": "порт8",
    "IRSENSOR_READ_PORT_2": "порт9",
    "IRSENSOR_READ_PORT_3": "порт10",
    "IRsensor_read": "IR receiver [PORT] (only in Arduino mode)",
    "humanIR_read": "PIR sensor [PORT] detected human's motion?",
    "tempsensor_read": "Датчик температуры[PORT] [SLOT]",
    "TEMP_MOISTURE_SENSOR_READ_TEMP_HUMITURE_0": "влажность",
    "TEMP_MOISTURE_SENSOR_READ_TEMP_HUMITURE_1": "температура",
    "temp_moisture_sensor_read": "датчик температуры/влажности [PORT] [TEMP_HUMITURE]",
    "firesensor_read": "датчик пламени[PORT]",
    "gassensor_read": "Датчик газа [PORT]",
    "GYRO_SESOR_READ_AXIS_0": "ось-x",
    "GYRO_SESOR_READ_AXIS_1": "ось-y",
    "GYRO_SESOR_READ_AXIS_2": "ось-z",
    "gyro_sesor_read": "гироскопа (на любом белом порту) [AXIS] Угол",
    "magsensor_read": "цифровой компас[PORT]",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_0": "Пресс затвор",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_1": "релиз затвора",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_2": "начать фокусировать",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_3": "остановить фокусировку",
    "shutter_set_fun": "Установите модуль затвора камеры, чтобы [SHUTTER_ACTION]",
    "sensing": "Сенсоры",
    "mpp_main": "Основная программа Мегаapi Pro",
    "match_in_automode": "конкуренция в автоматическом этапе?",
    "SET_SMART_ZERO_TITLE": "установить ноль сервопривода",
    "SET_SMART_ZERO_BTN": "принять текущую позицию за начало отсчета",
    "SET_SMART_ZERO_NO": "выбрать серийный номер",
    "SET_SMART_ZERO_BTN_LOADING": "установить положение начала отсчета...",
    "SET_SMART_ZERO_SUCCESS": "Успешной!",
    "SET_SMART_ZERO_FAIL": "Сбой при."
};