export default {
    "megapipro": "MegaPi Pro",
    "extensionName": "MegaPi Pro",
    "extensionDescription": "MegaPi Pro demo 测试",
    "firmwares_version_e0a3fed5": "在线固件",
    "UPDATE_FIRMWARE": "固件更新",
    "settings_292995a5": "设置智能舵机零点",
    "connect_fail_e3b8aead": "请确保USB线已正确连接当前设备",
    "connect_fail_0a8e963b": "请确保当前待连接设备处于开机状态",
    "connect_fail_c6b30a1c": "目前慧编程只支持连接一台设备，连接当前设备另一台已连接设备会自动断开",
    "connect_fail_9a8a4feb": "蓝牙4.0连接模式下，不支持上传模式，请先通过USB连接更新最新固件",
    "connect_fail_671017f3": "请确保您的电脑设备具备蓝牙4.0连接能力，且蓝牙4.0功能已经打开",
    "connect_fail_aad5f15d": "请确保当前待连接设备处于开机状态",
    "connect_fail_2df5ee83": "目前慧编程只支持连接一台设备，连接当前设备另一台已连接设备会自动断开",
    "upload_fail_c9f06d49": "请检查该设备的积木或代码的数据类型、参数类型、编程逻辑是否符合程序规范",
    "upload_fail_3bd7dbc4": "请检查您是否正确连接设备，可以尝试重启设备后再重新连接设备",
    "firmware_success_5a28c266": "为了保证更好的体验，您可以重启设备后重新连接设备",
    "firmware_fail_e4b56cf5": "请检查您是否正确连接设备，可以尝试重启设备后重新连接设备，再尝试更新",
    "timer": "计时器",
    "timer_reset": "计时器归零",
    "MegaPi Pro": "MegaPi Pro",
    "SEG7_SHOW_NUMBER_PORT_0": "接口6",
    "SEG7_SHOW_NUMBER_PORT_1": "接口7",
    "SEG7_SHOW_NUMBER_PORT_2": "接口8",
    "SEG7_SHOW_NUMBER_PORT_3": "接口9",
    "SEG7_SHOW_NUMBER_PORT_4": "接口10",
    "SEG7_SHOW_NUMBER_PORT_5": "接口11",
    "SEG7_SHOW_NUMBER_PORT_6": "接口12",
    "seg7_show_number": "数码管 [PORT] 显示数字 [NUMBER]",
    "mcore_show_face_time": " 表情面板 [PORT] 显示图案 [FACE_PANEL] 持续 [TIME] 秒",
    "mcore_show_face": "表情面板 [PORT] 显示图案 [FACE_PANEL]",
    "mcore_show_face_position": "表情面板 [PORT] 显示图案 [FACE_PANEL] 在x: [X] y: [Y]",
    "mcore_show_text": "表情面板 [PORT] 显示字符 [TEXT]",
    "mcore_show_text_position": "表情面板 [PORT] 显示字符 [TEXT] 在 x: [X] y: [Y]",
    "mcore_show_number": "表情面板 [PORT] 显示数字 [NUMBER]",
    "mcore_show_time": "表情面板 [PORT] 显示时间 [NUMBER1]: [NUMBER2]",
    "display": "显示",
    "LED_MODULE_SET_COLOR_LED_POSTION_0": "全部",
    "LED_MODULE_SET_COLOR_LED_POSTION_1": "1",
    "LED_MODULE_SET_COLOR_LED_POSTION_2": "2",
    "LED_MODULE_SET_COLOR_LED_POSTION_3": "3",
    "LED_MODULE_SET_COLOR_LED_POSTION_4": "4",
    "led_module_set_color": "LED模块 [PORT] 设置 [LED_POSTION] 灯颜色为：红 [R] 绿 [G]  蓝 [B]",
    "LED_STRIP_SET_COLOR_SLOT_0": "插头1",
    "LED_STRIP_SET_COLOR_SLOT_1": "插头2",
    "led_strip_set_color": "LED灯带 [PORT] [SLOT] 设置 第[POS] 个灯颜色为：红 [R] 绿 [G]  蓝 [B]",
    "soundandlight": "声光",
    "ENCODER_MOTOR_POWER_PORT_0": "接口1",
    "ENCODER_MOTOR_POWER_PORT_1": "接口2",
    "ENCODER_MOTOR_POWER_PORT_2": "接口3",
    "ENCODER_MOTOR_POWER_PORT_3": "接口4",
    "encoder_motor_power": "编码电机 [PORT] 以动力 [POWER] % 转动",
    "encoder_motor_pos": "编码电机 [PORT] 转动 [DEG] 度，以速度 [SPEED] 转每分钟",
    "encoder_motor_speed": "编码电机 [PORT]  以速度 [SPEED] 转每分钟 转动",
    "encoder_motor_get_speed": "编码电机 [PORT] 转速（转每分钟）",
    "encoder_motor_get_pos": "编码电机 [PORT] 角度位置（度）",
    "HP_ENCODER_MOTOR_POWER_SWITCH_0": "LLL",
    "HP_ENCODER_MOTOR_POWER_SWITCH_1": "LLH",
    "HP_ENCODER_MOTOR_POWER_SWITCH_2": "LHL",
    "HP_ENCODER_MOTOR_POWER_SWITCH_3": "LHH",
    "HP_ENCODER_MOTOR_POWER_SWITCH_4": "HLL",
    "HP_ENCODER_MOTOR_POWER_SWITCH_5": "HLH",
    "HP_ENCODER_MOTOR_POWER_SWITCH_6": "HHL",
    "HP_ENCODER_MOTOR_POWER_SWITCH_7": "HHH",
    "HP_ENCODER_MOTOR_POWER_SLOT_0": "电机接口1",
    "HP_ENCODER_MOTOR_POWER_SLOT_1": "电机接口2",
    "hp_encoder_motor_power": "大功率编码电机 （拨码开关 [SWITCH]   [SLOT] ）以动力 [POWER]  % 转动",
    "hp_encoder_motor_pos": "大功率编码电机（拨码开关 [SWITCH] [SLOT] ）转动 [DEG] 度，以速度 [SPEED] 转每分钟",
    "hp_encoder_motor_speed": "大功率编码电机 （拨码开关 [SWITCH] [SLOT] ）以速度 [SPEED] 转每分钟 转动",
    "hp_encoder_motor_get_speed": "大功率编码电机 (拨码开关 [SWITCH] [SLOT] ) 转速（转每分钟）",
    "hp_encoder_motor_get_pos": "大功率编码电机 （拨码开关 [SWITCH] [SLOT] ） 角度位置（度）",
    "stepper_motor_pos": "步进电机 [PORT] 转动 [STEP] 步，以速度 [SPEED] 步每秒",
    "enhanced_encoder_motor_power": "增强型编码电机 [PORT] 以动力 [POWER]% 转动",
    "enhanced_encoder_motor_speed": "增强型编码电机 [PORT] 转动速度（圈/分钟）",
    "enhanced_encoder_motor_pos": "增强型编码电机 [PORT] 当前角度位置（度）",
    "DCMOTOR_POWER_1_PORT_0": "接口1A",
    "DCMOTOR_POWER_1_PORT_1": "接口1B",
    "DCMOTOR_POWER_1_PORT_2": "接口2A",
    "DCMOTOR_POWER_1_PORT_3": "接口2B",
    "DCMOTOR_POWER_1_PORT_4": "接口3A",
    "DCMOTOR_POWER_1_PORT_5": "接口3B",
    "DCMOTOR_POWER_1_PORT_6": "接口4A",
    "DCMOTOR_POWER_1_PORT_7": "接口4B",
    "DCmotor_power_1": "直流电机 [PORT] 以动力 [POWER] %转动",
    "DCMOTOR_POWER_2_PORT_0": "M9",
    "DCMOTOR_POWER_2_PORT_1": "M10",
    "DCMOTOR_POWER_2_PORT_2": "M11",
    "DCMOTOR_POWER_2_PORT_3": "M12",
    "DCmotor_power_2": "直流电机 [PORT] 以动力 [POWER] %转动",
    "BLmotor_lock": "无刷电机 [PORT] 解锁",
    "BLmotor_power": "无刷电机 [PORT] 以动力 [POWER] %转动",
    "BLOCK_1577092133273_INDEX_0": "1",
    "BLOCK_1577092133273_INDEX_1": "2",
    "BLOCK_1577092133273_INDEX_2": "3",
    "BLOCK_1577092133273_INDEX_3": "4",
    "BLOCK_1577092133273_INDEX_4": "5",
    "BLOCK_1577092133273_INDEX_5": "6",
    "BLOCK_1577092133273": "智能舵机 [INDEX] 转动到零点",
    "BLOCK_1577092158156": "智能舵机 [INDEX] 以动力 [POWER] %转动",
    "BLOCK_1577092279792": "智能舵机 [INDEX] 转动到 [DEG] 度，速度 [SPEED] 圈每分钟",
    "BLOCK_1577094190142": "智能舵机 [INDEX] 转动 [DEG] 度，速度 [SPEED] 圈每分钟",
    "BLOCK_1577094267367_OPTION_0": "电流",
    "BLOCK_1577094267367_OPTION_1": "电压",
    "BLOCK_1577094267367_OPTION_2": "速度",
    "BLOCK_1577094267367_OPTION_3": "角度",
    "BLOCK_1577094267367_OPTION_4": "温度",
    "BLOCK_1577094267367": "智能舵机 [INDEX]  [OPTION] ",
    "VALVE_STATUS_A_STATUS_0": "通电",
    "VALVE_STATUS_A_STATUS_1": "断电",
    "valve_status_a": "电磁阀 [PORT] 设置状态为 [STATUS]",
    "valve_status_b": "电磁阀 [PORT] 设置状态为 [STATUS]",
    "SMALL_FUN_FAN_ROTATE_0": "顺时针旋转吹气",
    "SMALL_FUN_FAN_ROTATE_1": "逆时针旋转吸气",
    "SMALL_FUN_FAN_ROTATE_2": "停止",
    "small_fun": "小风扇模块 [PORT]  [FAN_ROTATE]",
    "power": "动力",
    "ultrasonic_dis": "超声波传感器 [PORT] （CM）",
    "linefollower_status": "巡线传感器 [PORT] 状态",
    "COLOR_SENSOR_READ_COLOR_0": "R",
    "COLOR_SENSOR_READ_COLOR_1": "G",
    "COLOR_SENSOR_READ_COLOR_2": "B",
    "color_sensor_read": "颜色传感器 [PORT] [COLOR] 值",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_0": "白",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_1": "红",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_2": "黄",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_3": "绿",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_4": "蓝",
    "COLOR_SENSOR_COLOR_DETECTED_COLOR_5": "黑",
    "color_sensor_color_detected": "颜色传感器 [PORT] 检测到 [COLOR] ？",
    "JOYSTICK_AXIS_X_Y_0": "X轴",
    "JOYSTICK_AXIS_X_Y_1": "Y轴",
    "joystick": "摇杆模块 [PORT][AXIS_X_Y]",
    "BUTTON_PRESSED_FOUR_KEY_0": "按键1",
    "BUTTON_PRESSED_FOUR_KEY_1": "按键2",
    "BUTTON_PRESSED_FOUR_KEY_2": "按键3",
    "BUTTON_PRESSED_FOUR_KEY_3": "按键4",
    "button_pressed": "按键模块 [PORT] [FOUR_KEY] 被按下？",
    "touch_sensor_touch_detected": "触摸传感器 [PORT] 检测到 触摸？",
    "pointmeter": "电位器模块 [PORT]",
    "limitswitch_read": "限位开关 [PORT] [SLOT]",
    "light_sensor_read": "光线传感器 [PORT]",
    "LIGHT_SENSOR_STATUS_0": "关",
    "LIGHT_SENSOR_STATUS_1": "开",
    "light_sensor": "光线传感器 [PORT]  LED 状态为 [STATUS]",
    "soundsensor_read": "音量传感器 [PORT]",
    "IRSENSOR_READ_PORT_0": "接口7",
    "IRSENSOR_READ_PORT_1": "接口8",
    "IRSENSOR_READ_PORT_2": "接口9",
    "IRSENSOR_READ_PORT_3": "接口10",
    "IRsensor_read": "红外接收模块 [PORT] （仅限Arduino模式）",
    "humanIR_read": "人体红外传感器 [PORT]检测到人的运动？",
    "tempsensor_read": "温度传感器 [PORT] [SLOT]",
    "TEMP_MOISTURE_SENSOR_READ_TEMP_HUMITURE_0": "湿度",
    "TEMP_MOISTURE_SENSOR_READ_TEMP_HUMITURE_1": "温度",
    "temp_moisture_sensor_read": "温湿度传感器 [PORT] [TEMP_HUMITURE]",
    "firesensor_read": "火焰传感器 [PORT]",
    "gassensor_read": "气体传感器 [PORT]",
    "GYRO_SESOR_READ_AXIS_0": "X轴",
    "GYRO_SESOR_READ_AXIS_1": "Y轴",
    "GYRO_SESOR_READ_AXIS_2": "Z轴",
    "gyro_sesor_read": "陀螺仪（位于任一白色接口） [AXIS] 角度",
    "magsensor_read": "电子罗盘模块 [PORT]",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_0": "按下快门",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_1": "松开快门",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_2": "开始对焦",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_3": "停止对焦",
    "shutter_set_fun": "相机快门模块 [PORT] 功能为 [SHUTTER_ACTION]",
    "sensing": "感知",
    "mpp_main": "MegaPi Pro 主程序",
    "match_in_automode": "比赛处于自动阶段？",
    "SET_SMART_ZERO_TITLE": "设置智能舵机零点",
    "SET_SMART_ZERO_BTN": "设置当前位置为舵机零点",
    "SET_SMART_ZERO_NO": "选择编号",
    "SET_SMART_ZERO_BTN_LOADING": "正在设置零点",
    "SET_SMART_ZERO_SUCCESS": "设置成功",
    "SET_SMART_ZERO_FAIL": "设置失败"
};