export default {
    "uno_shield": "Uno Shield",
    "extensionName": "Uno Shield",
    "extensionDescription": "Uno shield extension",
    "UNO_SHIELD_SET_MOTOR_POWER_PORT_0": "port1",
    "UNO_SHIELD_SET_MOTOR_POWER_PORT_1": "port2",
    "UNO_SHIELD_SET_MOTOR_POWER_PORT_2": "port9",
    "UNO_SHIELD_SET_MOTOR_POWER_PORT_3": "port10",
    "uno_shield_set_motor_power": "set motor [PORT] power [POWER]%",
    "UNO_SHIELD_SET_SERVER_ANGLE_PORT_0": "port3",
    "UNO_SHIELD_SET_SERVER_ANGLE_PORT_1": "port4",
    "UNO_SHIELD_SET_SERVER_ANGLE_PORT_2": "port6",
    "UNO_SHIELD_SET_SERVER_ANGLE_PORT_3": "port7",
    "UNO_SHIELD_SET_SERVER_ANGLE_PORT_4": "port8",
    "UNO_SHIELD_SET_SERVER_ANGLE_SLOT_0": "slot1",
    "UNO_SHIELD_SET_SERVER_ANGLE_SLOT_1": "slot2",
    "uno_shield_set_server_angle": "set servo [PORT] [SLOT] angle[DEGREE]°",
    "uno_shield_stepper_motor_pos": "set stepper motor [PORT] speed [SPEED]distance [STEP]",
    "uno_shield_run_encoder_motor": "set encoder motor [PORT] [SLOT] speed [POWER] distance [DEGREE]",
    "UNO_SHIELD_SHOW_7SEGMENTS_NUMBER_PORT_0": "port3",
    "UNO_SHIELD_SHOW_7SEGMENTS_NUMBER_PORT_1": "port7",
    "UNO_SHIELD_SHOW_7SEGMENTS_NUMBER_PORT_2": "port8",
    "uno_shield_show_7segments_number": "set 7-segment [PORT] number [NUMBER]",
    "UNO_SHIELD_SHOW_EXTERNAL_LED_RGB_LED_POSTION_0": "all",
    "UNO_SHIELD_SHOW_EXTERNAL_LED_RGB_LED_POSTION_1": "1",
    "UNO_SHIELD_SHOW_EXTERNAL_LED_RGB_LED_POSTION_2": "2",
    "UNO_SHIELD_SHOW_EXTERNAL_LED_RGB_LED_POSTION_3": "3",
    "UNO_SHIELD_SHOW_EXTERNAL_LED_RGB_LED_POSTION_4": "4",
    "uno_shield_show_external_led_rgb": "set LED [PORT] [LED_POSTION] color to red [R] green [G] blue[B]",
    "uno_shield_show_ledstrip_rbg": "set LED strip [PORT] [SLOT] [POS] color to red [R] green [G] blue [B]",
    "UNO_SHIELD_SET_LIGHT_SENSOR_LED_PORT_0": "port7",
    "UNO_SHIELD_SET_LIGHT_SENSOR_LED_PORT_1": "port8",
    "UNO_SHIELD_SET_LIGHT_SENSOR_LED_STATUS_0": "turn on",
    "UNO_SHIELD_SET_LIGHT_SENSOR_LED_STATUS_1": "turn off",
    "uno_shield_set_light_sensor_led": "set light sensor [PORT] LED status to [STATUS]",
    "UNO_SHIELD_SHUTTER_SET_FUN_SHUTTER_ACTION_0": "press shutter",
    "UNO_SHIELD_SHUTTER_SET_FUN_SHUTTER_ACTION_1": "release shutter",
    "UNO_SHIELD_SHUTTER_SET_FUN_SHUTTER_ACTION_2": "start focusing",
    "UNO_SHIELD_SHUTTER_SET_FUN_SHUTTER_ACTION_3": "stop focusing",
    "uno_shield_shutter_set_fun": "set camera shutter [PORT] status to [SHUTTER_ACTION]",
    "uno_shield_ultrasonic_dis": "ultrasonic sensor [PORT] distance",
    "uno_shield_linefollower_status": "line-following sensor [PORT]",
    "uno_shield_light_sensor_read": "light sensor [PORT]",
    "UNO_SHIELD_JOYSTICK_AXIS_X_Y_0": "x-axis",
    "UNO_SHIELD_JOYSTICK_AXIS_X_Y_1": "y-axis",
    "uno_shield_joystick": "joystick [PORT] [AXIS_X_Y]",
    "uno_shield_pointmeter": "potentiometer [PORT]",
    "uno_shield_soundsensor": "sound sensor [PORT]",
    "uno_shield_ir_sensor": "IR receiver [PORT]",
    "uno_shield_limitswitch": "limit switch [PORT] [SLOT]",
    "uno_shield_human_ir": "PIR sensor [PORT] detected human's motion?",
    "uno_shield_tempsensor": "temperature sensor [PORT] [SLOT]  ℃",
    "UNO_SHIELD_GYRO_SESOR_AXIS_0": "x-axis",
    "UNO_SHIELD_GYRO_SESOR_AXIS_1": "y-axis",
    "UNO_SHIELD_GYRO_SESOR_AXIS_2": "z-axis",
    "uno_shield_gyro_sesor": "gyroscope [AXIS] angle",
    "UNO_SHIELD_TEMP_MOISTURE_SENSOR_TEMP_HUMITURE_0": "temperature",
    "UNO_SHIELD_TEMP_MOISTURE_SENSOR_TEMP_HUMITURE_1": "humidity",
    "uno_shield_temp_moisture_sensor": "humiture sensor [PORT] [TEMP_HUMITURE]",
    "uno_shield_firesensor": "flame sensor [PORT]",
    "uno_shield_gassensor": "gas sensor [PORT]",
    "uno_shield_touch_sensor_touch_detected": "touch sensor [PORT] being touched?",
    "UNO_SHIELD_BUTTON_PRESSED_FOUR_KEY_0": "button1",
    "UNO_SHIELD_BUTTON_PRESSED_FOUR_KEY_1": "button2",
    "UNO_SHIELD_BUTTON_PRESSED_FOUR_KEY_2": "button3",
    "UNO_SHIELD_BUTTON_PRESSED_FOUR_KEY_3": "button4",
    "uno_shield_button_pressed": "button [PORT] [FOUR_KEY] pressed?",
    "uno_shield_timer": "timer",
    "uno_shield_timer_set_zero": "reset timer",
    "BLOCK_1608630189153": "UNO Shield Main Program",
    "cate_3cfb9c54": "Uno_shield"
};