export default {
    "halocode_mbuild_dualrgbcolorsensor": "Dual RGB Sensor",
    "extensionName": "Dual RGB Sensor",
    "extensionDescription": "",
    "DUAL_RGB_IS_COLOR_INDEX_0": "1",
    "DUAL_RGB_IS_COLOR_INDEX_1": "2",
    "DUAL_RGB_IS_COLOR_INDEX_2": "3",
    "DUAL_RGB_IS_COLOR_INDEX_3": "4",
    "DUAL_RGB_IS_COLOR_INDEX_4": "5",
    "DUAL_RGB_IS_COLOR_INDEX_5": "6",
    "DUAL_RGB_IS_COLOR_INDEX_6": "7",
    "DUAL_RGB_IS_COLOR_INDEX_7": "8",
    "DUAL_RGB_IS_COLOR_PROB_0": "1",
    "DUAL_RGB_IS_COLOR_PROB_1": "2",
    "DUAL_RGB_IS_COLOR_COLOR_0": "white",
    "DUAL_RGB_IS_COLOR_COLOR_1": "red",
    "DUAL_RGB_IS_COLOR_COLOR_2": "yellow",
    "DUAL_RGB_IS_COLOR_COLOR_3": "green",
    "DUAL_RGB_IS_COLOR_COLOR_4": "cyan",
    "DUAL_RGB_IS_COLOR_COLOR_5": "blue",
    "DUAL_RGB_IS_COLOR_COLOR_6": "purple",
    "DUAL_RGB_IS_COLOR_COLOR_7": "black",
    "DUAL_RGB_IS_COLOR": "dual RGB sensor [index] probe[prob] detects color [color] ?",
    "DUAL_RGB_GET_RGB_VALUE_INDEX_0": "1",
    "DUAL_RGB_GET_RGB_VALUE_INDEX_1": "2",
    "DUAL_RGB_GET_RGB_VALUE_INDEX_2": "3",
    "DUAL_RGB_GET_RGB_VALUE_COLOR_0": "red",
    "DUAL_RGB_GET_RGB_VALUE_COLOR_1": "green",
    "DUAL_RGB_GET_RGB_VALUE_COLOR_2": "blue",
    "DUAL_RGB_GET_RGB_VALUE": "dual RGB sensor [index] probe[prob] detects [color] color value",
    "DUAL_RGB_GET_INTENSITY": "dual RGB sensor [index] probe[prob] detects ambient light intensity",
    "DUAL_RGB_GET_INFLECTION_INTENSITY": "dual RGB sensor [index] probe[prob]detects reflected light intensity",
    "DUAL_RGB_SET_SUPPLEMENT_LIGHT_WITH_FACE": "dual RGB sensor [index] probe[prob] sets fill light to [color]",
    "DUAL_RGB_SET_SUPPLEMENT_LIGHT_WITH_RGB_INDEX_0": "1",
    "DUAL_RGB_SET_SUPPLEMENT_LIGHT_WITH_RGB": "dual RGB sensor [index] probe[prob] sets fill light toR: [r] G: [g] B: [b]",
    "cate_a5be49dc": "Dual RGB Sensor",
    "BLOCK_1547779213407": "servo [ID] rotates to [angle] (°)",
    "BLOCK_1547779701469": "speaker [ID]  play sound [audio]",
    "BLOCK_1547779887637": "speaker [ID]  play audio file [audio] until done",
    "BLOCK_1547781171854": "speaker [ID]  set volume to [volume] %",
    "BLOCK_1547779298912": "servo [ID] rotates to 0 (°)",
    "halocode_mbuild": "module",
    "cate_9a6d8599": "Action",
    "BLOCK_1547779701469_AUDIO_0": "hello",
    "BLOCK_1547779701469_AUDIO_1": "hi",
    "BLOCK_1547779701469_AUDIO_2": "bye",
    "BLOCK_1547779701469_AUDIO_3": "yeah",
    "BLOCK_1547779701469_AUDIO_4": "wow",
    "BLOCK_1547779701469_AUDIO_5": "laugh",
    "BLOCK_1547779701469_AUDIO_6": "Sing",
    "BLOCK_1547779701469_AUDIO_7": "sad",
    "cate_a85789e6": "speaker",
    "BLOCK_1547779726695": "speaker [ID]  play sound [audio] until done"
};