export default {
    "halocode_mbuild_dualrgbcolorsensor": "Double capteur RGB",
    "extensionName": "Double capteur RGB",
    "extensionDescription": "",
    "DUAL_RGB_IS_COLOR_INDEX_0": "1",
    "DUAL_RGB_IS_COLOR_INDEX_1": "2",
    "DUAL_RGB_IS_COLOR_INDEX_2": "3",
    "DUAL_RGB_IS_COLOR_INDEX_3": "4",
    "DUAL_RGB_IS_COLOR_INDEX_4": "5",
    "DUAL_RGB_IS_COLOR_INDEX_5": "6",
    "DUAL_RGB_IS_COLOR_INDEX_6": "7",
    "DUAL_RGB_IS_COLOR_INDEX_7": "8",
    "DUAL_RGB_IS_COLOR_PROB_0": "1",
    "DUAL_RGB_IS_COLOR_PROB_1": "2",
    "DUAL_RGB_IS_COLOR_COLOR_0": "blanc",
    "DUAL_RGB_IS_COLOR_COLOR_1": "rouge",
    "DUAL_RGB_IS_COLOR_COLOR_2": "jaune",
    "DUAL_RGB_IS_COLOR_COLOR_3": "vert",
    "DUAL_RGB_IS_COLOR_COLOR_4": "Cyan",
    "DUAL_RGB_IS_COLOR_COLOR_5": "bleu",
    "DUAL_RGB_IS_COLOR_COLOR_6": "violet",
    "DUAL_RGB_IS_COLOR_COLOR_7": "noir",
    "DUAL_RGB_IS_COLOR": "double capteur RGB [index] sonde[prob] détecte la couleur [color] ?",
    "DUAL_RGB_GET_RGB_VALUE_INDEX_0": "1",
    "DUAL_RGB_GET_RGB_VALUE_INDEX_1": "2",
    "DUAL_RGB_GET_RGB_VALUE_INDEX_2": "3",
    "DUAL_RGB_GET_RGB_VALUE_COLOR_0": "rouge",
    "DUAL_RGB_GET_RGB_VALUE_COLOR_1": "vert",
    "DUAL_RGB_GET_RGB_VALUE_COLOR_2": "bleu",
    "DUAL_RGB_GET_RGB_VALUE": "double capteur RGB [index] sonde[prob] Détecte [color] valeur de couleur",
    "DUAL_RGB_GET_INTENSITY": "double capteur RGB [index] sonde[prob] détecte l’intensité de la lumière ambiante",
    "DUAL_RGB_GET_INFLECTION_INTENSITY": "double capteur RGB [index] sonde[prob]détecte l’intensité lumineuse réfléchie",
    "DUAL_RGB_SET_SUPPLEMENT_LIGHT_WITH_FACE": "double capteur RGB [index] sonde[prob] définit la lumière de remplissage pour [color]",
    "DUAL_RGB_SET_SUPPLEMENT_LIGHT_WITH_RGB_INDEX_0": "1",
    "DUAL_RGB_SET_SUPPLEMENT_LIGHT_WITH_RGB": "double capteur RGB [index] sonde[prob] définit la lumière de remplissage toR: [r] gr: [g] bien: [b]",
    "cate_a5be49dc": "Double capteur RGB",
    "BLOCK_1547779213407": "orienter le servo-moteur [ID] à un angle de [angle] (°)",
    "BLOCK_1547779701469": "haut-parleur [ID]  jouer le son [audio]",
    "BLOCK_1547779887637": "haut-parleur [ID]  lire le fichier audio [audio] jusqu'au bout",
    "BLOCK_1547781171854": "haut-parleur [ID]  Réglez le volume sur [volume] %"
};