export default {
    "halocode_mbuild_dualrgbcolorsensor": "Ikileýin RGB duýujy enjam",
    "extensionName": "Ikileýin RGB duýujy enjam",
    "extensionDescription": "",
    "DUAL_RGB_IS_COLOR_INDEX_0": "1",
    "DUAL_RGB_IS_COLOR_INDEX_1": "2",
    "DUAL_RGB_IS_COLOR_INDEX_2": "3",
    "DUAL_RGB_IS_COLOR_INDEX_3": "4",
    "DUAL_RGB_IS_COLOR_INDEX_4": "5",
    "DUAL_RGB_IS_COLOR_INDEX_5": "6",
    "DUAL_RGB_IS_COLOR_INDEX_6": "7",
    "DUAL_RGB_IS_COLOR_INDEX_7": "8",
    "DUAL_RGB_IS_COLOR_PROB_0": "1",
    "DUAL_RGB_IS_COLOR_PROB_1": "2",
    "DUAL_RGB_IS_COLOR_COLOR_0": "ak",
    "DUAL_RGB_IS_COLOR_COLOR_1": "gyzyl",
    "DUAL_RGB_IS_COLOR_COLOR_2": "sary",
    "DUAL_RGB_IS_COLOR_COLOR_3": "ýaşyl",
    "DUAL_RGB_IS_COLOR_COLOR_4": "pöwrize",
    "DUAL_RGB_IS_COLOR_COLOR_5": "gök",
    "DUAL_RGB_IS_COLOR_COLOR_6": "benewşe",
    "DUAL_RGB_IS_COLOR_COLOR_7": "gara",
    "DUAL_RGB_IS_COLOR": "[index] belgili Ikileýin RGB duýujy enjamynyň [prob] probasy [color] reňkini duýýarmy ?",
    "DUAL_RGB_GET_RGB_VALUE_INDEX_0": "1",
    "DUAL_RGB_GET_RGB_VALUE_INDEX_1": "2",
    "DUAL_RGB_GET_RGB_VALUE_INDEX_2": "3",
    "DUAL_RGB_GET_RGB_VALUE_COLOR_0": "gyzyl",
    "DUAL_RGB_GET_RGB_VALUE_COLOR_1": "ýaşyl",
    "DUAL_RGB_GET_RGB_VALUE_COLOR_2": "gök",
    "DUAL_RGB_GET_RGB_VALUE": "[index] belgili Ikileýin RGB duýujy enjamynyň [prob] probasy [color] reňk bahasyny duýýar",
    "DUAL_RGB_GET_INTENSITY": "[index] belgili Ikileýin RGB duýujy enjamynyň [prob] probasy daşky ýagtylyk kuwwatlylygyny duýýar",
    "DUAL_RGB_GET_INFLECTION_INTENSITY": "[index] belgili Ikileýin RGB duýujy enjamynyň [prob] probasy gaýtarylýan ýagtylyk kuwwatlylygyny duýýar",
    "DUAL_RGB_SET_SUPPLEMENT_LIGHT_WITH_FACE": "[index] belgili Ikileýin RGB duýujy enjamynda [prob] probasyny [color] reňki bilen doldur",
    "DUAL_RGB_SET_SUPPLEMENT_LIGHT_WITH_RGB_INDEX_0": "1",
    "DUAL_RGB_SET_SUPPLEMENT_LIGHT_WITH_RGB": "[index] belgili Ikileýin RGB duýujy enjamynda [prob] probasyny R: [r] G: [g] B: [b] reňki bilen doldur",
    "cate_a5be49dc": "Ikileýin RGB duýujy enjam",
    "BLOCK_1547779213407": "[ID] serwo-hereketlendiriji [angle] burçuna çenli aýlanýar (°)",
    "BLOCK_1547779701469": "[ID] dinamigi [audio] sesini aýtdyrýar",
    "BLOCK_1547779887637": "[ID] dinamigi [audio] ses faýlyny soňuna çenli aýtdyrýar",
    "BLOCK_1547781171854": "[ID] dinamigi ses kuwwatlylygyny [volume] % edip sazlaýar"
};