export default {
    "halocode_mbuild_dualrgbcolorsensor": "雙顏色感測器",
    "extensionName": "雙顏色感測器",
    "extensionDescription": "",
    "DUAL_RGB_IS_COLOR_INDEX_0": "1",
    "DUAL_RGB_IS_COLOR_INDEX_1": "2",
    "DUAL_RGB_IS_COLOR_INDEX_2": "3",
    "DUAL_RGB_IS_COLOR_INDEX_3": "4",
    "DUAL_RGB_IS_COLOR_INDEX_4": "5",
    "DUAL_RGB_IS_COLOR_INDEX_5": "6",
    "DUAL_RGB_IS_COLOR_INDEX_6": "7",
    "DUAL_RGB_IS_COLOR_INDEX_7": "8",
    "DUAL_RGB_IS_COLOR_PROB_0": "1",
    "DUAL_RGB_IS_COLOR_PROB_1": "2",
    "DUAL_RGB_IS_COLOR_COLOR_0": "白",
    "DUAL_RGB_IS_COLOR_COLOR_1": "紅色",
    "DUAL_RGB_IS_COLOR_COLOR_2": "黃色",
    "DUAL_RGB_IS_COLOR_COLOR_3": "綠色",
    "DUAL_RGB_IS_COLOR_COLOR_4": "青色",
    "DUAL_RGB_IS_COLOR_COLOR_5": "藍色",
    "DUAL_RGB_IS_COLOR_COLOR_6": "紫色",
    "DUAL_RGB_IS_COLOR_COLOR_7": "黑",
    "DUAL_RGB_IS_COLOR": "雙顏色感測器 [index] 探頭 [prob] 偵測 [color] 顏色?",
    "DUAL_RGB_GET_RGB_VALUE_INDEX_0": "1",
    "DUAL_RGB_GET_RGB_VALUE_INDEX_1": "2",
    "DUAL_RGB_GET_RGB_VALUE_INDEX_2": "3",
    "DUAL_RGB_GET_RGB_VALUE_COLOR_0": "紅色",
    "DUAL_RGB_GET_RGB_VALUE_COLOR_1": "綠色",
    "DUAL_RGB_GET_RGB_VALUE_COLOR_2": "藍色",
    "DUAL_RGB_GET_RGB_VALUE": "雙顏色感測器 [index] 探頭 [prob] 偵測 [color] 顏色數值",
    "DUAL_RGB_GET_INTENSITY": "雙顏色感測器 [index] 探頭 [prob] 偵測環境光強度",
    "DUAL_RGB_GET_INFLECTION_INTENSITY": "雙顏色感測器 [index] 探頭 [prob] 偵測反射光強度",
    "DUAL_RGB_SET_SUPPLEMENT_LIGHT_WITH_FACE": "雙顏色感測器 [index] 探頭 [prob] 設定補光顏色為 [color]",
    "DUAL_RGB_SET_SUPPLEMENT_LIGHT_WITH_RGB_INDEX_0": "1",
    "DUAL_RGB_SET_SUPPLEMENT_LIGHT_WITH_RGB": "雙顏色感測器 [index] 探頭 [prob] 設定補光顏色為 紅: [r] 綠: [g] 藍: [b]",
    "cate_a5be49dc": "雙顏色感測器",
    "BLOCK_1547779213407": "伺服馬達 [ID] 旋轉到 [angle] 度",
    "BLOCK_1547779701469": "喇叭 [ID] 播放 [audio] 聲音",
    "BLOCK_1547779887637": "喇叭 [ID] 播放 [audio] 音樂檔直到結束",
    "BLOCK_1547781171854": "喇叭 [ID] 的音量設定為 [volume] %"
};