export default {
    "auriga_mbuild_camera": "Smart Camera",
    "extensionName": "Smart Camera",
    "extensionDescription": "Smart camera extension for Auriga",
    "auriga_1566200222835": "check camera image",
    "AURIGA_CAMERA_SWITCH_COLOR_MODE_PORT_0": "port6",
    "AURIGA_CAMERA_SWITCH_COLOR_MODE_PORT_1": "port7",
    "AURIGA_CAMERA_SWITCH_COLOR_MODE_PORT_2": "port8",
    "AURIGA_CAMERA_SWITCH_COLOR_MODE_PORT_3": "port9",
    "AURIGA_CAMERA_SWITCH_COLOR_MODE_PORT_4": "port10",
    "auriga_camera_switch_color_mode": "smart camera [PORT] switch to color block detection mode",
    "AURIGA_CAMERA_RECOGNIZE_COLOR_SIG_0": "1",
    "AURIGA_CAMERA_RECOGNIZE_COLOR_SIG_1": "2",
    "AURIGA_CAMERA_RECOGNIZE_COLOR_SIG_2": "3",
    "AURIGA_CAMERA_RECOGNIZE_COLOR_SIG_3": "4",
    "AURIGA_CAMERA_RECOGNIZE_COLOR_SIG_4": "5",
    "AURIGA_CAMERA_RECOGNIZE_COLOR_SIG_5": "6",
    "AURIGA_CAMERA_RECOGNIZE_COLOR_SIG_6": "7",
    "auriga_camera_recognize_color": "smart camera [PORT] starts learning color block [SIG] until button pressed",
    "AURIGA_CAMERA_CENTER_SATURATION_FIELDMENU_2_0": "center",
    "AURIGA_CAMERA_CENTER_SATURATION_FIELDMENU_2_1": "average",
    "AURIGA_CAMERA_CENTER_SATURATION_FIELDMENU_1_0": "saturation",
    "AURIGA_CAMERA_CENTER_SATURATION_FIELDMENU_1_1": "R value",
    "AURIGA_CAMERA_CENTER_SATURATION_FIELDMENU_1_2": "G value",
    "AURIGA_CAMERA_CENTER_SATURATION_FIELDMENU_1_3": "B value",
    "AURIGA_CAMERA_CENTER_SATURATION_FIELDMENU_1_4": "Grayscale",
    "auriga_camera_center_saturation": "smart camera [fieldMenu_1] image [fieldMenu_2]'s [fieldMenu_1]",
    "auriga_camera_get_color": "smart camera [PORT] detected color block [SIG]?",
    "AURIGA_CAMERA_COLOR_IN_CENTER_LOCATION_0": "center",
    "AURIGA_CAMERA_COLOR_IN_CENTER_LOCATION_1": "upper",
    "AURIGA_CAMERA_COLOR_IN_CENTER_LOCATION_2": "bottom",
    "AURIGA_CAMERA_COLOR_IN_CENTER_LOCATION_3": "left",
    "AURIGA_CAMERA_COLOR_IN_CENTER_LOCATION_4": "right",
    "auriga_camera_color_in_center": "smart camera [PORT] detected color block [SIG] at [LOCATION] of the image？",
    "AURIGA_CAMERA_COLOR_COORDINATE_CCCINFO_0": "x-coordinate",
    "AURIGA_CAMERA_COLOR_COORDINATE_CCCINFO_1": "y-coordinate",
    "AURIGA_CAMERA_COLOR_COORDINATE_CCCINFO_2": "width",
    "AURIGA_CAMERA_COLOR_COORDINATE_CCCINFO_3": "height",
    "auriga_camera_color_coordinate": "smart camera [PORT] detected [CCCINFO] of color block [SIG]",
    "AURIGA_CAMERA_TURN_ON_LIGHT_STATE_0": "turn on",
    "AURIGA_CAMERA_TURN_ON_LIGHT_STATE_1": "turn off",
    "auriga_camera_turn_on_light": "smart camera [PORT]   [STATE] fill light",
    "auriga_camera_set_white_balance": "smart camera [PORT] resets white balance",
    "cate_6aae53c0": "Color Block Detect",
    "auriga_camera_1566200222835": "check camera image",
    "auriga_camera_switch_line_qrcode_mode": "smart camera [PORT] switch to line/label tracking mode",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_0": "(1) forward",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_1": "(2) backward",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_2": "(3) turn left",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_3": "(4) turn right",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_4": "(5) stop",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_5": "(6) plus sign",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_6": "(7) minus sign",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_7": "(8) question mark",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_8": "(9) red heart",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_9": "(10) A",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_10": "(11) B",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_11": "(12) C",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_12": "(13) ①",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_13": "(14) ②",
    "AURIGA_CAMERA_GET_QRCODE_MOVE_BARCODE_14": "(15) ③",
    "auriga_camera_get_qrcode_move": "smart camera [PORT]detected label [BARCODE]？",
    "AURIGA_CAMERA_GET_QRCODE_COORDINATE_BARCODEINFO_0": "x",
    "AURIGA_CAMERA_GET_QRCODE_COORDINATE_BARCODEINFO_1": "y",
    "auriga_camera_get_qrcode_coordinate": "label [BARCODE]'s [BARCODEINFO] coordinate returned by smart camera [PORT]",
    "AURIGA_CAMERA_LINE_START_COORDINATE_LINEINFO_0": "start's x coordinate",
    "AURIGA_CAMERA_LINE_START_COORDINATE_LINEINFO_1": "start's y coordinate",
    "AURIGA_CAMERA_LINE_START_COORDINATE_LINEINFO_2": "end's x coordinate",
    "AURIGA_CAMERA_LINE_START_COORDINATE_LINEINFO_3": "end's y coordinate",
    "auriga_camera_line_start_coordinate": "smart camera [PORT] current line's [LINEINFO]",
    "auriga_camera_get_cross": "smart camera [PORT] detected cross-point?",
    "auriga_camera_corss_coordinate": " cross point's [COORDINATES] coordinate returned by smart camera [PORT]",
    "auriga_camera_get_branch_num": "number of cross-points returned by smart camera [PORT]",
    "auriga_camera_get_branch_angle": "angle of number [NUMBER]cross-point returned by smart camera [PORT]",
    "AURIGA_CAMERA_SET_LINE_MODE_LINEMODE_0": "dark line on light background",
    "AURIGA_CAMERA_SET_LINE_MODE_LINEMODE_1": "light line on dark background",
    "auriga_camera_set_line_mode": "smart camera[PORT]sets line tracking mode to [LINEMODE]",
    "auriga_camera_1566200454757": "smart camera [PORT] sets preferred angle to [ANGLE]",
    "auriga_camera_1566200474887": "smart camera [PORT] current preferred angle (°)",
    "cate_aff8824d": "Line/label Tracking",
    "auriga_camera_set_kp": "smart camera [PORT] sets Kp in motor differential speed calculation to [KP]",
    "auriga_camera_follow_color": "smart camera [PORT] calculates motor differential speed (auto follows color block [SIG] to [LOCATION] axis [NUMBER])",
    "auriga_camera_follow_qrcode": "smart camera [PORT] calculates motor differential speed (auto follows label [BARCODE] to [LOCATION] axis [NUMBER])",
    "auriga_camera_get_diff_speed": "smart camera [PORT] calculates motor differential speed (targets the line-following section)",
    "auriga_camera_lock_color": "smart camera [PORT] targets area near color block [SIG] to [LOCATION] axis [NUMBER]?",
    "auriga_camera_lock_qrcode": "smart camera [PORT] targets area near label [BARCODE] to [LOCATION] axis [NUMBER]?",
    "cate_41d9cfb5": "Event-specific Smart Camera",
    "BLOCK_1566199596519": "smart camera [PORT]switch to color block detection mode",
    "BLOCK_1566200061809": "smart camera [PORT] starts learning color block [SIG] until button pressed",
    "BLOCK_1566200149400": "smart camera [PORT] detected [CCCINFO] of color block [SIG]",
    "BLOCK_1566200281367_BARCODE_0": "(1) forward",
    "BLOCK_1566200281367_BARCODE_1": "(2) backward",
    "BLOCK_1566200281367_BARCODE_2": "(3) turn left",
    "BLOCK_1566200281367_BARCODE_3": "(4) turn right",
    "BLOCK_1566200281367_BARCODE_4": "(5) stop",
    "BLOCK_1566200281367_BARCODE_5": "(6) plus sign",
    "BLOCK_1566200281367_BARCODE_6": "(7) minus sign",
    "BLOCK_1566200281367_BARCODE_7": "(8) question mark",
    "BLOCK_1566200281367_BARCODE_8": "(9) red heart",
    "BLOCK_1566200281367_BARCODE_9": "(10) A",
    "BLOCK_1566200281367_BARCODE_10": "(11) B",
    "BLOCK_1566200281367_BARCODE_11": "(12) C",
    "BLOCK_1566200281367_BARCODE_12": "(13) ①",
    "BLOCK_1566200281367_BARCODE_13": "(14) ②",
    "BLOCK_1566200281367_BARCODE_14": "(15) ③",
    "BLOCK_1566200281367": "smart camera [PORT]detected label [BARCODE]？",
    "BLOCK_1566200305130": "smart camera [PORT] detected label [BARCODE]'s [BARCODEINFO] coordinate",
    "BLOCK_1566200324089": "smart camera[PORT] current line's [LINEINFO]",
    "BLOCK_1566200343169": "smart camera[PORT]detected cross-point？",
    "BLOCK_1566200380110": "smart camera[PORT]detected cross point's [COORDINATES] coordinate",
    "BLOCK_1566200411758": "smart camera [PORT]  [NUMBER]-numbered branch road's angle",
    "BLOCK_1566200440316": "smart camera[PORT] sets line tracking mode to[LINEMODE]",
    "BLOCK_1567596489390": "smart camera [PORT] calculates motor differential speed (auto follows color block[SIG] to [LOCATION] axis [NUMBER] )",
    "BLOCK_1567596489391": "smart camera [PORT] calculates motor differential speed (auto follows label [BARCODE] to [LOCATION] axis [NUMBER])",
    "BLOCK_1567596489392": "smart camera[PORT]targets area near color block [SIG] to[LOCATION] axis [NUMBER] ?",
    "BLOCK_1567596489393": "smart camera[PORT] targets area near label[BARCODE] to [LOCATION] axis [NUMBER] ?"
};