export default {
    "rgb_linefollower_rj25": "RGB Lijnvolger",
    "extensionName": "RGB Lijnvolger",
    "extensionDescription": "RGB Lijnvolger",
    "RGB_LINEFOLLOW_INIT_SENSOR_ID_0": "1",
    "RGB_LINEFOLLOW_INIT_SENSOR_ID_1": "2",
    "RGB_LINEFOLLOW_INIT_SENSOR_ID_2": "3",
    "RGB_LINEFOLLOW_INIT_SENSOR_ID_3": "4",
    "RGB_LINEFOLLOW_INIT_PORT_0": "poort1",
    "RGB_LINEFOLLOW_INIT_PORT_1": "poort2",
    "RGB_LINEFOLLOW_INIT_PORT_2": "poort3",
    "RGB_LINEFOLLOW_INIT_PORT_3": "poort4",
    "RGB_LINEFOLLOW_INIT_PORT_4": "poort5",
    "RGB_LINEFOLLOW_INIT_PORT_5": "poort6",
    "RGB_LINEFOLLOW_INIT_PORT_6": "poort7",
    "RGB_LINEFOLLOW_INIT_PORT_7": "poort8",
    "RGB_LINEFOLLOW_INIT_PORT_8": "poort9",
    "RGB_LINEFOLLOW_INIT_PORT_9": "poort10",
    "RGB_LINEFOLLOW_INIT_PORT_10": "port11",
    "RGB_LINEFOLLOW_INIT_PORT_11": "port12",
    "rgb_linefollow_init": "initialiseren RGB lijnvolger [SENSOR_ID] : op [PORT]",
    "rgb_linefollow_turning_sens": "RGB lijnvolger[SENSOR_ID] : (default lijnvolgend) zet draai gevoeligheid op [SENS]",
    "rgb_linefollow_speed_diff": "RGB-lijnvolger[SENSOR_ID]: (standaardregel volgende) motor differentiële snelheid",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_0": "0000",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_1": "0001",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_2": "0010",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_3": "0011",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_4": "0100",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_5": "0101",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_6": "0110",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_7": "0111",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_8": "1000",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_9": "1001",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_10": "1010",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_11": "1011",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_12": "1100",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_13": "1101",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_14": "1110",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_15": "1111",
    "rgb_linefollow_sensor_status": "RGB-lijnvolger [SENSOR_ID]: de status van de sonde zoals (RGB4 ~ RGB1) [SENSOR_STATUS]",
    "RGB_LINEFOLLOW_BACKGROUND_DETECT_CHANNEL_0": "RGB1",
    "RGB_LINEFOLLOW_BACKGROUND_DETECT_CHANNEL_1": "RGB2",
    "RGB_LINEFOLLOW_BACKGROUND_DETECT_CHANNEL_2": "RGB3",
    "RGB_LINEFOLLOW_BACKGROUND_DETECT_CHANNEL_3": "RGB4",
    "rgb_linefollow_background_detect": "RGB-lijnvolger [SENSOR_ID]: sonde[CHANNEL] detecteert achtergrondkleur?",
    "RGB_LINEFOLLOW_SET_COLOR_COLOR_0": "rood",
    "RGB_LINEFOLLOW_SET_COLOR_COLOR_1": "groen",
    "RGB_LINEFOLLOW_SET_COLOR_COLOR_2": "blauw",
    "rgb_linefollow_set_color": "RGB-lijnvolger [SENSOR_ID]: zet doelkleur en invullicht op [COLOR]",
    "rgb_linefollow_get_data": "RGB lijnvolger [SENSOR_ID] : sonde[CHANNEL] waarde",
    "rgb_linefollow_sensor": "RGB Lijnvolger"
};