export default {
    "rgb_linefollower_rj25": "RGB Line Follower",
    "extensionName": "RGB Line Follower",
    "extensionDescription": "RGB Line Follower",
    "RGB_LINEFOLLOW_INIT_SENSOR_ID_0": "1",
    "RGB_LINEFOLLOW_INIT_SENSOR_ID_1": "2",
    "RGB_LINEFOLLOW_INIT_SENSOR_ID_2": "3",
    "RGB_LINEFOLLOW_INIT_SENSOR_ID_3": "4",
    "RGB_LINEFOLLOW_INIT_PORT_0": "порт1",
    "RGB_LINEFOLLOW_INIT_PORT_1": "порт2",
    "RGB_LINEFOLLOW_INIT_PORT_2": "порт3",
    "RGB_LINEFOLLOW_INIT_PORT_3": "порт4",
    "RGB_LINEFOLLOW_INIT_PORT_4": "порт5",
    "RGB_LINEFOLLOW_INIT_PORT_5": "порт6",
    "RGB_LINEFOLLOW_INIT_PORT_6": "порт7",
    "RGB_LINEFOLLOW_INIT_PORT_7": "порт8",
    "RGB_LINEFOLLOW_INIT_PORT_8": "порт9",
    "RGB_LINEFOLLOW_INIT_PORT_9": "порт10",
    "RGB_LINEFOLLOW_INIT_PORT_10": "порт11",
    "RGB_LINEFOLLOW_INIT_PORT_11": "порт12",
    "rgb_linefollow_init": "инициализация линии RGB line follower [SENSOR_ID] : в [PORT]",
    "rgb_linefollow_turning_sens": "RGB line follower[SENSOR_ID] : (по умолчанию следующая строка) установите чувствительность поворота к [SENS]",
    "rgb_linefollow_speed_diff": "RGB линия последователем[SENSOR_ID]: (по умолчанию следующая строка) дифференциальный скорость двигателя",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_0": "0000",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_1": "0001",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_2": "0010",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_3": "0011",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_4": "0100",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_5": "0101",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_6": "0110",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_7": "0111",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_8": "1000",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_9": "1001",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_10": "1010",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_11": "1011",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_12": "1100",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_13": "1101",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_14": "1110",
    "RGB_LINEFOLLOW_SENSOR_STATUS_SENSOR_STATUS_15": "1111",
    "rgb_linefollow_sensor_status": "RGB линия последователем [SENSOR_ID]: Состояние зонда как (RGB4 ~ RGB1) [SENSOR_STATUS]",
    "RGB_LINEFOLLOW_BACKGROUND_DETECT_CHANNEL_0": "RGB1",
    "RGB_LINEFOLLOW_BACKGROUND_DETECT_CHANNEL_1": "RGB2",
    "RGB_LINEFOLLOW_BACKGROUND_DETECT_CHANNEL_2": "RGB3",
    "RGB_LINEFOLLOW_BACKGROUND_DETECT_CHANNEL_3": "RGB4",
    "rgb_linefollow_background_detect": "RGB line follower [SENSOR_ID]: зонд[CHANNEL] обнаруживает цвет фона?",
    "RGB_LINEFOLLOW_SET_COLOR_COLOR_0": "красный",
    "RGB_LINEFOLLOW_SET_COLOR_COLOR_1": "зелёный",
    "RGB_LINEFOLLOW_SET_COLOR_COLOR_2": "синий",
    "rgb_linefollow_set_color": "RGB line follower [SENSOR_ID]: установить целевой цвет и заполнить свет [COLOR]",
    "rgb_linefollow_get_data": "RGB line follower [SENSOR_ID] : зонд[CHANNEL] Возвращаемое значение",
    "rgb_linefollow_sensor": "RGB Line Follower"
};