export default {
    "megapi_all": "Maker's Platform",
    "extensionName": "Maker's Platform",
    "extensionDescription": "mBot Ranger Extensions Collection",
    "MEGAPI_RUN_SERVO_PORT_0": "port6",
    "MEGAPI_RUN_SERVO_PORT_1": "port7",
    "MEGAPI_RUN_SERVO_PORT_2": "port8",
    "MEGAPI_RUN_SERVO_SLOT_0": "slot1",
    "MEGAPI_RUN_SERVO_SLOT_1": "slot2",
    "megapi_run_servo": "[ICON] servo [PORT] [SLOT] angle [DEGREE] degree",
    "MEGAPI_RUN_FAN_FAN_ROTATE_0": "clockwise",
    "MEGAPI_RUN_FAN_FAN_ROTATE_1": "anticlockwise",
    "MEGAPI_RUN_FAN_FAN_ROTATE_2": "stop",
    "megapi_run_fan": "[ICON] fan [PORT] [FAN_ROTATE] rotates",
    "MEGAPI_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "all",
    "MEGAPI_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MEGAPI_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MEGAPI_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MEGAPI_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "megapi_show_external_led_time": "[ICON] RGB LED [PORT] lights up LED[LED_POSTION] with color [COLOR]for [TIME]secs",
    "megapi_show_external_led": "[ICON] RGB LED [PORT] lights up LED [LED_POSTION] with color [COLOR]",
    "megapi_show_external_led_rgb": "[ICON] RGB LED [PORT] lights up LED [LED_POSTION] with red [R] green [G] blue[B]",
    "MEGAPI_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "red",
    "MEGAPI_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "orange",
    "MEGAPI_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "yellow",
    "MEGAPI_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "green",
    "MEGAPI_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "cyan",
    "MEGAPI_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "blue",
    "MEGAPI_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "purple",
    "MEGAPI_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "black",
    "megapi_show_all_ledstrip_color": "[ICON] LED strip [PORT] [SLOT] all lights up with color [COLOR_LIST]",
    "megapi_show_ledstrip_color": "[ICON] LED strip [PORT] [SLOT] [POS] lights up with color [COLOR_LIST]",
    "megapi_show_ledstrip_rbg": "[ICON] LED strip [PORT] [SLOT] [POS] lights up with red [R] green [G] blue [B]",
    "megapi_show_7segments_number": "[ICON] 7-segment [PORT] displays number [NUMBER]",
    "megapi_detect_external_light": "[ICON] light sensor [PORT] light intensity",
    "megapi_detect_external_loudness": "[ICON] sound sensor [PORT]volume",
    "megapi_detec_temperature": "[ICON] temperature sensor [PORT] [SLOT] temperature（℃）",
    "MEGAPI_DETECT_HUMITURE_TEMP_HUMITURE_0": "humidity",
    "MEGAPI_DETECT_HUMITURE_TEMP_HUMITURE_1": "temperature",
    "megapi_detect_humiture": "[ICON] humiture sensor [PORT] [TEMP_HUMITURE]",
    "megapi_event_touch": "[ICON] touch sensor [PORT] touched?",
    "megapi_detect_compass": "[ICON] electronic compass [PORT]to north",
    "megapi_detect_flame": "[ICON]flame sensor[PORT]value",
    "megapi_detect_gas": "[ICON] gas sensor [PORT] value",
    "megapi_event_pir_motion": "[ICON] PIR sensor[PORT]detected human motion?",
    "MEGAPI_EVENT_BUTTON_PRESS_FOUR_KEY_0": "button1",
    "MEGAPI_EVENT_BUTTON_PRESS_FOUR_KEY_1": "button2",
    "MEGAPI_EVENT_BUTTON_PRESS_FOUR_KEY_2": "button3",
    "MEGAPI_EVENT_BUTTON_PRESS_FOUR_KEY_3": "button4",
    "megapi_event_button_press": "[ICON] button [PORT] [FOUR_KEY] pressed?",
    "megapi_event_limit_switch": "[ICON] limit switch [PORT] [SLOT] pressed？",
    "megapi_detect_potentiometer": "[ICON] potentiometer [PORT]value",
    "MEGAPI_DETECT_JOYSTICK_AXIS_X_Y_0": "x-axis",
    "MEGAPI_DETECT_JOYSTICK_AXIS_X_Y_1": "y-axis",
    "megapi_detect_joystick": "[ICON] joystick [PORT] [AXIS_X_Y] value",
    "megapi_detect_infrared": "[ICON] IR receiver [PORT]",
    "MEGAPI_DETECT_PM25_SENSOR_OPTION_0": "PM1.0",
    "MEGAPI_DETECT_PM25_SENSOR_OPTION_1": "PM2.5",
    "MEGAPI_DETECT_PM25_SENSOR_OPTION_2": "PM10",
    "megapi_detect_pm25_sensor": "[image_1] air quality sensor[PORT] ， [OPTION] (μg/m³)",
    "BLOCK_1575275074292_PORT_0": "port1",
    "BLOCK_1575275074292_PORT_1": "port2",
    "BLOCK_1575275074292_PORT_2": "port3",
    "BLOCK_1575275074292_PORT_3": "port4",
    "BLOCK_1575275074292_DIRECT_0": "clockwise",
    "BLOCK_1575275074292_DIRECT_1": "anticlockwise",
    "BLOCK_1575275074292": "enhanced encoder motor [PORT]  [DIRECT] rotates by [DEGREE]degrees at speed of[SPEED]r/min",
    "enhanced_encoder_motor_power": "[image_1]enhanced encoder motor[PORT] rotates at power [POWER]%",
    "enhanced_encoder_motor_speed": "[image_1] enhanced encoder motor [PORT]rotational speed (r/min）",
    "enhanced_encoder_motor_pos": "[image_1]enhanced encoder motor [PORT]angle (°）",
    "auriga_all": "Maker's Platform",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_0": "LLL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_1": "LLH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_2": "LHL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_3": "LHH",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_4": "HLL",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SWITCH_7": "HHH",
    "auriga_encoder_motor_V2_motor": "[ICON] set encoder motor V2 DIP switch [SWITCH] [SLOT] power to[POWER]%",
    "auriga_encoder_motor_V2_speed": "[ICON] set encoder motor V2 DIP switch [SWITCH] [SLOT] speed to [SPEED]r/min",
    "auriga_encoder_motor_V2_pos": "[ICON] set encoder motor V2 DIP switch [SWITCH] [SLOT]to rotate by [DEGREE]degrees at speed of [SPEED]r/min",
    "auriga_encoder_motor_V2_minute": "[ICON]encoder motor V2 DIP switch [SWITCH] [SLOT]speed (r/min)",
    "auriga_encoder_motor_V2_angle": "[ICON]encoder motor V2 DIP switch[SWITCH] [SLOT] [ICON]angle (°)",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_ROTATE_0": "clockwise",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_PORT_0": "onboard motor port1",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_PORT_1": "onboard motor port2",
    "AURIGA_RUN_BOARD_ENCODER_MOTOR_ROTATE_1": "anticlockwise",
    "auriga_run_board_encoder_motor": "[ICON]encoder motor [PORT] [ROTATE] rotates at power[POWER]%",
    "auriga_run_board_encoder_motor_speed": "[ICON]encoder motor [PORT] [ROTATE] rotates at speed of [POWER] r/min",
    "auriga_run_board_encoder_motor_pos": "[ICON]encoder motor [PORT] [ROTATE] rotates by [DEGREE] degree at speed of[POWER] r/min",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_0": "port1",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_1": "port2",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_2": "port3",
    "AURIGA_RUN_ENCODER_MOTOR_PORT_3": "port4",
    "AURIGA_RUN_ENCODER_MOTOR_SLOT_0": "slot1",
    "AURIGA_RUN_ENCODER_MOTOR_SLOT_1": "slot2",
    "AURIGA_RUN_ENCODER_MOTOR_ROTATE_0": "clockwise",
    "AURIGA_RUN_ENCODER_MOTOR_ROTATE_1": "anticlockwise",
    "auriga_run_encoder_motor": "[ICON] encoder motor [PORT] [SLOT] [ROTATE] rotates by [DEGREE] degree at speed of [POWER] r/min",
    "auriga_run_motor": "[ICON]DC motor [PORT] [ROTATE] rotates at power[POWER] %",
    "auriga_run_stepper_motor_pos": "[ICON] stepping motor [PORT] [ROTATE] rotates with a distance of [DISTANCE] steps,at speed of [POWER] stp/min",
    "AURIGA_RUN_SERVO_PORT_0": "port6",
    "AURIGA_RUN_SERVO_PORT_1": "port7",
    "AURIGA_RUN_SERVO_PORT_2": "port8",
    "AURIGA_RUN_SERVO_PORT_3": "port9",
    "AURIGA_RUN_SERVO_PORT_4": "port10",
    "auriga_run_servo": "[ICON]servo [PORT] [SLOT] positioned at [DEGREE] angle",
    "AURIGA_RUN_FAN_FAN_ROTATE_0": "clockwise",
    "AURIGA_RUN_FAN_FAN_ROTATE_1": "anticlockwise",
    "AURIGA_RUN_FAN_FAN_ROTATE_2": "stop",
    "auriga_run_fan": "[ICON] fan [PORT] [FAN_ROTATE] rotates",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_0": "press",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_1": "release",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_2": "focus",
    "AURIGA_RUN_SHUTTER_SHUTTER_ACTION_3": "stop focusing",
    "auriga_run_shutter": "[ICON]shutter [PORT] [SHUTTER_ACTION]",
    "auriga_run_smart_servo_to_zero": "[ICON] smart servo [INDEX] rotates to starting position",
    "auriga_run_smart_servo": "[ICON]smart servo [INDEX] [ROTATE]rotates at speed of [POWER]",
    "auriga_run_smart_servo_absolute": "[ICON]smart servo [INDEX] [ROTATE] rotates to [POSITION] degree at speed of [POWER]r/min",
    "auriga_run_smart_servo_to_relative": "[ICON]smart servo [INDEX] [ROTATE] rotates by [DEGREE] degree at speed of [POWER]r/min",
    "auriga_show_face_time": "[ICON]LED panel [PORT] shows image[FACE_PANEL] for[TIME] secs",
    "auriga_show_face": "[ICON]LED panel [PORT] shows image [FACE_PANEL]",
    "auriga_show_face_position": "[ICON] LED panel [PORT] shows image [FACE_PANEL] at x: [X] y: [Y]",
    "auriga_show_text": "[ICON] LED panel [PORT] shows text [TEXT] ",
    "auriga_show_text_position": "[ICON] LED panel[PORT] shows text [TEXT] at x: [X] y: [Y]",
    "auriga_show_number": "[ICON] LED panel [PORT] shows number[NUMBER]",
    "auriga_show_time": "[ICON] LED panel [PORT] shows time [NUMBER1]：[NUMBER2]",
    "auriga_show_face_off": "[ICON]LED panel [PORT] clears screen",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "all",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "AURIGA_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "auriga_show_external_led_time": "[ICON]RGB LED [PORT]  lights up[LED_POSTION] with color [COLOR] for [TIME] secs",
    "auriga_show_external_led": "[ICON]RGB LED [PORT] lights up [LED_POSTION]with color [COLOR]",
    "auriga_show_external_led_rgb": "[ICON] RGB LED [PORT]  lights up [LED_POSTION] with color red [R] green[G] blue [B]",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "red",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "orange",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "yellow",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "green",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "cyan",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "blue",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "purple",
    "auriga_show_all_ledstrip_color": "[ICON]LED strip [PORT] [SLOT] all lights up with color [COLOR_LIST]",
    "auriga_show_ledstrip_color": "[ICON]LED strip [PORT] [SLOT] [POS] lights up with color [COLOR_LIST]",
    "auriga_show_ledstrip_rbg": "[ICON] LED strip [PORT] [SLOT] [POS] lights up with color red [R] green [G] blue [B]",
    "auriga_show_7segments_number": "[ICON] seven-segments  [PORT] displays number [NUMBER]",
    "auriga_detect_external_ultrasonic": "[ICON] ultrasonic sensor [PORT] distance",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_0": "port6",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_1": "port7",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_2": "port8",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_3": "port9",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_4": "port10",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_5": "onboard1",
    "AURIGA_DETECT_EXTERNAL_LIGHT_PORT_6": "onboard2",
    "auriga_detect_external_light": "[ICON] light sensor[PORT] light intensity",
    "auriga_detect_external_loudness": "[ICON] sound sensor [PORT] volume",
    "auriga_detect_external_linefollower": "[ICON] line follower sensor [PORT]  value",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "leftside",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "rightside",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "all",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "none",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "black",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "white",
    "auriga_event_external_linefollower": "[ICON] line follower sensor[PORT] detects [LINEFOLLOW_STATE] being [BLACK_WHITE] ？",
    "auriga_detec_temperature": "[ICON] temperature sensor [PORT] [SLOT] temperature（℃）",
    "AURIGA_DETECT_HUMITURE_TEMP_HUMITURE_0": "humidity",
    "AURIGA_DETECT_HUMITURE_TEMP_HUMITURE_1": "temperature",
    "auriga_detect_humiture": "[ICON] humiture sensor [PORT] [TEMP_HUMITURE]",
    "auriga_event_touch": "[ICON]touch sensor[PORT] touched？",
    "auriga_detect_compass": "[ICON]electronic compass [PORT] towards the north",
    "auriga_detect_flame": "[ICON] flame sensor [PORT]  value",
    "auriga_detect_gas": "[ICON]gas sensor[PORT]  value",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_0": " x-axis",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_1": "y-axis",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_2": "z-axis",
    "auriga_detect_board_gyro_angle": "[ICON] gyro onboard[AXIS] angle",
    "auriga_detect_gyro_angle": "[ICON]gyroscope outward [AXIS] angle",
    "auriga_event_pir_motion": "[ICON]PIR sensor [PORT] detects human's motion？",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_0": "button1",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_1": "button2",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_2": "button3",
    "AURIGA_EVENT_BUTTON_PRESS_FOUR_KEY_3": "button4",
    "auriga_event_button_press": "[ICON]button [PORT] [FOUR_KEY] pressed？",
    "auriga_event_limit_switch": "[ICON]limit switch[PORT] [SLOT] pressed？",
    "auriga_detect_potentiometer": "[ICON]potentiometer [PORT] value",
    "AURIGA_DETECT_JOYSTICK_AXIS_X_Y_0": "x-axis",
    "AURIGA_DETECT_JOYSTICK_AXIS_X_Y_1": "y-axis",
    "auriga_detect_joystick": "[ICON]joystick [PORT] [AXIS_X_Y] value",
    "auriga_detect_infrared": "[ICON] IR receiver [PORT] ",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SLOT_0": "motor port1",
    "AURIGA_ENCODER_MOTOR_V2_MOTOR_SLOT_1": "motor port2",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "black"
};