export default {
    "audio_player_rj25": "オーディオプレーヤー",
    "extensionName": "オーディオプレーヤー",
    "extensionDescription": "Audio Player",
    "audioplayer_init": "オーディオプレーヤーの初期化：任意のホワイトポート (I2C)",
    "audioplayer_play_by_sn": "オーディオプレーヤー：オーディオファイル[FILE_SN] を再生する",
    "audioplayer_play_by_name": "オーディオプレーヤー：[FILE_NAME] のオーディオファイルを再生する",
    "AUDIOPLAYER_SET_PLAY_MODE_PLAY_MODE_0": "1曲再生",
    "AUDIOPLAYER_SET_PLAY_MODE_PLAY_MODE_1": "ループ再生",
    "AUDIOPLAYER_SET_PLAY_MODE_PLAY_MODE_2": "順番再生",
    "AUDIOPLAYER_SET_PLAY_MODE_PLAY_MODE_3": "シャッフル再生",
    "audioplayer_set_play_mode": "オーディオプレーヤー：再生モードを [PLAY_MODE] に設定する",
    "audioplayer_play_previous": "オーディオプレーヤー：前のオーディオファイルを再生する",
    "audioplayer_play_next": "オーディオプレーヤー：次のオーディオファイルを再生する",
    "audioplayer_pause": "オーディオプレーヤー：一時停止/再生",
    "audioplayer_stop": "オーディオプレーヤー：再生を停止する",
    "audioplayer_set_volume": "オーディオプレーヤー：音量を [VOLUME] %に設定する",
    "audioplayer_volume_up": "オーディオプレーヤー：音量を上げる",
    "audioplayer_volume_down": "オーディオプレーヤー：音量を下げる",
    "audioplayer_record": "オーディオプレーヤー：録音を開始して[FILE_NAME] に保存する",
    "audioplayer_record_stop": "オーディオプレーヤー：録音を停止する"
};