export default {
    "audio_player_rj25": "Audio Player",
    "extensionName": "Audio Player",
    "extensionDescription": "Audio Player",
    "audioplayer_init": "инициализировать аудио проигрыватель: любой белый порт (I2C)",
    "audioplayer_play_by_sn": "audio player: воспроизвести [FILE_SN] звуковой файл",
    "audioplayer_play_by_name": "audio player: воспроизвести звуковой файл с именем [FILE_NAME]",
    "AUDIOPLAYER_SET_PLAY_MODE_PLAY_MODE_0": "Одного",
    "AUDIOPLAYER_SET_PLAY_MODE_PLAY_MODE_1": "Цикл",
    "AUDIOPLAYER_SET_PLAY_MODE_PLAY_MODE_2": "Заказ",
    "AUDIOPLAYER_SET_PLAY_MODE_PLAY_MODE_3": "Shuffle",
    "audioplayer_set_play_mode": "audio player: установить режим [PLAY_MODE]",
    "audioplayer_play_previous": "audio player: Воспроизвести предыдущий звуковой файл",
    "audioplayer_play_next": "audio player: воспроизвести следующий звуковой файл",
    "audioplayer_pause": "audio player: пауза/продолжить",
    "audioplayer_stop": "audio player: остановка воспроизведения",
    "audioplayer_set_volume": "audio player: установить громкость [VOLUME] %",
    "audioplayer_volume_up": "audio player: громкость вверх",
    "audioplayer_volume_down": "audio player: громкость вниз",
    "audioplayer_record": "audio player: начать запись и сохранить в [FILE_NAME]",
    "audioplayer_record_stop": "audio player: остановка записи"
};