export default {
    "audio_player_rj25": "Ses aýtdyryjy",
    "extensionName": "Ses aýtdyryjy",
    "extensionDescription": "Audio Player",
    "audioplayer_init": "ses aýtdyryjyny işlet: islendik ak portda (I2C)",
    "audioplayer_play_by_sn": "ses aýtdyryjy: [FILE_SN] atly ses faýlyny aýtdyr",
    "audioplayer_play_by_name": "ses aýtdyryjy: [FILE_NAME] atly ses faýlyny aýtdyr",
    "AUDIOPLAYER_SET_PLAY_MODE_PLAY_MODE_0": "ýekeleýin",
    "AUDIOPLAYER_SET_PLAY_MODE_PLAY_MODE_1": "siklleýin",
    "AUDIOPLAYER_SET_PLAY_MODE_PLAY_MODE_2": "düzgün boýunça",
    "AUDIOPLAYER_SET_PLAY_MODE_PLAY_MODE_3": "tötänleýin",
    "audioplayer_set_play_mode": "ses aýtdyryjy: işlediş düzgünini [PLAY_MODE] et",
    "audioplayer_play_previous": "ses aýtdyryjy: öňki ses faýlyny aýtdyr",
    "audioplayer_play_next": "ses aýtdyryjy: indiki ses faýlyny aýtdyr",
    "audioplayer_pause": "ses aýtdyryjy: sakla/dowam et",
    "audioplayer_stop": "ses aýtdyryjy: aýtdyrmagy bes et",
    "audioplayer_set_volume": "ses aýtdyryjy: ses kuwwatlylygyny [VOLUME] % et",
    "audioplayer_volume_up": "ses aýtdyryjy: sesi artdyrmak",
    "audioplayer_volume_down": "ses aýtdyryjy: sesi peseltmek",
    "audioplayer_record": "ses aýtdyryjy: ýazgy etmäge başla we [FILE_NAME] faýlyna ýazdyr",
    "audioplayer_record_stop": "ses aýtdyryjy: ýazgy etmegi bes et"
};