export default {
    "mcore_light_sound": "ひかり・おと",
    "extensionName": "ひかり・おと",
    "extensionDescription": "ひかりおいかけロボット、サソリロボット、ちのうランプをこうちくすることによって、mBotにひかりやおんせいこうかをくわえます。",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_0": "ポート1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_1": "ポート2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_2": "ポート3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_3": "ポート4",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "すべて",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON]RGB LED [PORT] の[LED_POSTION] を[COLOR] いろで[TIME] びょうてんとうする",
    "mcore_show_external_led": "[ICON]RGB LED [PORT] の[LED_POSTION] を[COLOR] いろでてんとうする",
    "mcore_show_external_led_rgb": "[ICON] RGB LED [PORT] の[LED_POSTION] をあか [R] みどり[G] あお [B] でてんとうする",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_0": "ポート3",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_1": "ポート4",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_2": "オードじょうのひかりセンサー",
    "mcore_detect_external_light": "[ICON]ひかりセンサー [PORT] のあたい",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_0": "ポート3",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_1": "ポート4",
    "mcore_detect_external_loudness": "[ICON]おんせいセンサー [PORT] のおんりょう",
    "CATEGORY_LIGHT_SOUND": "ひかり・おと"
};