export default {
    "mcore_light_sound": "Światło dźwięk",
    "extensionName": "Światło i dźwięk",
    "extensionDescription": "Rozbuduj mBota o dodatkowe czujniki światła, czujnik dźwięku i moduł z diodami LED. Zbuduj robota podążającego za światłem, robota reagującego na dźwięk lub inteligentną lampkę.",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_0": "port1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_1": "port2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_2": "port3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_3": "port4",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "wszystkie",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] moduł LED [PORT] zapal [LED_POSTION] na [COLOR] przez [TIME] s",
    "mcore_show_external_led": "[ICON] moduł LED [PORT] zapal [LED_POSTION] na [COLOR]",
    "mcore_show_external_led_rgb": "[ICON] moduł LED [PORT] zapal [LED_POSTION] na R [R] G [G] B [B]",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_0": "port3",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_1": "port4",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_2": "na płytce",
    "mcore_detect_external_light": "[ICON] czujnik światła [PORT]",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_0": "port3",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_1": "port4",
    "mcore_detect_external_loudness": "[ICON] czujnik dźwięku [PORT]",
    "CATEGORY_LIGHT_SOUND": "Światło dźwięk"
};