export default {
    "mcore_light_sound": "聲光互動",
    "extensionName": "聲光互動",
    "extensionDescription": "透過組裝追光機器人，蝎子機器人和智能枱燈，讓您的mBot展現出更多的聲光效果。",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_0": "連接埠1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_1": "連接埠2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_2": "連接埠3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_3": "連接埠4",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "全部",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] LED燈 [PORT] 位置 [LED_POSTION] 的顏色設為 [COLOR]，持續 [TIME] 秒",
    "mcore_show_external_led": "[ICON] LED燈 [PORT] 位置 [LED_POSTION] 的顏色設為 [COLOR]",
    "mcore_show_external_led_rgb": "[ICON] LED燈 [PORT] 位置 [LED_POSTION] 的配色數值為 紅[R] 綠[G] 藍[B]",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_0": "連接埠3",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_1": "連接埠4",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_2": "板載",
    "mcore_detect_external_light": "[ICON] 光線感測器[PORT] 光度值",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_0": "連接埠3",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_1": "連接埠4",
    "mcore_detect_external_loudness": "[ICON] 聲音感測器 [PORT] 音量",
    "CATEGORY_LIGHT_SOUND": "聲光互動"
};