export default {
    "cyberpi": "CyberPi",
    "extensionName": "CyberPi",
    "extensionDescription": "HaloCode Wi-Fi 내장의 싱글보드 컴퓨터",
    "firmwares_version_9c2fcf2b": "최신 펌웨어",
    "UPDATE_FIRMWARE": "펌웨어 업데이트",
    "settings_05de708e": "Set up Hostname",
    "settings_cc775efd": "Set up Wi-Fi",
    "connect_fail_418dd2b0": "USB 케이블이 장치에 제대로 연결되어 있는지 확인하십시오.",
    "connect_fail_be44da45": "연결할 장치가 켜져 있는지 확인하십시오.",
    "connect_fail_81f19800": "해당 버전에서는 한 번에 하나의 장치만 연결할 수 있습니다. 새로운 장치를 연결하면 기존 장치의 연결이 끊어지게 됩니다.",
    "connect_fail_a2244e18": "사용하고 있는 컴퓨터가 Bluetooth 4.0을 지원하는지 확인하고, Bluetooth가 켜져 있는지 확인하십시오.",
    "connect_fail_2ff4c830": "연결할 장치가 켜져 있는지 확인하십시오.",
    "connect_fail_f516f160": "해당 버전에서는 한 번에 하나의 장치만 연결할 수 있습니다. 새로운 장치를 연결하면 기존 장치의 연결이 끊어지게 됩니다.",
    "upload_fail_440e4ba6": "이 장치의 코딩 블록 또는 코드를 검토하십시오. 모든 데이터, 매개 변수 및 프로그래밍 로직이 올바른지 확인하십시오.",
    "upload_fail_24d8e745": "장치가 제대로 연결되어 있는지 확인하십시오. 장치를 재시작하고 다시 연결해 보세요.",
    "upload_fail_c52d223b": "펌웨어가 올바르게 동작하는지 확인해 주세요. 펌웨어를 갱신하거나, 초기화하고 재시행해 주세요.",
    "firmware_success_70e9b6c0": "보다 좋은 조작을 위해, 디바이스를 재기동해 한번 더 접속해 보세요.",
    "firmware_fail_9b5aae92": "디바이스가 올바르게 접속되어 있는지 확인해 주세요. 디바이스를 재시작하고 다시 연결한 다음 펌웨어를 업데이트 해보십시오.",
    "firmware_fail_9a92af14": "이 장치는 Bluetooth 어댑터 또는 다른 방법에 의한 펌웨어 업데이트를 지원 하지 않습니다.",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_0": "hi",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_1": "bye",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_2": "yeah",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_3": "wow",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_4": "웃음",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_5": "콧노래",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_6": "슬픔",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_7": "한숨",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_8": "짜증이 난",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_9": "화남",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_10": "놀람",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_11": "맛있는",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_12": "궁금",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_13": "embarrased",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_14": "준비",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_15": "고함",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_16": "잠",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_17": "야옹",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_18": "시작",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_19": "스위치",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_20": "알람",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_21": "버저",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_22": "폭팔",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_23": "점프",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_24": "레이저",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_25": "레벨 업",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_26": "에너지 부족",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_27": "prompt",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_28": "오른쪽",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_29": "틀림",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_30": "링",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_31": "점수",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_32": "기상",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_33": "경고",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_34": "금속-충돌",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_35": "발사",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_36": "유리-클 링크",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_37": "Inflator",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_38": "흐르는 물",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_39": "시계",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_40": "클릭",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_41": "전류",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_42": "wood-hit",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_43": "iron",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_44": "드롭",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_45": "bubble",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_46": "웨이브",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_47": "마법",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_48": "스핏파이어",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_49": "하트 비트",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_50": "로드",
    "cyberpi_play_audio_until_2": "play[file_name]until done",
    "cyberpi_play_audio_2": "play[file_name]",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_0": "안녕",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_1": "잘가",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_2": "네",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_3": "와우",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_4": "웃음",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_5": "콧노래",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_6": "슬픔",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_7": "한숨",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_8": "짜증",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_9": "화난",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_10": "놀람",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_11": "맛있는",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_12": "궁금",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_13": "embarrased",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_14": "준비",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_15": "고함",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_16": "잠",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_17": "야옹",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_18": "시작",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_19": "스위치",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_20": "알람",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_21": "버저",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_22": "점프",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_23": "레벨 업",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_24": "에너지 부족",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_25": "prompt",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_26": "오른쪽",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_27": "틀림",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_28": "링",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_29": "점수",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_30": "깨우다",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_31": "경고",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_32": "금속-충돌",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_33": "유리-클 링크",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_34": "Inflator",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_35": "흐르는 물",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_36": "시계",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_37": "클릭",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_38": "전류",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_39": "wood-hit",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_40": "iron",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_41": "드롭",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_42": "bubble",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_43": "웨이브",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_44": "마법",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_45": "스핏파이어",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_46": "하트 비트",
    "cyberpi_play_audio_until_3": "play[file_name]until done",
    "cyberpi_play_audio_3": "play[file_name]",
    "cyberpi_start_record": "start recording",
    "cyberpi_stop_record": "녹화 중단",
    "cyberpi_play_record_until": "play recording until done",
    "cyberpi_play_record": "play recording",
    "cyberpi_play_music_with_tone_and_note": "play note[number_1]for[number_2]beat",
    "cyberpi_play_music_with_tone_and_note_2": "play note[number_1]for[number_2]beat",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_0": "snare",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_1": "bass drum",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_2": "side stick",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_3": "crash cymbal",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_4": "open hi-hat",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_5": "closed hi-hat",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_6": "탬버린",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_7": "hand clap",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_8": "클라베스",
    "cyberpi_play_music_with_note": "play[fieldMenu_1]for [number_3]beat",
    "cyberpi_add_audio_speed": "increase audio speed by [number_1]%",
    "cyberpi_set_audio_speed": "set audio speed to[number_1]%",
    "cyberpi_get_audio_speed": "audio speed",
    "cyberpi_add_volume": "increase volume by[number_1] %",
    "cyberpi_set_volume": "set volume to[number_1] %",
    "cyberpi_get_volume": "volume(%)",
    "cyberpi_play_buzzer_tone_with_time": "play buzzer at [number_1]Hz for [number_2]secs",
    "cyberpi_play_buzzer_tone": "play buzzer at [number_2]Hz",
    "cyberpi_stop_audio": "모든 소리 끄기",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_0": "hi",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_1": "bye",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_2": "yeah",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_3": "wow",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_4": "웃음",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_5": "콧노래",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_6": "슬픔",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_7": "한숨",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_8": "짜증이 난",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_9": "화남",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_10": "놀람",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_11": "맛있는",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_12": "궁금",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_13": "당황",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_14": "준비",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_15": "고함",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_16": "잠",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_17": "야옹",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_18": "시작",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_19": "스위치",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_20": "알람",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_21": "버저",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_22": "폭팔",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_23": "점프",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_24": "레이저",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_25": "레벨 업",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_26": "에너지 부족",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_27": "시계종",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_28": "오른쪽",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_29": "틀림",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_30": "링",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_31": "점수",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_32": "기상",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_33": "경고",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_34": "금속-충돌",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_35": "발사",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_36": "유리-클 링크",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_37": "Inflator",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_38": "흐르는 물",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_39": "시계",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_40": "클릭",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_41": "전류",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_42": "스위치",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_43": "wood-hit",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_44": "iron",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_45": "드롭",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_46": "bubble",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_47": "웨이브",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_48": "마법",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_49": "스핏파이어",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_50": "하트 비트",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_51": "로드",
    "cyberpi_play_audio_until": "play[file_name]until done",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_0": "hi",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_1": "bye",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_2": "yeah",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_3": "wow",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_4": "웃음",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_5": "콧노래",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_6": "슬픔",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_7": "한숨",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_8": "짜증이 난",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_9": "화남",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_10": "놀람",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_11": "맛있는",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_12": "궁금",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_13": "당황",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_14": "준비",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_15": "고함",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_16": "잠",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_17": "야옹",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_18": "시작",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_19": "스위치",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_20": "알람",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_21": "버저",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_22": "폭팔",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_23": "점프",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_24": "레이저",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_25": "레벨 업",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_26": "에너지 부족",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_27": "시계종",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_28": "오른쪽",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_29": "틀림",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_30": "링",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_31": "점수",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_32": "기상",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_33": "경고",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_34": "금속-충돌",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_35": "발사",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_36": "유리-클 링크",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_37": "Inflator",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_38": "흐르는 물",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_39": "시계",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_40": "클릭",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_41": "전류",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_42": "스위치",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_43": "wood-hit",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_44": "iron",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_45": "드롭",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_46": "bubble",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_47": "웨이브",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_48": "마법",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_49": "스핏파이어",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_50": "心跳",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_51": "로드",
    "cyberpi_play_audio": "play[file_name]",
    "cate_34b1ba6f": "Audio",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_0": "무지개",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_1": "물보라",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_2": "별똥별(파랑)",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_3": "별똥별(초록)",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_4": "헬륨 섬광(빨강)",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_5": "헬륨 섬광(오렌지)",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_6": "반딧불",
    "cyberpi_play_led_animation_until": "play LED animation[LED_animation]until done",
    "cyberpi_show_led": "display[ledRing]",
    "cyberpi_move_led": "roll[led_number]LEDs rightwards",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_0": "모든",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_1": "1",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_2": "2",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_3": "3",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_4": "4",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_5": "5",
    "cyberpi_led_show_single_with_color_and_time_2": "LED[fieldMenu_1]displays [color_1]for [number_3]secs",
    "cyberpi_led_show_single_with_color_2": "LED[fieldMenu_1]displays[color_1]",
    "cyberpi_led_show_single_with_rgb_and_time": "LED[fieldMenu_1]displays R[r] G[g] B[b] for[number_5]secs",
    "cyberpi_led_show_single_with_rgb_2": "LED[fieldMenu_1]displays R [r] G [g] B [b]",
    "cyberpi_add_led_brightness": "increase LED brightness by [number_1] %",
    "cyberpi_set_led_brightness": "set brightness to [number_1] %",
    "cyberpi_get_led_brightness": "LED brightness(%)",
    "cyberpi_led_off_2": "turn off LED[fieldMenu_1]",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_0": "모든",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_1": "1",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_2": "2",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_3": "3",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_4": "4",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_5": "5",
    "cyberpi_led_show_single_with_color_and_time": "LED[fieldMenu_1]displays[color_1]for [number_3]secs",
    "cyberpi_led_show_single_with_color": "LED[fieldMenu_1]displays[color_1]",
    "cyberpi_led_show_single_with_rgb": "LED[fieldMenu_1]displays R [r] G [g] B [b]",
    "cyberpi_led_off": "turn off LED[fieldMenu_1]",
    "E_1783_n": "LED",
    "cyberpi_display_println": "print[string_2] and move to a newline",
    "cyberpi_display_print": "print[string_2]",
    "CYBERPI_CONSOLE_SET_FONT_INPUTMENU_1_0": "small",
    "CYBERPI_CONSOLE_SET_FONT_INPUTMENU_1_1": "가운데",
    "CYBERPI_CONSOLE_SET_FONT_INPUTMENU_1_2": "big",
    "CYBERPI_CONSOLE_SET_FONT_INPUTMENU_1_3": "super big",
    "cyberpi_console_set_font": "set print size to [inputMenu_1]",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_0": "center of screen",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_1": "middle at top",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_2": "middle at bottom",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_3": "middle on left",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_4": "middle on right",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_5": "upper left corner",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_6": "upper right corner",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_7": "bottom left corner",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_8": "bottom right corner",
    "cyberpi_display_show_at_somewhere_with_size": "show[string_2] at [fieldMenu_2] by[inputMenu_4]pixel",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_0": "1",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_1": "2",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_2": "3",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_3": "4",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_4": "5",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_5": "6",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_6": "7",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_7": "8",
    "cyberpi_display_label_show_at_somewhere_with_size": "show label [fieldMenu_1]  [string_2] at [fieldMenu_2] by [inputMenu_4]pixel",
    "cyberpi_display_show_label_xy_with_size": "show[string_2]at x[number_2] y[number_3]by[inputMenu_4]pixel",
    "cyberpi_display_label_show_label_xy_with_size": "show label [fieldMenu_1] [string_2] at x: [number_2] y [number_3] by [inputMenu_4] pixel",
    "cyberpi_display_set_chart_name": "name chart title: [string_1]",
    "cyberpi_display_line_chart_add_data": "line chart, add data[number_1]",
    "cyberpi_display_bar_chart_set_interval": "line chart, set spacing to [number_3] pixel",
    "cyberpi_display_bar_chart_add_data": "bar chart, add data[number_1]",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_1_0": "1",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_1_1": "2",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_1_2": "3",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_1_3": "4",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_2_0": "1",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_2_1": "2",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_2_2": "3",
    "cyberpi_display_table_add_data_at_row_column_2": "table, input[string_3] at row[fieldMenu_1], column[fieldMenu_2]",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_0": "1",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_1": "2",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_2": "3",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_3": "4",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_4": "5",
    "cyberpi_display_table_add_data_at_row_column": "table, input[string_3] at row[fieldMenu_1], column[fieldMenu_2]",
    "cyberpi_display_clear_chart": "데이터 지우기",
    "cyberpi_display_set_brush_with_color": "set brush color[color_1]",
    "cyberpi_display_set_brush_with_r_g_b": "set brush color to R [number_1] G [number_2] B [number_3]",
    "CYBERPI_DISPLAY_ROTATE_TO_2_FIELDMENU_1_0": "upside-down(-90°)",
    "CYBERPI_DISPLAY_ROTATE_TO_2_FIELDMENU_1_1": "left(0°)",
    "CYBERPI_DISPLAY_ROTATE_TO_2_FIELDMENU_1_2": "default(90°)",
    "CYBERPI_DISPLAY_ROTATE_TO_2_FIELDMENU_1_3": "right(180°)",
    "cyberpi_display_rotate_to_2": "screen towards[fieldMenu_1]",
    "CYBERPI_DISPLAY_ROTATE_TO_FIELDMENU_1_0": "upside-down(-90°)",
    "CYBERPI_DISPLAY_ROTATE_TO_FIELDMENU_1_1": "left(0°)",
    "CYBERPI_DISPLAY_ROTATE_TO_FIELDMENU_1_2": "default(90°)",
    "CYBERPI_DISPLAY_ROTATE_TO_FIELDMENU_1_3": "right(180°)",
    "cyberpi_display_rotate_to": "screen towards[fieldMenu_1]",
    "cyberpi_display_clear": "화면 지우기",
    "cate_52186034": "화면",
    "CYBERPI_FOLLOW_MBLOCK_SPRITE_GRADE_0": "low(0.2)",
    "CYBERPI_FOLLOW_MBLOCK_SPRITE_GRADE_1": "middle(0.4)",
    "CYBERPI_FOLLOW_MBLOCK_SPRITE_GRADE_2": "high(0.6)",
    "cyberpi_follow_mblock_sprite": "control[spriteMenu_1]to follow CyberPi with sensitivity[GRADE]",
    "CYBERPI_DETECT_ATTITUDE_TILT_0": "tilted forward",
    "CYBERPI_DETECT_ATTITUDE_TILT_1": "tilted backward",
    "CYBERPI_DETECT_ATTITUDE_TILT_2": "tilted left",
    "CYBERPI_DETECT_ATTITUDE_TILT_3": "tilted right",
    "CYBERPI_DETECT_ATTITUDE_TILT_4": "screen up",
    "CYBERPI_DETECT_ATTITUDE_TILT_5": "screen down",
    "cyberpi_detect_attitude": " [tilt]?",
    "CYBERPI_DETECT_ACTION_TILT_0": "wave up",
    "CYBERPI_DETECT_ACTION_TILT_1": "wave down",
    "CYBERPI_DETECT_ACTION_TILT_2": "wave left",
    "CYBERPI_DETECT_ACTION_TILT_3": "wave right",
    "CYBERPI_DETECT_ACTION_TILT_4": "rotate clockwise",
    "CYBERPI_DETECT_ACTION_TILT_5": "rotate counterclockwise",
    "CYBERPI_DETECT_ACTION_TILT_6": "freefall",
    "CYBERPI_DETECT_ACTION_TILT_7": "흔들기",
    "cyberpi_detect_action": "[tilt]detected?",
    "cyberpi_shaked_value": "흔들림 세기",
    "cyberpi_wave_angle": "waving direction (°)",
    "cyberpi_wave_speed": "waving speed",
    "CYBERPI_TILT_DEGREE_ROTATION_0": "tilted forward",
    "CYBERPI_TILT_DEGREE_ROTATION_1": "tilted backward(pitch)",
    "CYBERPI_TILT_DEGREE_ROTATION_2": "tilted left",
    "CYBERPI_TILT_DEGREE_ROTATION_3": "tilted right(roll)",
    "CYBERPI_TILT_DEGREE_ROTATION_4": "rotate clockwise",
    "CYBERPI_TILT_DEGREE_ROTATION_5": "rotate counterclockwise(yaw)",
    "cyberpi_tilt_degree": " [rotation]angle (°)",
    "CYBERPI_AXIS_ACCELERATION_AXIS_0": "x",
    "CYBERPI_AXIS_ACCELERATION_AXIS_1": "y",
    "CYBERPI_AXIS_ACCELERATION_AXIS_2": "z",
    "cyberpi_axis_acceleration": "motion sensor[axis]acceleration(m/s²)",
    "cyberpi_axis_angle_speed": "angle speed around [axis]axis(°/s)",
    "cyberpi_axis_rotation_angle": "rotated angle around [axis]axis (°)",
    "CYBERPI_RESET_AXIS_ROTATION_ANGLE_AXIS_0": "모든",
    "CYBERPI_RESET_AXIS_ROTATION_ANGLE_AXIS_1": "x",
    "CYBERPI_RESET_AXIS_ROTATION_ANGLE_AXIS_2": "y",
    "CYBERPI_RESET_AXIS_ROTATION_ANGLE_AXIS_3": "z",
    "cyberpi_reset_axis_rotation_angle": "reset rotated angle around[axis]axis",
    "cyberpi_reset_yaw": "reset yaw angle",
    "cate_c589c493": "Motion Sensing",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_0": "pulled↑",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_1": "pulled↓",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_2": "pulled←",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_3": "pulled→",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_4": "middle pressed",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_5": "any direction",
    "cyberpi_direction_key_press": "조이스틱[fieldMenu_1]?",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_0": "pulled↑",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_1": "pulled↓",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_2": "pulled←",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_3": "pulled→",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_4": "middle pressed",
    "cyberpi_direction_key_count": "joystick [fieldMenu_1]counts",
    "cyberpi_direction_key_count_reset": "reset joystick [fieldMenu_1]counts",
    "CYBERPI_BUTTON_PRESS_FIELDMENU_1_0": "A",
    "CYBERPI_BUTTON_PRESS_FIELDMENU_1_1": "B",
    "CYBERPI_BUTTON_PRESS_FIELDMENU_1_2": "any button",
    "cyberpi_button_press": "button[fieldMenu_1]pressed?",
    "CYBERPI_BUTTON_COUNT_FIELDMENU_1_0": "A",
    "CYBERPI_BUTTON_COUNT_FIELDMENU_1_1": "B",
    "cyberpi_button_count": "button[fieldMenu_1]press counts",
    "cyberpi_button_count_reset": "reset button[fieldMenu_1]press counts",
    "cyberpi_loudness": "음량",
    "cyberpi_brightness": "주변 조도",
    "cyberpi_timer_get": "타이머 (초)",
    "cyberpi_timer_reset": "타이머 초기화",
    "cyberpi_name": "hostname",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_0": "battery level(%)",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_1": "MAC address",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_2": "Bluetooth name",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_3": "system language",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_4": "extension name",
    "cyberpi_battery_macaddress_blename_and_so_on": "[fieldMenu_1]",
    "E_1784_n": "관찰",
    "cyberpi_mesh_create": "이름이 [mesh_name] 인 LAN을 만들기",
    "cyberpi_mesh_join": "이름이 [mesh_name] 인 LAN에 참여하기",
    "cyberpi_set_wifi_broadcast": "broadcast message [message] on LAN",
    "cyberpi_set_wifi_broadcast_with_value": "broadcast message[message]with value[value]on LAN",
    "cyberpi_wifi_broadcast_when_received_message": "when receiving[message]boadcast on LAN",
    "cyberpi_wifi_broadcast_get_value": "LAN broadcast [message]value received",
    "mesh": "LAN",
    "cyberpi_wifi_set": "connect to Wi-Fi[ssid] password [wifipassword]",
    "cyberpi_wifi_is_connect": "network connected?",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_0": "(1) Chinese",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_1": "(2) Chinese(Taiwan)",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_2": "(3) Cantonese",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_3": "(4) Japanese",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_4": "(5) English",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_5": "(6) French",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_6": "(7) German",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_7": "(8) Spanish",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_8": "(9) Portuguese",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_9": "(10) Russian",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_10": "(11) Korean",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_11": "(12) Italian",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_12": "(13) Dutch",
    "cyberpi_speak_with_some_language": "speak [fieldMenu_1] [string_2]",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_2_FIELDMENU_1_0": "중국어",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_2_FIELDMENU_1_1": "영어",
    "cyberpi_speak_with_some_language_2": "speak[fieldMenu_1][string_2]",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_3_FIELDMENU_1_0": "auto",
    "cyberpi_speak_with_some_language_3": "speak[fieldMenu_1][string_2]",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_0": "(1) Chinese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_1": "(2) Chinese(Taiwan)",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_2": "(3) Cantonese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_3": "(4) English",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_4": "(5) French",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_5": "(6) German",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_6": "(7) Spanish",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_7": "(8) Italian",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_8": "(9) Japanese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_9": "(10) Portuguese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_10": "(11) Russian",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_11": "(12) Korean",
    "cyberpi_speech_recognition_with_time_3": "recognize[fieldMenu_1] [number_2]secs",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_0": "(1) Chinese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_1": "(2) Chinese(Taiwan)",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_2": "(3) Cantonese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_3": "(4) English",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_4": "(5) French",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_5": "(6) German",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_6": "(7) Spanish",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_7": "(8) Italian",
    "cyberpi_speech_recognition_with_time_2": "recognize[fieldMenu_1] [number_3]secs",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_0": "(1) Chinese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_1": "(2) Chinese(Taiwan)",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_2": "(3) Cantonese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_3": "(4) Japanese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_4": "(5) English",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_5": "(6) French",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_6": "(7) German",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_7": "(8) Spanish",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_8": "(9) Portuguese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_9": "(10) Russian",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_10": "(11) Korean",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_11": "(12) Italian",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_12": "(13) Dutch",
    "cyberpi_speech_recognition_with_record_2": "对录音进行 [fieldMenu_1]  识别",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_0": "(1) Chinese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_1": "(2) Chinese (Taiwan)",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_2": "(3) Cantonese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_3": "(4) Japanese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_4": "(5) English",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_5": "(6) French",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_6": "(7) German",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_7": "(8) Spanish",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_8": "(9) Portuguese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_9": "(10) Russian",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_10": "(11) Korean",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_11": "(12) Italian",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_12": "(13) Dutch",
    "cyberpi_speech_recognition_with_time": "recognize[fieldMenu_1] [number_3]secs",
    "BLOCK_1599643085220": "识别 [fieldMenu_1]  [number_3] 秒 copy",
    "cyberpi_speech_recognition_with_record": "对录音进行 [fieldMenu_1]   识别",
    "cyberpi_speech_recognition_result": "음성인식 결과",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_0": "중국어",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_1": "영어",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_2": "Traditional Chinese",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_3": "일본어",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_4": "프랑스어",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_5": "독일어",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_6": "스페인어",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_7": "포르투갈어",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_8": "러시아어",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_9": "한국어",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_10": "이탈리아어",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_11": "네덜란드어",
    "cyberpi_translate_to_some_language_2": "translate[string_1] into[fieldMenu_2]",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_FIELDMENU_2_0": "중국어",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_FIELDMENU_2_1": "영어",
    "cyberpi_translate_to_some_language": "translate [string_1]into[fieldMenu_2]",
    "ai": "AI",
    "cyberpi_set_cloud_broadcast": "send user cloud broadcast[message]",
    "cyberpi_set_cloud_broadcast_with_value": "send user cloud broadcast [message]with value [value]",
    "cyberpi_when_cloud_broadcast": "when receiving user cloud broadcast[message]",
    "cyberpi_cloud_broadcast_get_value": "user cloud broadcast[message]value received",
    "widget_445594f4": "위치",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_0": "highest temperature (℃)",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_1": "lowest temperature(℃)",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_2": "highest temperature(℉)",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_3": "lowest temperature(℉)",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_4": "날씨",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_5": "습도",
    "cyberpi_get_weather_from_internet": "[LOCATION] [WEATHER_TYPE]",
    "widget_dcc97542": "위치",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_0": "AQI",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_1": "PM2.5",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_2": "PM10",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_3": "CO",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_4": "SO₂",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_5": "NO₂",
    "cyberpi_get_air_quality_from_internet": "air quality[METEOROLOGICAL] [aq_type]",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_SUN_MOVE_TYPE_0": "일출",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_SUN_MOVE_TYPE_1": "일몰",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_TIME_TYPE_0": "시간",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_TIME_TYPE_1": "시",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_TIME_TYPE_2": "분",
    "cyberpi_get_sun_time_from_internet": "[LOCATION]  [sun_move_type] [time_type]",
    "CYBERPI_GET_LOCAL_TIME_FROM_INTERNET_FIELDMENU_3_0": "시간",
    "CYBERPI_GET_LOCAL_TIME_FROM_INTERNET_FIELDMENU_3_1": "시",
    "CYBERPI_GET_LOCAL_TIME_FROM_INTERNET_FIELDMENU_3_2": "분",
    "cyberpi_get_local_time_from_internet": "get [widget_1] local time [fieldMenu_3]",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_0": "local time",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_1": "local hour",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_2": "local minute",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_3": "sunrise time",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_4": "sunrise hour",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_5": "sunrise minute",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_6": "sunset time",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_7": "sunset hour",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_8": "sunset minute",
    "cyberpi_get_time_from_internet": "get[widget_1]'s [fieldMenu_3]",
    "BLOCK_1610527804319_FIELDMENU_1_0": "(0) UTC",
    "BLOCK_1610527804319_FIELDMENU_1_1": "(1) UTC+1",
    "BLOCK_1610527804319_FIELDMENU_1_2": "(2) UTC+2",
    "BLOCK_1610527804319_FIELDMENU_1_3": "(3) UTC+3",
    "BLOCK_1610527804319_FIELDMENU_1_4": "(4) UTC+4",
    "BLOCK_1610527804319_FIELDMENU_1_5": "(5) UTC+5",
    "BLOCK_1610527804319_FIELDMENU_1_6": "(6) UTC+6",
    "BLOCK_1610527804319_FIELDMENU_1_7": "(7) UTC+7",
    "BLOCK_1610527804319_FIELDMENU_1_8": "(8) UTC+8",
    "BLOCK_1610527804319_FIELDMENU_1_9": "(9) UTC+9",
    "BLOCK_1610527804319_FIELDMENU_1_10": "(10) UTC+10",
    "BLOCK_1610527804319_FIELDMENU_1_11": "(11) UTC+11",
    "BLOCK_1610527804319_FIELDMENU_1_12": "(12) UTC-12",
    "BLOCK_1610527804319_FIELDMENU_1_13": "(-11) UTC-11",
    "BLOCK_1610527804319_FIELDMENU_1_14": "(-10) UTC-10",
    "BLOCK_1610527804319_FIELDMENU_1_15": "(-9) UTC-9",
    "BLOCK_1610527804319_FIELDMENU_1_16": "(-8) UTC-8",
    "BLOCK_1610527804319_FIELDMENU_1_17": "(-7) UTC-7",
    "BLOCK_1610527804319_FIELDMENU_1_18": "(-6) UTC-6",
    "BLOCK_1610527804319_FIELDMENU_1_19": "(-5) UTC-5",
    "BLOCK_1610527804319_FIELDMENU_1_20": "(-4) UTC-4",
    "BLOCK_1610527804319_FIELDMENU_1_21": "(-3) UTC-3",
    "BLOCK_1610527804319_FIELDMENU_1_22": "(-2) UTC-2",
    "BLOCK_1610527804319_FIELDMENU_1_23": "(-1) UTC-1",
    "BLOCK_1610527804319_FIELDMENU_2_0": "년",
    "BLOCK_1610527804319_FIELDMENU_2_1": "달",
    "BLOCK_1610527804319_FIELDMENU_2_2": "day",
    "BLOCK_1610527804319_FIELDMENU_2_3": "week",
    "BLOCK_1610527804319_FIELDMENU_2_4": "시",
    "BLOCK_1610527804319_FIELDMENU_2_5": "분",
    "BLOCK_1610527804319_FIELDMENU_2_6": "초",
    "BLOCK_1610527804319": "get [fieldMenu_1]'s [fieldMenu_2]",
    "iot": "IoT",
    "cyberpi_when_launch": "[ICON]when CyberPi starts up",
    "cyberpi_when_direction_key_press": "[image_1]when joystick [fieldMenu_2]",
    "cyberpi_when_button_press": "[image_1]when button[fieldMenu_2]pressed",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_0": "tilted left",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_1": "tilted right",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_2": "tilted forward",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_3": "tilted backward",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_4": "screen faces up",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_5": "screen faces down",
    "cyberpi_when_detect_attitude": "[image_1]when CyberPi[tilt]",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_0": "wave left",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_1": "wave right",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_2": "wave up",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_3": "wave down",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_4": "rotate clockwise",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_5": "rotate countercloclwise",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_6": "freefall",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_7": "흔들기",
    "cyberpi_when_detect_action": "[image_1]when[tilt]detected",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_2_0": "빛",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_2_1": "소리",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_2_2": "흔들림 세기",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_2_3": "타이머",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_3_0": ">",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_3_1": "<",
    "cyberpi_when_sensor_value_bigger_or_smaller_than": "[image_1]when[fieldMenu_2]value [fieldMenu_3][number_3]",
    "cyberpi_restart": "[image_1]restart CyberPi",
    "cyberpi_python_insert": "插入代码  [string_1] ",
    "CYBERPI_OPERATOR_CASTS_FIELDMENU_1_0": "integer",
    "CYBERPI_OPERATOR_CASTS_FIELDMENU_1_1": "float",
    "CYBERPI_OPERATOR_CASTS_FIELDMENU_1_2": "문자열",
    "cyberpi_operator_casts": "read[string_2] in[fieldMenu_1]",
    "e_509_c_events_b_18280": "HaloCode가 [tilt] 일 때",
    "e_509_c_events_b_18281": "[touchpad_number] 핀이 터치 되었을때",
    "e_509_c_1410_b_18249": "모든 LED를 [color_1] 색상으로 켜다.",
    "haloboard_show_ring_effect": "LED에 [LED_animation] 애니메이션을 끝까지 출력하기",
    "haloboard_show_ring_color": "[ledRing] 을 출력하기",
    "haloboard_show_rotation_color": "[ledRing] 을 [led_number] 개의 LED 소자만큼 [rotate] (시계방향)으로 회전시켜 출력하기",
    "haloboard_show_all_leds_with_lightness": "모든 LED를 [color_1] 색상, [lightness] % 밝기로 켜기",
    "haloboard_show_all_leds_with_rgb": "lED를 R[r] G[g] B[b] 색으로 모두 켜기",
    "haloboard_show_single_led_with_rgb": "[led_id] 번 LED를 R [r] G [g] B [b] 색상으로 켜기",
    "haloboard_show_percentage": "전체 LED의 [percentage]  % 를 켜기",
    "haloboard_detect_touch": "터치 패드 [touchpad_number] 에 닿았나요?",
    "haloboard_detect_tilt": "HaloCode는 [tilt]？",
    "haloboard_detect_axis_acceleration": "모션 센서의 [axis] 축 가속도 값 (m/s ²)",
    "haloboard_detect_tilt_degree": "모션 센서 [rotation] 각도 값 (°)",
    "haloboard_detect_rotation_degree": "[axis] 축 회전각도",
    "haloboard_reset_rotation_degree": "회전 각도 재설정  [axis]",
    "haloboard_pin_read_digtial": " [pin_number] 번 핀의 디지털 입력값",
    "haloboard_pin_write_digtial": "값 [Digtial_value] 을 [pin_number] 번 핀에 디지털 출력하기",
    "haloboard_pin_set_servo": "[pin_number] 서보핀 [ServoRotaryAngle] 으로 회전하기",
    "BLOCK_1543754866399": "버저핀 [pin] 으로 높이 [frequency] HZ의 소리를 [duration] 초 울림",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_1": "물보라",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_2": "별똥별",
    "haloboard_detect_time": "타이머 (초)",
    "BLOCK_1543818559542_TEMPO_4": "2박자",
    "haloboard_pin_write_PWM": "값 [PWM_value] 을 [pin_number] 번 핀에 아날로그 출력하기",
    "haloboard_mesh_join1": "이름이 [mesh_name] 인 LAN에 참여하기",
    "haloboard_mesh_create1": "이름이 [mesh_name] 인 LAN을 만들기",
    "halo_play_buzzer_with_note": "버저핀 [pin_num] 에서 [note] 의 소리를 [beat] 로 울림",
    "halo_pin_play_buzzer_with_frequency": "버저핀 [pin_num] 에 [frequency] 의 주파수로 [duration] 초간 출력하기",
    "BLOCK_1552905879755": "터치 패드 [touchpad_number] 의 민감도를 [sensitivity] 으로 설정하기",
    "BLOCK_1574094194223": "read[string_2] in[fieldMenu_1]",
    "BLOCK_1586933935668": "execute code[string_1]",
    "cyberpi_play_music_with_note_2": "play [fieldMenu_1]for [number_3]beat",
    "cybeipi_name": "Hostname:",
    "affirm": "Ok",
    "Wifi_name": "Wi-Fi name:",
    "Wifi_password": "Wi-Fi password:",
    "city": "도시"
};