export default {
    "cyberpi": "CyberPi",
    "extensionName": "CyberPi",
    "extensionDescription": "HaloCode Single-Board Computer with Built-in Wi-Fi",
    "firmwares_version_9c2fcf2b": "Firmware mais recente",
    "UPDATE_FIRMWARE": "Atualização de firmware",
    "settings_05de708e": "Set up Hostname",
    "settings_cc775efd": "Set up Wi-Fi",
    "connect_fail_418dd2b0": "Certifique-se de que o cabo USB está correctamente ligado ao dispositivo.",
    "connect_fail_be44da45": "Por favor, certifique-se que o dispositivo a ser ligado está ligado.",
    "connect_fail_81f19800": "Apenas um dispositivo pode ser conectado por vez nesta versão. Assim, a conexão deste dispositivo levará à desconexão do anterior.",
    "connect_fail_a2244e18": "Por favor, certifique-se de que o computador suporta Bluetooth 4,0 e Bluetooth já ligado.",
    "connect_fail_2ff4c830": "Por favor, certifique-se que o dispositivo a ser ligado está ligado.",
    "connect_fail_f516f160": "Apenas um dispositivo pode ser conectado por vez nesta versão. Assim, a conexão deste dispositivo levará à desconexão do anterior.",
    "upload_fail_440e4ba6": "Reveja os blocos de codificação ou o código para este dispositivo. Certifique-se de que todos os dados, parâmetros e lógica de programação estão corretos.",
    "upload_fail_24d8e745": "Certifique-se de que o dispositivo está correctamente ligado. Você pode reiniciar o dispositivo e conectá-lo novamente.",
    "upload_fail_c52d223b": "Por favor, certifique-se o firmware funciona bem. Você pode atualizar o firmware ou restaurar as configurações de fábrica e tente novamente.",
    "firmware_success_70e9b6c0": "Para uma melhor experiência, por favor, reinicie o dispositivo e conectá-lo mais uma vez.",
    "firmware_fail_9b5aae92": "Certifique-se de que o dispositivo está correctamente ligado. Reinicie o dispositivo, conectá-lo novamente e, em seguida, tente atualizar o firmware mais uma vez.",
    "firmware_fail_9a92af14": "Este dispositivo não suporta actualizações de firmware através de adaptador Bluetooth ou outras formas.",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_0": "olá",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_1": "adeus",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_2": "sim",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_3": "uau",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_4": "rir",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_5": "hum",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_6": "triste",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_7": "suspirar",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_8": "irritado",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_9": "zangado",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_10": "surpreso",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_11": "delicioso",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_12": "curioso",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_13": "embarrased",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_14": "pronto",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_15": "acelerar",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_16": "sonolento",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_17": "miau",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_18": "começar",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_19": "interruptor",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_20": "sinal sonoro",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_21": "zumbindo",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_22": "explosão",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_23": "salto",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_24": "laser",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_25": "subir de nível",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_26": "energia baixa",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_27": "prompt",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_28": "direita",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_29": "incorreto",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_30": "toque",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_31": "pontuação",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_32": "acordar",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_33": "aviso",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_34": "colisão de metal",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_35": "tiro",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_36": "vidro-Clink",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_37": "Insuflador",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_38": "água corrente",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_39": "Mecânica",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_40": "Clique",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_41": "corrente",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_42": "wood-hit",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_43": "iron",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_44": "Gota",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_45": "bubble",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_46": "Onda",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_47": "Magia",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_48": "Spitfire",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_49": "Batimento cardíaco",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_50": "Carga",
    "cyberpi_play_audio_until_2": "play[file_name]until done",
    "cyberpi_play_audio_2": "play[file_name]",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_0": "olá",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_1": "adeus",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_2": "sim",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_3": "uau",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_4": "rir",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_5": "hum",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_6": "triste",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_7": "suspirar",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_8": "irritado",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_9": "zangado",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_10": "surpreso",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_11": "delicioso",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_12": "curioso",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_13": "embarrased",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_14": "pronto",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_15": "acelerar",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_16": "sonolento",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_17": "miau",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_18": "iniciar",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_19": "interruptor",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_20": "sinal sonoro",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_21": "zumbindo",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_22": "saltar",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_23": "subir de nível",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_24": "pouca energia",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_25": "prompt",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_26": "direita",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_27": "incorreto",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_28": "toque",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_29": "pontuação",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_30": "acordar",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_31": "aviso",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_32": "colisão de metal",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_33": "vidro-Clink",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_34": "Insuflador",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_35": "água corrente",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_36": "Mecânica",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_37": "Clique",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_38": "Atual",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_39": "wood-hit",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_40": "iron",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_41": "Gota",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_42": "bubble",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_43": "Onda",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_44": "Magia",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_45": "Spitfire",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_46": "Batimento cardíaco",
    "cyberpi_play_audio_until_3": "play[file_name]until done",
    "cyberpi_play_audio_3": "play[file_name]",
    "cyberpi_start_record": "start recording",
    "cyberpi_stop_record": "parar gravação",
    "cyberpi_play_record_until": "play recording until done",
    "cyberpi_play_record": "play recording",
    "cyberpi_play_music_with_tone_and_note": "play note[number_1]for[number_2]beat",
    "cyberpi_play_music_with_tone_and_note_2": "play note[number_1]for[number_2]beat",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_0": "snare",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_1": "bass drum",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_2": "side stick",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_3": "crash cymbal",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_4": "open hi-hat",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_5": "closed hi-hat",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_6": "pandeireta",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_7": "hand clap",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_8": "claves",
    "cyberpi_play_music_with_note": "play[fieldMenu_1]for [number_3]beat",
    "cyberpi_add_audio_speed": "increase audio speed by [number_1]%",
    "cyberpi_set_audio_speed": "set audio speed to[number_1]%",
    "cyberpi_get_audio_speed": "audio speed",
    "cyberpi_add_volume": "increase volume by[number_1] %",
    "cyberpi_set_volume": "set volume to[number_1] %",
    "cyberpi_get_volume": "volume(%)",
    "cyberpi_play_buzzer_tone_with_time": "play buzzer at [number_1]Hz for [number_2]secs",
    "cyberpi_play_buzzer_tone": "play buzzer at [number_2]Hz",
    "cyberpi_stop_audio": "parar todos os sons",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_0": "olá",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_1": "adeus",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_2": "sim",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_3": "uau",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_4": "rir",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_5": "hum",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_6": "triste",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_7": "suspirar",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_8": "irritado",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_9": "zangado",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_10": "surpreso",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_11": "delicioso",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_12": "curioso",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_13": "envergonhado",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_14": "pronto",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_15": "acelerar",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_16": "sonolento",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_17": "miau",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_18": "começar",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_19": "interruptor",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_20": "sinal sonoro",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_21": "zumbindo",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_22": "explosão",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_23": "salto",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_24": "laser",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_25": "subir de nível",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_26": "energia baixa",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_27": "sinal de aviso",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_28": "direita",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_29": "incorreto",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_30": "toque",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_31": "pontuação",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_32": "acordar",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_33": "aviso",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_34": "colisão de metal",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_35": "tiro",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_36": "vidro-Clink",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_37": "Insuflador",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_38": "água corrente",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_39": "Mecânica",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_40": "Clique",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_41": "corrente",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_42": "interruptor",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_43": "wood-hit",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_44": "iron",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_45": "Gota",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_46": "bubble",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_47": "Onda",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_48": "Magia",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_49": "Spitfire",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_50": "Batimento cardíaco",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_51": "Carga",
    "cyberpi_play_audio_until": "play[file_name]until done",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_0": "olá",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_1": "adeus",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_2": "sim",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_3": "uau",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_4": "rir",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_5": "hum",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_6": "triste",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_7": "suspirar",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_8": "irritado",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_9": "zangado",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_10": "surpreso",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_11": "delicioso",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_12": "curioso",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_13": "envergonhado",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_14": "pronto",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_15": "acelerar",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_16": "sonolento",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_17": "miau",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_18": "começar",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_19": "interruptor",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_20": "sinal sonoro",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_21": "zumbindo",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_22": "explosão",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_23": "salto",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_24": "laser",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_25": "subir de nível",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_26": "energia baixa",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_27": "sinal de aviso",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_28": "direita",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_29": "incorreto",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_30": "toque",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_31": "pontuação",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_32": "acordar",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_33": "aviso",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_34": "colisão de metal",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_35": "tiro",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_36": "vidro-Clink",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_37": "Insuflador",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_38": "água corrente",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_39": "Mecânica",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_40": "Clique",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_41": "corrente",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_42": "interruptor",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_43": "wood-hit",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_44": "iron",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_45": "Gota",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_46": "bubble",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_47": "Onda",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_48": "Magia",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_49": "Spitfire",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_50": "心跳",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_51": "Carga",
    "cyberpi_play_audio": "play[file_name]",
    "cate_34b1ba6f": "Audio",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_0": "Arco-íris",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_1": "Spindrift",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_2": "meteor(blue)",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_3": "meteor (green)",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_4": "helium flash(red)",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_5": "helium flash(orange)",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_6": "Firefly",
    "cyberpi_play_led_animation_until": "play LED animation[LED_animation]until done",
    "cyberpi_show_led": "display[ledRing]",
    "cyberpi_move_led": "roll[led_number]LEDs rightwards",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_0": "todos",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_1": "1",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_2": "2",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_3": "3",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_4": "4",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_5": "5",
    "cyberpi_led_show_single_with_color_and_time_2": "LED[fieldMenu_1]displays [color_1]for [number_3]secs",
    "cyberpi_led_show_single_with_color_2": "LED[fieldMenu_1]displays[color_1]",
    "cyberpi_led_show_single_with_rgb_and_time": "LED[fieldMenu_1]displays R[r] G[g] B[b] for[number_5]secs",
    "cyberpi_led_show_single_with_rgb_2": "LED[fieldMenu_1]displays R [r] G [g] B [b]",
    "cyberpi_add_led_brightness": "increase LED brightness by [number_1] %",
    "cyberpi_set_led_brightness": "set brightness to [number_1] %",
    "cyberpi_get_led_brightness": "LED brightness(%)",
    "cyberpi_led_off_2": "turn off LED[fieldMenu_1]",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_0": "todos",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_1": "1",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_2": "2",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_3": "3",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_4": "4",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_5": "5",
    "cyberpi_led_show_single_with_color_and_time": "LED[fieldMenu_1]displays[color_1]for [number_3]secs",
    "cyberpi_led_show_single_with_color": "LED[fieldMenu_1]displays[color_1]",
    "cyberpi_led_show_single_with_rgb": "LED[fieldMenu_1]displays R [r] G [g] B [b]",
    "cyberpi_led_off": "turn off LED[fieldMenu_1]",
    "E_1783_n": "LED",
    "cyberpi_display_println": "print[string_2] and move to a newline",
    "cyberpi_display_print": "print[string_2]",
    "CYBERPI_CONSOLE_SET_FONT_INPUTMENU_1_0": "small",
    "CYBERPI_CONSOLE_SET_FONT_INPUTMENU_1_1": "centro",
    "CYBERPI_CONSOLE_SET_FONT_INPUTMENU_1_2": "big",
    "CYBERPI_CONSOLE_SET_FONT_INPUTMENU_1_3": "super big",
    "cyberpi_console_set_font": "set print size to [inputMenu_1]",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_0": "center of screen",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_1": "middle at top",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_2": "middle at bottom",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_3": "middle on left",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_4": "middle on right",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_5": "upper left corner",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_6": "upper right corner",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_7": "bottom left corner",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_8": "bottom right corner",
    "cyberpi_display_show_at_somewhere_with_size": "show[string_2] at [fieldMenu_2] by[inputMenu_4]pixel",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_0": "1",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_1": "2",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_2": "3",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_3": "4",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_4": "5",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_5": "6",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_6": "7",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_7": "8",
    "cyberpi_display_label_show_at_somewhere_with_size": "show label [fieldMenu_1]  [string_2] at [fieldMenu_2] by [inputMenu_4]pixel",
    "cyberpi_display_show_label_xy_with_size": "show[string_2]at x[number_2] y[number_3]by[inputMenu_4]pixel",
    "cyberpi_display_label_show_label_xy_with_size": "show label [fieldMenu_1] [string_2] at x: [number_2] y [number_3] by [inputMenu_4] pixel",
    "cyberpi_display_set_chart_name": "name chart title: [string_1]",
    "cyberpi_display_line_chart_add_data": "line chart, add data[number_1]",
    "cyberpi_display_bar_chart_set_interval": "line chart, set spacing to [number_3] pixel",
    "cyberpi_display_bar_chart_add_data": "bar chart, add data[number_1]",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_1_0": "1",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_1_1": "2",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_1_2": "3",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_1_3": "4",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_2_0": "1",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_2_1": "2",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_2_2": "3",
    "cyberpi_display_table_add_data_at_row_column_2": "table, input[string_3] at row[fieldMenu_1], column[fieldMenu_2]",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_0": "1",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_1": "2",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_2": "3",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_3": "4",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_4": "5",
    "cyberpi_display_table_add_data_at_row_column": "table, input[string_3] at row[fieldMenu_1], column[fieldMenu_2]",
    "cyberpi_display_clear_chart": "dados claros",
    "cyberpi_display_set_brush_with_color": "set brush color[color_1]",
    "cyberpi_display_set_brush_with_r_g_b": "set brush color to R [number_1] G [number_2] B [number_3]",
    "CYBERPI_DISPLAY_ROTATE_TO_2_FIELDMENU_1_0": "upside-down(-90°)",
    "CYBERPI_DISPLAY_ROTATE_TO_2_FIELDMENU_1_1": "left(0°)",
    "CYBERPI_DISPLAY_ROTATE_TO_2_FIELDMENU_1_2": "default(90°)",
    "CYBERPI_DISPLAY_ROTATE_TO_2_FIELDMENU_1_3": "right(180°)",
    "cyberpi_display_rotate_to_2": "screen towards[fieldMenu_1]",
    "CYBERPI_DISPLAY_ROTATE_TO_FIELDMENU_1_0": "upside-down(-90°)",
    "CYBERPI_DISPLAY_ROTATE_TO_FIELDMENU_1_1": "left(0°)",
    "CYBERPI_DISPLAY_ROTATE_TO_FIELDMENU_1_2": "default(90°)",
    "CYBERPI_DISPLAY_ROTATE_TO_FIELDMENU_1_3": "right(180°)",
    "cyberpi_display_rotate_to": "screen towards[fieldMenu_1]",
    "cyberpi_display_clear": "limpar ecrã",
    "cate_52186034": "Ecrã",
    "CYBERPI_FOLLOW_MBLOCK_SPRITE_GRADE_0": "low(0.2)",
    "CYBERPI_FOLLOW_MBLOCK_SPRITE_GRADE_1": "middle(0.4)",
    "CYBERPI_FOLLOW_MBLOCK_SPRITE_GRADE_2": "high(0.6)",
    "cyberpi_follow_mblock_sprite": "control[spriteMenu_1]to follow CyberPi with sensitivity[GRADE]",
    "CYBERPI_DETECT_ATTITUDE_TILT_0": "tilted forward",
    "CYBERPI_DETECT_ATTITUDE_TILT_1": "tilted backward",
    "CYBERPI_DETECT_ATTITUDE_TILT_2": "tilted left",
    "CYBERPI_DETECT_ATTITUDE_TILT_3": "tilted right",
    "CYBERPI_DETECT_ATTITUDE_TILT_4": "screen up",
    "CYBERPI_DETECT_ATTITUDE_TILT_5": "screen down",
    "cyberpi_detect_attitude": " [tilt]?",
    "CYBERPI_DETECT_ACTION_TILT_0": "wave up",
    "CYBERPI_DETECT_ACTION_TILT_1": "wave down",
    "CYBERPI_DETECT_ACTION_TILT_2": "wave left",
    "CYBERPI_DETECT_ACTION_TILT_3": "wave right",
    "CYBERPI_DETECT_ACTION_TILT_4": "rotate clockwise",
    "CYBERPI_DETECT_ACTION_TILT_5": "rotate counterclockwise",
    "CYBERPI_DETECT_ACTION_TILT_6": "queda livre",
    "CYBERPI_DETECT_ACTION_TILT_7": "agitado",
    "cyberpi_detect_action": "[tilt]detected?",
    "cyberpi_shaked_value": "agitando a força",
    "cyberpi_wave_angle": "waving direction (°)",
    "cyberpi_wave_speed": "waving speed",
    "CYBERPI_TILT_DEGREE_ROTATION_0": "tilted forward",
    "CYBERPI_TILT_DEGREE_ROTATION_1": "tilted backward(pitch)",
    "CYBERPI_TILT_DEGREE_ROTATION_2": "tilted left",
    "CYBERPI_TILT_DEGREE_ROTATION_3": "tilted right(roll)",
    "CYBERPI_TILT_DEGREE_ROTATION_4": "rotate clockwise",
    "CYBERPI_TILT_DEGREE_ROTATION_5": "rotate counterclockwise(yaw)",
    "cyberpi_tilt_degree": " [rotation]angle (°)",
    "CYBERPI_AXIS_ACCELERATION_AXIS_0": "x",
    "CYBERPI_AXIS_ACCELERATION_AXIS_1": "y",
    "CYBERPI_AXIS_ACCELERATION_AXIS_2": "z",
    "cyberpi_axis_acceleration": "motion sensor[axis]acceleration(m/s²)",
    "cyberpi_axis_angle_speed": "angle speed around [axis]axis(°/s)",
    "cyberpi_axis_rotation_angle": "rotated angle around [axis]axis (°)",
    "CYBERPI_RESET_AXIS_ROTATION_ANGLE_AXIS_0": "todos",
    "CYBERPI_RESET_AXIS_ROTATION_ANGLE_AXIS_1": "x",
    "CYBERPI_RESET_AXIS_ROTATION_ANGLE_AXIS_2": "y",
    "CYBERPI_RESET_AXIS_ROTATION_ANGLE_AXIS_3": "z",
    "cyberpi_reset_axis_rotation_angle": "reset rotated angle around[axis]axis",
    "cyberpi_reset_yaw": "reset yaw angle",
    "cate_c589c493": "Motion Sensing",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_0": "pulled↑",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_1": "pulled↓",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_2": "pulled←",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_3": "pulled→",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_4": "middle pressed",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_5": "any direction",
    "cyberpi_direction_key_press": "joystick[fieldMenu_1]?",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_0": "pulled↑",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_1": "pulled↓",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_2": "pulled←",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_3": "pulled→",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_4": "middle pressed",
    "cyberpi_direction_key_count": "joystick [fieldMenu_1]counts",
    "cyberpi_direction_key_count_reset": "reset joystick [fieldMenu_1]counts",
    "CYBERPI_BUTTON_PRESS_FIELDMENU_1_0": "A",
    "CYBERPI_BUTTON_PRESS_FIELDMENU_1_1": "B",
    "CYBERPI_BUTTON_PRESS_FIELDMENU_1_2": "any button",
    "cyberpi_button_press": "button[fieldMenu_1]pressed?",
    "CYBERPI_BUTTON_COUNT_FIELDMENU_1_0": "A",
    "CYBERPI_BUTTON_COUNT_FIELDMENU_1_1": "B",
    "cyberpi_button_count": "button[fieldMenu_1]press counts",
    "cyberpi_button_count_reset": "reset button[fieldMenu_1]press counts",
    "cyberpi_loudness": "intensidade do som",
    "cyberpi_brightness": "ambient light intensity",
    "cyberpi_timer_get": "temporriz (s)",
    "cyberpi_timer_reset": "reiniciar o cronómetro",
    "cyberpi_name": "hostname",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_0": "battery level(%)",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_1": "MAC address",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_2": "Bluetooth name",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_3": "system language",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_4": "extension name",
    "cyberpi_battery_macaddress_blename_and_so_on": "[fieldMenu_1]",
    "E_1784_n": "Sensores",
    "cyberpi_mesh_create": "configurar LAN nomeado[mesh_name]",
    "cyberpi_mesh_join": "aderir à LAN com o nome [mesh_name]",
    "cyberpi_set_wifi_broadcast": "broadcast message [message] on LAN",
    "cyberpi_set_wifi_broadcast_with_value": "broadcast message[message]with value[value]on LAN",
    "cyberpi_wifi_broadcast_when_received_message": "when receiving[message]boadcast on LAN",
    "cyberpi_wifi_broadcast_get_value": "LAN broadcast [message]value received",
    "mesh": "Lan",
    "cyberpi_wifi_set": "connect to Wi-Fi[ssid] password [wifipassword]",
    "cyberpi_wifi_is_connect": "network connected?",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_0": "(1) Chinese",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_1": "(2) Chinese(Taiwan)",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_2": "(3) Cantonese",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_3": "(4) Japanese",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_4": "(5) English",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_5": "(6) French",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_6": "(7) German",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_7": "(8) Spanish",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_8": "(9) Portuguese",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_9": "(10) Russian",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_10": "(11) Korean",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_11": "(12) Italian",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_12": "(13) Dutch",
    "cyberpi_speak_with_some_language": "speak [fieldMenu_1] [string_2]",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_2_FIELDMENU_1_0": "Chinês",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_2_FIELDMENU_1_1": "Inglês",
    "cyberpi_speak_with_some_language_2": "speak[fieldMenu_1][string_2]",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_3_FIELDMENU_1_0": "auto",
    "cyberpi_speak_with_some_language_3": "speak[fieldMenu_1][string_2]",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_0": "(1) Chinese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_1": "(2) Chinese(Taiwan)",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_2": "(3) Cantonese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_3": "(4) English",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_4": "(5) French",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_5": "(6) German",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_6": "(7) Spanish",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_7": "(8) Italian",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_8": "(9) Japanese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_9": "(10) Portuguese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_10": "(11) Russian",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_11": "(12) Korean",
    "cyberpi_speech_recognition_with_time_3": "recognize[fieldMenu_1] [number_2]secs",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_0": "(1) Chinese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_1": "(2) Chinese(Taiwan)",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_2": "(3) Cantonese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_3": "(4) English",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_4": "(5) French",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_5": "(6) German",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_6": "(7) Spanish",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_7": "(8) Italian",
    "cyberpi_speech_recognition_with_time_2": "recognize[fieldMenu_1] [number_3]secs",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_0": "(1) Chinese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_1": "(2) Chinese(Taiwan)",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_2": "(3) Cantonese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_3": "(4) Japanese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_4": "(5) English",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_5": "(6) French",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_6": "(7) German",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_7": "(8) Spanish",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_8": "(9) Portuguese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_9": "(10) Russian",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_10": "(11) Korean",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_11": "(12) Italian",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_12": "(13) Dutch",
    "cyberpi_speech_recognition_with_record_2": "对录音进行 [fieldMenu_1]  识别",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_0": "(1) Chinese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_1": "(2) Chinese (Taiwan)",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_2": "(3) Cantonese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_3": "(4) Japanese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_4": "(5) English",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_5": "(6) French",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_6": "(7) German",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_7": "(8) Spanish",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_8": "(9) Portuguese",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_9": "(10) Russian",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_10": "(11) Korean",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_11": "(12) Italian",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_12": "(13) Dutch",
    "cyberpi_speech_recognition_with_time": "recognize[fieldMenu_1] [number_3]secs",
    "BLOCK_1599643085220": "识别 [fieldMenu_1]  [number_3] 秒 copy",
    "cyberpi_speech_recognition_with_record": "对录音进行 [fieldMenu_1]   识别",
    "cyberpi_speech_recognition_result": "resultado do reconhecimento de voz",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_0": "Chinês",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_1": "Inglês",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_2": "Traditional Chinese",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_3": "Japanese",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_4": "Francês",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_5": "Alemão",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_6": "Espanhol",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_7": "Portuguese",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_8": "Russian",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_9": "Korean",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_10": "Italiano",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_11": "Dutch",
    "cyberpi_translate_to_some_language_2": "translate[string_1] into[fieldMenu_2]",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_FIELDMENU_2_0": "Chinês",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_FIELDMENU_2_1": "Inglês",
    "cyberpi_translate_to_some_language": "translate [string_1]into[fieldMenu_2]",
    "ai": "AI",
    "cyberpi_set_cloud_broadcast": "send user cloud broadcast[message]",
    "cyberpi_set_cloud_broadcast_with_value": "send user cloud broadcast [message]with value [value]",
    "cyberpi_when_cloud_broadcast": "when receiving user cloud broadcast[message]",
    "cyberpi_cloud_broadcast_get_value": "user cloud broadcast[message]value received",
    "widget_445594f4": "localização",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_0": "highest temperature (℃)",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_1": "lowest temperature(℃)",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_2": "highest temperature(℉)",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_3": "lowest temperature(℉)",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_4": "meteorologia",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_5": "humidade",
    "cyberpi_get_weather_from_internet": "[LOCATION] [WEATHER_TYPE]",
    "widget_dcc97542": "localização",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_0": "AQI",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_1": "PM2.5",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_2": "PM10",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_3": "CO",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_4": "SO₂",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_5": "NO₂",
    "cyberpi_get_air_quality_from_internet": "air quality[METEOROLOGICAL] [aq_type]",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_SUN_MOVE_TYPE_0": "nascer do sol",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_SUN_MOVE_TYPE_1": "pôr do sol",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_TIME_TYPE_0": "hora",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_TIME_TYPE_1": "hora",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_TIME_TYPE_2": "minuto",
    "cyberpi_get_sun_time_from_internet": "[LOCATION]  [sun_move_type] [time_type]",
    "CYBERPI_GET_LOCAL_TIME_FROM_INTERNET_FIELDMENU_3_0": "hora",
    "CYBERPI_GET_LOCAL_TIME_FROM_INTERNET_FIELDMENU_3_1": "hora",
    "CYBERPI_GET_LOCAL_TIME_FROM_INTERNET_FIELDMENU_3_2": "minuto",
    "cyberpi_get_local_time_from_internet": "get [widget_1] local time [fieldMenu_3]",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_0": "local time",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_1": "local hour",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_2": "local minute",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_3": "sunrise time",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_4": "sunrise hour",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_5": "sunrise minute",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_6": "sunset time",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_7": "sunset hour",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_8": "sunset minute",
    "cyberpi_get_time_from_internet": "get[widget_1]'s [fieldMenu_3]",
    "BLOCK_1610527804319_FIELDMENU_1_0": "(0) UTC",
    "BLOCK_1610527804319_FIELDMENU_1_1": "(1) UTC+1",
    "BLOCK_1610527804319_FIELDMENU_1_2": "(2) UTC+2",
    "BLOCK_1610527804319_FIELDMENU_1_3": "(3) UTC+3",
    "BLOCK_1610527804319_FIELDMENU_1_4": "(4) UTC+4",
    "BLOCK_1610527804319_FIELDMENU_1_5": "(5) UTC+5",
    "BLOCK_1610527804319_FIELDMENU_1_6": "(6) UTC+6",
    "BLOCK_1610527804319_FIELDMENU_1_7": "(7) UTC+7",
    "BLOCK_1610527804319_FIELDMENU_1_8": "(8) UTC+8",
    "BLOCK_1610527804319_FIELDMENU_1_9": "(9) UTC+9",
    "BLOCK_1610527804319_FIELDMENU_1_10": "(10) UTC+10",
    "BLOCK_1610527804319_FIELDMENU_1_11": "(11) UTC+11",
    "BLOCK_1610527804319_FIELDMENU_1_12": "(12) UTC-12",
    "BLOCK_1610527804319_FIELDMENU_1_13": "(-11) UTC-11",
    "BLOCK_1610527804319_FIELDMENU_1_14": "(-10) UTC-10",
    "BLOCK_1610527804319_FIELDMENU_1_15": "(-9) UTC-9",
    "BLOCK_1610527804319_FIELDMENU_1_16": "(-8) UTC-8",
    "BLOCK_1610527804319_FIELDMENU_1_17": "(-7) UTC-7",
    "BLOCK_1610527804319_FIELDMENU_1_18": "(-6) UTC-6",
    "BLOCK_1610527804319_FIELDMENU_1_19": "(-5) UTC-5",
    "BLOCK_1610527804319_FIELDMENU_1_20": "(-4) UTC-4",
    "BLOCK_1610527804319_FIELDMENU_1_21": "(-3) UTC-3",
    "BLOCK_1610527804319_FIELDMENU_1_22": "(-2) UTC-2",
    "BLOCK_1610527804319_FIELDMENU_1_23": "(-1) UTC-1",
    "BLOCK_1610527804319_FIELDMENU_2_0": "ano",
    "BLOCK_1610527804319_FIELDMENU_2_1": "mês",
    "BLOCK_1610527804319_FIELDMENU_2_2": "day",
    "BLOCK_1610527804319_FIELDMENU_2_3": "week",
    "BLOCK_1610527804319_FIELDMENU_2_4": "hora",
    "BLOCK_1610527804319_FIELDMENU_2_5": "minuto",
    "BLOCK_1610527804319_FIELDMENU_2_6": "segundo",
    "BLOCK_1610527804319": "get [fieldMenu_1]'s [fieldMenu_2]",
    "iot": "IoT",
    "cyberpi_when_launch": "[ICON]when CyberPi starts up",
    "cyberpi_when_direction_key_press": "[image_1]when joystick [fieldMenu_2]",
    "cyberpi_when_button_press": "[image_1]when button[fieldMenu_2]pressed",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_0": "tilted left",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_1": "tilted right",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_2": "tilted forward",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_3": "tilted backward",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_4": "screen faces up",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_5": "screen faces down",
    "cyberpi_when_detect_attitude": "[image_1]when CyberPi[tilt]",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_0": "wave left",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_1": "wave right",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_2": "wave up",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_3": "wave down",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_4": "rotate clockwise",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_5": "rotate countercloclwise",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_6": "queda livre",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_7": "agitado",
    "cyberpi_when_detect_action": "[image_1]when[tilt]detected",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_2_0": "luz",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_2_1": "som",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_2_2": "agitando a força",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_2_3": "cronómetro",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_3_0": ">",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_3_1": "<",
    "cyberpi_when_sensor_value_bigger_or_smaller_than": "[image_1]when[fieldMenu_2]value [fieldMenu_3][number_3]",
    "cyberpi_restart": "[image_1]restart CyberPi",
    "cyberpi_python_insert": "插入代码  [string_1] ",
    "CYBERPI_OPERATOR_CASTS_FIELDMENU_1_0": "integer",
    "CYBERPI_OPERATOR_CASTS_FIELDMENU_1_1": "float",
    "CYBERPI_OPERATOR_CASTS_FIELDMENU_1_2": "cadeia de carateres",
    "cyberpi_operator_casts": "read[string_2] in[fieldMenu_1]",
    "e_509_c_events_b_18280": "when HaloCode [tilt]",
    "e_509_c_events_b_18281": "Quando o pino [touchpad_number] é tocado",
    "e_509_c_1410_b_18249": "todos os LEDs acendem [color_1]",
    "haloboard_show_ring_effect": "jogar animação LED  [LED_animation] até feito",
    "haloboard_show_ring_color": "mostrar [ledRing]",
    "haloboard_show_rotation_color": "Mostrar [ledRing] Depois [rotate] Rotativa [led_number] Leds",
    "haloboard_show_all_leds_with_lightness": "todos os LEDs acendem  [color_1]Brilho [lightness] %",
    "haloboard_show_all_leds_with_rgb": "light up all LEDs with color R [r]G  [g]B  [b]",
    "haloboard_show_single_led_with_rgb": "Ilumine acima o diodo emissor de luz [led_id] com cor R [r] G [g] B [b]",
    "haloboard_show_percentage": "Anel LED mostra [percentage]  %",
    "haloboard_detect_touch": "Touchpad [touchpad_number] é tocado?",
    "haloboard_detect_tilt": "HaloCode is [tilt] ？",
    "haloboard_detect_axis_acceleration": "aceleração do sensor de movimento (m/s ²)  [axis] Eixo",
    "haloboard_detect_tilt_degree": "motion sensor [rotation] angle(°)",
    "haloboard_detect_rotation_degree": "rotation angle around [axis]",
    "haloboard_reset_rotation_degree": "redefinir o ângulo de rotação em torno  [axis]",
    "haloboard_pin_read_digtial": " pino de leitura digital [pin_number]",
    "haloboard_pin_write_digtial": " escrita digital [Digtial_value] para fixar [pin_number]",
    "haloboard_pin_set_servo": "pino servo [pin_number] gira para [ServoRotaryAngle]",
    "BLOCK_1543754866399": "alarme pino [pin] reproduz som em frequência [frequency] HZ para [duration] Segundos",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_1": "Spindrift",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_2": "Meteoro",
    "haloboard_detect_time": "temporizador (s)",
    "BLOCK_1543818559542_TEMPO_4": "dois tempos",
    "haloboard_pin_write_PWM": "escrever analógico  [PWM_value] para fixar [pin_number]",
    "haloboard_mesh_join1": "aderir à LAN com o nome [mesh_name]",
    "haloboard_mesh_create1": "configurar LAN nomeado[mesh_name]",
    "halo_play_buzzer_with_note": "alarme pino[pin_num]  desempenha nota [note] Para [beat]",
    "halo_pin_play_buzzer_with_frequency": "alarme pino [pin_num] desempenha na frequência de [frequency] HZ para [duration]Segundos",
    "BLOCK_1552905879755": "definir Touchpad [touchpad_number] sensibilidade para[sensitivity]",
    "BLOCK_1574094194223": "read[string_2] in[fieldMenu_1]",
    "BLOCK_1586933935668": "execute code[string_1]",
    "cyberpi_play_music_with_note_2": "play [fieldMenu_1]for [number_3]beat",
    "cybeipi_name": "Hostname:",
    "affirm": "Ok",
    "Wifi_name": "Wi-Fi name:",
    "Wifi_password": "Wi-Fi password:",
    "city": "Cidade"
};