export default {
    "cyberpi": "CyberPi",
    "extensionName": "CyberPi",
    "extensionDescription": "Içine gurnalan Wi-Fi baglanyşykly HaloCode ýeke plataly kompýuter",
    "firmwares_version_9c2fcf2b": "Soňky firmware programmasy",
    "UPDATE_FIRMWARE": "Firmware programmasynyň täzelenmegi",
    "settings_05de708e": "Host adyny belläň",
    "settings_cc775efd": "Wi-Fi gurnamak",
    "connect_fail_418dd2b0": "USB kabeliňiziň enjama dogry baglanandygyny anyklaň.",
    "connect_fail_be44da45": "Baglanylýan enjamyň işledilendigini anyklaň.",
    "connect_fail_81f19800": "Şu wersiýada diňe bir enjama baglanmaga rugsat berilýär. Bu enjama baglanmak öňki enjamyň baglanyşygynyň kesilmegini netije berer.",
    "connect_fail_a2244e18": "Kompýuteriňiziň Bluetooth 4.0 aýratynlygyny gollaýandygy we Bluetooth baglanyşygynyň şledilendigini anyklaň.",
    "connect_fail_2ff4c830": "Baglanylýan enjamyň işledilendigini anyklaň.",
    "connect_fail_f516f160": "Şu wersiýada diňe bir enjama baglanmaga rugsat berilýär. Bu enjama baglanmak öňki enjamyň baglanyşygynyň kesilmegini netije berer.",
    "upload_fail_440e4ba6": "Şu enjam üçin ähli kodlama bloklaryny ýa-da kodlary gözden geçiriň. Ähli maglumatlaryň, sazlamalaryň we programmirleýiş logikasynyň dogrudygyny anyklaň.",
    "upload_fail_24d8e745": "Enjamyňyzyň dogry baglanandygyny anyklaň. Enjamy täzeden işledip täzeden baglap bilersiňiz.",
    "upload_fail_c52d223b": "Firmware programmaňyzyň dogry işleýändigini anyklaň. Siz firmware programmaňyzy täzelendirip ýa-da zawod sazlamalaryna gaýtaryp täzeden synanyşyp görüň.",
    "firmware_success_70e9b6c0": "Has gowy tejribe üçin enjamy täzeden işlediň we ony täzeden baglaň.",
    "firmware_fail_9b5aae92": "Enjamyň dogry baglanandygyny anyklaň. Siz enjamy täzeden işledip, täzeden baglap soňra bolsa firmware programmasyny täzelemegi barlap görüň.",
    "firmware_fail_9a92af14": "Bu enjam Bluetooth adapteri arkaly ýa-da başga bir usul bilen firmware programmasynyň täzelenmegini gollamaýar.",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_0": "salam",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_1": "sag bol",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_2": "hawa",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_3": "wow",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_4": "gülki",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_5": "güwwüldi",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_6": "gynançly",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_7": "uludan dem alyş",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_8": "gaharlanan",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_9": "gaharly",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_10": "geň galan",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_11": "süýjije",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_12": "bilesigeliji",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_13": "utanan",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_14": "taýýar",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_15": "ylga",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_16": "ukuly",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_17": "maw",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_18": "başla",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_19": "pereklýuçatel",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_20": "gudoklar",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_21": "wazzyldy",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_22": "partlama",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_23": "bökmek",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_24": "lazer",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_25": "täze dereje",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_26": "pes energiýa",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_27": "duýduryş sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_28": "sag",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_29": "ýalňyş",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_30": "halka",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_31": "utuk",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_32": "oýan",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_33": "duýduryş",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_34": "demir sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_35": "atyş",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_36": "aýna şyňňyrdamasy",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_37": "inflýator",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_38": "akýan suw sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_39": "sagat sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_40": "şyrkyldy sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_41": "häzirki",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_42": "agaç sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_43": "demir sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_44": "gaçmak sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_45": "köpürjik sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_46": "tolkun",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_47": "jady",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_48": "spitfire",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_49": "ýürek urgusy",
    "CYBERPI_PLAY_AUDIO_UNTIL_2_FILE_NAME_50": "ýük",
    "cyberpi_play_audio_until_2": "play[file_name]until done",
    "cyberpi_play_audio_2": "[file_name] aýtdyr",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_0": "salam",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_1": "sag bol",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_2": "hawa",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_3": "wow",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_4": "gülki",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_5": "güwwüldi",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_6": "gynançly",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_7": "uludan dem alyş",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_8": "gaharlanan",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_9": "gaharly",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_10": "geň galan",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_11": "süýjije",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_12": "bilesigeliji",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_13": "utanan",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_14": "taýýar",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_15": "ylga",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_16": "ukuly",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_17": "maw",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_18": "başla",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_19": "pereklýuçatel",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_20": "gudoklar",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_21": "wazzyldy",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_22": "bökmek",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_23": "täze dereje",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_24": "pes energiýa",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_25": "duýduryş sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_26": "sag",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_27": "ýalňyş",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_28": "halka",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_29": "utuk",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_30": "oýan",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_31": "duýduryş",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_32": "demir sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_33": "aýna şyňňyrdamasy",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_34": "inflýator",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_35": "akýan suw sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_36": "sagat sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_37": "şyrkyldy sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_38": "häzirki",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_39": "agaç sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_40": "demir sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_41": "gaçmak sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_42": "köpürjik sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_43": "tolkun",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_44": "jady",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_45": "spitfire",
    "CYBERPI_PLAY_AUDIO_UNTIL_3_FILE_NAME_46": "ýürek urgusy",
    "cyberpi_play_audio_until_3": "gutarýança [file_name] aýtdyr",
    "cyberpi_play_audio_3": "[file_name] aýtdyr",
    "cyberpi_start_record": "ýazgy etmäge başla",
    "cyberpi_stop_record": "ýazgy etmegi duruz",
    "cyberpi_play_record_until": "ses ýazgysyny gutarýança aýtdyr",
    "cyberpi_play_record": "ses ýazgysyny aýtdyr",
    "cyberpi_play_music_with_tone_and_note": "[number_1] notasyny [number_2] gezek aýtdyr",
    "cyberpi_play_music_with_tone_and_note_2": "[number_1] notasyny [number_2] gezek aýtdyr",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_0": "kiçi deprek",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_1": "uly deprek",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_2": "taýajyklar",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_3": "tarelkalar",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_4": "açyk tarelkalar",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_5": "ýapyk tarelkalar",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_6": "deprek",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_7": "el çarpma",
    "CYBERPI_PLAY_MUSIC_WITH_NOTE_FIELDMENU_1_8": "klawişler",
    "cyberpi_play_music_with_note": "[number_3] gezekligine [fieldMenu_1] aýtdyr",
    "cyberpi_add_audio_speed": "ses tizligini [number_1] % ýokarlandyr",
    "cyberpi_set_audio_speed": "ses tizligini [number_1]% edip sazla",
    "cyberpi_get_audio_speed": "ses tizligi",
    "cyberpi_add_volume": "ses kuwwatlylygyny [number_1]% ýokarlandyr",
    "cyberpi_set_volume": "sesiň kuwwatlylygyny [number_1] % edip sazla",
    "cyberpi_get_volume": "sesiň kuwwatlylygy(%)",
    "cyberpi_play_buzzer_tone_with_time": "[number_1]Hz ýygylykly sesi [number_2]sekuntlap aýtdyr",
    "cyberpi_play_buzzer_tone": "[number_2]Hz ýygylykly sesi aýtdyr",
    "cyberpi_stop_audio": "ähli sesleri duruz",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_0": "salam",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_1": "sag bol",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_2": "hawa",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_3": "wow",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_4": "gülki",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_5": "güwwüldi",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_6": "gynançly",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_7": "uludan dem alyş",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_8": "gaharlanan",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_9": "gaharly",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_10": "geň galan",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_11": "süýjije",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_12": "bilesigeliji",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_13": "utanan",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_14": "taýýar",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_15": "ylga",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_16": "ukuly",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_17": "maw",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_18": "başla",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_19": "pereklýuçatel",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_20": "gudoklar",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_21": "wazzyldy",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_22": "partlama",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_23": "bökmek",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_24": "lazer",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_25": "täze dereje",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_26": "pes energiýa",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_27": "duýduryş sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_28": "sag",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_29": "ýalňyş",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_30": "halka",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_31": "utuk",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_32": "oýan",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_33": "duýduryş",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_34": "demir sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_35": "atyş",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_36": "aýna şyňňyrdamasy",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_37": "inflýator",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_38": "akýan suw sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_39": "sagat sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_40": "şyrkyldy sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_41": "häzirki",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_42": "pereklýuçatel",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_43": "agaç sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_44": "demir sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_45": "gaçmak sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_46": "köpürjik sesi",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_47": "tolkun",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_48": "jady",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_49": "spitfire",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_50": "ýürek urgusy",
    "CYBERPI_PLAY_AUDIO_UNTIL_FILE_NAME_51": "ýük",
    "cyberpi_play_audio_until": "gutarýança [file_name] aýtdyr",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_0": "salam",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_1": "sag bol",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_2": "hawa",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_3": "wow",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_4": "gülki",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_5": "güwwüldi",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_6": "gynançly",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_7": "uludan dem alyş",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_8": "gaharlanan",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_9": "gaharly",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_10": "geň galan",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_11": "süýjije",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_12": "bilesigeliji",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_13": "utanan",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_14": "taýýar",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_15": "ylga",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_16": "ukuly",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_17": "maw",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_18": "başla",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_19": "pereklýuçatel",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_20": "gudoklar",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_21": "wazzyldy",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_22": "partlama",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_23": "bökmek",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_24": "lazer",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_25": "täze dereje",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_26": "pes energiýa",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_27": "duýduryş sesi",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_28": "sag",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_29": "ýalňyş",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_30": "halka",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_31": "utuk",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_32": "oýan",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_33": "duýduryş",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_34": "demir sesi",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_35": "atyş",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_36": "aýna şyňňyrdamasy",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_37": "inflýator",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_38": "akýan suw sesi",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_39": "sagat sesi",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_40": "şyrkyldy sesi",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_41": "häzirki",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_42": "pereklýuçatel",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_43": "agaç sesi",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_44": "demir sesi ",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_45": "gaçmak sesi",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_46": "köpürjik sesi ",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_47": "tolkun",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_48": "jady",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_49": "spitfire",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_50": "心跳",
    "CYBERPI_PLAY_AUDIO_FILE_NAME_51": "ýük",
    "cyberpi_play_audio": "[file_name] aýtdyr",
    "cate_34b1ba6f": "Ses",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_0": "älemgoşar",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_1": "spindrift",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_2": "meteor (gök)",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_3": "meteor (ýaşyl)",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_4": "geliý alowy (gyzyl)",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_5": "geliý alowy (mämişi)",
    "CYBERPI_PLAY_LED_ANIMATION_UNTIL_LED_ANIMATION_6": "ýaldyrawuk tomzak",
    "cyberpi_play_led_animation_until": "[LED_animation] yşyk-diot animasiýasyny gutarýança görkez",
    "cyberpi_show_led": "[ledRing] görkez",
    "cyberpi_move_led": "[led_number]LEDleri saga aýla",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_0": "ählisi",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_1": "1",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_2": "2",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_3": "3",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_4": "4",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_2_FIELDMENU_1_5": "5",
    "cyberpi_led_show_single_with_color_and_time_2": "[fieldMenu_1]LED-i [color_1] reňkini [number_3] sekuntlap görkezýär",
    "cyberpi_led_show_single_with_color_2": "[fieldMenu_1]LED-i [color_1] reňkini görkezýär",
    "cyberpi_led_show_single_with_rgb_and_time": "[fieldMenu_1]LED-i [r]gyzyl [g]ýaşyl [b]gök reňklerini [number_5] sekuntlap görkezýär",
    "cyberpi_led_show_single_with_rgb_2": "[fieldMenu_1]LED-i [r]gyzyl [g]ýaşyl [b]gök reňklerini görkezýär",
    "cyberpi_add_led_brightness": "LED parlaklygyny[number_1]% artdyr",
    "cyberpi_set_led_brightness": "parlaklygy [number_1]% et",
    "cyberpi_get_led_brightness": "LED parlaklygy(%)",
    "cyberpi_led_off_2": "[fieldMenu_1] LED-i öçür",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_0": "ählisi",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_1": "1",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_2": "2",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_3": "3",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_4": "4",
    "CYBERPI_LED_SHOW_SINGLE_WITH_COLOR_AND_TIME_FIELDMENU_1_5": "5",
    "cyberpi_led_show_single_with_color_and_time": "[fieldMenu_1]LED-i [color_1] reňkini [number_3] sekuntlap görkezýär",
    "cyberpi_led_show_single_with_color": "[fieldMenu_1]LED-i [color_1] reňkini görkezýär",
    "cyberpi_led_show_single_with_rgb": "[fieldMenu_1]LED-i [r]gyzyl [g]ýaşyl [b]gök reňklerini görkezýär",
    "cyberpi_led_off": "[fieldMenu_1] LED-i öçür",
    "E_1783_n": "LED",
    "cyberpi_display_println": "[string_2] ýaz we täze setire geç",
    "cyberpi_display_print": "[string_2] ýazdyr",
    "CYBERPI_CONSOLE_SET_FONT_INPUTMENU_1_0": "kiçi",
    "CYBERPI_CONSOLE_SET_FONT_INPUTMENU_1_1": "orta",
    "CYBERPI_CONSOLE_SET_FONT_INPUTMENU_1_2": "uly",
    "CYBERPI_CONSOLE_SET_FONT_INPUTMENU_1_3": "super uly",
    "cyberpi_console_set_font": "set print size to [inputMenu_1]",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_0": "ekranyň merkezi",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_1": "ortada ýokarda",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_2": "ortada aşakda",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_3": "ortada çepde",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_4": "ortada sagda",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_5": "ýokarky çepdäki burç",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_6": "ýokarky sagdaky burç",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_7": "aşaky çepdäki burç",
    "CYBERPI_DISPLAY_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_2_8": "aşaky sagdaky burç",
    "cyberpi_display_show_at_somewhere_with_size": "görkez:[string_2] ýeri:[fieldMenu_2] ölçegi:[inputMenu_4]piksel",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_0": "1",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_1": "2",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_2": "3",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_3": "4",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_4": "5",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_5": "6",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_6": "7",
    "CYBERPI_DISPLAY_LABEL_SHOW_AT_SOMEWHERE_WITH_SIZE_FIELDMENU_1_7": "8",
    "cyberpi_display_label_show_at_somewhere_with_size": "show label [fieldMenu_1]  [string_2] at [fieldMenu_2] by [inputMenu_4]pixel",
    "cyberpi_display_show_label_xy_with_size": "görkez:[string_2]ýeri: x[number_2] y[number_3]ölçegi:[inputMenu_4]piksel",
    "cyberpi_display_label_show_label_xy_with_size": "show label [fieldMenu_1] [string_2] at x: [number_2] y [number_3] by [inputMenu_4] pixel",
    "cyberpi_display_set_chart_name": "diagrammanyň adyny [string_1] et",
    "cyberpi_display_line_chart_add_data": "çyzykly grafik, [number_1] maglumat goş",
    "cyberpi_display_bar_chart_set_interval": "çyzykly grafik, aralygy [number_3] piksel et",
    "cyberpi_display_bar_chart_add_data": "gistogramma, [number_1] maglumat goş",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_1_0": "1",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_1_1": "2",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_1_2": "3",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_1_3": "4",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_2_0": "1",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_2_1": "2",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_2_FIELDMENU_2_2": "3",
    "cyberpi_display_table_add_data_at_row_column_2": "tablisa, giriş[string_3] setir:[fieldMenu_1], sütün:[fieldMenu_2]",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_0": "1",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_1": "2",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_2": "3",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_3": "4",
    "CYBERPI_DISPLAY_TABLE_ADD_DATA_AT_ROW_COLUMN_FIELDMENU_1_4": "5",
    "cyberpi_display_table_add_data_at_row_column": "tablisa, giriş[string_3] setir:[fieldMenu_1], sütün:[fieldMenu_2]",
    "cyberpi_display_clear_chart": "maglumatlary arassala",
    "cyberpi_display_set_brush_with_color": "çotganyň reňkini [color_1] et",
    "cyberpi_display_set_brush_with_r_g_b": "çotganyň reňkini R [number_1] G [number_2] B [number_3] et",
    "CYBERPI_DISPLAY_ROTATE_TO_2_FIELDMENU_1_0": "baş aşak(-90°)",
    "CYBERPI_DISPLAY_ROTATE_TO_2_FIELDMENU_1_1": "çepe (0°)",
    "CYBERPI_DISPLAY_ROTATE_TO_2_FIELDMENU_1_2": "üýtgewsüz (90°)",
    "CYBERPI_DISPLAY_ROTATE_TO_2_FIELDMENU_1_3": "saga (180°)",
    "cyberpi_display_rotate_to_2": "ekrany [fieldMenu_1] tarap öwürmek",
    "CYBERPI_DISPLAY_ROTATE_TO_FIELDMENU_1_0": "baş aşak(-90°)",
    "CYBERPI_DISPLAY_ROTATE_TO_FIELDMENU_1_1": "çepe (0°)",
    "CYBERPI_DISPLAY_ROTATE_TO_FIELDMENU_1_2": "üýtgewsüz (90°)",
    "CYBERPI_DISPLAY_ROTATE_TO_FIELDMENU_1_3": "saga (180°)",
    "cyberpi_display_rotate_to": "ekrany [fieldMenu_1] tarap öwürmek",
    "cyberpi_display_clear": "ekrany arassalamak",
    "cate_52186034": "Displeý",
    "CYBERPI_FOLLOW_MBLOCK_SPRITE_GRADE_0": "low(0.2)",
    "CYBERPI_FOLLOW_MBLOCK_SPRITE_GRADE_1": "middle(0.4)",
    "CYBERPI_FOLLOW_MBLOCK_SPRITE_GRADE_2": "high(0.6)",
    "cyberpi_follow_mblock_sprite": "[spriteMenu_1] dolandyrmak, [GRADE] duýgurlyk bilen CyberPi yzarlamak",
    "CYBERPI_DETECT_ATTITUDE_TILT_0": "öňe egilen",
    "CYBERPI_DETECT_ATTITUDE_TILT_1": "yza egilen",
    "CYBERPI_DETECT_ATTITUDE_TILT_2": "çepe egilen",
    "CYBERPI_DETECT_ATTITUDE_TILT_3": "saga egilen",
    "CYBERPI_DETECT_ATTITUDE_TILT_4": "screen up",
    "CYBERPI_DETECT_ATTITUDE_TILT_5": "screen down",
    "cyberpi_detect_attitude": " [tilt]?",
    "CYBERPI_DETECT_ACTION_TILT_0": "ýokary tolkun",
    "CYBERPI_DETECT_ACTION_TILT_1": "aşak tolkun",
    "CYBERPI_DETECT_ACTION_TILT_2": "çepe tolkun",
    "CYBERPI_DETECT_ACTION_TILT_3": "saga tolkun",
    "CYBERPI_DETECT_ACTION_TILT_4": "sagadyň öwrüliş ugruna öwürmek",
    "CYBERPI_DETECT_ACTION_TILT_5": "sagadyň öwrüliş ugrunyň tersine öwürmek",
    "CYBERPI_DETECT_ACTION_TILT_6": "erkin gaçyş",
    "CYBERPI_DETECT_ACTION_TILT_7": "yrgyldan",
    "cyberpi_detect_action": "[tilt]anyklandymy?",
    "cyberpi_shaked_value": "titreme kuwwatlylygy",
    "cyberpi_wave_angle": "tolkun ugry (°)",
    "cyberpi_wave_speed": "tolkun tizligi",
    "CYBERPI_TILT_DEGREE_ROTATION_0": "öňe egilen",
    "CYBERPI_TILT_DEGREE_ROTATION_1": "yza egilen(pitch)",
    "CYBERPI_TILT_DEGREE_ROTATION_2": "çepe egilen",
    "CYBERPI_TILT_DEGREE_ROTATION_3": "saga egilen (roll)",
    "CYBERPI_TILT_DEGREE_ROTATION_4": "sagadyň öwrüliş ugruna öwürmek",
    "CYBERPI_TILT_DEGREE_ROTATION_5": "sagadyň öwrüliş ugrunyň tersine öwürmek(yaw)",
    "cyberpi_tilt_degree": " [rotation] burç (°)",
    "CYBERPI_AXIS_ACCELERATION_AXIS_0": "x",
    "CYBERPI_AXIS_ACCELERATION_AXIS_1": "y",
    "CYBERPI_AXIS_ACCELERATION_AXIS_2": "z",
    "cyberpi_axis_acceleration": "hereketi duýujy enjamyň [axis] oky boýunça tizlenmesi (m/s²)",
    "cyberpi_axis_angle_speed": "[axis] okunyň daşyndaky burç tizligi (°/s)",
    "cyberpi_axis_rotation_angle": "[axis] okynyň daşyndan aýlanylan burç möçberi (°)",
    "CYBERPI_RESET_AXIS_ROTATION_ANGLE_AXIS_0": "ählisi",
    "CYBERPI_RESET_AXIS_ROTATION_ANGLE_AXIS_1": "x",
    "CYBERPI_RESET_AXIS_ROTATION_ANGLE_AXIS_2": "y",
    "CYBERPI_RESET_AXIS_ROTATION_ANGLE_AXIS_3": "z",
    "cyberpi_reset_axis_rotation_angle": "[axis] okunyň daşyndan aýlanylan burç möçberini başa gaýtarmak",
    "cyberpi_reset_yaw": "täsirleniş burçuny nollamak",
    "cate_c589c493": "Hereketi Duýmak",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_0": "çekilen↑",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_1": "çekilen↓",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_2": "çekilen←",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_3": "çekilen→",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_4": "orta düwme basylan",
    "CYBERPI_DIRECTION_KEY_PRESS_FIELDMENU_1_5": "islendik ugur",
    "cyberpi_direction_key_press": "joýstik[fieldMenu_1]?",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_0": "çekilen↑",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_1": "çekilen↓",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_2": "çekilen←",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_3": "çekilen→",
    "CYBERPI_DIRECTION_KEY_COUNT_FIELDMENU_1_4": "orta düwme basylan",
    "cyberpi_direction_key_count": "joýstik[fieldMenu_1]sany",
    "cyberpi_direction_key_count_reset": "joýstik[fieldMenu_1]sanyny nollamak",
    "CYBERPI_BUTTON_PRESS_FIELDMENU_1_0": "A",
    "CYBERPI_BUTTON_PRESS_FIELDMENU_1_1": "B",
    "CYBERPI_BUTTON_PRESS_FIELDMENU_1_2": "islendik düwme",
    "cyberpi_button_press": "[fieldMenu_1] düwme basylanmy?",
    "CYBERPI_BUTTON_COUNT_FIELDMENU_1_0": "A",
    "CYBERPI_BUTTON_COUNT_FIELDMENU_1_1": "B",
    "cyberpi_button_count": "[fieldMenu_1] düwmesiniň basylan sanaw sany",
    "cyberpi_button_count_reset": "[fieldMenu_1] düwmesiniň basylan sanaw sanyny nollamak",
    "cyberpi_loudness": "sesiň kuwwatlylygy",
    "cyberpi_brightness": "gurşawyň ýagtylyk kuwwatlylygy",
    "cyberpi_timer_get": "taýmer (sek)",
    "cyberpi_timer_reset": "taýmeri nollamak",
    "cyberpi_name": "host ady",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_0": "batareýa kuwwatlylyk derejesi(%)",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_1": "MAC Salgysy",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_2": "Bluetooth ady",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_3": "ulgam dili",
    "CYBERPI_BATTERY_MACADDRESS_BLENAME_AND_SO_ON_FIELDMENU_1_4": "extension name",
    "cyberpi_battery_macaddress_blename_and_so_on": "[fieldMenu_1]",
    "E_1784_n": "Duýujy enjamlar",
    "cyberpi_mesh_create": "[mesh_name] atly LAN toryny gurnamak",
    "cyberpi_mesh_join": "[mesh_name] atly LAN toryna goşulmak",
    "cyberpi_set_wifi_broadcast": "[message] habaryny LAN arkaly ýaýratmak",
    "cyberpi_set_wifi_broadcast_with_value": "[message] habaryny [value] bahasy bilen LAN arkaly ýaýratmak",
    "cyberpi_wifi_broadcast_when_received_message": "haçan-da [message] habaryny LAN arkaly alýan wagty",
    "cyberpi_wifi_broadcast_get_value": "[message] bahaly LAN ýaýlymy habary alyndy",
    "mesh": "LAN",
    "cyberpi_wifi_set": "[ssid] atly [wifipassword] açar sözli Wi-Fi toruna baglan",
    "cyberpi_wifi_is_connect": "tor baglananmy?",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_0": "(1) Hytaýça",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_1": "(2) Hytaý dili (Taiwan)",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_2": "(3) Kanton",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_3": "(4) Ýaponça",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_4": "(5) Iňlisçe",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_5": "(6) Fransuzça",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_6": "(7) Nemesçe",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_7": "(8) Ispança",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_8": "(9) Portugalça",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_9": "(10) Rusça",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_10": "(11) Koreýçe",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_11": "(12) Italýança",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_FIELDMENU_1_12": "(13) Gollandça",
    "cyberpi_speak_with_some_language": "[fieldMenu_1] geple[string_2]",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_2_FIELDMENU_1_0": "Hytaý",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_2_FIELDMENU_1_1": "Iňlisçe",
    "cyberpi_speak_with_some_language_2": "[fieldMenu_1] geple[string_2]",
    "CYBERPI_SPEAK_WITH_SOME_LANGUAGE_3_FIELDMENU_1_0": "auto",
    "cyberpi_speak_with_some_language_3": "[fieldMenu_1] geple[string_2]",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_0": "(1) Hytaýça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_1": "(2) Hytaý dili (Taiwan)",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_2": "(3) Kanton",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_3": "(4) Iňlisçe",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_4": "(5) Fransuzça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_5": "(6) Nemesçe",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_6": "(7) Ispança",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_7": "(8) Italýança",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_8": "(9) Ýaponça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_9": "(10) Portugalça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_10": "(11) Rusça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_3_FIELDMENU_1_11": "(12) Koreýçe",
    "cyberpi_speech_recognition_with_time_3": "[fieldMenu_1] görnüşini [number_2] sekunt soňra anykla",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_0": "(1) Hytaýça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_1": "(2) Hytaý dili (Taiwan)",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_2": "(3) Kanton",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_3": "(4) Iňlisçe",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_4": "(5) Fransuzça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_5": "(6) Nemesçe",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_6": "(7) Ispança",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_2_FIELDMENU_1_7": "(8) Italýança",
    "cyberpi_speech_recognition_with_time_2": "[fieldMenu_1] görnüşini [number_3] sekunt soňra anykla",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_0": "(1) Hytaýça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_1": "(2) Hytaý dili (Taiwan)",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_2": "(3) Kanton",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_3": "(4) Ýaponça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_4": "(5) Iňlisçe",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_5": "(6) Fransuzça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_6": "(7) Nemesçe",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_7": "(8) Ispança",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_8": "(9) Portugalça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_9": "(10) Rusça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_10": "(11) Koreýçe",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_11": "(12) Italýança",
    "CYBERPI_SPEECH_RECOGNITION_WITH_RECORD_2_FIELDMENU_1_12": "(13) Gollandça",
    "cyberpi_speech_recognition_with_record_2": "对录音进行 [fieldMenu_1]  识别",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_0": "(1) Hytaýça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_1": "(2) Hytaý dili (Taiwan)",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_2": "(3) Kanton",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_3": "(4) Ýaponça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_4": "(5) Iňlisçe",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_5": "(6) Fransuzça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_6": "(7) Nemesçe",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_7": "(8) Ispança",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_8": "(9) Portugalça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_9": "(10) Rusça",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_10": "(11) Koreýçe",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_11": "(12) Italýança",
    "CYBERPI_SPEECH_RECOGNITION_WITH_TIME_FIELDMENU_1_12": "(13) Gollandça",
    "cyberpi_speech_recognition_with_time": "[fieldMenu_1] görnüşini [number_3] sekunt soňra anykla",
    "BLOCK_1599643085220": "识别 [fieldMenu_1]  [number_3] 秒 copy",
    "cyberpi_speech_recognition_with_record": "对录音进行 [fieldMenu_1]   识别",
    "cyberpi_speech_recognition_result": "gepleşik kesgitleýişiniň netijesi",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_0": "Hytaý",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_1": "Iňlisçe",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_2": "Milli Hytaýça",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_3": "Ýaponça",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_4": "Fransuzça",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_5": "Nemesçe",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_6": "Ispança",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_7": "Portugalça",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_8": "Rusça",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_9": "Koreýçe",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_10": "Italýança",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_2_FIELDMENU_2_11": "Gollandça",
    "cyberpi_translate_to_some_language_2": "[string_1] sözleri [fieldMenu_2] diline terjime etmek",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_FIELDMENU_2_0": "Hytaý",
    "CYBERPI_TRANSLATE_TO_SOME_LANGUAGE_FIELDMENU_2_1": "Iňlisçe",
    "cyberpi_translate_to_some_language": "[string_1] sözleri [fieldMenu_2] diline terjime etmek",
    "ai": "AI",
    "cyberpi_set_cloud_broadcast": "[message] ulanyjynyň bulut ulgam habaryny ugrat",
    "cyberpi_set_cloud_broadcast_with_value": "[message] ulanyjynyň bulut ulgam habaryny [value] bahasy bilen ugrat",
    "cyberpi_when_cloud_broadcast": "when receiving user cloud broadcast[message]",
    "cyberpi_cloud_broadcast_get_value": "[message] ulanyjynyň bulut ulgam habarynynyň bahasy alyndy",
    "widget_445594f4": "ýer",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_0": "aňrybaş gyzgynlyk derejesi (℃)",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_1": "iň pes gyzgynlyk derejesi(℃)",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_2": "aňrybaş gyzgynlyk derejesi(℉)",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_3": "iň pes gyzgynlyk derejesi(℉)",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_4": "howa maglumaty",
    "CYBERPI_GET_WEATHER_FROM_INTERNET_WEATHER_TYPE_5": "çyglylyk",
    "cyberpi_get_weather_from_internet": "[LOCATION] [WEATHER_TYPE]",
    "widget_dcc97542": "ýer",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_0": "Howa Hil Indeksi",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_1": "Ultradispers bölejikler görkezijisi PM2.5",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_2": "Ultradispers bölejikler görkezijisi PM10",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_3": "CO",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_4": "SO₂",
    "CYBERPI_GET_AIR_QUALITY_FROM_INTERNET_AQ_TYPE_5": "NO₂",
    "cyberpi_get_air_quality_from_internet": "[aq_type] howa hil derejesi [METEOROLOGICAL]",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_SUN_MOVE_TYPE_0": "günüň doguşy",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_SUN_MOVE_TYPE_1": "günüň ýaşmagy",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_TIME_TYPE_0": "wagt",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_TIME_TYPE_1": "sagat",
    "CYBERPI_GET_SUN_TIME_FROM_INTERNET_TIME_TYPE_2": "minut",
    "cyberpi_get_sun_time_from_internet": "[LOCATION]  [sun_move_type] [time_type]",
    "CYBERPI_GET_LOCAL_TIME_FROM_INTERNET_FIELDMENU_3_0": "wagt",
    "CYBERPI_GET_LOCAL_TIME_FROM_INTERNET_FIELDMENU_3_1": "sagat",
    "CYBERPI_GET_LOCAL_TIME_FROM_INTERNET_FIELDMENU_3_2": "minut",
    "cyberpi_get_local_time_from_internet": "[widget_1] ýerli wagty [fieldMenu_3] almak",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_0": "ýerli wagt",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_1": "ýerli sagat",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_2": "ýerli minut",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_3": "günüň dogýan wagty",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_4": "günüň dogýan sagady",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_5": "günüň dogýan minuty",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_6": "günüň ýaşýan wagty",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_7": "günüň ýaşýan sagady",
    "CYBERPI_GET_TIME_FROM_INTERNET_FIELDMENU_3_8": "günüň ýaşýan minuty",
    "cyberpi_get_time_from_internet": "[widget_1]-den[fieldMenu_3] almak",
    "BLOCK_1610527804319_FIELDMENU_1_0": "(0) UTC",
    "BLOCK_1610527804319_FIELDMENU_1_1": "(1) UTC+1",
    "BLOCK_1610527804319_FIELDMENU_1_2": "(2) UTC+2",
    "BLOCK_1610527804319_FIELDMENU_1_3": "(3) UTC+3",
    "BLOCK_1610527804319_FIELDMENU_1_4": "(4) UTC+4",
    "BLOCK_1610527804319_FIELDMENU_1_5": "(5) UTC+5",
    "BLOCK_1610527804319_FIELDMENU_1_6": "(6) UTC+6",
    "BLOCK_1610527804319_FIELDMENU_1_7": "(7) UTC+7",
    "BLOCK_1610527804319_FIELDMENU_1_8": "(8) UTC+8",
    "BLOCK_1610527804319_FIELDMENU_1_9": "(9) UTC+9",
    "BLOCK_1610527804319_FIELDMENU_1_10": "(10) UTC+10",
    "BLOCK_1610527804319_FIELDMENU_1_11": "(11) UTC+11",
    "BLOCK_1610527804319_FIELDMENU_1_12": "(12) UTC-12",
    "BLOCK_1610527804319_FIELDMENU_1_13": "(-11) UTC-11",
    "BLOCK_1610527804319_FIELDMENU_1_14": "(-10) UTC-10",
    "BLOCK_1610527804319_FIELDMENU_1_15": "(-9) UTC-9",
    "BLOCK_1610527804319_FIELDMENU_1_16": "(-8) UTC-8",
    "BLOCK_1610527804319_FIELDMENU_1_17": "(-7) UTC-7",
    "BLOCK_1610527804319_FIELDMENU_1_18": "(-6) UTC-6",
    "BLOCK_1610527804319_FIELDMENU_1_19": "(-5) UTC-5",
    "BLOCK_1610527804319_FIELDMENU_1_20": "(-4) UTC-4",
    "BLOCK_1610527804319_FIELDMENU_1_21": "(-3) UTC-3",
    "BLOCK_1610527804319_FIELDMENU_1_22": "(-2) UTC-2",
    "BLOCK_1610527804319_FIELDMENU_1_23": "(-1) UTC-1",
    "BLOCK_1610527804319_FIELDMENU_2_0": "ýyl",
    "BLOCK_1610527804319_FIELDMENU_2_1": "aý",
    "BLOCK_1610527804319_FIELDMENU_2_2": "day",
    "BLOCK_1610527804319_FIELDMENU_2_3": "week",
    "BLOCK_1610527804319_FIELDMENU_2_4": "sagat",
    "BLOCK_1610527804319_FIELDMENU_2_5": "minut",
    "BLOCK_1610527804319_FIELDMENU_2_6": "sekunt",
    "BLOCK_1610527804319": "get [fieldMenu_1]'s [fieldMenu_2]",
    "iot": "IoT (Zatlaryň Interneti)",
    "cyberpi_when_launch": "[ICON] CyberPi işläp başlan wagty",
    "cyberpi_when_direction_key_press": "[image_1] haçan-da joýstik [fieldMenu_2] bolan wagty",
    "cyberpi_when_button_press": "[image_1] haçan-da düwme [fieldMenu_2] basylan wagty",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_0": "çepe egilen",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_1": "saga egilen",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_2": "öňe egilen",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_3": "yza egilen",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_4": "ekran ýüzleri ýokary",
    "CYBERPI_WHEN_DETECT_ATTITUDE_TILT_5": "ekran ýüzleri aşak",
    "cyberpi_when_detect_attitude": "[image_1] haçan-da CyberPi[tilt]",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_0": "çepe tolkun",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_1": "saga tolkun",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_2": "ýokary tolkun",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_3": "aşak tolkun",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_4": "sagadyň öwrüliş ugruna öwürmek",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_5": "sagadyň öwrüliş ugrunyň tersine öwürmek",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_6": "erkin gaçyş",
    "CYBERPI_WHEN_DETECT_ACTION_TILT_7": "yrgyldan",
    "cyberpi_when_detect_action": "haçan-da[tilt] anyklanan wagty[image_1]",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_2_0": "yşyk",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_2_1": "ses",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_2_2": "titreme kuwwatlylygy",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_2_3": "taýmer",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_3_0": ">",
    "CYBERPI_WHEN_SENSOR_VALUE_BIGGER_OR_SMALLER_THAN_FIELDMENU_3_1": "<",
    "cyberpi_when_sensor_value_bigger_or_smaller_than": "[image_1]haçan-da[fieldMenu_2]bahasy[fieldMenu_3][number_3]",
    "cyberpi_restart": "[image_1]CyberPi täzeden başlatmak",
    "cyberpi_python_insert": "插入代码  [string_1] ",
    "CYBERPI_OPERATOR_CASTS_FIELDMENU_1_0": "bitin san",
    "CYBERPI_OPERATOR_CASTS_FIELDMENU_1_1": "float",
    "CYBERPI_OPERATOR_CASTS_FIELDMENU_1_2": "setir",
    "cyberpi_operator_casts": "read[string_2] in[fieldMenu_1]",
    "e_509_c_events_b_18280": "haçan-da HaloCode [tilt] wagty",
    "e_509_c_events_b_18281": "haçan-da [touchpad_number] kontaktyna deglen wagty",
    "e_509_c_1410_b_18249": "ähli yşyk-diotlar [color_1] reňki bilen ýanýarlar",
    "haloboard_show_ring_effect": "[LED_animation] yşyk-diot animasiýasyny gutarýança aýtdyr",
    "haloboard_show_ring_color": "[ledRing] görkez",
    "haloboard_show_rotation_color": "yşyk-diot çyralary [led_number] gezek [rotate] aýlamakdan soňra [ledRing] görkez",
    "haloboard_show_all_leds_with_lightness": "ähli yşyk-diotlar [color_1] reňki bilen, [lightness] parlaklyk ýanýarlar",
    "haloboard_show_all_leds_with_rgb": "ähli LEDleri Gyzyl [r] Ýaşyl[g] Gök[b] reňkler bilen ýak",
    "haloboard_show_single_led_with_rgb": "[led_id] yşyk-diot çyrasyny Gyzyl [r] Ýaşyl[g] Gök[b] reňkler bilen ýak",
    "haloboard_show_percentage": "Yşyk-diot halkasy [percentage] % görkezýär",
    "haloboard_detect_touch": "[touchpad_number] kontaktyna deglipdirmi?",
    "haloboard_detect_tilt": "HaloCode [tilt] ýagdaýdamy？",
    "haloboard_detect_axis_acceleration": "hereketi duýujy enjamyň [axis] okundaky tizlenişi  (m/s²)",
    "haloboard_detect_tilt_degree": "hereketi duýujy enjamyň [rotation] burçy(°)",
    "haloboard_detect_rotation_degree": "[axis] okynyň daşyndaky aýlanyş burçy",
    "haloboard_reset_rotation_degree": "aýlanyş burçuny [axis] başa gaýtar",
    "haloboard_pin_read_digtial": " [pin_number] sanly okama kontakty",
    "haloboard_pin_write_digtial": " [pin_number] kontaktyna [Digtial_value] sanly bahany ýaz",
    "haloboard_pin_set_servo": "serwo-hereketlendirijiniň [pin_number] kontakty [ServoRotaryAngle] burçuna çenli aýlanýar",
    "BLOCK_1543754866399": "zummeriň [pin] kontakty [frequency] Hz ýygylykly sesi [duration] sekuntlap aýtdyrýar",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_1": "spindrift",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_2": "meteor",
    "haloboard_detect_time": "taýmer (sek)",
    "BLOCK_1543818559542_TEMPO_4": "iki urgy",
    "haloboard_pin_write_PWM": "[pin_number] kontaktyna [PWM_value] analog bahany ýaz",
    "haloboard_mesh_join1": "[mesh_name] atly LAN toryna goşulmak",
    "haloboard_mesh_create1": "[mesh_name] atly LAN toryny gurnamak",
    "halo_play_buzzer_with_note": "zummeriň [pin_num] kontakty [note] notasyny [beat] temp bilen aýtdyrýar",
    "halo_pin_play_buzzer_with_frequency": "zummeriň [pin_num] kontakty [frequency] Hz ýygylykly sesi [duration] sekuntlap aýtdyrýar",
    "BLOCK_1552905879755": "[touchpad_number] duýgurlyk derejesini [sensitivity] edip sazla",
    "BLOCK_1574094194223": "read[string_2] in[fieldMenu_1]",
    "BLOCK_1586933935668": "[string_1] koduny ýerine ýetirmek",
    "cyberpi_play_music_with_note_2": "[number_3] gezekligine [fieldMenu_1] aýtdyr",
    "cybeipi_name": "Host ady:",
    "affirm": "Bolýar",
    "Wifi_name": "Wi-Fi ady:",
    "Wifi_password": "Wi-Fi açarsözüňizi giriziň:",
    "city": "Şäher"
};