export default {
    "novapi": "NovaPi",
    "extensionName": "NovaPi",
    "extensionDescription": "",
    "firmwares_version_64e1ab3a": "Dernier firmware",
    "UPDATE_FIRMWARE": "Mise à jour du firmware",
    "settings_cbe1cff9": "régler la position du servo-moteur sur zéro",
    "timer": "Minuterie",
    "timer_reset": "minuterie de réinitialisation",
    "MOTION_SENSOR_ACC_AXIS_0": "axe x",
    "MOTION_SENSOR_ACC_AXIS_1": "axe y",
    "MOTION_SENSOR_ACC_AXIS_2": "axe z",
    "motion_sensor_acc": "capteur de mouvement [AXIS] accélération (m/s ²)",
    "motion_sensor_gyro": "capteur de mouvement [AXIS] Vitesse angulaire (deg/s)",
    "motion_sensor_angle": "capteur de mouvement [AXIS] angle (°)",
    "motion_sensor_set_threshold": "sensibilité du capteur de mouvement [THRESHOLD] %",
    "motion_sensor_check_shake": "détecteur de mouvement détecte un tremblement?",
    "MOTION_SENSOR_RESET_ROTATION_AXIS_0": "z-axe",
    "motion_sensor_reset_rotation": "capteur de mouvement réinitialise l’angle autour [AXIS]",
    "cate_0c16e042": "NovaPi",
    "DRGB_INIT_NUM_0": "1",
    "DRGB_INIT_NUM_1": "2",
    "DRGB_INIT_NUM_2": "3",
    "DRGB_INIT_NUM_3": "4",
    "DRGB_INIT_NUM_4": "5",
    "DRGB_INIT_NUM_5": "6",
    "DRGB_INIT_PORT_0": "port 1",
    "DRGB_INIT_PORT_1": "port 2",
    "DRGB_INIT_PORT_2": "port 3",
    "DRGB_INIT_PORT_3": "port 4",
    "DRGB_INIT_PORT_4": "port5",
    "DRGB_INIT_INDEX_0": "1",
    "DRGB_INIT_INDEX_1": "2",
    "DRGB_INIT_INDEX_2": "3",
    "DRGB_INIT": "initialiser le double capteur RGB [NUM] : à  [PORT] Lla [INDEX] Un",
    "DRGB_SET_SENSOR_KP": "Double capteur RGB [NUM]: Réglez KP dans le calcul de la vitesse différentielle du moteur [KP]",
    "DRGB_SET_SENSOR_COLOR_COLOR_0": "Rouge",
    "DRGB_SET_SENSOR_COLOR_COLOR_1": "Vert",
    "DRGB_SET_SENSOR_COLOR_COLOR_2": "Bleu",
    "DRGB_SET_SENSOR_COLOR": "Double capteur RGB[NUM]: Réglez la lumière de remplissage sur [COLOR]",
    "DRGB_CHECK_COLOR_CHANNEL_0": "RGB1",
    "DRGB_CHECK_COLOR_CHANNEL_1": "RGB2",
    "DRGB_CHECK_COLOR_COLOR_0": "Blanc",
    "DRGB_CHECK_COLOR_COLOR_1": "rouge",
    "DRGB_CHECK_COLOR_COLOR_2": "jaune",
    "DRGB_CHECK_COLOR_COLOR_3": "vert",
    "DRGB_CHECK_COLOR_COLOR_4": "bleu",
    "DRGB_CHECK_COLOR_COLOR_5": "noir",
    "DRGB_CHECK_COLOR": "Double capteur RGB [NUM] Sonde [CHANNEL]  détecte la couleur [COLOR]?",
    "DRGB_SENSOR_STATUS_STATE_0": "00",
    "DRGB_SENSOR_STATUS_STATE_1": "01",
    "DRGB_SENSOR_STATUS_STATE_2": "10",
    "DRGB_SENSOR_STATUS_STATE_3": "11",
    "DRGB_SENSOR_STATUS": "Double capteur RGB [NUM] définir l'état de la sonde sur (RGB2 | RGB1[STATE]?",
    "DRGB_BACKGROUND_DETECTED": "Double capteur RGB [NUM] Sonde [CHANNEL] détecte la couleur d'arrière-plan?",
    "DRGB_GET_INTENSITY": "Capteur RGB double [NUM] sonde [CHANNEL] valeur retournée",
    "DRGB_GET_POSITION_OFFSET": "Double capteur RGB [NUM] décalage de position de ligne (-100 ~ 100)",
    "DRGB_GET_POSITION_OFFSET_KP": "Double capteur RGB[NUM] Vitesse différentielle du moteur (décalage de position de ligne × KP)",
    "cate_0c16e043": "Double capteur RGB",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_0": "DC1",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_1": "DC2",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_2": "DC3",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_3": "DC4",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_4": "DC5",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_5": "DC6",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_6": "DC7",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_7": "DC8",
    "POWER_EXPAND_DCmotor_power": "Moteur DC[CHANNEL] tourne à la puissance [POWER] %",
    "POWER_EXPAND_DCmotor_stop": "Moteur DC [CHANNEL] S' arrête",
    "POWER_EXPAND_BLMOTOR_POWER_CHANNEL_0": "BL1",
    "POWER_EXPAND_BLMOTOR_POWER_CHANNEL_1": "BL2",
    "POWER_EXPAND_BLmotor_power": "moteur brushless[CHANNEL] tourne à la puissance [POWER] %",
    "POWER_EXPAND_BLmotor_stop": "moteur brushless [CHANNEL] S' arrête",
    "POWER_EXPAND_SOLENOIDVALVE_STATUS_0": "mise hors tension",
    "POWER_EXPAND_SOLENOIDVALVE_STATUS_1": "mise sous tension",
    "POWER_EXPAND_solenoidvalve": "électrovanne réglée [CHANNEL] statut à [STATUS]",
    "cate_0c16e044": "Carte d'extension de puissance",
    "ENCODER_MOTOR_POWER_PORT_0": "M1",
    "ENCODER_MOTOR_POWER_PORT_1": "M2",
    "ENCODER_MOTOR_POWER_PORT_2": "M3",
    "ENCODER_MOTOR_POWER_PORT_3": "M4",
    "ENCODER_MOTOR_POWER_PORT_4": "M5",
    "ENCODER_MOTOR_POWER_PORT_5": "M6",
    "encoder_motor_power": "moteur codeur [PORT]  tourne à la puissance [POWER] %",
    "encoder_motor_move": "moteur codeur[PORT] tourne par[POSITION] degré à la vitesse de [SPEED] r/min",
    "encoder_motor_move_to": "moteur codeur [PORT] tourne à [POSITION] degré à la vitesse de [SPEED] r/min",
    "encoder_motor_speed": "moteur codeur [PORT] tourne à la vitesse de [SPEED] r/min",
    "encoder_motor_get_speed": "moteur codeur[PORT] Vitesse de rotation (r/min)",
    "encoder_motor_get_pos": "moteur codeur [PORT] angle (°)",
    "cate_0c16e045": "Moteur de codeur",
    "SMARTSERVO_INIT_NUM_0": "1",
    "SMARTSERVO_INIT_NUM_1": "2",
    "SMARTSERVO_INIT_NUM_2": "3",
    "SMARTSERVO_INIT_NUM_3": "4",
    "SMARTSERVO_INIT_NUM_4": "5",
    "SMARTSERVO_INIT_NUM_5": "6",
    "SMARTSERVO_INIT_NUM_6": "7",
    "SMARTSERVO_INIT_NUM_7": "8",
    "SMARTSERVO_INIT_NUM_8": "9",
    "SMARTSERVO_INIT_NUM_9": "10",
    "SMARTSERVO_INIT_NUM_10": "11",
    "SMARTSERVO_INIT_NUM_11": "12",
    "SMARTSERVO_INIT_INDEX_0": "1",
    "SMARTSERVO_INIT_INDEX_1": "2",
    "SMARTSERVO_INIT_INDEX_2": "3",
    "SMARTSERVO_INIT_INDEX_3": "4",
    "SMARTSERVO_INIT_INDEX_4": "5",
    "SMARTSERVO_INIT_INDEX_5": "6",
    "smartservo_init": "initialiser le servo intelligent[NUM]: à [PORT] Lla [INDEX] Un",
    "smartservo_move": "servo intelligent [NUM] tourne par [POSITION] degré à la vitesse de  [SPEED] r/min",
    "smartservo_move_to": "servo intelligent[NUM] tourne à [POSITION] degré à la vitesse de [SPEED] r/min",
    "smartservo_set_power": "servo intelligent[NUM] tourne à la puissance [POWER] %",
    "SMARTSERVO_POWER_TYPE_0": "actuel",
    "SMARTSERVO_POWER_TYPE_1": "tension",
    "SMARTSERVO_POWER_TYPE_2": "vitesse",
    "SMARTSERVO_POWER_TYPE_3": "angle",
    "SMARTSERVO_POWER_TYPE_4": "température",
    "SMARTSERVO_POWER": "servo intelligent[NUM] actuel[TYPE]",
    "cate_0c16e046": "Servo intelligent",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_0": "1",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_1": "2",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_2": "3",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_3": "4",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_4": "↑",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_5": "↓",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_6": "←",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_7": "→",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_8": "L1",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_9": "L2",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_10": "R1",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_11": "R2",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_12": "+",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_13": "≡",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_14": "L_Thumb",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_15": "R_Thumb",
    "BT_CONTROLLER_BUTTON_PRESSED": "Bouton [BUTTON] de la manette Bluetooth pressé?",
    "BT_CONTROLLER_JOYSTICK_POSITION_0": "LX",
    "BT_CONTROLLER_JOYSTICK_POSITION_1": "LY",
    "BT_CONTROLLER_JOYSTICK_POSITION_2": "RX",
    "BT_CONTROLLER_JOYSTICK_POSITION_3": "RY",
    "BT_CONTROLLER_JOYSTICK": "Joystick[POSITION](-100 ~ 100) de la manette Bluetooth",
    "cate_0c16e047": "Manette Bluetooth",
    "distance_sensor_init": "initialiser le capteur de télémétrie [NUM]: à [PORT] Lla [INDEX] Un",
    "distance_sensor_get_data": "capteur de télémétrie[NUM] distance à l’obstacle (cm)",
    "cate_0c16e048": "Capteur de télémétrie",
    "NovaPi main program setup": "Programme principal de NovaPi",
    "compitition_mode": "La concurrence est en phase automatique?",
    "BLOCK_1555405469500": "",
    "SET_SMART_ZERO_TITLE": "Régler la position du servo-moteur sur zéro",
    "SET_SMART_ZERO_PORT": "Sélectionner le port",
    "SET_SMART_ZERO_NO": "Sélectionner le numéro de série",
    "SET_SMART_ZERO_BTN": "Régler la position actuelle sur zéro",
    "SET_SMART_ZERO_BTN_LOADING": "Réglage de la position sur zéro...",
    "SET_SMART_ZERO_SUCCESS": "Réglage réussi",
    "SET_SMART_ZERO_FAIL": "Échec du réglage"
};