export default {
    "novapi": "NovaPi",
    "extensionName": "NovaPi",
    "extensionDescription": "",
    "firmwares_version_64e1ab3a": "Najnoviji firmware",
    "UPDATE_FIRMWARE": "Firmware ažurirati",
    "settings_cbe1cff9": "Postavljanje pametnog servo nultog položaja",
    "timer": "Timer",
    "timer_reset": "Reset timer",
    "MOTION_SENSOR_ACC_AXIS_0": "x-Axis",
    "MOTION_SENSOR_ACC_AXIS_1": "y-Axis",
    "MOTION_SENSOR_ACC_AXIS_2": "z-Axis",
    "motion_sensor_acc": "senzor kretanja [AXIS] ubrzanje（m/s²）",
    "motion_sensor_gyro": "senzor pokreta [AXIS] Kutna brzina (deg/s)",
    "motion_sensor_angle": "senzor pokreta[AXIS] kut (°)",
    "motion_sensor_set_threshold": "postavite osjetljivost senzora kretanja na [THRESHOLD] %",
    "motion_sensor_check_shake": "senzor pokreta otkriva tresnju?",
    "MOTION_SENSOR_RESET_ROTATION_AXIS_0": "z-OS",
    "motion_sensor_reset_rotation": "senzor pokreta ponovno postavlja kut oko [AXIS]",
    "cate_0c16e042": "NovaPi",
    "DRGB_INIT_NUM_0": "1",
    "DRGB_INIT_NUM_1": "2",
    "DRGB_INIT_NUM_2": "3",
    "DRGB_INIT_NUM_3": "4",
    "DRGB_INIT_NUM_4": "5",
    "DRGB_INIT_NUM_5": "6",
    "DRGB_INIT_PORT_0": "port1",
    "DRGB_INIT_PORT_1": "port2",
    "DRGB_INIT_PORT_2": "port3",
    "DRGB_INIT_PORT_3": "port4",
    "DRGB_INIT_PORT_4": "port5",
    "DRGB_INIT_INDEX_0": "1",
    "DRGB_INIT_INDEX_1": "2",
    "DRGB_INIT_INDEX_2": "3",
    "DRGB_INIT": "inicijalizacija dvostrukog RGB senzora [NUM] : na  [PORT] na [INDEX] Jedan",
    "DRGB_SET_SENSOR_KP": "Dual RGB senzor [NUM]: postavi Kp pomoću izračuna motora diferencijalne brzine na [KP]",
    "DRGB_SET_SENSOR_COLOR_COLOR_0": "Crveni",
    "DRGB_SET_SENSOR_COLOR_COLOR_1": "Zelena",
    "DRGB_SET_SENSOR_COLOR_COLOR_2": "Plava",
    "DRGB_SET_SENSOR_COLOR": "Dual RGB senzor[NUM]: postavi svjetlo ispune [COLOR]",
    "DRGB_CHECK_COLOR_CHANNEL_0": "RGB1",
    "DRGB_CHECK_COLOR_CHANNEL_1": "RGB2",
    "DRGB_CHECK_COLOR_COLOR_0": "Bijeli",
    "DRGB_CHECK_COLOR_COLOR_1": "crvena",
    "DRGB_CHECK_COLOR_COLOR_2": "žuta",
    "DRGB_CHECK_COLOR_COLOR_3": "zelena",
    "DRGB_CHECK_COLOR_COLOR_4": "plava",
    "DRGB_CHECK_COLOR_COLOR_5": "crno",
    "DRGB_CHECK_COLOR": "Dual RGB senzor [NUM] Sonda [CHANNEL]  otkriva boju [COLOR]?",
    "DRGB_SENSOR_STATUS_STATE_0": "00",
    "DRGB_SENSOR_STATUS_STATE_1": "01",
    "DRGB_SENSOR_STATUS_STATE_2": "10",
    "DRGB_SENSOR_STATUS_STATE_3": "11",
    "DRGB_SENSOR_STATUS": "Dual RGB senzor [NUM] zalazak sonda stanje to (RGB2 | RGB1)[STATE]?",
    "DRGB_BACKGROUND_DETECTED": "Dual RGB senzor [NUM] sonda [CHANNEL] otkriva pozadinsku boju?",
    "DRGB_GET_INTENSITY": "Dual RGB senzor [NUM] sonda [CHANNEL] povratna vrijednost",
    "DRGB_GET_POSITION_OFFSET": "Dual RGB senzor [NUM] položaj linije (-100 ~ 100)",
    "DRGB_GET_POSITION_OFFSET_KP": "Dual RGB senzor[NUM] motorna diferencijalna brzina (pozicija linije × KP)",
    "cate_0c16e043": "Dual RGB senzor",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_0": "DC1",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_1": "DC2",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_2": "DC3",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_3": "DC4",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_4": "DC5",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_5": "DC6",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_6": "DC7",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_7": "DC8",
    "POWER_EXPAND_DCmotor_power": "DC Motor[CHANNEL]] vrti na snazi [POWER]%",
    "POWER_EXPAND_DCmotor_stop": "DC motor [CHANNEL] staje",
    "POWER_EXPAND_BLMOTOR_POWER_CHANNEL_0": "BL1",
    "POWER_EXPAND_BLMOTOR_POWER_CHANNEL_1": "BL2",
    "POWER_EXPAND_BLmotor_power": "motor bez četkica[CHANNEL] vrtina snazi [POWER] %",
    "POWER_EXPAND_BLmotor_stop": "motor bez četkica [CHANNEL] staje",
    "POWER_EXPAND_SOLENOIDVALVE_STATUS_0": "isključi",
    "POWER_EXPAND_SOLENOIDVALVE_STATUS_1": "uključi",
    "POWER_EXPAND_solenoidvalve": "postavite solenoidni ventil [CHANNEL] status u [STATUS]",
    "cate_0c16e044": "Pločica za proširenje snage",
    "ENCODER_MOTOR_POWER_PORT_0": "М1",
    "ENCODER_MOTOR_POWER_PORT_1": "M2",
    "ENCODER_MOTOR_POWER_PORT_2": "M3",
    "ENCODER_MOTOR_POWER_PORT_3": "M4",
    "ENCODER_MOTOR_POWER_PORT_4": "M5",
    "ENCODER_MOTOR_POWER_PORT_5": "M6",
    "encoder_motor_power": "koder motor [PORT]  rotira na snazi [POWER] %",
    "encoder_motor_move": "enkoderski motor[PORT] vrti se po[POSITION] stupnjeva na brzini od [SPEED] r/min",
    "encoder_motor_move_to": "enkoderski motor[PORT] rotira za [POSITION] stupanj na brzini od [SPEED] r/min",
    "encoder_motor_speed": "enkoderski motor [PORT] vrti se na brzini od [SPEED] r/min",
    "encoder_motor_get_speed": "enkoderski motor[PORT] brzina rotacije (r/min)",
    "encoder_motor_get_pos": "enkoderski motor [PORT] kut (°)",
    "cate_0c16e045": "Enkoderski motor",
    "SMARTSERVO_INIT_NUM_0": "1",
    "SMARTSERVO_INIT_NUM_1": "2",
    "SMARTSERVO_INIT_NUM_2": "3",
    "SMARTSERVO_INIT_NUM_3": "4",
    "SMARTSERVO_INIT_NUM_4": "5",
    "SMARTSERVO_INIT_NUM_5": "6",
    "SMARTSERVO_INIT_NUM_6": "7",
    "SMARTSERVO_INIT_NUM_7": "8",
    "SMARTSERVO_INIT_NUM_8": "9",
    "SMARTSERVO_INIT_NUM_9": "10",
    "SMARTSERVO_INIT_NUM_10": "11",
    "SMARTSERVO_INIT_NUM_11": "12",
    "SMARTSERVO_INIT_INDEX_0": "1",
    "SMARTSERVO_INIT_INDEX_1": "2",
    "SMARTSERVO_INIT_INDEX_2": "3",
    "SMARTSERVO_INIT_INDEX_3": "4",
    "SMARTSERVO_INIT_INDEX_4": "5",
    "SMARTSERVO_INIT_INDEX_5": "6",
    "smartservo_init": "inicijalizacija pametnog serva [NUM]: na [PORT] na [INDEX] jedan",
    "smartservo_move": "pametni servo [NUM] vrti se na [POSITION] stupnjeva brzinom od [SPEED] r/min",
    "smartservo_move_to": "pametni servo[NUM] vrti se na [POSITION] stpnjeva na brzini od [SPEED] r/min",
    "smartservo_set_power": "pametni servo[NUM] vrti se na brzini [POWER]%",
    "SMARTSERVO_POWER_TYPE_0": "struja",
    "SMARTSERVO_POWER_TYPE_1": "voltaža",
    "SMARTSERVO_POWER_TYPE_2": "brzina",
    "SMARTSERVO_POWER_TYPE_3": "kut",
    "SMARTSERVO_POWER_TYPE_4": "temperatura",
    "SMARTSERVO_POWER": "pametni servo[NUM] trenutni[TYPE]",
    "cate_0c16e046": "Pametni Servo",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_0": "1",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_1": "2",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_2": "3",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_3": "4",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_4": "↑",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_5": "↓",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_6": "←",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_7": "→",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_8": "L1",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_9": "L2",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_10": "R1",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_11": "R2",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_12": "+",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_13": "≡",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_14": "L_Thumb",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_15": "R_Thumb",
    "BT_CONTROLLER_BUTTON_PRESSED": "Gumb Bluetooth kontroler [BUTTON] Pritisne?",
    "BT_CONTROLLER_JOYSTICK_POSITION_0": "LX",
    "BT_CONTROLLER_JOYSTICK_POSITION_1": "LY",
    "BT_CONTROLLER_JOYSTICK_POSITION_2": "RX",
    "BT_CONTROLLER_JOYSTICK_POSITION_3": "RY",
    "BT_CONTROLLER_JOYSTICK": "Bluetooth kontroler joystick[POSITION])(-100 ~ 100)",
    "cate_0c16e047": "Bluetooth kontroler",
    "distance_sensor_init": "inicijaliziraj senzor raspona [NUM]: na [PORT] na [INDEX] jedan",
    "distance_sensor_get_data": "senzoraspona[NUM] udaljenost(cm)",
    "cate_0c16e048": "Senzor raspona",
    "NovaPi main program setup": "NovaPi glavni program",
    "compitition_mode": "Konkurencija je u automatskoj fazi?",
    "BLOCK_1555405469500": "",
    "SET_SMART_ZERO_TITLE": "Postavite Smart servo nultu poziciju",
    "SET_SMART_ZERO_PORT": "Odaberite priključak",
    "SET_SMART_ZERO_NO": "Odaberite serijski broj",
    "SET_SMART_ZERO_BTN": "Postavljanje trenutnog položaja kao nulte pozicije",
    "SET_SMART_ZERO_BTN_LOADING": "Postavljanje nultog položaja...",
    "SET_SMART_ZERO_SUCCESS": "Postavljanje uspješnog",
    "SET_SMART_ZERO_FAIL": "Postavka nije uspjela"
};