export default {
    "novapi": "NovaPi",
    "extensionName": "NovaPi",
    "extensionDescription": "",
    "firmwares_version_64e1ab3a": "Najnowsze firmware",
    "UPDATE_FIRMWARE": "Aktualizacja oprogramowania sprzętowego",
    "settings_cbe1cff9": "Ustaw inteligentne ustawienie serwa zerowego",
    "timer": "Timer",
    "timer_reset": "Zerowanie timera",
    "MOTION_SENSOR_ACC_AXIS_0": "x-axis",
    "MOTION_SENSOR_ACC_AXIS_1": "y-axis",
    "MOTION_SENSOR_ACC_AXIS_2": "z-axis",
    "motion_sensor_acc": "Czujnik ruchu [AXIS] przyspieszenie (m/s ²)",
    "motion_sensor_gyro": "Czujnik ruchu [AXIS] prędkość kątowa (stopni/s)",
    "motion_sensor_angle": "Czujnik ruchu [AXIS] kąt (°)",
    "motion_sensor_set_threshold": "Ustaw czułość czujnika ruchu na [THRESHOLD] %",
    "motion_sensor_check_shake": "Czujnik ruchu wykrywa drgania?",
    "MOTION_SENSOR_RESET_ROTATION_AXIS_0": "Osi",
    "motion_sensor_reset_rotation": "czujnik ruchu resetuje kąt wokół [AXIS]",
    "cate_0c16e042": "NovaPi",
    "DRGB_INIT_NUM_0": "1",
    "DRGB_INIT_NUM_1": "2",
    "DRGB_INIT_NUM_2": "3",
    "DRGB_INIT_NUM_3": "4",
    "DRGB_INIT_NUM_4": "5",
    "DRGB_INIT_NUM_5": "6",
    "DRGB_INIT_PORT_0": "port1",
    "DRGB_INIT_PORT_1": "port2",
    "DRGB_INIT_PORT_2": "port3",
    "DRGB_INIT_PORT_3": "port4",
    "DRGB_INIT_PORT_4": "port5",
    "DRGB_INIT_INDEX_0": "1",
    "DRGB_INIT_INDEX_1": "2",
    "DRGB_INIT_INDEX_2": "3",
    "DRGB_INIT": "Inicjowanie podwójnego czujnika RGB [NUM] : at  [PORT] Tthe [INDEX] Jeden",
    "DRGB_SET_SENSOR_KP": "Podwójny czujnik RGB [NUM]: Ustaw KP przy obliczaniu różnicy prędkości silnika, aby [KP]",
    "DRGB_SET_SENSOR_COLOR_COLOR_0": "Czerwony",
    "DRGB_SET_SENSOR_COLOR_COLOR_1": "Zielony",
    "DRGB_SET_SENSOR_COLOR_COLOR_2": "Niebieski",
    "DRGB_SET_SENSOR_COLOR": "Podwójny czujnik RGB[NUM]: Ustaw światło wypełnienia na [COLOR]",
    "DRGB_CHECK_COLOR_CHANNEL_0": "RGB1",
    "DRGB_CHECK_COLOR_CHANNEL_1": "RGB2",
    "DRGB_CHECK_COLOR_COLOR_0": "Biały",
    "DRGB_CHECK_COLOR_COLOR_1": "czerwony",
    "DRGB_CHECK_COLOR_COLOR_2": "żółty",
    "DRGB_CHECK_COLOR_COLOR_3": "zielony",
    "DRGB_CHECK_COLOR_COLOR_4": "niebieski",
    "DRGB_CHECK_COLOR_COLOR_5": "czarne",
    "DRGB_CHECK_COLOR": "Podwójny czujnik RGB [NUM] Sondy [CHANNEL]  wykrywa kolor [COLOR]?",
    "DRGB_SENSOR_STATUS_STATE_0": "00",
    "DRGB_SENSOR_STATUS_STATE_1": "01",
    "DRGB_SENSOR_STATUS_STATE_2": "10",
    "DRGB_SENSOR_STATUS_STATE_3": "11",
    "DRGB_SENSOR_STATUS": "Podwójny czujnik RGB [NUM] Ustaw stan sondy na (RGB2 | RGB1)[STATE]?",
    "DRGB_BACKGROUND_DETECTED": "Podwójny czujnik RGB [NUM] Sondy [CHANNEL] wykrywa kolor tła?",
    "DRGB_GET_INTENSITY": "Podwójny czujnik RGB [NUM] Sondy [CHANNEL] wartość zwracana",
    "DRGB_GET_POSITION_OFFSET": "Podwójny czujnik RGB [NUM] przesunięcie pozycji linii (-100 ~ 100)",
    "DRGB_GET_POSITION_OFFSET_KP": "Podwójny czujnik RGB[NUM] prędkość różnicowa silnika (przesunięcie pozycji linii × KP)",
    "cate_0c16e043": "Podwójny czujnik RGB",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_0": "DC1",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_1": "DC2",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_2": "DC3",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_3": "DC4",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_4": "DC5",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_5": "DC6",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_6": "DC7",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_7": "DC8",
    "POWER_EXPAND_DCmotor_power": "Silnik prądu stałego[CHANNEL] obraca się przy zasilaniu [POWER] %",
    "POWER_EXPAND_DCmotor_stop": "Silnik prądu stałego [CHANNEL] Zatrzymuje",
    "POWER_EXPAND_BLMOTOR_POWER_CHANNEL_0": "BL1",
    "POWER_EXPAND_BLMOTOR_POWER_CHANNEL_1": "BL2",
    "POWER_EXPAND_BLmotor_power": "silnik bezszczotkowy[CHANNEL] obraca się przy zasilaniu [POWER] %",
    "POWER_EXPAND_BLmotor_stop": "silnik bezszczotkowy [CHANNEL] Zatrzymuje",
    "POWER_EXPAND_SOLENOIDVALVE_STATUS_0": "wyłączenie zasilania",
    "POWER_EXPAND_SOLENOIDVALVE_STATUS_1": "Włącz",
    "POWER_EXPAND_solenoidvalve": "Ustaw zawór elektromagnetyczny [CHANNEL] stan, aby [STATUS]",
    "cate_0c16e044": "Płyta rozszerzeń zasilania",
    "ENCODER_MOTOR_POWER_PORT_0": "M1",
    "ENCODER_MOTOR_POWER_PORT_1": "M2",
    "ENCODER_MOTOR_POWER_PORT_2": "M3",
    "ENCODER_MOTOR_POWER_PORT_3": "M4",
    "ENCODER_MOTOR_POWER_PORT_4": "M5",
    "ENCODER_MOTOR_POWER_PORT_5": "M6",
    "encoder_motor_power": "silnik enkodera[PORT]  obraca się z mocą [POWER]%",
    "encoder_motor_move": "silnik enkodera[PORT] obraca się o[POSITION] stopień z prędkością [SPEED] obr/min",
    "encoder_motor_move_to": "silnik enkodera [PORT] obraca się do [POSITION] stopień z prędkością [SPEED] obr/min",
    "encoder_motor_speed": "silnik enkodera [PORT] obraca się z prędkością [SPEED] obr/min",
    "encoder_motor_get_speed": "silnik enkodera[PORT] prędkość obrotowa (obr/min)",
    "encoder_motor_get_pos": "silnik enkodera [PORT] kąt (°)",
    "cate_0c16e045": "Silnik enkodera",
    "SMARTSERVO_INIT_NUM_0": "1",
    "SMARTSERVO_INIT_NUM_1": "2",
    "SMARTSERVO_INIT_NUM_2": "3",
    "SMARTSERVO_INIT_NUM_3": "4",
    "SMARTSERVO_INIT_NUM_4": "5",
    "SMARTSERVO_INIT_NUM_5": "6",
    "SMARTSERVO_INIT_NUM_6": "7",
    "SMARTSERVO_INIT_NUM_7": "8",
    "SMARTSERVO_INIT_NUM_8": "9",
    "SMARTSERVO_INIT_NUM_9": "10",
    "SMARTSERVO_INIT_NUM_10": "11",
    "SMARTSERVO_INIT_NUM_11": "12",
    "SMARTSERVO_INIT_INDEX_0": "1",
    "SMARTSERVO_INIT_INDEX_1": "2",
    "SMARTSERVO_INIT_INDEX_2": "3",
    "SMARTSERVO_INIT_INDEX_3": "4",
    "SMARTSERVO_INIT_INDEX_4": "5",
    "SMARTSERVO_INIT_INDEX_5": "6",
    "smartservo_init": "Inicjowanie inteligentnego serwa[NUM]: at [PORT] Tthe [INDEX] Jeden",
    "smartservo_move": "inteligentny serw [NUM] obraca się o [POSITION] stopień z prędkością  [SPEED] obr/min",
    "smartservo_move_to": "inteligentny serw[NUM] obraca się do [POSITION] stopień z prędkością [SPEED] obr/min",
    "smartservo_set_power": "inteligentny serw[NUM] obraca się przy zasilaniu [POWER] %",
    "SMARTSERVO_POWER_TYPE_0": "prąd",
    "SMARTSERVO_POWER_TYPE_1": "napięcie",
    "SMARTSERVO_POWER_TYPE_2": "prędkość",
    "SMARTSERVO_POWER_TYPE_3": "kąt",
    "SMARTSERVO_POWER_TYPE_4": "temperatura",
    "SMARTSERVO_POWER": "inteligentny serw[NUM] bieżących[TYPE]",
    "cate_0c16e046": "Inteligentny serw",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_0": "1",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_1": "2",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_2": "3",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_3": "4",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_4": "↑",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_5": "↓",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_6": "←",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_7": "→",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_8": "L1",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_9": "L2",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_10": "R1",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_11": "R2",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_12": "+",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_13": "≡",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_14": "L_Thumb",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_15": "R_Thumb",
    "BT_CONTROLLER_BUTTON_PRESSED": "Przycisk kontrolera Bluetooth [BUTTON] Wciśnięty?",
    "BT_CONTROLLER_JOYSTICK_POSITION_0": "LX",
    "BT_CONTROLLER_JOYSTICK_POSITION_1": "LY",
    "BT_CONTROLLER_JOYSTICK_POSITION_2": "RX",
    "BT_CONTROLLER_JOYSTICK_POSITION_3": "Ry",
    "BT_CONTROLLER_JOYSTICK": "Joystick kontrolera Bluetooth[POSITION](-100 ~ 100)",
    "cate_0c16e047": "Kontroler Bluetooth",
    "distance_sensor_init": "Inicjowanie czujnika zakresu [NUM]: at [PORT] Tthe [INDEX] Jeden",
    "distance_sensor_get_data": "zakres czujnika[NUM] Odległość do przeszkody (cm)",
    "cate_0c16e048": "Czujnik zakresu",
    "NovaPi main program setup": "Główny program NovaPi",
    "compitition_mode": "Konkurs jest w fazie automatycznej?",
    "BLOCK_1555405469500": "",
    "SET_SMART_ZERO_TITLE": "Ustaw inteligentne położenie serwa zerowego",
    "SET_SMART_ZERO_PORT": "Wybierz port",
    "SET_SMART_ZERO_NO": "Numer seryjny produktu",
    "SET_SMART_ZERO_BTN": "Ustaw aktualną pozycję jako pozycję zerową",
    "SET_SMART_ZERO_BTN_LOADING": "Ustawienie pozycji zerowej...",
    "SET_SMART_ZERO_SUCCESS": "Ustawianie udanych",
    "SET_SMART_ZERO_FAIL": "Ustawienie nie powiodło się"
};