export default {
    "device_data_chart": "Tietokartta",
    "extensionName": "Tietokartta",
    "extensionDescription": "Käytä tätä laajennusta visualisoimaan tietojasi. Kaavio kertoo enemmän kuin pitkät lauseet.",
    "open_chart": "avaa Datakaavio-ikkuna",
    "set_chart_name": "aseta kaavion otsikko [data]",
    "SET_CHART_TYPE_TYPE_0": "pöytä",
    "SET_CHART_TYPE_TYPE_1": "viivakaavio",
    "SET_CHART_TYPE_TYPE_2": "pylväskaavio",
    "SET_CHART_TYPE_TYPE_3": "dual axis chart",
    "SET_CHART_TYPE_TYPE_4": "pie chart",
    "set_chart_type": "Määritä kaavio tyypiksi [type]",
    "BLOCK_1586773178961_RATE_0": "no latency",
    "BLOCK_1586773178961_RATE_1": "fast",
    "BLOCK_1586773178961_RATE_2": "slow",
    "BLOCK_1586773178961": "set rendering rate to [rate]",
    "set_axis_name": "Aseta akselin nimi: x [xName]  Y [yName]",
    "BLOCK_1586773463661": "name y-axis on the right:[rightYAxisTitle]",
    "BLOCK_1586773584919_YAXISDIRECTION_0": "y-axis on the left",
    "BLOCK_1586773584919_YAXISDIRECTION_1": "y-axis on the right",
    "BLOCK_1586773584919": "set data group [seriesName]to [yAxisDirection]",
    "set_data_handler": "syöttö tiedot [type]: x [xData]  Y [yData]",
    "set_data_handler_1": "input data to [type]: item [xData] value [yData]",
    "clear_chart": "tyhjennä tiedot",
    "close_chart": "sulje Datakaavio-ikkuna",
    "cate_13c26abc": "Tietokartta",
    "DWONLOAD": "lataa",
    "REATCH_MAX_XAXIS_DATA": "Tietosyöttö ylittää jo rajan [0], joten syöttö on pysähtynyt.",
    "REATCH_MAX_LENGEND": "Luomasi legendat ylittävät rajan [0], joten et voi lisätä lisää",
    "TABLE_LABEL": "Data Table",
    "CHART_LABEL": "Data Chart",
    "EXPORT_FILE": "Export",
    "IMPORT_FILE": "Import",
    "IMPORT_FILE_SUCCEED": "import successful",
    "IMPORT_FILE_OVERSIZE_ERROR": "import file not larger than[0]m",
    "IMPORT_FILE_FORMAT_ERROR": "only .csv format files supported for import",
    "IMPORT_FILE_FAILED": "Export failed. Please try again.",
    "EMPTY_DATA_LABEL": "Empty data",
    "BIAX_CHART_TIPS_1": "To present a dual axis chart, the following conditions must be met:",
    "BIAX_CHART_TIPS_2": "1. At least 2 groups of data",
    "BIAX_CHART_TIPS_3": "2. y-axis on the right is named using the coding block",
    "BIAX_CHART_TIPS_4": "3. Use coding blocks to define what data is displayed on the left y-axis and right y-axis",
    "PIE_CHART_TIPS": "Pie charts only support no more than 2 groups of data displayed.",
    "DATA_SET_MAX_NUM": "Data groups already exceeds the limit [0], so the input has stopped.",
    "SINGLE_DATA_SET_ITEM_MAX_NUM": "Data volume in one single group already exceeds the limit [0], so the input has stopped.",
    "ALL_DATA_SET_ITEM_MAX_NUM": "Data already exceeds the limit [0], so the input has stopped.",
    "data_chart": "Tietokartta"
};