export default {
    "mcore_variety_gizmos": "Pack gadgets",
    "extensionName": "Pack gadgets",
    "extensionDescription": "Dans les 6 projets d'extension ranger mbot, vous apprendrez comment faire bouger ou modifier la forme de votre robot comme vous le souhaitez. ",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_0": "port 1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_1": "port 2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_2": "port 3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_3": "port 4",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "tout",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] La LED RGB [PORT] [LED_POSTION] s'allume en couleur [COLOR] pendant [TIME] s",
    "mcore_show_external_led": "[ICON] La LED RGB [PORT] [LED_POSTION] s'allume en couleur [COLOR] ",
    "mcore_show_external_led_rgb": "[ICON] La LED RGB [PORT] [LED_POSTION] s'allume avec couleur rouge [R] vert [G] bleu [B]",
    "MCORE_RUN_SERVO_SLOT_0": "emplacement1",
    "MCORE_RUN_SERVO_SLOT_1": "emplacement2",
    "mcore_run_servo": "[ICON] servo[PORT] [SLOT] positionné à un angle de [DEGREE] ",
    "mcore_show_7segments_number": "[ICON] [PORT] 7 segments affiche le nombre [NUMBER]",
    "mcore_event_limit_switch": "[ICON] l'interrupteur de fin de course [PORT] [SLOT] est-il enfoncé？",
    "CATEGORY_VARITY": "Gadgets "
};