export default {
    "mcore_variety_gizmos": "Pacchetto Gadgets",
    "extensionName": "Pacchetto Gadgets",
    "extensionDescription": "Nei 6 progetti di estensione mBot, imparerai come far muovere il tuo robot o dispositivo e a cambiarne a piacere la forma. ",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_0": "port1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_1": "port2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_2": "port3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_3": "port4",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "tutti",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] LED RGB [PORT] accendi [LED_POSTION] luce con colore [COLOR] per [TIME] secs",
    "mcore_show_external_led": "[ICON] LED RGB [PORT] accesi [LED_POSTION] con colore [COLOR] ",
    "mcore_show_external_led_rgb": "[ICON] LED RGB [PORT] accesi [LED_POSTION] con colore rosso [R] verde[G] blu [B]",
    "MCORE_RUN_SERVO_SLOT_0": "slot1",
    "MCORE_RUN_SERVO_SLOT_1": "slot2",
    "mcore_run_servo": "[ICON] servo [PORT] [SLOT] posizionato a [DEGREE] gradi ",
    "mcore_show_7segments_number": "[ICON] il display a sette segmenti [PORT] mostra il numero [NUMBER]",
    "mcore_event_limit_switch": "[ICON] limit switch [PORT] [SLOT] is pressed？",
    "CATEGORY_VARITY": "Gadget "
};