export default {
    "mcore_variety_gizmos": "ガジェットパック",
    "extensionName": "ガジェットパック",
    "extensionDescription": "6のmBotかくちょうプロジェクトでは、あなたのロボットやデバイスをいどうさせるほうほうや、おもいどおりにかたちをへんこうさせることについてまなべます。 ",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_0": "ポート1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_1": "ポート2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_2": "ポート3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_3": "ポート4",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "すべて",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON]RGB LED [PORT]の[LED_POSTION] に[COLOR] いろで[TIME] びょうてんとうする",
    "mcore_show_external_led": "[ICON]RGB LED [PORT] の[LED_POSTION] に[COLOR] いろでてんとうする ",
    "mcore_show_external_led_rgb": "[ICON]RGB LED [PORT] の[LED_POSTION] にあか [R] みどり[G] あお [B] で てんとうする",
    "MCORE_RUN_SERVO_SLOT_0": "スロット1",
    "MCORE_RUN_SERVO_SLOT_1": "スロット2",
    "mcore_run_servo": "[ICON] サーボ[PORT] の[SLOT] のかくどを[DEGREE] にする ",
    "mcore_show_7segments_number": "[ICON] 7セグメントディスプレイ [PORT] にすうじ [NUMBER] をひょうじする",
    "mcore_event_limit_switch": "[ICON] リミットスイッチ[PORT][SLOT] がおされたか？",
    "CATEGORY_VARITY": "ガジェット"
};