export default {
    "mcore_variety_gizmos": "Gadgetspak",
    "extensionName": "Gadgetspak",
    "extensionDescription": "In de 6 mBot extensieprojecten zul je leren hoe je je robot of apparaat kunt laten bewegen en zijn vorm veranderen zoals je wilt. ",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_0": "poort1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_1": "poort2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_2": "poort3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_3": "poort4",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "alle",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] RGB LED [PORT]licht aan [LED_POSTION]met kleur[COLOR] voor [TIME] sec",
    "mcore_show_external_led": "[ICON] RGB LED [PORT]licht aan [LED_POSTION]met kleur[COLOR] ",
    "mcore_show_external_led_rgb": "[ICON] RGB LED [PORT]licht aan [LED_POSTION]met kleur rood [R] groen [G] blauw [B]",
    "MCORE_RUN_SERVO_SLOT_0": "slot1",
    "MCORE_RUN_SERVO_SLOT_1": "slot2",
    "mcore_run_servo": "[ICON] servo [PORT][SLOT] gepositioneerd op [DEGREE] ",
    "mcore_show_7segments_number": "[ICON] zeven segment[PORT] toon nummer [NUMBER]",
    "mcore_event_limit_switch": "[ICON] limietschakelaar [PORT][SLOT] is ingedrukt？",
    "CATEGORY_VARITY": "Gadgets "
};