export default {
    "mcore_variety_gizmos": "擴充包",
    "extensionName": "擴充包",
    "extensionDescription": "在這 6個 mBot 擴充專案中, 你會學到如何使你的機器人移動，並隨你喜歡地改變形狀。 ",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_0": "連接埠1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_1": "連接埠2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_2": "連接埠3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_PORT_3": "連接埠4",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "全部",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] LED 燈 [PORT] 位置 [LED_POSTION] 的顏色設為 [COLOR]，持續 [TIME] 秒",
    "mcore_show_external_led": "[ICON] LED 燈 [PORT] 位置 [LED_POSTION] 的顏色設為 [COLOR] ",
    "mcore_show_external_led_rgb": "[ICON] LED 燈 [PORT] 位置 [LED_POSTION] 的三原色設為 紅[R] 綠[G] 藍[B]",
    "MCORE_RUN_SERVO_SLOT_0": "插座1",
    "MCORE_RUN_SERVO_SLOT_1": "插座2",
    "mcore_run_servo": "[ICON] 伺服馬達 [PORT] [SLOT] 定位在 [DEGREE] 度 ",
    "mcore_show_7segments_number": "[ICON] 數字板 [PORT] 顯示數字 [NUMBER]",
    "mcore_event_limit_switch": "[ICON] 極限開關 [PORT] [SLOT] 被按壓？",
    "CATEGORY_VARITY": "百變小發明 "
};