export default {
    "cyberpi_mbuild_ultrasonic2": "مستشعر فوق صوتي 2",
    "extensionName": "مستشعر فوق صوتي 2",
    "extensionDescription": "",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_0": "1",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_1": "2",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_2": "3",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_3": "4",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_4": "5",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_5": "6",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_6": "7",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_7": "8",
    "mbuild_ultrasonic2_get_distance": " جهاز الاستشعار فوق الصوتي 2 [index] مسافة الكائن (م)",
    "mbuild_ultrasonic2_out_of_range": "[index] مستشعر فوق صوتي 2 خارج النطاق",
    "mbuild_ultrasonic2_show_with_facepanel": "عرض [inputMenu_1] فوق صوتي 2 [inputMenu_1] [facePanel_1] [facePanel_2]",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_0": "الكل",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_1": "1",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_2": "2",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_3": "3",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_4": "4",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_5": "5",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_6": "6",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_7": "7",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_8": "8",
    "mbuild_ultrasonic2_set_bri": "جهاز الاستشعار فوق الصوتي 2 [index]  يعين الضوء المحيط [order] السطوع[bv]%",
    "mbuild_ultrasonic2_add_bri": "جهاز الاستشعار فوق الصوتي 2 [index] يزيد من السطوع المحيط [order] بنسبة [bv]%",
    "mbuild_ultrasonic2_get_bri": "جهاز الاستشعار فوق الصوتي 2 [index] ضوء المحيط [order] سطوع",
    "mbuild_ultrasonic2_off_led": "جهاز الاستشعار فوق الصوتي 2 [index] يوقف الضوء المحيط [inputMenu_3]",
    "mbuild_ultrasonic2_show_one_by_one": "مستشعر فوق صوتي جديد [index] ضوء محيط مع [bv1] [bv2] [bv3] [bv4] [bv5] [bv6] [bv7] [bv8] شاشة السطوع",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_0": "standby",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_1": "happy",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_2": "dizzy",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_3": "raise eyebrows",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_4": "think",
    "mbuild_ultrasonic2_show_emotion": "ultrasonic 2 [index] displays emotion [emotion]",
    "cate_d58a1c87": "مستشعر بالموجات فوق الصوتية",
    "BLOCK_1547779213407": "سيرفو [ID] تعيين زاوية إلى [angle] (°)",
    "BLOCK_1547779701469": "المتكلم [ID]  تشغيل الصوت [audio]",
    "BLOCK_1547779887637": "المتكلم [ID]  تشغيل الصوت المخصص [audio] حتى يتم",
    "BLOCK_1547781171854": "المتكلم [ID]  تعيين وحدة التخزين إلى [volume] %",
    "BLOCK_1552140890585": "مستشعر بالموجات فوق الصوتية [index] المسافة إلى كائن (سم)",
    "BLOCK_1552140919772": "مستشعر بالموجات فوق الصوتية[index] خارج مدى المسافة؟"
};