export default {
    "cyberpi_mbuild_ultrasonic2": "超音波センサー2",
    "extensionName": "超音波センサー2",
    "extensionDescription": "",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_0": "1",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_1": "2",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_2": "3",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_3": "4",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_4": "5",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_5": "6",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_6": "7",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_7": "8",
    "mbuild_ultrasonic2_get_distance": " 超音波センサー2 [index] がオブジェクトまでの距離 (cm) を検出する",
    "mbuild_ultrasonic2_out_of_range": "超音波センサー2 [index] が範囲外",
    "mbuild_ultrasonic2_show_with_facepanel": "超音波2 [inputMenu_1] に感情 [facePanel_1] [facePanel_2] を表示する",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_0": "全て",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_1": "1",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_2": "2",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_3": "3",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_4": "4",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_5": "5",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_6": "6",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_7": "7",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_8": "8",
    "mbuild_ultrasonic2_set_bri": "超音波センサー2 [index] の周囲光 [order] の明るさを[bv] %にする",
    "mbuild_ultrasonic2_add_bri": "超音波センサー2 [index] の周囲光 [order] の明るさを[bv] %ずつ増やす",
    "mbuild_ultrasonic2_get_bri": "超音波センサー2 [index] の周囲光 [order] の明るさ",
    "mbuild_ultrasonic2_off_led": "超音波センサー 2 [index] の周囲光 [inputMenu_3] をオフにする",
    "mbuild_ultrasonic2_show_one_by_one": "新超声波传感器 [index]   氛围灯以 [bv1] [bv2] [bv3] [bv4] [bv5] [bv6] [bv7] [bv8] 亮度显示",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_0": "standby",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_1": "happy",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_2": "dizzy",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_3": "raise eyebrows",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_4": "think",
    "mbuild_ultrasonic2_show_emotion": "ultrasonic 2 [index] displays emotion [emotion]",
    "cate_d58a1c87": "超音波センサー",
    "BLOCK_1547779213407": "サーボ [ID] を角度 [angle] (°) に設定する",
    "BLOCK_1547779701469": "スピーカー [ID] で[audio] を再生する",
    "BLOCK_1547779887637": "スピーカー [ID] でカスタムオーディオ [audio] を完了まで再生する",
    "BLOCK_1547781171854": "スピーカー [ID] の音量を [volume] %に設定する",
    "BLOCK_1552140890585": "超音波センサー[index] がオブジェクトまでの距離 (cm) を検出する",
    "BLOCK_1552140919772": "超音波センサー[index] の距離範囲外"
};