export default {
    "cyberpi_mbuild_ultrasonic2": "Ультразвуковий датчик 2",
    "extensionName": "Ультразвуковий датчик 2",
    "extensionDescription": "",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_0": "1",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_1": "2",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_2": "3",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_3": "4",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_4": "5",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_5": "6",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_6": "7",
    "MBUILD_ULTRASONIC2_GET_DISTANCE_INDEX_7": "8",
    "mbuild_ultrasonic2_get_distance": " ультразвуковий датчик 2 [index] відстань до об'єкта (см)",
    "mbuild_ultrasonic2_out_of_range": "ультразвуковий датчик 2 [index] поза діапазоном?",
    "mbuild_ultrasonic2_show_with_facepanel": "ультразвуковий датчик 2 [inputMenu_1] вивести [facePanel_1][facePanel_2]",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_0": "всі",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_1": "1",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_2": "2",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_3": "3",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_4": "4",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_5": "5",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_6": "6",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_7": "7",
    "MBUILD_ULTRASONIC2_SET_BRI_ORDER_8": "8",
    "mbuild_ultrasonic2_set_bri": "ультразвуковий датчик 2 [index]  встановити підсвітку [order] яскравість [bv]%",
    "mbuild_ultrasonic2_add_bri": "ультразвуковий датчик 2 [index] збільшити яскравість підсвітки [order] на [bv]%",
    "mbuild_ultrasonic2_get_bri": "ультразвуковий датчик 2 [index] яскравість підсвітки [order]",
    "mbuild_ultrasonic2_off_led": "ультразвуковий датчик 2 [index] вимкнути підсвітку [inputMenu_3]",
    "mbuild_ultrasonic2_show_one_by_one": "ультразвуковий датчик 2 [index] підсвітка [bv1] [bv2] [bv3] [bv4] [bv5] [bv6] [bv7] [bv8] яскравість",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_0": "standby",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_1": "happy",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_2": "dizzy",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_3": "raise eyebrows",
    "MBUILD_ULTRASONIC2_SHOW_EMOTION_EMOTION_4": "think",
    "mbuild_ultrasonic2_show_emotion": "ultrasonic 2 [index] displays emotion [emotion]",
    "cate_d58a1c87": "Ультразвуковий датчик",
    "BLOCK_1547779213407": "серво [ID] задати кут [angle] (°)",
    "BLOCK_1547779701469": "динамік [ID] відтворювати звук [audio]",
    "BLOCK_1547779887637": "динамік [ID] відтворювати унікальний файл [audio] до кінця",
    "BLOCK_1547781171854": "динамік [ID] встановити гучність на [volume] %",
    "BLOCK_1552140890585": "ультразвуковий датчик [index] відстань до об'єкта (см)",
    "BLOCK_1552140919772": "ультразвуковий датчик [index] поза доступним діапазоном відстані?"
};