export default {
    "mbot2": "mBot2 拡張ボード",
    "extensionName": "mBot2 拡張ボード",
    "extensionDescription": "",
    "MBOT2_MOVE_DIRECTION_WITH_TIME_DIRECTION_0": "前進する",
    "MBOT2_MOVE_DIRECTION_WITH_TIME_DIRECTION_1": "後退する",
    "MBOT2_MOVE_DIRECTION_WITH_TIME_DIRECTION_2": "左折する",
    "MBOT2_MOVE_DIRECTION_WITH_TIME_DIRECTION_3": "右折する",
    "mbot2_move_direction_with_time": "[POWER] RPMで [TIME] 秒[DIRECTION]",
    "mbot2_move_direction_with_rpm": "[POWER] RPMで [DIRECTION]",
    "MBOT2_MOVE_STRAIGHT_WITH_CM_AND_INCH_DIRECTION_0": "前進する",
    "MBOT2_MOVE_STRAIGHT_WITH_CM_AND_INCH_DIRECTION_1": "後退する",
    "MBOT2_MOVE_STRAIGHT_WITH_CM_AND_INCH_FIELDMENU_3_0": "cm",
    "MBOT2_MOVE_STRAIGHT_WITH_CM_AND_INCH_FIELDMENU_3_1": "インチ",
    "mbot2_move_straight_with_cm_and_inch": "完了するまで[POWER] [fieldMenu_3] [DIRECTION] ",
    "MBOT2_CW_AND_CCW_WITH_ANGLE_FIELDMENU_1_0": "左折する",
    "MBOT2_CW_AND_CCW_WITH_ANGLE_FIELDMENU_1_1": "右折する",
    "mbot2_cw_and_ccw_with_angle": "完了するまで [fieldMenu_1] に [ANGLE] °動かす",
    "MBOT2_ENCODER_MOTOR_SET_WITH_TIME_FIELDMENU_1_0": "左車輪(EM1)",
    "MBOT2_ENCODER_MOTOR_SET_WITH_TIME_FIELDMENU_1_1": "右車輪(EM2)",
    "MBOT2_ENCODER_MOTOR_SET_WITH_TIME_FIELDMENU_1_2": "全て",
    "MBOT2_ENCODER_MOTOR_SET_WITH_TIME_FIELDMENU_4_0": "回転速度(RPM)",
    "MBOT2_ENCODER_MOTOR_SET_WITH_TIME_FIELDMENU_4_1": "強さ(%)",
    "mbot2_encoder_motor_set_with_time": "エンコーダーモーター [fieldMenu_1] [image_2] を [LEFT_POWER][fieldMenu_4] で [number_3] 秒回転する",
    "mbot2_encoder_motor_set": "エンコーダーモーター [inputMenu_1] [image_2] を [LEFT_POWER][fieldMenu_4] で回転する",
    "mbot2_encoder_motor_set_with_time_angle_and_circle": "エンコーダーモーター [fieldMenu_1] [image_1] を [LEFT_POWER] °回転する ",
    "mbot2_encoder_motor_drive_speed": "エンコーダーモーターEM1 [image_1] が [LEFT_POWER]RPM、エンコーダーモーターEM2 [image_3] が [number_2]RPMで回転する",
    "mbot2_encoder_motor_drive_speed2": "encoder motor EM1 [image_1] rotates at [LEFT_POWER]RPM, encoder motor EM2 [image_3] rotates at [RIGHT_POWER] RPM",
    "mbot2_encoder_motor_drive_power": "エンコーダーモーターEM1 [image_1] が [LEFT_POWER] %の強さ、エンコーダーモーターEM2 [image_3] が [number_2] %の強さで回転する",
    "MBOT2_ENCODER_MOTOR_STOP_FIELDMENU_1_0": "(1) EM1",
    "MBOT2_ENCODER_MOTOR_STOP_FIELDMENU_1_1": "(2) M2",
    "MBOT2_ENCODER_MOTOR_STOP_FIELDMENU_1_2": "全て",
    "mbot2_encoder_motor_stop": "エンコーダーモーター [fieldMenu_1] を停止する",
    "MBOT2_ENCODER_MOTOR_GET_SPEED_INPUTMENU_2_0": "(1) EM1",
    "MBOT2_ENCODER_MOTOR_GET_SPEED_INPUTMENU_2_1": "(2) M2",
    "MBOT2_ENCODER_MOTOR_GET_SPEED_FIELDMENU_3_0": "回転速度(RPM)",
    "MBOT2_ENCODER_MOTOR_GET_SPEED_FIELDMENU_3_1": "強さ(%)",
    "mbot2_encoder_motor_get_speed": "エンコーダーモーター [inputMenu_2] の [image_2][fieldMenu_3]",
    "mbot2_encoder_motor_get_angle": "エンコーダーモーター [inputMenu_1] [image_2] の角度(°)",
    "mbot2_encoder_motor_reset_angle": "エンコーダーモーター [inputMenu_1][image_2] の角度をリセットする",
    "MBOT2_ENCODER_MOTOR_LOCK_AND_UNLOCK_FIELDMENU_2_0": "有効",
    "MBOT2_ENCODER_MOTOR_LOCK_AND_UNLOCK_FIELDMENU_2_1": "無効",
    "mbot2_encoder_motor_lock_and_unlock": "エンコーダーモーター [inputMenu_1] のオートロック [fieldMenu_2] ",
    "BLOCK_1599105327388": "设置底盘车轮直径为 [number_1] mm，车轮间距为 [number_2] mm【未完成】",
    "cate_6b671be0": "mBot2 シャーシ",
    "MBOT2_MOTOR_SET_POWER_CW_FIELDMENU_1_0": "全て",
    "MBOT2_MOTOR_SET_POWER_CW_FIELDMENU_1_1": "(1) M1",
    "MBOT2_MOTOR_SET_POWER_CW_FIELDMENU_1_2": "(2) M2",
    "mbot2_motor_set_power_cw": "モーター[fieldMenu_1] が [number_2] %の強さで回転する",
    "mbot2_motor_add_power_cw": "モーター[fieldMenu_1] の回転を [power] %強める",
    "mbot2_motor_driver_power_cw": "モーターM1の強さを [number_1] %、モーターM2の強さを [number_2] %にする",
    "MBOT2_MOTOR_GET_POWER_CW_FIELDMENU_1_0": "(1) M1",
    "MBOT2_MOTOR_GET_POWER_CW_FIELDMENU_1_1": "(2) M2",
    "mbot2_motor_get_power_cw": "モーター [fieldMenu_1] の回転出力の強さ(%)",
    "mbot2_motor_stop_power": "モーター [fieldMenu_1] を停止する",
    "MBOT2_SERVO_SET_ANGLE_FIELDMENU_1_0": "全て",
    "MBOT2_SERVO_SET_ANGLE_FIELDMENU_1_1": "(1) S1",
    "MBOT2_SERVO_SET_ANGLE_FIELDMENU_1_2": "(2) S2",
    "MBOT2_SERVO_SET_ANGLE_FIELDMENU_1_3": "(3) S3",
    "MBOT2_SERVO_SET_ANGLE_FIELDMENU_1_4": "(4) S4",
    "mbot2_servo_set_angle": "サーボモーター [fieldMenu_1] の角度を [angle] °にする",
    "mbot2_servo_add_angle": "サーボモーター [fieldMenu_1] の角度を [angle] °上げる",
    "mbot2_servo_driver": "サーボ角度をS1 [number_1]°、S2 [number_2]°、S3 [number_3]°、S4 [number_4] °にする",
    "MBOT2_SERVO_GET_ANGLE_FIELDMENU_1_0": "(1) S1",
    "MBOT2_SERVO_GET_ANGLE_FIELDMENU_1_1": "(2) S2",
    "MBOT2_SERVO_GET_ANGLE_FIELDMENU_1_2": "(3) S3",
    "MBOT2_SERVO_GET_ANGLE_FIELDMENU_1_3": "(4) S4",
    "mbot2_servo_get_angle": "サーボ [fieldMenu_1] の現在の角度 (°)",
    "mbot2_servo_release_angle": "サーボ [fieldMenu_1] のリリース角度",
    "mbot2_servo_reset_angle_to_zero": "サーボ [fieldMenu_1] を初期位置に戻す",
    "MBOT2_LED_SHOW_FIELDMENU_1_0": "全て",
    "MBOT2_LED_SHOW_FIELDMENU_1_1": "(1) S1",
    "MBOT2_LED_SHOW_FIELDMENU_1_2": "(2) S2",
    "mbot2_led_show": "LEDストリップ [fieldMenu_1] を[facePanel] 色で点灯する",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_0": "全て",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_1": "1",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_2": "2",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_3": "3",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_4": "4",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_5": "5",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_6": "6",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_7": "7",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_8": "8",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_9": "9",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_10": "10",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_11": "11",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_12": "12",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_13": "13",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_14": "14",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_15": "15",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_16": "16",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_17": "17",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_18": "18",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_19": "19",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_20": "20",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_21": "21",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_22": "22",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_23": "23",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_24": "24",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_25": "25",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_26": "26",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_27": "27",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_28": "28",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_29": "29",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_30": "30",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_31": "31",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_32": "32",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_33": "33",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_34": "34",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_35": "35",
    "MBOT2_LED_ON_WITH_COLOR_FIELDMENU_2_36": "36",
    "mbot2_led_on_with_color": "LEDストリップ [fieldMenu_1] のLED [fieldMenu_2] の色を [color_1] にする",
    "mbot2_led_on_with_rgb": "LEDストリップ [fieldMenu_1] のLED [fieldMenu_2] の色を R: [r] G: [g] B: [b] にする",
    "mbot2_led_move_with_cycle": "LEDストリップ [fieldMenu_1] の [number_2] を周期 [number_3] で回す",
    "mbot2_led_off": "LEDストリップ [fieldMenu_1] のLED [fieldMenu_2] を消す",
    "mbot2_led_add_brightness": "LEDストリップ [fieldMenu_1] の明るさを [number_1] %大きくする",
    "mbot2_led_set_brightness": "LEDストリップ [fieldMenu_1] の明るさを [number_1] %にする",
    "MBOT2_LED_GET_BRIGHTNESS_FIELDMENU_1_0": "(1) S1",
    "MBOT2_LED_GET_BRIGHTNESS_FIELDMENU_1_1": "(2) S2",
    "mbot2_led_get_brightness": "LEDストリップ [fieldMenu_1] の明るさ(%)",
    "mbot2_pin_is_high": "ピン [pin_number] が高い",
    "mbot2_pin_read_digtial": "デジタル読み取りピン [pin_number]",
    "mbot2_pin_use_5V_read_digtial": "電圧読み取りピン [inputMenu_1](V)",
    "mbot2_pin_write_digtial": "値 [Digtial_value] をピン[fieldMenu_1] にデジタルで書き込む",
    "MBOT2_PIN_SET_PWM_WITH_DUTY_AND_FRQUENCY_FIELDMENU_3_0": "2000",
    "MBOT2_PIN_SET_PWM_WITH_DUTY_AND_FRQUENCY_FIELDMENU_3_1": "1000",
    "MBOT2_PIN_SET_PWM_WITH_DUTY_AND_FRQUENCY_FIELDMENU_3_2": "500",
    "MBOT2_PIN_SET_PWM_WITH_DUTY_AND_FRQUENCY_FIELDMENU_3_3": "200",
    "MBOT2_PIN_SET_PWM_WITH_DUTY_AND_FRQUENCY_FIELDMENU_3_4": "100",
    "MBOT2_PIN_SET_PWM_WITH_DUTY_AND_FRQUENCY_FIELDMENU_3_5": "50",
    "MBOT2_PIN_SET_PWM_WITH_DUTY_AND_FRQUENCY_FIELDMENU_3_6": "20",
    "MBOT2_PIN_SET_PWM_WITH_DUTY_AND_FRQUENCY_FIELDMENU_3_7": "10",
    "MBOT2_PIN_SET_PWM_WITH_DUTY_AND_FRQUENCY_FIELDMENU_3_8": "5",
    "MBOT2_PIN_SET_PWM_WITH_DUTY_AND_FRQUENCY_FIELDMENU_3_9": "2",
    "mbot2_pin_set_pwm_with_duty_and_frquency": "アナログ書き込みピン [pin_number] デューティー比 [PWM_value] %、周波数 [fieldMenu_3] Hz",
    "cate_974f15e9": "mBot2 拡張ポート",
    "mbot2_encoder_motor_drive": "左車輪(EM1) [image_1] が[LEFT_POWER]RPM、右車輪(EM2) [image_3] が [number_2]RPMで回転する",
    "MBOT2_ENCODER_MOTOR_RESET_ANGLE_FIELDMENU_2_0": "左車輪(EM1)",
    "MBOT2_ENCODER_MOTOR_RESET_ANGLE_FIELDMENU_2_1": "右車輪(EM2)",
    "BLOCK_1618991049674": "エンコーダーモーターEM1 [image_1] が [LEFT_POWER] RPM、エンコーダーモーターEM2 [image_3] が [RIGHT_POWER]RPMで回転する"
};