export default {
    "raspberrypi_camera": "树莓派视觉",
    "extensionName": "树莓派视觉",
    "extensionDescription": "",
    "settings_e0af8b3d": "固件更新",
    "connect_fail_1ea235f7": "请确保网线已正确连接当前设备",
    "connect_fail_e6ac27c2": "请确保已成功安装USB转网口模块驱动",
    "connect_fail_f9935fe4": "请确保树莓派主板已上电开机",
    "upload_fail_25394bfc": "请检查该设备的积木或代码的数据类型、参数类型、编程逻辑是否符合程序规范",
    "upload_fail_02f5b518": "请检查您是否正确连接设备，可以尝试重启设备后再重新连接设备",
    "open_camera": "打开摄像头",
    "close_camera": "关闭摄像头",
    "RECOGNIZE_SYMBOL_SIZE_0": "150 * 150",
    "RECOGNIZE_SYMBOL_SIZE_1": "130 * 130",
    "RECOGNIZE_SYMBOL_SIZE_2": "100 * 100",
    "RECOGNIZE_SYMBOL_SIZE_3": "80 * 80",
    "RECOGNIZE_SYMBOL_SIZE_4": "60 * 60",
    "RECOGNIZE_SYMBOL_LETTER_0": "M",
    "RECOGNIZE_SYMBOL_LETTER_1": "A",
    "RECOGNIZE_SYMBOL_LETTER_2": "K",
    "RECOGNIZE_SYMBOL_LETTER_3": "E",
    "RECOGNIZE_SYMBOL_LETTER_4": "X",
    "RECOGNIZE_SYMBOL_TYPE_0": "中心坐标X",
    "RECOGNIZE_SYMBOL_TYPE_1": "中心坐标Y",
    "RECOGNIZE_SYMBOL_TYPE_2": "外接矩形宽",
    "RECOGNIZE_SYMBOL_TYPE_3": "外接矩形高",
    "RECOGNIZE_SYMBOL_TYPE_4": "面积",
    "RECOGNIZE_SYMBOL_TYPE_5": "离摄像头距离（mm）",
    "RECOGNIZE_SYMBOL_TYPE_6": "偏转角度",
    "recognize_symbol": "获取 尺寸为[SIZE] 字符 [LETTER] 的 [TYPE]",
    "cate_58ed155e": "图像",
    "raspberrypi_main": "树莓派视觉主程序",
    "raspberryPi": "树莓派",
    "firmware_is_latest": "固件版本正常",
    "firmware_is_old": "固件版本较低，请更新",
    "raspberrypi_firmware_link": "<a target=\"_blank\" rel=\"nofollow me noopener noreferrer\" style=\"                         text-decoration: none;                         display: inline-block;                         border: 1px solid #fff;                         padding: 3px 8px;                         background: #1eaaff;                         color: #fff!important;                         border-radius: 15px;                 \" href=\"https://www.mblock.cc/doc/zh/faq/firmware.html#3%E3%80%81%E6%A0%91%E8%8E%93%E6%B4%BE%E5%A6%82%E4%BD%95%E8%BF%9B%E8%A1%8C%E5%9B%BA%E4%BB%B6%E5%8D%87%E7%BA%A7%EF%BC%9F\">查看更新指南</a>",
    "novapi_firmware_link": "<a target=\"_blank\" rel=\"nofollow me noopener noreferrer\" style=\"                         text-decoration: none;                         display: inline-block;                         border: 1px solid #fff;                         padding: 3px 8px;                         background: #1eaaff;                         color: #fff!important;                         border-radius: 15px;                 \" href=\" https://www.mblock.cc/doc/zh/hardware-guide/novapi/novapi.html#固件升级\">查看更新指南</a>",
    "firmware_update": "固件更新",
    "ok": "确定",
    "insert_novapi": "请插入NovaPi",
    "novaPi": "NovaPi"
};