export default {
    "auriga_perception_gizmos": "Aparatos de detección",
    "extensionName": "Aparatos de detección",
    "extensionDescription": "En los 2 proyectos de extensión de mBot Ranger, aprenderás cómo usar los sensores en la vida real y comprenderás mejor la electrónica. ",
    "AURIGA_RUN_FAN_PORT_0": "puerto6",
    "AURIGA_RUN_FAN_PORT_1": "puerto7",
    "AURIGA_RUN_FAN_PORT_2": "puerto8",
    "AURIGA_RUN_FAN_PORT_3": "puerto9",
    "AURIGA_RUN_FAN_PORT_4": "puerto10",
    "AURIGA_RUN_FAN_FAN_ROTATE_0": "hacia la derecha",
    "AURIGA_RUN_FAN_FAN_ROTATE_1": "hacia la izquierda",
    "AURIGA_RUN_FAN_FAN_ROTATE_2": "Parada",
    "auriga_run_fan": "[ICON] ventilador [PORT] gira [FAN_ROTATE]",
    "auriga_detect_external_loudness": "[ICON] volumen del sensor de sonido [PORT]",
    "AURIGA_DETEC_TEMPERATURE_SLOT_0": "conexión 1",
    "AURIGA_DETEC_TEMPERATURE_SLOT_1": "conexión 2",
    "auriga_detec_temperature": "[ICON] sensor de temperatura [PORT] [SLOT] grados (℃)",
    "auriga_detect_potentiometer": "[ICON] valor del potenciómetro [PORT]",
    "CATEGORY_PERCEPTION": "Aparatos de detección"
};