export default {
    "halocode_mbuild_pirsensor": "ПІЧ датчик",
    "extensionName": "ПІЧ датчик",
    "extensionDescription": "",
    "EVENT_PIR_INDEX_0": "1",
    "EVENT_PIR_INDEX_1": "2",
    "EVENT_PIR_INDEX_2": "3",
    "EVENT_PIR_INDEX_3": "4",
    "EVENT_PIR_INDEX_4": "5",
    "EVENT_PIR_INDEX_5": "6",
    "EVENT_PIR_INDEX_6": "7",
    "EVENT_PIR_INDEX_7": "8",
    "event_pir": "ПІЧ датчик [index] виявив людину?",
    "pir_count": "ПІЧ датчик [index] кількість виявлень людини",
    "pir_count_make_zero": "ПІЧ датчик [index] скинути кількість виявлень",
    "cate_7477652c": "ПІЧ датчик",
    "BLOCK_1547779213407": "серво [ID] повертатися до [angle] (°)",
    "BLOCK_1547779701469": "динамік [ID] відтворювати звук [audio]",
    "BLOCK_1547779887637": "динамік [ID] відтворювати файл [audio] до кінця",
    "BLOCK_1547781171854": "динамік [ID] встановити гучність [volume] %"
};