export default {
    "megapipro_bluetoothcontroller": "Bluetooth Controller",
    "extensionName": "Bluetooth Controller",
    "extensionDescription": "Usa il Bluetooth controller per fare fare al tuo robot quello che vuoi.",
    "GETBLUETOOTHJOYSTICKVALUE_AXIS_0": "RX",
    "GETBLUETOOTHJOYSTICKVALUE_AXIS_1": "RY",
    "GETBLUETOOTHJOYSTICKVALUE_AXIS_2": "LX",
    "GETBLUETOOTHJOYSTICKVALUE_AXIS_3": "LY",
    "getBluetoothJoystickValue": "joystick[AXIS]",
    "CHECKBLUETOOTHKEY_AXIS_0": "1",
    "CHECKBLUETOOTHKEY_AXIS_1": "2",
    "CHECKBLUETOOTHKEY_AXIS_2": "3",
    "CHECKBLUETOOTHKEY_AXIS_3": "4",
    "CHECKBLUETOOTHKEY_AXIS_4": "←",
    "CHECKBLUETOOTHKEY_AXIS_5": "↑",
    "CHECKBLUETOOTHKEY_AXIS_6": "→",
    "CHECKBLUETOOTHKEY_AXIS_7": "↓",
    "CHECKBLUETOOTHKEY_AXIS_8": "L1",
    "CHECKBLUETOOTHKEY_AXIS_9": "R1",
    "CHECKBLUETOOTHKEY_AXIS_10": "L2",
    "CHECKBLUETOOTHKEY_AXIS_11": "R2",
    "CHECKBLUETOOTHKEY_AXIS_12": "Left Thumb",
    "CHECKBLUETOOTHKEY_AXIS_13": "Right Thumb",
    "CHECKBLUETOOTHKEY_AXIS_14": "+",
    "CHECKBLUETOOTHKEY_AXIS_15": "≡",
    "checkBluetoothKey": "bottone [AXIS] premuto",
    "controller": "Bluetooth controller"
};