export default {
    "mcore": "mBot",
    "extensionName": "mBot",
    "extensionDescription": "Fin de nueva categoría",
    "firmwares_version_0": "Firmware en internet",
    "firmwares_version_73cf5917": "Firmware de fábrica",
    "UPDATE_FIRMWARE": "Actualizar firmware",
    "connect_fail_2a0b1f15": "Asegúrate que el cable USB está conectado correctamente al dispositivo.",
    "connect_fail_488c674d": "Asegúrate que el dispositivo a conectar está encendido.",
    "connect_fail_0adf83ae": "Solo puedes conectar un dispositivo a la vez, en esta versión. Si conectas este dispositivo, se desconectará el que ya está conectado.",
    "connect_fail_9a020618": "No se puede actualizar el firmware cuando el modo Bluetooth 4.0 está encendido. Conecta el dispositivo con un cable USB e intenta actualizar el firmware de nuevo.",
    "connect_fail_f0f225df": "Asegúrate que tu ordenador tiene Bluetooth 4.0, y que el Bluetooth está encendido.",
    "connect_fail_3d459770": "Asegúrate que el dispositivo a conectar está encendido.",
    "connect_fail_13e00731": "Solo puedes conectar un dispositivo a la vez, en esta versión. Si conectas este dispositivo, se desconectará el que ya está conectado.",
    "connect_fail_4f0e9760": "Please make sure the 2.4G adapter is properly installed.",
    "connect_fail_e6e51d02": "Please make sure the device to connect is powered on.",
    "connect_fail_dc54eaae": "Solo puedes conectar un dispositivo a la vez, en esta versión. Si conectas este dispositivo, se desconectará el que ya está conectado.",
    "connect_fail_7c45be19": "2.4G module indicator status: slow flash = no adapter, fast flash = pairing, solid on=successful pairing",
    "upload_fail_fded06b5": "Comprueba los bloques de código o las líneas de código para este dispositivo. Asegúrate que los datos, parámetros y lógica del programa son correctos.",
    "upload_fail_17773a37": "Comprueba si tu dispositivo está bien conectado. Puedes reiniciar el dispositivo y conectarlo de nuevo.",
    "firmware_success_ddc56406": "Para aprovechar la actualización, puedes reiniciar el dispositivo y conectarlo de nuevo.",
    "firmware_fail_f1b7513c": "Comprueba que tu dispositivo esté bien conectado. Puedes reiniciar el dispositivo, volver a conectarlo e intentar actualizar el firmare de nuevo.",
    "MCORE_SHOW_FACE_TIME_PORT_0": "puerto1",
    "MCORE_SHOW_FACE_TIME_PORT_1": "puerto2",
    "MCORE_SHOW_FACE_TIME_PORT_2": "puerto3",
    "MCORE_SHOW_FACE_TIME_PORT_3": "puerto4",
    "mcore_show_face_time": "[ICON] panel LED [PORT] muestra imagen [FACE_PANEL] durante [TIME] seg",
    "mcore_show_face": "[ICON] panel LED [PORT] muestra imagen [FACE_PANEL]",
    "mcore_show_point_position": "[ICON] 表情面板 [PORT] 点亮x: [X] y: [Y] ",
    "mcore_show_face_position": "[ICON] panel LED [PORT] muestra imagen [FACE_PANEL] en x: [X] y: [Y]",
    "mcore_show_text": "[ICON] panel LED [PORT] muestra texto [TEXT] ",
    "mcore_show_text_position": "[ICON] panel LED [PORT] muestra texto [TEXT] en x: [X] y: [Y]",
    "mcore_show_number": "[ICON] panel LED [PORT] muestra número [NUMBER]",
    "mcore_show_time": "[ICON] panel LED [PORT] muestra hora [NUMBER1]:[NUMBER2]",
    "mcore_show_face_off": "[ICON] borra pantalla de panel LED [PORT]",
    "mcore_show_7segments_number": "[ICON] 7-segmentos [PORT] muestra número [NUMBER]",
    "CATEGORY_SHOW": "Apariencia",
    "MCORE_SHOW_LED_TIME_LED_POSTION_0": "todos",
    "MCORE_SHOW_LED_TIME_LED_POSTION_1": "izquierdo",
    "MCORE_SHOW_LED_TIME_LED_POSTION_2": "derecho",
    "mcore_show_led_time": "[ICON] enciende LED [LED_POSTION] en [COLOR] durante [TIME] seg",
    "mcore_show_led": "[ICON] enciende LED [LED_POSTION] en [COLOR]",
    "mcore_show_led_rgb": "[ICON] enciende LED [LED_POSTION] en rojo [R] verde [G] azul [B]",
    "MCORE_SOUND_PLAY_NOTE_NOTE_0": "Do2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_1": "Re2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_2": "Mi2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_3": "Fa2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_4": "Sol2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_5": "A2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_6": "Si2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_7": "Do3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_8": "Re3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_9": "Mi3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_10": "Fa3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_11": "Sol3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_12": "La3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_13": "Si3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_14": "Do4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_15": "Re4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_16": "Mi4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_17": "Fa4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_18": "Sol4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_19": "La4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_20": "Si4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_21": "Do5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_22": "Re5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_23": "Mi5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_24": "Fa5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_25": "Sol5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_26": "La5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_27": "Si5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_28": "Do6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_29": "Re6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_30": "Mi6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_31": "Fa6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_32": "Sol6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_33": "La6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_34": "Si6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_35": "Do7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_36": "Re7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_37": "Mi7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_38": "Fa7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_39": "Sol7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_40": "La7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_41": "Si7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_42": "Do8",
    "MCORE_SOUND_PLAY_NOTE_NOTE_43": "Re8",
    "mcore_sound_play_note": "[ICON] toca nota [NOTE] durante [BEAT] tiempos",
    "mcore_sound_play_hz": "[ICON] suena con frecuencia [HZ] Hz durante [TIME] seg",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "todos",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] LED RGB [PORT] encendido [LED_POSTION] en [COLOR] durante [TIME] seg",
    "mcore_show_external_led": "[ICON] LED RGB [PORT] encendido [LED_POSTION] en [COLOR]",
    "mcore_show_external_led_rgb": "[ICON] LED RGB [PORT] encendido [LED_POSTION] en rojo [R] verde [G] azul [B]",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_SLOT_0": "conexión 1",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_SLOT_1": "conexión 2",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "rojo",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "naranja",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "amarillo",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "verde",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "cian",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "azul",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "morado",
    "mcore_show_all_ledstrip_color": "[ICON] tira LED [PORT] [SLOT] encendida en [COLOR_LIST]",
    "mcore_show_ledstrip_color": "[ICON] tira LED [PORT] [SLOT] encendida [POS] en [COLOR_LIST]",
    "mcore_show_ledstrip_rbg": "[ICON] tira LED [PORT] [SLOT] encendida [POS] en rojo [R] verde [G] azul [B]",
    "CATEGORY_LIGHT": "Luz y Sonido",
    "mcore_forward_time": " [ICON] avanza a potencia [POWER]% durante [TIME] seg",
    "mcore_backward_time": "[ICON] retrocede a potencia [POWER]% durante [TIME] seg",
    "mcore_turnleft_time": "[ICON] gira a la izquierda a potencia [POWER]% durante [TIME] seg",
    "mcore_turnright_time": "[ICON] gira a la derecha a potencia [POWER]% durante [TIME] seg",
    "MCORE_MOVE_MOVE_DIRECTION_0": "avanza",
    "MCORE_MOVE_MOVE_DIRECTION_1": "retrocede",
    "MCORE_MOVE_MOVE_DIRECTION_2": "gira a la izquierda",
    "MCORE_MOVE_MOVE_DIRECTION_3": "gira a la derecha",
    "mcore_move": "[ICON] [MOVE_DIRECTION] a potencia [POWER]%",
    "mcore_move_wheel_speed": "[ICON] rueda izquierda a potencia [POWER_LEFT]%, rueda derecha a potencia [POWER_RIGHT]%",
    "mcore_move_stop": "[ICON] para",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_0": "pulsar",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_1": "soltar",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_2": "enfocar",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_3": "dejar de enfocar",
    "mcore_run_shutter": "[ICON]obturador [PORT] [SHUTTER_ACTION]",
    "MCORE_RUN_MOTOR_PORT_0": "motor puerto1",
    "MCORE_RUN_MOTOR_PORT_1": "motor puerto2",
    "MCORE_RUN_MOTOR_ROTATE_0": "hacia la derecha",
    "MCORE_RUN_MOTOR_ROTATE_1": "hacia la izquierda",
    "mcore_run_motor": "[ICON] motor C.C. [PORT] gira [ROTATE] a potencia [POWER]%",
    "mcore_run_servo": "[ICON] servo [PORT] [SLOT] girado en ángulo [DEGREE]",
    "MCORE_RUN_FAN_FAN_ROTATE_0": "hacia la derecha",
    "MCORE_RUN_FAN_FAN_ROTATE_1": "hacia la izquierda",
    "MCORE_RUN_FAN_FAN_ROTATE_2": "(no gira)",
    "mcore_run_fan": "[ICON] ventilador [PORT] gira [FAN_ROTATE]",
    "CATEGORY_ACTION": "Acción",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_0": "puerto3",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_1": "puerto4",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_2": "integrado",
    "mcore_detect_external_light": "[ICON] intensidad del sensor de luz [PORT]",
    "mcore_detect_external_ultrasonic": "[ICON]ultrasonic sensor [PORT] distance(cm)",
    "mcore_detect_external_linefollower": "[ICON] valor del sensor siguelíneas [PORT]",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "lado izquierdo",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "lado derecho",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "todos",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "ninguno",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "negro",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "blanco",
    "mcore_event_external_linefollower": "[ICON] ¿sensor siguelíneas [PORT] detecta [LINEFOLLOW_STATE] [BLACK_WHITE]?",
    "MCORE_EVENT_BOARD_BUTTON_PRESSED_OPTION_0": "pulsado",
    "MCORE_EVENT_BOARD_BUTTON_PRESSED_OPTION_1": "soltado",
    "mcore_event_board_button_pressed": "[ICON] ¿cuando botón integrado [OPTION]?",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_0": "A",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_1": "B",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_2": "C",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_3": "D",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_4": "E",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_5": "F",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_6": "arriba",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_7": "abajo",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_8": "izquierda",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_9": "derecha",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_10": "fijar",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_11": "0",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_12": "1",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_13": "2",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_14": "3",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_15": "4",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_16": "5",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_17": "6",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_18": "7",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_19": "8",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_20": "9",
    "mcore_event_ir_remote": "[ICON] ¿pulsado botón [REMOTE_KEY] del mando a distancia?",
    "mcore_send_ir": "[ICON] envía mensaje infrarrojo [MESSAGE]",
    "mcore_detect_ir": "[ICON] mensaje infrarrojo recibido",
    "mcore_detect_timer": "[ICON] temporizador",
    "mcore_reset_timer": "[ICON] reiniciar temporizador",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_0": "puerto3",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_1": "puerto4",
    "mcore_detect_external_loudness": "[ICON] volumen del sensor de sonido [PORT]",
    "mcore_detec_temperature": "[ICON] sensor de temperatura [PORT] [SLOT] grados (℃)",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_0": "humedad",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_1": "temperatura",
    "mcore_detect_humiture": "[ICON] sensor de temperatura+humedad [PORT] [TEMP_HUMITURE]",
    "mcore_event_touch": "[ICON] ¿activado sensor de contacto [PORT]?",
    "mcore_detect_compass": "[ICON] brújula electrónica [PORT] hacia el norte",
    "mcore_detect_flame": "[ICON] valor del sensor de llama [PORT]",
    "mcore_detect_gas": "[ICON] valor de sensor de gas [PORT]",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_0": "eje x",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_1": "eje y",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_2": "eje z",
    "mcore_detect_gyro_angle": "[ICON] ángulo [AXIS] del giroscopio",
    "mcore_event_pir_motion": "[ICON] ¿sensor de presencia [PORT] detecta movimiento de personas？",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_0": "botón1",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_1": "botón2",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_2": "botón3",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_3": "botón4",
    "mcore_event_button_press": "[ICON] ¿pulsado botón [PORT] [FOUR_KEY]？",
    "mcore_event_limit_switch": "[ICON] ¿pulsado interruptor de tope [PORT] [SLOT]?",
    "mcore_detect_potentiometer": "[ICON] valor del potenciómetro [PORT]",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_0": "eje x",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_1": "eje y",
    "mcore_detect_joystick": "[ICON] valor [AXIS_X_Y] del mando de juego [PORT]",
    "mcore_detect_infrared": "[ICON] receptor de infrarrojos [PORT] ",
    "mcore_event_linefollower": "[ICON] ¿detectada línea negra?",
    "mcore_event_obstacle": "[ICON] ¿obstáculo delante?",
    "mcore_detect_obstacle_distance": "[ICON] distancia al obstáculo al frente",
    "mcore_detect_light": "[ICON] intensidad de luz ambiente",
    "CATEGORY_SENSOR": "Sensores",
    "mcore_when_board_launch": "cuando mBot(mcore) se pone en marcha",
    "mcore_when_board_button": "cuando botón integrado [IS_PRESS]"
};