export default {
    "mcore": "mBot",
    "extensionName": "mBot",
    "extensionDescription": "קטגוריה חדשה סוף",
    "firmwares_version_0": "קושחה מקוונת",
    "firmwares_version_73cf5917": "קושחה מקורית",
    "UPDATE_FIRMWARE": "עדכן קושחה",
    "connect_fail_2a0b1f15": "נא ודא שכבל ה-USB מחובר כראוי להתקן.",
    "connect_fail_488c674d": "נא ודא שההתקן שיחובר מופעל.",
    "connect_fail_0adf83ae": "ניתן לחבר רק התקן אחד בכל פעם בגירסה זו. חיבור התקן חדש יוביל לניתוק של הרכיב הקיים.",
    "connect_fail_9a020618": "מצב ההעלאה אינו נתמך כאשר בלוטוס 4 דלוק. חברו את המכשיר דרך USB ונסו לעדכן את הקושחה שוב.",
    "connect_fail_f0f225df": "נא ודא שהמחשב שלך תומך ב-Bluetooth 4.0 ו-Bluetooth כבר מאופשר.",
    "connect_fail_3d459770": "נא ודא שההתקן שיחובר מופעל.",
    "connect_fail_13e00731": "ניתן לחבר רק התקן אחד בכל פעם בגירסה זו. חיבור התקן חדש יוביל לניתוק של הרכיב הקיים.",
    "connect_fail_4f0e9760": "בבקשה וודאו שהמתאם 2.4G מותקן כראוי.",
    "connect_fail_e6e51d02": "נא ודא שההתקן המחובר מופעל.",
    "connect_fail_dc54eaae": "ניתן לחבר רק התקן אחד בכל פעם בגירסה זו. חיבור התקן חדש יוביל לניתוק של הרכיב הקיים.",
    "connect_fail_7c45be19": "סטטוס מודל 2.4G מראה: הבהוב איטי = אין מתאם, הבהוב מהיר = מצבע צימוד, דולק קבוע = הצימוד בוצע בהצלחה",
    "upload_fail_fded06b5": "נא עברו על הבלוקים או הקוד של המכשיר הזה. וודאו שכל המידע, הפרמטרים והלוגיקה נכונים.",
    "upload_fail_17773a37": "נא בדוק אם ההתקן מחובר כראוי. נסה להפעיל מחדש את ההתקן ולחבר אותו שוב.",
    "firmware_success_ddc56406": "לחוויה יותר טובה, אתם יכולים להדליק מחדש את המכשיר ולחבר אותו שוב.",
    "firmware_fail_f1b7513c": "נא וודאו שהמכשיר מחובר בצורה תקינה. אתם יכולים להפעיל שוב את המכשיר, לחבר אותו שוב ואז נסו לעדכן קושחה שוב.",
    "MCORE_SHOW_FACE_TIME_PORT_0": "port1",
    "MCORE_SHOW_FACE_TIME_PORT_1": "יציאה 2",
    "MCORE_SHOW_FACE_TIME_PORT_2": "יציאה 3",
    "MCORE_SHOW_FACE_TIME_PORT_3": "port4",
    "mcore_show_face_time": "[ICON] פנל לדים [PORT] מציג תמונת [FACE_PANEL] למשך [TIME] שניות",
    "mcore_show_face": "[ICON] פנל לדים [PORT] מציג תמונת [FACE_PANEL]",
    "mcore_show_point_position": "[ICON] 表情面板 [PORT] 点亮x: [X] y: [Y] ",
    "mcore_show_face_position": "[ICON] פנל נוריות [PORT] מציג תמונת [FACE_PANEL] בקואורדינטות - [X], [Y]",
    "mcore_show_text": "[ICON] פנל לדים [PORT] מציג טקסט [TEXT] ",
    "mcore_show_text_position": "[ICON]פנל לדים [PORT] מציג טקסט [TEXT] בקואורדינטות - [X], [Y]",
    "mcore_show_number": "[ICON] פנל לדים [PORT] מציג מספר [NUMBER]",
    "mcore_show_time": "[ICON] פנל לדים [PORT] מציג זמן [NUMBER1]: [NUMBER2]",
    "mcore_show_face_off": "[ICON] פנל לדים [PORT] מנקה מסך",
    "mcore_show_7segments_number": "[ICON] שבעה מקטעים [PORT] הצג מספר [NUMBER]",
    "CATEGORY_SHOW": "מראה",
    "MCORE_SHOW_LED_TIME_LED_POSTION_0": "הכל",
    "MCORE_SHOW_LED_TIME_LED_POSTION_1": "שמאל",
    "MCORE_SHOW_LED_TIME_LED_POSTION_2": "ימין",
    "mcore_show_led_time": "[ICON] לד [LED_POSTION] מראה צבע [COLOR] למשך [TIME] שניות",
    "mcore_show_led": "[ICON] לד [LED_POSTION] מראה צבע [COLOR]",
    "mcore_show_led_rgb": "[ICON] הדלק אור [LED_POSTION] עם צבע אדום [R] ירוק [G] כחול [B]",
    "MCORE_SOUND_PLAY_NOTE_NOTE_0": "C2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_1": "D2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_2": "E2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_3": "F2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_4": "G2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_5": "A2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_6": "B2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_7": "C3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_8": "D3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_9": "E3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_10": "F3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_11": "G3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_12": "A3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_13": "B3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_14": "C4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_15": "D4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_16": "E4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_17": "F4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_18": "G4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_19": "A4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_20": "B4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_21": "C5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_22": "D5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_23": "E5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_24": "F5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_25": "G5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_26": "A5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_27": "B5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_28": "C6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_29": "D6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_30": "E6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_31": "F6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_32": "G6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_33": "A6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_34": "B6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_35": "C7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_36": "D7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_37": "E7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_38": "F7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_39": "G7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_40": "A7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_41": "B7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_42": "C8",
    "MCORE_SOUND_PLAY_NOTE_NOTE_43": "D8",
    "mcore_sound_play_note": "[ICON] נגן תו [NOTE] למשך [BEAT] ביטים",
    "mcore_sound_play_hz": "[ICON] נגן צליל בתדר [HZ] הרץ במשך [TIME] שניות",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "הכל",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] לד RGB [PORT] האורות דולקים [LED_POSTION] בצבע [COLOR] עבור [TIME] שניות",
    "mcore_show_external_led": "[ICON] נורית מסוג RGB [PORT] האורות דולקים [LED_POSTION] בצבע [COLOR]",
    "mcore_show_external_led_rgb": "[ICON] נורית מסוג RGB [PORT] האורות דולקים [LED_POSTION] בצבע אדום [R] ירוק [G] כחול [B]",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_SLOT_0": "מחבר 1",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_SLOT_1": "מחבר 2",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "אדום",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "כתום",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "צהוב",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "ירוק",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "טורקיז",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "כחול",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "סגול",
    "mcore_show_all_ledstrip_color": "[ICON] רצועת לדים [PORT] [SLOT] כולם מאירים בצבע [COLOR_LIST]",
    "mcore_show_ledstrip_color": "[ICON] רצועת לדים [PORT] [SLOT] [POS] דולק בצבע [COLOR_LIST]",
    "mcore_show_ledstrip_rbg": "[ICON] רצועת לדים [PORT] [SLOT] [POS] הנורות דולקות בצבע אדום [R] ירוק [G] כחול [B]",
    "CATEGORY_LIGHT": "הצג",
    "mcore_forward_time": " [ICON] מתקדם בכוח [POWER] % למשך [TIME] שניות",
    "mcore_backward_time": "[ICON] נע לאחור בכוח [POWER] % למשך [TIME] שניות",
    "mcore_turnleft_time": "[ICON] פונה שמאלה בכוח [POWER] % למשך [TIME] שניות",
    "mcore_turnright_time": "[ICON] פונה ימינה בכוח [POWER] % למשך [TIME] שניות",
    "MCORE_MOVE_MOVE_DIRECTION_0": "זוז קדימה",
    "MCORE_MOVE_MOVE_DIRECTION_1": "זוז אחורה",
    "MCORE_MOVE_MOVE_DIRECTION_2": "פנה שמאלה",
    "MCORE_MOVE_MOVE_DIRECTION_3": "פנה ימינה",
    "mcore_move": "[MOVE_DIRECTION] [ICON] בכח [POWER] %",
    "mcore_move_wheel_speed": "[ICON] הגלגל השמאלי מסתובב בעוצמה [POWER_LEFT] %, הגלגל הימני מסתובב בעוצמה [POWER_RIGHT] %",
    "mcore_move_stop": "[ICON] עצור",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_0": "לחץ",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_1": "שחרר",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_2": "התמקד",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_3": "הפסק מיקוד",
    "mcore_run_shutter": "[ICON] תריס [PORT] [SHUTTER_ACTION]",
    "MCORE_RUN_MOTOR_PORT_0": "port1 על המנוע",
    "MCORE_RUN_MOTOR_PORT_1": "יציאת מנוע 2",
    "MCORE_RUN_MOTOR_ROTATE_0": "בכיוון השעון",
    "MCORE_RUN_MOTOR_ROTATE_1": "נגד כיוון השעון",
    "mcore_run_motor": "[ICON] מנוע DC [PORT] [ROTATE] מסתובב בעוצמה [POWER] %",
    "mcore_run_servo": "[ICON] מנוע סרוו [PORT] [SLOT] ממוקם בזווית [DEGREE]",
    "MCORE_RUN_FAN_FAN_ROTATE_0": "בכיוון השעון",
    "MCORE_RUN_FAN_FAN_ROTATE_1": "נגד כיוון השעון",
    "MCORE_RUN_FAN_FAN_ROTATE_2": "עצור",
    "mcore_run_fan": "[ICON] מאוורר [PORT] [FAN_ROTATE] מסתובב",
    "CATEGORY_ACTION": "פעולה",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_0": "port2",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_1": "פורט 4",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_2": "על הלוח",
    "mcore_detect_external_light": "[ICON] חיישן אור [PORT] עוצמת אור",
    "mcore_detect_external_ultrasonic": "[ICON] חיישן אולטרה סוניק [PORT] מרחק (ס\"מ)",
    "mcore_detect_external_linefollower": "[ICON] חיישן עקיבת קו [PORT] ערך",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "צד שמאל",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "צד ימין",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "הכל",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "ללא",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "שחור",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "לבן",
    "mcore_event_external_linefollower": "[ICON] חיישן עקיבת קו[PORT] מזהה[LINEFOLLOW_STATE] כ- [BLACK_WHITE] ？",
    "MCORE_EVENT_BOARD_BUTTON_PRESSED_OPTION_0": "נלחץ",
    "MCORE_EVENT_BOARD_BUTTON_PRESSED_OPTION_1": "משוחרר",
    "mcore_event_board_button_pressed": "[ICON]כאשר לחצן שנמצא על הלוח [OPTION]?",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_0": "A",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_1": "B",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_2": "C",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_3": "D",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_4": "E",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_5": "F",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_6": "למעלה",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_7": "למטה",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_8": "שמאל",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_9": "ימין",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_10": "הגדר",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_11": "0",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_12": "1",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_13": "2",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_14": "3",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_15": "4",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_16": "5",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_17": "6",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_18": "7",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_19": "8",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_20": "9",
    "mcore_event_ir_remote": "[ICON] שלט אינפרה אדום [REMOTE_KEY] נלחץ?",
    "mcore_send_ir": "[ICON] שלח הודעה דרך אינפרה אדום [MESSAGE]",
    "mcore_detect_ir": "[ICON] אינפרה אדום הודעה התקבלה",
    "mcore_detect_timer": "[ICON] טיימר",
    "mcore_reset_timer": "[ICON] אפס טיימר",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_0": "יציאה 3",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_1": "יציאה 4",
    "mcore_detect_external_loudness": "[ICON] חיישן קול [PORT] עוצמה",
    "mcore_detec_temperature": "[ICON] חיישן טמפרטורה [PORT] [SLOT] צלסיוס (° c)",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_0": "לחות",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_1": "טמפרטורה",
    "mcore_detect_humiture": "[ICON] חיישן לחות וטמפרטורה[PORT] [TEMP_HUMITURE]",
    "mcore_event_touch": "[ICON] חיישן מגע [PORT] נגיעה?",
    "mcore_detect_compass": "[ICON] מצפן אלקטרוני [PORT] לכיוון צפון",
    "mcore_detect_flame": "[ICON] חיישן הלהבה [PORT] ערך",
    "mcore_detect_gas": "[ICON]חיישן הגז [PORT] ערך",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_0": "ציר x",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_1": "ציר y",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_2": "ציר z",
    "mcore_detect_gyro_angle": "[ICON] ג'יירוסקופ [AXIS] זווית",
    "mcore_event_pir_motion": "[ICON] חיישן PIR [PORT] מזהה תנועה אנושית",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_0": "לחצן 1",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_1": "לחצן 2",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_2": "לחצן 3",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_3": "לחצן 4",
    "mcore_event_button_press": "[ICON] לחצן [PORT] [FOUR_KEY] נלחץ?",
    "mcore_event_limit_switch": "[ICON]מפסק גבול [PORT] [SLOT] נלחץ?",
    "mcore_detect_potentiometer": "[ICON] נגד משתנה [PORT] ערך",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_0": "ציר x",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_1": "ציר y",
    "mcore_detect_joystick": "[ICON] ג'ויסטיק [PORT] ערך [AXIS_X_Y]",
    "mcore_detect_infrared": "[ICON]מקלט אינפרה אדום [PORT] ",
    "mcore_event_linefollower": "[ICON]קו שחור מזוהה?",
    "mcore_event_obstacle": "[ICON] מכשול לפנים?",
    "mcore_detect_obstacle_distance": "[ICON] מרחק של מכשול לפנים",
    "mcore_detect_light": "[ICON] עוצמת אור סביבתי",
    "CATEGORY_SENSOR": "לחוש",
    "mcore_when_board_launch": "כאשר mBot(mcore) עולה",
    "mcore_when_board_button": "כאשר הפתור על הלוח [IS_PRESS]"
};