export default {
    "mcore": "mBot",
    "extensionName": "mBot",
    "extensionDescription": "Новая категория END",
    "firmwares_version_0": "Прошивка онлайн",
    "firmwares_version_73cf5917": "Заводская прошивка",
    "UPDATE_FIRMWARE": "Обновить прошивку",
    "connect_fail_2a0b1f15": "Убедитесь, что кабель USB правильно подключен к устройству.",
    "connect_fail_488c674d": "Убедитесь, что подключенное устройство включено.",
    "connect_fail_0adf83ae": "Только одно устройство может быть подключено одновременно в этой версии. Таким образом, подключение этого устройства приведет к разъединению предыдущего.",
    "connect_fail_9a020618": "Режим загрузки не поддерживается, если включен режим Bluetooth 4,0. Подключите устройство через USB-кабель и повторите попытку обновления микропрограммы.",
    "connect_fail_f0f225df": "Пожалуйста, убедитесь, что ваш компьютер поддерживает Bluetooth 4,0 и Bluetooth уже включен.",
    "connect_fail_3d459770": "Убедитесь, что подключенное устройство включено.",
    "connect_fail_13e00731": "Только одно устройство может быть подключено одновременно в этой версии. Таким образом, подключение этого устройства приведет к разъединению предыдущего.",
    "connect_fail_4f0e9760": "Please make sure the 2.4G adapter is properly installed.",
    "connect_fail_e6e51d02": "Please make sure the device to connect is powered on.",
    "connect_fail_dc54eaae": "Только одно устройство может быть подключено одновременно в этой версии. Таким образом, подключение этого устройства приведет к разъединению предыдущего.",
    "connect_fail_7c45be19": "2.4G module indicator status: slow flash = no adapter, fast flash = pairing, solid on=successful pairing",
    "upload_fail_fded06b5": "Пожалуйста, просмотрите блоки кодирования или код для этого устройства. Убедитесь, что все данные, параметры и логика программирования верны.",
    "upload_fail_17773a37": "Пожалуйста, убедитесь, что ваше устройство подключено правильно. Можно перезагрузить устройство и подключить его снова.",
    "firmware_success_ddc56406": "Для лучшего опыта, вы можете перезагрузить устройство и подключить его еще раз.",
    "firmware_fail_f1b7513c": "Убедитесь, что устройство подключено правильно. Вы можете перезагрузить устройство, подключить его снова, а затем попробовать обновить прошивку еще раз.",
    "MCORE_SHOW_FACE_TIME_PORT_0": "порт1",
    "MCORE_SHOW_FACE_TIME_PORT_1": "порт2",
    "MCORE_SHOW_FACE_TIME_PORT_2": "порт3",
    "MCORE_SHOW_FACE_TIME_PORT_3": "порт4",
    "mcore_show_face_time": "[ICON] Светодиодная панель [PORT] отображает изображение [FACE_PANEL] [TIME] сек",
    "mcore_show_face": "[ICON] Светодиодная панель [PORT] отображает изображение [FACE_PANEL]",
    "mcore_show_point_position": "[ICON] 表情面板 [PORT] 点亮x: [X] y: [Y] ",
    "mcore_show_face_position": "[ICON] Светодиодная панель [PORT] отображает изображение [FACE_PANEL] на x:[X], y:[Y]",
    "mcore_show_text": "[ICON] Светодиодная панель [PORT] отображает текст [TEXT] ",
    "mcore_show_text_position": "[ICON] Светодиодная панель [PORT] показывает текст [TEXT] на X:[X], Y:[Y]",
    "mcore_show_number": "[ICON] Светодиодная панель [PORT] показывает число [NUMBER]",
    "mcore_show_time": "[ICON] Светодиодная панель [PORT] показывает время [NUMBER1]: [NUMBER2]",
    "mcore_show_face_off": "[ICON] Светодиодная панель [PORT] очищает экран",
    "mcore_show_7segments_number": "[ICON] 7-сегментный дисплей [PORT] показывает число [NUMBER]",
    "CATEGORY_SHOW": "Внешность",
    "MCORE_SHOW_LED_TIME_LED_POSTION_0": "все",
    "MCORE_SHOW_LED_TIME_LED_POSTION_1": "влево",
    "MCORE_SHOW_LED_TIME_LED_POSTION_2": "вправо",
    "mcore_show_led_time": "[ICON] Светодиод [LED_POSTION] светится цветом [COLOR] в течение [TIME] сек",
    "mcore_show_led": "[ICON] Светодиод [LED_POSTION] светится цветом [COLOR]",
    "mcore_show_led_rgb": "[ICON] включить свет [LED_POSTION] с цветами: красный [R], зеленый [G], синий [B]",
    "MCORE_SOUND_PLAY_NOTE_NOTE_0": "C2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_1": "D2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_2": "E2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_3": "F2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_4": "G2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_5": "A2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_6": "B2",
    "MCORE_SOUND_PLAY_NOTE_NOTE_7": "C3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_8": "D3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_9": "E3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_10": "F3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_11": "G3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_12": "A3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_13": "B3",
    "MCORE_SOUND_PLAY_NOTE_NOTE_14": "C4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_15": "D4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_16": "E4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_17": "F4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_18": "G4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_19": "A4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_20": "B4",
    "MCORE_SOUND_PLAY_NOTE_NOTE_21": "C5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_22": "D5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_23": "E5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_24": "F5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_25": "G5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_26": "A5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_27": "B5",
    "MCORE_SOUND_PLAY_NOTE_NOTE_28": "C6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_29": "D6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_30": "E6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_31": "F6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_32": "G6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_33": "A6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_34": "B6",
    "MCORE_SOUND_PLAY_NOTE_NOTE_35": "C7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_36": "D7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_37": "E7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_38": "F7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_39": "G7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_40": "A7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_41": "B7",
    "MCORE_SOUND_PLAY_NOTE_NOTE_42": "C8",
    "MCORE_SOUND_PLAY_NOTE_NOTE_43": "D8",
    "mcore_sound_play_note": "[ICON]играть ноту [NOTE] длительностью [BEAT] долей",
    "mcore_sound_play_hz": "[ICON]воспроизводить звук частотой [HZ] Гц [TIME] сек",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "все",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] RGB LED [PORT] загорается [LED_POSTION] цветом [COLOR] на [TIME] сек",
    "mcore_show_external_led": "[ICON]RGB LED [PORT] загорается [LED_POSTION] цветом [COLOR]",
    "mcore_show_external_led_rgb": "[ICON]RGB LED [PORT] загорается [LED_POSTION] цветом красный [R] зеленый [G] синий [B]",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_SLOT_0": "слот1",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_SLOT_1": "слот2",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "красный",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "оранжевый",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "жёлтый",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "зелёный",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "голубой",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "синий",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "фиолетовый",
    "mcore_show_all_ledstrip_color": "[ICON] Светодиодная лента [PORT] [SLOT] загорается цветом [COLOR_LIST]",
    "mcore_show_ledstrip_color": "[ICON] Светодиодная лента [PORT] [SLOT] [POS] загорается цветом [COLOR_LIST]",
    "mcore_show_ledstrip_rbg": "[ICON] Светодиодная лента [PORT] [SLOT] [POS] включить цвет: красный [R] зеленый [G] синий [B]",
    "CATEGORY_LIGHT": "sound & light",
    "mcore_forward_time": " [ICON]двигаться вперёд на скорости [POWER] % в течение [TIME] секунд",
    "mcore_backward_time": "[ICON]двигаться назад на скорости [POWER] % в течение [TIME] секунд",
    "mcore_turnleft_time": "[ICON] повернуть налево на скорости [POWER] % в течение [TIME] секунд",
    "mcore_turnright_time": "[ICON] повернуть направо на скорости [POWER] % в течение [TIME] секунд",
    "MCORE_MOVE_MOVE_DIRECTION_0": "двигаться вперед",
    "MCORE_MOVE_MOVE_DIRECTION_1": "двигаться назад",
    "MCORE_MOVE_MOVE_DIRECTION_2": "повернуть налево",
    "MCORE_MOVE_MOVE_DIRECTION_3": "повернуть направо",
    "mcore_move": "[ICON] [MOVE_DIRECTION] на скорости [POWER] %",
    "mcore_move_wheel_speed": "[ICON] вращать левое колесо со скоростью [POWER_LEFT] %, правое колесо со скоростью [POWER_RIGHT] %",
    "mcore_move_stop": "[ICON] остановить движение",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_0": "нажать",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_1": "отжать",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_2": "фокус",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_3": "остановить фокусировку",
    "mcore_run_shutter": "[ICON]затвор [PORT] [SHUTTER_ACTION]",
    "MCORE_RUN_MOTOR_PORT_0": "порт двигателя 1",
    "MCORE_RUN_MOTOR_PORT_1": "порт двигателя 2",
    "MCORE_RUN_MOTOR_ROTATE_0": "по часовой стрелке",
    "MCORE_RUN_MOTOR_ROTATE_1": "против часовой стрелки",
    "mcore_run_motor": "[ICON] двигатель постоянного тока [PORT] вращать [ROTATE] на скорости [POWER]%",
    "mcore_run_servo": "[ICON] сервомотор [PORT] [SLOT] расположен под углом [DEGREE]",
    "MCORE_RUN_FAN_FAN_ROTATE_0": "по часовой стрелке",
    "MCORE_RUN_FAN_FAN_ROTATE_1": "против часовой стрелки",
    "MCORE_RUN_FAN_FAN_ROTATE_2": "остановить",
    "mcore_run_fan": "[ICON] вентилятор [PORT] [FAN_ROTATE] вращается",
    "CATEGORY_ACTION": "Действие",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_0": "Порт3",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_1": "Порт4",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_2": "на борту",
    "mcore_detect_external_light": "[ICON] световой датчик [PORT] интенсивность света",
    "mcore_detect_external_ultrasonic": "[ICON]ultrasonic sensor [PORT] distance(cm)",
    "mcore_detect_external_linefollower": "[ICON] датчик линии [PORT] отображает значение",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "слева",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "справа",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "все",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "нет",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "чёрный",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "белый",
    "mcore_event_external_linefollower": "[ICON] датчик линии [PORT] обнаруживает [LINEFOLLOW_STATE] в состоянии [BLACK_WHITE] ?",
    "MCORE_EVENT_BOARD_BUTTON_PRESSED_OPTION_0": "нажата",
    "MCORE_EVENT_BOARD_BUTTON_PRESSED_OPTION_1": "отпущена",
    "mcore_event_board_button_pressed": "[ICON]когда бортовая кнопка [OPTION]?",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_0": "A",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_1": "B",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_2": "C",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_3": "D",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_4": "E",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_5": "F",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_6": "вверх",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_7": "вниз",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_8": "влево",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_9": "вправо",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_10": "установить",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_11": "0",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_12": "1",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_13": "2",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_14": "3",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_15": "4",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_16": "5",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_17": "6",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_18": "7",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_19": "8",
    "MCORE_EVENT_IR_REMOTE_REMOTE_KEY_20": "9",
    "mcore_event_ir_remote": "[ICON] Нажата кнопка [REMOTE_KEY] на ИК-пульте?",
    "mcore_send_ir": "[ICON]отправить сообщение [MESSAGE] по ИК-порту",
    "mcore_detect_ir": "[ICON] Получено сообщение по ИК-порту",
    "mcore_detect_timer": "[ICON] таймер",
    "mcore_reset_timer": "[ICON] обнулить таймер",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_0": "Порт3",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_1": "Порт4",
    "mcore_detect_external_loudness": "[ICON]звуковой датчик [PORT] громкость",
    "mcore_detec_temperature": "[ICON]датчик температуры [PORT] [SLOT] в градусах Цельсия (℃)",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_0": "влажность",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_1": "температура",
    "mcore_detect_humiture": "[ICON]датчик температуры/влажности [PORT] [TEMP_HUMITURE]",
    "mcore_event_touch": "[ICON] датчик прикосновения [PORT] активен?",
    "mcore_detect_compass": "[ICON] электронный компас [PORT] в северном направлении",
    "mcore_detect_flame": "[ICON] датчик огня [PORT] фиксирует значение",
    "mcore_detect_gas": "[ICON]датчик газа [PORT] фиксирует значение",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_0": "ось X",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_1": "ось Y",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_2": "ось Z",
    "mcore_detect_gyro_angle": "[ICON]гироскоп [AXIS] угол",
    "mcore_event_pir_motion": "[ICON] Датчик движения [PORT] фиксирует движение?",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_0": "кнопка 1",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_1": "кнопка 2",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_2": "кнопка 3",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_3": "кнопка 4",
    "mcore_event_button_press": "[ICON] кнопка [PORT] [FOUR_KEY] нажата?",
    "mcore_event_limit_switch": "[ICON]концевой выключатель [PORT] [SLOT] нажат?",
    "mcore_detect_potentiometer": "[ICON] потенциометр [PORT] отображает значение",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_0": "ось X",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_1": "ось Y",
    "mcore_detect_joystick": "[ICON]джойстик [PORT] [AXIS_X_Y] отображает значение",
    "mcore_detect_infrared": "[ICON] Инфракрасный приемник [PORT] ",
    "mcore_event_linefollower": "[ICON] черная линия обнаружена?",
    "mcore_event_obstacle": "[ICON] впереди препятствие?",
    "mcore_detect_obstacle_distance": "[ICON] расстояние до препятствия впереди",
    "mcore_detect_light": "[ICON] яркость окружающего света",
    "CATEGORY_SENSOR": "Сенсоры",
    "mcore_when_board_launch": "при запуске mBot(mcore)",
    "mcore_when_board_button": "при нажатии бортовой кнопки [IS_PRESS]"
};