export default {
    "haloboard": "Halocode",
    "extensionName": "Halocode",
    "extensionDescription": "Halocode single-Board računalo s ugrađenim Wi-Fi",
    "firmwares_version_9c2fcf2b": "Najnoviji firmware",
    "UPDATE_FIRMWARE": "Firmware ažurirati",
    "settings_717e2676": "Status Check",
    "connect_fail_418dd2b0": "Provjerite je li USB kabel ispravno spojen na uređaj.",
    "connect_fail_be44da45": "Provjerite je li uređaj priključen.",
    "connect_fail_81f19800": "U ovoj verziji može se istovremeno povezati samo jedan uređaj. Povezivanje ovog uređaja dovesti će do odspajanja prijašnjeg.",
    "connect_fail_a2244e18": "Provjerite podržava li vaše računalo Bluetooth 4,0 i ako je Bluetooth već uključen.",
    "connect_fail_2ff4c830": "Provjerite je li uređaj priključen.",
    "connect_fail_f516f160": "U ovoj verziji može se istovremeno povezati samo jedan uređaj. Povezivanje ovog uređaja dovesti će do odspajanja prijašnjeg.",
    "upload_fail_440e4ba6": "Molimo pregledajte blokove kodiranja ili kôd za ovaj uređaj. Pobrinite se da svi podaci, parametri i programiranje logika su točni.",
    "upload_fail_24d8e745": "Provjerite je li uređaj ispravno spojen. Možete ponovno pokrenuti uređaj i ponovno ga povezati.",
    "upload_fail_c52d223b": "Molimo provjerite je li firmware dobro radi. Možete ažurirati firmware ili vratiti na tvorničke postavke, a zatim pokušajte ponovno.",
    "firmware_success_70e9b6c0": "Za bolje iskustvo, molimo ponovno pokrenite uređaj i ponovno ga spojite.",
    "firmware_fail_9b5aae92": "Provjerite je li uređaj ispravno spojen. Ponovno pokrenite uređaj, ponovno ga povežite, a zatim ponovno pokušajte ažurirati firmver.",
    "firmware_fail_9a92af14": "Ovaj uređaj ne podržava ažuriranja firmwarea putem Bluetooth prilagodnika ili drugih načina.",
    "BLOCK_1570879365614_LED_ANIMATION_0": "duga",
    "BLOCK_1570879365614_LED_ANIMATION_1": "spindrift",
    "BLOCK_1570879365614_LED_ANIMATION_2": "meteor(plavo)",
    "BLOCK_1570879365614_LED_ANIMATION_3": "meteor(zeleno)",
    "BLOCK_1570879365614_LED_ANIMATION_4": "helijski bljesak(crveno)",
    "BLOCK_1570879365614_LED_ANIMATION_5": "helijski bljesak(narančasto)",
    "BLOCK_1570879365614_LED_ANIMATION_6": "svitac",
    "BLOCK_1570879365614": "prikazuj LED animaciju [LED_animation] dok nije gotova",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_0": "duga",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_1": "spindrift",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_2": "meteor",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_3": "svitac",
    "haloboard_show_ring_effect": "prikazuj LED animaciju [LED_animation] dok nije gotova",
    "haloboard_show_ring_color": "prikaži [ledRing]",
    "haloboard_show_rotation_color": "Pokazati [ledRing] Nakon [rotate] Rotirajući [led_number] Leds",
    "haloboard_show_all_leds": "sve LEDice svijetle u boji [color_1]",
    "haloboard_show_all_leds_with_lightness": "sve LEDice svijetle u boji [color_1], intenzitet [lightness]%",
    "haloboard_off_all_leds": "isključi sve LEDice",
    "haloboard_show_all_leds_with_rgb": "upali sve LEDice u boji R[r] G[g] B[b]",
    "haloboard_show_single_led_with_rgb": "upali LEDicu [led_id] u boji R[r] G[g] B[b]",
    "haloboard_off_single_led": "ugasi LEDicu [led_id]",
    "haloboard_show_percentage": "LED prsten prikazuje [percentage] %",
    "E_1783_n": "Rasvjeta",
    "haloboard_detect_button_pressed": "dugme je pritisnuto?",
    "haloboard_detect_volume": "glasnoća mikrofona",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_0": "0",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_1": "1",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_2": "2",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_3": "3",
    "haloboard_detect_touch": "touch sensor [touchpad_number] is touched?",
    "haloboard_detect_touch_value": "touch sensor [touchpad_number] touch value",
    "BLOCK_1552905879755_SENSITIVITY_0": "high",
    "BLOCK_1552905879755_SENSITIVITY_1": "srednje",
    "BLOCK_1552905879755_SENSITIVITY_2": "low",
    "BLOCK_1552905879755": "set touch sensor [touchpad_number] sensitivity to[sensitivity]",
    "HALOBOARD_DETECT_TILT_1_TILT_0": "tilt left",
    "HALOBOARD_DETECT_TILT_1_TILT_1": "tilt right",
    "HALOBOARD_DETECT_TILT_1_TILT_2": "strelica-gore",
    "HALOBOARD_DETECT_TILT_1_TILT_3": "strelica-dolje",
    "HALOBOARD_DETECT_TILT_1_TILT_4": "LED prsten gore",
    "HALOBOARD_DETECT_TILT_1_TILT_5": "LED prsten dolje",
    "HALOBOARD_DETECT_TILT_1_TILT_6": "rotacija u smjeru kazaljke na satu",
    "HALOBOARD_DETECT_TILT_1_TILT_7": "rotacija u smjeru obrnutom od kazaljke na satu",
    "HALOBOARD_DETECT_TILT_1_TILT_8": "slobodni pad",
    "HALOBOARD_DETECT_TILT_1_TILT_9": "arrow to left",
    "HALOBOARD_DETECT_TILT_1_TILT_10": "arrow to right",
    "HALOBOARD_DETECT_TILT_1_TILT_11": "arrow to up",
    "HALOBOARD_DETECT_TILT_1_TILT_12": "arrow to down",
    "haloboard_detect_tilt_1": "Halocode [tilt] ？",
    "HALOBOARD_DETECT_TILT_TILT_0": "left tilted",
    "HALOBOARD_DETECT_TILT_TILT_1": "right tilted",
    "HALOBOARD_DETECT_TILT_TILT_2": "strelica-gore",
    "HALOBOARD_DETECT_TILT_TILT_3": "strelica-dolje",
    "HALOBOARD_DETECT_TILT_TILT_4": "LED prsten gore",
    "HALOBOARD_DETECT_TILT_TILT_5": "LED prsten dolje",
    "HALOBOARD_DETECT_TILT_TILT_6": "rotacija u smjeru kazaljke na satu",
    "HALOBOARD_DETECT_TILT_TILT_7": "rotacija u smjeru obrnutom od kazaljke na satu",
    "HALOBOARD_DETECT_TILT_TILT_8": "slobodni pad",
    "haloboard_detect_tilt": "Halocode je [tilt] ？",
    "HALOBOARD_DETECT_INCLINE_INCLINE_0": "left tilted",
    "HALOBOARD_DETECT_INCLINE_INCLINE_1": "right tilted",
    "HALOBOARD_DETECT_INCLINE_INCLINE_2": "forward tilted",
    "HALOBOARD_DETECT_INCLINE_INCLINE_3": "backward tilted",
    "haloboard_detect_incline": "Halocode [incline] angle (°)",
    "haloboard_detect_shaked": "Kad se Halocode trese?",
    "haloboard_detect_shaked_value": "snaga potresa",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_0": "x",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_1": "y",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_2": "z",
    "haloboard_detect_axis_acceleration": "senzor kretanja ubrzanje (m/s²) na [axis] osi",
    "haloboard_detect_axis_gyro": "kružna brzina oko[axis](°/s)",
    "HALOBOARD_DETECT_TILT_DEGREE_ROTATION_0": "nagib°",
    "HALOBOARD_DETECT_TILT_DEGREE_ROTATION_1": "svitak°",
    "haloboard_detect_tilt_degree": "senzor pokreta[rotation] kut(°)",
    "haloboard_detect_rotation_degree": "kut rotacije oko [axis] (°)",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_0": "sve",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_1": "x",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_2": "y",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_3": "z",
    "haloboard_reset_rotation_degree": "resetiranje kuta rotacije oko  [axis]",
    "haloboard_detect_time": "timer (s)",
    "haloboard_reset_time": "Reset timer",
    "E_1784_n": "Osjećajući",
    "haloboard_pin_is_digtial": "pin [pin_number] na visokoj razini?",
    "haloboard_pin_read_digtial": " digital read pin [pin_number]",
    "HALOBOARD_PIN_READ_ANALOG_PIN_NUMBER_0": "2",
    "HALOBOARD_PIN_READ_ANALOG_PIN_NUMBER_1": "3",
    "haloboard_pin_read_analog": "analog read pin [pin_number]",
    "haloboard_pin_write_digtial": " digital write [Digtial_value] na pin [pin_number]",
    "haloboard_pin_write_PWM": "analog write [PWM_value] na pin [pin_number]",
    "haloboard_pin_set_servo": "servo pin [pin_number] vrti se na [ServoRotaryAngle]",
    "halo_pin_play_buzzer_with_frequency": "zujalica [pin_num] svira na frekvenciji od [frequency] na [duration] sek",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_0": "C2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_1": "D2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_2": "E2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_3": "F2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_4": "G2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_5": "A3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_6": "B3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_7": "C3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_8": "D3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_9": "E3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_10": "F3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_11": "G3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_12": "A4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_13": "B4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_14": "C4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_15": "D4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_16": "E4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_17": "F4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_18": "G4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_19": "A5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_20": "B5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_21": "C5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_22": "D5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_23": "E5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_24": "F5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_25": "G5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_26": "A6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_27": "B6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_28": "C6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_29": "D6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_30": "E6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_31": "F6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_32": "G6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_33": "A7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_34": "B7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_35": "C7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_36": "D7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_37": "E7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_38": "F7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_39": "G7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_40": "A8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_41": "B8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_42": "C8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_43": "D8",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_0": "takt jedne četvrtine",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_1": "jedan poluritam",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_2": "jedna osmina takta",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_3": "jedan takt",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_4": "dupli takt",
    "halo_play_buzzer_with_note": "zujalica [pin_num] svira notu [note] za [beat] taktova",
    "cate_74a71a9d": "Pinovi",
    "haloboard_wifi_set": "spoji se na Wi-Fi [ssid] lozinka [wifipassword]",
    "haloboard_wifi_is_connect": "Wi-Fi spojen?",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_LANGUAGE_0": "Kineski",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_LANGUAGE_1": "Engleski",
    "haloboard_wifi_speech_recognition": "prepoznaj [Language] za [Time] sekundi",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_0": "Chinese_standard(pojednostavljeni)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_1": "Chinese_cantonese (tradicionalni)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_2": "Chinese_Taiwan (tradicionalno)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_3": "Engleski",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_4": "Francuski",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_5": "Njemački",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_6": "Talijanski",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_7": "Španjolski",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_8": "Japanese",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_9": "Portuguese",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_10": "Russian",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_11": "Korean",
    "haloboard_wifi_speech_recognition_v2": "prepoznaj [Language] za [Time] sekundi",
    "haloboard_wifi_speech_recognition_word": "rezultat prepoznavanja govora",
    "haloboard_wifi_user_broadcast": "pošalji korisničku poruku u oblaku[message]",
    "haloboard_wifi_user_broadcast_with_value": "pošalji korisničku poruku u oblaku[message] sa vrijednošću [value]",
    "haloboard_wifi_when_user_broadcast": "kada primim korisničku poruku u oblaku [message]",
    "haloboard_wifi_user_broadcast_value": "korisnička poruka u oblaku[message] vrijednost",
    "BLOCK_1543814805990": "暂时不做-当无线网络 [ssid] 密码 [password] 连接时",
    "widget_445594f4": "lokacija",
    "BLOCK_1560701681811_WEATHER_TYPE_0": "najviša temperatura (℃)",
    "BLOCK_1560701681811_WEATHER_TYPE_1": "najniža temperatura (℃)",
    "BLOCK_1560701681811_WEATHER_TYPE_2": "najviša temperatura (℉)",
    "BLOCK_1560701681811_WEATHER_TYPE_3": "najniža temperatura (℉)",
    "BLOCK_1560701681811_WEATHER_TYPE_4": "vrijeme",
    "BLOCK_1560701681811_WEATHER_TYPE_5": "vlaga",
    "BLOCK_1560701681811": "[LOCATION]  [WEATHER_TYPE] ",
    "widget_dcc97542": "lokacija",
    "BLOCK_1560702195139_AQ_TYPE_0": "AQI",
    "BLOCK_1560702195139_AQ_TYPE_1": "PM2.5",
    "BLOCK_1560702195139_AQ_TYPE_2": "PM10",
    "BLOCK_1560702195139_AQ_TYPE_3": "CO",
    "BLOCK_1560702195139_AQ_TYPE_4": "SO₂",
    "BLOCK_1560702195139_AQ_TYPE_5": "NO₂",
    "BLOCK_1560702195139": "kvaliteta zraka [METEOROLOGICAL] [aq_type]",
    "BLOCK_1560702421892_SUN_MOVE_TYPE_0": "izlazak sunca",
    "BLOCK_1560702421892_SUN_MOVE_TYPE_1": "zalazak sunca",
    "BLOCK_1560702421892_TIME_TYPE_0": "vrijeme",
    "BLOCK_1560702421892_TIME_TYPE_1": "sat",
    "BLOCK_1560702421892_TIME_TYPE_2": "minuta",
    "BLOCK_1560702421892": "[LOCATION][sun_move_type][time_type]",
    "BLOCK_1560702536759_FIELDMENU_3_0": "vrijeme",
    "BLOCK_1560702536759_FIELDMENU_3_1": "sat",
    "BLOCK_1560702536759_FIELDMENU_3_2": "minuta",
    "BLOCK_1560702536759_FIELDMENU_3_3": "sekunda",
    "BLOCK_1560702536759": "pristup [widget_1]lokalno vrijeme [fieldMenu_3]",
    "Wi-Fi": "Wi-Fi",
    "haloboard_mesh_create1": "postavljanje LAN-a po imenu[mesh_name]",
    "haloboard_mesh_join1": "pridružite se LAN-u po imenu [mesh_name]",
    "haloboard_mesh_broadcast_message": "emitiranje [message] na LAN",
    "haloboard_mesh_broadcast_message_with_value": "emitiranje [message] na LAN-u s vrijednošću [value]",
    "haloboard_mesh_when_received_message": "pri primitku emitiranja LAN-a [message]",
    "haloboard_mesh_get_value": " LAN poruka [message] primljene vrijednosti",
    "BLOCK_1554191633131": "暂时不做 - 局域网是否已连接？",
    "mesh": "LAN",
    "haloboard_when_launch": "[ICON] kad se Halocode pokrene",
    "haloboard_when_button_pressed": "[ICON] dugme je pritisnuto",
    "haloboard_when_shaked": "[ICON] kad se Halocode trese",
    "HALOBOARD_WHEN_TILT_TILT_0": "strelica-gore",
    "HALOBOARD_WHEN_TILT_TILT_1": "strelica-dolje",
    "HALOBOARD_WHEN_TILT_TILT_2": "lijevo-nagnut",
    "HALOBOARD_WHEN_TILT_TILT_3": "desno-nagnut",
    "HALOBOARD_WHEN_TILT_TILT_4": "rotacija u smjeru kazaljke na satu",
    "HALOBOARD_WHEN_TILT_TILT_5": "rotacija u smjeru obrnutom od kazaljke na satu",
    "HALOBOARD_WHEN_TILT_TILT_6": "slobodni pad",
    "haloboard_when_tilt": "[ICON] kada je Halocode [tilt]",
    "HALOBOARD_WHEN_TILT_1_TILT_0": "strelica-gore",
    "HALOBOARD_WHEN_TILT_1_TILT_1": "strelica-dolje",
    "HALOBOARD_WHEN_TILT_1_TILT_2": "lijevo-nagnut",
    "HALOBOARD_WHEN_TILT_1_TILT_3": "desno-nagnut",
    "HALOBOARD_WHEN_TILT_1_TILT_4": "rotacija u smjeru kazaljke na satu",
    "HALOBOARD_WHEN_TILT_1_TILT_5": "rotacija u smjeru obrnutom od kazaljke na satu",
    "HALOBOARD_WHEN_TILT_1_TILT_6": "slobodni pad",
    "HALOBOARD_WHEN_TILT_1_TILT_7": "arrow to left",
    "HALOBOARD_WHEN_TILT_1_TILT_8": "arrow to right",
    "HALOBOARD_WHEN_TILT_1_TILT_9": "arrow to up",
    "HALOBOARD_WHEN_TILT_1_TILT_10": "arrow to down",
    "haloboard_when_tilt_1": "[ICON] kada je Halocode [tilt]",
    "HALOBOARD_WHEN_TILT_2_TILT_0": "arrow-up",
    "HALOBOARD_WHEN_TILT_2_TILT_1": "arrow-down",
    "HALOBOARD_WHEN_TILT_2_TILT_2": "left-tilted",
    "HALOBOARD_WHEN_TILT_2_TILT_3": "right-tilted",
    "HALOBOARD_WHEN_TILT_2_TILT_4": "clockwise rotates",
    "HALOBOARD_WHEN_TILT_2_TILT_5": "anticlockwise rotates",
    "HALOBOARD_WHEN_TILT_2_TILT_6": "freefall",
    "HALOBOARD_WHEN_TILT_2_TILT_7": "arrow to left",
    "HALOBOARD_WHEN_TILT_2_TILT_8": "arrow to right",
    "HALOBOARD_WHEN_TILT_2_TILT_9": "arrow to up",
    "HALOBOARD_WHEN_TILT_2_TILT_10": "arrow to down",
    "haloboard_when_tilt_2": "[ICON] when Halocode is [tilt]",
    "haloboard_when_touched": "[ICON] when touch sensor [touchpad_number] is touched",
    "HALOBOARD_WHEN_GREATER_THAN_CATEGORY_0": "Timer",
    "HALOBOARD_WHEN_GREATER_THAN_CATEGORY_1": "glasnoća mikrofona",
    "haloboard_when_greater_than": "[ICON] kada je [category]>[value]",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_0": "tajmer",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_1": "glasnoća mikrofona",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_2": "snaga potresa",
    "haloboard_when_greater_than_1": "[ICON] when [category] ＞ [value]",
    "e_509_c_events_b_18280": "kada Halocode [tilt]",
    "e_509_c_events_b_18281": "kada je pin [touchpad_number] dotaknut",
    "e_509_c_1410_b_18249": "sve LEDice svijetle u boji [color_1]",
    "BLOCK_1543754866399": "pin zujalice [pin] svira zvuk na frekvenciji [frequency] HZ za [duration] sekundi",
    "BLOCK_1543818559542_TEMPO_4": "dupli takt",
    "CHOOSE_CITY": "Grad",
    "METEOROLOGICAL": "Grad",
    "firmware_versions": "Verzija firmwarea:",
    "show_mode": "Current Mode:",
    "wifi_link_status": "Wi-Fi Connection:",
    "bluetooth_address": "Bluetooth Address:",
    "language_recognition_results": "Speech Recognition Result:",
    "mac_address": "MAC Address:",
    "prompt_message": "Halocode not fully started may lead to inaccurate readouts. Please wait seconds and try again later.",
    "device_state": "Device Status"
};