export default {
    "haloboard": "Halocode",
    "extensionName": "Halocode",
    "extensionDescription": "Halocode è un computer su singola scheda con Wi-Fi integrato",
    "firmwares_version_9c2fcf2b": "Ultimo firmware",
    "UPDATE_FIRMWARE": "Aggiornamento del firmware",
    "settings_717e2676": "Controllo dello stato",
    "connect_fail_418dd2b0": "Assicurarsi che il cavo USB sia collegato correttamente al dispositivo.",
    "connect_fail_be44da45": "Assicurarsi che il dispositivo da collegare sia acceso.",
    "connect_fail_81f19800": "Solo un dispositivo può essere collegato alla volta in questa versione. Quindi, il collegamento di questo dispositivo porterà alla disconnessione di quella precedente.",
    "connect_fail_a2244e18": "Assicurarsi che il computer supporti Bluetooth 4,0 e Bluetooth già attivati.",
    "connect_fail_2ff4c830": "Assicurarsi che il dispositivo da collegare sia acceso.",
    "connect_fail_f516f160": "Solo un dispositivo può essere collegato alla volta in questa versione. Quindi, il collegamento di questo dispositivo porterà alla disconnessione di quella precedente.",
    "upload_fail_440e4ba6": "Si prega di esaminare i blocchi di codifica o il codice per questo dispositivo. Assicurarsi che tutti i dati, i parametri e la logica di programmazione siano corretti.",
    "upload_fail_24d8e745": "Assicurati che il dispositivo sia collegato correttamente. Puoi riavviare il dispositivo e collegarlo nuovamente.",
    "upload_fail_c52d223b": "Assicuri prego che il firmware funzioni bene. È possibile aggiornare il firmware o ripristinare le impostazioni di fabbrica e riprovare.",
    "firmware_success_70e9b6c0": "Per un'esperienza migliore, riavviare il dispositivo e collegarlo nuovamente.",
    "firmware_fail_9b5aae92": "Assicurarsi che il dispositivo sia collegato correttamente. Riavviare il dispositivo, collegarlo di nuovo e riprovare ad aggiornare il firmware.",
    "firmware_fail_9a92af14": "Questo dispositivo non supporta gli aggiornamenti del firmware tramite adattatore Bluetooth o altri modi.",
    "BLOCK_1570879365614_LED_ANIMATION_0": "arcobaleno",
    "BLOCK_1570879365614_LED_ANIMATION_1": "spindrift",
    "BLOCK_1570879365614_LED_ANIMATION_2": "meteor(blu)",
    "BLOCK_1570879365614_LED_ANIMATION_3": "meteor (verde)",
    "BLOCK_1570879365614_LED_ANIMATION_4": "flash dell'elio (rosso)",
    "BLOCK_1570879365614_LED_ANIMATION_5": "flash dell'elio (arancio)",
    "BLOCK_1570879365614_LED_ANIMATION_6": "firefly",
    "BLOCK_1570879365614": "riproduci animazione LED [LED_animation] e attendi completamento",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_0": "arcobaleno",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_1": "spindrift",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_2": "meteora",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_3": "firefly",
    "haloboard_show_ring_effect": "animazione LED del gioco  [LED_animation] e attendi la fine",
    "haloboard_show_ring_color": "mostra [ledRing]",
    "haloboard_show_rotation_color": "visualizza [ledRing] rotante [rotate] dopo [led_number] LEDs",
    "haloboard_show_all_leds": "tutti i LED si accendono [color_1]",
    "haloboard_show_all_leds_with_lightness": "tutti i LED si accendono  [color_1] Luminosità [lightness] %",
    "haloboard_off_all_leds": "spegni tutti i LED",
    "haloboard_show_all_leds_with_rgb": "accendi tutti i LED con colore R [r]G [g]B [b]",
    "haloboard_show_single_led_with_rgb": "accendi il LED [led_id] con il colore R [r] G [g] B [b]",
    "haloboard_off_single_led": "spegni il LED [led_id]",
    "haloboard_show_percentage": "mostra anello LED [percentage]%",
    "E_1783_n": "Illuminazione",
    "haloboard_detect_button_pressed": "pulsante è premuto?",
    "haloboard_detect_volume": "livello audio microfono",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_0": "0",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_1": "1",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_2": "2",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_3": "3",
    "haloboard_detect_touch": "touch sensor [touchpad_number] is touched?",
    "haloboard_detect_touch_value": "touch sensor [touchpad_number] touch value",
    "BLOCK_1552905879755_SENSITIVITY_0": "high",
    "BLOCK_1552905879755_SENSITIVITY_1": "medio",
    "BLOCK_1552905879755_SENSITIVITY_2": "low",
    "BLOCK_1552905879755": "set touch sensor [touchpad_number] sensitivity to[sensitivity]",
    "HALOBOARD_DETECT_TILT_1_TILT_0": "inclinazione a sinistra",
    "HALOBOARD_DETECT_TILT_1_TILT_1": "inclinazione a destra",
    "HALOBOARD_DETECT_TILT_1_TILT_2": "freccia su",
    "HALOBOARD_DETECT_TILT_1_TILT_3": "freccia in giù",
    "HALOBOARD_DETECT_TILT_1_TILT_4": "LED anello su",
    "HALOBOARD_DETECT_TILT_1_TILT_5": "Anello LED verso il basso",
    "HALOBOARD_DETECT_TILT_1_TILT_6": "ruota in senso orario",
    "HALOBOARD_DETECT_TILT_1_TILT_7": "ruota in senso antiorario",
    "HALOBOARD_DETECT_TILT_1_TILT_8": "caduta libera",
    "HALOBOARD_DETECT_TILT_1_TILT_9": "freccia a sinistra",
    "HALOBOARD_DETECT_TILT_1_TILT_10": "freccia a destra",
    "HALOBOARD_DETECT_TILT_1_TILT_11": "freccia verso l'alto",
    "HALOBOARD_DETECT_TILT_1_TILT_12": "freccia verso il basso",
    "haloboard_detect_tilt_1": "Halocode [tilt] ？",
    "HALOBOARD_DETECT_TILT_TILT_0": "inclinato a sinistra",
    "HALOBOARD_DETECT_TILT_TILT_1": "inclinato a destra",
    "HALOBOARD_DETECT_TILT_TILT_2": "freccia su",
    "HALOBOARD_DETECT_TILT_TILT_3": "freccia in giù",
    "HALOBOARD_DETECT_TILT_TILT_4": "LED anello su",
    "HALOBOARD_DETECT_TILT_TILT_5": "Anello LED verso il basso",
    "HALOBOARD_DETECT_TILT_TILT_6": "ruota in senso orario",
    "HALOBOARD_DETECT_TILT_TILT_7": "ruota in senso antiorario",
    "HALOBOARD_DETECT_TILT_TILT_8": "caduta libera",
    "haloboard_detect_tilt": "Halocode è [tilt] ？",
    "HALOBOARD_DETECT_INCLINE_INCLINE_0": "inclinato a sinistra",
    "HALOBOARD_DETECT_INCLINE_INCLINE_1": "inclinato a destra",
    "HALOBOARD_DETECT_INCLINE_INCLINE_2": "inclinato in avanti",
    "HALOBOARD_DETECT_INCLINE_INCLINE_3": "inclinato all'indietro",
    "haloboard_detect_incline": "Halocode [incline] angolo (°)",
    "haloboard_detect_shaked": "Halocode viene agitato?",
    "haloboard_detect_shaked_value": "forza di agitazione",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_0": "x",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_1": "y",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_2": "z",
    "haloboard_detect_axis_acceleration": "accelerazione sensore di movimento asse[axis] (m/s ²)",
    "haloboard_detect_axis_gyro": "velocità angolare attorno a[axis](°/s)",
    "HALOBOARD_DETECT_TILT_DEGREE_ROTATION_0": "beccheggio°",
    "HALOBOARD_DETECT_TILT_DEGREE_ROTATION_1": "rollio°",
    "haloboard_detect_tilt_degree": "posizione(°) del sensore di movimento [rotation]",
    "haloboard_detect_rotation_degree": "angolo di rotazione attorno a [axis] (°)",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_0": "all",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_1": "x",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_2": "y",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_3": "z",
    "haloboard_reset_rotation_degree": "reimposta angolo di rotazione attorno a [axis]",
    "haloboard_detect_time": "timer (s)",
    "haloboard_reset_time": "Reset timer",
    "E_1784_n": "Rilevamento",
    "haloboard_pin_is_digtial": "pin [pin_number]è a livello logico alto?",
    "haloboard_pin_read_digtial": " lettura del pin digitale [pin_number]",
    "HALOBOARD_PIN_READ_ANALOG_PIN_NUMBER_0": "2",
    "HALOBOARD_PIN_READ_ANALOG_PIN_NUMBER_1": "3",
    "haloboard_pin_read_analog": "lettura del pin analogico [pin_number]",
    "haloboard_pin_write_digtial": " scrittura digitale [Digtial_value] al pin [pin_number]",
    "haloboard_pin_write_PWM": "scrittura analogica  [PWM_value] al pin [pin_number]",
    "haloboard_pin_set_servo": "ruota il pin servo [pin_number] di [ServoRotaryAngle]",
    "halo_pin_play_buzzer_with_frequency": "pin altoparlante [pin_num] riproduce[frequency]Hz per [duration] sec",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_0": "C2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_1": "D2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_2": "E2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_3": "F2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_4": "G2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_5": "A3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_6": "B3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_7": "C3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_8": "D3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_9": "E3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_10": "F3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_11": "G3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_12": "A4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_13": "B4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_14": "C4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_15": "D4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_16": "E4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_17": "F4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_18": "G4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_19": "A5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_20": "B5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_21": "C5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_22": "D5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_23": "E5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_24": "F5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_25": "G5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_26": "A6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_27": "B6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_28": "C6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_29": "D6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_30": "E6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_31": "F6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_32": "G6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_33": "A7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_34": "B7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_35": "C7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_36": "D7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_37": "E7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_38": "F7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_39": "G7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_40": "A8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_41": "B8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_42": "C8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_43": "D8",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_0": "un quarto di battuta",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_1": "mezza battuta",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_2": "un ottavo di battuta",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_3": "una battuta",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_4": "doppia battuta",
    "halo_play_buzzer_with_note": "pin altoparlante [pin_num]  riproduce nota [note] per [beat] battiti",
    "cate_74a71a9d": "Pins",
    "haloboard_wifi_set": "connettersi al Wi-Fi [ssid] password [wifipassword]",
    "haloboard_wifi_is_connect": "Wi-Fi collegato?",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_LANGUAGE_0": "Cinese",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_LANGUAGE_1": "Inglese",
    "haloboard_wifi_speech_recognition": "riconosci[Language] per[Time] secondi",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_0": "Cinese_standard(semplificato)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_1": "Cinese_cantonese (tradizionale)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_2": "Cinese_Taiwan (tradizionale)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_3": "Inglese",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_4": "Francese",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_5": "Tedesco",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_6": "Italiano",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_7": "Spagnolo",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_8": "Japanese",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_9": "Portuguese",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_10": "Russian",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_11": "Korean",
    "haloboard_wifi_speech_recognition_v2": "riconosci[Language] per[Time] secondi",
    "haloboard_wifi_speech_recognition_word": "risultato riconoscimento vocale",
    "haloboard_wifi_user_broadcast": "invia messaggio utente cloud[message]",
    "haloboard_wifi_user_broadcast_with_value": "invia messaggio utente cloud[message] con valore[value]",
    "haloboard_wifi_when_user_broadcast": "quando ricevo messaggio cloud utente [message]",
    "haloboard_wifi_user_broadcast_value": "valore messaggio cloud utente[message]",
    "BLOCK_1543814805990": "E s.T. . . . . . . . . . . . . . . . . . . . . . . . . . . . [ssid] , quindi il numero di persone [password] , quindi il numero di siè ad esempio,",
    "widget_445594f4": "posizione",
    "BLOCK_1560701681811_WEATHER_TYPE_0": "temperatura più alta(°C)",
    "BLOCK_1560701681811_WEATHER_TYPE_1": "temperatura più bassa(°C)",
    "BLOCK_1560701681811_WEATHER_TYPE_2": "temperatura più alta (°F)",
    "BLOCK_1560701681811_WEATHER_TYPE_3": "temperatura più bassa(°F)",
    "BLOCK_1560701681811_WEATHER_TYPE_4": "meteo",
    "BLOCK_1560701681811_WEATHER_TYPE_5": "umidità",
    "BLOCK_1560701681811": "[LOCATION] [WEATHER_TYPE] ",
    "widget_dcc97542": "posizione",
    "BLOCK_1560702195139_AQ_TYPE_0": "AQI",
    "BLOCK_1560702195139_AQ_TYPE_1": "PM2.5",
    "BLOCK_1560702195139_AQ_TYPE_2": "PM10",
    "BLOCK_1560702195139_AQ_TYPE_3": "CO",
    "BLOCK_1560702195139_AQ_TYPE_4": "SO₂",
    "BLOCK_1560702195139_AQ_TYPE_5": "NO₂",
    "BLOCK_1560702195139": "qualità dell'aria [METEOROLOGICAL] [aq_type]",
    "BLOCK_1560702421892_SUN_MOVE_TYPE_0": "alba",
    "BLOCK_1560702421892_SUN_MOVE_TYPE_1": "tramonto",
    "BLOCK_1560702421892_TIME_TYPE_0": "ora",
    "BLOCK_1560702421892_TIME_TYPE_1": "ora",
    "BLOCK_1560702421892_TIME_TYPE_2": "minuto",
    "BLOCK_1560702421892": "[LOCATION] [sun_move_type] [time_type]",
    "BLOCK_1560702536759_FIELDMENU_3_0": "ora",
    "BLOCK_1560702536759_FIELDMENU_3_1": "ora",
    "BLOCK_1560702536759_FIELDMENU_3_2": "minuto",
    "BLOCK_1560702536759_FIELDMENU_3_3": "secondo",
    "BLOCK_1560702536759": "accedi [widget_1]ora locale [fieldMenu_3]",
    "Wi-Fi": "Wi-Fi",
    "haloboard_mesh_create1": "configura LAN con nome[mesh_name]",
    "haloboard_mesh_join1": "collegati alla LAN denominata [mesh_name]",
    "haloboard_mesh_broadcast_message": "trasmetti[message] su LAN",
    "haloboard_mesh_broadcast_message_with_value": "trasmetti [message] su LAN con valore [value]",
    "haloboard_mesh_when_received_message": "quando si riceve su LAN il messaggio[message]",
    "haloboard_mesh_get_value": "valore del messaggio ricevuto su LAN [message]",
    "BLOCK_1554191633131": "\" \" \" \" \" \" \" \" \" \" \" \" ? . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
    "mesh": "LAN",
    "haloboard_when_launch": "[ICON] Quando Halocode si avvia",
    "haloboard_when_button_pressed": "[ICON] Quando pulsante è premuto",
    "haloboard_when_shaked": "[ICON] quando Halocode viene scosso",
    "HALOBOARD_WHEN_TILT_TILT_0": "freccia-in su",
    "HALOBOARD_WHEN_TILT_TILT_1": "freccia-giù",
    "HALOBOARD_WHEN_TILT_TILT_2": "inclinato-sinistra",
    "HALOBOARD_WHEN_TILT_TILT_3": "inclinato-destra",
    "HALOBOARD_WHEN_TILT_TILT_4": "ruota in senso orario",
    "HALOBOARD_WHEN_TILT_TILT_5": "ruota in senso antiorario",
    "HALOBOARD_WHEN_TILT_TILT_6": "caduta libera",
    "haloboard_when_tilt": "[ICON] quando Halocode è [tilt]",
    "HALOBOARD_WHEN_TILT_1_TILT_0": "freccia su",
    "HALOBOARD_WHEN_TILT_1_TILT_1": "freccia giù",
    "HALOBOARD_WHEN_TILT_1_TILT_2": "inclinato-sinistra",
    "HALOBOARD_WHEN_TILT_1_TILT_3": "inclinato-destra",
    "HALOBOARD_WHEN_TILT_1_TILT_4": "ruota in senso orario",
    "HALOBOARD_WHEN_TILT_1_TILT_5": "ruota in senso antiorario",
    "HALOBOARD_WHEN_TILT_1_TILT_6": "caduta libera",
    "HALOBOARD_WHEN_TILT_1_TILT_7": "freccia a sinistra",
    "HALOBOARD_WHEN_TILT_1_TILT_8": "freccia a destra",
    "HALOBOARD_WHEN_TILT_1_TILT_9": "freccia verso l'alto",
    "HALOBOARD_WHEN_TILT_1_TILT_10": "freccia verso il basso",
    "haloboard_when_tilt_1": "[ICON] quando Halocode è [tilt]",
    "HALOBOARD_WHEN_TILT_2_TILT_0": "arrow-up",
    "HALOBOARD_WHEN_TILT_2_TILT_1": "arrow-down",
    "HALOBOARD_WHEN_TILT_2_TILT_2": "left-tilted",
    "HALOBOARD_WHEN_TILT_2_TILT_3": "right-tilted",
    "HALOBOARD_WHEN_TILT_2_TILT_4": "clockwise rotates",
    "HALOBOARD_WHEN_TILT_2_TILT_5": "anticlockwise rotates",
    "HALOBOARD_WHEN_TILT_2_TILT_6": "freefall",
    "HALOBOARD_WHEN_TILT_2_TILT_7": "arrow to left",
    "HALOBOARD_WHEN_TILT_2_TILT_8": "arrow to right",
    "HALOBOARD_WHEN_TILT_2_TILT_9": "arrow to up",
    "HALOBOARD_WHEN_TILT_2_TILT_10": "arrow to down",
    "haloboard_when_tilt_2": "[ICON] when Halocode is [tilt]",
    "haloboard_when_touched": "[ICON] when touch sensor [touchpad_number] is touched",
    "HALOBOARD_WHEN_GREATER_THAN_CATEGORY_0": "Timer",
    "HALOBOARD_WHEN_GREATER_THAN_CATEGORY_1": "livello audio microfono",
    "haloboard_when_greater_than": "[ICON] quando [category] >[value]",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_0": "timer",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_1": "livello audio microfono",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_2": "forza di agitazione",
    "haloboard_when_greater_than_1": "[ICON] quando [category] ＞ [value]",
    "e_509_c_events_b_18280": "quando Halocode [tilt]",
    "e_509_c_events_b_18281": "quando il pin [touchpad_number] è toccato",
    "e_509_c_1410_b_18249": "tutti i LED si accendono [color_1]",
    "BLOCK_1543754866399": "altoparlante [pin] riproduce la frequenza di [frequency] per [duration] sec",
    "BLOCK_1543818559542_TEMPO_4": "doppia battuta",
    "CHOOSE_CITY": "Città",
    "METEOROLOGICAL": "Città",
    "firmware_versions": "Versione Firmware:",
    "show_mode": "Modalità Corrente:",
    "wifi_link_status": "Connessione Wi-Fi:",
    "bluetooth_address": "Indirizzo Bluetooth:",
    "language_recognition_results": "Risultato riconoscimento vocale:",
    "mac_address": "Indirizzo MAC:",
    "prompt_message": "Halocode non completamente avviato può portare a letture imprecise. Attendere alcuni secondi e riprovare più tardi.",
    "device_state": "Stato del dispositivo"
};