export default {
    "haloboard": "Halocode",
    "extensionName": "Halocode",
    "extensionDescription": "Uniwersalny komputer Halokodowy z wbudowanym Wi-Fi",
    "firmwares_version_9c2fcf2b": "Najnowszy firmware",
    "UPDATE_FIRMWARE": "Aktualizacja oprogramowania sprzętowego",
    "settings_717e2676": "Sprawdzanie statusu",
    "connect_fail_418dd2b0": "Upewnij się, że przewód USB jest prawidłowo podłączony do urządzenia.",
    "connect_fail_be44da45": "Upewnij się, że urządzenie, które ma być podłączone, jest włączone.",
    "connect_fail_81f19800": "W tej wersji można podłączyć tylko jedno urządzenie naraz. Tak więc podłączenie tego urządzenia doprowadzi do odłączenia poprzedniego.",
    "connect_fail_a2244e18": "Upewnij się, że komputer obsługuje technologię Bluetooth 4,0 i funkcja Bluetooth jest już włączona.",
    "connect_fail_2ff4c830": "Upewnij się, że urządzenie, które ma być podłączone, jest włączone.",
    "connect_fail_f516f160": "W tej wersji można podłączyć tylko jedno urządzenie naraz. Tak więc podłączenie tego urządzenia doprowadzi do odłączenia poprzedniego.",
    "upload_fail_440e4ba6": "Proszę przejrzeć bloki kodujące lub kod dla tego urządzenia. Upewnij się, że wszystkie dane, parametry i logika programowania są poprawne.",
    "upload_fail_24d8e745": "Upewnij się, że urządzenie jest prawidłowo podłączone. Możesz ponownie uruchomić urządzenie i podłączyć je ponownie.",
    "upload_fail_c52d223b": "Upewnij się, że firmware działa dobrze. Możesz zaktualizować firmware lub przywrócić ustawienia fabryczne i spróbować ponownie.",
    "firmware_success_70e9b6c0": "Aby uzyskać lepsze wrażenia, należy ponownie uruchomić urządzenie i podłączyć je ponownie.",
    "firmware_fail_9b5aae92": "Upewnij się, że urządzenie jest prawidłowo podłączone. Ponownie uruchom urządzenie, podłącz je ponownie, a następnie spróbuj ponownie zaktualizować oprogramowanie układowe.",
    "firmware_fail_9a92af14": "To urządzenie nie obsługuje aktualizacji oprogramowania układowego za pośrednictwem adaptera Bluetooth lub innych sposobów.",
    "BLOCK_1570879365614_LED_ANIMATION_0": "Rainbow",
    "BLOCK_1570879365614_LED_ANIMATION_1": "Spindrift",
    "BLOCK_1570879365614_LED_ANIMATION_2": "meteor(niebieski)",
    "BLOCK_1570879365614_LED_ANIMATION_3": "meteor (zielony)",
    "BLOCK_1570879365614_LED_ANIMATION_4": "helium flash(red)",
    "BLOCK_1570879365614_LED_ANIMATION_5": "helium flash(orange)",
    "BLOCK_1570879365614_LED_ANIMATION_6": "Firefly",
    "BLOCK_1570879365614": "zagraj animację LED [LED_animation] aż się skończy",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_0": "Rainbow",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_1": "Spindrift",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_2": "Meteor",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_3": "Firefly",
    "haloboard_show_ring_effect": "Odtwórz animację LED  [LED_animation] do zrobienia",
    "haloboard_show_ring_color": "Pokaż [ledRing]",
    "haloboard_show_rotation_color": "Pokaż [ledRing] Po [rotate] Obrotowa [led_number] Diody led",
    "haloboard_show_all_leds": "Wszystkie diody LED zapalają się  [color_1]",
    "haloboard_show_all_leds_with_lightness": "Wszystkie diody LED zapalają się  [color_1]Jasność [lightness] %",
    "haloboard_off_all_leds": "świeci wszystkie diody LED",
    "haloboard_show_all_leds_with_rgb": "zaświeć wszystkie LED-y w kolorze R [r]G [g]B [b]",
    "haloboard_show_single_led_with_rgb": "zapala się DIODa LED [led_id] z kolorem R [r] G [g] B [b]",
    "haloboard_off_single_led": "światło wyłączone LED [led_id]",
    "haloboard_show_percentage": "Pokazy pierścieniowe LED [percentage]  %",
    "E_1783_n": "Oświetlenie",
    "haloboard_detect_button_pressed": "naciśnięciu przycisku?",
    "haloboard_detect_volume": "głośność mikrofonu",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_0": "0",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_1": "1",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_2": "2",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_3": "3",
    "haloboard_detect_touch": "touch sensor [touchpad_number] is touched?",
    "haloboard_detect_touch_value": "touch sensor [touchpad_number] touch value",
    "BLOCK_1552905879755_SENSITIVITY_0": "wysoka",
    "BLOCK_1552905879755_SENSITIVITY_1": "Średni",
    "BLOCK_1552905879755_SENSITIVITY_2": "niska",
    "BLOCK_1552905879755": "set touch sensor [touchpad_number] sensitivity to[sensitivity]",
    "HALOBOARD_DETECT_TILT_1_TILT_0": "tilt left",
    "HALOBOARD_DETECT_TILT_1_TILT_1": "tilt right",
    "HALOBOARD_DETECT_TILT_1_TILT_2": "Strzałka w górę",
    "HALOBOARD_DETECT_TILT_1_TILT_3": "Strzałka w dół",
    "HALOBOARD_DETECT_TILT_1_TILT_4": "Pierścienie LED",
    "HALOBOARD_DETECT_TILT_1_TILT_5": "Pierścień LED w dół",
    "HALOBOARD_DETECT_TILT_1_TILT_6": "obrót z ruchem wskazówek zegara",
    "HALOBOARD_DETECT_TILT_1_TILT_7": "obrót przeciwny do wskazówek zegara",
    "HALOBOARD_DETECT_TILT_1_TILT_8": "swobodne spadanie",
    "HALOBOARD_DETECT_TILT_1_TILT_9": "arrow to left",
    "HALOBOARD_DETECT_TILT_1_TILT_10": "arrow to right",
    "HALOBOARD_DETECT_TILT_1_TILT_11": "arrow to up",
    "HALOBOARD_DETECT_TILT_1_TILT_12": "arrow to down",
    "haloboard_detect_tilt_1": "Halocode [tilt] ？",
    "HALOBOARD_DETECT_TILT_TILT_0": "left tilted",
    "HALOBOARD_DETECT_TILT_TILT_1": "right tilted",
    "HALOBOARD_DETECT_TILT_TILT_2": "Strzałka w górę",
    "HALOBOARD_DETECT_TILT_TILT_3": "Strzałka w dół",
    "HALOBOARD_DETECT_TILT_TILT_4": "Pierścienie LED",
    "HALOBOARD_DETECT_TILT_TILT_5": "Pierścień LED w dół",
    "HALOBOARD_DETECT_TILT_TILT_6": "obrót z ruchem wskazówek zegara",
    "HALOBOARD_DETECT_TILT_TILT_7": "anti clockwise rotates",
    "HALOBOARD_DETECT_TILT_TILT_8": "swobodne spadanie",
    "haloboard_detect_tilt": "Halocode jest [tilt] ？",
    "HALOBOARD_DETECT_INCLINE_INCLINE_0": "left tilted",
    "HALOBOARD_DETECT_INCLINE_INCLINE_1": "right tilted",
    "HALOBOARD_DETECT_INCLINE_INCLINE_2": "forward tilted",
    "HALOBOARD_DETECT_INCLINE_INCLINE_3": "backward tilted",
    "haloboard_detect_incline": "Halocode [incline] angle (°)",
    "haloboard_detect_shaked": "Halocode jest wstrząśany?",
    "haloboard_detect_shaked_value": "siła potrząsania",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_0": "x",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_1": "y",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_2": "z",
    "haloboard_detect_axis_acceleration": "przyspieszenie czujnika ruchu (m/s ²)  [axis] Osi",
    "haloboard_detect_axis_gyro": "angular velocity around[axis](°/s)",
    "HALOBOARD_DETECT_TILT_DEGREE_ROTATION_0": "Raster °",
    "HALOBOARD_DETECT_TILT_DEGREE_ROTATION_1": "Rolka °",
    "haloboard_detect_tilt_degree": "motion sensor [rotation] posture(°)",
    "haloboard_detect_rotation_degree": "rotated angle around [axis] (°)",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_0": "wszystkie",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_1": "x",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_2": "y",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_3": "z",
    "haloboard_reset_rotation_degree": "reset rotated angle around  [axis]",
    "haloboard_detect_time": "Timer (s)",
    "haloboard_reset_time": "Zerowanie timera",
    "E_1784_n": "Wykrywania",
    "haloboard_pin_is_digtial": "Pin [pin_number] na wysokim poziomie?",
    "haloboard_pin_read_digtial": " cyfrowy odczytany PIN [pin_number]",
    "HALOBOARD_PIN_READ_ANALOG_PIN_NUMBER_0": "2",
    "HALOBOARD_PIN_READ_ANALOG_PIN_NUMBER_1": "3",
    "haloboard_pin_read_analog": "analogowy odczyt PIN [pin_number]",
    "haloboard_pin_write_digtial": " cyfrowy zapis [Digtial_value] Aby przypiąć [pin_number]",
    "haloboard_pin_write_PWM": "zapis analogowy  [PWM_value] Aby przypiąć [pin_number]",
    "haloboard_pin_set_servo": "Sworzeń SERVO [pin_number] obraca się do [ServoRotaryAngle]",
    "halo_pin_play_buzzer_with_frequency": "Kołek brzęczyk[pin_num] gra z częstotliwością [frequency] HZ dla [duration]Sekund",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_0": "C2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_1": "D2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_2": "E2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_3": "F2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_4": "G2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_5": "A3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_6": "B3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_7": "C3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_8": "D3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_9": "E3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_10": "F3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_11": "G3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_12": "A4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_13": "B4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_14": "C4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_15": "D4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_16": "E4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_17": "F4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_18": "G4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_19": "A5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_20": "B5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_21": "C5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_22": "D5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_23": "E5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_24": "F5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_25": "G5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_26": "A6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_27": "B6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_28": "C6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_29": "D6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_30": "E6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_31": "F6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_32": "G6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_33": "A7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_34": "B7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_35": "C7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_36": "D7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_37": "E7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_38": "F7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_39": "G7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_40": "A8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_41": "B8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_42": "C8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_43": "D8",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_0": "jeden kwartał pokonać",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_1": "jedna połowa Beat",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_2": "jeden ósmy rytm",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_3": "jeden rytm",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_4": "podwójne bity",
    "halo_play_buzzer_with_note": "Kołek brzęczyk [pin_num]  odtworzenia notatki[note] For [beat]Bije",
    "cate_74a71a9d": "Szpilki",
    "haloboard_wifi_set": "Nawiązywanie połączenia z siecią Wi-Fi [ssid] Hasło [wifipassword]",
    "haloboard_wifi_is_connect": "Połączenie z siecią Wi-Fi?",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_LANGUAGE_0": "Chiński",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_LANGUAGE_1": "Angielski",
    "haloboard_wifi_speech_recognition": "Rozpoznać [Language] For [Time] Sekund",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_0": "Chiński_standardowy (uproszczony)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_1": "Chiński_kantonowy (tradycyjny)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_2": "Chiński (tradycyjny)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_3": "Angielski",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_4": "Francuski",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_5": "Niemiecki",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_6": "Włoski",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_7": "Hiszpański",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_8": "Japanese",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_9": "Portuguese",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_10": "Russian",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_11": "Korean",
    "haloboard_wifi_speech_recognition_v2": "Rozpoznać [Language] For [Time] Sekund",
    "haloboard_wifi_speech_recognition_word": "wynik rozpoznawania mowy",
    "haloboard_wifi_user_broadcast": "komunikat emisji chmur użytkowników [message]",
    "haloboard_wifi_user_broadcast_with_value": "komunikat emisji chmur użytkowników [message] o wartości [value]",
    "haloboard_wifi_when_user_broadcast": "podczas odbierania wiadomości w chmurze użytkownika [message]",
    "haloboard_wifi_user_broadcast_value": "wiadomość w chmurze użytkownika [message] wartość odebrana",
    "BLOCK_1543814805990": "暂时不做-当无线网络 [ssid] 密码 [password] 连接时",
    "widget_445594f4": "lokalizacja",
    "BLOCK_1560701681811_WEATHER_TYPE_0": "najwyższa temperatura(℃)",
    "BLOCK_1560701681811_WEATHER_TYPE_1": "najniższa temperatura(℃)",
    "BLOCK_1560701681811_WEATHER_TYPE_2": "najwyższa temperatura (℉)",
    "BLOCK_1560701681811_WEATHER_TYPE_3": "najniższa temperatura (℉)",
    "BLOCK_1560701681811_WEATHER_TYPE_4": "pogoda",
    "BLOCK_1560701681811_WEATHER_TYPE_5": "wilgotność",
    "BLOCK_1560701681811": "[LOCATION]  [WEATHER_TYPE] ",
    "widget_dcc97542": "lokalizacja",
    "BLOCK_1560702195139_AQ_TYPE_0": "AQI",
    "BLOCK_1560702195139_AQ_TYPE_1": "PM2.5",
    "BLOCK_1560702195139_AQ_TYPE_2": "PM10",
    "BLOCK_1560702195139_AQ_TYPE_3": "CO",
    "BLOCK_1560702195139_AQ_TYPE_4": "SO₂",
    "BLOCK_1560702195139_AQ_TYPE_5": "NO₂",
    "BLOCK_1560702195139": "jakość powietrza [METEOROLOGICAL]  [aq_type]",
    "BLOCK_1560702421892_SUN_MOVE_TYPE_0": "wschód słońca",
    "BLOCK_1560702421892_SUN_MOVE_TYPE_1": "zachód słońca",
    "BLOCK_1560702421892_TIME_TYPE_0": "czas",
    "BLOCK_1560702421892_TIME_TYPE_1": "godzina",
    "BLOCK_1560702421892_TIME_TYPE_2": "minuta",
    "BLOCK_1560702421892": "[LOCATION]  [sun_move_type] [time_type]",
    "BLOCK_1560702536759_FIELDMENU_3_0": "czas",
    "BLOCK_1560702536759_FIELDMENU_3_1": "godzina",
    "BLOCK_1560702536759_FIELDMENU_3_2": "minuta",
    "BLOCK_1560702536759_FIELDMENU_3_3": "sekunda",
    "BLOCK_1560702536759": "access [widget_1]local time [fieldMenu_3]",
    "Wi-Fi": "Wi-Fi",
    "haloboard_mesh_create1": "skonfigurować LAN o nazwie[mesh_name]",
    "haloboard_mesh_join1": "Dołącz do sieci LAN o nazwie [mesh_name]",
    "haloboard_mesh_broadcast_message": "Emisji [message] na LAN",
    "haloboard_mesh_broadcast_message_with_value": "Emisji [message] w sieci LAN o wartości [value]",
    "haloboard_mesh_when_received_message": "podczas odbierania transmisji LAN [message]",
    "haloboard_mesh_get_value": " LAN message [message]value received",
    "BLOCK_1554191633131": "暂时不做 - 局域网是否已连接？",
    "mesh": "Lan",
    "haloboard_when_launch": "[ICON] kiedy Halocode uruchomi się",
    "haloboard_when_button_pressed": "[ICON] po naciśnięciu przycisku",
    "haloboard_when_shaked": "[ICON] kiedy Halocode uruchomi się",
    "HALOBOARD_WHEN_TILT_TILT_0": "Strzałka w górę",
    "HALOBOARD_WHEN_TILT_TILT_1": "Strzałka w dół",
    "HALOBOARD_WHEN_TILT_TILT_2": "pochylenie lewe",
    "HALOBOARD_WHEN_TILT_TILT_3": "prawo-Tilted",
    "HALOBOARD_WHEN_TILT_TILT_4": "obrót z ruchem wskazówek zegara",
    "HALOBOARD_WHEN_TILT_TILT_5": "obrót przeciwny do wskazówek zegara",
    "HALOBOARD_WHEN_TILT_TILT_6": "swobodne spadanie",
    "haloboard_when_tilt": "[ICON] kiedy Halocode uruchomi się[tilt]",
    "HALOBOARD_WHEN_TILT_1_TILT_0": "Strzałka w górę",
    "HALOBOARD_WHEN_TILT_1_TILT_1": "Strzałka w dół",
    "HALOBOARD_WHEN_TILT_1_TILT_2": "pochylenie lewe",
    "HALOBOARD_WHEN_TILT_1_TILT_3": "prawo-Tilted",
    "HALOBOARD_WHEN_TILT_1_TILT_4": "obrót z ruchem wskazówek zegara",
    "HALOBOARD_WHEN_TILT_1_TILT_5": "obrót przeciwny do wskazówek zegara",
    "HALOBOARD_WHEN_TILT_1_TILT_6": "swobodne spadanie",
    "HALOBOARD_WHEN_TILT_1_TILT_7": "arrow to left",
    "HALOBOARD_WHEN_TILT_1_TILT_8": "arrow to right",
    "HALOBOARD_WHEN_TILT_1_TILT_9": "arrow to up",
    "HALOBOARD_WHEN_TILT_1_TILT_10": "arrow to down",
    "haloboard_when_tilt_1": "[ICON] kiedy Halocode uruchomi się[tilt]",
    "HALOBOARD_WHEN_TILT_2_TILT_0": "arrow-up",
    "HALOBOARD_WHEN_TILT_2_TILT_1": "arrow-down",
    "HALOBOARD_WHEN_TILT_2_TILT_2": "left-tilted",
    "HALOBOARD_WHEN_TILT_2_TILT_3": "right-tilted",
    "HALOBOARD_WHEN_TILT_2_TILT_4": "clockwise rotates",
    "HALOBOARD_WHEN_TILT_2_TILT_5": "anticlockwise rotates",
    "HALOBOARD_WHEN_TILT_2_TILT_6": "freefall",
    "HALOBOARD_WHEN_TILT_2_TILT_7": "arrow to left",
    "HALOBOARD_WHEN_TILT_2_TILT_8": "arrow to right",
    "HALOBOARD_WHEN_TILT_2_TILT_9": "arrow to up",
    "HALOBOARD_WHEN_TILT_2_TILT_10": "arrow to down",
    "haloboard_when_tilt_2": "[ICON] when Halocode is [tilt]",
    "haloboard_when_touched": "[ICON] when touch sensor [touchpad_number] is touched",
    "HALOBOARD_WHEN_GREATER_THAN_CATEGORY_0": "Timer",
    "HALOBOARD_WHEN_GREATER_THAN_CATEGORY_1": "głośność mikrofonu",
    "haloboard_when_greater_than": "[ICON] Kiedy [category] >[value]",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_0": "timer",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_1": "głośność mikrofonu",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_2": "siła potrząsania",
    "haloboard_when_greater_than_1": "[ICON] when [category] ＞ [value]",
    "e_509_c_events_b_18280": "gdy Halocode [tilt]",
    "e_509_c_events_b_18281": "gdy PIN [touchpad_number] jest dotykany",
    "e_509_c_1410_b_18249": "Wszystkie diody LED zapalają się [color_1]",
    "BLOCK_1543754866399": "PIN brzęczyka [pin] odtwarza dźwięk z częstotliwością [frequency] HZ dla [duration] Sekund",
    "BLOCK_1543818559542_TEMPO_4": "podwójne bicie",
    "CHOOSE_CITY": "Miasto",
    "METEOROLOGICAL": "Miasto",
    "firmware_versions": "Wersja oprogramowania:",
    "show_mode": "Current Mode:",
    "wifi_link_status": "Wi-Fi Connection:",
    "bluetooth_address": "Bluetooth Address:",
    "language_recognition_results": "Speech Recognition Result:",
    "mac_address": "Adres MAC:",
    "prompt_message": "Halocode not fully started may lead to inaccurate readouts. Please wait seconds and try again later.",
    "device_state": "Status urządzenia"
};