export default {
    "haloboard": "Halocode",
    "extensionName": "Halocode",
    "extensionDescription": "Halocode um único computador com Wi-Fi embutido",
    "firmwares_version_9c2fcf2b": "Firmware mais recente",
    "UPDATE_FIRMWARE": "Atualização de firmware",
    "settings_717e2676": "Status Check",
    "connect_fail_418dd2b0": "Certifique-se de que o cabo USB está correctamente ligado ao dispositivo.",
    "connect_fail_be44da45": "Por favor, certifique-se que o dispositivo a ser ligado está ligado.",
    "connect_fail_81f19800": "Apenas um dispositivo pode ser conectado por vez nesta versão. Assim, a conexão deste dispositivo levará à desconexão do anterior.",
    "connect_fail_a2244e18": "Por favor, certifique-se de que o computador suporta Bluetooth 4,0 e Bluetooth já ligado.",
    "connect_fail_2ff4c830": "Por favor, certifique-se que o dispositivo a ser ligado está ligado.",
    "connect_fail_f516f160": "Apenas um dispositivo pode ser conectado por vez nesta versão. Assim, a conexão deste dispositivo levará à desconexão do anterior.",
    "upload_fail_440e4ba6": "Reveja os blocos de codificação ou o código para este dispositivo. Certifique-se de que todos os dados, parâmetros e lógica de programação estão corretos.",
    "upload_fail_24d8e745": "Certifique-se de que o dispositivo está correctamente ligado. Você pode reiniciar o dispositivo e conectá-lo novamente.",
    "upload_fail_c52d223b": "Por favor, certifique-se o firmware funciona bem. Você pode atualizar o firmware ou restaurar as configurações de fábrica e tente novamente.",
    "firmware_success_70e9b6c0": "Para uma melhor experiência, por favor, reinicie o dispositivo e conectá-lo mais uma vez.",
    "firmware_fail_9b5aae92": "Certifique-se de que o dispositivo está correctamente ligado. Reinicie o dispositivo, conectá-lo novamente e, em seguida, tente atualizar o firmware mais uma vez.",
    "firmware_fail_9a92af14": "Este dispositivo não suporta actualizações de firmware através de adaptador Bluetooth ou outras formas.",
    "BLOCK_1570879365614_LED_ANIMATION_0": "Arco-íris",
    "BLOCK_1570879365614_LED_ANIMATION_1": "Spindrift",
    "BLOCK_1570879365614_LED_ANIMATION_2": "meteor(blue)",
    "BLOCK_1570879365614_LED_ANIMATION_3": "meteor (green)",
    "BLOCK_1570879365614_LED_ANIMATION_4": "helium flash(red)",
    "BLOCK_1570879365614_LED_ANIMATION_5": "helium flash(orange)",
    "BLOCK_1570879365614_LED_ANIMATION_6": "Firefly",
    "BLOCK_1570879365614": "play LED animation [LED_animation] until done",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_0": "Arco-íris",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_1": "Spindrift",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_2": "Meteoro",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_3": "Firefly",
    "haloboard_show_ring_effect": "jogar animação LED  [LED_animation] até feito",
    "haloboard_show_ring_color": "Mostrar [ledRing]",
    "haloboard_show_rotation_color": "Mostrar [ledRing] Depois [rotate] Rotativa [led_number] Leds",
    "haloboard_show_all_leds": "todos os LEDs acendem  [color_1]",
    "haloboard_show_all_leds_with_lightness": "todos os LEDs acendem  [color_1]Brilho [lightness] %",
    "haloboard_off_all_leds": "luz fora todos os LEDs",
    "haloboard_show_all_leds_with_rgb": "light up all LEDs with color R [r]G  [g]B [b]",
    "haloboard_show_single_led_with_rgb": "Ilumine acima o diodo emissor de luz [led_id] com cor R [r] G [g] B [b]",
    "haloboard_off_single_led": "luz fora LED [led_id]",
    "haloboard_show_percentage": "Anel LED mostra [percentage]  %",
    "E_1783_n": "Iluminação",
    "haloboard_detect_button_pressed": "botão é pressionado?",
    "haloboard_detect_volume": "microfone LOUDNESS",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_0": "0",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_1": "1",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_2": "2",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_3": "3",
    "haloboard_detect_touch": "touch sensor [touchpad_number] is touched?",
    "haloboard_detect_touch_value": "touch sensor [touchpad_number] touch value",
    "BLOCK_1552905879755_SENSITIVITY_0": "alto",
    "BLOCK_1552905879755_SENSITIVITY_1": "médio",
    "BLOCK_1552905879755_SENSITIVITY_2": "baixo",
    "BLOCK_1552905879755": "set touch sensor [touchpad_number] sensitivity to[sensitivity]",
    "HALOBOARD_DETECT_TILT_1_TILT_0": "tilt left",
    "HALOBOARD_DETECT_TILT_1_TILT_1": "tilt right",
    "HALOBOARD_DETECT_TILT_1_TILT_2": "seta para cima",
    "HALOBOARD_DETECT_TILT_1_TILT_3": "seta para baixo",
    "HALOBOARD_DETECT_TILT_1_TILT_4": "LED Ring up",
    "HALOBOARD_DETECT_TILT_1_TILT_5": "Anel de LED para baixo",
    "HALOBOARD_DETECT_TILT_1_TILT_6": "clockwise rotates",
    "HALOBOARD_DETECT_TILT_1_TILT_7": "anticlockwise rotates",
    "HALOBOARD_DETECT_TILT_1_TILT_8": "queda livre",
    "HALOBOARD_DETECT_TILT_1_TILT_9": "arrow to left",
    "HALOBOARD_DETECT_TILT_1_TILT_10": "arrow to right",
    "HALOBOARD_DETECT_TILT_1_TILT_11": "arrow to up",
    "HALOBOARD_DETECT_TILT_1_TILT_12": "arrow to down",
    "haloboard_detect_tilt_1": "Halocode [tilt] ？",
    "HALOBOARD_DETECT_TILT_TILT_0": "left tilted",
    "HALOBOARD_DETECT_TILT_TILT_1": "right tilted",
    "HALOBOARD_DETECT_TILT_TILT_2": "seta para cima",
    "HALOBOARD_DETECT_TILT_TILT_3": "seta para baixo",
    "HALOBOARD_DETECT_TILT_TILT_4": "LED Ring up",
    "HALOBOARD_DETECT_TILT_TILT_5": "Anel de LED para baixo",
    "HALOBOARD_DETECT_TILT_TILT_6": "clockwise rotates",
    "HALOBOARD_DETECT_TILT_TILT_7": "anti clockwise rotates",
    "HALOBOARD_DETECT_TILT_TILT_8": "queda livre",
    "haloboard_detect_tilt": "Halocode é [tilt]",
    "HALOBOARD_DETECT_INCLINE_INCLINE_0": "left tilted",
    "HALOBOARD_DETECT_INCLINE_INCLINE_1": "right tilted",
    "HALOBOARD_DETECT_INCLINE_INCLINE_2": "forward tilted",
    "HALOBOARD_DETECT_INCLINE_INCLINE_3": "backward tilted",
    "haloboard_detect_incline": "Halocode [incline] angle (°)",
    "haloboard_detect_shaked": "Halocode está abalado?",
    "haloboard_detect_shaked_value": "agitando a força",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_0": "x",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_1": "y",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_2": "z",
    "haloboard_detect_axis_acceleration": "aceleração do sensor de movimento (m/s ²)  [axis] Eixo",
    "haloboard_detect_axis_gyro": "angular velocity around[axis](°/s)",
    "HALOBOARD_DETECT_TILT_DEGREE_ROTATION_0": "pitch °",
    "HALOBOARD_DETECT_TILT_DEGREE_ROTATION_1": "rolo °",
    "haloboard_detect_tilt_degree": "motion sensor [rotation] posture(°)",
    "haloboard_detect_rotation_degree": "rotated angle around [axis] (°)",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_0": "todos",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_1": "x",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_2": "y",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_3": "z",
    "haloboard_reset_rotation_degree": "reset rotated angle around  [axis]",
    "haloboard_detect_time": "temporizador (s)",
    "haloboard_reset_time": "temporizador Reset",
    "E_1784_n": "Sentindo",
    "haloboard_pin_is_digtial": "pino [pin_number] em alto nível?",
    "haloboard_pin_read_digtial": " pino de leitura digital [pin_number]",
    "HALOBOARD_PIN_READ_ANALOG_PIN_NUMBER_0": "2",
    "HALOBOARD_PIN_READ_ANALOG_PIN_NUMBER_1": "3",
    "haloboard_pin_read_analog": "pino de leitura analógico [pin_number]",
    "haloboard_pin_write_digtial": " escrita digital [Digtial_value] para fixar [pin_number]",
    "haloboard_pin_write_PWM": "escrever analógico  [PWM_value] para fixar [pin_number]",
    "haloboard_pin_set_servo": "pino servo [pin_number] gira para [ServoRotaryAngle]",
    "halo_pin_play_buzzer_with_frequency": "alarme pino [pin_num] desempenha na frequência de [frequency] HZ para [duration]Segundos",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_0": "C2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_1": "D2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_2": "E2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_3": "F2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_4": "G2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_5": "A3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_6": "B3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_7": "C3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_8": "D3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_9": "E3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_10": "F3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_11": "G3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_12": "A4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_13": "B4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_14": "C4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_15": "D4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_16": "E4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_17": "F4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_18": "G4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_19": "A5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_20": "B5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_21": "C5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_22": "D5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_23": "E5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_24": "F5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_25": "G5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_26": "A6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_27": "B6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_28": "C6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_29": "D6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_30": "E6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_31": "F6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_32": "G6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_33": "A7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_34": "B7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_35": "C7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_36": "D7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_37": "E7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_38": "F7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_39": "G7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_40": "A8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_41": "B8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_42": "C8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_43": "D8",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_0": "um quarto de batida",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_1": "uma meia batida",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_2": "uma oitava batida",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_3": "uma batida",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_4": "batidas duplas",
    "halo_play_buzzer_with_note": "alarme pino[pin_num]  desempenha nota [note] Para [beat]",
    "cate_74a71a9d": "Pinos",
    "haloboard_wifi_set": "conectar ao Wi-Fi [ssid] Senha [wifipassword]",
    "haloboard_wifi_is_connect": "Wi-Fi conectado?",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_LANGUAGE_0": "Chinês",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_LANGUAGE_1": "Inglês",
    "haloboard_wifi_speech_recognition": "Reconhecer [Language] Para [Time] Segundos",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_0": "Chinese_standard(simplified)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_1": "Chinese_cantonese (traditional)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_2": "Chinese_Taiwan (traditional)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_3": "Inglês",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_4": "Francês",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_5": "Alemão",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_6": "Italiano",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_7": "Espanhol",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_8": "Japanese",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_9": "Portuguese",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_10": "Russian",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_11": "Korean",
    "haloboard_wifi_speech_recognition_v2": "Reconhecer [Language] Para [Time] Segundos",
    "haloboard_wifi_speech_recognition_word": "resultado de reconhecimento de fala",
    "haloboard_wifi_user_broadcast": "mensagem de nuvem de usuário de difusão [message]",
    "haloboard_wifi_user_broadcast_with_value": "mensagem de nuvem de usuário de difusão [message] com valor [value]",
    "haloboard_wifi_when_user_broadcast": "ao receber mensagem de nuvem do usuário [message]",
    "haloboard_wifi_user_broadcast_value": "mensagem de nuvem do usuário [message] valor recebido",
    "BLOCK_1543814805990": "暂时不做-当无线网络 [ssid] 密码 [password] 连接时",
    "widget_445594f4": "localização",
    "BLOCK_1560701681811_WEATHER_TYPE_0": "highest temperature(℃)",
    "BLOCK_1560701681811_WEATHER_TYPE_1": "lowest temperature(℃)",
    "BLOCK_1560701681811_WEATHER_TYPE_2": "highest temperature (℉)",
    "BLOCK_1560701681811_WEATHER_TYPE_3": "lowest temperature(℉)",
    "BLOCK_1560701681811_WEATHER_TYPE_4": "meteorologia",
    "BLOCK_1560701681811_WEATHER_TYPE_5": "humidade",
    "BLOCK_1560701681811": "[LOCATION]  [WEATHER_TYPE] ",
    "widget_dcc97542": "localização",
    "BLOCK_1560702195139_AQ_TYPE_0": "AQI",
    "BLOCK_1560702195139_AQ_TYPE_1": "PM2.5",
    "BLOCK_1560702195139_AQ_TYPE_2": "PM10",
    "BLOCK_1560702195139_AQ_TYPE_3": "CO",
    "BLOCK_1560702195139_AQ_TYPE_4": "SO₂",
    "BLOCK_1560702195139_AQ_TYPE_5": "NO₂",
    "BLOCK_1560702195139": "air quality [METEOROLOGICAL]  [aq_type]",
    "BLOCK_1560702421892_SUN_MOVE_TYPE_0": "nascer do sol",
    "BLOCK_1560702421892_SUN_MOVE_TYPE_1": "pôr do sol",
    "BLOCK_1560702421892_TIME_TYPE_0": "hora",
    "BLOCK_1560702421892_TIME_TYPE_1": "hora",
    "BLOCK_1560702421892_TIME_TYPE_2": "minuto",
    "BLOCK_1560702421892": "[LOCATION]  [sun_move_type] [time_type]",
    "BLOCK_1560702536759_FIELDMENU_3_0": "hora",
    "BLOCK_1560702536759_FIELDMENU_3_1": "hora",
    "BLOCK_1560702536759_FIELDMENU_3_2": "minuto",
    "BLOCK_1560702536759_FIELDMENU_3_3": "segundo",
    "BLOCK_1560702536759": "access [widget_1]local time [fieldMenu_3]",
    "Wi-Fi": "Wi-Fi",
    "haloboard_mesh_create1": "configurar LAN nomeado[mesh_name]",
    "haloboard_mesh_join1": "aderir à LAN com o nome [mesh_name]",
    "haloboard_mesh_broadcast_message": "Transmissão [message] em LAN",
    "haloboard_mesh_broadcast_message_with_value": "Transmissão [message] em LAN com valor [value]",
    "haloboard_mesh_when_received_message": "ao receber transmissão LAN [message]",
    "haloboard_mesh_get_value": " LAN message [message]value received",
    "BLOCK_1554191633131": "暂时不做 - 局域网是否已连接？",
    "mesh": "Lan",
    "haloboard_when_launch": "[ICON] Quando o Halocode arranca",
    "haloboard_when_button_pressed": "[ICON] quando o botão é pressionado",
    "haloboard_when_shaked": "[ICON] quando o Halocode está tremendo",
    "HALOBOARD_WHEN_TILT_TILT_0": "seta para cima",
    "HALOBOARD_WHEN_TILT_TILT_1": "seta para baixo",
    "HALOBOARD_WHEN_TILT_TILT_2": "esquerda-inclinado",
    "HALOBOARD_WHEN_TILT_TILT_3": "direito inclinados",
    "HALOBOARD_WHEN_TILT_TILT_4": "clockwise rotates",
    "HALOBOARD_WHEN_TILT_TILT_5": "anticlockwise rotates",
    "HALOBOARD_WHEN_TILT_TILT_6": "queda livre",
    "haloboard_when_tilt": "[ICON] quando o Halocode é [tilt]",
    "HALOBOARD_WHEN_TILT_1_TILT_0": "seta para cima",
    "HALOBOARD_WHEN_TILT_1_TILT_1": "seta para baixo",
    "HALOBOARD_WHEN_TILT_1_TILT_2": "esquerda-inclinado",
    "HALOBOARD_WHEN_TILT_1_TILT_3": "direito inclinados",
    "HALOBOARD_WHEN_TILT_1_TILT_4": "clockwise rotates",
    "HALOBOARD_WHEN_TILT_1_TILT_5": "anticlockwise rotates",
    "HALOBOARD_WHEN_TILT_1_TILT_6": "queda livre",
    "HALOBOARD_WHEN_TILT_1_TILT_7": "arrow to left",
    "HALOBOARD_WHEN_TILT_1_TILT_8": "arrow to right",
    "HALOBOARD_WHEN_TILT_1_TILT_9": "arrow to up",
    "HALOBOARD_WHEN_TILT_1_TILT_10": "arrow to down",
    "haloboard_when_tilt_1": "[ICON] quando o Halocode é [tilt]",
    "HALOBOARD_WHEN_TILT_2_TILT_0": "arrow-up",
    "HALOBOARD_WHEN_TILT_2_TILT_1": "arrow-down",
    "HALOBOARD_WHEN_TILT_2_TILT_2": "left-tilted",
    "HALOBOARD_WHEN_TILT_2_TILT_3": "right-tilted",
    "HALOBOARD_WHEN_TILT_2_TILT_4": "clockwise rotates",
    "HALOBOARD_WHEN_TILT_2_TILT_5": "anticlockwise rotates",
    "HALOBOARD_WHEN_TILT_2_TILT_6": "freefall",
    "HALOBOARD_WHEN_TILT_2_TILT_7": "arrow to left",
    "HALOBOARD_WHEN_TILT_2_TILT_8": "arrow to right",
    "HALOBOARD_WHEN_TILT_2_TILT_9": "arrow to up",
    "HALOBOARD_WHEN_TILT_2_TILT_10": "arrow to down",
    "haloboard_when_tilt_2": "[ICON] when Halocode is [tilt]",
    "haloboard_when_touched": "[ICON] when touch sensor [touchpad_number] is touched",
    "HALOBOARD_WHEN_GREATER_THAN_CATEGORY_0": "Timer",
    "HALOBOARD_WHEN_GREATER_THAN_CATEGORY_1": "microfone LOUDNESS",
    "haloboard_when_greater_than": "[ICON] quando [category] >[value]",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_0": "cronómetro",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_1": "microfone LOUDNESS",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_2": "agitando a força",
    "haloboard_when_greater_than_1": "[ICON] when [category] ＞ [value]",
    "e_509_c_events_b_18280": "quando o Halocode [tilt]",
    "e_509_c_events_b_18281": "Quando o pino [touchpad_number] é tocado",
    "e_509_c_1410_b_18249": "todos os LEDs acendem [color_1]",
    "BLOCK_1543754866399": "alarme pino [pin] reproduz som em frequência [frequency] HZ para [duration] Segundos",
    "BLOCK_1543818559542_TEMPO_4": "batida dobro",
    "CHOOSE_CITY": "Cidade",
    "METEOROLOGICAL": "Cidade",
    "firmware_versions": "Versão de Firmware:",
    "show_mode": "Current Mode:",
    "wifi_link_status": "Wi-Fi Connection:",
    "bluetooth_address": "Bluetooth Address:",
    "language_recognition_results": "Speech Recognition Result:",
    "mac_address": "MAC Address:",
    "prompt_message": "Halocode not fully started may lead to inaccurate readouts. Please wait seconds and try again later.",
    "device_state": "Device Status"
};