export default {
    "haloboard": "HaloCode",
    "extensionName": "Halocode",
    "extensionDescription": "HaloCode - це одноплатний комп'ютер з вбудованим Wi-Fi",
    "firmwares_version_9c2fcf2b": "Остання прошивка",
    "UPDATE_FIRMWARE": "Оновлення прошивки",
    "settings_717e2676": "Перевірка статусу",
    "connect_fail_418dd2b0": "Переконайтеся, що USB-кабель правильно під'єднано до пристрою.",
    "connect_fail_be44da45": "Переконайтеся, що підключений пристрій увімкнуто.",
    "connect_fail_81f19800": "Одночасно в цій версії можна підключити тільки один пристрій. Підключення нового пристрою призведе до відключення попереднього.",
    "connect_fail_a2244e18": "Переконайтеся, що ваш комп'ютер підтримує Bluetooth 4,0 і на ньому ввімкнутий Bluetooth.",
    "connect_fail_2ff4c830": "Переконайтеся, що пристрій, який ви намагаєтеся підключити, увімкнуто.",
    "connect_fail_f516f160": "Одночасно в цій версії можна підключити тільки один пристрій. Підключення нового пристрою призведе до відключення попереднього.",
    "upload_fail_440e4ba6": "Будь ласка, перегляньте блоки кодування або код для цього пристрою. Переконайтеся, що всі дані, параметри та логіка програмування правильні.",
    "upload_fail_24d8e745": "Переконайтеся, що пристрій підключено належним чином. Ви можете перезапустити пристрій і підключити його знову.",
    "upload_fail_c52d223b": "Будь ласка, переконайтеся, що прошивка коректно працює. Ви можете оновити її або скинути до заводських установок, а потім повторити спробу.",
    "firmware_success_70e9b6c0": "Для корректної роботи, будь ласка, перезавантажте пристрій і знову підключіть його.",
    "firmware_fail_9b5aae92": "Переконайтеся, що пристрій під'єднано належним чином. Перезавантажте пристрій, підключіть його та спробуйте знову оновити прошивку.",
    "firmware_fail_9a92af14": "Цей пристрій не підтримує оновлення прошивки за допомогою адаптера Bluetooth або іншими способами.",
    "BLOCK_1570879365614_LED_ANIMATION_0": "веселка",
    "BLOCK_1570879365614_LED_ANIMATION_1": "обертання",
    "BLOCK_1570879365614_LED_ANIMATION_2": "метеор (блакитний)",
    "BLOCK_1570879365614_LED_ANIMATION_3": "метеор (зелений)",
    "BLOCK_1570879365614_LED_ANIMATION_4": "спалах (червоний)",
    "BLOCK_1570879365614_LED_ANIMATION_5": "спалах (помаранчевий)",
    "BLOCK_1570879365614_LED_ANIMATION_6": "світлячок",
    "BLOCK_1570879365614": "відтворити LED анімацію [LED_animation] до кінця",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_0": "веселка",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_1": "обертання",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_2": "метеор",
    "HALOBOARD_SHOW_RING_EFFECT_LED_ANIMATION_3": "світлячок",
    "haloboard_show_ring_effect": "відтворити LED анімацію  [LED_animation] до кінця",
    "haloboard_show_ring_color": "вивести [ledRing]",
    "haloboard_show_rotation_color": "вивести [ledRing] після [rotate] обертань [led_number] світлодіодів",
    "haloboard_show_all_leds": "всі світлодіоди світитись [color_1]",
    "haloboard_show_all_leds_with_lightness": "всі світлодіоди світитись [color_1] з яскравістю [lightness] %",
    "haloboard_off_all_leds": "вимкнути всі світлодіоди",
    "haloboard_show_all_leds_with_rgb": "всі світлодіоди світитись кольором R [r] G  [g] B [b]",
    "haloboard_show_single_led_with_rgb": "світлодіод [led_id] світитись кольором R[r] G[g] B[b]",
    "haloboard_off_single_led": "вимкнути світлодіод [led_id]",
    "haloboard_show_percentage": "LED кільце вивести [percentage] %",
    "E_1783_n": "Освітлення",
    "haloboard_detect_button_pressed": "натиснуто кнопку?",
    "haloboard_detect_volume": "чутливість мікрофону",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_0": "0",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_1": "1",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_2": "2",
    "HALOBOARD_DETECT_TOUCH_TOUCHPAD_NUMBER_3": "3",
    "haloboard_detect_touch": "touch sensor [touchpad_number] is touched?",
    "haloboard_detect_touch_value": "touch sensor [touchpad_number] touch value",
    "BLOCK_1552905879755_SENSITIVITY_0": "високий",
    "BLOCK_1552905879755_SENSITIVITY_1": "середня",
    "BLOCK_1552905879755_SENSITIVITY_2": "низький",
    "BLOCK_1552905879755": "set touch sensor [touchpad_number] sensitivity to[sensitivity]",
    "HALOBOARD_DETECT_TILT_1_TILT_0": "нахиена ліворуч",
    "HALOBOARD_DETECT_TILT_1_TILT_1": "нахилена ліворуч",
    "HALOBOARD_DETECT_TILT_1_TILT_2": "стрілкою вгору",
    "HALOBOARD_DETECT_TILT_1_TILT_3": "стрілкою вниз",
    "HALOBOARD_DETECT_TILT_1_TILT_4": "LED кільцем вгору",
    "HALOBOARD_DETECT_TILT_1_TILT_5": "LED кільцем вниз",
    "HALOBOARD_DETECT_TILT_1_TILT_6": "обертати за годинниковою стрілкою",
    "HALOBOARD_DETECT_TILT_1_TILT_7": "обертати проти годинникової стрілки",
    "HALOBOARD_DETECT_TILT_1_TILT_8": "вільне падіння",
    "HALOBOARD_DETECT_TILT_1_TILT_9": "стрілкою вліво",
    "HALOBOARD_DETECT_TILT_1_TILT_10": "стрілкою вправо",
    "HALOBOARD_DETECT_TILT_1_TILT_11": "стрілкою вгору",
    "HALOBOARD_DETECT_TILT_1_TILT_12": "стрілкою вниз",
    "haloboard_detect_tilt_1": "Halocode [tilt] ?",
    "HALOBOARD_DETECT_TILT_TILT_0": "нахилена ліворуч",
    "HALOBOARD_DETECT_TILT_TILT_1": "нахилена праворуч",
    "HALOBOARD_DETECT_TILT_TILT_2": "стрілкою вгору",
    "HALOBOARD_DETECT_TILT_TILT_3": "стрілкою вниз",
    "HALOBOARD_DETECT_TILT_TILT_4": "LED кільцем вгору",
    "HALOBOARD_DETECT_TILT_TILT_5": "LED кільцем вниз",
    "HALOBOARD_DETECT_TILT_TILT_6": "обертати за годинниковою стрілкою",
    "HALOBOARD_DETECT_TILT_TILT_7": "обертати проти годинникової стрілки",
    "HALOBOARD_DETECT_TILT_TILT_8": "вільне падіння",
    "haloboard_detect_tilt": "HaloCode [tilt]？",
    "HALOBOARD_DETECT_INCLINE_INCLINE_0": "нахилена ліворуч",
    "HALOBOARD_DETECT_INCLINE_INCLINE_1": "нахилена праворуч",
    "HALOBOARD_DETECT_INCLINE_INCLINE_2": "нахилена вперед",
    "HALOBOARD_DETECT_INCLINE_INCLINE_3": "нахилена назад",
    "haloboard_detect_incline": "Halocode [incline] кут (°)",
    "haloboard_detect_shaked": "HaloCode труситься?",
    "haloboard_detect_shaked_value": "сила струшування",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_0": "x",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_1": "y",
    "HALOBOARD_DETECT_AXIS_ACCELERATION_AXIS_2": "z",
    "haloboard_detect_axis_acceleration": "датчик руху прискорення (м/с ²) по осі [axis]",
    "haloboard_detect_axis_gyro": "кутова швидкість навколо [axis] (°/s)",
    "HALOBOARD_DETECT_TILT_DEGREE_ROTATION_0": "тангаж °",
    "HALOBOARD_DETECT_TILT_DEGREE_ROTATION_1": "обертання °",
    "haloboard_detect_tilt_degree": "датчик руху [rotation] положення (°)",
    "haloboard_detect_rotation_degree": "кут повороту навколо [axis] (°)",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_0": "Всі",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_1": "x",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_2": "y",
    "HALOBOARD_RESET_ROTATION_DEGREE_AXIS_3": "z",
    "haloboard_reset_rotation_degree": "скинути кут повороту навколо [axis]",
    "haloboard_detect_time": "таймер (сек)",
    "haloboard_reset_time": "скинути таймер",
    "E_1784_n": "Вимірювання",
    "haloboard_pin_is_digtial": "контакт [pin_number] високий?",
    "haloboard_pin_read_digtial": " цифровий порт зчитування [pin_number]",
    "HALOBOARD_PIN_READ_ANALOG_PIN_NUMBER_0": "2",
    "HALOBOARD_PIN_READ_ANALOG_PIN_NUMBER_1": "3",
    "haloboard_pin_read_analog": "аналоговий порт зчитування [pin_number]",
    "haloboard_pin_write_digtial": " записати [Digtial_value] у цифровий порт [pin_number]",
    "haloboard_pin_write_PWM": "записати [PWM_value] у аналоговий порт [pin_number]",
    "haloboard_pin_set_servo": "порт серво [pin_number] повертатися до [ServoRotaryAngle]",
    "halo_pin_play_buzzer_with_frequency": "зумер контакт [pin_num] грати на частоті [frequency] Гц [duration] сек",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_0": "C2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_1": "D2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_2": "E2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_3": "F2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_4": "G2",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_5": "A3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_6": "B3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_7": "C3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_8": "D3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_9": "E3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_10": "F3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_11": "G3",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_12": "A4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_13": "B4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_14": "C4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_15": "D4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_16": "E4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_17": "F4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_18": "G4",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_19": "A5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_20": "B5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_21": "C5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_22": "D5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_23": "E5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_24": "F5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_25": "G5",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_26": "A6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_27": "B6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_28": "C6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_29": "D6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_30": "E6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_31": "F6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_32": "G6",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_33": "A7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_34": "B7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_35": "C7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_36": "D7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_37": "E7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_38": "F7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_39": "G7",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_40": "A8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_41": "B8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_42": "C8",
    "HALO_PLAY_BUZZER_WITH_NOTE_NOTE_43": "D8",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_0": "чверть долі",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_1": "половина долі",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_2": "одна восьма долі",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_3": "ціла",
    "HALO_PLAY_BUZZER_WITH_NOTE_BEAT_4": "подвійна",
    "halo_play_buzzer_with_note": "зумер порт [pin_num] грати ноту [note] [beat] долей",
    "cate_74a71a9d": "Контакти",
    "haloboard_wifi_set": "підключитися до Wi-Fi мережі [ssid], пароль [wifipassword]",
    "haloboard_wifi_is_connect": "Wi-Fi підключено?",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_LANGUAGE_0": "Китайська",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_LANGUAGE_1": "Англійська",
    "haloboard_wifi_speech_recognition": "розпізнати [Language] за [Time] секунд",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_0": "Китайська Мандарин (спрощене письмо)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_1": "Китайська Кантонська (традиційне письмо)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_2": "Китайська Тайванська (традиційне письмо)",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_3": "Англійська",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_4": "Французька",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_5": "Німецька",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_6": "Італійська",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_7": "Іспанська",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_8": "Japanese",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_9": "Portuguese",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_10": "Russian",
    "HALOBOARD_WIFI_SPEECH_RECOGNITION_V2_LANGUAGE_11": "Korean",
    "haloboard_wifi_speech_recognition_v2": "розпізнати [Language] за [Time] секунд",
    "haloboard_wifi_speech_recognition_word": "результат розпізнавання мови",
    "haloboard_wifi_user_broadcast": "транслювати повідомлення користувача у хмару [message]",
    "haloboard_wifi_user_broadcast_with_value": "транслювати повідомлення користувача [message] у хмару зі значенням [value]",
    "haloboard_wifi_when_user_broadcast": "коли надходить повідомлення користувача із хмари [message]",
    "haloboard_wifi_user_broadcast_value": "значення отриманого повідомлення користувача із хмари [message]",
    "BLOCK_1543814805990": "暂时不做-当无线网络 [ssid] 密码 [password] 连接时",
    "widget_445594f4": "місцезнаходження",
    "BLOCK_1560701681811_WEATHER_TYPE_0": "максимальна температура(℃)",
    "BLOCK_1560701681811_WEATHER_TYPE_1": "мінімальна температура(℃)",
    "BLOCK_1560701681811_WEATHER_TYPE_2": "максимальна температура (℉)",
    "BLOCK_1560701681811_WEATHER_TYPE_3": "мінімальна температура (℉)",
    "BLOCK_1560701681811_WEATHER_TYPE_4": "погода",
    "BLOCK_1560701681811_WEATHER_TYPE_5": "вологість",
    "BLOCK_1560701681811": "[LOCATION]  [WEATHER_TYPE] ",
    "widget_dcc97542": "місцезнаходження",
    "BLOCK_1560702195139_AQ_TYPE_0": "AQI",
    "BLOCK_1560702195139_AQ_TYPE_1": "PM2.5",
    "BLOCK_1560702195139_AQ_TYPE_2": "PM10",
    "BLOCK_1560702195139_AQ_TYPE_3": "CO",
    "BLOCK_1560702195139_AQ_TYPE_4": "SO₂",
    "BLOCK_1560702195139_AQ_TYPE_5": "NO₂",
    "BLOCK_1560702195139": "якість повітря [METEOROLOGICAL] [aq_type]",
    "BLOCK_1560702421892_SUN_MOVE_TYPE_0": "схід сонця",
    "BLOCK_1560702421892_SUN_MOVE_TYPE_1": "захід сонця",
    "BLOCK_1560702421892_TIME_TYPE_0": "час",
    "BLOCK_1560702421892_TIME_TYPE_1": "година",
    "BLOCK_1560702421892_TIME_TYPE_2": "хвилина",
    "BLOCK_1560702421892": "[LOCATION]  [sun_move_type] [time_type]",
    "BLOCK_1560702536759_FIELDMENU_3_0": "час",
    "BLOCK_1560702536759_FIELDMENU_3_1": "година",
    "BLOCK_1560702536759_FIELDMENU_3_2": "хвилина",
    "BLOCK_1560702536759_FIELDMENU_3_3": "секунда",
    "BLOCK_1560702536759": "доступ [widget_1]місцевий час [fieldMenu_3]",
    "Wi-Fi": "Wi-Fi",
    "haloboard_mesh_create1": "створити локальну мережу [mesh_name]",
    "haloboard_mesh_join1": "приєднатись до локальної мережі [mesh_name]",
    "haloboard_mesh_broadcast_message": "транслювати [message] по LAN",
    "haloboard_mesh_broadcast_message_with_value": "транслювати [message] по LAN зі значенням [value]",
    "haloboard_mesh_when_received_message": "коли по LAN отримано повідомлення [message]",
    "haloboard_mesh_get_value": " LAN повідомлення [message] отримано значення",
    "BLOCK_1554191633131": "暂时不做 - 局域网是否已连接？",
    "mesh": "LAN",
    "haloboard_when_launch": "[ICON] при запуску HaloCode",
    "haloboard_when_button_pressed": "[ICON] коли натиснута кнопка",
    "haloboard_when_shaked": "[ICON] коли HaloCode труситься",
    "HALOBOARD_WHEN_TILT_TILT_0": "стрілкою вгору",
    "HALOBOARD_WHEN_TILT_TILT_1": "стрілкою вниз",
    "HALOBOARD_WHEN_TILT_TILT_2": "нахилене ліворуч",
    "HALOBOARD_WHEN_TILT_TILT_3": "нахилене праворуч",
    "HALOBOARD_WHEN_TILT_TILT_4": "обертати за годинниковою стрілкою",
    "HALOBOARD_WHEN_TILT_TILT_5": "обертати проти годинникової стрілки",
    "HALOBOARD_WHEN_TILT_TILT_6": "вільне падіння",
    "haloboard_when_tilt": "[ICON] коли HaloCode [tilt]",
    "HALOBOARD_WHEN_TILT_1_TILT_0": "стрілкою вгору",
    "HALOBOARD_WHEN_TILT_1_TILT_1": "стрілкою вниз",
    "HALOBOARD_WHEN_TILT_1_TILT_2": "нахилене ліворуч",
    "HALOBOARD_WHEN_TILT_1_TILT_3": "нахилене праворуч",
    "HALOBOARD_WHEN_TILT_1_TILT_4": "обертати за годинниковою стрілкою",
    "HALOBOARD_WHEN_TILT_1_TILT_5": "обертати проти годинникової стрілки",
    "HALOBOARD_WHEN_TILT_1_TILT_6": "вільне падіння",
    "HALOBOARD_WHEN_TILT_1_TILT_7": "стрілкою вліво",
    "HALOBOARD_WHEN_TILT_1_TILT_8": "стрілкою вправо",
    "HALOBOARD_WHEN_TILT_1_TILT_9": "стрілкою вгору",
    "HALOBOARD_WHEN_TILT_1_TILT_10": "стрілкою вниз",
    "haloboard_when_tilt_1": "[ICON] коли HaloCode [tilt]",
    "HALOBOARD_WHEN_TILT_2_TILT_0": "arrow-up",
    "HALOBOARD_WHEN_TILT_2_TILT_1": "arrow-down",
    "HALOBOARD_WHEN_TILT_2_TILT_2": "left-tilted",
    "HALOBOARD_WHEN_TILT_2_TILT_3": "right-tilted",
    "HALOBOARD_WHEN_TILT_2_TILT_4": "clockwise rotates",
    "HALOBOARD_WHEN_TILT_2_TILT_5": "anticlockwise rotates",
    "HALOBOARD_WHEN_TILT_2_TILT_6": "freefall",
    "HALOBOARD_WHEN_TILT_2_TILT_7": "arrow to left",
    "HALOBOARD_WHEN_TILT_2_TILT_8": "arrow to right",
    "HALOBOARD_WHEN_TILT_2_TILT_9": "arrow to up",
    "HALOBOARD_WHEN_TILT_2_TILT_10": "arrow to down",
    "haloboard_when_tilt_2": "[ICON] when Halocode is [tilt]",
    "haloboard_when_touched": "[ICON] when touch sensor [touchpad_number] is touched",
    "HALOBOARD_WHEN_GREATER_THAN_CATEGORY_0": "Таймер",
    "HALOBOARD_WHEN_GREATER_THAN_CATEGORY_1": "чутливість мікрофону",
    "haloboard_when_greater_than": "[ICON] коли [category] > [value]",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_0": "таймер",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_1": "чутливість мікрофону",
    "HALOBOARD_WHEN_GREATER_THAN_1_CATEGORY_2": "сила струшування",
    "haloboard_when_greater_than_1": "[ICON] коли [category] > [value]",
    "e_509_c_events_b_18280": "коли HaloCode [tilt]",
    "e_509_c_events_b_18281": "коли до контакту [touchpad_number] торкнулися",
    "e_509_c_1410_b_18249": "всі світлодіоди світитись [color_1]",
    "BLOCK_1543754866399": "зумер порт [pin] грати на частоті [frequency] HZ [duration] сек",
    "BLOCK_1543818559542_TEMPO_4": "подвійна",
    "CHOOSE_CITY": "Місто",
    "METEOROLOGICAL": "Місто",
    "firmware_versions": "Версія прошивки:",
    "show_mode": "Поточний режим:",
    "wifi_link_status": "Підключення Wi-Fi:",
    "bluetooth_address": "Bluetooth адреса:",
    "language_recognition_results": "Результат розпізнання мови:",
    "mac_address": "MAC-адреса:",
    "prompt_message": "Halocode ще не повністю запущена. Це може призвести до неточних показань. Будь ласка, зачекайте декілька секунд і спробуйте ще раз.",
    "device_state": "Стан пристрою"
};