export default {
    "fingertip_piano": "Fingertip Piano",
    "extensionName": "Fingertip Piano",
    "extensionDescription": "",
    "firmwares_version_ae4299ad": "Latest Firmware",
    "UPDATE_FIRMWARE": "Firmware Update",
    "connect_fail_c01ed169": "Please ensure the USB cable is properly connected to the device.",
    "connect_fail_718157dd": "Please ensure the device to be connected is powered on.",
    "connect_fail_3da2d16f": "Only one device can be connected at a time in this version. A new device connection will lead to the disconnection of the existing one.",
    "connect_fail_a777d1e4": "Please ensure your computer supports Bluetooth4.0 and Bluetooth4.0 is already enabled.",
    "connect_fail_e573866d": "Please ensure the device to be connected is powered on.",
    "connect_fail_b7a97436": "Only one device can be connected at a time in this version. A new device connection will lead to the disconnection of the existing one.",
    "firmware_success_0ef92dd4": "For better experience, we recommend that you reconnect the device after restarting it.",
    "firmware_fail_3dfa6a56": "Please check if the device is properly connected. Try restarting the device and reconnect it. Then update again.",
    "fingertip_piano_set_rgb_clolor": "LED displays [color] with brightness [lightness] %",
    "fingertip_piano_reset_rgb": "turn off LED",
    "fingertip_piano_set_rgb_value": "LED displays R[r] G[g]B [b]",
    "cate_515586b6": "Lighting",
    "FINGERTIP_PIANO_IS_TOUCHPAD_TOUCHED_CHANNEL_0": "1",
    "FINGERTIP_PIANO_IS_TOUCHPAD_TOUCHED_CHANNEL_1": "2",
    "FINGERTIP_PIANO_IS_TOUCHPAD_TOUCHED_CHANNEL_2": "3",
    "FINGERTIP_PIANO_IS_TOUCHPAD_TOUCHED_CHANNEL_3": "4",
    "fingertip_piano_is_touchpad_touched": "touchpad [channel]touched?",
    "FINGERTIP_PIANO_IS_BUTTON_PRESSED_BUTTON_0": "A",
    "FINGERTIP_PIANO_IS_BUTTON_PRESSED_BUTTON_1": "B",
    "fingertip_piano_is_button_pressed": "button [button]pressed?",
    "fingertip_piano_get_button_count": "button [button] press counts",
    "fingertip_piano_reset_button_count": "button [button]resets counts",
    "FINGERTIP_PIANO_IS_JOYSTICK_MOVED_DIRECTION_0": "upward",
    "FINGERTIP_PIANO_IS_JOYSTICK_MOVED_DIRECTION_1": "downward",
    "FINGERTIP_PIANO_IS_JOYSTICK_MOVED_DIRECTION_2": "leftward",
    "FINGERTIP_PIANO_IS_JOYSTICK_MOVED_DIRECTION_3": "rightward",
    "fingertip_piano_is_joystick_moved": "joystick [direction]shaken?",
    "fingertip_piano_touchpad_value": "touchpad [channel]value",
    "cate_9ca82b40": "Control",
    "fingertip_piano_detected_obstacle": "obstacle detected?",
    "FINGERTIP_PIANO_DETECTED_OBSTACLE_DIRECTON_ATTITUDE_0": "coming close",
    "FINGERTIP_PIANO_DETECTED_OBSTACLE_DIRECTON_ATTITUDE_1": "getting away",
    "fingertip_piano_detected_obstacle_directon": "when obstacle [attitude] ?",
    "fingertip_piano_get_obstacle_distance": "obstacle distance",
    "fingertip_piano_get_ir_sensor_value": "reflected infrared light intensity",
    "FINGERTIP_PIANO_GET_GESTURE_ATTITUDE_0": "up",
    "FINGERTIP_PIANO_GET_GESTURE_ATTITUDE_1": "down",
    "FINGERTIP_PIANO_GET_GESTURE_ATTITUDE_2": "waving",
    "fingertip_piano_get_gesture": "hand [attitude]?",
    "cate_12fc6527": "Sensing",
    "fingertip_piano_obstacle_event": "when obstacle detected",
    "fingertip_piano_detected_obstacle_event": "when obstacle [attitude]",
    "fingertip_piano_get_obstacle_event": "when obstacle distance＜[distance]",
    "fingertip_piano_touchpad_event": "when touchpad [channel]touched",
    "fingertip_piano_button_event": "when [button]button pressed",
    "fingertip_piano_joystick_event": "when joystick [direction]shaken",
    "fingertip_piano_gesture_event": "when hand [attitude]"
};