export default {
    "megapipro_mbuild_camera": "视觉模块",
    "extensionName": "视觉模块",
    "extensionDescription": "megapipro的视觉模块扩展",
    "megapipro_1566200222835": "查看摄像头画面",
    "MEGAPIPRO_CAMERA_SWITCH_COLOR_MODE_PORT_0": "接口6",
    "MEGAPIPRO_CAMERA_SWITCH_COLOR_MODE_PORT_1": "接口7",
    "MEGAPIPRO_CAMERA_SWITCH_COLOR_MODE_PORT_2": "接口8",
    "MEGAPIPRO_CAMERA_SWITCH_COLOR_MODE_PORT_3": "接口9",
    "MEGAPIPRO_CAMERA_SWITCH_COLOR_MODE_PORT_4": "接口10",
    "MEGAPIPRO_CAMERA_SWITCH_COLOR_MODE_PORT_5": "接口11",
    "MEGAPIPRO_CAMERA_SWITCH_COLOR_MODE_PORT_6": "接口12",
    "megapipro_camera_switch_color_mode": "视觉模块 [PORT]  切换到色块识别模式 ",
    "MEGAPIPRO_CAMERA_RECOGNIZE_COLOR_SIG_0": "1",
    "MEGAPIPRO_CAMERA_RECOGNIZE_COLOR_SIG_1": "2",
    "MEGAPIPRO_CAMERA_RECOGNIZE_COLOR_SIG_2": "3",
    "MEGAPIPRO_CAMERA_RECOGNIZE_COLOR_SIG_3": "4",
    "MEGAPIPRO_CAMERA_RECOGNIZE_COLOR_SIG_4": "5",
    "MEGAPIPRO_CAMERA_RECOGNIZE_COLOR_SIG_5": "6",
    "MEGAPIPRO_CAMERA_RECOGNIZE_COLOR_SIG_6": "7",
    "megapipro_camera_recognize_color": "视觉模块 [PORT] 开始学习色块 [SIG] 直到学习按钮按下",
    "MEGAPIPRO_CAMERA_CENTER_SATURATION_FIELDMENU_2_0": "中心",
    "MEGAPIPRO_CAMERA_CENTER_SATURATION_FIELDMENU_2_1": "平均",
    "MEGAPIPRO_CAMERA_CENTER_SATURATION_FIELDMENU_1_0": "饱和度",
    "MEGAPIPRO_CAMERA_CENTER_SATURATION_FIELDMENU_1_1": "R值",
    "MEGAPIPRO_CAMERA_CENTER_SATURATION_FIELDMENU_1_2": "G值",
    "MEGAPIPRO_CAMERA_CENTER_SATURATION_FIELDMENU_1_3": "B值",
    "MEGAPIPRO_CAMERA_CENTER_SATURATION_FIELDMENU_1_4": "灰度",
    "megapipro_camera_center_saturation": "视觉模块 [fieldMenu_1]   画面 [fieldMenu_2] 的 [fieldMenu_1] ",
    "megapipro_camera_get_color": "视觉模块 [PORT]  识别到色块 [SIG] ？",
    "MEGAPIPRO_CAMERA_COLOR_IN_CENTER_LOCATION_0": "中央",
    "MEGAPIPRO_CAMERA_COLOR_IN_CENTER_LOCATION_1": "上方",
    "MEGAPIPRO_CAMERA_COLOR_IN_CENTER_LOCATION_2": "下方",
    "MEGAPIPRO_CAMERA_COLOR_IN_CENTER_LOCATION_3": "左边",
    "MEGAPIPRO_CAMERA_COLOR_IN_CENTER_LOCATION_4": "右边",
    "megapipro_camera_color_in_center": "视觉模块 [PORT]   识别到色块 [SIG] 位于画面 [LOCATION] ？",
    "MEGAPIPRO_CAMERA_COLOR_COORDINATE_CCCINFO_0": "x 坐标",
    "MEGAPIPRO_CAMERA_COLOR_COORDINATE_CCCINFO_1": "y 坐标",
    "MEGAPIPRO_CAMERA_COLOR_COORDINATE_CCCINFO_2": "宽度",
    "MEGAPIPRO_CAMERA_COLOR_COORDINATE_CCCINFO_3": "高度",
    "megapipro_camera_color_coordinate": "视觉模块 [PORT]  识别到色块 [SIG] 的 [CCCINFO] ",
    "MEGAPIPRO_CAMERA_TURN_ON_LIGHT_STATE_0": "打开",
    "MEGAPIPRO_CAMERA_TURN_ON_LIGHT_STATE_1": "关闭",
    "megapipro_camera_turn_on_light": "视觉模块 [PORT]   [STATE] 补光灯",
    "megapipro_camera_set_white_balance": "视觉模块 [PORT] 重置白平衡",
    "cate_6aae53c0": "视觉模块色块识别",
    "megapipro_camera_1566200222835": "查看摄像头画面",
    "megapipro_camera_switch_line_qrcode_mode": "视觉模块 [PORT] 切换到 线/条码 追踪模式",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_0": "(1) 前进",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_1": "(2) 后退",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_2": "(3) 左转",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_3": "(4) 右转",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_4": "(5) 停止",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_5": "(6) 加号",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_6": "(7) 减号",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_7": "(8) 问号",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_8": "(9) 红心",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_9": "(10) A",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_10": "(11) B",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_11": "(12) C",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_12": "(13) ①",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_13": "(14) ②",
    "MEGAPIPRO_CAMERA_GET_QRCODE_MOVE_BARCODE_14": "(15) ③",
    "megapipro_camera_get_qrcode_move": "视觉模块 [PORT]检测到条码 [BARCODE] ？",
    "MEGAPIPRO_CAMERA_GET_QRCODE_COORDINATE_BARCODEINFO_0": "x",
    "MEGAPIPRO_CAMERA_GET_QRCODE_COORDINATE_BARCODEINFO_1": "y",
    "megapipro_camera_get_qrcode_coordinate": "视觉模块 [PORT] 检测到条码 [BARCODE] 的 [BARCODEINFO] 坐标",
    "MEGAPIPRO_CAMERA_LINE_START_COORDINATE_LINEINFO_0": "起始 x 坐标",
    "MEGAPIPRO_CAMERA_LINE_START_COORDINATE_LINEINFO_1": "起始 y 坐标",
    "MEGAPIPRO_CAMERA_LINE_START_COORDINATE_LINEINFO_2": "终点 x 坐标",
    "MEGAPIPRO_CAMERA_LINE_START_COORDINATE_LINEINFO_3": "终点 y 坐标",
    "megapipro_camera_line_start_coordinate": "视觉模块 [PORT] 当前所在线段的 [LINEINFO] ",
    "megapipro_camera_get_cross": "视觉模块 [PORT] 检测到交叉点？",
    "megapipro_camera_corss_coordinate": "视觉模块 [PORT] 检测到交叉点的 [COORDINATES] 坐标",
    "megapipro_camera_get_branch_num": "视觉模块 [PORT] 检测到岔路的数量",
    "megapipro_camera_get_branch_angle": "视觉模块 [PORT] 检测到第 [NUMBER] 个岔路的角度",
    "MEGAPIPRO_CAMERA_SET_LINE_MODE_LINEMODE_0": "浅底深线",
    "MEGAPIPRO_CAMERA_SET_LINE_MODE_LINEMODE_1": "深底浅线",
    "megapipro_camera_set_line_mode": "视觉模块 [PORT] 设置线追踪模式为 [LINEMODE] ",
    "megapipro_camera_1566200454757": "视觉模块 [PORT] 设置偏好角度为 [ANGLE] ",
    "megapipro_camera_1566200474887": "视觉模块 [PORT] 当前偏好角度 (°)",
    "cate_aff8824d": "视觉模块线/条码追踪",
    "megapipro_camera_set_kp": "视觉模块 [PORT] 设置电机差速计算系数 Kp 为 [KP] ",
    "megapipro_camera_follow_color": "视觉模块 [PORT] 计算电机差速值 (自动跟随色块 [SIG]至 [LOCATION] 轴 [NUMBER] ）",
    "megapipro_camera_follow_qrcode": "视觉模块 [PORT] 计算电机差速值 (自动跟随条形码 [BARCODE] 至 [LOCATION] 轴 [NUMBER] ）",
    "megapipro_camera_get_diff_speed": "视觉模块 [PORT] 计算电机差速值 (对准巡线线段）",
    "megapipro_camera_lock_color": "视觉模块 [PORT] 锁定色块 [SIG] 到 [LOCATION] 轴 [NUMBER]  附近?",
    "megapipro_camera_lock_qrcode": "视觉模块 [PORT] 锁定条形码  [BARCODE] 到 [LOCATION] 轴 [NUMBER] 附近?",
    "cate_41d9cfb5": "视觉模块赛事专用",
    "BLOCK_1566199596519": "视觉模块 [PORT]  切换到色块识别模式",
    "BLOCK_1566200061809": "视觉模块 [PORT] 开始学习色块 [SIG] 直到学习按钮按下",
    "BLOCK_1566200149400": "视觉模块 [PORT]  识别到色块 [SIG] 的 [CCCINFO]",
    "BLOCK_1566200281367_BARCODE_0": "(1) 前进",
    "BLOCK_1566200281367_BARCODE_1": "(2) 后退",
    "BLOCK_1566200281367_BARCODE_2": "(3) 左转",
    "BLOCK_1566200281367_BARCODE_3": "(4) 右转",
    "BLOCK_1566200281367_BARCODE_4": "(5) 停止",
    "BLOCK_1566200281367_BARCODE_5": "(6) 加号",
    "BLOCK_1566200281367_BARCODE_6": "(7) 减号",
    "BLOCK_1566200281367_BARCODE_7": "(8) 问号",
    "BLOCK_1566200281367_BARCODE_8": "(9) 红心",
    "BLOCK_1566200281367_BARCODE_9": "(10) A",
    "BLOCK_1566200281367_BARCODE_10": "(11) B",
    "BLOCK_1566200281367_BARCODE_11": "(12) C",
    "BLOCK_1566200281367_BARCODE_12": "(13) ①",
    "BLOCK_1566200281367_BARCODE_13": "(14) ②",
    "BLOCK_1566200281367_BARCODE_14": "(15) ③",
    "BLOCK_1566200281367": "视觉模块 [PORT]检测到条码 [BARCODE] ？",
    "BLOCK_1566200305130": "视觉模块 [PORT] 检测到条码 [BARCODE] 的 [BARCODEINFO] 坐标",
    "BLOCK_1566200324089": "视觉模块 [PORT] 当前所在线段的 [LINEINFO]",
    "BLOCK_1566200343169": "视觉模块 [PORT] 检测到交叉点？",
    "BLOCK_1566200380110": "视觉模块 [PORT] 检测到交叉点的 [COORDINATES] 坐标",
    "BLOCK_1566200411758": "视觉模块 [PORT] 检测到第 [NUMBER] 个岔路的角度",
    "BLOCK_1566200440316": "视觉模块 [PORT] 设置线追踪模式为 [LINEMODE]",
    "BLOCK_1567596489390": "视觉模块 [PORT] 计算电机差速值 (自动跟随色块 [SIG]至 [LOCATION] 轴 [NUMBER] ）",
    "BLOCK_1567596489391": "视觉模块 [PORT] 计算电机差速值 (自动跟随条形码 [BARCODE] 至 [LOCATION] 轴 [NUMBER] ）",
    "BLOCK_1567596489392": "视觉模块 [PORT] 锁定色块 [SIG] 到 [LOCATION] 轴 [NUMBER]  附近?",
    "BLOCK_1567596489393": "视觉模块 [PORT] 锁定条形码  [BARCODE] 到 [LOCATION] 轴 [NUMBER] 附近?"
};