export default {
    "neuron": "Neuron",
    "extensionName": "Neuron",
    "extensionDescription": "v0.0.1（20180928） v0.0.2(20180929)",
    "connect_fail_3eef6a81": "Asegúrate que el cable USB está conectado correctamente al dispositivo.",
    "connect_fail_2cdd56fc": "Asegúrate que el dispositivo a conectar está encendido.",
    "connect_fail_5f94d30a": "Solo puedes conectar un dispositivo a la vez, en esta versión. Si conectas este dispositivo, se desconectará el que ya está conectado.",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_0": "todos ",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_1": "conexión 1",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_2": "conexión 2",
    "neuron_run_dcmotor_with_time": "[ICON] motor C.C. [ID] gira [SLOT] a potencia [POWER]% durante [TIME] seg",
    "neuron_run_dcmotor_with_speed": "[ICON] motor C.C. [ID] gira [SLOT] a potencia [POWER]%",
    "neuron_run_dcmotors": "[ICON] motor C. C. [ID] slot1 gira a potencia [POWER_LEFT]%, slot2 gira a potencia [POWER_RIGHT]%",
    "neuron_run_servo": "[ICON] servo [ID] gira [SLOT] hasta [ANGLE] grados",
    "BLOCK_1566873821085": "[ICON] servo inteligente [index] gira por[angle] grados a velocidad de [speed] •",
    "BLOCK_1566873830496": "[ICON] servo inteligente [index] gira a [angle] grados a velocidad de [speed] •",
    "BLOCK_1566873904029": "[ICON] servo inteligente [index] En el sentido de las agujas del reloj gira a la potencia [speed_percent] % para [time] Segundos",
    "BLOCK_1566873923438": "[ICON] servo inteligente [index] En el sentido de las agujas del reloj gira a la potencia [speed_percent] %",
    "BLOCK_1566874019471": "[ICON] servo inteligente [index] deja de moverse",
    "BLOCK_1566874230002": "[ICON] servo inteligente [index] grados girados (o)",
    "BLOCK_1566874263478": "[ICON] servo inteligente [index] rondas rotadas",
    "BLOCK_1566874323828": "[ICON] servo inteligente [index] velocidad de rotación real (s)»",
    "BLOCK_1566874317863": "[ICON] servo inteligente [index] ángulo liberado",
    "BLOCK_1566874339176": "[ICON] servo inteligente [index] ángulo bloqueado",
    "BLOCK_1566985510345": "[ICON]servo inteligente [index]  posición actual como posición cero",
    "CATEGORY_ACTION": "Acción",
    "neuron_set_led_with_time": "[ICON] LED RGB [ID] encendido en [COLOR] durante [TIME] seg",
    "neuron_set_led": " [ICON] LED [ID] encendido en [COLOR]",
    "neuron_set_led_with_rgb": "[ICON] LED RGB [ID] en rojo [R] verde [G] azul [B]",
    "neuron_turn_off_led": "[ICON] LED apagado",
    "neuron_set_ledstrip_mode": "[ICON] tira de LED [ID] encendida [STRIP]",
    "neuron_set_ledstrip_with_color": "[ICON] tira LED [ID] encendido LED RGB [POSITION] en [COLOR]",
    "neuron_set_ledstrip_with_rgb": "[ICON] tira LED [ID] encendido LED RGB [POSITION] en rojo [R] verde [G] azul [B]",
    "neuron_turn_off_ledstrip": "[ICON] tira LED apagada",
    "neuron_set_ledpanel_with_time": "[ICON] panel LED [ID] muestra imagen [PANEL] durante [TIME] seg",
    "neuron_set_ledpanel_face": "[ICON] panel LED [ID] muestra imagen [PANEL]",
    "neuron_set_ledpanel_postion": "[ICON] panel LED [ID] encendido x: [X] y: [Y] en color [COLOR]",
    "neuron_set_ledpanel_postion_rgb": "[ICON] panel LED [ID] encendido x: [X] y: [Y] en rojo [R] verde [G] azul [B]",
    "neuron_turn_off_ledpanel_postion": "[ICON] panel LED [ID] apagado en x: [X] y: [Y]",
    "neuron_turn_off_ledpanel": "[ICON] panel LED apagado",
    "NEURON_DISPLAY_EMOTION_EMOTION_0": "normal",
    "NEURON_DISPLAY_EMOTION_EMOTION_1": "adormilado",
    "NEURON_DISPLAY_EMOTION_EMOTION_2": "triste",
    "NEURON_DISPLAY_EMOTION_EMOTION_3": "feliz",
    "NEURON_DISPLAY_EMOTION_EMOTION_4": "con gafas",
    "NEURON_DISPLAY_EMOTION_EMOTION_5": "enfadado",
    "NEURON_DISPLAY_EMOTION_EMOTION_6": "mirada fija",
    "NEURON_DISPLAY_EMOTION_EMOTION_7": "mirar de reojo",
    "neuron_display_emotion": "[ICON] pantalla [ID] muestra animación [EMOTION]",
    "neuron_display_emotion_with_time": "[ICON] pantalla [ID] muestra animación [EMOTION] durante [DURATION] seg",
    "NEURON_DISPLAY_ICON_ICON_ID_0": "aire",
    "NEURON_DISPLAY_ICON_ICON_ID_1": "marcas de verificación",
    "NEURON_DISPLAY_ICON_ICON_ID_2": "nube",
    "NEURON_DISPLAY_ICON_ICON_ID_3": "corazón",
    "NEURON_DISPLAY_ICON_ICON_ID_4": "luna",
    "NEURON_DISPLAY_ICON_ICON_ID_5": "lluvia",
    "NEURON_DISPLAY_ICON_ICON_ID_6": "anillo circular",
    "NEURON_DISPLAY_ICON_ICON_ID_7": "regla",
    "NEURON_DISPLAY_ICON_ICON_ID_8": "corriendo",
    "NEURON_DISPLAY_ICON_ICON_ID_9": "sonrisa",
    "NEURON_DISPLAY_ICON_ICON_ID_10": "nieve",
    "NEURON_DISPLAY_ICON_ICON_ID_11": "sol",
    "NEURON_DISPLAY_ICON_ICON_ID_12": "termómetro",
    "NEURON_DISPLAY_ICON_ICON_ID_13": "gota de agua",
    "NEURON_DISPLAY_ICON_ICON_ID_14": "ninguna",
    "neuron_display_icon": "[ICON] pantalla [ID] muestra icono [ICON_ID] y texto [STRING]",
    "neuron_display_icon_with_pos": "[ICON] pantalla [ID] muestra icono [ICON_ID_1] texto [STRING_1] en la línea superior e icono [ICON_ID_2] texto [STRING_2] en la línea inferior",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_0": "todos",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_1": "conexión 1",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_2": "conexión 2",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_3": "conexión 3",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_4": "conexión 4",
    "neuron_light_on_el_wiredriver": "[ICON] cable luminoso [ID] encendido en [SLOT]",
    "neuron_light_off_el_wiredriver": "[ICON] cable luminoso [ID] apagado en [SLOT]",
    "CATEGORY_SHOW": "Apariencia",
    "NEURON_PLAY_TONE_TONE_0": "C7",
    "NEURON_PLAY_TONE_TONE_1": "C2",
    "NEURON_PLAY_TONE_TONE_2": "D2",
    "NEURON_PLAY_TONE_TONE_3": "E2",
    "NEURON_PLAY_TONE_TONE_4": "F2",
    "NEURON_PLAY_TONE_TONE_5": "G2",
    "NEURON_PLAY_TONE_TONE_6": "A2",
    "NEURON_PLAY_TONE_TONE_7": "B2",
    "NEURON_PLAY_TONE_TONE_8": "C3",
    "NEURON_PLAY_TONE_TONE_9": "D3",
    "NEURON_PLAY_TONE_TONE_10": "E3",
    "NEURON_PLAY_TONE_TONE_11": "F3",
    "NEURON_PLAY_TONE_TONE_12": "Fa3#",
    "NEURON_PLAY_TONE_TONE_13": "G3",
    "NEURON_PLAY_TONE_TONE_14": "Sol3#",
    "NEURON_PLAY_TONE_TONE_15": "A3",
    "NEURON_PLAY_TONE_TONE_16": "La3#",
    "NEURON_PLAY_TONE_TONE_17": "B3",
    "NEURON_PLAY_TONE_TONE_18": "C4",
    "NEURON_PLAY_TONE_TONE_19": "Do4#",
    "NEURON_PLAY_TONE_TONE_20": "D4",
    "NEURON_PLAY_TONE_TONE_21": "Re4#",
    "NEURON_PLAY_TONE_TONE_22": "Mi4\n",
    "NEURON_PLAY_TONE_TONE_23": "F4",
    "NEURON_PLAY_TONE_TONE_24": "Fa4#",
    "NEURON_PLAY_TONE_TONE_25": "G4",
    "NEURON_PLAY_TONE_TONE_26": "Sol4#",
    "NEURON_PLAY_TONE_TONE_27": "A4",
    "NEURON_PLAY_TONE_TONE_28": "La4#",
    "NEURON_PLAY_TONE_TONE_29": "B4",
    "NEURON_PLAY_TONE_TONE_30": "C5",
    "NEURON_PLAY_TONE_TONE_31": "Do5#",
    "NEURON_PLAY_TONE_TONE_32": "D5",
    "NEURON_PLAY_TONE_TONE_33": "Re5#",
    "NEURON_PLAY_TONE_TONE_34": "E5",
    "NEURON_PLAY_TONE_TONE_35": "F5",
    "NEURON_PLAY_TONE_TONE_36": "G5",
    "NEURON_PLAY_TONE_TONE_37": "A5",
    "NEURON_PLAY_TONE_TONE_38": "B5",
    "NEURON_PLAY_TONE_TONE_39": "C6",
    "NEURON_PLAY_TONE_TONE_40": "D6",
    "NEURON_PLAY_TONE_TONE_41": "E6",
    "NEURON_PLAY_TONE_TONE_42": "F6",
    "NEURON_PLAY_TONE_TONE_43": "G6",
    "NEURON_PLAY_TONE_TONE_44": "A6",
    "NEURON_PLAY_TONE_TONE_45": "B6",
    "NEURON_PLAY_TONE_TONE_46": "D7",
    "NEURON_PLAY_TONE_TONE_47": "E7",
    "NEURON_PLAY_TONE_TONE_48": "F7",
    "NEURON_PLAY_TONE_TONE_49": "G7",
    "NEURON_PLAY_TONE_TONE_50": "A7",
    "NEURON_PLAY_TONE_TONE_51": "Si7",
    "NEURON_PLAY_TONE_TONE_52": "Do8",
    "neuron_play_tone": "[ICON] zumbador [ID] toca nota [TONE] durante [BEAT] tiempos",
    "neuron_play_hz": "[ICON] zumbador [ID] suena con frecuencia [HZ] Hz durante [TIME] seg",
    "CATEGORY_PLAY": "Sonido",
    "neuron_event_button_pressed": "[ICON] ¿pulsado el botón [ID]?",
    "neuron_detect_knob": "[ICON] valor del mando en [ID]",
    "neuron_detect_temperature": "[ICON] sensor de temperatura [ID] grados (℃)",
    "NEURON_EVENT_LINEFOLLOW_AXIS_0": "izquierda",
    "NEURON_EVENT_LINEFOLLOW_AXIS_1": "derecha",
    "NEURON_EVENT_LINEFOLLOW_AXIS_2": "todos",
    "NEURON_EVENT_LINEFOLLOW_AXIS_3": "ninguna",
    "neuron_event_linefollow": "[ICON] ¿detector de infrarrojos doble [ID] activado [AXIS]?",
    "neuron_detect_lightness": "[ICON] intensidad del sensor de luz [ID]",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_0": "azul",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_1": "amarillo",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_2": "rojo",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_3": "verde",
    "neuron_event_touch_color": "[ICON] ¿tocado [COLOR] del Funny Touch [ID]?",
    "neuron_detect_volume": "[ICON] volumen del sensor de sonido [ID]",
    "neuron_detect_ultrasonic": "[ICON] distancia del sensor de ultrasonidos [ID] (cm)",
    "NEURON_EVENT_TILT_DIRECTION_0": "hacia adelante",
    "NEURON_EVENT_TILT_DIRECTION_1": "hacia atrás",
    "NEURON_EVENT_TILT_DIRECTION_2": "hacia la izquierda",
    "NEURON_EVENT_TILT_DIRECTION_3": "hacia la derecha",
    "neuron_event_tilt": "[ICON] ¿giroscopio [ID] inclinado [DIRECTION]?",
    "neuron_event_shaked": "[ICON] ¿sensor giroscópico [ID] sacudido?",
    "NEURON_DETECT_GYRO_ANGLE_COORDINATE_0": "ángulo de balanceo",
    "NEURON_DETECT_GYRO_ANGLE_COORDINATE_1": "ángulo de inclinación",
    "neuron_detect_gyro_angle": "[ICON] giroscopio [ID] ángulo [COORDINATE] (º)",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_0": "x",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_1": "y",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_2": "z",
    "neuron_detect_gyro_speed": "[ICON] giroscopio [ID] aceleración [COORDINATE] m/s²",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_0": "rojo",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_1": "verde",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_2": "azul",
    "neuron_detect_color_sensor": "[ICON] sensor de color [ID] valor [COLOR]",
    "neuron_event_josystick_direction": "[ICON] ¿mando de juego [ID] movido [DIRECTION]?",
    "NEURON_DETECT_JOYSTICK_AXIS_0": "x",
    "NEURON_DETECT_JOYSTICK_AXIS_1": "y",
    "neuron_detect_joystick": "[ICON] mando de juego [ID] valor del eje [AXIS]",
    "neuron_event_pir": "[ICON] ¿sensor de presencia [ID] detecta personas?",
    "neuron_detect_humidity": "[ICON] valor del sensor de humedad del suelo [ID]",
    "op_ranging": "[ICON] distancia del sensor de ultrasonidos [ID] (cm)",
    "op_humidity": "[ICON] humedad del sensor de temperatura+humedad [ID] (%)",
    "op_temperature": "[ICON] temperatura del sensor de temperatura+humedad [ID] (ºC)",
    "op_htemperature": "[ICON] temperatura del sensor de temperatura+humedad [ID] (ºF)",
    "CATEGORY_SENSOR": "Sensores"
};