export default {
    "neuron": "Neuron",
    "extensionName": "Neuron",
    "extensionDescription": "v 0.0.1 (20180928) v 0.0.2 (20180929)",
    "connect_fail_3eef6a81": "Controleer of de USB-kabel is aangesloten op het apparaat.",
    "connect_fail_2cdd56fc": "Controleer of het aangesloten apparaat is ingeschakeld.",
    "connect_fail_5f94d30a": "Slechts één apparaat kan tegelijk worden aangesloten in deze versie. Het aansluiten van dit apparaat zal de verbinding met de vorige verbreken.",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_0": "alle ",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_1": "slot1",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_2": "slot2",
    "neuron_run_dcmotor_with_time": "[ICON] DC Motor [ID] [SLOT] rotates at power [POWER]% for [TIME] secs",
    "neuron_run_dcmotor_with_speed": "[ICON]DC Motor [ID] [SLOT] rotates at power [POWER]%",
    "neuron_run_dcmotors": "[ICON] DC Motor [ID] slot1 rotates at power [POWER_LEFT]% slot2 rotates at power [POWER_RIGHT]%",
    "neuron_run_servo": "[ICON] zet servo [ID] [SLOT] op [ANGLE] graden",
    "BLOCK_1566873821085": "[ICON] slimme servo [index] draait door[angle] graden op snelheid van [speed] °/s",
    "BLOCK_1566873830496": "[ICON] slimme servo [index] draait om [angle] graden op snelheid van [speed] °/s",
    "BLOCK_1566873904029": "[ICON] slimme servo [index] rechtsom draaien aan de macht [speed_percent] % voor [time] Seconden",
    "BLOCK_1566873923438": "[ICON] slimme servo [index] rechtsom draaien aan de macht [speed_percent] %",
    "BLOCK_1566874019471": "[ICON] slimme servo [index] stopt met bewegen",
    "BLOCK_1566874230002": "[ICON] slimme servo [index] gedraaide graden (°)",
    "BLOCK_1566874263478": "[ICON] slimme servo [index] geroteerde rondes",
    "BLOCK_1566874323828": "[ICON] slimme servo [index] werkelijke rotatiesnelheid (°/s)",
    "BLOCK_1566874317863": "[ICON] slimme servo [index] uitgebrachte hoek",
    "BLOCK_1566874339176": "[ICON] slimme servo [index] vergrendelde hoek",
    "BLOCK_1566985510345": "[ICON]slimme servo [index]  huidige positie als nulpositie",
    "CATEGORY_ACTION": "Actie",
    "neuron_set_led_with_time": "[ICON] RGB-LED [ID] licht [COLOR] aan voor [TIME] sec",
    "neuron_set_led": " [ICON] RGB LED [ID] licht op in [COLOR]",
    "neuron_set_led_with_rgb": "[ICON]Zet RGB LED [ID] rood [R] groen [G] blauw [B]",
    "neuron_turn_off_led": "[ICON] RGB LED lichten uit",
    "neuron_set_ledstrip_mode": "[ICON]LED Strip [ID] licht aan [STRIP]",
    "neuron_set_ledstrip_with_color": "[ICON] LED-Strip set [ID] zet [POSITION] RGB LED [COLOR]",
    "neuron_set_ledstrip_with_rgb": "[ICON] LED-Strip set [ID] zet [POSITION] RGB LED rood [R] groen [G] blauw [B]",
    "neuron_turn_off_ledstrip": "[ICON] LED Strip alle lichten uit",
    "neuron_set_ledpanel_with_time": "[ICON]LED panel [ID] toon beeld [PANEL] voor [TIME] sec",
    "neuron_set_ledpanel_face": "[ICON]LED panel [ID] toon beeld [PANEL]",
    "neuron_set_ledpanel_postion": "[ICON]LED Panel licht aan [ID] op x: [X] y: [Y] met kleur [COLOR]",
    "neuron_set_ledpanel_postion_rgb": "[ICON]LED Panel licht aan [ID] op x: [X] y: [Y] met rood [R] groen [G] blauw [B]",
    "neuron_turn_off_ledpanel_postion": "[ICON]LED panel licht uit [ID] op x: [X] y: [Y]",
    "neuron_turn_off_ledpanel": "[ICON] LED panel lichten uit",
    "NEURON_DISPLAY_EMOTION_EMOTION_0": "normaal",
    "NEURON_DISPLAY_EMOTION_EMOTION_1": "slaperig",
    "NEURON_DISPLAY_EMOTION_EMOTION_2": "Triest",
    "NEURON_DISPLAY_EMOTION_EMOTION_3": "blij",
    "NEURON_DISPLAY_EMOTION_EMOTION_4": "bril",
    "NEURON_DISPLAY_EMOTION_EMOTION_5": "Boos",
    "NEURON_DISPLAY_EMOTION_EMOTION_6": "staren",
    "NEURON_DISPLAY_EMOTION_EMOTION_7": "scheel",
    "neuron_display_emotion": "[ICON] display [ID] toon animatie [EMOTION]",
    "neuron_display_emotion_with_time": "[ICON]display [ID] toon animatie [EMOTION] voor [DURATION] sec",
    "NEURON_DISPLAY_ICON_ICON_ID_0": "lucht",
    "NEURON_DISPLAY_ICON_ICON_ID_1": "vinkjes",
    "NEURON_DISPLAY_ICON_ICON_ID_2": "wolk",
    "NEURON_DISPLAY_ICON_ICON_ID_3": "hart",
    "NEURON_DISPLAY_ICON_ICON_ID_4": "maan",
    "NEURON_DISPLAY_ICON_ICON_ID_5": "regen",
    "NEURON_DISPLAY_ICON_ICON_ID_6": "cirkelvormige ring",
    "NEURON_DISPLAY_ICON_ICON_ID_7": "liniaal",
    "NEURON_DISPLAY_ICON_ICON_ID_8": "rennen",
    "NEURON_DISPLAY_ICON_ICON_ID_9": "glimlach",
    "NEURON_DISPLAY_ICON_ICON_ID_10": "sneeuw",
    "NEURON_DISPLAY_ICON_ICON_ID_11": "zon",
    "NEURON_DISPLAY_ICON_ICON_ID_12": "thermometer",
    "NEURON_DISPLAY_ICON_ICON_ID_13": "waterdruppel",
    "NEURON_DISPLAY_ICON_ICON_ID_14": "geen",
    "neuron_display_icon": "[ICON]display [ID] toon pictogram [ICON_ID] met tekst [STRING]",
    "neuron_display_icon_with_pos": "[ICON]display [ID] toon pictogram [ICON_ID_1] tekst [STRING_1] op de bovenste regel, en toon pictogram [ICON_ID_2] tekst [STRING_2] op de regel daaronder",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_0": "alle",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_1": "slot1",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_2": "slot2",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_3": "slot3",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_4": "slot4",
    "neuron_light_on_el_wiredriver": "[ICON] EL [ID] licht aan bij [SLOT]",
    "neuron_light_off_el_wiredriver": "[ICON] EL [ID] licht uit bij [SLOT]",
    "CATEGORY_SHOW": "Uiterlijken",
    "NEURON_PLAY_TONE_TONE_0": "C7",
    "NEURON_PLAY_TONE_TONE_1": "C2",
    "NEURON_PLAY_TONE_TONE_2": "D2",
    "NEURON_PLAY_TONE_TONE_3": "E2",
    "NEURON_PLAY_TONE_TONE_4": "F2",
    "NEURON_PLAY_TONE_TONE_5": "G2",
    "NEURON_PLAY_TONE_TONE_6": "A2",
    "NEURON_PLAY_TONE_TONE_7": "B2",
    "NEURON_PLAY_TONE_TONE_8": "C3",
    "NEURON_PLAY_TONE_TONE_9": "D3",
    "NEURON_PLAY_TONE_TONE_10": "E3",
    "NEURON_PLAY_TONE_TONE_11": "F3",
    "NEURON_PLAY_TONE_TONE_12": "F3m",
    "NEURON_PLAY_TONE_TONE_13": "G3",
    "NEURON_PLAY_TONE_TONE_14": "G3m",
    "NEURON_PLAY_TONE_TONE_15": "A3",
    "NEURON_PLAY_TONE_TONE_16": "A3m",
    "NEURON_PLAY_TONE_TONE_17": "B3",
    "NEURON_PLAY_TONE_TONE_18": "C4",
    "NEURON_PLAY_TONE_TONE_19": "C4m",
    "NEURON_PLAY_TONE_TONE_20": "D4",
    "NEURON_PLAY_TONE_TONE_21": "D4m",
    "NEURON_PLAY_TONE_TONE_22": "E4\n",
    "NEURON_PLAY_TONE_TONE_23": "F4",
    "NEURON_PLAY_TONE_TONE_24": "F4m",
    "NEURON_PLAY_TONE_TONE_25": "G4",
    "NEURON_PLAY_TONE_TONE_26": "G4m",
    "NEURON_PLAY_TONE_TONE_27": "A4",
    "NEURON_PLAY_TONE_TONE_28": "A4m",
    "NEURON_PLAY_TONE_TONE_29": "B4",
    "NEURON_PLAY_TONE_TONE_30": "C5",
    "NEURON_PLAY_TONE_TONE_31": "C5m",
    "NEURON_PLAY_TONE_TONE_32": "D5",
    "NEURON_PLAY_TONE_TONE_33": "D5m",
    "NEURON_PLAY_TONE_TONE_34": "E5",
    "NEURON_PLAY_TONE_TONE_35": "F5",
    "NEURON_PLAY_TONE_TONE_36": "G5",
    "NEURON_PLAY_TONE_TONE_37": "A5",
    "NEURON_PLAY_TONE_TONE_38": "B5",
    "NEURON_PLAY_TONE_TONE_39": "C6",
    "NEURON_PLAY_TONE_TONE_40": "D6",
    "NEURON_PLAY_TONE_TONE_41": "E6",
    "NEURON_PLAY_TONE_TONE_42": "F6",
    "NEURON_PLAY_TONE_TONE_43": "G6",
    "NEURON_PLAY_TONE_TONE_44": "A6",
    "NEURON_PLAY_TONE_TONE_45": "B6",
    "NEURON_PLAY_TONE_TONE_46": "D7",
    "NEURON_PLAY_TONE_TONE_47": "E7",
    "NEURON_PLAY_TONE_TONE_48": "F7",
    "NEURON_PLAY_TONE_TONE_49": "G7",
    "NEURON_PLAY_TONE_TONE_50": "A7",
    "NEURON_PLAY_TONE_TONE_51": "B7",
    "NEURON_PLAY_TONE_TONE_52": "C8",
    "neuron_play_tone": "[ICON] buzzer [ID] speelt noot [TONE] voor [BEAT] slagen",
    "neuron_play_hz": "[ICON] buzzer [ID] speelt frequentie [HZ] voor [TIME] sec",
    "CATEGORY_PLAY": "Geluid",
    "neuron_event_button_pressed": "[ICON]is knop [ID] is ingedrukt?",
    "neuron_detect_knob": "[ICON]knop waarden bij [ID]",
    "neuron_detect_temperature": "[ICON] temperatuur sensor [ID] leest (°C) graden",
    "NEURON_EVENT_LINEFOLLOW_AXIS_0": "links",
    "NEURON_EVENT_LINEFOLLOW_AXIS_1": "rechts",
    "NEURON_EVENT_LINEFOLLOW_AXIS_2": "alle",
    "NEURON_EVENT_LINEFOLLOW_AXIS_3": "geen",
    "neuron_event_linefollow": "[ICON] dual IR detector [ID] [AXIS] geactiveerd?",
    "neuron_detect_lightness": "[ICON] lichtsensor [ID] lichtintensiteit",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_0": "blauw",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_1": "geel",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_2": "rood",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_3": "groen",
    "neuron_event_touch_color": "[ICON] touch schakelaar [ID] [COLOR] is aangeraakt?",
    "neuron_detect_volume": "[ICON] geluid sensor [ID] volume",
    "neuron_detect_ultrasonic": "[ICON] ultrasone sensor [ID] afstand (cm)",
    "NEURON_EVENT_TILT_DIRECTION_0": "vooruit",
    "NEURON_EVENT_TILT_DIRECTION_1": "achteruit",
    "NEURON_EVENT_TILT_DIRECTION_2": "naar links",
    "NEURON_EVENT_TILT_DIRECTION_3": "naar rechts",
    "neuron_event_tilt": "[ICON]gyro sensor [ID] gekanteld [DIRECTION]?",
    "neuron_event_shaked": "[ICON] gyro sensor [ID] schuddend?",
    "NEURON_DETECT_GYRO_ANGLE_COORDINATE_0": "rolhoek",
    "NEURON_DETECT_GYRO_ANGLE_COORDINATE_1": "werphoek",
    "neuron_detect_gyro_angle": "[ICON]gyro sensor [ID] [COORDINATE] hoek",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_0": "x",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_1": "y",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_2": "z",
    "neuron_detect_gyro_speed": "[ICON]gyro sensor [ID] [COORDINATE] versnelling m/s²",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_0": "rood",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_1": "groen",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_2": "blauw",
    "neuron_detect_color_sensor": "[ICON]kleursensor [ID] [COLOR] kleurwaarde",
    "neuron_event_josystick_direction": "[ICON] joystick [ID] [DIRECTION] schuddend?",
    "NEURON_DETECT_JOYSTICK_AXIS_0": "x",
    "NEURON_DETECT_JOYSTICK_AXIS_1": "y",
    "neuron_detect_joystick": "[ICON]joystick [ID] [AXIS] as waarde",
    "neuron_event_pir": "[ICON] pir sensor [ID] detecteert mensen?",
    "neuron_detect_humidity": "[ICON] bodemvochtigheid sensor [ID] vochtigheid",
    "op_ranging": "[ICON] afstandsdetecterende sensor [ID] afstand(cm)",
    "op_humidity": "[ICON]omgevingssensor [ID] vochtigheid(%)",
    "op_temperature": "[ICON] omgevingssensor [ID] temperatuur(℃)\n \n",
    "op_htemperature": "[ICON] omgevingssensor [ID] temperatuur(℉)",
    "CATEGORY_SENSOR": "Waarnemen"
};