export default {
    "neuron": "Neuron",
    "extensionName": "Neuron",
    "extensionDescription": "v0.0.1（20180928） v0.0.2(20180929)",
    "connect_fail_3eef6a81": "Upewnij się, że przewód USB jest prawidłowo podłączony do urządzenia.",
    "connect_fail_2cdd56fc": "Upewnij się, że podłączone urządzenie jest włączone.",
    "connect_fail_5f94d30a": "Jednocześnie w tej wersji można podłączyć tylko jedno urządzenie. Więc podłączenie tego urządzenia doprowadzi do odłączenia poprzedniej.",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_0": "wszystkie ",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_1": "slot1",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_2": "slot2",
    "neuron_run_dcmotor_with_time": "[ICON]Silnik [ID] [SLOT] obraca się przy zasilaniu [POWER] % przez [TIME] sekund",
    "neuron_run_dcmotor_with_speed": "[ICON]Silnik [ID] [SLOT] obraca się przy zasilaniu [POWER]%",
    "neuron_run_dcmotors": "[ICON] Silnik [ID] slot 1 obraca się przy zasilaniu [POWER_LEFT]% slot 2 obraca się przy zasilaniu [POWER_RIGHT]%",
    "neuron_run_servo": "[ICON]serwo [ID] [SLOT] obraca się do [ANGLE] stopni",
    "BLOCK_1566873821085": "[ICON] Inteligentne serwo [index] obraca się przez[angle] stopni przy prędkości [speed] °/s",
    "BLOCK_1566873830496": "[ICON] Inteligentne serwo [index] obraca się do [angle] stopni przy prędkości [speed] °/s",
    "BLOCK_1566873904029": "[ICON] Inteligentne serwo [index] obrót zgodnie z ruchem wskazówek zegara [speed_percent] % dla [time] Sekund",
    "BLOCK_1566873923438": "[ICON] Inteligentne serwo [index] obrót zgodnie z ruchem wskazówek zegara [speed_percent] %",
    "BLOCK_1566874019471": "[ICON] Inteligentne serwo [index] zatrzymuje się w ruchu",
    "BLOCK_1566874230002": "[ICON] Inteligentne serwo [index] obrócone stopnie (°)",
    "BLOCK_1566874263478": "[ICON] Inteligentne serwo [index] obrócone rundy",
    "BLOCK_1566874323828": "[ICON] Inteligentne serwo [index] Rzeczywista prędkość obrotowa (°/s)",
    "BLOCK_1566874317863": "[ICON] Inteligentne serwo [index] kąt zwolniony",
    "BLOCK_1566874339176": "[ICON] Inteligentne serwo [index] kąt zablokowany",
    "BLOCK_1566985510345": "[ICON]Inteligentne serwo [index]  aktualnej pozycji jako pozycji zerowej",
    "CATEGORY_ACTION": "Działania",
    "neuron_set_led_with_time": "[ICON]Dioda RGB LED [ID] świeci [COLOR] przez [TIME] sekund",
    "neuron_set_led": " [ICON] dioda LED RGB [ID] zapala się [COLOR]",
    "neuron_set_led_with_rgb": "[ICON]ustaw Diodę RGB LED [ID] czerwony [R] zielony [G] niebieski [B]",
    "neuron_turn_off_led": "[ICON]Dioda RGB LED światła wyłączone",
    "neuron_set_ledstrip_mode": "[ICON]Pasek LED [ID] świeci na [STRIP]",
    "neuron_set_ledstrip_with_color": "[ICON]ustaw pasek LED [ID] ustaw [POSITION] RGB LED [COLOR]",
    "neuron_set_ledstrip_with_rgb": "[ICON]ustaw pasek LED [ID] ustaw [POSITION] RGB LED czerwony [R] zielony [G] niebieski [B]",
    "neuron_turn_off_ledstrip": "[ICON]Światła paska LED wyłączone",
    "neuron_set_ledpanel_with_time": "[ICON]Panel LED [ID] pokazuje obraz[PANEL] przez [TIME] sekund",
    "neuron_set_ledpanel_face": "[ICON]Panel LED [ID] pokazuje obraz [PANEL]",
    "neuron_set_ledpanel_postion": "[ICON]Panel LED włącza się [ID] we współrzędnych x: [X] y: [Y] w kolorze [COLOR]",
    "neuron_set_ledpanel_postion_rgb": "[ICON]Panel LED włącza się[ID] w x: [X] y: [Y] z czerwonym [R] zielonym [G] niebieskim [B]",
    "neuron_turn_off_ledpanel_postion": "[ICON]Panel LED wyłącza się [ID] x: [X] y: [Y]",
    "neuron_turn_off_ledpanel": "[ICON]Światła panelu LED wyłączone",
    "NEURON_DISPLAY_EMOTION_EMOTION_0": "normalny",
    "NEURON_DISPLAY_EMOTION_EMOTION_1": "ospały",
    "NEURON_DISPLAY_EMOTION_EMOTION_2": "Smutne",
    "NEURON_DISPLAY_EMOTION_EMOTION_3": "szczęśliwy",
    "NEURON_DISPLAY_EMOTION_EMOTION_4": "wytrzeszczać oczy",
    "NEURON_DISPLAY_EMOTION_EMOTION_5": "Zły",
    "NEURON_DISPLAY_EMOTION_EMOTION_6": "wpatrywać się",
    "NEURON_DISPLAY_EMOTION_EMOTION_7": "zez",
    "neuron_display_emotion": "[ICON]ekran [ID] pokazuje animację [EMOTION]",
    "neuron_display_emotion_with_time": "[ICON]ekran [ID] pokazuje animację [EMOTION] przez [DURATION] sekund",
    "NEURON_DISPLAY_ICON_ICON_ID_0": "powietrze",
    "NEURON_DISPLAY_ICON_ICON_ID_1": "ptaszek",
    "NEURON_DISPLAY_ICON_ICON_ID_2": "chmura",
    "NEURON_DISPLAY_ICON_ICON_ID_3": "serce",
    "NEURON_DISPLAY_ICON_ICON_ID_4": "księżyc",
    "NEURON_DISPLAY_ICON_ICON_ID_5": "deszcz",
    "NEURON_DISPLAY_ICON_ICON_ID_6": "pierścień",
    "NEURON_DISPLAY_ICON_ICON_ID_7": "linijka",
    "NEURON_DISPLAY_ICON_ICON_ID_8": "bieg",
    "NEURON_DISPLAY_ICON_ICON_ID_9": "uśmiech",
    "NEURON_DISPLAY_ICON_ICON_ID_10": "śnieg",
    "NEURON_DISPLAY_ICON_ICON_ID_11": "słońce",
    "NEURON_DISPLAY_ICON_ICON_ID_12": "termometr",
    "NEURON_DISPLAY_ICON_ICON_ID_13": "kropla wody",
    "NEURON_DISPLAY_ICON_ICON_ID_14": "Brak",
    "neuron_display_icon": "[ICON]ekran [ID] pokazuje ikonę [ICON_ID] tekst [STRING]",
    "neuron_display_icon_with_pos": "[ICON]wyświetlacz [ID] pokazuje ikonę [ICON_ID_1] tekst [STRING_1] na wyższej linii i pokazuje ikonę [ICON_ID_2] tekst [STRING_2] na linii poniżej",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_0": "wszystkie",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_1": "slot1",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_2": "slot2",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_3": "slot3",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_4": "slot4",
    "neuron_light_on_el_wiredriver": "[ICON]Elektryczny [ID] zapala się na [SLOT]",
    "neuron_light_off_el_wiredriver": "[ICON]Elektryczny [ID] zgaśnie na [SLOT]",
    "CATEGORY_SHOW": "Wygląd",
    "NEURON_PLAY_TONE_TONE_0": "C7",
    "NEURON_PLAY_TONE_TONE_1": "C2",
    "NEURON_PLAY_TONE_TONE_2": "D2",
    "NEURON_PLAY_TONE_TONE_3": "E2",
    "NEURON_PLAY_TONE_TONE_4": "F2",
    "NEURON_PLAY_TONE_TONE_5": "G2",
    "NEURON_PLAY_TONE_TONE_6": "A2",
    "NEURON_PLAY_TONE_TONE_7": "B2",
    "NEURON_PLAY_TONE_TONE_8": "C3",
    "NEURON_PLAY_TONE_TONE_9": "D3",
    "NEURON_PLAY_TONE_TONE_10": "E3",
    "NEURON_PLAY_TONE_TONE_11": "F3",
    "NEURON_PLAY_TONE_TONE_12": "F3m",
    "NEURON_PLAY_TONE_TONE_13": "G3",
    "NEURON_PLAY_TONE_TONE_14": "G3m",
    "NEURON_PLAY_TONE_TONE_15": "A3",
    "NEURON_PLAY_TONE_TONE_16": "A3m",
    "NEURON_PLAY_TONE_TONE_17": "B3",
    "NEURON_PLAY_TONE_TONE_18": "C4",
    "NEURON_PLAY_TONE_TONE_19": "C4m",
    "NEURON_PLAY_TONE_TONE_20": "D4",
    "NEURON_PLAY_TONE_TONE_21": "D4m",
    "NEURON_PLAY_TONE_TONE_22": "E4\n",
    "NEURON_PLAY_TONE_TONE_23": "F4",
    "NEURON_PLAY_TONE_TONE_24": "F4m",
    "NEURON_PLAY_TONE_TONE_25": "G4",
    "NEURON_PLAY_TONE_TONE_26": "G4m",
    "NEURON_PLAY_TONE_TONE_27": "A4",
    "NEURON_PLAY_TONE_TONE_28": "A4m",
    "NEURON_PLAY_TONE_TONE_29": "B4",
    "NEURON_PLAY_TONE_TONE_30": "C5",
    "NEURON_PLAY_TONE_TONE_31": "C5m",
    "NEURON_PLAY_TONE_TONE_32": "D5",
    "NEURON_PLAY_TONE_TONE_33": "D5m",
    "NEURON_PLAY_TONE_TONE_34": "E5",
    "NEURON_PLAY_TONE_TONE_35": "F5",
    "NEURON_PLAY_TONE_TONE_36": "G5",
    "NEURON_PLAY_TONE_TONE_37": "A5",
    "NEURON_PLAY_TONE_TONE_38": "B5",
    "NEURON_PLAY_TONE_TONE_39": "C6",
    "NEURON_PLAY_TONE_TONE_40": "D6",
    "NEURON_PLAY_TONE_TONE_41": "E6",
    "NEURON_PLAY_TONE_TONE_42": "F6",
    "NEURON_PLAY_TONE_TONE_43": "G6",
    "NEURON_PLAY_TONE_TONE_44": "A6",
    "NEURON_PLAY_TONE_TONE_45": "B6",
    "NEURON_PLAY_TONE_TONE_46": "D7",
    "NEURON_PLAY_TONE_TONE_47": "E7",
    "NEURON_PLAY_TONE_TONE_48": "F7",
    "NEURON_PLAY_TONE_TONE_49": "G7",
    "NEURON_PLAY_TONE_TONE_50": "A7",
    "NEURON_PLAY_TONE_TONE_51": "B7",
    "NEURON_PLAY_TONE_TONE_52": "C8",
    "neuron_play_tone": "[ICON]brzęczyk [ID] odtwarza nutę [TONE] przez [BEAT] taktów",
    "neuron_play_hz": "[ICON]brzęczyk [ID] odtwarza z częstotliwością [HZ] przez [TIME] sekund",
    "CATEGORY_PLAY": "Dźwięku",
    "neuron_event_button_pressed": "[ICON]przycisk [ID] jest wciśnięty?",
    "neuron_detect_knob": "[ICON]wartości pokrętła na [ID]",
    "neuron_detect_temperature": "[ICON]czujnik temperatury [ID] stopnie (℃)",
    "NEURON_EVENT_LINEFOLLOW_AXIS_0": "Lewej",
    "NEURON_EVENT_LINEFOLLOW_AXIS_1": "Prawo",
    "NEURON_EVENT_LINEFOLLOW_AXIS_2": "wszystkie",
    "NEURON_EVENT_LINEFOLLOW_AXIS_3": "Brak",
    "neuron_event_linefollow": "[ICON]podwójny czujnik podczerwieni [ID] [AXIS] uruchomiony?",
    "neuron_detect_lightness": "[ICON]czujnik światła [ID] natężenie światła",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_0": "Niebieski",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_1": "Żółty",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_2": "Czerwony",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_3": "Zielony",
    "neuron_event_touch_color": "[ICON]przełącznik dotykowy [ID] [COLOR] jest dotknięty ?",
    "neuron_detect_volume": "[ICON]czujnik dźwięku [ID] głośność",
    "neuron_detect_ultrasonic": "[ICON]czujnik ultradźwiękowy [ID] odległość (cm)",
    "NEURON_EVENT_TILT_DIRECTION_0": "naprzód",
    "NEURON_EVENT_TILT_DIRECTION_1": "do tyłu",
    "NEURON_EVENT_TILT_DIRECTION_2": "do lewej",
    "NEURON_EVENT_TILT_DIRECTION_3": "w kierunku prawa",
    "neuron_event_tilt": "[ICON]czujnik żyroskopowy [ID] przechylony [DIRECTION]?",
    "neuron_event_shaked": "[ICON]czujnik żyroskopowy [ID] potrząśnięty?",
    "NEURON_DETECT_GYRO_ANGLE_COORDINATE_0": "kąt obrotu",
    "NEURON_DETECT_GYRO_ANGLE_COORDINATE_1": "kąt nachylenia",
    "neuron_detect_gyro_angle": "[ICON]czujnik żyroskopowy [ID] [COORDINATE] kąt",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_0": "X",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_1": "Y",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_2": "Z",
    "neuron_detect_gyro_speed": "[ICON]czujnik żyroskopowy [ID] [COORDINATE] przyspieszenie m/s²",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_0": "Czerwony",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_1": "Zielony",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_2": "Niebieski",
    "neuron_detect_color_sensor": "[ICON]czujnik koloru [ID] [COLOR] wartość",
    "neuron_event_josystick_direction": "[ICON]joystick [ID] [DIRECTION] trzęsie się?",
    "NEURON_DETECT_JOYSTICK_AXIS_0": "X",
    "NEURON_DETECT_JOYSTICK_AXIS_1": "Y",
    "neuron_detect_joystick": "[ICON]joystick [ID] [AXIS] wartość osi",
    "neuron_event_pir": "[ICON]czujnik ruchu PIR [ID] wykrywa ludzi?",
    "neuron_detect_humidity": "[ICON]czujnik nawilżenia gleby [ID] wilgotność",
    "op_ranging": "[ICON] Czujnik lokacji [ID] odległość (cm)",
    "op_humidity": "[ICON]Czujnik wilgotności [ID] wilgotność (%)",
    "op_temperature": "[ICON] czujnik wilgotności [ID] temperatura (℃)",
    "op_htemperature": "[ICON] czujnik wilgotności [ID] temperatura (F)",
    "CATEGORY_SENSOR": "Czujniki"
};