export default {
    "neuron": "Neuron",
    "extensionName": "Neuron",
    "extensionDescription": "v0.0.1（20180928） v0.0.2(20180929)",
    "connect_fail_3eef6a81": "Lütfen USB kablosunun doğru bağlandığından emin olun.",
    "connect_fail_2cdd56fc": "Lütfen bağlanan aygıtın açık olduğundan emin olun.",
    "connect_fail_5f94d30a": "Bu sürümde aynı anda sadece bir aygıt bağlanabilir. Yeni bir aygıt bağlamak, mevcut bağlantının kesilmesine yol açacaktır.",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_0": "hepsi ",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_1": "yuva1",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_2": "yuva2",
    "neuron_run_dcmotor_with_time": "[ICON] DC Motor [ID] [SLOT] dönsün [POWER]% güçte [TIME] saniye",
    "neuron_run_dcmotor_with_speed": "[ICON] DC motor [ID] [SLOT] dönsün [POWER]% güçte",
    "neuron_run_dcmotors": "[ICON] DC Motor [ID] yuva1 [POWER_LEFT]% güçte dönsün, yuva2 [POWER_RIGHT]% güçte dönsün",
    "neuron_run_servo": "[ICON] servo [ID] [SLOT] dönsün [ANGLE] derece",
    "BLOCK_1566873821085": "[ICON] akıllı servo [index] tarafından döndürülür[angle] hızında derece [speed] °/s",
    "BLOCK_1566873830496": "[ICON] akıllı servo [index] için döndürür [angle] hızında derece [speed] °/s",
    "BLOCK_1566873904029": "[ICON] akıllı servo [index] saat yönünde güçte döner [speed_percent] Için % [time] Saniye",
    "BLOCK_1566873923438": "[ICON] akıllı servo [index] saat yönünde güçte döner [speed_percent] %",
    "BLOCK_1566874019471": "[ICON] akıllı servo [index] hareket etmeyi durdurur",
    "BLOCK_1566874230002": "[ICON] akıllı servo [index] döndürülen dereceler (°)",
    "BLOCK_1566874263478": "[ICON] akıllı servo [index] döndürülmüş mermiler",
    "BLOCK_1566874323828": "[ICON] akıllı servo [index] gerçek dönüş hızı (°/s)",
    "BLOCK_1566874317863": "[ICON] akıllı servo [index] serbest açı",
    "BLOCK_1566874339176": "[ICON] akıllı servo [index] kilitli açı",
    "BLOCK_1566985510345": "[ICON]akıllı servo [index]  sıfır konum olarak geçerli konum",
    "CATEGORY_ACTION": "Hareket",
    "neuron_set_led_with_time": "[ICON] RGB LED [ID] ışıkları yak [COLOR] renkte [TIME] saniye",
    "neuron_set_led": " [ICON] RGB LED [ID] ışıkları yak [COLOR]",
    "neuron_set_led_with_rgb": "[ICON] RGB LED [ID] kırmızı [R] yeşil [G] mavi [B] yap",
    "neuron_turn_off_led": "[ICON] RGB LED ışıkları kapat",
    "neuron_set_ledstrip_mode": "[ICON] LED şerit [ID] ışıkları yak [STRIP]",
    "neuron_set_ledstrip_with_color": "[ICON] LED Şerit [ID] RGB LED [POSITION] [COLOR] yap",
    "neuron_set_ledstrip_with_rgb": "[ICON] LED Şerit [ID] RGB LED [POSITION] kırmızı [R] yeşil [G] mavi [B] yap",
    "neuron_turn_off_ledstrip": "[ICON] LED şerit ışıkları söndür",
    "neuron_set_ledpanel_with_time": "[ICON]LED panel [ID] resim göster [PANEL] de [TIME] saniye",
    "neuron_set_ledpanel_face": "[ICON]LED panel [ID] resim göster [PANEL]",
    "neuron_set_ledpanel_postion": "[ICON] LED panel [ID] ışıkları yak x: [X] Y: [Y] [COLOR] renkte",
    "neuron_set_ledpanel_postion_rgb": "[ICON] LED panel [ID] ışıkları yak x: [X] y: [Y] kırmızı [R] yeşil [G] mavi [B] renkte",
    "neuron_turn_off_ledpanel_postion": "[ICON]LED panel ışıkları kapat [ID] x: [X] Y: [Y]",
    "neuron_turn_off_ledpanel": "[ICON] LED panel ışıkları söndür",
    "NEURON_DISPLAY_EMOTION_EMOTION_0": "normal",
    "NEURON_DISPLAY_EMOTION_EMOTION_1": "uykulu",
    "NEURON_DISPLAY_EMOTION_EMOTION_2": "üzgün",
    "NEURON_DISPLAY_EMOTION_EMOTION_3": "mutlu",
    "NEURON_DISPLAY_EMOTION_EMOTION_4": "gözlüklü",
    "NEURON_DISPLAY_EMOTION_EMOTION_5": "kızgın",
    "NEURON_DISPLAY_EMOTION_EMOTION_6": "dik dik",
    "NEURON_DISPLAY_EMOTION_EMOTION_7": "şaşı",
    "neuron_display_emotion": "[ICON] ekran [ID] canlandırma göster [EMOTION]",
    "neuron_display_emotion_with_time": "[ICON] ekran [ID] canlandırma göster [EMOTION] [DURATION] saniye",
    "NEURON_DISPLAY_ICON_ICON_ID_0": "hava",
    "NEURON_DISPLAY_ICON_ICON_ID_1": "onay işaretleri",
    "NEURON_DISPLAY_ICON_ICON_ID_2": "bulut veri",
    "NEURON_DISPLAY_ICON_ICON_ID_3": "kalp",
    "NEURON_DISPLAY_ICON_ICON_ID_4": "ay",
    "NEURON_DISPLAY_ICON_ICON_ID_5": "yağmur",
    "NEURON_DISPLAY_ICON_ICON_ID_6": "yüzük",
    "NEURON_DISPLAY_ICON_ICON_ID_7": "cetvel",
    "NEURON_DISPLAY_ICON_ICON_ID_8": "koşu",
    "NEURON_DISPLAY_ICON_ICON_ID_9": "gülücük",
    "NEURON_DISPLAY_ICON_ICON_ID_10": "kar",
    "NEURON_DISPLAY_ICON_ICON_ID_11": "güneş",
    "NEURON_DISPLAY_ICON_ICON_ID_12": "termometre",
    "NEURON_DISPLAY_ICON_ICON_ID_13": "su damlası",
    "NEURON_DISPLAY_ICON_ICON_ID_14": "hiçbiri",
    "neuron_display_icon": "[ICON] ekran [ID] simge göster [ICON_ID] yazı [STRING]",
    "neuron_display_icon_with_pos": "[ICON] ekran [ID] üst satırda [ICON_ID_1] simge göster [STRING_1] yaz, alt satırda [ICON_ID_2] simge göster [STRING_2] yaz",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_0": "hepsi",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_1": "yuva1",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_2": "yuva2",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_3": "yuva3",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_4": "yuva4",
    "neuron_light_on_el_wiredriver": "[ICON]  [ID] EL [SLOT] ışıkları yak",
    "neuron_light_off_el_wiredriver": "[ICON] EL [ID] [SLOT] ışıkları kapat",
    "CATEGORY_SHOW": "Görünüm",
    "NEURON_PLAY_TONE_TONE_0": "C7",
    "NEURON_PLAY_TONE_TONE_1": "C2",
    "NEURON_PLAY_TONE_TONE_2": "D2",
    "NEURON_PLAY_TONE_TONE_3": "E2",
    "NEURON_PLAY_TONE_TONE_4": "F2",
    "NEURON_PLAY_TONE_TONE_5": "G2",
    "NEURON_PLAY_TONE_TONE_6": "A2",
    "NEURON_PLAY_TONE_TONE_7": "B2",
    "NEURON_PLAY_TONE_TONE_8": "C3",
    "NEURON_PLAY_TONE_TONE_9": "D3",
    "NEURON_PLAY_TONE_TONE_10": "E3",
    "NEURON_PLAY_TONE_TONE_11": "F3",
    "NEURON_PLAY_TONE_TONE_12": "F3m",
    "NEURON_PLAY_TONE_TONE_13": "G3",
    "NEURON_PLAY_TONE_TONE_14": "G3m",
    "NEURON_PLAY_TONE_TONE_15": "A3",
    "NEURON_PLAY_TONE_TONE_16": "A3m",
    "NEURON_PLAY_TONE_TONE_17": "B3",
    "NEURON_PLAY_TONE_TONE_18": "C4",
    "NEURON_PLAY_TONE_TONE_19": "C4m",
    "NEURON_PLAY_TONE_TONE_20": "D4",
    "NEURON_PLAY_TONE_TONE_21": "D4m",
    "NEURON_PLAY_TONE_TONE_22": "E4\n",
    "NEURON_PLAY_TONE_TONE_23": "F4",
    "NEURON_PLAY_TONE_TONE_24": "F4m",
    "NEURON_PLAY_TONE_TONE_25": "G4",
    "NEURON_PLAY_TONE_TONE_26": "G4m",
    "NEURON_PLAY_TONE_TONE_27": "A4",
    "NEURON_PLAY_TONE_TONE_28": "A4M",
    "NEURON_PLAY_TONE_TONE_29": "B4",
    "NEURON_PLAY_TONE_TONE_30": "C5",
    "NEURON_PLAY_TONE_TONE_31": "C5m",
    "NEURON_PLAY_TONE_TONE_32": "D5",
    "NEURON_PLAY_TONE_TONE_33": "D5m",
    "NEURON_PLAY_TONE_TONE_34": "E5",
    "NEURON_PLAY_TONE_TONE_35": "F5",
    "NEURON_PLAY_TONE_TONE_36": "G5",
    "NEURON_PLAY_TONE_TONE_37": "A5",
    "NEURON_PLAY_TONE_TONE_38": "B5",
    "NEURON_PLAY_TONE_TONE_39": "C6",
    "NEURON_PLAY_TONE_TONE_40": "D6",
    "NEURON_PLAY_TONE_TONE_41": "E6",
    "NEURON_PLAY_TONE_TONE_42": "F6",
    "NEURON_PLAY_TONE_TONE_43": "G6",
    "NEURON_PLAY_TONE_TONE_44": "A6",
    "NEURON_PLAY_TONE_TONE_45": "B6",
    "NEURON_PLAY_TONE_TONE_46": "D7",
    "NEURON_PLAY_TONE_TONE_47": "E7",
    "NEURON_PLAY_TONE_TONE_48": "F7",
    "NEURON_PLAY_TONE_TONE_49": "G7",
    "NEURON_PLAY_TONE_TONE_50": "A7",
    "NEURON_PLAY_TONE_TONE_51": "B7",
    "NEURON_PLAY_TONE_TONE_52": "C8",
    "neuron_play_tone": "[ICON] vızırtı [ID] [TONE] notasını çal [BEAT] vuruş",
    "neuron_play_hz": "[ICON] vızırtı [ID] [HZ] frekansını çal [TIME] saniye",
    "CATEGORY_PLAY": "Ses",
    "neuron_event_button_pressed": "[ICON] düğme [ID] basıldı?",
    "neuron_detect_knob": "[ICON] topuz [ID] değer",
    "neuron_detect_temperature": "[ICON] sıcaklık algılayıcı [ID] sıcaklık (℃)",
    "NEURON_EVENT_LINEFOLLOW_AXIS_0": "sol",
    "NEURON_EVENT_LINEFOLLOW_AXIS_1": "sağ",
    "NEURON_EVENT_LINEFOLLOW_AXIS_2": "hepsi",
    "NEURON_EVENT_LINEFOLLOW_AXIS_3": "hiçbiri",
    "neuron_event_linefollow": "[ICON] [ID] çift kızılötesi algılayıcı [AXIS] tetiklendi?",
    "neuron_detect_lightness": "[ICON] ışık algılayıcı [ID] ışık şiddeti",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_0": "mavi",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_1": "sarı",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_2": "kırmızı",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_3": "yeşil",
    "neuron_event_touch_color": "[ICON] Komik Dokunuş [ID] [COLOR] dokunuldu mu?",
    "neuron_detect_volume": "[ICON] ses algılayıcı [ID] ses şiddeti",
    "neuron_detect_ultrasonic": "[ICON] mesafe algılayıcı [ID] mesafe (cm)",
    "NEURON_EVENT_TILT_DIRECTION_0": "ileri",
    "NEURON_EVENT_TILT_DIRECTION_1": "geri",
    "NEURON_EVENT_TILT_DIRECTION_2": "sola doğru",
    "NEURON_EVENT_TILT_DIRECTION_3": "sağa doğru",
    "neuron_event_tilt": "[ICON] cayro algılayıcı [ID] eğilmiş [DIRECTION]?",
    "neuron_event_shaked": "[ICON] cayro algılayıcı [ID] sallanıyor?",
    "NEURON_DETECT_GYRO_ANGLE_COORDINATE_0": "\ndönüş açısı",
    "NEURON_DETECT_GYRO_ANGLE_COORDINATE_1": "eğim açısı",
    "neuron_detect_gyro_angle": "[ICON] cayro algılayıcı [ID] [COORDINATE] açısı(°)",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_0": "x",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_1": "y",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_2": "z",
    "neuron_detect_gyro_speed": "[ICON] cayro algılayıcı [ID] [COORDINATE] hızlanma m/s²",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_0": "kırmızı",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_1": "yeşil",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_2": "mavi",
    "neuron_detect_color_sensor": "[ICON] renk algılayıcı [ID] [COLOR] değer",
    "neuron_event_josystick_direction": "[ICON] oyun kolu [ID] [DIRECTION] sallanıyor?",
    "NEURON_DETECT_JOYSTICK_AXIS_0": "x",
    "NEURON_DETECT_JOYSTICK_AXIS_1": "y",
    "neuron_detect_joystick": "[ICON] oyun kolu [ID] [AXIS] eksen değeri",
    "neuron_event_pir": "[ICON] PIR algılayıcı [ID] insan algıladı?",
    "neuron_detect_humidity": "[ICON] toprak nem algılayıcı [ID] nem",
    "op_ranging": "[ICON] mesafe algılayıcı [ID] mesafe(cm)",
    "op_humidity": "[ICON]nem algılayıcı [ID] nem(%)",
    "op_temperature": "[ICON] nem algılayıcı [ID] sıcaklık(℃)",
    "op_htemperature": "[ICON] nem algılayıcı [ID] sıcaklık(℉)",
    "CATEGORY_SENSOR": "Algılanıyor"
};