export default {
    "neuron": "Neuron",
    "extensionName": "Neuron",
    "extensionDescription": "v0.0.1 (20180928) v0.0.2 (20180929)",
    "connect_fail_3eef6a81": "Переконайтеся, що USB-кабель правильно під'єднано до пристрою.",
    "connect_fail_2cdd56fc": "Переконайтеся, що пристрій увімкнуто.",
    "connect_fail_5f94d30a": "Одночасно в цій версії можна підключити тільки один пристрій. Підключення нового пристрою призведе до відключення попереднього.",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_0": "всі ",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_1": "роз'єм1",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_2": "роз'єм2",
    "neuron_run_dcmotor_with_time": "[ICON] Мотор постійного струму [ID] [SLOT] обертати зі швидкістю [POWER] % [TIME] сек",
    "neuron_run_dcmotor_with_speed": "[ICON] Мотор постійного струму [ID] [SLOT] обертати зі швидкістю [POWER]%",
    "neuron_run_dcmotors": "[ICON] Мотори постійного струму обертати зі швидкістю: [ID] Порт1 [POWER_LEFT]%, Порт2 [POWER_RIGHT]%",
    "neuron_run_servo": "[ICON] серво [ID] [SLOT] обертати на [ANGLE] градусів",
    "BLOCK_1566873821085": "[ICON] смарт серво [index] обертатися на [angle]° зі швидкістю [speed] °/сек",
    "BLOCK_1566873830496": "[ICON] смарт серво [index] обертатися до [angle]° зі швидкістю [speed] °/сек",
    "BLOCK_1566873904029": "[ICON] смарт серво [index] обертатися за годинниковою стрілкою зі швидкістю [speed_percent] % [time] сек",
    "BLOCK_1566873923438": "[ICON] смарт серво [index] обертатися за годинниковою стрілкою зі швидкістю [speed_percent] %",
    "BLOCK_1566874019471": "[ICON] смарт серво [index] зупинитись",
    "BLOCK_1566874230002": "[ICON] смарт серво [index] обертатися градусів (°)",
    "BLOCK_1566874263478": "[ICON] смарт серво [index] обертатися обертів",
    "BLOCK_1566874323828": "[ICON] смарт серво [index] швидкість обертання (°/сек)",
    "BLOCK_1566874317863": "[ICON] смарт серво [index] кут фіксації",
    "BLOCK_1566874339176": "[ICON] смарт серво [index] кут звільнення",
    "BLOCK_1566985510345": "[ICON]смарт серво [index] задати поточну позицію як нульову",
    "CATEGORY_ACTION": "Дія",
    "neuron_set_led_with_time": "[ICON] LED блок [ID] світитись [COLOR] [TIME] сек",
    "neuron_set_led": " [ICON] LED світлодіод [ID] світитись [COLOR]",
    "neuron_set_led_with_rgb": "[ICON] RGB LED блок [ID] світитись червоним [R] зеленим [G] синім [B]",
    "neuron_turn_off_led": "[ICON] Вимкнути LED блок",
    "neuron_set_ledstrip_mode": "[ICON] LED стрічка [ID] увімкнути [STRIP]",
    "neuron_set_ledstrip_with_color": "[ICON] LED стрічка [ID] світлодіод [POSITION] світитись кольором [COLOR]",
    "neuron_set_ledstrip_with_rgb": "[ICON] LED стрічка [ID] світлодіод [POSITION] задати колір червоний [R] зелений [G] синій [B]",
    "neuron_turn_off_ledstrip": "[ICON] Вимкнути вогні LED стрічки",
    "neuron_set_ledpanel_with_time": "[ICON] LED панель [ID] вивести зображення [PANEL] на [TIME] сек",
    "neuron_set_ledpanel_face": "[ICON] LED панель [ID] вивести зображення [PANEL]",
    "neuron_set_ledpanel_postion": "[ICON] LED панель [ID] увімкнути світлодіод, координати x: [X] y: [Y], колір [COLOR]",
    "neuron_set_ledpanel_postion_rgb": "[ICON] LED панель [ID]увімкнути світлодіод, координати x: [X] y: [Y], колір: червоний [R] зелений [G] синій [B]",
    "neuron_turn_off_ledpanel_postion": "[ICON] LED панель [ID] вимкнути світлодіод, координати x: [X] y: [Y]",
    "neuron_turn_off_ledpanel": "[ICON] Вимкнути вогні LED панелі",
    "NEURON_DISPLAY_EMOTION_EMOTION_0": "звичайний",
    "NEURON_DISPLAY_EMOTION_EMOTION_1": "сонний",
    "NEURON_DISPLAY_EMOTION_EMOTION_2": "сумний",
    "NEURON_DISPLAY_EMOTION_EMOTION_3": "щасливий",
    "NEURON_DISPLAY_EMOTION_EMOTION_4": "в окулярах",
    "NEURON_DISPLAY_EMOTION_EMOTION_5": "сердитий",
    "NEURON_DISPLAY_EMOTION_EMOTION_6": "витріщається",
    "NEURON_DISPLAY_EMOTION_EMOTION_7": "косий погляд",
    "neuron_display_emotion": "[ICON] дисплей [ID] вивести анімацію [EMOTION]",
    "neuron_display_emotion_with_time": "[ICON] дисплей [ID] вивести анімацію [EMOTION] впродовж [DURATION] сек",
    "NEURON_DISPLAY_ICON_ICON_ID_0": "повітря",
    "NEURON_DISPLAY_ICON_ICON_ID_1": "позначка",
    "NEURON_DISPLAY_ICON_ICON_ID_2": "хмара",
    "NEURON_DISPLAY_ICON_ICON_ID_3": "серце",
    "NEURON_DISPLAY_ICON_ICON_ID_4": "місяць",
    "NEURON_DISPLAY_ICON_ICON_ID_5": "дощ",
    "NEURON_DISPLAY_ICON_ICON_ID_6": "кільце",
    "NEURON_DISPLAY_ICON_ICON_ID_7": "лінійка",
    "NEURON_DISPLAY_ICON_ICON_ID_8": "біг",
    "NEURON_DISPLAY_ICON_ICON_ID_9": "посмішка",
    "NEURON_DISPLAY_ICON_ICON_ID_10": "сніг",
    "NEURON_DISPLAY_ICON_ICON_ID_11": "сонце",
    "NEURON_DISPLAY_ICON_ICON_ID_12": "термометр",
    "NEURON_DISPLAY_ICON_ICON_ID_13": "крапля води",
    "NEURON_DISPLAY_ICON_ICON_ID_14": "нічого",
    "neuron_display_icon": "[ICON] дисплей [ID] вивести значок [ICON_ID] текст [STRING]",
    "neuron_display_icon_with_pos": "[ICON] дисплей [ID] вивести значок [ICON_ID_1] текст [STRING_1] на верхньому рядку і значок [ICON_ID_2] і текст [STRING_2] на нижньому рядку",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_0": "всі",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_1": "роз'єм1",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_2": "роз'єм2",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_3": "роз'єм 3",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_4": "роз'єм 4",
    "neuron_light_on_el_wiredriver": "[ICON] Увімкнути світлодіод [ID][SLOT]",
    "neuron_light_off_el_wiredriver": "[ICON] Вимкнути світлодіод[ID][SLOT]",
    "CATEGORY_SHOW": "Вигляд",
    "NEURON_PLAY_TONE_TONE_0": "C7",
    "NEURON_PLAY_TONE_TONE_1": "C2",
    "NEURON_PLAY_TONE_TONE_2": "D2",
    "NEURON_PLAY_TONE_TONE_3": "E2",
    "NEURON_PLAY_TONE_TONE_4": "F2",
    "NEURON_PLAY_TONE_TONE_5": "G2",
    "NEURON_PLAY_TONE_TONE_6": "A2",
    "NEURON_PLAY_TONE_TONE_7": "B2",
    "NEURON_PLAY_TONE_TONE_8": "C3",
    "NEURON_PLAY_TONE_TONE_9": "D3",
    "NEURON_PLAY_TONE_TONE_10": "E3",
    "NEURON_PLAY_TONE_TONE_11": "F3",
    "NEURON_PLAY_TONE_TONE_12": "F3m",
    "NEURON_PLAY_TONE_TONE_13": "G3",
    "NEURON_PLAY_TONE_TONE_14": "G3m",
    "NEURON_PLAY_TONE_TONE_15": "A3",
    "NEURON_PLAY_TONE_TONE_16": "A3m",
    "NEURON_PLAY_TONE_TONE_17": "B3",
    "NEURON_PLAY_TONE_TONE_18": "C4",
    "NEURON_PLAY_TONE_TONE_19": "C4m",
    "NEURON_PLAY_TONE_TONE_20": "D4",
    "NEURON_PLAY_TONE_TONE_21": "D4m",
    "NEURON_PLAY_TONE_TONE_22": "E4\n",
    "NEURON_PLAY_TONE_TONE_23": "F4",
    "NEURON_PLAY_TONE_TONE_24": "F4m",
    "NEURON_PLAY_TONE_TONE_25": "G4",
    "NEURON_PLAY_TONE_TONE_26": "G4m",
    "NEURON_PLAY_TONE_TONE_27": "A4",
    "NEURON_PLAY_TONE_TONE_28": "A4m",
    "NEURON_PLAY_TONE_TONE_29": "B4",
    "NEURON_PLAY_TONE_TONE_30": "C5",
    "NEURON_PLAY_TONE_TONE_31": "C5m",
    "NEURON_PLAY_TONE_TONE_32": "D5",
    "NEURON_PLAY_TONE_TONE_33": "D5m",
    "NEURON_PLAY_TONE_TONE_34": "E5",
    "NEURON_PLAY_TONE_TONE_35": "F5",
    "NEURON_PLAY_TONE_TONE_36": "G5",
    "NEURON_PLAY_TONE_TONE_37": "A5",
    "NEURON_PLAY_TONE_TONE_38": "B5",
    "NEURON_PLAY_TONE_TONE_39": "C6",
    "NEURON_PLAY_TONE_TONE_40": "D6",
    "NEURON_PLAY_TONE_TONE_41": "E6",
    "NEURON_PLAY_TONE_TONE_42": "F6",
    "NEURON_PLAY_TONE_TONE_43": "G6",
    "NEURON_PLAY_TONE_TONE_44": "A6",
    "NEURON_PLAY_TONE_TONE_45": "B6",
    "NEURON_PLAY_TONE_TONE_46": "D7",
    "NEURON_PLAY_TONE_TONE_47": "E7",
    "NEURON_PLAY_TONE_TONE_48": "F7",
    "NEURON_PLAY_TONE_TONE_49": "G7",
    "NEURON_PLAY_TONE_TONE_50": "A7",
    "NEURON_PLAY_TONE_TONE_51": "B7",
    "NEURON_PLAY_TONE_TONE_52": "C8",
    "neuron_play_tone": "[ICON] зуммер [ID] грати ноту [TONE] [BEAT] долей",
    "neuron_play_hz": "[ICON] зумер [ID] грати на частоті [HZ] Гц [TIME] сек",
    "CATEGORY_PLAY": "Звук",
    "neuron_event_button_pressed": "[ICON] чи натиснута кнопка [ID]?",
    "neuron_detect_knob": "[ICON] значення ручки [ID]",
    "neuron_detect_temperature": "[ICON] датчик температури [ID] температура (℃)",
    "NEURON_EVENT_LINEFOLLOW_AXIS_0": "ліворуч",
    "NEURON_EVENT_LINEFOLLOW_AXIS_1": "праворуч",
    "NEURON_EVENT_LINEFOLLOW_AXIS_2": "Всі",
    "NEURON_EVENT_LINEFOLLOW_AXIS_3": "нічого",
    "neuron_event_linefollow": "[ICON] спрацював подвійний ІЧ датчик [ID] [AXIS]?",
    "neuron_detect_lightness": "[ICON] датчик світла [ID] яскравість",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_0": "синій",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_1": "жовтий",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_2": "червоний",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_3": "зелений",
    "neuron_event_touch_color": "[ICON] спрацював сенсорний перемикач [ID] [COLOR]?",
    "neuron_detect_volume": "[ICON] гучність датчика звуку [ID]",
    "neuron_detect_ultrasonic": "[ICON] ультразвуковий датчик [ID] відстань (см)",
    "NEURON_EVENT_TILT_DIRECTION_0": "вперед",
    "NEURON_EVENT_TILT_DIRECTION_1": "назад",
    "NEURON_EVENT_TILT_DIRECTION_2": "вперед і ліворуч",
    "NEURON_EVENT_TILT_DIRECTION_3": "вперед і праворуч",
    "neuron_event_tilt": "[ICON] гіроскоп [ID] нахилений [DIRECTION]?",
    "neuron_event_shaked": "[ICON] гіроскоп [ID] труситься?",
    "NEURON_DETECT_GYRO_ANGLE_COORDINATE_0": "кут руху",
    "NEURON_DETECT_GYRO_ANGLE_COORDINATE_1": "кут нахилу",
    "neuron_detect_gyro_angle": "[ICON] гіроскоп [ID] [COORDINATE] кут (°)",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_0": "x",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_1": "y",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_2": "z",
    "neuron_detect_gyro_speed": "[ICON] гіроскоп [ID][COORDINATE] прискорення м/с²",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_0": "червоний",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_1": "зелений",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_2": "синій",
    "neuron_detect_color_sensor": "[ICON] значення датчика кольору [ID] [COLOR]",
    "neuron_event_josystick_direction": "[ICON] джойстик [ID] [DIRECTION] труситься?",
    "NEURON_DETECT_JOYSTICK_AXIS_0": "x",
    "NEURON_DETECT_JOYSTICK_AXIS_1": "y",
    "neuron_detect_joystick": "[ICON] джойстик [ID] вісь [AXIS] значення",
    "neuron_event_pir": "[ICON] пІЧ датчик [ID] виявив людину?",
    "neuron_detect_humidity": "[ICON] датчик вологості грунту [ID] вологість",
    "op_ranging": "[ICON] ультразвуковий датчик [ID] відстань (см)",
    "op_humidity": "[ICON] датчик вологості [ID] вологість(%)",
    "op_temperature": "[ICON] датчик температури і вологості [ID] температура(℃)",
    "op_htemperature": "[ICON] датчик температури і вологості [ID] температура(℉)",
    "CATEGORY_SENSOR": "Сенсори"
};