export default {
    "neuron": "Neuron",
    "extensionName": "Neuron",
    "extensionDescription": "v0.0.1（20180928） v0.0.2(20180929)",
    "connect_fail_3eef6a81": "請確保 USB 電纜已正確連接到設備。",
    "connect_fail_2cdd56fc": "請確保要連接的設備已打開。",
    "connect_fail_5f94d30a": "在此版本中, 一次只能連接一個設備。因此, 連接此設備將導致斷開前一個設備的連接。",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_0": "全部插座 ",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_1": "插座1",
    "NEURON_RUN_DCMOTOR_WITH_TIME_SLOT_2": "插座2",
    "neuron_run_dcmotor_with_time": "[ICON] 直流馬達[ID][SLOT] 以動力[POWER]% 轉動[TIME] 秒",
    "neuron_run_dcmotor_with_speed": "[ICON] 直流馬達 [ID] [SLOT] 以動力 [POWER]% 轉動",
    "neuron_run_dcmotors": "[ICON] 直流馬達 [ID] 插座1動力 [POWER_LEFT]%，插座2動力[POWER_RIGHT]%",
    "neuron_run_servo": "[ICON] 伺服馬達 [ID] [SLOT] 定位至 [ANGLE] 度",
    "BLOCK_1566873821085": "[ICON] 智能伺服 [index] 旋轉 [angle] 度，速度 [speed] °/s",
    "BLOCK_1566873830496": "[ICON] 智能伺服 [index] 旋轉到 [angle] 度，速度 [speed] °/s",
    "BLOCK_1566873904029": "[ICON] 智能伺服 [index] 順時針旋轉，動力 [speed_percent] %，持續 [time] 秒",
    "BLOCK_1566873923438": "[ICON] 智能伺服 [index] 順時針旋轉，動力 [speed_percent] %",
    "BLOCK_1566874019471": "[ICON] 智能伺服 [index] 停止動作",
    "BLOCK_1566874230002": "[ICON] 智能伺服 [index] 旋轉過的角度 (°)",
    "BLOCK_1566874263478": "[ICON] 智能伺服 [index] 旋轉圈數",
    "BLOCK_1566874323828": "[ICON] 智能伺服 [index] 實際轉速 （°/s）",
    "BLOCK_1566874317863": "[ICON] 智能伺服 [index] 釋放時的角度",
    "BLOCK_1566874339176": "[ICON] 智能伺服 [index] 鎖定時的角度",
    "BLOCK_1566985510345": "[ICON]智能伺服 [index] 設定當前位置為零點",
    "CATEGORY_ACTION": "運動",
    "neuron_set_led_with_time": "[ICON] LED 燈 [ID] 的顏色設為 [COLOR]，持續 [TIME] 秒",
    "neuron_set_led": " [ICON] LED 燈 [ID] 的顏色設為 [COLOR]",
    "neuron_set_led_with_rgb": "[ICON] LED 燈 [ID] 的配色數值為 紅[R] 綠[G] 藍[B]",
    "neuron_turn_off_led": "[ICON] RGB LED 燈熄滅",
    "neuron_set_ledstrip_mode": "[ICON] LED燈條 [ID] 點亮 [STRIP]",
    "neuron_set_ledstrip_with_color": "[ICON] LED 燈條 [ID] 位置 [POSITION] 的顏色設為 [COLOR]",
    "neuron_set_ledstrip_with_rgb": "[ICON] LED 燈條 [ID] [POSITION] 位置的配色數值為 紅[R] 綠[G] 藍[B]",
    "neuron_turn_off_ledstrip": "[ICON] LED 燈條熄滅",
    "neuron_set_ledpanel_with_time": "[ICON] LED面板 [ID] 顯示圖案 [PANEL] 持續 [TIME] 秒",
    "neuron_set_ledpanel_face": "[ICON] LED面板 [ID] 顯示圖案 [PANEL]",
    "neuron_set_ledpanel_postion": "[ICON] LED面板 [ID] 亮起 x: [X] y: [Y] 的顏色為 [COLOR]",
    "neuron_set_ledpanel_postion_rgb": "[ICON] LED面板 [ID] 位置 x: [X] y: [Y] 設定為紅 [R] 綠 [G] 藍 [B]",
    "neuron_turn_off_ledpanel_postion": "[ICON] LED面板 [ID] 熄滅 x: [X] y: [Y] 位置的燈",
    "neuron_turn_off_ledpanel": "[ICON] 清除LED面板顯示",
    "NEURON_DISPLAY_EMOTION_EMOTION_0": "一般",
    "NEURON_DISPLAY_EMOTION_EMOTION_1": "昏昏欲睡",
    "NEURON_DISPLAY_EMOTION_EMOTION_2": "傷心",
    "NEURON_DISPLAY_EMOTION_EMOTION_3": "快樂",
    "NEURON_DISPLAY_EMOTION_EMOTION_4": "瞪眼",
    "NEURON_DISPLAY_EMOTION_EMOTION_5": "生氣",
    "NEURON_DISPLAY_EMOTION_EMOTION_6": "盯著",
    "NEURON_DISPLAY_EMOTION_EMOTION_7": "眯眼",
    "neuron_display_emotion": "[ICON] 液晶螢幕 [ID] 顯示動畫 [EMOTION]",
    "neuron_display_emotion_with_time": "[ICON] 液晶螢幕 [ID] 顯示動畫 [EMOTION]，持續 [DURATION] 秒",
    "NEURON_DISPLAY_ICON_ICON_ID_0": "空氣",
    "NEURON_DISPLAY_ICON_ICON_ID_1": "勾選記號",
    "NEURON_DISPLAY_ICON_ICON_ID_2": "雲朵",
    "NEURON_DISPLAY_ICON_ICON_ID_3": "愛心",
    "NEURON_DISPLAY_ICON_ICON_ID_4": "月亮",
    "NEURON_DISPLAY_ICON_ICON_ID_5": "下雨",
    "NEURON_DISPLAY_ICON_ICON_ID_6": "圓環",
    "NEURON_DISPLAY_ICON_ICON_ID_7": "直尺",
    "NEURON_DISPLAY_ICON_ICON_ID_8": "奔跑",
    "NEURON_DISPLAY_ICON_ICON_ID_9": "微笑",
    "NEURON_DISPLAY_ICON_ICON_ID_10": "下雪",
    "NEURON_DISPLAY_ICON_ICON_ID_11": "太陽",
    "NEURON_DISPLAY_ICON_ICON_ID_12": "溫度計",
    "NEURON_DISPLAY_ICON_ICON_ID_13": "水滴",
    "NEURON_DISPLAY_ICON_ICON_ID_14": "沒有",
    "neuron_display_icon": "[ICON] 液晶螢幕 [ID] 顯示圖示 [ICON_ID] ，文字 [STRING]",
    "neuron_display_icon_with_pos": "[ICON] 液晶螢幕 [ID] 上行顯示圖示 [ICON_ID_1] ，文字 [STRING_1]；下行顯示圖示 [ICON_ID_2] ，文字[STRING_2]",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_0": "全部",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_1": "插座1",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_2": "插座2",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_3": "插座3",
    "NEURON_LIGHT_ON_EL_WIREDRIVER_SLOT_4": "插座4",
    "neuron_light_on_el_wiredriver": "[ICON] 冷光線 [ID] [SLOT] 亮起",
    "neuron_light_off_el_wiredriver": "[ICON] 冷光線 [ID] [SLOT] 熄滅",
    "CATEGORY_SHOW": "外觀",
    "NEURON_PLAY_TONE_TONE_0": "C7",
    "NEURON_PLAY_TONE_TONE_1": "C2",
    "NEURON_PLAY_TONE_TONE_2": "D2",
    "NEURON_PLAY_TONE_TONE_3": "E2",
    "NEURON_PLAY_TONE_TONE_4": "F2",
    "NEURON_PLAY_TONE_TONE_5": "G2",
    "NEURON_PLAY_TONE_TONE_6": "A2",
    "NEURON_PLAY_TONE_TONE_7": "B2",
    "NEURON_PLAY_TONE_TONE_8": "C3",
    "NEURON_PLAY_TONE_TONE_9": "D3",
    "NEURON_PLAY_TONE_TONE_10": "E3",
    "NEURON_PLAY_TONE_TONE_11": "F3",
    "NEURON_PLAY_TONE_TONE_12": "F3m",
    "NEURON_PLAY_TONE_TONE_13": "G3",
    "NEURON_PLAY_TONE_TONE_14": "G3m",
    "NEURON_PLAY_TONE_TONE_15": "A3",
    "NEURON_PLAY_TONE_TONE_16": "A3m",
    "NEURON_PLAY_TONE_TONE_17": "B3",
    "NEURON_PLAY_TONE_TONE_18": "C4",
    "NEURON_PLAY_TONE_TONE_19": "C4m",
    "NEURON_PLAY_TONE_TONE_20": "D4",
    "NEURON_PLAY_TONE_TONE_21": "D4m",
    "NEURON_PLAY_TONE_TONE_22": "E4\n",
    "NEURON_PLAY_TONE_TONE_23": "F4",
    "NEURON_PLAY_TONE_TONE_24": "F4m",
    "NEURON_PLAY_TONE_TONE_25": "G4",
    "NEURON_PLAY_TONE_TONE_26": "G4m",
    "NEURON_PLAY_TONE_TONE_27": "A4",
    "NEURON_PLAY_TONE_TONE_28": "A4m",
    "NEURON_PLAY_TONE_TONE_29": "B4",
    "NEURON_PLAY_TONE_TONE_30": "C5",
    "NEURON_PLAY_TONE_TONE_31": "C5m",
    "NEURON_PLAY_TONE_TONE_32": "D5",
    "NEURON_PLAY_TONE_TONE_33": "D5m",
    "NEURON_PLAY_TONE_TONE_34": "E5",
    "NEURON_PLAY_TONE_TONE_35": "F5",
    "NEURON_PLAY_TONE_TONE_36": "G5",
    "NEURON_PLAY_TONE_TONE_37": "A5",
    "NEURON_PLAY_TONE_TONE_38": "B5",
    "NEURON_PLAY_TONE_TONE_39": "C6",
    "NEURON_PLAY_TONE_TONE_40": "D6",
    "NEURON_PLAY_TONE_TONE_41": "E6",
    "NEURON_PLAY_TONE_TONE_42": "F6",
    "NEURON_PLAY_TONE_TONE_43": "G6",
    "NEURON_PLAY_TONE_TONE_44": "A6",
    "NEURON_PLAY_TONE_TONE_45": "B6",
    "NEURON_PLAY_TONE_TONE_46": "D7",
    "NEURON_PLAY_TONE_TONE_47": "E7",
    "NEURON_PLAY_TONE_TONE_48": "F7",
    "NEURON_PLAY_TONE_TONE_49": "G7",
    "NEURON_PLAY_TONE_TONE_50": "A7",
    "NEURON_PLAY_TONE_TONE_51": "B7",
    "NEURON_PLAY_TONE_TONE_52": "C8",
    "neuron_play_tone": "[ICON] 蜂鳴器 [ID] 播放音調 [TONE]，持續 [BEAT] 拍",
    "neuron_play_hz": "[ICON] 蜂鳴器 [ID] 播放音頻 [HZ] 赫茲，持續 [TIME] 秒",
    "CATEGORY_PLAY": "音效",
    "neuron_event_button_pressed": "[ICON] 當按下 [ID] 按鈕?",
    "neuron_detect_knob": "[ICON] 旋鈕 [ID] 數值",
    "neuron_detect_temperature": "[ICON] 溫度感測器 [ID] 溫度 (℃)",
    "NEURON_EVENT_LINEFOLLOW_AXIS_0": "左",
    "NEURON_EVENT_LINEFOLLOW_AXIS_1": "右",
    "NEURON_EVENT_LINEFOLLOW_AXIS_2": "所有",
    "NEURON_EVENT_LINEFOLLOW_AXIS_3": "沒有",
    "neuron_event_linefollow": "[ICON] 雙紅外線感測器 [ID] [AXIS] 側被觸發？",
    "neuron_detect_lightness": "[ICON] 光線感測器 [ID] 光線強度",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_0": "藍色",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_1": "黃色",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_2": "紅色",
    "NEURON_EVENT_TOUCH_COLOR_COLOR_3": "綠色",
    "neuron_event_touch_color": "[ICON] 觸摸感測器 [ID] 觸摸 [COLOR] ？",
    "neuron_detect_volume": "[ICON] 聲音感測器 [ID] 響度",
    "neuron_detect_ultrasonic": "[ICON] 超音波感測器 [ID] 距離 (cm)",
    "NEURON_EVENT_TILT_DIRECTION_0": "向前",
    "NEURON_EVENT_TILT_DIRECTION_1": "落後",
    "NEURON_EVENT_TILT_DIRECTION_2": "向左",
    "NEURON_EVENT_TILT_DIRECTION_3": "向右",
    "neuron_event_tilt": "[ICON] 陀螺儀 [ID] 感測到 [DIRECTION] 傾斜？",
    "neuron_event_shaked": "[ICON] 陀螺儀 [ID] 感測到搖晃？",
    "NEURON_DETECT_GYRO_ANGLE_COORDINATE_0": "滾轉角",
    "NEURON_DETECT_GYRO_ANGLE_COORDINATE_1": "俯仰角",
    "neuron_detect_gyro_angle": "[ICON] 陀螺儀 [ID] 偵測 [COORDINATE] 軸的角度(°)",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_0": "x",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_1": "y",
    "NEURON_DETECT_GYRO_SPEED_COORDINATE_2": "z",
    "neuron_detect_gyro_speed": "[ICON] 陀螺儀 [ID] [COORDINATE] 軸的加速度 m/s²",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_0": "紅色",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_1": "綠色",
    "NEURON_DETECT_COLOR_SENSOR_COLOR_2": "藍色",
    "neuron_detect_color_sensor": "[ICON] 顏色感測器 [ID] [COLOR] 色值",
    "neuron_event_josystick_direction": "[ICON] 搖桿 [ID] [DIRECTION] 搖動？",
    "NEURON_DETECT_JOYSTICK_AXIS_0": "x",
    "NEURON_DETECT_JOYSTICK_AXIS_1": "y",
    "neuron_detect_joystick": "[ICON] 搖桿 [ID] [AXIS] 軸數值",
    "neuron_event_pir": "[ICON] 人體紅外線感測器 [ID] 偵測有人？",
    "neuron_detect_humidity": "[ICON] 土壤濕度感測器 [ID] 濕度",
    "op_ranging": "[ICON] 超音波感測器 [ID] 距離 (cm)",
    "op_humidity": "[ICON] 溫濕度感測器 [ID] 濕度(%)",
    "op_temperature": "[ICON] 溫度感測器 [ID] 溫度(℃)",
    "op_htemperature": "[ICON] 溫濕度感測器 [ID] 溫度(℉)",
    "CATEGORY_SENSOR": "偵測"
};