export default {
    "halocode_mbuild_humituresensor": "온습도센서",
    "extensionName": "온습도센서",
    "extensionDescription": "",
    "OP_TEMPERATURE_INDEX_0": "1",
    "OP_TEMPERATURE_INDEX_1": "2",
    "OP_TEMPERATURE_INDEX_2": "3",
    "OP_TEMPERATURE_INDEX_3": "4",
    "OP_TEMPERATURE_INDEX_4": "5",
    "OP_TEMPERATURE_INDEX_5": "6",
    "OP_TEMPERATURE_INDEX_6": "7",
    "OP_TEMPERATURE_INDEX_7": "8",
    "op_temperature": "온습도센서 [index] 온도 (℃)",
    "op_htemperature": "온습도센서 [index] 온도 (℉)",
    "op_humidity": "온습도센서 [index] 공기 습도 (%)",
    "cate_5ce6a4bb": "온습도센서",
    "BLOCK_1547779213407": "서보 [ID] 으로 회전 [angle] (°)",
    "BLOCK_1547779701469": "스피커 [ID]  사운드 재생 [audio]",
    "BLOCK_1547779887637": "스피커 [ID]  오디오 파일 재생 [audio] 완료 될 때까지",
    "BLOCK_1547781171854": "스피커 [ID]  볼륨 설정 [volume] %"
};