export default {
    "halocode_mbuild_humituresensor": "Gyzgynlyk/çyglylyk derejesiniň duýujy enjamy",
    "extensionName": "Gyzgynlyk/çyglylyk derejesiniň duýujy enjamy",
    "extensionDescription": "",
    "OP_TEMPERATURE_INDEX_0": "1",
    "OP_TEMPERATURE_INDEX_1": "2",
    "OP_TEMPERATURE_INDEX_2": "3",
    "OP_TEMPERATURE_INDEX_3": "4",
    "OP_TEMPERATURE_INDEX_4": "5",
    "OP_TEMPERATURE_INDEX_5": "6",
    "OP_TEMPERATURE_INDEX_6": "7",
    "OP_TEMPERATURE_INDEX_7": "8",
    "op_temperature": "[index] gyzgynlyk/çyglylyk derejesini duýujy enjamyň gyzgynlyk derejesi（℃）",
    "op_htemperature": "[index] gyzgynlyk/çyglylyk derejesini duýujy enjamyň gyzgynlyk derejesi（℉）",
    "op_humidity": "[index] gyzgynlyk/çyglylyk derejesini duýujy howanyň çyglylyk derejesi（%）",
    "cate_5ce6a4bb": "Gyzgynlyk/çyglylyk derejesiniň duýujy enjamy",
    "BLOCK_1547779213407": "[ID] serwo-hereketlendiriji [angle] burçuna çenli aýlanýar (°)",
    "BLOCK_1547779701469": "[ID] dinamigi [audio] sesini aýtdyrýar",
    "BLOCK_1547779887637": "[ID] dinamigi [audio] ses faýlyny soňuna çenli aýtdyrýar",
    "BLOCK_1547781171854": "[ID] dinamigi ses kuwwatlylygyny [volume] % edip sazlaýar"
};