export default {
    "halocode_mbuild_humituresensor": "Cảm biến độ ẩm",
    "extensionName": "Cảm biến độ ẩm",
    "extensionDescription": "",
    "OP_TEMPERATURE_INDEX_0": "1",
    "OP_TEMPERATURE_INDEX_1": "2",
    "OP_TEMPERATURE_INDEX_2": "3",
    "OP_TEMPERATURE_INDEX_3": "4",
    "OP_TEMPERATURE_INDEX_4": "5",
    "OP_TEMPERATURE_INDEX_5": "6",
    "OP_TEMPERATURE_INDEX_6": "7",
    "OP_TEMPERATURE_INDEX_7": "8",
    "op_temperature": "humiture cảm biến [index] nhiệt độ (° c)",
    "op_htemperature": "cảm biến nhiệt độ[index] nhiệt độ (° F)",
    "op_humidity": "humiture cảm biến [index] độ ẩm không khí (%)",
    "cate_5ce6a4bb": "Cảm biến độ ẩm",
    "BLOCK_1547779213407": "servo [ID] quay đến góc [angle] (°)",
    "BLOCK_1547779701469": "loa [ID]  phát âm thanh [audio]",
    "BLOCK_1547779887637": "loa [ID]  phát tệp âm thanh [audio] cho đến khi hoàn tất",
    "BLOCK_1547781171854": "loa [ID]  thiết lập âm lượng [volume] %"
};