export default {
    "megapi": "Ultimate 2.0",
    "extensionName": "Ultimate 2.0",
    "extensionDescription": "MegaPi Pro demo",
    "UPDATE_FIRMWARE": "Firmware Update",
    "firmwares_version_e0a3fed5": "Online Firmware",
    "MCORE_SHOW_FACE_TIME_PORT_0": "port6",
    "MCORE_SHOW_FACE_TIME_PORT_1": "port7",
    "MCORE_SHOW_FACE_TIME_PORT_2": "port8",
    "mcore_show_face_time": "LED panel [PORT] displays image [FACE_PANEL] for [TIME]secs",
    "mcore_show_face": "LED panel [PORT] displays image [FACE_PANEL]",
    "mcore_show_face_position": "LED panel [PORT] displays image[FACE_PANEL] at x: [X] y: [Y]",
    "mcore_show_text": "LED panel [PORT] displays text[TEXT]",
    "mcore_show_text_position": "LED panel [PORT] displays text[TEXT] at x: [X] y: [Y]",
    "mcore_show_number": "LED panel[PORT]displays number [NUMBER]",
    "mcore_show_time": "LED panel [PORT] displays time [NUMBER1]: [NUMBER2]",
    "mcore_show_face_off": "LED panel [PORT] lights off",
    "display": "Looks",
    "ultimate_forward_time": "[ICON] move forward at power [POWER] % for [TIME]secs",
    "ultimate_backward_time": "[ICON] move backward at power [POWER] % for [TIME]secs",
    "ultimate_turnleft_time": "[ICON]turn left at power[POWER] % for [TIME]secs",
    "ultimate_turnright_time": "[ICON]turn right at power [POWER] % for [TIME]secs",
    "ULTIMATE_MOVE_MOVE_DIRECTION_0": "move forward",
    "ULTIMATE_MOVE_MOVE_DIRECTION_1": "move backward",
    "ULTIMATE_MOVE_MOVE_DIRECTION_2": "turn left",
    "ULTIMATE_MOVE_MOVE_DIRECTION_3": "turn right",
    "ultimate_move": "[ICON] [MOVE_DIRECTION]at power [POWER] %",
    "ultimate_move_wheel_speed": "[ICON]left wheel turns at power [POWER_LEFT] %，right wheel turns at power[POWER_RIGHT] %",
    "ultimate_move_stop": "[ICON]stop moving",
    "DCMOTOR_POWER_1_PORT_0": "port1A",
    "DCMOTOR_POWER_1_PORT_1": "port1B",
    "DCMOTOR_POWER_1_PORT_2": "port2A",
    "DCMOTOR_POWER_1_PORT_3": "port2B",
    "DCMOTOR_POWER_1_PORT_4": "port3A",
    "DCMOTOR_POWER_1_PORT_5": "port3B",
    "DCMOTOR_POWER_1_PORT_6": "port4A",
    "DCMOTOR_POWER_1_PORT_7": "port4B",
    "DCmotor_power_1": "DC motor[PORT]turns at power [POWER]%",
    "ENCODER_MOTOR_POWER_PORT_0": "port1",
    "ENCODER_MOTOR_POWER_PORT_1": "port2",
    "ENCODER_MOTOR_POWER_PORT_2": "port3",
    "ENCODER_MOTOR_POWER_PORT_3": "port4",
    "encoder_motor_power": "encoder motor [PORT]rotates at power [POWER] %",
    "encoder_motor_speed": "encoder motor [PORT]rotates at speed of [SPEED]r/min",
    "encoder_motor_pos": "encoder motor[PORT]rotates by[DEG]degrees at speed of [SPEED]r/min",
    "power": "Motion",
    "ultrasonic_dis": "ultrasonic sensor [PORT] distance(cm)",
    "linefollower_status": "line-following sensor [PORT] value",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_0": "left",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_1": "right",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_2": "all",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_3": "none",
    "LINEFOLLOWER_EXTERNAL_BLACK_WHITE_0": "black",
    "LINEFOLLOWER_EXTERNAL_BLACK_WHITE_1": "white",
    "linefollower_external": "line-following sensor [PORT]detected[LINEFOLLOW_STATE] to be [BLACK_WHITE] ？",
    "GYRO_SESOR_READ_AXIS_0": "x-axis",
    "GYRO_SESOR_READ_AXIS_1": "y-axis",
    "GYRO_SESOR_READ_AXIS_2": "z-axis",
    "gyro_sesor_read": "gyroscope (one any white port) [AXIS] angle",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_0": "press shutter",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_1": "release shutter",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_2": "start focusing",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_3": "stop focusing",
    "shutter_set_fun": "set camera shutter[PORT] to [SHUTTER_ACTION]",
    "encoder_motor_get_speed": "encoder motor[PORT] rotational speed (r/min)",
    "encoder_motor_get_pos": "encoder motor[PORT] angle(°)",
    "sensing": "Sensing",
    "megapi_main": "when Ultimate 2.0（MegaPi）starts up",
    "connect_fail_e3b8aead": "Please ensure the USB cable is properly connected to the device.",
    "connect_fail_0a8e963b": "Please ensure the device to be connected is powered on.",
    "connect_fail_c6b30a1c": "Only one device can be connected at a time in mBlock. So connecting this device will lead to the disconnection of the previous one.",
    "connect_fail_9a8a4feb": "Upload Mode is not available when the device is connected via Bluetooth4.0. Please use a USB cable to connect your device to mBlock before updating firmware.",
    "connect_fail_671017f3": "Please ensure your computer supports Bluetooth4.0 and Bluetooth4.0 is already enabled.",
    "connect_fail_aad5f15d": "Please ensure the device to be connected is powered on.",
    "connect_fail_2df5ee83": "Only one device can be connected at a time in mBlock. So connecting this device will lead to the disconnection of the previous one.",
    "upload_fail_c9f06d49": "Please ensure you align the data type, parameter type and logic of blocks or code for the device to standards.",
    "upload_fail_3bd7dbc4": "Please check if the device is properly connected. Try restarting the device and reconnect it.",
    "firmware_success_5a28c266": "For better experience, we recommend that you reconnect the device after restarting it.",
    "firmware_fail_e4b56cf5": "Please check if the device is properly connected. Try restarting the device and reconnect it to mBlock. Then update the firmware again.",
    "SET_SMART_ZERO_TITLE": "set smart servo zero position",
    "SET_SMART_ZERO_BTN": "set current position as zero position",
    "SET_SMART_ZERO_NO": "select serial number",
    "SET_SMART_ZERO_BTN_LOADING": "setting zero position...",
    "SET_SMART_ZERO_SUCCESS": "Successful!",
    "SET_SMART_ZERO_FAIL": "Failed.",
    "run_stepper_motor_pos": "stepper motor [PORT] rotates by [STEP] steps at speed of  [SPEED] stp/min",
    "detect_timer": "timer",
    "reset_timer": "reset timer"
};