export default {
    "megapi": "Ultimate 2.0",
    "extensionName": "Ultimate 2.0",
    "extensionDescription": "הדגמת MegaPi Pro",
    "firmwares_version_e0a3fed5": "קושחה מקוונת",
    "UPDATE_FIRMWARE": "עדכון קושחה",
    "connect_fail_e3b8aead": "נא וודא שכבל ה-USB מחובר כראוי להתקן.",
    "connect_fail_0a8e963b": "נא ודא שההתקן המחובר מופעל.",
    "connect_fail_c6b30a1c": "ניתן לחבר רק התקן אחד בכל פעם בגירסה זו. חיבור התקן חדש יוביל לניתוק של הרכיב הקיים.",
    "connect_fail_9a8a4feb": "מצב העלאה אינו זמין כאשר ההתקן מחובר באמצעות Bluetooth 4.0. נא השתמש בכבל USB כדי לחבר את ההתקן ל-mBlock לפני עדכון הקושחה.",
    "connect_fail_671017f3": "נא ודא שהמחשב שלך תומך ב-Bluetooth 4.0 ו-Bluetooth 4.0 כבר מאופשר.",
    "connect_fail_aad5f15d": "נא ודא שההתקן המחובר מופעל.",
    "connect_fail_2df5ee83": "ניתן לחבר רק התקן אחד בכל פעם בגירסה זו. חיבור התקן חדש יוביל לניתוק של הרכיב הקיים.",
    "upload_fail_c9f06d49": "נא וודא שהתאמת את סוג הנתונים, את סוג הפרמטר ואת הלוגיקה של הבלוקים או הקוד עבור ההתקן לפי הסטנדרטים.",
    "upload_fail_3bd7dbc4": "נא בדוק אם ההתקן מחובר כראוי. נסה להפעיל מחדש את ההתקן ולחבר אותו שוב.",
    "firmware_success_5a28c266": "לחוויית משתמש טובה יותר, אנו ממליצים שתחבר מחדש את ההתקן לאחר הפעלתו מחדש.",
    "firmware_fail_e4b56cf5": "נא בדוק אם ההתקן מחובר כראוי. נסה להפעיל מחדש את ההתקן ולחבר אותו שוב ל-mBlock. לאחר מכן עדכן שוב את הקושחה.",
    "MCORE_SHOW_FACE_TIME_PORT_0": "יציאה 6",
    "MCORE_SHOW_FACE_TIME_PORT_1": "יציאה 7",
    "MCORE_SHOW_FACE_TIME_PORT_2": "יציאה 8",
    "mcore_show_face_time": "פנל נוריות [PORT] מציג תמונת [FACE_PANEL] למשך [TIME] שניות",
    "mcore_show_face": "פנל נוריות [PORT] מציג תמונת [FACE_PANEL]",
    "mcore_show_face_position": "פנל נוריות [PORT] מציג תמונת [FACE_PANEL] בקואורדינטות - [X], [Y]",
    "mcore_show_text": "פנל נוריות [PORT] מציג טקסט [TEXT]",
    "mcore_show_text_position": "פנל נוריות [PORT] מציג טקסט [TEXT] בקואורדינטות - [X], [Y]",
    "mcore_show_number": "פנל נוריות [PORT] מציג מספר [NUMBER]",
    "mcore_show_time": "פנל נוריות [PORT] מציג זמן [NUMBER1]: [NUMBER2]",
    "mcore_show_face_off": "פנל נוריות [PORT] כבוי",
    "display": "מראה",
    "ultimate_forward_time": "[ICON] מתקדם בכוח [POWER] % למשך [TIME] שניות",
    "ultimate_backward_time": "[ICON] נע לאחור בכוח [POWER] % למשך [TIME] שניות",
    "ultimate_turnleft_time": "[ICON] פונה שמאלה בכוח [POWER] % למשך [TIME] שניות",
    "ultimate_turnright_time": "[ICON] פונה ימינה בכוח [POWER] % למשך [TIME] שניות",
    "ULTIMATE_MOVE_MOVE_DIRECTION_0": "סע קדימה",
    "ULTIMATE_MOVE_MOVE_DIRECTION_1": "סע אחורה",
    "ULTIMATE_MOVE_MOVE_DIRECTION_2": "פנה שמאלה",
    "ULTIMATE_MOVE_MOVE_DIRECTION_3": "פנה ימינה",
    "ultimate_move": "[MOVE_DIRECTION] [ICON] בכח [POWER] %",
    "ultimate_move_wheel_speed": "[ICON] הגלגל השמאלי מסתובב בעוצמה [POWER_LEFT] %, הגלגל הימני מסתובב בעוצמה [POWER_RIGHT] %",
    "ultimate_move_stop": "[ICON] עצור",
    "DCMOTOR_POWER_1_PORT_0": "יציאה 1A",
    "DCMOTOR_POWER_1_PORT_1": "יציאה 1B",
    "DCMOTOR_POWER_1_PORT_2": "יציאה 2A",
    "DCMOTOR_POWER_1_PORT_3": "יציאה 2B",
    "DCMOTOR_POWER_1_PORT_4": "יציאה 3A",
    "DCMOTOR_POWER_1_PORT_5": "יציאה 3B",
    "DCMOTOR_POWER_1_PORT_6": "יציאה 4A",
    "DCMOTOR_POWER_1_PORT_7": "יציאה 4B",
    "DCmotor_power_1": "מנוע זרם ישר[PORT]פועל בעוצמה [POWER]%",
    "ENCODER_MOTOR_POWER_PORT_0": "יציאה 1",
    "ENCODER_MOTOR_POWER_PORT_1": "יציאה 2",
    "ENCODER_MOTOR_POWER_PORT_2": "יציאה 3",
    "ENCODER_MOTOR_POWER_PORT_3": "יציאה 4",
    "encoder_motor_power": "מנוע מקודד [PORT]מסתובב בעוצמה [POWER] %",
    "encoder_motor_speed": "מנוע מקודד [PORT]מסתובב במהירות [SPEED] % סל\"ד",
    "encoder_motor_pos": "מנוע מקודד[PORT]מסתובב ב-[DEG]מעלות במהירות [SPEED]סל\"ד",
    "run_stepper_motor_pos": "מנוע צעד [PORT] מסתובב [STEP] צעדים במהירות [SPEED] סל\"ד",
    "power": "תנועה",
    "ultrasonic_dis": "חיישן אולטרה סאונד [PORT] מרחק (ס\"מ)",
    "linefollower_status": "חיישן עקיבת קו [PORT] ערך",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_0": "שמאל",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_1": "ימין",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_2": "הכל",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_3": "ללא",
    "LINEFOLLOWER_EXTERNAL_BLACK_WHITE_0": "שחור",
    "LINEFOLLOWER_EXTERNAL_BLACK_WHITE_1": "לבן",
    "linefollower_external": "חיישן עקיבת קו[PORT]מזהה[LINEFOLLOW_STATE] כ- [BLACK_WHITE] ？",
    "GYRO_SESOR_READ_AXIS_0": "ציר x",
    "GYRO_SESOR_READ_AXIS_1": "ציר y",
    "GYRO_SESOR_READ_AXIS_2": "ציר Z",
    "gyro_sesor_read": "ג'ירוסקופ (באחת היציאות הלבנות) בזווית [AXIS]",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_0": "לחץ על לחצן הצילום",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_1": "שחרר את לחצן הצילום",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_2": "התחל מיקוד",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_3": "הפסק מיקוד",
    "shutter_set_fun": "הגדר לחצן צילום[PORT] ל-[SHUTTER_ACTION]",
    "encoder_motor_get_speed": "מנוע מקודד [PORT] מהירות סיבובית (סל\"ד)",
    "encoder_motor_get_pos": "מנוע מקודד [PORT] בזווית (°)",
    "detect_timer": "טיימר",
    "reset_timer": "אפס טיימר",
    "sensing": "לחוש",
    "megapi_main": "כאשר when Ultimate 2.0（MegaPi）מתחיל",
    "SET_SMART_ZERO_TITLE": "הגדרת מיקום ראשוני של מערך סרוו חכם",
    "SET_SMART_ZERO_BTN": "הגדרת מיקום נוכחי כמיקום ראשוני",
    "SET_SMART_ZERO_NO": "בחר מספר סידורי",
    "SET_SMART_ZERO_BTN_LOADING": "הגדרת מיקום התחלתי...",
    "SET_SMART_ZERO_SUCCESS": "עבר בהצלחה!",
    "SET_SMART_ZERO_FAIL": "נכשל."
};