export default {
    "megapi": "Ultimate 2.0",
    "extensionName": "Ultimate 2,0",
    "extensionDescription": "Demo do MegaPi pro",
    "firmwares_version_e0a3fed5": "Firmware online",
    "UPDATE_FIRMWARE": "Atualização de firmware",
    "connect_fail_e3b8aead": "Certifique-se de que o cabo USB está correctamente ligado ao dispositivo.",
    "connect_fail_0a8e963b": "Certifique-se de que o dispositivo a ligar está ligado.",
    "connect_fail_c6b30a1c": "Apenas um dispositivo pode ser conectado por vez no mBlock. Assim, a conexão deste dispositivo levará à desconexão do anterior.",
    "connect_fail_9a8a4feb": "O modo de carregamento não está disponível quando o dispositivo está conectado via Bluetooth 4.0. Utilize um cabo USB para ligar o dispositivo ao mBlock antes de actualizar o firmware.",
    "connect_fail_671017f3": "Certifique-se de que o computador suporta Bluetooth 4.0 e Bluetooth 4.0 já está activado.",
    "connect_fail_aad5f15d": "Certifique-se de que o dispositivo a ligar está ligado.",
    "connect_fail_2df5ee83": "Apenas um dispositivo pode ser conectado por vez no mBlock. Assim, a conexão deste dispositivo levará à desconexão do anterior.",
    "upload_fail_c9f06d49": "Certifique-se de alinhar o tipo de dados, tipo de parâmetro e lógica de blocos ou código para o dispositivo a padrões.",
    "upload_fail_3bd7dbc4": "Por favor, verifique se o dispositivo está conectado corretamente. Tente reiniciar o dispositivo e reconectá-lo.",
    "firmware_success_5a28c266": "Para uma melhor experiência, recomendamos que volte a ligar o dispositivo depois de o reiniciar.",
    "firmware_fail_e4b56cf5": "Por favor, verifique se o dispositivo está conectado corretamente. Tente reiniciar o dispositivo e reconectá-lo ao mBlock. Em seguida, atualize o firmware novamente.",
    "MCORE_SHOW_FACE_TIME_PORT_0": "port6",
    "MCORE_SHOW_FACE_TIME_PORT_1": "port7",
    "MCORE_SHOW_FACE_TIME_PORT_2": "Port8",
    "mcore_show_face_time": "Painel de LED [PORT] mostra a imagem [FACE_PANEL] durante [TIME] segundo(s)",
    "mcore_show_face": "Painel de LED [PORT] exibe a imagem [FACE_PANEL]",
    "mcore_show_face_position": "Painel de LED [PORT] mostra a imagem [FACE_PANEL] em x: [X] y: [Y]",
    "mcore_show_text": "Painel de LED [PORT] mostra o texto [TEXT]",
    "mcore_show_text_position": "Painel de LED [PORT] mostra a imagem [TEXT] em x: [X] y: [Y]",
    "mcore_show_number": "Painel de LED [PORT] mostra o número [NUMBER]",
    "mcore_show_time": "Painel de LED [PORT] mostra a hora [NUMBER1]: [NUMBER2]",
    "mcore_show_face_off": "Painel de LED[PORT] desligado",
    "display": "Parece",
    "ultimate_forward_time": "[ICON] avançar na potência [POWER] % durante [TIME] segundo(s)",
    "ultimate_backward_time": "[ICON] recuar na potência [POWER] % durante [TIME] segundo(s)",
    "ultimate_turnleft_time": "[ICON]virar à esquerda na potência [POWER] % durante [TIME] segundo(s)",
    "ultimate_turnright_time": "[ICON] virar à direita na potência [POWER] % durante [TIME] segundo(s)",
    "ULTIMATE_MOVE_MOVE_DIRECTION_0": "Avançar",
    "ULTIMATE_MOVE_MOVE_DIRECTION_1": "mover para trás",
    "ULTIMATE_MOVE_MOVE_DIRECTION_2": "Vire à esquerda",
    "ULTIMATE_MOVE_MOVE_DIRECTION_3": "Vire à direita",
    "ultimate_move": "[ICON] [MOVE_DIRECTION] na potência [POWER] %",
    "ultimate_move_wheel_speed": "[ICON]roda esquerda na potência[POWER_LEFT] %, roda direita na potência[POWER_RIGHT] %",
    "ultimate_move_stop": "[ICON]parar de se mover",
    "DCMOTOR_POWER_1_PORT_0": "port1A",
    "DCMOTOR_POWER_1_PORT_1": "port1B",
    "DCMOTOR_POWER_1_PORT_2": "port2A",
    "DCMOTOR_POWER_1_PORT_3": "port2B",
    "DCMOTOR_POWER_1_PORT_4": "port3A",
    "DCMOTOR_POWER_1_PORT_5": "port3B",
    "DCMOTOR_POWER_1_PORT_6": "port4A",
    "DCMOTOR_POWER_1_PORT_7": "port4B",
    "DCmotor_power_1": "Motor da C.C.[PORT]gira no poder [POWER]%",
    "ENCODER_MOTOR_POWER_PORT_0": "port1",
    "ENCODER_MOTOR_POWER_PORT_1": "port2",
    "ENCODER_MOTOR_POWER_PORT_2": "port3",
    "ENCODER_MOTOR_POWER_PORT_3": "port4",
    "encoder_motor_power": "motor de codificação [PORT] gira na potência[POWER]%",
    "encoder_motor_speed": "motor do codificador [PORT]gira na velocidade de [SPEED]r/min",
    "encoder_motor_pos": "motor de codificação[PORT] gira por[DEG] grau de velocidade de [SPEED] r/min",
    "run_stepper_motor_pos": "stepper motor [PORT] rotates by [STEP] steps at speed of  [SPEED] stp/min",
    "power": "Movimento",
    "ultrasonic_dis": "sensor de ultrassom [PORT] distância (cm)",
    "linefollower_status": "sensor de seguidor de linha [PORT] Valor",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_0": "Deixou",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_1": "Certo",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_2": "Todos",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_3": "Nenhum",
    "LINEFOLLOWER_EXTERNAL_BLACK_WHITE_0": "Preto",
    "LINEFOLLOWER_EXTERNAL_BLACK_WHITE_1": "Branco",
    "linefollower_external": "line-following sensor [PORT]detected[LINEFOLLOW_STATE] to be [BLACK_WHITE] ？",
    "GYRO_SESOR_READ_AXIS_0": "eixo x",
    "GYRO_SESOR_READ_AXIS_1": "eixo y",
    "GYRO_SESOR_READ_AXIS_2": "eixo z",
    "gyro_sesor_read": "giroscópio (um qualquer porta branca) [AXIS] Ângulo",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_0": "Pressione o obturador",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_1": "obturador de liberação",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_2": "começar a focar",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_3": "parar de focar",
    "shutter_set_fun": "definir o obturador da câmera[PORT] Para [SHUTTER_ACTION]",
    "encoder_motor_get_speed": "motor de codificação[PORT] velocidade de rotação (r/min)",
    "encoder_motor_get_pos": "motor de codificação [PORT] ângulo(°)",
    "detect_timer": "cronómetro",
    "reset_timer": "reiniciar o cronómetro",
    "sensing": "Sentindo",
    "megapi_main": "quando Ultimate 2.0 (MegaPi) é iniciado",
    "SET_SMART_ZERO_TITLE": "ajuste a posição zero servo inteligente",
    "SET_SMART_ZERO_BTN": "definir a posição atual como posição zero",
    "SET_SMART_ZERO_NO": "Selecione o número de série",
    "SET_SMART_ZERO_BTN_LOADING": "definindo a posição zero...",
    "SET_SMART_ZERO_SUCCESS": "Bem sucedido!",
    "SET_SMART_ZERO_FAIL": "Falhou."
};