export default {
    "megapi": "Ultimate 2.0",
    "extensionName": "Ultimate 2.0",
    "extensionDescription": "MegaPi Pro 範例",
    "firmwares_version_e0a3fed5": "線上更新韌體",
    "UPDATE_FIRMWARE": "韌體升級",
    "connect_fail_e3b8aead": "請確認 USB 傳輸線已正確連接到設備。",
    "connect_fail_0a8e963b": "請確認要連接的設備已打開。",
    "connect_fail_c6b30a1c": "此版本每次只能連接一個設備，連接新的設備將斷開前一個設備的連線。",
    "connect_fail_9a8a4feb": "當設備透過藍牙4.0 連接時, 上傳模式不可用。在更新韌體件之前, 請使用 USB 連接線將設備連接到 mBlock。",
    "connect_fail_671017f3": "請確認您的電腦支持藍牙4.0 及藍牙已打開。",
    "connect_fail_aad5f15d": "請確認要連接的設備已打開。",
    "connect_fail_2df5ee83": "此版本每次只能連接一個設備，連接新的設備將斷開前一個設備的連線。",
    "upload_fail_c9f06d49": "請確認積木程式或文字程式中的資料型態、參數類型和邏輯皆符合設備規範。",
    "upload_fail_3bd7dbc4": "請確認您的設備連接正確。您可以重新開機啟動設備並重新連接。",
    "firmware_success_5a28c266": "為了獲得更好的體驗, 我們建議您在重啟設備後重新連接設備。",
    "firmware_fail_e4b56cf5": "請檢查設備是否已正確連接。嘗試重新開機設備並將其重新連接到 mBlock。然後再次更新韌體。",
    "MCORE_SHOW_FACE_TIME_PORT_0": "連接埠6",
    "MCORE_SHOW_FACE_TIME_PORT_1": "連接埠7",
    "MCORE_SHOW_FACE_TIME_PORT_2": "連接埠8",
    "mcore_show_face_time": "表情面板 [PORT] 顯示圖案 [FACE_PANEL] 持續 [TIME] 秒",
    "mcore_show_face": "表情面板 [PORT] 顯示圖案 [FACE_PANEL]",
    "mcore_show_face_position": "表情面板 [PORT] 顯示圖案 [FACE_PANEL] 於 x: [X] y: [Y]",
    "mcore_show_text": "表情面板 [PORT] 顯示文字 [TEXT]",
    "mcore_show_text_position": "表情面板 [PORT] 顯示文字 [TEXT] 位置 x: [X] y: [Y]",
    "mcore_show_number": "表情面板 [PORT] 顯示數字 [NUMBER]",
    "mcore_show_time": "表情面板 [PORT] 顯示時間 [NUMBER1][NUMBER2]",
    "mcore_show_face_off": "表情面板 [PORT] 熄滅燈",
    "display": "外觀",
    "ultimate_forward_time": "[ICON] 前進，動力 [POWER] %，持續 [TIME] 秒",
    "ultimate_backward_time": "[ICON] 後退，動力 [POWER] %，持續 [TIME] 秒",
    "ultimate_turnleft_time": "[ICON]左轉，動力 [POWER]%，持續 [TIME] 秒",
    "ultimate_turnright_time": "[ICON] 右轉，動力 [POWER] %，持續 [TIME] 秒",
    "ULTIMATE_MOVE_MOVE_DIRECTION_0": "前進",
    "ULTIMATE_MOVE_MOVE_DIRECTION_1": "後退",
    "ULTIMATE_MOVE_MOVE_DIRECTION_2": "左轉",
    "ULTIMATE_MOVE_MOVE_DIRECTION_3": "右轉",
    "ultimate_move": "[ICON] [MOVE_DIRECTION] ，動力 [POWER]%",
    "ultimate_move_wheel_speed": "[ICON]左輪動力 [POWER_LEFT] %，右輪動力 [POWER_RIGHT] %",
    "ultimate_move_stop": "[ICON] 停止運動",
    "DCMOTOR_POWER_1_PORT_0": "連接埠1A",
    "DCMOTOR_POWER_1_PORT_1": "連接埠1B",
    "DCMOTOR_POWER_1_PORT_2": "連接埠2A",
    "DCMOTOR_POWER_1_PORT_3": "連接埠2B",
    "DCMOTOR_POWER_1_PORT_4": "連接埠3A",
    "DCMOTOR_POWER_1_PORT_5": "連接埠3B",
    "DCMOTOR_POWER_1_PORT_6": "連接埠4A",
    "DCMOTOR_POWER_1_PORT_7": "連接埠4B",
    "DCmotor_power_1": "直流馬達 [PORT] 以動力 [POWER]% 轉動",
    "ENCODER_MOTOR_POWER_PORT_0": "連接埠1",
    "ENCODER_MOTOR_POWER_PORT_1": "連接埠2",
    "ENCODER_MOTOR_POWER_PORT_2": "連接埠3",
    "ENCODER_MOTOR_POWER_PORT_3": "連接埠4",
    "encoder_motor_power": "編碼馬達 [PORT] 轉動，動力 [POWER]%",
    "encoder_motor_speed": "編碼馬達 [PORT] 轉動，速度[SPEED] r/min",
    "encoder_motor_pos": "編碼馬達 [PORT] 轉動[DEG]，速度 [SPEED] 圈/分",
    "run_stepper_motor_pos": "步進馬達 [PORT] 旋轉 [STEP] 步，速度 [SPEED] stp/min",
    "power": "動作",
    "ultrasonic_dis": "超音波感測器 [PORT] 距離 (cm)",
    "linefollower_status": "循線感測器 [PORT] 數值",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_0": "左",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_1": "右",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_2": "所有",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_3": "沒有",
    "LINEFOLLOWER_EXTERNAL_BLACK_WHITE_0": "黑",
    "LINEFOLLOWER_EXTERNAL_BLACK_WHITE_1": "白",
    "linefollower_external": "循線感測器 [PORT] 偵測到 [LINEFOLLOW_STATE] 為 [BLACK_WHITE]?",
    "GYRO_SESOR_READ_AXIS_0": "x 軸",
    "GYRO_SESOR_READ_AXIS_1": "y 軸",
    "GYRO_SESOR_READ_AXIS_2": "z 軸",
    "gyro_sesor_read": "陀螺儀 (任何白色埠) [AXIS] 角度",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_0": "按下快門",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_1": "放開快門",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_2": "開始對焦",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_3": "停止對焦",
    "shutter_set_fun": "將相機快門[PORT] 設定為 [SHUTTER_ACTION]",
    "encoder_motor_get_speed": "編碼馬達 [PORT] 轉速 (r/min)",
    "encoder_motor_get_pos": "編碼馬達 [PORT] 角度(°)",
    "detect_timer": "計時 器",
    "reset_timer": "計時器歸零",
    "sensing": "偵測",
    "megapi_main": "當 Ultimate 2.0（MegaPi）開機",
    "SET_SMART_ZERO_TITLE": "設定智能伺服零位置",
    "SET_SMART_ZERO_BTN": "將當前位置設置為零位點",
    "SET_SMART_ZERO_NO": "選擇序號",
    "SET_SMART_ZERO_BTN_LOADING": "設定零位...",
    "SET_SMART_ZERO_SUCCESS": "成功！",
    "SET_SMART_ZERO_FAIL": "失敗"
};