export default {
    "megapi": "Ultimate 2.0",
    "extensionName": "Ultimate 2.0",
    "extensionDescription": "MegaPi Pro demo 测试",
    "firmwares_version_e0a3fed5": "在线固件",
    "UPDATE_FIRMWARE": "固件更新",
    "connect_fail_e3b8aead": "请确保USB线已正确连接当前设备",
    "connect_fail_0a8e963b": "请确保当前待连接设备处于开机状态",
    "connect_fail_c6b30a1c": "目前慧编程只支持连接一台设备，连接当前设备另一台已连接设备会自动断开",
    "connect_fail_9a8a4feb": "蓝牙4.0连接模式下，不支持上传模式，请先通过USB连接更新最新固件",
    "connect_fail_671017f3": "请确保您的电脑设备具备蓝牙4.0连接能力，且蓝牙4.0功能已经打开",
    "connect_fail_aad5f15d": "请确保当前待连接设备处于开机状态",
    "connect_fail_2df5ee83": "目前慧编程只支持连接一台设备，连接当前设备另一台已连接设备会自动断开",
    "upload_fail_c9f06d49": "请检查该设备的积木或代码的数据类型、参数类型、编程逻辑是否符合程序规范",
    "upload_fail_3bd7dbc4": "请检查您是否正确连接设备，可以尝试重启设备后再重新连接设备",
    "firmware_success_5a28c266": "为了保证更好的体验，您可以重启设备后重新连接设备",
    "firmware_fail_e4b56cf5": "请检查您是否正确连接设备，可以尝试重启设备后重新连接设备，再尝试更新",
    "MCORE_SHOW_FACE_TIME_PORT_0": "接口6",
    "MCORE_SHOW_FACE_TIME_PORT_1": "接口7",
    "MCORE_SHOW_FACE_TIME_PORT_2": "接口8",
    "mcore_show_face_time": " 表情面板 [PORT] 显示图案 [FACE_PANEL] 持续 [TIME] 秒",
    "mcore_show_face": "表情面板 [PORT] 显示图案 [FACE_PANEL]",
    "mcore_show_face_position": "表情面板 [PORT] 显示图案 [FACE_PANEL] 在x: [X] y: [Y]",
    "mcore_show_text": "表情面板 [PORT] 显示字符 [TEXT]",
    "mcore_show_text_position": "表情面板 [PORT] 显示字符 [TEXT] 在x: [X] y: [Y]",
    "mcore_show_number": "表情面板 [PORT] 显示数字 [NUMBER]",
    "mcore_show_time": "表情面板 [PORT] 显示时间 [NUMBER1]: [NUMBER2]",
    "mcore_show_face_off": "表情面板 [PORT] 熄灭面板",
    "display": "显示",
    "ultimate_forward_time": "[ICON] 前进以动力 [POWER] %，持续 [TIME] 秒",
    "ultimate_backward_time": "[ICON] 后退以动力 [POWER] %，持续 [TIME] 秒",
    "ultimate_turnleft_time": "[ICON] 左转以动力 [POWER] %，持续 [TIME] 秒",
    "ultimate_turnright_time": "[ICON] 右转以动力 [POWER] %，持续 [TIME] 秒",
    "ULTIMATE_MOVE_MOVE_DIRECTION_0": "前进",
    "ULTIMATE_MOVE_MOVE_DIRECTION_1": "后退",
    "ULTIMATE_MOVE_MOVE_DIRECTION_2": "左转",
    "ULTIMATE_MOVE_MOVE_DIRECTION_3": "右转",
    "ultimate_move": "[ICON] [MOVE_DIRECTION] 以动力 [POWER] %",
    "ultimate_move_wheel_speed": "[ICON] 左轮转动以动力 [POWER_LEFT] %，右轮转动以动力 [POWER_RIGHT] %",
    "ultimate_move_stop": "[ICON] 停止运动",
    "DCMOTOR_POWER_1_PORT_0": "接口1A",
    "DCMOTOR_POWER_1_PORT_1": "接口1B",
    "DCMOTOR_POWER_1_PORT_2": "接口2A",
    "DCMOTOR_POWER_1_PORT_3": "接口2B",
    "DCMOTOR_POWER_1_PORT_4": "接口3A",
    "DCMOTOR_POWER_1_PORT_5": "接口3B",
    "DCMOTOR_POWER_1_PORT_6": "接口4A",
    "DCMOTOR_POWER_1_PORT_7": "接口4B",
    "DCmotor_power_1": "直流电机 [PORT] 以动力 [POWER] %转动",
    "ENCODER_MOTOR_POWER_PORT_0": "接口1",
    "ENCODER_MOTOR_POWER_PORT_1": "接口2",
    "ENCODER_MOTOR_POWER_PORT_2": "接口3",
    "ENCODER_MOTOR_POWER_PORT_3": "接口4",
    "encoder_motor_power": "编码电机 [PORT] 以动力 [POWER] % 转动",
    "encoder_motor_speed": "编码电机 [PORT]  以速度 [SPEED] 转每分钟 转动",
    "encoder_motor_pos": "编码电机 [PORT] 转动 [DEG] 度，以速度 [SPEED] 转每分钟",
    "run_stepper_motor_pos": "步进电机 [PORT] 转动，距离 [STEP] 步，速度 [SPEED] 步每分钟",
    "power": "运动",
    "ultrasonic_dis": "超声波传感器 [PORT] 距离 cm",
    "linefollower_status": "巡线传感器 [PORT] 读数",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_0": "左边",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_1": "右边",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_2": "全部",
    "LINEFOLLOWER_EXTERNAL_LINEFOLLOW_STATE_3": "没有",
    "LINEFOLLOWER_EXTERNAL_BLACK_WHITE_0": "黑",
    "LINEFOLLOWER_EXTERNAL_BLACK_WHITE_1": "白",
    "linefollower_external": "巡线传感器 [PORT] 检测到 [LINEFOLLOW_STATE] 为 [BLACK_WHITE] ？",
    "GYRO_SESOR_READ_AXIS_0": "X轴",
    "GYRO_SESOR_READ_AXIS_1": "Y轴",
    "GYRO_SESOR_READ_AXIS_2": "Z轴",
    "gyro_sesor_read": "陀螺仪（位于任一白色接口） [AXIS] 角度",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_0": "按下快门",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_1": "松开快门",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_2": "开始对焦",
    "SHUTTER_SET_FUN_SHUTTER_ACTION_3": "停止对焦",
    "shutter_set_fun": "相机快门模块 [PORT] 功能为 [SHUTTER_ACTION]",
    "encoder_motor_get_speed": "编码电机 [PORT] 转速（转每分钟）",
    "encoder_motor_get_pos": "编码电机 [PORT] 角度位置（度）",
    "detect_timer": "计时器",
    "reset_timer": " 计时器归零",
    "sensing": "感知",
    "megapi_main": "当Ultimate 2.0（MegaPi） 启动",
    "SET_SMART_ZERO_TITLE": "设置智能舵机零点",
    "SET_SMART_ZERO_BTN": "设置当前位置为舵机零点",
    "SET_SMART_ZERO_NO": "选择编号",
    "SET_SMART_ZERO_BTN_LOADING": "正在设置零点",
    "SET_SMART_ZERO_SUCCESS": "设置成功",
    "SET_SMART_ZERO_FAIL": "设置失败"
};