export default {
    "auriga_laser_sword": "LED mač",
    "extensionName": "LED mač",
    "extensionDescription": "Pretvorite svoj mBot Ranger u LED mač. ",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_0": "port6",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_1": "port7",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_2": "port8",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_3": "port9",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_4": "port10",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_SLOT_0": "slot1",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_SLOT_1": "slot2",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "crveno",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "narančasta",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "žuta",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "zelena",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "svijetlo Plava",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "plava",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "ljubičasta",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "black",
    "auriga_show_all_ledstrip_color": "[ICON] LED traka[PORT] [SLOT] sve lampice svijetle u boji[COLOR_LIST]",
    "auriga_show_ledstrip_color": "[ICON] LED traka[PORT][SLOT][POS] svijetli u boji [COLOR_LIST]",
    "auriga_show_ledstrip_rbg": "[ICON] LED traka[PORT] [SLOT] [POS] svijetli s crvenom bojom [R] zelenom [G] plavom [B]",
    "CATEGORY_LASER_SWORD": "LED mač"
};