export default {
    "auriga_laser_sword": "Spada LED",
    "extensionName": "Spada LED",
    "extensionDescription": "Trasforma il tuo mBot Ranger in una spada a LED. ",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_0": "port6",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_1": "port7",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_2": "port8",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_3": "port9",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_4": "port10",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_SLOT_0": "slot1",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_SLOT_1": "slot2",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "rosso",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "arancione",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "giallo",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "green",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "ciano",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "blu",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "viola",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "black",
    "auriga_show_all_ledstrip_color": "[ICON] striscia LED [PORT] [SLOT]: accendi tutte le luci con colore [COLOR_LIST]",
    "auriga_show_ledstrip_color": "[ICON] striscia LED [PORT] [SLOT] [POS]: accendi le luci con colore [COLOR_LIST]",
    "auriga_show_ledstrip_rbg": "[ICON] Striscia LED [PORT] [SLOT] [POS] luce con colore rosso [R] verde [G] blu [B]",
    "CATEGORY_LASER_SWORD": "Spada LED"
};