export default {
    "auriga_laser_sword": "LED剣",
    "extensionName": "LED剣",
    "extensionDescription": "mBot RangerをLED剣に変形する",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_0": "ポート6",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_1": "ポート7",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_2": "ポート8",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_3": "ポート9",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_4": "ポート10",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_SLOT_0": "スロット1",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_SLOT_1": "スロット2",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "赤",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "オレンジ",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "黄",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "緑",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "シアン",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "青",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "紫",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "black",
    "auriga_show_all_ledstrip_color": "[ICON] LED ストリップ[PORT] の[SLOT] を[COLOR_LIST] 色で点灯する",
    "auriga_show_ledstrip_color": "[ICON] LED ストリップ[PORT] の[SLOT] の[POS] 番目を[COLOR_LIST] 色で点灯する",
    "auriga_show_ledstrip_rbg": "[ICON] LED ストリップ[PORT] の[SLOT] の[POS] 番目を赤 [R] 緑 [G] 青 [B] で点灯する",
    "CATEGORY_LASER_SWORD": "LED剣"
};