export default {
    "auriga_laser_sword": "Espada LED",
    "extensionName": "Espada LED",
    "extensionDescription": "Transforma o teu mBot Ranger numa Espada LED. ",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_0": "porta6",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_1": "porta7",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_2": "porta8",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_3": "porta9",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_4": "porta10",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_SLOT_0": "ranhura1",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_SLOT_1": "ranhura2",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "vermelho",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "laranja",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "amarelo",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "verde",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "ciano",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "azul",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "roxo",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "black",
    "auriga_show_all_ledstrip_color": "[ICON] banda de LED[PORT] [SLOT] com todas as luzes de cor [COLOR_LIST]",
    "auriga_show_ledstrip_color": "[ICON] Banda de LED [PORT] [SLOT] [POS] ligado com cor [COLOR_LIST]",
    "auriga_show_ledstrip_rbg": "[ICON] banda de LED [PORT] [SLOT] [POS] ligada com cor vermelha [R] verde [G] azul [B]",
    "CATEGORY_LASER_SWORD": "Espada LED"
};