export default {
    "auriga_laser_sword": "Светодиодный меч",
    "extensionName": "Светодиодный меч",
    "extensionDescription": "Превратите ваш mBot Ranger в светодиодный меч. ",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_0": "Порт6",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_1": "Порт7",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_2": "Порт8",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_3": "Порт9",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_4": "Порт10",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_SLOT_0": "слот 1",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_SLOT_1": "слот 2",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "красный",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "оранжевый",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "желтый",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "зеленый",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "голубой",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "синий",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "фиолетовый",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "black",
    "auriga_show_all_ledstrip_color": "[ICON] Светодиодная лента [PORT] [SLOT] включить всем цвет [COLOR_LIST]",
    "auriga_show_ledstrip_color": "[ICON] Светодиодная лента [PORT] [SLOT][POS] загорается [COLOR_LIST] цветом",
    "auriga_show_ledstrip_rbg": "[ICON] Светодиодная лента [PORT] [SLOT] [POS] включить цвет: красный [R] зеленый [G] синий [B]",
    "CATEGORY_LASER_SWORD": "Светодиодный меч"
};