export default {
    "auriga_laser_sword": "LED gylyç",
    "extensionName": "LED gylyç",
    "extensionDescription": "Öz mBot Ranger robotyňyzy LED gylyjyna öwüriň. ",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_0": "port6",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_1": "port7",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_2": "port8",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_3": "port9",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_4": "port10",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_SLOT_0": "slot1",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_SLOT_1": "slot2",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "gyzyl",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "mämişi",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "sary",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "ýaşyl",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "pöwrize",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "gök",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "benewşe",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "black",
    "auriga_show_all_ledstrip_color": "[ICON] Yşyk-diot lentasy [PORT][SLOT] ähli çyralary bilen [COLOR_LIST] reňkinde ýanýar",
    "auriga_show_ledstrip_color": "[ICON] Yşyk-diot lentasynyň [PORT][SLOT][POS] çyrasy [COLOR_LIST] reňkinde ýanýar",
    "auriga_show_ledstrip_rbg": "[ICON] Yşyk-diot lentasynyň [PORT][SLOT][POS] çyrasy [R] gyzyl [G] ýaşyl [B] gök reňler bilen ýanýar",
    "CATEGORY_LASER_SWORD": "LED gylyç"
};