export default {
    "auriga_laser_sword": "LED меч",
    "extensionName": "LED меч",
    "extensionDescription": "Перетворіть вашого mBot Ranger на LED меч. ",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_0": "порт 6",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_1": "порт 7",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_2": "порт 8",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_3": "порт 9",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_PORT_4": "порт 10",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_SLOT_0": "роз'єм1",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_SLOT_1": "роз'єм2",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "червоний",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "помаранчевий",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "жовтий",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "зелений",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "блакитний",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "синій",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "фіолетовий",
    "AURIGA_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "black",
    "auriga_show_all_ledstrip_color": "[ICON] LED стрічка [PORT] [SLOT] всі вогні [COLOR_LIST]",
    "auriga_show_ledstrip_color": "[ICON] LED стрічка [PORT] [SLOT] [POS] світитись [COLOR_LIST]",
    "auriga_show_ledstrip_rbg": "[ICON] LED стрічка [PORT] [SLOT] [POS] світитись червоним [R] зеленим [G] синім [B]",
    "CATEGORY_LASER_SWORD": "LED меч"
};