export default {
    "halocode_mbuild_rangingsensor": "거리 측정 센서",
    "extensionName": "거리 측정 센서",
    "extensionDescription": "",
    "OP_RANGING_INDEX_0": "1",
    "OP_RANGING_INDEX_1": "2",
    "OP_RANGING_INDEX_2": "3",
    "OP_RANGING_INDEX_3": "4",
    "OP_RANGING_INDEX_4": "5",
    "OP_RANGING_INDEX_5": "6",
    "OP_RANGING_INDEX_6": "7",
    "OP_RANGING_INDEX_7": "8",
    "op_ranging": "레인 징 센서[index] 물체 까지의 거리 (센티미터)",
    "event_ranging_pressed": "레인 징 센서[index] 외부 거리 범위?",
    "cate_a8ddb2a0": "거리 측정 센서",
    "BLOCK_1547779213407": "서보 [ID] 으로 회전 [angle] (°)",
    "BLOCK_1547779701469": "스피커 [ID]  사운드 재생 [audio]",
    "BLOCK_1547779887637": "스피커 [ID]  오디오 파일 재생 [audio] 완료 될 때까지",
    "BLOCK_1547781171854": "스피커 [ID]  볼륨 설정 [volume] %"
};