export default {
    "halocode_mbuild_rangingsensor": "Czujnik zakresu",
    "extensionName": "Czujnik zakresu",
    "extensionDescription": "",
    "OP_RANGING_INDEX_0": "1",
    "OP_RANGING_INDEX_1": "2",
    "OP_RANGING_INDEX_2": "3",
    "OP_RANGING_INDEX_3": "4",
    "OP_RANGING_INDEX_4": "5",
    "OP_RANGING_INDEX_5": "6",
    "OP_RANGING_INDEX_6": "7",
    "OP_RANGING_INDEX_7": "8",
    "op_ranging": "zakres czujnika[index] Odległość do obiektu (cm)",
    "event_ranging_pressed": "zakres czujnika[index] odległość poza zasięgiem?",
    "cate_a8ddb2a0": "Czujnik zakresu",
    "BLOCK_1547779213407": "Serwa [ID] obraca się do [angle] (°)",
    "BLOCK_1547779701469": "Głośnik [ID]  Odtwarzanie dźwięku [audio]",
    "BLOCK_1547779887637": "Głośnik [ID]  Odtwarzanie pliku audio [audio] aż do zrobienia",
    "BLOCK_1547781171854": "Głośnik [ID]  ustawić głośność na [volume] %"
};