export default {
    "orion": "Orion",
    "extensionName": "Orion",
    "extensionDescription": "",
    "firmwares_version_60bbba12": "Firmware más reciente",
    "firmwares_version_01bb1787": "Firmware de fábrica",
    "UPDATE_FIRMWARE": "Actualización de firmware",
    "connect_fail_c0e2b9a5": "Asegúrate que el cable USB está conectado correctamente al dispositivo.",
    "connect_fail_2d58cae4": "Asegúrate que el dispositivo a conectar está encendido.",
    "connect_fail_19a23a8c": "Solo puedes conectar un dispositivo a la vez, en esta versión. Si conectas un nuevo dispositivo, se desconectará el que ya está conectado.",
    "connect_fail_71e3a310": "El modo de carga no se puede usar cuando el dispositivo está conectado a través de Bluetooth 4.0. Usa un cable USB para conectar el dispositivo a mBlock antes de actualizar el firmware.",
    "connect_fail_c6660567": "Asegúrate que tu ordenador tiene Bluetooth 4.0, y que el Bluetooth está encendido.",
    "connect_fail_18b1b666": "Asegúrate que el dispositivo a conectar está encendido.",
    "connect_fail_321f3fab": "En esta versión, solo puedes conectar un dispositivo a la vez. Si conectas un nuevo dispositivo, se desconectará el que ya está conectado.",
    "upload_fail_7f425b63": "Asegúrate que el tipo de los datos, el tipo de los parámetros y la lógica de los bloques o del código se ajustan a los estándares.",
    "upload_fail_c59c7bc9": "Asegúrese de que el dispositivo esté bien conectado. Puede reiniciar el dispositivo e intentar conectarlo de nuevo.",
    "upload_fail_bfa364fb": "Please check if any Bluetooth module is connected to the device. Remove the Bluetooth module first if there's any.",
    "firmware_success_b589e7b9": "Para aprovechar la actualización, reinicia el dispositivo y conéctalo de nuevo.",
    "firmware_fail_8141b74c": "Asegúrese de que el dispositivo esté bien conectado. Puede reiniciar el dispositivo e intentar conectarlo de nuevo.",
    "RUNSEVSEG_BLUEPORTS_0": "puerto3",
    "RUNSEVSEG_BLUEPORTS_1": "puerto4",
    "RUNSEVSEG_BLUEPORTS_2": "puerto6",
    "runSevseg": "siete segmentos[bluePorts] muestra el número [args0]",
    "cate_b072ec4f": "Pantalla",
    "RUNLED_LPORT_0": "puerto3",
    "RUNLED_LPORT_1": "puerto4",
    "RUNLED_LPORT_2": "puerto6",
    "RUNLED_LPORT_3": "puerto7",
    "RUNLED_LPORT_4": "puerto8",
    "RUNLED_INDEX_0": "todos",
    "RUNLED_INDEX_1": "1",
    "RUNLED_INDEX_2": "2",
    "RUNLED_INDEX_3": "3",
    "RUNLED_INDEX_4": "4",
    "runLed": "RGB LED [lport] se ilumina[index]con color [color]",
    "BLOCK_1569571656649": "RGB LED  [lport]se ilumina[index] con color rojo [value]  Verde [value1] Azul [value2]",
    "BLOCK_1569572294998_SLOT_0": "conexión 1",
    "BLOCK_1569572294998_SLOT_1": "conexión 2",
    "BLOCK_1569572294998": "Tira LED[normalPort] [slot] todas las luces con el color [color]",
    "BLOCK_1571019759214": "tira LED [normalPort] [slot] [index] encendida en color [color]",
    "runLedStrip": "Tira LED[normalPort] [slot] todas las luces con color rojo [value] Verde [value1]Azul [value2]",
    "BLOCK_1571022561858": "Tira LED [normalPort] [slot] [index2]luz con color rojo [value] Verde [value1]Azul [value2]",
    "cate_2ced8c33": "Luz y Sonido",
    "RUNMOTOR_MOTORPORT_0": "motor puerto1",
    "RUNMOTOR_MOTORPORT_1": "motor puerto2",
    "RUNMOTOR_MOTORPORT_2": "puerto1",
    "RUNMOTOR_MOTORPORT_3": "puerto2",
    "RUNMOTOR_DIRECTION_0": "hacia la derecha",
    "RUNMOTOR_DIRECTION_1": "hacia la izquierda",
    "runMotor": "motor [motorPort] [direction] rotates at speed of [motorvalue]",
    "RUNDCMOTOR_DIRECTION_0": "hacia la derecha",
    "RUNDCMOTOR_DIRECTION_1": "hacia la izquierda",
    "runDcMotor": "motor [motorPort]   [direction] rotates at power [motorvalue] %",
    "RUNDCMOTOR_1_MOTORPORT_0": "motor port1",
    "RUNDCMOTOR_1_MOTORPORT_1": "motor port2",
    "RUNDCMOTOR_1_MOTORPORT_2": "port1",
    "RUNDCMOTOR_1_MOTORPORT_3": "port2",
    "runDcMotor_1": "motor [motorPort]   [direction] rotates at power [motorvalue] %",
    "runServo": "Servo [servoPort] [slot] Ángulo [angle]",
    "RUNSTEPPERMOTOR_EXMOTORPORT_0": "puerto1",
    "RUNSTEPPERMOTOR_EXMOTORPORT_1": "puerto2",
    "runStepperMotor": "stepper motor[exMotorPort]  [direction] rotates [distance] steps at speed of[stepperSpeed]stp/min",
    "runStepperMotor_1": "stepper motor [port] [direction] rotates[step]steps at speed of [speed]stp/min",
    "runEncoderMotor": "encoder motor[exMotorPort] [slot] [direction] rotates [args0] degrees at speed of [encoderSpeed]r/min",
    "runEncoderMotor_1": "encoder motor[exMotorPort] [slot] [direction] rotates [args0] degrees at speed of [encoderSpeed]r/min",
    "RUNSHUTTER_SHUTTER_0": "presionado",
    "RUNSHUTTER_SHUTTER_1": " Liberado",
    "RUNSHUTTER_SHUTTER_2": "empezar a enfocar",
    "RUNSHUTTER_SHUTTER_3": "dejar de enfocar",
    "runShutter": "Obturador [bluePorts]'s status being [shutter]",
    "RUNFAN_FAN_0": "en sentido horario",
    "RUNFAN_FAN_1": "al contrario de las agujas del reloj",
    "RUNFAN_FAN_2": "Parar",
    "runFan": "ventilador [fanPorts] gira [fan]",
    "cate_79d47608": "Acción",
    "RUNLIGHTSENSOR_LIGHTPORTS_0": "puerto6",
    "RUNLIGHTSENSOR_SWITCH_0": "apagado",
    "RUNLIGHTSENSOR_SWITCH_1": "encendido",
    "runLightsensor": "sensor de luz [lightPorts] LED girado [switch]",
    "GETLIGHTSENSOR_LAPORT_0": "puerto6",
    "GETLIGHTSENSOR_LAPORT_1": "puerto7",
    "GETLIGHTSENSOR_LAPORT_2": "puerto8",
    "getLightsensor": "sensor de luz [laport]intensidad de la luz",
    "getInfrared": "Receptor IR [bluePorts]Valor",
    "getPirmotion": "¿Sensor de presencia [bluePorts] detecta movimiento de personas？",
    "getTemperature": "sensor de temperatura [normalPort] [slot] ℃",
    "GETHUMITURE_HUMITURE_0": "humedad",
    "GETHUMITURE_HUMITURE_1": "temperatura",
    "getHumiture": "sensor de humedad [normalPort] [humiture]",
    "getUltrasonic": "distancia del sensor de ultrasonidos [whitePorts] (cm)",
    "getLinefollower": "sensor de seguimiento de línea[bluePorts]",
    "GETJOYSTICK_AXIS_0": "eje X",
    "GETJOYSTICK_AXIS_1": "eje Y",
    "getJoystick": "valor [Axis] del mando de juego [blackPorts]",
    "getPotentiometer": "Potenciómetro [blackPorts]Valor",
    "getSoundsensor": "sensor de sonido [soundPort]Volumen",
    "getLimitswitch": "interruptor de límite[normalPort] [slot]¿Presionado?",
    "GYRO_SESOR_READ_GYROAXIS_0": "eje x",
    "GYRO_SESOR_READ_GYROAXIS_1": "eje y",
    "GYRO_SESOR_READ_GYROAXIS_2": "eje z",
    "gyro_sesor_read": "gyroscope(at any of white port) [GyroAxis]angle",
    "getFlame": "sensor de llama[blackPorts]Valor",
    "getGas": "sensor de gas [blackPorts]Valor",
    "getTouchSensor": "sensor táctil [bluePorts] ¿Tocado?",
    "GETBUTTON_BUTTON_KEY_0": "key1",
    "GETBUTTON_BUTTON_KEY_1": "key2",
    "GETBUTTON_BUTTON_KEY_2": "key3",
    "GETBUTTON_BUTTON_KEY_3": "key4",
    "getButton": "¿Pulsado botón [blackPorts] [button_key]？",
    "getTimer": "temporizador(es)",
    "resetTimer": "reiniciar cronómetro",
    "cate_53f02e41": "Sensores",
    "runArduino": "cuando Orion se inicia",
    "update_firmware_prompt": "Turn off the buzzer before updating the firmware."
};