export default {
    "orion": "Orion",
    "extensionName": "Orion",
    "extensionDescription": "",
    "firmwares_version_60bbba12": "さいしんのファームウェア",
    "firmwares_version_01bb1787": "こうじょうしゅっかじのファームウェア",
    "UPDATE_FIRMWARE": "ファームウェアのこうしん",
    "connect_fail_c0e2b9a5": "USBケーブルがデバイスにただしくせつぞくされていることをかくにんしてください。",
    "connect_fail_2d58cae4": "せつぞくするデバイスのでんげんがはいっていることをかくにんしてください。",
    "connect_fail_19a23a8c": "このバージョンでは、いちどに 1 つのデバイスしかせつぞくできません。あたらしいデバイスのせつぞくは、きぞんの デバイスをせつだんします。",
    "connect_fail_71e3a310": "デバイスがBluetooth 4.0けいゆでせつぞくされているばあい、アップロードモードはしようできません。ファームウェアをこうしんするまえに、USBケーブルをしようしてデバイスをmBlockにせつぞくしてください。",
    "connect_fail_c6660567": "おつかいのコンピュータがBluetooth 4.0をサポートしていることをかくにんし、Bluetoothがオンであることをかくにんしてください。",
    "connect_fail_18b1b666": "せつぞくするデバイスのでんげんがはいっていることをかくにんしてください。",
    "connect_fail_321f3fab": "このバージョンでは、いちどに 1 つのデバイスしかせつぞくできません。あたらしいデバイスのせつぞくは、きぞんの デバイスをせつだんします。",
    "upload_fail_7f425b63": "データタイプ、パラメータタイプ、ブロックのロジック、またはデバイスようのコードをひょうじゅんにそろえるようにしてください。",
    "upload_fail_c59c7bc9": "デバイスがてきせつにせつぞくされていることをかくにんしてください。デバイスをさいきどうして、もういちどせつぞくすることができます。",
    "upload_fail_bfa364fb": "Bluetoothモジュールがデバイスにせつぞくされているかどうかをかくにんしてください。 Bluetoothモジュールがあるばあいは、さいしょにとりはずします。",
    "firmware_success_b589e7b9": "よりよいそうさのために、デバイスをさいきどうしてもういちどせつぞくしてみてください。",
    "firmware_fail_8141b74c": "デバイスがてきせつにせつぞくされていることをかくにんしてください。デバイスをさいきどうして、もういちどせつぞくすることができます。",
    "RUNSEVSEG_BLUEPORTS_0": "ポート3",
    "RUNSEVSEG_BLUEPORTS_1": "ポート4",
    "RUNSEVSEG_BLUEPORTS_2": "ポート6",
    "runSevseg": "7セグメント[bluePorts] に[args0] をひょうじする",
    "cate_b072ec4f": "みため",
    "RUNLED_LPORT_0": "ポート3",
    "RUNLED_LPORT_1": "ポート4",
    "RUNLED_LPORT_2": "ポート6",
    "RUNLED_LPORT_3": "ポート7",
    "RUNLED_LPORT_4": "ポート8",
    "RUNLED_INDEX_0": "すべて",
    "RUNLED_INDEX_1": "1",
    "RUNLED_INDEX_2": "2",
    "RUNLED_INDEX_3": "3",
    "RUNLED_INDEX_4": "4",
    "runLed": "RGB LED [lport] の [index] を[color] いろでてんとうする",
    "BLOCK_1569571656649": "RGB LED [lport] の [index] をあか [value] みどり[value1] あお [value2] でてんとうする",
    "BLOCK_1569572294998_SLOT_0": "スロット1",
    "BLOCK_1569572294998_SLOT_1": "スロット2",
    "BLOCK_1569572294998": "LEDストリップ[normalPort] [slot] のすべてを[color] いろでてんとうする",
    "BLOCK_1571019759214": "LED ストリップ[normalPort] [slot] [index] を[color] いろでてんとうする",
    "runLedStrip": "LEDストリップ[normalPort] [slot] のすべてをあか [value] みどり [value1] あお [value2] でてんとうする",
    "BLOCK_1571022561858": "LEDストリップ [normalPort] [slot] [index2] をあか [value] みどり [value1] あお[value2] でてんとうする",
    "cate_2ced8c33": "みため",
    "RUNMOTOR_MOTORPORT_0": "モーター ポート1",
    "RUNMOTOR_MOTORPORT_1": "モーター ポート2",
    "RUNMOTOR_MOTORPORT_2": "ポート1",
    "RUNMOTOR_MOTORPORT_3": "ポート2",
    "RUNMOTOR_DIRECTION_0": "とけいまわり",
    "RUNMOTOR_DIRECTION_1": "はんとけいまわり",
    "runMotor": "モーター [motorPort] [direction] を [motorvalue] のそくどでかいてんする",
    "RUNDCMOTOR_DIRECTION_0": "とけいまわり",
    "RUNDCMOTOR_DIRECTION_1": "はんとけいまわり",
    "runDcMotor": "モーター [motorPort] [direction] を[motorvalue] % のはやさでかいてんする",
    "RUNDCMOTOR_1_MOTORPORT_0": "motor port1",
    "RUNDCMOTOR_1_MOTORPORT_1": "motor port2",
    "RUNDCMOTOR_1_MOTORPORT_2": "port1",
    "RUNDCMOTOR_1_MOTORPORT_3": "port2",
    "runDcMotor_1": "motor [motorPort]   [direction] rotates at power [motorvalue] %",
    "runServo": "サーボ [servoPort] [slot] のかくど [angle]",
    "RUNSTEPPERMOTOR_EXMOTORPORT_0": "ポート1",
    "RUNSTEPPERMOTOR_EXMOTORPORT_1": "ポート2",
    "runStepperMotor": "ステッピングモーター[exMotorPort] [direction]で[distance] ステップを[stepperSpeed] ステップ/ふんのそくどでかいてんする",
    "runStepperMotor_1": "ステッピングモーター[port] [direction]で[step] ステップを[speed] ステップ/ふんのそくどでかいてんする",
    "runEncoderMotor": "エンコーダーモーター[exMotorPort] [slot] [direction] を[args0] かくどと[encoderSpeed] かいてん/ふんのはやさでかいてんする",
    "runEncoderMotor_1": "エンコーダーモーター[exMotorPort] [slot] [direction] を[args0] かくどと[encoderSpeed] かいてん/ふんのはやさでかいてんする",
    "RUNSHUTTER_SHUTTER_0": "おされた",
    "RUNSHUTTER_SHUTTER_1": " はなされた",
    "RUNSHUTTER_SHUTTER_2": "しょうてんあわせをかいしする",
    "RUNSHUTTER_SHUTTER_3": "しょうてんあわせをていしする",
    "runShutter": "シャッター [bluePorts]のステータス [shutter]",
    "RUNFAN_FAN_0": "とけいまわり",
    "RUNFAN_FAN_1": "はんとけいまわり",
    "RUNFAN_FAN_2": "ていし",
    "runFan": "ファン [fanPorts] [fan] をかいてんする",
    "cate_79d47608": "アクション",
    "RUNLIGHTSENSOR_LIGHTPORTS_0": "ポート6",
    "RUNLIGHTSENSOR_SWITCH_0": "オフ",
    "RUNLIGHTSENSOR_SWITCH_1": "オン",
    "runLightsensor": "ひかりセンサー [lightPorts] のLEDを [switch] ",
    "GETLIGHTSENSOR_LAPORT_0": "ポート6",
    "GETLIGHTSENSOR_LAPORT_1": "ポート7",
    "GETLIGHTSENSOR_LAPORT_2": "ポート8",
    "getLightsensor": "ひかりセンサー [laport] のあかるさ",
    "getInfrared": "IRじゅしんき [bluePorts]のあたい",
    "getPirmotion": "PIRセンサー[bluePorts] がひとのうごきをけんしゅつする",
    "getTemperature": "おんどセンサー[normalPort] [slot] °C",
    "GETHUMITURE_HUMITURE_0": "しつど",
    "GETHUMITURE_HUMITURE_1": "おんど",
    "getHumiture": "おんしつどセンサー[normalPort] [humiture]",
    "getUltrasonic": "ちょうおんぱセンサー [whitePorts] のきょり (cm)",
    "getLinefollower": "ライントレースセンサー [bluePorts]",
    "GETJOYSTICK_AXIS_0": "xじく",
    "GETJOYSTICK_AXIS_1": "yじく",
    "getJoystick": "ジョイスティック [blackPorts] [Axis] じくのあたい",
    "getPotentiometer": "ポテンショメータ [blackPorts] のあたい",
    "getSoundsensor": "おんせいセンサー [soundPort] のあたい",
    "getLimitswitch": "リミットスイッチ[normalPort] [slot] がおされた",
    "GYRO_SESOR_READ_GYROAXIS_0": "xじく",
    "GYRO_SESOR_READ_GYROAXIS_1": "yじく",
    "GYRO_SESOR_READ_GYROAXIS_2": "zじく",
    "gyro_sesor_read": "ジャイロスコープ (にんいのホワイトポートじょう) [GyroAxis] のかくど",
    "getFlame": "ほのおセンサー[blackPorts]のあたい",
    "getGas": "ガスセンサー[blackPorts]のあたい",
    "getTouchSensor": "タッチセンサー [bluePorts] にふれた",
    "GETBUTTON_BUTTON_KEY_0": "key1",
    "GETBUTTON_BUTTON_KEY_1": "key2",
    "GETBUTTON_BUTTON_KEY_2": "key3",
    "GETBUTTON_BUTTON_KEY_3": "key4",
    "getButton": "ボタン [blackPorts] [button_key] がおされた",
    "getTimer": "タイマー (びょう)",
    "resetTimer": "タイマーをリセット",
    "cate_53f02e41": "しらべる",
    "runArduino": "Orionがきどうしたとき",
    "update_firmware_prompt": "ファームウェアをこうしんするまえにブザーをオフにしてください。"
};