export default {
    "orion": "Orion",
    "extensionName": "Orion",
    "extensionDescription": "",
    "firmwares_version_60bbba12": "最新固件",
    "firmwares_version_01bb1787": "出厂固件",
    "UPDATE_FIRMWARE": "固件更新",
    "connect_fail_c0e2b9a5": "请确保USB线已正确连接当前设备",
    "connect_fail_2d58cae4": "请确保当前待连接设备处于开机状态",
    "connect_fail_19a23a8c": "目前慧编程只支持连接一台设备，连接当前设备另一台已连接设备会自动断开",
    "connect_fail_71e3a310": "蓝牙4.0连接模式下，不支持上传模式，请先通过USB连接更新最新固件",
    "connect_fail_c6660567": "请确保您的电脑设备具备蓝牙4.0连接能力，且蓝牙4.0功能已经打开",
    "connect_fail_18b1b666": "请确保当前待连接设备处于开机状态",
    "connect_fail_321f3fab": "目前慧编程只支持连接一台设备，连接当前设备另一台已连接设备会自动断开",
    "upload_fail_7f425b63": "请检查该设备的积木或代码的数据类型、参数类型、编程逻辑是否符合程序规范",
    "upload_fail_c59c7bc9": "请检查您是否正确连接设备，可以尝试重启设备后再重新连接设备",
    "upload_fail_bfa364fb": "请检查是否有蓝牙模块连接设备，若有，请先拔掉蓝牙模块",
    "firmware_success_b589e7b9": "为了保证更好的体验，您可以重启设备后重新连接设备",
    "firmware_fail_8141b74c": "请检查您是否正确连接设备，可以尝试重启设备后重新连接设备，再尝试更新",
    "RUNSEVSEG_BLUEPORTS_0": "接口3",
    "RUNSEVSEG_BLUEPORTS_1": "接口4",
    "RUNSEVSEG_BLUEPORTS_2": "接口6",
    "runSevseg": "数码管 [bluePorts] 显示数字 [args0] ",
    "cate_b072ec4f": "显示",
    "RUNLED_LPORT_0": "接口3",
    "RUNLED_LPORT_1": "接口4",
    "RUNLED_LPORT_2": "接口6",
    "RUNLED_LPORT_3": "接口7",
    "RUNLED_LPORT_4": "接口8",
    "RUNLED_INDEX_0": "全部",
    "RUNLED_INDEX_1": "1",
    "RUNLED_INDEX_2": "2",
    "RUNLED_INDEX_3": "3",
    "RUNLED_INDEX_4": "4",
    "runLed": "RGB LED  [lport] 亮起[index] 灯，颜色为 [color] ",
    "BLOCK_1569571656649": "RGB LED  [lport] 亮起[index] 灯，颜色为 红 [value]  绿 [value1]   蓝 [value2] ",
    "BLOCK_1569572294998_SLOT_0": "插头1",
    "BLOCK_1569572294998_SLOT_1": "插头2",
    "BLOCK_1569572294998": "灯带 [normalPort] [slot]  全部灯，颜色为 [color] ",
    "BLOCK_1571019759214": "灯带 [normalPort] [slot] [index]   灯，颜色为 [color]",
    "runLedStrip": "灯带 [normalPort] [slot] 全部灯，颜色为 红 [value]  绿 [value1]  蓝 [value2] ",
    "BLOCK_1571022561858": "灯带 [normalPort] [slot] [index2]  灯，颜色为 红 [value]  绿 [value1]  蓝 [value2] ",
    "cate_2ced8c33": "声光",
    "RUNMOTOR_MOTORPORT_0": "电机接口1",
    "RUNMOTOR_MOTORPORT_1": "电机接口1",
    "RUNMOTOR_MOTORPORT_2": "接口1",
    "RUNMOTOR_MOTORPORT_3": "接口2",
    "RUNMOTOR_DIRECTION_0": "顺时针",
    "RUNMOTOR_DIRECTION_1": "逆时针",
    "runMotor": "电机 [motorPort]   [direction] 转动，动力 [motorvalue] %",
    "RUNDCMOTOR_DIRECTION_0": "顺时针",
    "RUNDCMOTOR_DIRECTION_1": "逆时针",
    "runDcMotor": "电机 [motorPort]   [direction] 转动，动力 [motorvalue] %",
    "RUNDCMOTOR_1_MOTORPORT_0": "电机接口1",
    "RUNDCMOTOR_1_MOTORPORT_1": "电机接口2",
    "RUNDCMOTOR_1_MOTORPORT_2": "接口1",
    "RUNDCMOTOR_1_MOTORPORT_3": "接口2",
    "runDcMotor_1": "电机 [motorPort]   [direction] 转动，动力 [motorvalue] % ",
    "runServo": "舵机 [servoPort] [slot] 角度 [angle] ",
    "RUNSTEPPERMOTOR_EXMOTORPORT_0": "接口1",
    "RUNSTEPPERMOTOR_EXMOTORPORT_1": "接口2",
    "runStepperMotor": "步进电机[exMotorPort]  [direction] 转动 [distance] 步，速度 [stepperSpeed]  步每分钟",
    "runStepperMotor_1": "步进电机 [port]   [direction] 转动 [step] 步，速度 [speed]  步每分钟",
    "runEncoderMotor": "编码电机[exMotorPort] [slot]  [direction] 转动 [args0] 度，速度 [encoderSpeed]  圈每分钟",
    "runEncoderMotor_1": "编码电机 [exMotorPort]  [slot]   [direction] 转动 [args0] 度，速度 [encoderSpeed]  圈每分钟",
    "RUNSHUTTER_SHUTTER_0": "按下快门",
    "RUNSHUTTER_SHUTTER_1": "松开快门",
    "RUNSHUTTER_SHUTTER_2": "开始对焦",
    "RUNSHUTTER_SHUTTER_3": "停止对焦",
    "runShutter": "相机快门 [bluePorts] 状态为 [shutter] ",
    "RUNFAN_FAN_0": "顺时针",
    "RUNFAN_FAN_1": "逆时针",
    "RUNFAN_FAN_2": "停止",
    "runFan": "小风扇 [fanPorts] [fan] 转动",
    "cate_79d47608": "运动",
    "RUNLIGHTSENSOR_LIGHTPORTS_0": "接口6",
    "RUNLIGHTSENSOR_SWITCH_0": "关",
    "RUNLIGHTSENSOR_SWITCH_1": "开",
    "runLightsensor": "光线传感器 [lightPorts] LED状态为 [switch] ",
    "GETLIGHTSENSOR_LAPORT_0": "接口6",
    "GETLIGHTSENSOR_LAPORT_1": "接口7",
    "GETLIGHTSENSOR_LAPORT_2": "接口8",
    "getLightsensor": "光线传感器 [laport] 光线强度",
    "getInfrared": "红外接收器 [bluePorts] 读值",
    "getPirmotion": "人体红外传感器 [bluePorts] 检测到人的运动？",
    "getTemperature": "温度传感器 [normalPort] [slot] °C",
    "GETHUMITURE_HUMITURE_0": "湿度",
    "GETHUMITURE_HUMITURE_1": "温度",
    "getHumiture": "温湿度传感器 [normalPort] [humiture] ",
    "getUltrasonic": "超声波传感器 [whitePorts] 距离（cm）",
    "getLinefollower": "巡线传感器 [bluePorts] ",
    "GETJOYSTICK_AXIS_0": "x轴",
    "GETJOYSTICK_AXIS_1": "y轴",
    "getJoystick": "摇杆 [blackPorts] [Axis] 读数",
    "getPotentiometer": "电位器 [blackPorts] 读数",
    "getSoundsensor": "声音传感器 [soundPort] 音量 ",
    "getLimitswitch": "限位开关 [normalPort] [slot] 被按下？ ",
    "GYRO_SESOR_READ_GYROAXIS_0": "X轴",
    "GYRO_SESOR_READ_GYROAXIS_1": "Y轴",
    "GYRO_SESOR_READ_GYROAXIS_2": "Z轴",
    "gyro_sesor_read": "陀螺仪 （位于任一白色接口） [GyroAxis] 角度",
    "getFlame": "火焰传感器 [blackPorts] 读数",
    "getGas": "气体传感器 [blackPorts] 读数",
    "getTouchSensor": "触摸传感器 [bluePorts] 被触摸？",
    "GETBUTTON_BUTTON_KEY_0": "key1",
    "GETBUTTON_BUTTON_KEY_1": "key2",
    "GETBUTTON_BUTTON_KEY_2": "key3",
    "GETBUTTON_BUTTON_KEY_3": "key4",
    "getButton": "按键模块 [blackPorts] [button_key] 被按下？",
    "getTimer": "计时器（s）",
    "resetTimer": "计时器归零",
    "cate_53f02e41": "感知",
    "runArduino": "当Orion启动",
    "update_firmware_prompt": "更新固件前，请关闭蜂鸣器"
};