export default {
    "sprites_data_chart": "مخطط البيانات",
    "extensionName": "مخطط البيانات",
    "extensionDescription": "استخدم هذا الملحق لتصور بياناتك. الرسم البياني يتحدث بصوت أعلى من الكلمات المطولة.",
    "open_chart": "فتح نافذة مخطط البيانات",
    "set_chart_name": "تعيين عنوان المخطط [data]",
    "SET_CHART_TYPE_TYPE_0": "الجدول",
    "SET_CHART_TYPE_TYPE_1": "مخطط خطي",
    "SET_CHART_TYPE_TYPE_2": "مخطط شريطي",
    "SET_CHART_TYPE_TYPE_3": "مخطط المحور المزدوج",
    "SET_CHART_TYPE_TYPE_4": "مخطط دائري",
    "set_chart_type": "تعيين نوع المخطط إلى [type]",
    "BLOCK_1586773178961_RATE_0": "لا يوجد وقت متأخر",
    "BLOCK_1586773178961_RATE_1": "سريع",
    "BLOCK_1586773178961_RATE_2": "بطئ",
    "BLOCK_1586773178961": "تعيين معدل التقديم إلى [rate]",
    "set_axis_name": "تعيين اسم المحور: x [xName]  y [yName]",
    "BLOCK_1586773463661": "اسم المحور y على اليمين:[rightYAxisTitle]",
    "BLOCK_1586773584919_YAXISDIRECTION_0": "محور y على اليسار",
    "BLOCK_1586773584919_YAXISDIRECTION_1": "محور y على اليمين",
    "BLOCK_1586773584919": "تعيين مجموعة البيانات [seriesName]إلى [yAxisDirection]",
    "set_data_handler": "إدخال البيانات إلى [type] x [xData]  y [yData]",
    "set_data_handler_1": "input data to [type]: item [xData] value [yData]",
    "clear_chart": "مسح البيانات",
    "close_chart": "إغلاق إطار مخطط البيانات",
    "cate_13c26abc": "مخطط البيانات",
    "DWONLOAD": "تحميل",
    "REATCH_MAX_XAXIS_DATA": "إدخال البيانات يتجاوز بالفعل الحد [0]، لذلك توقف الإدخال.",
    "REATCH_MAX_LENGEND": "تتجاوز وسائل الإيضاح التي أنشأتها الحد [0]، لذلك لا يمكنك إضافة المزيد",
    "TABLE_LABEL": "جدول البيانات",
    "CHART_LABEL": "مخطط البيانات",
    "EXPORT_FILE": "التصدير",
    "IMPORT_FILE": "استيراد",
    "IMPORT_FILE_SUCCEED": "تم الاستيراد بنجاح",
    "IMPORT_FILE_OVERSIZE_ERROR": "استيراد ملف لا يزيد عن[0]دقيقة",
    "IMPORT_FILE_FORMAT_ERROR": "ملفات تنسيق .csv فقط مدعومة للاستيراد",
    "IMPORT_FILE_FAILED": "فشل التصدير. الرجاء المحاولة مرة أخرى.",
    "EMPTY_DATA_LABEL": "بيانات فارغة",
    "BIAX_CHART_TIPS_1": "ولتقديم رسم بياني للمحور المزدوج، يجب استيفاء الشروط التالية:",
    "BIAX_CHART_TIPS_2": "1 - مجموعتان على الأقل من البيانات",
    "BIAX_CHART_TIPS_3": "2. يتم تسمية المحور y على اليمين باستخدام كتلة البرمجة",
    "BIAX_CHART_TIPS_4": "3. استخدم كتل البرمجة لتحديد البيانات التي يتم عرضها على المحور y الأيسر والمحور y الأيمن",
    "PIE_CHART_TIPS": "لا تدعم المخططات الدائرية إلا أكثر من مجموعتين من البيانات المعروضة.",
    "DATA_SET_MAX_NUM": "مجموعات البيانات تتجاوز بالفعل الحد [0]، لذلك توقف الإدخال.",
    "SINGLE_DATA_SET_ITEM_MAX_NUM": "حجم البيانات في مجموعة واحدة يتجاوز بالفعل الحد [0]، لذلك تم إيقاف الإدخال.",
    "ALL_DATA_SET_ITEM_MAX_NUM": "البيانات تتجاوز بالفعل الحد [0]، لذلك توقف الإدخال.",
    "data_chart": "مخطط البيانات",
    "BLOCK_1598863483261": "input data to [type]: item [xData] value [yData]"
};