export default {
    "sprites_data_chart": "Datový graf",
    "extensionName": "Datový graf",
    "extensionDescription": "Použijte toto rozšíření pro vizualizaci vašich dat, graf hovoří jasněji než dlouhé vysvětlování.",
    "open_chart": "otevřít okno datového grafu",
    "set_chart_name": "nastavit název grafu [data]",
    "SET_CHART_TYPE_TYPE_0": "tabulka",
    "SET_CHART_TYPE_TYPE_1": "spojnicový graf",
    "SET_CHART_TYPE_TYPE_2": "sloupcový graf",
    "SET_CHART_TYPE_TYPE_3": "dvouosý graf",
    "SET_CHART_TYPE_TYPE_4": "koláčový graf",
    "set_chart_type": "nastavit typ grafu na [type]",
    "BLOCK_1586773178961_RATE_0": "bez latence",
    "BLOCK_1586773178961_RATE_1": "rychle",
    "BLOCK_1586773178961_RATE_2": "pomalu",
    "BLOCK_1586773178961": "nastavit frekvenci vykreslování na [rate]",
    "set_axis_name": "nastavit název osy: x [xName]  y [yName]",
    "BLOCK_1586773463661": "název osy y vpravo:[rightYAxisTitle]",
    "BLOCK_1586773584919_YAXISDIRECTION_0": "osa y vlevo",
    "BLOCK_1586773584919_YAXISDIRECTION_1": "osa y vpravo",
    "BLOCK_1586773584919": "nastavit datovou skupinu [seriesName]na [yAxisDirection]",
    "set_data_handler": "vstupní data na [type]: x [xData]  Y [yData]",
    "set_data_handler_1": "input data to [type]: item [xData] value [yData]",
    "clear_chart": "vymazat data",
    "close_chart": "zavřít okno datového grafu",
    "cate_13c26abc": "Datový graf",
    "DWONLOAD": "stáhnout",
    "REATCH_MAX_XAXIS_DATA": "Vstupní data překročily limit [0], takže vstup byl zastaven.",
    "REATCH_MAX_LENGEND": "Vámi vytvořené legendy překračují limit [0], takže nemůžete přidat další",
    "TABLE_LABEL": "Tabulka dat",
    "CHART_LABEL": "Datový graf",
    "EXPORT_FILE": "Export",
    "IMPORT_FILE": "Import",
    "IMPORT_FILE_SUCCEED": "import byl úspěšný",
    "IMPORT_FILE_OVERSIZE_ERROR": "importovat soubor ne větší než[0]m",
    "IMPORT_FILE_FORMAT_ERROR": "pro import jsou podporovány pouze soubory formátu .csv",
    "IMPORT_FILE_FAILED": "Export se nezdařil. Zkuste to prosím znovu.",
    "EMPTY_DATA_LABEL": "Prázdná data",
    "BIAX_CHART_TIPS_1": "Pro zobrazení grafu s dvěma osami musí být splněny tyto podmínky:",
    "BIAX_CHART_TIPS_2": "1. Nejméně 2 skupiny dat",
    "BIAX_CHART_TIPS_3": "2. osa y na pravé straně je pojmenována pomocí bloku kódu",
    "BIAX_CHART_TIPS_4": "3. Pomocí kódovacích bloků definujte, jaká data se zobrazí na levé a pravé ose y",
    "PIE_CHART_TIPS": "Výsečové grafy podporují zobrazení nejvýše dvou skupin dat.",
    "DATA_SET_MAX_NUM": "Datové skupiny již překračují limit [0], vstup byl zastaven.",
    "SINGLE_DATA_SET_ITEM_MAX_NUM": "Objem dat v jedné skupině již překračuje limit [0], vstup byl zastaven.",
    "ALL_DATA_SET_ITEM_MAX_NUM": "Vstup dat již překračuje limit [0], vstup byl zastaven.",
    "data_chart": "Datový graf",
    "BLOCK_1598863483261": "input data to [type]: item [xData] value [yData]"
};