export default {
    "sprites_data_chart": "Tietojen kaavio",
    "extensionName": "Tietokartta",
    "extensionDescription": "Käytä tätä laajennusta visualisoimaan tietojasi. Kaavio kertoo enemmän kuin pitkät lauseet.",
    "open_chart": "Avaa Data kaavio-ikkuna",
    "set_chart_name": "kaavion otsikon asettaminen [data]",
    "SET_CHART_TYPE_TYPE_0": "Taulukossa",
    "SET_CHART_TYPE_TYPE_1": "viivakaavio",
    "SET_CHART_TYPE_TYPE_2": "pylväskaavio",
    "SET_CHART_TYPE_TYPE_3": "kaksiakselikaavio",
    "SET_CHART_TYPE_TYPE_4": "ympyrädiagrammi",
    "set_chart_type": "määritä kaaviotyypiksi [type]",
    "BLOCK_1586773178961_RATE_0": "ei viivettä",
    "BLOCK_1586773178961_RATE_1": "nopea",
    "BLOCK_1586773178961_RATE_2": "hidas",
    "BLOCK_1586773178961": "aseta renderointinopeudeksi [rate]",
    "set_axis_name": "Aseta akselin nimi: x [xName]  Y [yName]",
    "BLOCK_1586773463661": "nimi y-akseli oikealla: [rightYAxisTitle]",
    "BLOCK_1586773584919_YAXISDIRECTION_0": "y-akseli vasemmalla",
    "BLOCK_1586773584919_YAXISDIRECTION_1": "y-akseli oikealla",
    "BLOCK_1586773584919": "aseta tietoryhmäksi [seriesName] arvoksi [yAxisDirection]",
    "set_data_handler": "syötä tietoja [type]: x [xData]  Y [yData]",
    "set_data_handler_1": "input data to [type]: item [xData] value [yData]",
    "clear_chart": "tyhjennä tiedot",
    "close_chart": "Sulje Data kaavio-ikkuna",
    "cate_13c26abc": "Tietokartta",
    "DWONLOAD": "lataa",
    "REATCH_MAX_XAXIS_DATA": "Tietosyöttö ylittää jo rajan [0], joten syöttö on pysähtynyt.",
    "REATCH_MAX_LENGEND": "Luomasi legendat ylittävät rajan [0], joten et voi lisätä lisää",
    "TABLE_LABEL": "Datataulukko",
    "CHART_LABEL": "Tietokartta",
    "EXPORT_FILE": "Vie",
    "IMPORT_FILE": "Tuo",
    "IMPORT_FILE_SUCCEED": "tuonti onnistui",
    "IMPORT_FILE_OVERSIZE_ERROR": "tuontitiedosto on enintään [0] m",
    "IMPORT_FILE_FORMAT_ERROR": "vain tuetut .csv-tiedostot",
    "IMPORT_FILE_FAILED": "Vienti epäonnistui. Yritä uudelleen.",
    "EMPTY_DATA_LABEL": "Tyhjät tiedot",
    "BIAX_CHART_TIPS_1": "Kaksiakselikaavion esittämiseksi on täytettävä seuraavat ehdot:",
    "BIAX_CHART_TIPS_2": "1. Ainakin 2 tietoryhmää",
    "BIAX_CHART_TIPS_3": "2. Y-akseli oikealla on nimetty koodauslohkolla",
    "BIAX_CHART_TIPS_4": "3. Käytä koodauslohkoja määritelläksesi, mitä tietoja näytetään vasemmalla y-akselilla ja oikealla y-akselilla",
    "PIE_CHART_TIPS": "Ympyrädiagrammit tukevat vain korkeintaan kahta näytettyä tietoryhmää.",
    "DATA_SET_MAX_NUM": "Tietoryhmät ylittävät jo rajan [0], joten syöttö on pysähtynyt.",
    "SINGLE_DATA_SET_ITEM_MAX_NUM": "Yhden ryhmän tietomäärä ylittää jo rajan [0], joten syöttö on pysähtynyt.",
    "ALL_DATA_SET_ITEM_MAX_NUM": "Tiedot ylittävät jo rajan [0], joten syöttö on pysähtynyt.",
    "data_chart": "Tietokartta",
    "BLOCK_1598863483261": "input data to [type]: item [xData] value [yData]"
};