export default {
    "auriga": "mBot Ranger",
    "extensionName": "mBot Ranger",
    "extensionDescription": "",
    "firmwares_version_0": "Firmware Online",
    "UPDATE_FIRMWARE": "Aggiornamento Firmware",
    "settings_8013da10": "Set smart servo zero position",
    "connect_fail_4e720cf3": "Assicurarsi che il cavo USB sia collegato correttamente al dispositivo.",
    "connect_fail_29312b3b": "Assicurarsi che il dispositivo da collegare sia acceso.",
    "connect_fail_09099d40": "Solo un dispositivo può essere collegato alla volta in questa versione. Quindi, il collegamento di questo dispositivo porterà alla disconnessione di quella precedente.",
    "connect_fail_34866b93": "La modalità di caricamento non è supportata quando si attiva la modalità Bluetooth 4,0. Collegare il dispositivo tramite il cavo USB e riprovare ad aggiornare il firmware.",
    "connect_fail_c2d05fc8": "Assicurarsi che il computer supporti Bluetooth 4,0 e Bluetooth già attivati.",
    "connect_fail_f198b930": "Assicurarsi che il dispositivo da collegare sia acceso.",
    "connect_fail_349388ff": "Solo un dispositivo può essere collegato alla volta in questa versione. Quindi, il collegamento di questo dispositivo porterà alla disconnessione di quella precedente.",
    "upload_fail_068e0a12": "Si prega di esaminare i blocchi di codifica o il codice per questo dispositivo. Assicurarsi che tutti i dati, i parametri e la logica di programmazione siano corretti.",
    "upload_fail_62e96a5f": "Assicurarsi che il dispositivo sia collegato correttamente. È possibile riavviare il dispositivo e collegarlo nuovamente.",
    "firmware_success_db9b07ee": "Per una migliore esperienza, è possibile riavviare il dispositivo e collegarlo ancora una volta.",
    "firmware_fail_901081f9": "Assicurarsi che il dispositivo sia collegato correttamente. È possibile riavviare il dispositivo, collegarlo di nuovo e riprovare ad aggiornare il firmware.",
    "auriga_show_all_led_time": "[ICON] tutte le luci accesse con il colore [COLOR] per [TIME] secs",
    "auriga_show_all_led": "[ICON] tutte le luci accese con colore[COLOR]",
    "auriga_show_all_led_rgb": "[ICON]tutte le luci accese con colore rosso [R] verde [G] blu [B]",
    "auriga_show_led_time": "[ICON]accendi la luce [LED_POSTION] con colore [COLOR] per [TIME] secondi",
    "auriga_show_led": "[ICON]accendi la luce [LED_POSTION] con colore [COLOR]",
    "auriga_show_led_rgb": "[ICON] accendere [LED_POSTION] luce con colore rosso[R] verde [G] blu [B]",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_0": "C2",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_1": "D2",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_2": "E2",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_3": "F2",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_4": "G2",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_5": "A2",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_6": "B2",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_7": "C3",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_8": "D3",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_9": "E3",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_10": "F3",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_11": "G3",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_12": "A3",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_13": "B3",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_14": "C4",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_15": "D4",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_16": "E4",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_17": "F4",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_18": "G4",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_19": "A4",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_20": "B4",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_21": "C5",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_22": "D5",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_23": "E5",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_24": "F5",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_25": "G5",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_26": "A5",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_27": "B5",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_28": "C6",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_29": "D6",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_30": "E6",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_31": "F6",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_32": "G6",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_33": "A6",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_34": "B6",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_35": "C7",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_36": "D7",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_37": "E7",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_38": "F7",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_39": "G7",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_40": "A7",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_41": "B7",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_42": "C8",
    "AURIGA_SOUND_PLAY_NOTE_NOTE_43": "D8",
    "auriga_sound_play_note": "[ICON]suona la nota [NOTE] per [BEAT] battute",
    "auriga_sound_play_hz": "[ICON]fai un suono alla frequenza [HZ] Hz per [TIME] secondi",
    "CATEGORY_LIGHT": "Luce e suono",
    "auriga_forward_time": "[ICON] vai avanti alla potenza [POWER] % per [TIME] sec",
    "auriga_backward_time": "[ICON]vai indietro alla potenza [POWER] % per[TIME] secondi",
    "auriga_turnleft_time": "[ICON]ruota a sinistra alla potenza [POWER] % per [TIME] sec",
    "auriga_turnright_time": "[ICON] girare a destra alla potenza [POWER] % per [TIME] sec",
    "AURIGA_MOVE_MOVE_DIRECTION_0": "avanti",
    "AURIGA_MOVE_MOVE_DIRECTION_1": "indietro",
    "AURIGA_MOVE_MOVE_DIRECTION_2": "ruota a sinistra",
    "AURIGA_MOVE_MOVE_DIRECTION_3": "ruota a destra",
    "auriga_move": "[ICON][MOVE_DIRECTION] alla potenza [POWER] %",
    "auriga_move_wheel_speed": "[ICON] ruota sinistra alla potenza [POWER_LEFT] %, ruota destra alla potenza [POWER_RIGHT] %",
    "auriga_move_stop": "[ICON]fermare il movimento",
    "CATEGORY_ACTION": "Azione",
    "AURIGA_DETECT_LIGHT_LED_PORT_0": "port6",
    "AURIGA_DETECT_LIGHT_LED_PORT_1": "port7",
    "AURIGA_DETECT_LIGHT_LED_PORT_2": "port8",
    "AURIGA_DETECT_LIGHT_LED_PORT_3": "port9",
    "AURIGA_DETECT_LIGHT_LED_PORT_4": "port10",
    "AURIGA_DETECT_LIGHT_LED_STATUS_0": "open",
    "AURIGA_DETECT_LIGHT_LED_STATUS_1": "close",
    "auriga_detect_light_led": "[ICON] set light sensor [PORT] LED status to [STATUS]",
    "AURIGA_DETECT_LIGHT_PORT_0": "sulla scheda 1",
    "AURIGA_DETECT_LIGHT_PORT_1": "sulla scheda 2",
    "AURIGA_DETECT_LIGHT_PORT_2": "porta6",
    "AURIGA_DETECT_LIGHT_PORT_3": "porta7",
    "AURIGA_DETECT_LIGHT_PORT_4": "porta8",
    "AURIGA_DETECT_LIGHT_PORT_5": "porta9",
    "AURIGA_DETECT_LIGHT_PORT_6": "porta10",
    "auriga_detect_light": "[ICON] sensore di luce [PORT] valore dell'intensità della luce",
    "auriga_detect_temperature": "[ICON] temperatura",
    "AURIGA_DETECT_LOUDNESS_PORT_0": "sulla scheda",
    "AURIGA_DETECT_LOUDNESS_PORT_1": "port6",
    "AURIGA_DETECT_LOUDNESS_PORT_2": "port7",
    "AURIGA_DETECT_LOUDNESS_PORT_3": "port8",
    "AURIGA_DETECT_LOUDNESS_PORT_4": "port9",
    "AURIGA_DETECT_LOUDNESS_PORT_5": "port10",
    "auriga_detect_loudness": "[ICON] sensore suono [PORT] rumoroso",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_0": "asse-x",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_1": "asse-y",
    "AURIGA_DETECT_BOARD_GYRO_ANGLE_AXIS_2": "asse z",
    "auriga_detect_board_gyro_angle": "[ICON]angolo giroscopio di bordo [AXIS]",
    "auriga_detect_external_ultrasonic": "[ICON]sensore ultrasuoni [PORT] distanza",
    "auriga_detect_external_linefollower": "[ICON] sensore di inseguimento linea [PORT] Mostra valore",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "sinistra",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "destra",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "tutti",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "nessuno",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "nero",
    "AURIGA_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "bianco",
    "auriga_event_external_linefollower": "[ICON]sensore di inseguimento linea [PORT] rileva [LINEFOLLOW_STATE] è [BLACK_WHITE]?",
    "auriga_detect_timer": "[ICON]cronometro",
    "auriga_reset_timer": "[ICON] azzera cronometro",
    "CATEGORY_SENSOR": "Sensori",
    "auriga_when_board_launch": "quando si avvia mBot Ranger(Auriga)",
    "AURIGA_DETECT_ANGLE_AXIS_0": "asse-x",
    "AURIGA_DETECT_ANGLE_AXIS_1": "asse-y",
    "AURIGA_DETECT_ANGLE_AXIS_2": "asse z",
    "auriga_run_board_encoder_motor": "[ICON] encoder motor [PORT] [ROTATE] ruota alla potenza [POWER]%",
    "auriga_run_board_encoder_motor_speed": "[ICON]encoder motor [PORT] [ROTATE] ruota alla velocità di [POWER] r/min",
    "auriga_run_board_encoder_motor_pos": "[ICON] encoder motor [PORT] [ROTATE] rotazione [DEGREE] alla potenza [POWER] %",
    "auriga_run_encoder_motor": "[ICON] encoder motor[PORT] [SLOT] [ROTATE] rotazione [DEGREE] alla potenza [POWER] %",
    "auriga_run_smart_servo_to_zero": "[ICON] servo smart [INDEX] ruotato alla posizione iniziale",
    "SET_SMART_ZERO_TITLE": "Set smart servo zero position",
    "SET_SMART_ZERO_NO": "select serial number",
    "SET_SMART_ZERO_BTN": "set current position as zero position",
    "SET_SMART_ZERO_BTN_LOADING": "setting zero position...",
    "SET_SMART_ZERO_SUCCESS": "Setting successful",
    "SET_SMART_ZERO_FAIL": "Setting failed"
};