export default {
    "raspberrypi_novapi": "NovaPi",
    "extensionName": "NovaPi",
    "extensionDescription": "",
    "timer": "timer",
    "timer_reset": "reset timer",
    "MOTION_SENSOR_ACC_AXIS_0": "x-axis",
    "MOTION_SENSOR_ACC_AXIS_1": "y-axis",
    "MOTION_SENSOR_ACC_AXIS_2": "z-axis",
    "motion_sensor_acc": "motion sensor acceleration on[AXIS](m/s²）",
    "motion_sensor_gyro": "motion  sensor angular velocity on [AXIS](°/s)",
    "motion_sensor_angle": "motion sensor angle on[AXIS](°)",
    "motion_sensor_set_threshold": "motion sensor sets vibration detection sensitivity to [THRESHOLD]%",
    "motion_sensor_check_shake": "motion sensor detected vibration?",
    "MOTION_SENSOR_RESET_ROTATION_AXIS_0": "z-axis",
    "motion_sensor_reset_rotation": "motion sensor resets rotated angle on[AXIS]",
    "compitition_mode": "competition is in automatic stage?",
    "cate_191bb821": "NovaPi",
    "DRGB_INIT_NUM_0": "1",
    "DRGB_INIT_NUM_1": "2",
    "DRGB_INIT_NUM_2": "3",
    "DRGB_INIT_NUM_3": "4",
    "DRGB_INIT_NUM_4": "5",
    "DRGB_INIT_NUM_5": "6",
    "DRGB_INIT_PORT_0": "port1",
    "DRGB_INIT_PORT_1": "port2",
    "DRGB_INIT_PORT_2": "port3",
    "DRGB_INIT_PORT_3": "port4",
    "DRGB_INIT_PORT_4": "port5",
    "DRGB_INIT_INDEX_0": "1",
    "DRGB_INIT_INDEX_1": "2",
    "DRGB_INIT_INDEX_2": "3",
    "DRGB_INIT": "initialize dual RGB sensor [NUM] : at  [PORT] the [INDEX] one",
    "DRGB_SET_SENSOR_KP": "dual RGB sensor [NUM] sets Kp in motor differential speed calculation to [KP]",
    "DRGB_SET_SENSOR_COLOR_COLOR_0": "red",
    "DRGB_SET_SENSOR_COLOR_COLOR_1": "green",
    "DRGB_SET_SENSOR_COLOR_COLOR_2": "blue",
    "DRGB_SET_SENSOR_COLOR": "dual RGB sensor[NUM] sets fill light to [COLOR]",
    "DRGB_CHECK_COLOR_CHANNEL_0": "RGB1",
    "DRGB_CHECK_COLOR_CHANNEL_1": "RGB2",
    "DRGB_CHECK_COLOR_COLOR_0": "white",
    "DRGB_CHECK_COLOR_COLOR_1": "red",
    "DRGB_CHECK_COLOR_COLOR_2": "yellow",
    "DRGB_CHECK_COLOR_COLOR_3": "green",
    "DRGB_CHECK_COLOR_COLOR_4": "blue",
    "DRGB_CHECK_COLOR_COLOR_5": "black",
    "DRGB_CHECK_COLOR": "dual RGB sensor [NUM] probe [CHANNEL]  detected color [COLOR]?",
    "DRGB_SENSOR_STATUS_STATE_0": "00",
    "DRGB_SENSOR_STATUS_STATE_1": "01",
    "DRGB_SENSOR_STATUS_STATE_2": "10",
    "DRGB_SENSOR_STATUS_STATE_3": "11",
    "DRGB_SENSOR_STATUS": "dual RGB sensor [NUM] sets probe status to（RGB2|RGB1）[STATE]?",
    "DRGB_BACKGROUND_DETECTED": "Dual RGB sensor [NUM] probe [CHANNEL] detected background color?",
    "DRGB_GET_INTENSITY": "dual RGB sensor [NUM] probe [CHANNEL] value returned",
    "DRGB_GET_POSITION_OFFSET": "dual RGB sensor [NUM] line position offset （-100~100）",
    "DRGB_GET_POSITION_OFFSET_KP": "dual RGB sensor[NUM] motor differential speed (line position offset × Kp)",
    "cate_4f8862d4": "Dual RGB Sensor",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_0": "DC1",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_1": "DC2",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_2": "DC3",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_3": "DC4",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_4": "DC5",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_5": "DC6",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_6": "DC7",
    "POWER_EXPAND_DCMOTOR_POWER_CHANNEL_7": "DC8",
    "POWER_EXPAND_DCmotor_power": "DC motor [CHANNEL] rotates at power [POWER] %",
    "POWER_EXPAND_DCmotor_stop": "DC motor [CHANNEL] stops",
    "POWER_EXPAND_BLMOTOR_POWER_CHANNEL_0": "BL1",
    "POWER_EXPAND_BLMOTOR_POWER_CHANNEL_1": "BL2",
    "POWER_EXPAND_BLmotor_power": "brushless motor[CHANNEL]rotates at power [POWER] %",
    "POWER_EXPAND_BLmotor_stop": "brushless motor [CHANNEL]stops",
    "POWER_EXPAND_SOLENOIDVALVE_STATUS_0": "power off",
    "POWER_EXPAND_SOLENOIDVALVE_STATUS_1": "power on",
    "POWER_EXPAND_solenoidvalve": "solenoid valve [CHANNEL] sets status to [STATUS]",
    "cate_70323d75": "Power Expansion Board",
    "ENCODER_MOTOR_POWER_PORT_0": "M1",
    "ENCODER_MOTOR_POWER_PORT_1": "M2",
    "ENCODER_MOTOR_POWER_PORT_2": "M3",
    "ENCODER_MOTOR_POWER_PORT_3": "M4",
    "ENCODER_MOTOR_POWER_PORT_4": "M5",
    "ENCODER_MOTOR_POWER_PORT_5": "M6",
    "encoder_motor_power": "encoder motor [PORT]rotates at power [POWER] %",
    "encoder_motor_move": "encoder motor [PORT] rotates by[POSITION] degree at speed of [SPEED]r/min",
    "encoder_motor_move_to": "encoder motor [PORT] rotates to [POSITION] degree at speed of [SPEED]r/min",
    "encoder_motor_speed": "encoder motor[PORT]rotates at speed of [SPEED] r/min",
    "encoder_motor_get_speed": "encoder motor [PORT] rotational speed (r/min)",
    "encoder_motor_get_pos": "encoder motor [PORT] angle(°)",
    "cate_444d2032": "Encoder Motor",
    "SMARTSERVO_INIT_NUM_0": "1",
    "SMARTSERVO_INIT_NUM_1": "2",
    "SMARTSERVO_INIT_NUM_2": "3",
    "SMARTSERVO_INIT_NUM_3": "4",
    "SMARTSERVO_INIT_NUM_4": "5",
    "SMARTSERVO_INIT_NUM_5": "6",
    "SMARTSERVO_INIT_NUM_6": "7",
    "SMARTSERVO_INIT_NUM_7": "8",
    "SMARTSERVO_INIT_NUM_8": "9",
    "SMARTSERVO_INIT_NUM_9": "10",
    "SMARTSERVO_INIT_NUM_10": "11",
    "SMARTSERVO_INIT_NUM_11": "12",
    "SMARTSERVO_INIT_INDEX_0": "1",
    "SMARTSERVO_INIT_INDEX_1": "2",
    "SMARTSERVO_INIT_INDEX_2": "3",
    "SMARTSERVO_INIT_INDEX_3": "4",
    "SMARTSERVO_INIT_INDEX_4": "5",
    "SMARTSERVO_INIT_INDEX_5": "6",
    "smartservo_init": "initialize smart servo[NUM]: at [PORT] the [INDEX] one",
    "smartservo_move": "smart servo [NUM] rotates by [POSITION]degree at speed of [SPEED] r/min",
    "smartservo_move_to": "smart servo [NUM] rotates to [POSITION] degree at speed of [SPEED]r/min",
    "smartservo_set_power": "smart servo [NUM] rotates at power [POWER]%",
    "SMARTSERVO_POWER_TYPE_0": "current",
    "SMARTSERVO_POWER_TYPE_1": "voltage",
    "SMARTSERVO_POWER_TYPE_2": "speed",
    "SMARTSERVO_POWER_TYPE_3": "angle",
    "SMARTSERVO_POWER_TYPE_4": "temperature",
    "SMARTSERVO_POWER": "smart servo [NUM] current[TYPE]",
    "cate_e3df46fb": "Smart Servo",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_0": "1",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_1": "2",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_2": "3",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_3": "4",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_4": "↑",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_5": "↓",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_6": "←",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_7": "→",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_8": "L1",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_9": "L2",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_10": "R1",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_11": "R2",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_12": "+",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_13": "≡",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_14": "L_Thumb",
    "BT_CONTROLLER_BUTTON_PRESSED_BUTTON_15": "R_Thumb",
    "BT_CONTROLLER_BUTTON_PRESSED": "Bluetooth controller's button [BUTTON]pressed?",
    "BT_CONTROLLER_JOYSTICK_POSITION_0": "LX",
    "BT_CONTROLLER_JOYSTICK_POSITION_1": "LY",
    "BT_CONTROLLER_JOYSTICK_POSITION_2": "RX",
    "BT_CONTROLLER_JOYSTICK_POSITION_3": "RY",
    "BT_CONTROLLER_JOYSTICK": "Bluetooth controller's joystick[POSITION](-100 ~ 100)",
    "cate_5cebd298": "Bluetooth Controller",
    "distance_sensor_init": "initialize ranging sensor [NUM]: at [PORT] the [INDEX]one",
    "distance_sensor_get_data": "ranging sensor [NUM]distance to obstacle (CM)",
    "cate_f9edb9ef": "Ranging Sensor"
};