export default {
    "codey": "Codey",
    "extensionName": "Codey",
    "extensionDescription": "ei mitään",
    "firmwares_version_0": "Uusin firmware",
    "UPDATE_FIRMWARE": "Päivitä Firmware",
    "settings_0": "Väri-sensorin kalibrointi",
    "settings_1": "Kalibroi gyro",
    "settings_54fdf115": "Tilatarkistus",
    "connect_fail_dc0edd70": "Varmista, että USB-kaapeli on kytketty oikein laitteeseen.",
    "connect_fail_ac025070": "Varmista, että laite on kytketty päälle.",
    "connect_fail_3a075878": "Vain yksi laite voidaan yhdistää kerrallaan tässä versiossa. Joten kytkemällä tämä laite johtaa katkaisua edellisen.",
    "connect_fail_12b07c7c": "Bluetooth direct connection only available on Mac computers",
    "connect_fail_ccd91361": "Varmista, että laite on kytketty päälle.",
    "connect_fail_1e4caec6": "Vain yksi laite voidaan yhdistää kerrallaan tässä versiossa. Tämän laitteen yhdistäminen johtaa edellisen yhteyden katkaiseminen.",
    "upload_fail_d5fa5444": "Varmista, että laite on kytketty oikein. Voit käynnistää laitteen uudelleen ja yhdistää sen uudelleen.",
    "upload_fail_ae3a4ed5": "Varmista, että laite ohjelmisto toimii hyvin. Voit päivittää laitteisto-ohjelmiston tai palauttaa sen tehdas asetuksiin ja yrittää uudelleen.",
    "upload_fail_d36df56a": "Tarkista laitteen laite ohjelmistossa, onko se toimii hyvin. Jos ei, yritä uudelleen laite ohjelmiston päivittämisen jälkeen.",
    "firmware_success_c205609a": "Jotta saat paremman käyttö kokemuksen, Käynnistä laite uudelleen ja liitä se uudelleen.",
    "firmware_fail_34b7a344": "Varmista, että laite on kytketty oikein. Käynnistä laite uudelleen, liitä se uudelleen ja yritä sitten päivittää laite ohjelmisto uudelleen.",
    "firmware_fail_340c3de8": "Tämä laite ei tue laite ohjelmisto päivityksiä Bluetooth-sovittimella tai muilla tavoilla.",
    "codey_emotion_look_up": "katso ylös",
    "codey_emotion_look_down": "Katso alas",
    "codey_emotion_look_left": "Katso vasemmalle",
    "codey_emotion_look_right": "Katso oikealle",
    "codey_emotion_look_around": "Katso ympärille",
    "codey_emotion_wink": "vilkuta",
    "codey_emotion_smile": "hymy",
    "codey_emotion_yeah": "yeah",
    "codey_emotion_naughty": "Tuhma",
    "codey_emotion_proud": "Ylpeä",
    "codey_emotion_coquetry": "namia",
    "codey_emotion_awkward": "uh_oh",
    "codey_emotion_exclaim": "wow",
    "codey_emotion_aggrieved": "satuttaa",
    "codey_emotion_sad": "surullinen",
    "codey_emotion_angry": "vihainen",
    "codey_emotion_greeting": "hei",
    "codey_emotion_sprint": "pyrähdys",
    "codey_emotion_startle": "Peloissaan",
    "codey_emotion_shiver": "vapista",
    "codey_emotion_dizzy": "Huimausta",
    "codey_emotion_sleepy": "Haukotus",
    "codey_emotion_sleeping": "Nukkua",
    "codey_emotion_revive": "herätä",
    "codey_emotion_agree": "kyllä",
    "codey_emotion_deny": "ei",
    "CATEGORY_EMOTION": "Tunteita",
    "meos_show_led_matrix_face_with_time": "[ICON] näytä kuva [PANEL] [TIME] sekuntia",
    "meos_show_led_matrix_face": "[ICON] näytä kuva [PANEL]",
    "meos_show_led_matrix_face_position": "[ICON] näytä kuva [PANEL] x:[AXIS-X] y:[AXIS-Y]",
    "meos_show_led_matrix_turn_off": "[ICON] Sammuta näyttö",
    "meos_show_led_matrix": "[ICON] Näytä [STRING]",
    "meos_show_led_matrix_string": "[ICON] Näytä [STRING] kunnes selaus valmis",
    "meos_show_led_matrix_string_position": "[ICON] näyttää [STRING] x:[X] y:[Y]",
    "meos_show_led_matrix_position": "[ICON] valot päälle x: [X] y: [Y]",
    "meos_light_off_led_matrix_position": "[ICON] valot pois x: [X] y: [Y]",
    "meos_toggle_led_matrix_position": "[ICON] vaihda valot päälle ja pois x: [X] y: [Y]",
    "meos_event_led_matrix_position_is_light": "[ICON] x: [X] y: [Y] onko valot päällä?",
    "CATEGORY_SHOW": "Ulkonäkö",
    "meos_show_led_with_time": "[ICON] RGB LED valot päälle [COLOR] [TIME] sekunniksi",
    "meos_show_led": "[ICON] RGB LED valot päälle [COLOR]",
    "MEOS_SHOW_LED_RGB_RGB_0": "punainen",
    "MEOS_SHOW_LED_RGB_RGB_1": "vihreä",
    "MEOS_SHOW_LED_RGB_RGB_2": "sininen",
    "meos_show_led_rgb": "[ICON] asetta indikaattori[RGB]väriin[VALUE]",
    "meos_turn_off_led": "[ICON] RGB LED valot pois",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_0": "punainen",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_1": "vihreä",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_2": "sininen",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_3": "keltainen",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_4": "turkoosi",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_5": "violetti",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_6": "valkoinen",
    "meos_rocky_show_led_color": "[ICON] näytää Rockyn valot värillä[COLORLIST]",
    "meos_rocky_turn_off_led_color": "[ICON] Rocky valot pois",
    "CATEGORY_LIGHT": "Valaistus",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_0": "hei",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_1": "moikka",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_2": "heippa",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_3": "yeah",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_4": "wow",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_5": "nauraa",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_6": "hyräillä",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_7": "surullinen",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_8": "huokaista",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_9": "vihainen",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_10": "vihainen",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_11": "yllättynyt",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_12": "namia",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_13": "utelias",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_14": "nolostunut",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_15": "valmis",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_16": "pyrähdys",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_17": "uninen",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_18": "miau",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_19": "alku",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_20": "vaihto",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_21": "piippaa",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_22": "pörisee",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_23": "pakoputki",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_24": "räjähdys",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_25": "sainpas",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_26": "satuttaa",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_27": "hyppää",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_28": "laser",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_29": "uusi taso",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_30": "vähän energiaa",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_31": "metallin kilistely",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_32": "kehote ääni",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_33": "oikea",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_34": "väärin",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_35": "rengas",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_36": "pisteet",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_37": "laukaus",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_38": "askel_1",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_39": "askel_2",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_40": "herätä",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_41": "varoitus",
    "meos_show_play_sound": "[ICON] soita ääni [SOUNDLIST]",
    "meos_show_play_sound_wait": "[ICON] toista ääni [SOUNDLIST] kunnes hiljennä",
    "meos_show_stop_allsound": "[ICON] hiljennä kaikki äänet",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_0": "C2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_1": "D2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_2": "E2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_3": "F2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_4": "G2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_5": "A2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_6": "B2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_7": "C3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_8": "D3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_9": "E3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_10": "F3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_11": "G3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_12": "A3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_13": "B3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_14": "C4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_15": "D4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_16": "E4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_17": "F4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_18": "G4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_19": "A4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_20": "B4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_21": "C5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_22": "D5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_23": "E5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_24": "F5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_25": "G5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_26": "A5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_27": "B5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_28": "C6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_29": "D6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_30": "E6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_31": "F6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_32": "G6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_33": "A6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_34": "B6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_35": "C7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_36": "D7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_37": "E7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_38": "F7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_39": "G7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_40": "A7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_41": "B7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_42": "C8",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_43": "D8",
    "meos_show_play_note_with_string": "[ICON] soita nuottia [SOUNDNOTE] [SOUNDBEAT] iskun ajan",
    "meos_show_pause_note": "[ICON] tauko [TIME] iskun ajan",
    "meos_show_play_hz": "[ICON] soita ääntä taajudella [HZ] Hz [TIME] sekuntia",
    "meos_show_change_volume": "[ICON] muuta äänenvoimakkuutta [VOLUME]",
    "meos_show_set_volume": "[ICON] aseta äänenvoimakkuus [VOLUME] %",
    "meos_detect_sound_volume": "[ICON] Äänenvoimakkuus",
    "CATEGORY_PLAY": "Kaiutin",
    "meos_move_forward_with_time": "[ICON] siirry eteenpäin teholla [POWER] % [TIME] sekuntia",
    "meos_move_backward_with_time": "[ICON] siirry taaksepäin teholla [POWER] % [TIME] sekuntia",
    "meos_move_left_with_time": "[ICON] käänny vasemalle teholla [POWER] % [TIME] sekuntia",
    "meos_move_right_with_time": "[ICON] käänny oikealle teholla [POWER] % [TIME] sekuntia",
    "meos_rocky_keep_absolute_forward": "[ICON] liiku suoraan eteenpäin nopeudella [POWER]% [TIME]sekuntia",
    "meos_rocky_keep_absolute_backward": "[ICON] liikkuu suoraan taaksepäin nopeudella[POWER]% [TIME]sekuntia",
    "meos_move_left_with_angle": "[image_4] Käänny vasemmalle [ICON] [ANGLE] astetta, kunnes valmis",
    "meos_move_right_with_angle": "[image_5] Käänny oikealle [ICON] [ANGLE] astetta, kunnes valmis",
    "MEOS_MOVE_DIRECTION_0": "liiku eteenpäin",
    "MEOS_MOVE_DIRECTION_1": "liiku taaksepäin",
    "MEOS_MOVE_DIRECTION_2": "käänny vasemmalle",
    "MEOS_MOVE_DIRECTION_3": "käänny oikealle",
    "meos_move": "[ICON][DIRECTION] teholla [POWER] %",
    "meos_move_with_motors": "[ICON] vasen pyörä pyörii [LEFT_POWER] %，oikea pyörä pyörii [RIGHT_POWER] %",
    "meos_move_stop": "[ICON] pysähdy",
    "MEOS_ROCKY_KEEP_ABSOLUTE_RUN_DIRECTION_0": "liiku eteenpäin",
    "MEOS_ROCKY_KEEP_ABSOLUTE_RUN_DIRECTION_1": "liiku taaksepäin",
    "meos_rocky_keep_absolute_run": "[ICON]liikkuu suoraan kohti[DIRECTION] nopeudella [POWER]% [TIME]sekuntia",
    "CATEGORY_ACTION": "Liike",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_0": "A",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_1": "B",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_2": "C",
    "meos_event_button_pressed": "[ICON] näppäintä [BUTTONS] painettu?",
    "meos_event_connect_rocky": "[ICON] kun Codey on kytketty Rockyyn",
    "meos_detect_potentiometer": "[ICON] Potentiometri arvo",
    "meos_detect_volume": "[ICON] äänentaso",
    "meos_detect_lightness": "[ICON] ympäristön valon voimakkuus",
    "meos_dump_energy": "[ICON] akun varaustaso",
    "meos_event_is_shaked": "[ICON] Ravistaa？",
    "meos_detect_shaked_strength": "[ICON] värinän voimakkuus",
    "MEOS_EVENT_IS_TILT_DIRECTION_0": "kallellaan vasemmalle",
    "MEOS_EVENT_IS_TILT_DIRECTION_1": "kallellaan oikealle",
    "MEOS_EVENT_IS_TILT_DIRECTION_2": "korvat ylös",
    "MEOS_EVENT_IS_TILT_DIRECTION_3": "korvat alas",
    "meos_event_is_tilt": "[ICON] Codey[DIRECTION] Kallistuu?",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_0": "kuvapuoli ylöspäin",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_1": "kuvapuoli alaspäin",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_2": "seiso pöydällä",
    "meos_event_is_orientate_to": "[ICON] Codey sijoitettava niin[ORIENTATE]?",
    "meos_detect_gyro_roll_angle": "[ICON] kallistuskulma°",
    "meos_detect_gyro_pitch_angle": "[ICON] korkeuskulma°",
    "meos_detect_rotatex_angle": "[ICON] kiertokulma ympäri x",
    "meos_detect_rotatey_angle": "[ICON] kiertokulma ympäri y",
    "meos_detect_rotatez_angle": "[ICON] kiertokulma ympäri z",
    "MEOS_RESET_ANGLE_AXIS_0": "x-akseli",
    "MEOS_RESET_ANGLE_AXIS_1": "y-akseli",
    "MEOS_RESET_ANGLE_AXIS_2": "z-akseli",
    "MEOS_RESET_ANGLE_AXIS_3": "kaikki akselit",
    "meos_reset_angle": "[ICON] Nollaa [AXIS] kiertokulma°",
    "meos_detect_time": "[ICON] ajastin",
    "meos_show_reset_time": "[ICON] Nollaa ajastin",
    "meos_rocky_event_obstacles_ahead": "[ICON] esteitä edessä?",
    "MEOS_EVENT_IS_COLOR_COLOR_0": "punainen",
    "MEOS_EVENT_IS_COLOR_COLOR_1": "vihreä",
    "MEOS_EVENT_IS_COLOR_COLOR_2": "sininen",
    "MEOS_EVENT_IS_COLOR_COLOR_3": "keltainen",
    "MEOS_EVENT_IS_COLOR_COLOR_4": "turkoosi",
    "MEOS_EVENT_IS_COLOR_COLOR_5": "violetti",
    "MEOS_EVENT_IS_COLOR_COLOR_6": "musta",
    "MEOS_EVENT_IS_COLOR_COLOR_7": "valkoinen",
    "meos_event_is_color": "[ICON] havaittu väri on [COLOR]?",
    "meos_rocky_detect_rgb": "[ICON] [RGB]väriarvo havaittu",
    "meos_rocky_detect_lightness": "[ICON] värianturin ympäristön valon voimakkuus",
    "meos_rocky_detect_reflection": "[ICON] väri sensoriin heijastunut valon voimakkuus",
    "meos_rocky_detect_ir_reflection": "[ICON] värisensoriin heijastunut infrapunavalon voimakkuus",
    "meos_rocky_detect_grey": "[ICON] värianturin harmaasävyn arvo",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_0": "x-akseli ",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_1": "y-akseli",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_2": "z-akseli",
    "meos_detect_rotate_angle": "[ICON] kiertokulma noin[AXIS]",
    "MEOS_DETECT_GYRO_ANGLE_AXIS_0": "kieritys",
    "MEOS_DETECT_GYRO_ANGLE_AXIS_1": "taajuus",
    "meos_detect_gyro_angle": "[ICON] [AXIS] kulma(°)",
    "CATEGORY_SENSOR": "Tuntoaisti",
    "meos_comm_send_ir": "[ICON] lähetä IR viesti [STRING]",
    "meos_comm_receive_ir": "[ICON] IR viesti vastaanotettu",
    "meos_comm_learn_with_time": "[ICON] tallentaa kodinlaitteiden kauko-ohjainta 3 sekuntia",
    "meos_comm_send_learn_result": "[ICON] lähettää kodin laitteiden kaukosignaalin  ",
    "CATEGORY_COMM": "Infrapuna",
    "meos_when_board_launch": "kun Codey käynnistyy",
    "meos_when_button_press": "kun painiketta painetaan [BUTTONS]",
    "meos_when_board_shake": "kun Codey väräjää",
    "meos_when_board_tilt": "kun Codey on [DIRECTION]Kallellaan",
    "MEOS_WHEN_VOLUME_OVER_MENU_LIST_0": "äänentaso",
    "MEOS_WHEN_VOLUME_OVER_MENU_LIST_1": "ajastin",
    "meos_when_volume_over": "kun [MENU_LIST] > [SOUNDVOLUME]",
    "meos_when_brightness_less": "kun valon herkkyys < [BRIGHTNESS]",
    "firmwares_version_470858d0": "Firmware yhteensopiva Makeblock App",
    "status_device_state": "Laitteen Tila",
    "status_firmware_versions": "Laiteohjelmistoversio:",
    "status_mac_address": "MAC-osoite:",
    "status_page_close": "Sulje"
};