export default {
    "codey": "Codey",
    "extensionName": "Codey",
    "extensionDescription": "ništa",
    "firmwares_version_0": "Najnoviji firmware",
    "UPDATE_FIRMWARE": "Ažuriranje firmvera",
    "settings_0": "Kalibrirajte senzor boje",
    "settings_1": "Kalibracija žiroskopa",
    "settings_54fdf115": "Status Check",
    "connect_fail_dc0edd70": "Provjerite je li USB kabel ispravno spojen na uređaj.",
    "connect_fail_ac025070": "Provjerite je li uređaj priključen.",
    "connect_fail_3a075878": "U ovoj verziji može se istovremeno povezati samo jedan uređaj. Povezivanje ovog uređaja dovesti će do odspajanja prijašnjeg.",
    "connect_fail_12b07c7c": "Bluetooth direct connection only available on Mac computers",
    "connect_fail_ccd91361": "Provjerite je li uređaj priključen.",
    "connect_fail_1e4caec6": "U ovoj verziji može se povezati samo jedan uređaj. Povezivanje ovog uređaja će dovesti do depovezivanja prethodnog.",
    "upload_fail_d5fa5444": "Provjerite je li uređaj ispravno spojen. Možete ponovno pokrenuti uređaj i ponovno ga povezati.",
    "upload_fail_ae3a4ed5": "Molimo provjerite je li firmware dobro radi. Možete ažurirati firmware ili vratiti na tvorničke postavke, a zatim pokušajte ponovno.",
    "upload_fail_d36df56a": "Molimo provjerite firmver uređaja da biste vidjeli radi li dobro. Ako ne, pokušajte ponovno nakon ažuriranja firmvera.",
    "firmware_success_c205609a": "Za bolje iskustvo, molimo ponovno pokrenite uređaj i ponovno ga spojite.",
    "firmware_fail_34b7a344": "Provjerite je li uređaj ispravno spojen. Ponovno pokrenite uređaj, ponovno ga povežite, a zatim ponovno pokušajte ažurirati firmver.",
    "firmware_fail_340c3de8": "Ovaj uređaj ne podržava ažuriranja firmwarea putem Bluetooth prilagodnika ili drugih načina.",
    "codey_emotion_look_up": "pogledaj gore",
    "codey_emotion_look_down": "pogledaj dolje",
    "codey_emotion_look_left": "pogledaj lijevo",
    "codey_emotion_look_right": "pogledaj desno",
    "codey_emotion_look_around": "pogledaj uokolo",
    "codey_emotion_wink": "trptanje",
    "codey_emotion_smile": "osmijeh",
    "codey_emotion_yeah": "da",
    "codey_emotion_naughty": "zločest",
    "codey_emotion_proud": "Ponosan",
    "codey_emotion_coquetry": "ukusan",
    "codey_emotion_awkward": "uh_oh",
    "codey_emotion_exclaim": "wow",
    "codey_emotion_aggrieved": "povrijediti",
    "codey_emotion_sad": "tužan",
    "codey_emotion_angry": "ljutit",
    "codey_emotion_greeting": "bok",
    "codey_emotion_sprint": "sprint",
    "codey_emotion_startle": "Uplašen",
    "codey_emotion_shiver": "Drhtaj",
    "codey_emotion_dizzy": "Dizzy",
    "codey_emotion_sleepy": "Zijevati",
    "codey_emotion_sleeping": "Spavati",
    "codey_emotion_revive": "buđenje",
    "codey_emotion_agree": "da",
    "codey_emotion_deny": "ne",
    "CATEGORY_EMOTION": "Emocija",
    "meos_show_led_matrix_face_with_time": "[ICON] prikaži sliku [PANEL] za [TIME] sek",
    "meos_show_led_matrix_face": "[ICON] prikaži sliku [PANEL]",
    "meos_show_led_matrix_face_position": "[ICON] prikaži sliku [PANEL] na x: [AXIS-X] y: [AXIS-Y]",
    "meos_show_led_matrix_turn_off": "[ICON] isključi zaslon",
    "meos_show_led_matrix": "[ICON] prikaži [STRING]",
    "meos_show_led_matrix_string": "[ICON] prikaži [STRING] do kraja klizača",
    "meos_show_led_matrix_string_position": "[ICON] prikaži [STRING] at x: [X] y: [Y]",
    "meos_show_led_matrix_position": "[ICON] osvijetli x: [X] y: [Y]",
    "meos_light_off_led_matrix_position": "[ICON] svjetla off x: [X] y: [Y]",
    "meos_toggle_led_matrix_position": "[ICON] prebaci se između upaljenog i ugašenog svjetla x: [X] y: [Y]",
    "meos_event_led_matrix_position_is_light": "[ICON] x: [X] y: [Y] da li je upaljeno?",
    "CATEGORY_SHOW": "Izgled",
    "meos_show_led_with_time": "[ICON] RGB LED svjetla upaljena [COLOR] na [TIME] sek",
    "meos_show_led": "[ICON] RGB LED svjetla upaljena [COLOR]",
    "MEOS_SHOW_LED_RGB_RGB_0": "crvena",
    "MEOS_SHOW_LED_RGB_RGB_1": "zelena",
    "MEOS_SHOW_LED_RGB_RGB_2": "plava",
    "meos_show_led_rgb": "[ICON] postavi indikator [RGB] sa vrijednošću boje [VALUE]",
    "meos_turn_off_led": "[ICON] RGB LED svjetla off",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_0": "crvena",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_1": "zelena",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_2": "plava",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_3": "žuta",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_4": "cijan",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_5": "ljubičasta",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_6": "bijelo",
    "meos_rocky_show_led_color": "[ICON] postavite svjetla na Rocky-u sa bojom [COLORLIST]",
    "meos_rocky_turn_off_led_color": "[ICON] Svjetla na Rocky-u ugašena",
    "CATEGORY_LIGHT": "Osvjetljenje",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_0": "bok",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_1": "bok",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_2": "doviđenja",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_3": "da",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_4": "wow",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_5": "smijeh",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_6": "hum",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_7": "tužan",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_8": "uzdah",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_9": "iznerviran",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_10": "ljutit",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_11": "iznenađen",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_12": "ukusan",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_13": "znatiželjan",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_14": "neugodno",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_15": "spreman",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_16": "sprint",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_17": "pospan",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_18": "mijau",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_19": "početak",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_20": "prekidač",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_21": "zvučni signal",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_22": "zujanje",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_23": "ispuh",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_24": "eksplozija",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_25": "imam te",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_26": "povrijediti",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_27": "skočiti",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_28": "laser",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_29": "nivo-gore",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_30": "niska energija",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_31": "metal-clash",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_32": "brz-ton",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_33": "desno",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_34": "pogrešno",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_35": "zvono",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_36": "rezultat",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_37": "pucaj",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_38": "korak_1",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_39": "korak_2",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_40": "buđenje",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_41": "upozorenje",
    "meos_show_play_sound": "[ICON] pusti zvuk [SOUNDLIST]",
    "meos_show_play_sound_wait": "[ICON] sviraj cijeli zvuk [SOUNDLIST] do kraja",
    "meos_show_stop_allsound": "[ICON] prekini sve zvukove",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_0": "C2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_1": "D2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_2": "E2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_3": "F2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_4": "G2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_5": "A2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_6": "B2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_7": "C3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_8": "D3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_9": "E3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_10": "F3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_11": "G3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_12": "A3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_13": "B3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_14": "C4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_15": "D4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_16": "E4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_17": "F4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_18": "G4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_19": "A4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_20": "B4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_21": "C5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_22": "D5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_23": "E5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_24": "F5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_25": "G5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_26": "A5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_27": "B5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_28": "C6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_29": "D6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_30": "E6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_31": "F6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_32": "G6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_33": "A6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_34": "B6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_35": "C7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_36": "D7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_37": "E7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_38": "F7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_39": "G7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_40": "A7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_41": "B7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_42": "C8",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_43": "D8",
    "meos_show_play_note_with_string": "[ICON] sviraj notu [SOUNDNOTE] u trajanju [SOUNDBEAT] takta",
    "meos_show_pause_note": "[ICON] miruj za [TIME] taktova",
    "meos_show_play_hz": "[ICON] reproduciraj zvuk na frekvenciji od [HZ] Hz za [TIME] sek",
    "meos_show_change_volume": "[ICON] promijeni jačinu zvuka na [VOLUME]",
    "meos_show_set_volume": "[ICON] postavi glasnoću na [VOLUME] %",
    "meos_detect_sound_volume": "[ICON] glasnoća",
    "CATEGORY_PLAY": "Zvučnik",
    "meos_move_forward_with_time": "[ICON] kreći se naprijed snagom [POWER] % [TIME] sekundi",
    "meos_move_backward_with_time": "[ICON] kreći se unatrag snagom [POWER] % [TIME] sekundi",
    "meos_move_left_with_time": "[ICON] skreni lijevo snagom [POWER] % [TIME] sekundi",
    "meos_move_right_with_time": "[ICON] skreni desno snagom [POWER] % [TIME] sekundi",
    "meos_rocky_keep_absolute_forward": "[ICON]idi ravno naprijed snagom [POWER]% za [TIME]secs",
    "meos_rocky_keep_absolute_backward": "[ICON]idi ravno nazad snagom [POWER]% za [TIME]secs",
    "meos_move_left_with_angle": "[image_4] okreni se lijevo[ICON][ANGLE] stupnjeva dok ne bude gotovo",
    "meos_move_right_with_angle": "[image_5] okreni se desno[ICON][ANGLE] stupnjeva dok ne bude gotovo",
    "MEOS_MOVE_DIRECTION_0": "idi naprijed",
    "MEOS_MOVE_DIRECTION_1": "idi natrag",
    "MEOS_MOVE_DIRECTION_2": "zakreni lijevo",
    "MEOS_MOVE_DIRECTION_3": "zakreni desno",
    "meos_move": "[ICON] [DIRECTION] snagom [POWER] %",
    "meos_move_with_motors": "[ICON] lijevi kotač na [LEFT_POWER] % snage, desni kotač na [RIGHT_POWER] % snage",
    "meos_move_stop": "[ICON] zaustavi kretanje",
    "MEOS_ROCKY_KEEP_ABSOLUTE_RUN_DIRECTION_0": "idi naprijed",
    "MEOS_ROCKY_KEEP_ABSOLUTE_RUN_DIRECTION_1": "idi natrag",
    "meos_rocky_keep_absolute_run": "[ICON] idi ravno prema [DIRECTION] snagom [POWER]% za [TIME]secs",
    "CATEGORY_ACTION": "Radnja",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_0": "A",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_1": "B",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_2": "C",
    "meos_event_button_pressed": "[ICON] dugme [BUTTONS] je pritisnuto?",
    "meos_event_connect_rocky": "[ICON] kada je Codey povezan sa Rocky",
    "meos_detect_potentiometer": "[ICON] vrijednost potenciometra na navijanje",
    "meos_detect_volume": "[ICON] glasnoća",
    "meos_detect_lightness": "[ICON] intenzitet ambijentalnog svjetla",
    "meos_dump_energy": "[ICON] razina baterije",
    "meos_event_is_shaked": "[ICON] drmanje?",
    "meos_detect_shaked_strength": "[ICON] snaga potresa",
    "MEOS_EVENT_IS_TILT_DIRECTION_0": "nagnut prema lijevo",
    "MEOS_EVENT_IS_TILT_DIRECTION_1": "nagnut prema desno",
    "MEOS_EVENT_IS_TILT_DIRECTION_2": "uši gore",
    "MEOS_EVENT_IS_TILT_DIRECTION_3": "uši dolje",
    "meos_event_is_tilt": "[ICON] Codey[DIRECTION] nagnut?",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_0": "licem prema gore",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_1": "licem prema dolje",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_2": "stani na stol",
    "meos_event_is_orientate_to": "[ICON] Codey pozicioniran kao[ORIENTATE]?",
    "meos_detect_gyro_roll_angle": "[ICON] kut kotrljanja°",
    "meos_detect_gyro_pitch_angle": "[ICON] kut nagiba°",
    "meos_detect_rotatex_angle": "[ICON] kut rotacije oko x",
    "meos_detect_rotatey_angle": "[ICON] kut rotacije oko y",
    "meos_detect_rotatez_angle": "[ICON] kut rotacije oko z",
    "MEOS_RESET_ANGLE_AXIS_0": "x-os",
    "MEOS_RESET_ANGLE_AXIS_1": "y-os",
    "MEOS_RESET_ANGLE_AXIS_2": "z-os",
    "MEOS_RESET_ANGLE_AXIS_3": "sve osi",
    "meos_reset_angle": "[ICON] resetiraj [AXIS] rotaciju kut°",
    "meos_detect_time": "[ICON] vrijeme",
    "meos_show_reset_time": "[ICON] resetiraj vrijeme",
    "meos_rocky_event_obstacles_ahead": "[ICON] zapreke na putu?",
    "MEOS_EVENT_IS_COLOR_COLOR_0": "crvena",
    "MEOS_EVENT_IS_COLOR_COLOR_1": "zelena",
    "MEOS_EVENT_IS_COLOR_COLOR_2": "plava",
    "MEOS_EVENT_IS_COLOR_COLOR_3": "žuta",
    "MEOS_EVENT_IS_COLOR_COLOR_4": "svijetlo Plava",
    "MEOS_EVENT_IS_COLOR_COLOR_5": "ljubičasta",
    "MEOS_EVENT_IS_COLOR_COLOR_6": "crna",
    "MEOS_EVENT_IS_COLOR_COLOR_7": "bijela",
    "meos_event_is_color": "[ICON] prepoznata boja je [COLOR]?",
    "meos_rocky_detect_rgb": "[ICON][RGB] detektirana vrijednost boje",
    "meos_rocky_detect_lightness": "[ICON] intenzitet sobnog svijetla na senzoru boje",
    "meos_rocky_detect_reflection": "[ICON] senzor boje reflektiran intenzitetom svijetla",
    "meos_rocky_detect_ir_reflection": "[ICON] intenzitet infracrvenog svijetla na senzoru boje",
    "meos_rocky_detect_grey": "[ICON] vrijednost sive boje senzora boje",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_0": "x-os ",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_1": "y-os",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_2": "z-os",
    "meos_detect_rotate_angle": "[ICON] kut rotacije oko [AXIS]",
    "MEOS_DETECT_GYRO_ANGLE_AXIS_0": "kut kotrljanja",
    "MEOS_DETECT_GYRO_ANGLE_AXIS_1": "kut nagiba",
    "meos_detect_gyro_angle": "[ICON] [AXIS] kut(°)",
    "CATEGORY_SENSOR": "Senzori",
    "meos_comm_send_ir": "[ICON] pošalji IC poruku [STRING]",
    "meos_comm_receive_ir": "[ICON] IC poruka primljena",
    "meos_comm_learn_with_time": "[ICON] snimi signal daljinskog upravljača kućanskih aparata u 3 sekunde",
    "meos_comm_send_learn_result": "[ICON] pošalji signal upravljača kućanskih aparata  ",
    "CATEGORY_COMM": "Infracrveno",
    "meos_when_board_launch": "kada se Codey upali",
    "meos_when_button_press": "kada se dugme [BUTTONS] pritisne",
    "meos_when_board_shake": "kada Codey protrese",
    "meos_when_board_tilt": "kada je Codey [DIRECTION] nagnut",
    "MEOS_WHEN_VOLUME_OVER_MENU_LIST_0": "glasnoča",
    "MEOS_WHEN_VOLUME_OVER_MENU_LIST_1": "tajmer",
    "meos_when_volume_over": "kada [MENU_LIST] > [SOUNDVOLUME]",
    "meos_when_brightness_less": "kada intenzitet svjetla < [BRIGHTNESS]",
    "firmwares_version_470858d0": "Firmware kompatibilan sa Makeblock app",
    "status_device_state": "Device Status",
    "status_firmware_versions": "Verzija firmwarea:",
    "status_mac_address": "MAC Address:",
    "status_page_close": "Zatvori"
};