export default {
    "codey": "Codey",
    "extensionName": "Codey",
    "extensionDescription": "żaden",
    "firmwares_version_0": "Najnowszy firmware",
    "UPDATE_FIRMWARE": "Aktualizacja Firmware",
    "settings_0": "Kalibracja czujnika koloru",
    "settings_1": "Skalibruj żyroskop",
    "settings_54fdf115": "Sprawdzanie statusu",
    "connect_fail_dc0edd70": "Upewnij się, że przewód USB jest prawidłowo podłączony do urządzenia.",
    "connect_fail_ac025070": "Upewnij się, że urządzenie, które ma być podłączone, jest włączone.",
    "connect_fail_3a075878": "W tej wersji można podłączyć tylko jedno urządzenie naraz. Tak więc podłączenie tego urządzenia doprowadzi do odłączenia poprzedniego.",
    "connect_fail_12b07c7c": "Bluetooth direct connection only available on Mac computers",
    "connect_fail_ccd91361": "Upewnij się, że urządzenie, które ma być podłączone, jest włączone.",
    "connect_fail_1e4caec6": "W tej wersji można podłączyć tylko jedno urządzenie naraz. Tak więc podłączenie tego urządzenia doprowadzi do odłączenia poprzedniego.",
    "upload_fail_d5fa5444": "Upewnij się, że urządzenie jest prawidłowo podłączone. Możesz ponownie uruchomić urządzenie i podłączyć je ponownie.",
    "upload_fail_ae3a4ed5": "Upewnij się, że firmware działa dobrze. Możesz zaktualizować firmware lub przywrócić ustawienia fabryczne i spróbować ponownie.",
    "upload_fail_d36df56a": "Proszę sprawdzić firmware urządzenia, aby sprawdzić, czy działa dobrze. Jeśli nie, spróbuj ponownie po zaktualizowaniu oprogramowania układowego.",
    "firmware_success_c205609a": "Aby uzyskać lepsze wrażenia, należy ponownie uruchomić urządzenie i podłączyć je ponownie.",
    "firmware_fail_34b7a344": "Upewnij się, że urządzenie jest prawidłowo podłączone. Ponownie uruchom urządzenie, podłącz je ponownie, a następnie spróbuj ponownie zaktualizować oprogramowanie układowe.",
    "firmware_fail_340c3de8": "To urządzenie nie obsługuje aktualizacji oprogramowania układowego za pośrednictwem adaptera Bluetooth lub innych sposobów.",
    "codey_emotion_look_up": "spójrz w górę",
    "codey_emotion_look_down": "Spójrz w dół",
    "codey_emotion_look_left": "spójrz w lewo",
    "codey_emotion_look_right": "Spójrz w prawo",
    "codey_emotion_look_around": "Rozejrzyj się dookoła",
    "codey_emotion_wink": "migaj",
    "codey_emotion_smile": "uśmiech",
    "codey_emotion_yeah": "yeah",
    "codey_emotion_naughty": "niegrzeczny",
    "codey_emotion_proud": "dumny",
    "codey_emotion_coquetry": "przepyszny",
    "codey_emotion_awkward": "uh_oh",
    "codey_emotion_exclaim": "wow",
    "codey_emotion_aggrieved": "boli",
    "codey_emotion_sad": "smutny",
    "codey_emotion_angry": "rozgniewany",
    "codey_emotion_greeting": "witaj",
    "codey_emotion_sprint": "sprint",
    "codey_emotion_startle": "Przestraszony",
    "codey_emotion_shiver": "dreszczyk",
    "codey_emotion_dizzy": "oszołomiony",
    "codey_emotion_sleepy": "Ziewać",
    "codey_emotion_sleeping": "Snu",
    "codey_emotion_revive": "obudzić",
    "codey_emotion_agree": "tak",
    "codey_emotion_deny": "nie",
    "CATEGORY_EMOTION": "Emocje",
    "meos_show_led_matrix_face_with_time": "[ICON]pokaż obraz [PANEL] przez [TIME] sekund",
    "meos_show_led_matrix_face": "[ICON]pokaż obraz [PANEL]",
    "meos_show_led_matrix_face_position": "[ICON] Pokaż obraz [PANEL] w x: [AXIS-X] Y: [AXIS-Y]",
    "meos_show_led_matrix_turn_off": "[ICON] Wyłącz ekran",
    "meos_show_led_matrix": "[ICON] pokaż[STRING] i czekaj",
    "meos_show_led_matrix_string": "[ICON] pokaż [STRING]",
    "meos_show_led_matrix_string_position": "[ICON] Pokaż [STRING] w x: [X] Y: [Y]",
    "meos_show_led_matrix_position": "[ICON]zapal x: [X] y: [Y]",
    "meos_light_off_led_matrix_position": "[ICON]zgaś x: [X] y: [Y]",
    "meos_toggle_led_matrix_position": "[ICON]przełączaj pomiędzy zapalaniem i gaszeniem x: [X] y: [Y]",
    "meos_event_led_matrix_position_is_light": "[ICON]x: [X] y: [Y] jest zapalone?",
    "CATEGORY_SHOW": "Wygląd",
    "meos_show_led_with_time": "[ICON] RGB LED świeci [COLOR] przez [TIME] sekund",
    "meos_show_led": "[ICON] dioda RGB świeci [COLOR]",
    "MEOS_SHOW_LED_RGB_RGB_0": "czerwony",
    "MEOS_SHOW_LED_RGB_RGB_1": "zielony",
    "MEOS_SHOW_LED_RGB_RGB_2": "niebieski",
    "meos_show_led_rgb": "[ICON] ustaw wskaźnik [RGB]z wartością koloru [VALUE]",
    "meos_turn_off_led": "[ICON] RGB LED światła wyłączone",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_0": "czerwony",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_1": "zielony",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_2": "niebieski",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_3": "żółty",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_4": "błękitny",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_5": "fioletowy",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_6": "biały",
    "meos_rocky_show_led_color": "[ICON] ustaw światło Rocky w kolorze [COLORLIST]",
    "meos_rocky_turn_off_led_color": "[ICON] Rocky światła wyłączone",
    "CATEGORY_LIGHT": "Błyskawica",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_0": "witaj",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_1": "cześć",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_2": "żegnaj",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_3": "jej",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_4": "wow",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_5": "śmiech",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_6": "nucenie",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_7": "smutny",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_8": "westchnienie",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_9": "zirytowany",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_10": "rozgniewany",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_11": "zaskoczony",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_12": "przepyszny",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_13": "ciekawy",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_14": "zakłopotany",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_15": "gotowy",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_16": "sprint",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_17": "senny",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_18": "miauczenie",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_19": "start",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_20": "przełącznik",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_21": "brzęczy",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_22": "brzęczenie",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_23": "wyczerpany",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_24": "eksplozja",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_25": "mam Cię",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_26": "boli",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_27": "skok",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_28": "laser",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_29": "poziom w górę",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_30": "słaba bateria",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_31": "brzdęk metalu",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_32": "przypomnienie",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_33": "prawo",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_34": "błędny",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_35": "dzwonek",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_36": "wynik",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_37": "strzał",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_38": "krok_1",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_39": "krok_2",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_40": "wybudzanie",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_41": "ostrzeżenie",
    "meos_show_play_sound": "[ICON]odtwórz dźwięk [SOUNDLIST]",
    "meos_show_play_sound_wait": "[ICON]odtwórz dźwięk [SOUNDLIST] i czekaj do wykonania",
    "meos_show_stop_allsound": "[ICON]zatrzymaj wszystkie dźwięki",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_0": "C2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_1": "D2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_2": "E2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_3": "F2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_4": "G2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_5": "A2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_6": "B2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_7": "C3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_8": "D3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_9": "E3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_10": "F3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_11": "G3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_12": "A3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_13": "B3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_14": "C4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_15": "D4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_16": "E4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_17": "F4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_18": "G4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_19": "A4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_20": "B4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_21": "C5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_22": "D5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_23": "E5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_24": "F5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_25": "G5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_26": "A5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_27": "B5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_28": "C6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_29": "D6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_30": "E6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_31": "F6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_32": "G6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_33": "A6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_34": "B6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_35": "C7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_36": "D7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_37": "E7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_38": "F7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_39": "G7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_40": "A7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_41": "B7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_42": "C8",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_43": "D8",
    "meos_show_play_note_with_string": "[ICON]zagraj nutę[SOUNDNOTE] przez [SOUNDBEAT] taktów",
    "meos_show_pause_note": "[ICON]pauzuj przez [TIME] taktów",
    "meos_show_play_hz": "[ICON]zagraj dźwięk o częstotliwości [HZ] herców przez [TIME] sekund",
    "meos_show_change_volume": "[ICON]zmień głośność o [VOLUME]",
    "meos_show_set_volume": "[ICON]ustaw głośność na [VOLUME] %",
    "meos_detect_sound_volume": "[ICON]głośność",
    "CATEGORY_PLAY": "Głośnik",
    "meos_move_forward_with_time": "[ICON]poruszaj się do przodu z mocą [POWER] % przez [TIME] sekund",
    "meos_move_backward_with_time": "[ICON]przesuń do tyłu z mocą [POWER]% przez [TIME] sekund",
    "meos_move_left_with_time": "[ICON]skręć w lewo z mocą [POWER] % przez [TIME] sekund",
    "meos_move_right_with_time": "[ICON]skręć w prawo z mocą [POWER] % przez [TIME] sekund",
    "meos_rocky_keep_absolute_forward": "[ICON] jedź prosto do przodu z mocą [POWER]% przez [TIME]sekund",
    "meos_rocky_keep_absolute_backward": "[ICON] jedź prosto do tyłu z mocą [POWER]% przez [TIME]sekund",
    "meos_move_left_with_angle": "[image_4] skręć w lewo [ICON][ANGLE] stopni i czekaj",
    "meos_move_right_with_angle": "[image_5] skręć w prawo [ICON][ANGLE] stopni i czekaj",
    "MEOS_MOVE_DIRECTION_0": "poruszaj się do przodu",
    "MEOS_MOVE_DIRECTION_1": "poruszaj się do tyłu",
    "MEOS_MOVE_DIRECTION_2": "skręcaj w lewo",
    "MEOS_MOVE_DIRECTION_3": "skręcaj w prawo",
    "meos_move": "[ICON][DIRECTION] z mocą [POWER] %",
    "meos_move_with_motors": "[ICON]lewe koło z mocą [LEFT_POWER] % i prawe koło z mocą [RIGHT_POWER] %",
    "meos_move_stop": "[ICON]zatrzymaj ruch",
    "MEOS_ROCKY_KEEP_ABSOLUTE_RUN_DIRECTION_0": "poruszaj się do przodu",
    "MEOS_ROCKY_KEEP_ABSOLUTE_RUN_DIRECTION_1": "poruszaj się do tyłu",
    "meos_rocky_keep_absolute_run": "[ICON] jedź prosto w kierunku [DIRECTION] z mocą[POWER]% przez [TIME]sekund",
    "CATEGORY_ACTION": "Akcja",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_0": "A",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_1": "B",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_2": "C",
    "meos_event_button_pressed": "[ICON] przycisk [BUTTONS] jest wciśnięty?",
    "meos_event_connect_rocky": "[ICON] kiedy Codey połączony z Rocky",
    "meos_detect_potentiometer": "[ICON] wartość potencjometru",
    "meos_detect_volume": "[ICON] głośność",
    "meos_detect_lightness": "[ICON] intensywność otaczającego światła",
    "meos_dump_energy": "[ICON] poziom naładowania baterii",
    "meos_event_is_shaked": "[ICON] potrząśnięty?",
    "meos_detect_shaked_strength": "[ICON] siła potrząsania",
    "MEOS_EVENT_IS_TILT_DIRECTION_0": "odchylony w lewo",
    "MEOS_EVENT_IS_TILT_DIRECTION_1": "odchylony w prawo",
    "MEOS_EVENT_IS_TILT_DIRECTION_2": "uszy w górę",
    "MEOS_EVENT_IS_TILT_DIRECTION_3": "uszy w dół",
    "meos_event_is_tilt": "[ICON] Codey[DIRECTION] przechylony?",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_0": "twarzą do góry",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_1": "twarzą do ziemi",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_2": "stój na biurku",
    "meos_event_is_orientate_to": "[ICON] Codey ustawiony jako [ORIENTATE]?",
    "meos_detect_gyro_roll_angle": "[ICON] kąt obrotu",
    "meos_detect_gyro_pitch_angle": "[ICON] kąt nachylenia",
    "meos_detect_rotatex_angle": "[ICON] kąt obrotu dookoła x",
    "meos_detect_rotatey_angle": "[ICON] kąt obrotu dookoła y",
    "meos_detect_rotatez_angle": "[ICON] kąt obrotu dookoła z",
    "MEOS_RESET_ANGLE_AXIS_0": "oś x",
    "MEOS_RESET_ANGLE_AXIS_1": "oś y",
    "MEOS_RESET_ANGLE_AXIS_2": "oś z",
    "MEOS_RESET_ANGLE_AXIS_3": "wszystkie osie",
    "meos_reset_angle": "[ICON] zresetować [AXIS] kąt obrotu °",
    "meos_detect_time": "[ICON] Timer",
    "meos_show_reset_time": "[ICON] zeruj timer",
    "meos_rocky_event_obstacles_ahead": "[ICON] przeszkody z przodu?",
    "MEOS_EVENT_IS_COLOR_COLOR_0": "czerwony",
    "MEOS_EVENT_IS_COLOR_COLOR_1": "zielony",
    "MEOS_EVENT_IS_COLOR_COLOR_2": "niebieski",
    "MEOS_EVENT_IS_COLOR_COLOR_3": "żółty",
    "MEOS_EVENT_IS_COLOR_COLOR_4": "turkusowy",
    "MEOS_EVENT_IS_COLOR_COLOR_5": "fioletowy",
    "MEOS_EVENT_IS_COLOR_COLOR_6": "czarny",
    "MEOS_EVENT_IS_COLOR_COLOR_7": "biały",
    "meos_event_is_color": "[ICON] wykryty kolor to [COLOR]?",
    "meos_rocky_detect_rgb": "[ICON] [RGB]wykryta wartość koloru",
    "meos_rocky_detect_lightness": "[ICON] intensywność światła otoczenia sensora kolorów",
    "meos_rocky_detect_reflection": "[ICON] intensywność światła odbitego sensora kolorów",
    "meos_rocky_detect_ir_reflection": "[ICON] intensywność światła odbitego podczerwieni sensora kolorów",
    "meos_rocky_detect_grey": "[ICON] wartość skali szarości sensora kolorów",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_0": "oś x ",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_1": "oś y",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_2": "oś z",
    "meos_detect_rotate_angle": "[ICON] kąt obrotu wokół [AXIS]",
    "MEOS_DETECT_GYRO_ANGLE_AXIS_0": "obracaj",
    "MEOS_DETECT_GYRO_ANGLE_AXIS_1": "ton",
    "meos_detect_gyro_angle": "[ICON] [AXIS] kąt (°)",
    "CATEGORY_SENSOR": "Czujniki",
    "meos_comm_send_ir": "[ICON]wyślij wiadomość przez podczerwień [STRING]",
    "meos_comm_receive_ir": "[ICON]Odebrana wiadomość przez podczerwień",
    "meos_comm_learn_with_time": "[ICON] nagraj sygnał sprzętów domowych 3 sekundy",
    "meos_comm_send_learn_result": "[ICON] wyślij sygnał sprzętów domowych  ",
    "CATEGORY_COMM": "Podczerwień",
    "meos_when_board_launch": "kiedy Codey uruchomi się",
    "meos_when_button_press": "kiedy przycisk [BUTTONS] jest wciśnięty",
    "meos_when_board_shake": "kiedy Codey jest potrząsany",
    "meos_when_board_tilt": "kiedy Codey jest [DIRECTION]przechylony",
    "MEOS_WHEN_VOLUME_OVER_MENU_LIST_0": "głośność",
    "MEOS_WHEN_VOLUME_OVER_MENU_LIST_1": "timer",
    "meos_when_volume_over": "kiedy [MENU_LIST] > [SOUNDVOLUME]",
    "meos_when_brightness_less": "kiedy intensywność światła < [BRIGHTNESS]",
    "firmwares_version_470858d0": "Firmware kompatybilny z aplikacją Makeblock",
    "status_device_state": "Status urządzenia",
    "status_firmware_versions": "Wersja oprogramowania:",
    "status_mac_address": "Adres MAC:",
    "status_page_close": "Zamknij"
};