export default {
    "codey": "Codey",
    "extensionName": "Codey",
    "extensionDescription": "нет",
    "firmwares_version_0": "Последняя версия прошивки",
    "UPDATE_FIRMWARE": "Обновить встроенные программы",
    "settings_0": "Калибровка датчика цвета",
    "settings_1": "Калибровка гироскопа",
    "settings_54fdf115": "Status Check",
    "connect_fail_dc0edd70": "Убедитесь, что кабель USB правильно подключен к устройству.",
    "connect_fail_ac025070": "Убедитесь, что подключенное устройство включено.",
    "connect_fail_3a075878": "Только одно устройство может быть подключено одновременно в этой версии. Таким образом, подключение этого устройства приведет к разъединению предыдущего.",
    "connect_fail_12b07c7c": "Bluetooth direct connection only available on Mac computers",
    "connect_fail_ccd91361": "Убедитесь, что подключенное устройство включено.",
    "connect_fail_1e4caec6": "Только одно устройство может быть подключено одновременно в этой версии. Таким образом, подключение этого устройства приведет к разъединению предыдущего.",
    "upload_fail_d5fa5444": "Убедитесь, что устройство подключено правильно. Вы можете перезапустить устройство и подключить его еще раз.",
    "upload_fail_ae3a4ed5": "Пожалуйста, убедитесь, что прошивка работает хорошо. Вы можете обновить микропрограмму или восстановить заводские настройки и повторить попытку.",
    "upload_fail_d36df56a": "Пожалуйста, проверьте прошивку устройства, чтобы увидеть, если он работает хорошо. Если нет, попробуйте еще раз после обновления прошивки.",
    "firmware_success_c205609a": "Для лучшего опыта, пожалуйста, перезагрузите устройство и подключите его еще раз.",
    "firmware_fail_34b7a344": "Убедитесь, что устройство подключено правильно. ПереЗагрузите устройство, подключите его снова и повторите попытку обновления микропрограммы.",
    "firmware_fail_340c3de8": "Это устройство не поддерживает обновления микропрограммы с помощью адаптера Bluetooth или другими способами.",
    "codey_emotion_look_up": "посмотреть вверх",
    "codey_emotion_look_down": "посмотреть вниз",
    "codey_emotion_look_left": "посмотреть влево",
    "codey_emotion_look_right": "посмотреть вправо",
    "codey_emotion_look_around": "оглянуться",
    "codey_emotion_wink": "мигать",
    "codey_emotion_smile": "улыбка",
    "codey_emotion_yeah": "да",
    "codey_emotion_naughty": "озорной",
    "codey_emotion_proud": "гордый",
    "codey_emotion_coquetry": "вкусно",
    "codey_emotion_awkward": "ухо",
    "codey_emotion_exclaim": "ого",
    "codey_emotion_aggrieved": "боль",
    "codey_emotion_sad": "грустный",
    "codey_emotion_angry": "злой",
    "codey_emotion_greeting": "привет",
    "codey_emotion_sprint": "бег",
    "codey_emotion_startle": "Страшно",
    "codey_emotion_shiver": "дрожь",
    "codey_emotion_dizzy": "головокружение",
    "codey_emotion_sleepy": "Зевать",
    "codey_emotion_sleeping": "Спать",
    "codey_emotion_revive": "будить",
    "codey_emotion_agree": "да",
    "codey_emotion_deny": "нет",
    "CATEGORY_EMOTION": "Эмоция",
    "meos_show_led_matrix_face_with_time": "[ICON] показывать изображение [PANEL] в течение [TIME] сек",
    "meos_show_led_matrix_face": "[ICON] показать изображение [PANEL]",
    "meos_show_led_matrix_face_position": "[ICON] показать изображение [PANEL] в x: [AXIS-X] y: [AXIS-Y]",
    "meos_show_led_matrix_turn_off": "[ICON] выключить экран",
    "meos_show_led_matrix": "[ICON] показать [STRING]",
    "meos_show_led_matrix_string": "[ICON] показать [STRING] до прокрутки сделано",
    "meos_show_led_matrix_string_position": "[ICON] показать [STRING] по координатам x:[X] y:[Y]",
    "meos_show_led_matrix_position": "[ICON] включить свет x: [X] y: [Y]",
    "meos_light_off_led_matrix_position": "[ICON] отключить свет x: [X] y: [Y]",
    "meos_toggle_led_matrix_position": "[ICON] включить и выключить свет x: [X] y: [Y]",
    "meos_event_led_matrix_position_is_light": "[ICON] x: [X] y: [Y] включены?",
    "CATEGORY_SHOW": "Внешность",
    "meos_show_led_with_time": "[ICON] RGB LED светится [COLOR] цветом [TIME] сек",
    "meos_show_led": "[ICON] RGB LED светится [COLOR]",
    "MEOS_SHOW_LED_RGB_RGB_0": "красный",
    "MEOS_SHOW_LED_RGB_RGB_1": "зелёный",
    "MEOS_SHOW_LED_RGB_RGB_2": "синий",
    "meos_show_led_rgb": "[ICON] установить индикатору [RGB] значение цвета: [VALUE]",
    "meos_turn_off_led": "[ICON] RGB LED выключен",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_0": "красный",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_1": "зелёный",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_2": "синий",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_3": "жёлтый",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_4": "голубой",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_5": "фиолетовый",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_6": "белый",
    "meos_rocky_show_led_color": "[ICON] установить цвет подсветки Rocky [COLORLIST]",
    "meos_rocky_turn_off_led_color": "[ICON] выключить подсветку Rocky",
    "CATEGORY_LIGHT": "Освещение",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_0": "привет",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_1": "привет",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_2": "пока",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_3": "да",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_4": "ого",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_5": "смех",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_6": "гул",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_7": "грустный",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_8": "вздох",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_9": "раздражённый",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_10": "злой",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_11": "удивлённый",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_12": "вкусно",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_13": "любопытный",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_14": "смущённый",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_15": "готовый",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_16": "бег",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_17": "сонный",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_18": "мяу",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_19": "начать",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_20": "переключатель",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_21": "гудки",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_22": "гудение",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_23": "уставший",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_24": "взрыв",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_25": "попался",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_26": "боль",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_27": "прыгать",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_28": "лазер",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_29": "новый уровень",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_30": "низкий заряд",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_31": "скрежет металла",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_32": "предупреждающий звук",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_33": "направо",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_34": "неверно",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_35": "звонок",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_36": "счёт",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_37": "выстрел",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_38": "шаг_1",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_39": "шаг_2",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_40": "будить",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_41": "предупреждение",
    "meos_show_play_sound": "[ICON] воспроизводить звук [SOUNDLIST]",
    "meos_show_play_sound_wait": "[ICON] воспроизводить звук [SOUNDLIST] до коцна",
    "meos_show_stop_allsound": "[ICON] остановить все звуки",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_0": "C2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_1": "D2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_2": "E2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_3": "F2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_4": "G2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_5": "A2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_6": "B2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_7": "C3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_8": "D3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_9": "E3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_10": "F3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_11": "G3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_12": "A3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_13": "B3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_14": "C4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_15": "D4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_16": "E4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_17": "F4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_18": "G4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_19": "A4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_20": "B4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_21": "C5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_22": "D5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_23": "E5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_24": "F5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_25": "G5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_26": "A5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_27": "B5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_28": "C6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_29": "D6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_30": "E6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_31": "F6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_32": "G6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_33": "A6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_34": "B6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_35": "C7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_36": "D7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_37": "E7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_38": "F7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_39": "G7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_40": "A7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_41": "B7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_42": "C8",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_43": "D8",
    "meos_show_play_note_with_string": "[ICON] играть ноту [SOUNDNOTE] длительностью [SOUNDBEAT] долей",
    "meos_show_pause_note": "[ICON] пауза [TIME] тактов",
    "meos_show_play_hz": "[ICON] воспроизводить звук частотой [HZ] Гц [TIME] сек",
    "meos_show_change_volume": "[ICON] изменить громкость на [VOLUME]",
    "meos_show_set_volume": "[ICON] установить громкость на [VOLUME] %",
    "meos_detect_sound_volume": "[ICON] громкость",
    "CATEGORY_PLAY": "Динамик",
    "meos_move_forward_with_time": "[ICON] двигаться вперёд на скорости [POWER] % в течение [TIME] секунд",
    "meos_move_backward_with_time": "[ICON] двигаться назад на скорости [POWER] % в течение [TIME] секунд",
    "meos_move_left_with_time": "[ICON] повернуть налево на скорости [POWER] % в течение [TIME] секунд",
    "meos_move_right_with_time": "[ICON] повернуть направо на скорости [POWER] % в течение [TIME] секунд",
    "meos_rocky_keep_absolute_forward": "[ICON] двигаться вперед по прямой на скорости[POWER]% [TIME]сек",
    "meos_rocky_keep_absolute_backward": "[ICON] двигаться назад по прямой на скорости[POWER]% [TIME]сек",
    "meos_move_left_with_angle": "[image_4] повернуть налево до конца на [ICON] [ANGLE] градусов",
    "meos_move_right_with_angle": "[image_5] повернуть направо до конца на [ICON] [ANGLE] градусов",
    "MEOS_MOVE_DIRECTION_0": "двигаться вперед",
    "MEOS_MOVE_DIRECTION_1": "двигаться назад",
    "MEOS_MOVE_DIRECTION_2": "повернуть налево",
    "MEOS_MOVE_DIRECTION_3": "повернуть направо",
    "meos_move": "[ICON] [DIRECTION] на скорости [POWER] %",
    "meos_move_with_motors": "[ICON] вращать левое колесо со скоростью [LEFT_POWER] %, правое колесо со скоростью [RIGHT_POWER] %",
    "meos_move_stop": "[ICON] оставновить движение",
    "MEOS_ROCKY_KEEP_ABSOLUTE_RUN_DIRECTION_0": "двигаться вперед",
    "MEOS_ROCKY_KEEP_ABSOLUTE_RUN_DIRECTION_1": "двигаться назад",
    "meos_rocky_keep_absolute_run": "[ICON] двигаться прямо в направлении[DIRECTION] на скорости[POWER]% [TIME]сек",
    "CATEGORY_ACTION": "Действие",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_0": "A",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_1": "B",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_2": "C",
    "meos_event_button_pressed": "[ICON] кнопка [BUTTONS] нажата?",
    "meos_event_connect_rocky": "[ICON] когда Codey подключен к Rocky",
    "meos_detect_potentiometer": "[ICON] значение потенциометра",
    "meos_detect_volume": "[ICON] громкость",
    "meos_detect_lightness": "[ICON] яркость окружающего света",
    "meos_dump_energy": "[ICON] заряд батареи",
    "meos_event_is_shaked": "[ICON] вибрирует?",
    "meos_detect_shaked_strength": "[ICON] сила вибрации",
    "MEOS_EVENT_IS_TILT_DIRECTION_0": "наклон влево",
    "MEOS_EVENT_IS_TILT_DIRECTION_1": "наклон вправо",
    "MEOS_EVENT_IS_TILT_DIRECTION_2": "уши вверх",
    "MEOS_EVENT_IS_TILT_DIRECTION_3": "уши вниз",
    "meos_event_is_tilt": "[ICON] Codey [DIRECTION] наклонен?",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_0": "лицом вверх",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_1": "лицом вниз",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_2": "стоять на столе",
    "meos_event_is_orientate_to": "[ICON] положение Codey как[ORIENTATE]?",
    "meos_detect_gyro_roll_angle": "[ICON] угол поворота°",
    "meos_detect_gyro_pitch_angle": "[ICON] угол наклона°",
    "meos_detect_rotatex_angle": "[ICON] угол поворота вокруг x",
    "meos_detect_rotatey_angle": "[ICON] угол поворота вокруг y",
    "meos_detect_rotatez_angle": "[ICON] угол поворота вокруг z",
    "MEOS_RESET_ANGLE_AXIS_0": "ось X",
    "MEOS_RESET_ANGLE_AXIS_1": "ось Y",
    "MEOS_RESET_ANGLE_AXIS_2": "ось Z",
    "MEOS_RESET_ANGLE_AXIS_3": "все оси",
    "meos_reset_angle": "[ICON] сбросить угол° поворота [AXIS]",
    "meos_detect_time": "[ICON] таймер",
    "meos_show_reset_time": "[ICON] сбросить таймер",
    "meos_rocky_event_obstacles_ahead": "[ICON] препятствие впереди?",
    "MEOS_EVENT_IS_COLOR_COLOR_0": "красный",
    "MEOS_EVENT_IS_COLOR_COLOR_1": "зелёный",
    "MEOS_EVENT_IS_COLOR_COLOR_2": "синий",
    "MEOS_EVENT_IS_COLOR_COLOR_3": "жёлтый",
    "MEOS_EVENT_IS_COLOR_COLOR_4": "голубой",
    "MEOS_EVENT_IS_COLOR_COLOR_5": "фиолетовый",
    "MEOS_EVENT_IS_COLOR_COLOR_6": "чёрный",
    "MEOS_EVENT_IS_COLOR_COLOR_7": "белый",
    "meos_event_is_color": "[ICON] цвет определяется как [COLOR]?",
    "meos_rocky_detect_rgb": "[ICON] обнаружен цвет [RGB]",
    "meos_rocky_detect_lightness": "[ICON] интенсивность окружающего света",
    "meos_rocky_detect_reflection": "[ICON] интенсивность отраженного света",
    "meos_rocky_detect_ir_reflection": "[ICON] интенсивность отраженного ИК-света",
    "meos_rocky_detect_grey": "[ICON] датчик цвета значение серого",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_0": "ось X ",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_1": "ось Y",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_2": "ось Z",
    "meos_detect_rotate_angle": "[ICON] угол поворота вокруг [AXIS]",
    "MEOS_DETECT_GYRO_ANGLE_AXIS_0": "крутиться",
    "MEOS_DETECT_GYRO_ANGLE_AXIS_1": "тон",
    "meos_detect_gyro_angle": "[ICON] [AXIS] угол(°)",
    "CATEGORY_SENSOR": "Сенсоры",
    "meos_comm_send_ir": "[ICON] отправить сообщение [STRING] по ИК-порту",
    "meos_comm_receive_ir": "[ICON] Получено сообщение по ИК-порту",
    "meos_comm_learn_with_time": "[ICON] записать сигнал от домашних устройств в течение 3 секунд",
    "meos_comm_send_learn_result": "[ICON] отправляет сигнал на домашние устройства  ",
    "CATEGORY_COMM": "Инфракрасный",
    "meos_when_board_launch": "при запуске Codey",
    "meos_when_button_press": "при нажатии кнопки [BUTTONS]",
    "meos_when_board_shake": "когда Codey вибрирует",
    "meos_when_board_tilt": "когда Codey [DIRECTION]наклонен",
    "MEOS_WHEN_VOLUME_OVER_MENU_LIST_0": "громкость",
    "MEOS_WHEN_VOLUME_OVER_MENU_LIST_1": "таймер",
    "meos_when_volume_over": "когда [MENU_LIST] > [SOUNDVOLUME]",
    "meos_when_brightness_less": "когда интенсивность света < [BRIGHTNESS]",
    "firmwares_version_470858d0": "Прошивка совместима с Makeblock App",
    "status_device_state": "Device Status",
    "status_firmware_versions": "Версия прошивки:",
    "status_mac_address": "MAC Address:",
    "status_page_close": "Закрыть"
};