export default {
    "codey": "Codey",
    "extensionName": "Codey",
    "extensionDescription": "沒有",
    "firmwares_version_0": "最新韌體",
    "UPDATE_FIRMWARE": "更新韌體",
    "settings_0": "校準顏色感測器",
    "settings_1": "校正陀螺儀",
    "settings_54fdf115": "狀態檢查",
    "connect_fail_dc0edd70": "請確認 USB 傳輸線已正確連接到設備。",
    "connect_fail_ac025070": "請確認設備已經連接並打開電源",
    "connect_fail_3a075878": "在此版本中, 一次只能連接一個設備。因此, 連接此設備將導致斷開前一個設備的連接。",
    "connect_fail_12b07c7c": "藍牙直接連接僅支援 Mac 電腦",
    "connect_fail_ccd91361": "請確認設備已經連接並打開電源",
    "connect_fail_1e4caec6": "在此版本中, 一次只能連接一個設備。因此, 連接此設備將會斷開前一個設備的連接。",
    "upload_fail_d5fa5444": "請確認您的設備連接正確。您可以重新開機啟動設備並重新連接。",
    "upload_fail_ae3a4ed5": "請確認韌體工作正常。您可以更新韌體或還原到出廠設定, 然後重試。",
    "upload_fail_d36df56a": "請檢查您的設備韌體，確認是否正常動作，假如沒有正常動作，請重新更新韌體。",
    "firmware_success_c205609a": "為了獲得更好的體驗, 請重新開機設備並再次連接它。",
    "firmware_fail_34b7a344": "請確保設備已正確連接。重新開機設備, 再次連接, 然後再次嘗試更新韌體。",
    "firmware_fail_340c3de8": "此設備不支援通過藍牙傳輸器或其他方式進行韌體更新。",
    "codey_emotion_look_up": "往上看",
    "codey_emotion_look_down": "往下看",
    "codey_emotion_look_left": "向左看",
    "codey_emotion_look_right": "向右看",
    "codey_emotion_look_around": "環顧四周",
    "codey_emotion_wink": "閃爍",
    "codey_emotion_smile": "笑容",
    "codey_emotion_yeah": "耶！",
    "codey_emotion_naughty": "淘氣",
    "codey_emotion_proud": "驕傲",
    "codey_emotion_coquetry": "美味",
    "codey_emotion_awkward": "尷尬",
    "codey_emotion_exclaim": "哇哦",
    "codey_emotion_aggrieved": "痛苦",
    "codey_emotion_sad": "悲傷",
    "codey_emotion_angry": "生氣",
    "codey_emotion_greeting": "你好",
    "codey_emotion_sprint": "衝刺",
    "codey_emotion_startle": "害怕",
    "codey_emotion_shiver": "發抖",
    "codey_emotion_dizzy": "頭暈",
    "codey_emotion_sleepy": "瞌睡",
    "codey_emotion_sleeping": "沉睡",
    "codey_emotion_revive": "激活",
    "codey_emotion_agree": "是",
    "codey_emotion_deny": "不是",
    "CATEGORY_EMOTION": "情感 ",
    "meos_show_led_matrix_face_with_time": "[ICON] 顯示圖案 [PANEL]，持續 [TIME] 秒",
    "meos_show_led_matrix_face": "[ICON] 顯示圖案 [PANEL]",
    "meos_show_led_matrix_face_position": "[ICON] 顯示圖案 [PANEL] 在 x: [AXIS-X] Y： [AXIS-Y]",
    "meos_show_led_matrix_turn_off": "[ICON] 清除螢幕",
    "meos_show_led_matrix": "[ICON] 顯示文字 [STRING]",
    "meos_show_led_matrix_string": "[ICON] 顯示 [STRING] 直到全部顯示",
    "meos_show_led_matrix_string_position": "[ICON] 顯示文字 [STRING] 在位置 x:[X] y:[Y]",
    "meos_show_led_matrix_position": "[ICON] 點亮位置 x: [X] y: [Y]",
    "meos_light_off_led_matrix_position": "[ICON] 熄滅位置 x: [X] y: [Y]",
    "meos_toggle_led_matrix_position": "[ICON] 位置 x:[X] y:[Y] 狀態切換",
    "meos_event_led_matrix_position_is_light": "[ICON] 位置 x: [X] y: [Y] 是點亮的嗎？",
    "CATEGORY_SHOW": "外觀",
    "meos_show_led_with_time": "[ICON] LED 燈的顏色設為 [COLOR]，持續 [TIME] 秒",
    "meos_show_led": "[ICON] LED 燈的顏色設為 [COLOR]",
    "MEOS_SHOW_LED_RGB_RGB_0": "紅色",
    "MEOS_SHOW_LED_RGB_RGB_1": "綠色",
    "MEOS_SHOW_LED_RGB_RGB_2": "藍色",
    "meos_show_led_rgb": "[ICON] LED燈的 [RGB] 值設為 [VALUE]",
    "meos_turn_off_led": "[ICON] 關閉 LED 燈",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_0": "紅色",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_1": "綠色",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_2": "藍色",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_3": "黃色",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_4": "青色",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_5": "紫色",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_6": "白色",
    "meos_rocky_show_led_color": "[ICON] Rocky的燈光顏色設為 [COLORLIST]",
    "meos_rocky_turn_off_led_color": "[ICON] 關閉Rocky燈光",
    "CATEGORY_LIGHT": "燈光",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_0": "哈囉",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_1": "嗨",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_2": "拜拜！",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_3": "耶！",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_4": "哇！",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_5": "笑聲",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_6": "哼！",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_7": "傷心",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_8": "嘆氣",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_9": "好吵",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_10": "生氣",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_11": "驚訝",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_12": "好吃",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_13": "好奇",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_14": "害羞",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_15": "準備",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_16": "衝刺",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_17": "想睡",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_18": "喵",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_19": "啟動",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_20": "開關",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_21": "嗶嗶",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_22": "嗡嗡",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_23": "排氣",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_24": "爆炸",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_25": "太好了！",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_26": "受傷",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_27": "跳動",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_28": "雷射",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_29": "升級",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_30": "低電量",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_31": "金屬碰撞",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_32": "提示音",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_33": "向右移動",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_34": "錯誤",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_35": "鈴聲",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_36": "得分",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_37": "發射",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_38": "腳步聲1",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_39": "腳步聲2",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_40": "喚醒",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_41": "警告",
    "meos_show_play_sound": "[ICON] 播放聲音 [SOUNDLIST]",
    "meos_show_play_sound_wait": "[ICON] 播放聲音 [SOUNDLIST] 直到結束",
    "meos_show_stop_allsound": "[ICON] 停止所有聲音",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_0": "C2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_1": "D2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_2": "E2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_3": "F2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_4": "G2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_5": "A2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_6": "B2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_7": "C3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_8": "D3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_9": "E3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_10": "F3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_11": "G3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_12": "A3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_13": "B3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_14": "C4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_15": "D4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_16": "E4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_17": "F4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_18": "G4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_19": "A4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_20": "B4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_21": "C5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_22": "D5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_23": "E5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_24": "F5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_25": "G5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_26": "A5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_27": "B5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_28": "C6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_29": "D6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_30": "E6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_31": "F6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_32": "G6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_33": "A6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_34": "B6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_35": "C7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_36": "D7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_37": "E7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_38": "F7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_39": "G7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_40": "A7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_41": "B7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_42": "C8",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_43": "D8",
    "meos_show_play_note_with_string": "[ICON] 播放音調 [SOUNDNOTE] 持續 [SOUNDBEAT] 拍",
    "meos_show_pause_note": "[ICON] 休止 [TIME] 拍",
    "meos_show_play_hz": "[ICON] 播放音頻 [HZ] 赫茲，持續 [TIME] 秒",
    "meos_show_change_volume": "[ICON] 音量增加 [VOLUME]",
    "meos_show_set_volume": "[ICON] 將音量設定為[VOLUME] %",
    "meos_detect_sound_volume": "[ICON] 音量",
    "CATEGORY_PLAY": "喇叭",
    "meos_move_forward_with_time": "[ICON] 前進，動力 [POWER] %，持續 [TIME] 秒",
    "meos_move_backward_with_time": "[ICON] 後退，動力 [POWER] %，持續 [TIME] 秒",
    "meos_move_left_with_time": "[ICON] 左轉，動力 [POWER] %，持續 [TIME] 秒",
    "meos_move_right_with_time": "[ICON] 右轉，動力 [POWER] %，持續 [TIME] 秒",
    "meos_rocky_keep_absolute_forward": "[ICON] 直線前進，動力 [POWER] %，持續 [TIME] 秒",
    "meos_rocky_keep_absolute_backward": "[ICON] 直線後退，動力 [POWER] %，持續 [TIME] 秒",
    "meos_move_left_with_angle": "[image_4] 左轉 [ICON] [ANGLE] 度直到結束",
    "meos_move_right_with_angle": "[image_5] 右轉 [ICON] [ANGLE] 度直到結束",
    "MEOS_MOVE_DIRECTION_0": "前進",
    "MEOS_MOVE_DIRECTION_1": "後退",
    "MEOS_MOVE_DIRECTION_2": "左轉",
    "MEOS_MOVE_DIRECTION_3": "右轉",
    "meos_move": "[ICON][DIRECTION]，動力 [POWER] %",
    "meos_move_with_motors": "[ICON] 左輪動力 [LEFT_POWER] %，右輪動力 [RIGHT_POWER] %",
    "meos_move_stop": "[ICON] 停止運動",
    "MEOS_ROCKY_KEEP_ABSOLUTE_RUN_DIRECTION_0": "前進",
    "MEOS_ROCKY_KEEP_ABSOLUTE_RUN_DIRECTION_1": "後退",
    "meos_rocky_keep_absolute_run": "[ICON] 直線 [DIRECTION]，動力 [POWER] %，持續 [TIME] 秒",
    "CATEGORY_ACTION": "作動",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_0": "A",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_1": "B",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_2": "C",
    "meos_event_button_pressed": "[ICON] 按下 [BUTTONS] 按鈕？",
    "meos_event_connect_rocky": "[ICON] 當Codey連接到Rocky",
    "meos_detect_potentiometer": "[ICON] 旋鈕-可變電阻讀值",
    "meos_detect_volume": "[ICON] 音量大小",
    "meos_detect_lightness": "[ICON] 環境光強度",
    "meos_dump_energy": "[ICON] 電池電量",
    "meos_event_is_shaked": "[ICON] 小程搖晃？",
    "meos_detect_shaked_strength": "[ICON] 搖晃強度",
    "MEOS_EVENT_IS_TILT_DIRECTION_0": "向左傾斜",
    "MEOS_EVENT_IS_TILT_DIRECTION_1": "向右傾斜",
    "MEOS_EVENT_IS_TILT_DIRECTION_2": "耳朵朝上",
    "MEOS_EVENT_IS_TILT_DIRECTION_3": "耳朵朝下",
    "meos_event_is_tilt": "[ICON] Codey偏向 [DIRECTION] 傾斜？",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_0": "正面朝上",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_1": "正面朝下",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_2": "站立在桌面",
    "meos_event_is_orientate_to": "[ICON] Codey姿態為[ORIENTATE]?",
    "meos_detect_gyro_roll_angle": "[ICON] 翻滾角度°",
    "meos_detect_gyro_pitch_angle": "[ICON] 俯仰角度°",
    "meos_detect_rotatex_angle": "[ICON] 繞x軸旋轉的角度",
    "meos_detect_rotatey_angle": "[ICON] 繞y軸旋轉的角度",
    "meos_detect_rotatez_angle": "[ICON] 繞z軸旋轉的角度",
    "MEOS_RESET_ANGLE_AXIS_0": "x 軸",
    "MEOS_RESET_ANGLE_AXIS_1": "y 軸",
    "MEOS_RESET_ANGLE_AXIS_2": "z 軸",
    "MEOS_RESET_ANGLE_AXIS_3": "所有軸向",
    "meos_reset_angle": "[ICON] 重置 [AXIS] 的旋轉角度°",
    "meos_detect_time": "[ICON] 計時器",
    "meos_show_reset_time": "[ICON] 重置計時器",
    "meos_rocky_event_obstacles_ahead": "[ICON] 前方有障礙物？",
    "MEOS_EVENT_IS_COLOR_COLOR_0": "紅色",
    "MEOS_EVENT_IS_COLOR_COLOR_1": "綠色",
    "MEOS_EVENT_IS_COLOR_COLOR_2": "藍色",
    "MEOS_EVENT_IS_COLOR_COLOR_3": "黃色",
    "MEOS_EVENT_IS_COLOR_COLOR_4": "青色",
    "MEOS_EVENT_IS_COLOR_COLOR_5": "紫色",
    "MEOS_EVENT_IS_COLOR_COLOR_6": "黑色",
    "MEOS_EVENT_IS_COLOR_COLOR_7": "白色",
    "meos_event_is_color": "[ICON] 偵測到顏色 [COLOR]?",
    "meos_rocky_detect_rgb": "[ICON] 偵測到 [RGB] 色值？",
    "meos_rocky_detect_lightness": "[ICON] 顏色紅外感測器 環境光強度",
    "meos_rocky_detect_reflection": "[ICON] 顏色紅外感測器 反射光強度",
    "meos_rocky_detect_ir_reflection": "[ICON] 顏色紅外感測器 紅外光反射強度",
    "meos_rocky_detect_grey": "[ICON] 顏色感測器的灰階數值",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_0": "x 軸 ",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_1": "y 軸",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_2": "z 軸",
    "meos_detect_rotate_angle": "[ICON] 繞[AXIS] 旋轉的角度",
    "MEOS_DETECT_GYRO_ANGLE_AXIS_0": "翻滾",
    "MEOS_DETECT_GYRO_ANGLE_AXIS_1": "俯仰",
    "meos_detect_gyro_angle": "[ICON] [AXIS] 角度 (°)",
    "CATEGORY_SENSOR": "偵測",
    "meos_comm_send_ir": "[ICON] 發送紅外線訊息 [STRING]",
    "meos_comm_receive_ir": "[ICON] 當收到紅外線訊息",
    "meos_comm_learn_with_time": "[ICON] 記錄家電遙控訊號3秒",
    "meos_comm_send_learn_result": "[ICON] 發送家電遙控訊號  ",
    "CATEGORY_COMM": "紅外線通訊",
    "meos_when_board_launch": "當Codey啟動時",
    "meos_when_button_press": "當按下 [BUTTONS] 按鈕",
    "meos_when_board_shake": "當Codey搖晃",
    "meos_when_board_tilt": "當 Codey [DIRECTION]傾斜",
    "MEOS_WHEN_VOLUME_OVER_MENU_LIST_0": "音量值",
    "MEOS_WHEN_VOLUME_OVER_MENU_LIST_1": "計時器",
    "meos_when_volume_over": "當 [MENU_LIST] > [SOUNDVOLUME]",
    "meos_when_brightness_less": "當光線強度 < [BRIGHTNESS]",
    "firmwares_version_470858d0": "相容於 Makeblock App 的韌體",
    "status_device_state": "設備狀態",
    "status_firmware_versions": "韌體版本:",
    "status_mac_address": "MAC 位址:",
    "status_page_close": "結束"
};