export default {
    "codey": "程小奔",
    "extensionName": "程小奔",
    "extensionDescription": "",
    "firmwares_version_0": "最新固件",
    "UPDATE_FIRMWARE": "固件更新",
    "settings_0": "颜色传感器校准",
    "settings_1": "陀螺仪校准",
    "settings_54fdf115": "状态查询",
    "connect_fail_dc0edd70": "请确保USB线已正确连接当前设备",
    "connect_fail_ac025070": "请确保当前待连接设备处于开机状态",
    "connect_fail_3a075878": "目前慧编程只支持连接一台设备，连接当前设备另一台已连接设备会自动断开",
    "connect_fail_12b07c7c": "仅支持MAC系统下的蓝牙直连",
    "connect_fail_ccd91361": "请确保当前待连接设备处于开机状态",
    "connect_fail_1e4caec6": "目前慧编程只支持连接一台设备，连接当前设备另一台已连接设备会自动断开",
    "upload_fail_d5fa5444": "请检查该设备的积木或代码的数据类型、参数类型、编程逻辑是否符合程序规范",
    "upload_fail_ae3a4ed5": "请检查您是否正确连接设备，可以尝试重启设备后再重新连接设备",
    "upload_fail_d36df56a": "请检查您的设备固件是否正常工作，可以尝试更新最新固件后重试",
    "firmware_success_c205609a": "为了保证更好的体验，您可以重启设备后重新连接设备",
    "firmware_fail_34b7a344": "请检查您是否正确连接设备，可以尝试重启设备后重新连接设备，再尝试更新",
    "firmware_fail_340c3de8": "该设备不支持使用蓝牙适配器等连接形式进行固件更新操作",
    "codey_emotion_look_up": "向上看",
    "codey_emotion_look_down": "向下看",
    "codey_emotion_look_left": "向左看",
    "codey_emotion_look_right": "向右看",
    "codey_emotion_look_around": "东张西望",
    "codey_emotion_wink": "眨眼",
    "codey_emotion_smile": "笑",
    "codey_emotion_yeah": "耶",
    "codey_emotion_naughty": "调皮",
    "codey_emotion_proud": "得意",
    "codey_emotion_coquetry": "撒娇",
    "codey_emotion_awkward": "尴尬",
    "codey_emotion_exclaim": "惊叹",
    "codey_emotion_aggrieved": "委屈",
    "codey_emotion_sad": "难过",
    "codey_emotion_angry": "生气",
    "codey_emotion_greeting": "打招呼",
    "codey_emotion_sprint": "冲刺",
    "codey_emotion_startle": "吓一跳",
    "codey_emotion_shiver": "发抖",
    "codey_emotion_dizzy": "头晕",
    "codey_emotion_sleepy": "瞌睡",
    "codey_emotion_sleeping": "熟睡",
    "codey_emotion_revive": "苏醒",
    "codey_emotion_agree": "肯定",
    "codey_emotion_deny": "否定",
    "CATEGORY_EMOTION": "个性",
    "meos_show_led_matrix_face_with_time": "[ICON] 显示图案 [PANEL]  [TIME] 秒",
    "meos_show_led_matrix_face": "[ICON] 显示图案 [PANEL]",
    "meos_show_led_matrix_face_position": "[ICON] 显示图案 [PANEL] 在x: [AXIS-X]  y: [AXIS-Y]",
    "meos_show_led_matrix_turn_off": "[ICON] 熄灭屏幕",
    "meos_show_led_matrix": "[ICON] 显示 [STRING]",
    "meos_show_led_matrix_string": "[ICON] 显示 [STRING] 直到滚动结束",
    "meos_show_led_matrix_string_position": "[ICON] 显示 [STRING] 在x: [X]   y: [Y]",
    "meos_show_led_matrix_position": "[ICON] 点亮 x: [X]  y: [Y]",
    "meos_light_off_led_matrix_position": "[ICON] 熄灭 x: [X]  y: [Y]",
    "meos_toggle_led_matrix_position": "[ICON] 切换点亮与熄灭 x: [X]  y: [Y]",
    "meos_event_led_matrix_position_is_light": "[ICON]  x: [X]  y: [Y] 是点亮状态 ？",
    "CATEGORY_SHOW": "显示",
    "meos_show_led_with_time": "[ICON] 指示灯亮起 [COLOR]   [TIME] 秒",
    "meos_show_led": "[ICON] 指示灯亮起 [COLOR]",
    "MEOS_SHOW_LED_RGB_RGB_0": "红",
    "MEOS_SHOW_LED_RGB_RGB_1": "绿",
    "MEOS_SHOW_LED_RGB_RGB_2": "蓝",
    "meos_show_led_rgb": "[ICON] 设置指示灯 [RGB] 色值为 [VALUE]",
    "meos_turn_off_led": "[ICON] 熄灭指示灯",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_0": "红",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_1": "绿",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_2": "蓝",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_3": "黄",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_4": "青",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_5": "紫",
    "MEOS_ROCKY_SHOW_LED_COLOR_COLORLIST_6": "白",
    "meos_rocky_show_led_color": "[ICON] 设置小奔的灯光颜色为 [COLORLIST]",
    "meos_rocky_turn_off_led_color": "[ICON] 熄灭小奔的灯光",
    "CATEGORY_LIGHT": "灯光",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_0": "哈喽",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_1": "嗨",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_2": "拜",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_3": "耶",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_4": "哇哦",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_5": "笑声",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_6": "哼唱",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_7": "难过",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_8": "叹气",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_9": "哼！",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_10": "生气",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_11": "惊吓",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_12": "撒娇",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_13": "好奇",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_14": "尴尬",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_15": "准备",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_16": "冲刺",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_17": "打呼",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_18": "喵",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_19": "启动",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_20": "开关",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_21": "哔哔",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_22": "蜂鸣",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_23": "排气",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_24": "爆炸",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_25": "获取",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_26": "痛苦",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_27": "跳动",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_28": "激光",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_29": "升级",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_30": "低能量",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_31": "金属音",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_32": "提示",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_33": "正确",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_34": "错误",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_35": "铃声",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_36": "得分",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_37": "发射",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_38": "脚步声1",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_39": "脚步声2",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_40": "激活",
    "MEOS_SHOW_PLAY_SOUND_SOUNDLIST_41": "警告",
    "meos_show_play_sound": "[ICON] 播放声音 [SOUNDLIST]",
    "meos_show_play_sound_wait": "[ICON] 播放声音 [SOUNDLIST] 直到结束",
    "meos_show_stop_allsound": "[ICON] 停止播放声音",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_0": "C2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_1": "D2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_2": "E2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_3": "F2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_4": "G2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_5": "A2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_6": "B2",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_7": "C3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_8": "D3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_9": "E3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_10": "F3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_11": "G3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_12": "A3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_13": "B3",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_14": "C4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_15": "D4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_16": "E4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_17": "F4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_18": "G4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_19": "A4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_20": "B4",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_21": "C5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_22": "D5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_23": "E5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_24": "F5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_25": "G5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_26": "A5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_27": "B5",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_28": "C6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_29": "D6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_30": "E6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_31": "F6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_32": "G6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_33": "A6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_34": "B6",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_35": "C7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_36": "D7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_37": "E7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_38": "F7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_39": "G7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_40": "A7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_41": "B7",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_42": "C8",
    "MEOS_SHOW_PLAY_NOTE_WITH_STRING_SOUNDNOTE_43": "D8",
    "meos_show_play_note_with_string": "[ICON] 播放音符 [SOUNDNOTE] 以 [SOUNDBEAT] 拍",
    "meos_show_pause_note": "[ICON] 休止 [TIME] 拍",
    "meos_show_play_hz": "[ICON] 播放声音以频率 [HZ] 赫兹，持续 [TIME] 秒",
    "meos_show_change_volume": "[ICON] 将音量增加 [VOLUME]",
    "meos_show_set_volume": "[ICON] 将音量设置为 [VOLUME] %",
    "meos_detect_sound_volume": "[ICON] 音量",
    "CATEGORY_PLAY": "播放",
    "meos_move_forward_with_time": "[ICON] 前进以动力 [POWER] % [TIME] 秒",
    "meos_move_backward_with_time": "[ICON] 后退以动力 [POWER] % [TIME] 秒",
    "meos_move_left_with_time": "[ICON] 左转以动力 [POWER] % [TIME] 秒",
    "meos_move_right_with_time": "[ICON] 右转以动力 [POWER] % [TIME] 秒",
    "meos_rocky_keep_absolute_forward": "[ICON] 直线前进以动力 [POWER] % [TIME] 秒",
    "meos_rocky_keep_absolute_backward": "[ICON] 直线后退以动力 [POWER] % [TIME] 秒",
    "meos_move_left_with_angle": "[image_4] 左转 [ICON]  [ANGLE] 度直到结束",
    "meos_move_right_with_angle": "[image_5] 右转 [ICON]  [ANGLE] 度直到结束",
    "MEOS_MOVE_DIRECTION_0": "前进",
    "MEOS_MOVE_DIRECTION_1": "后退",
    "MEOS_MOVE_DIRECTION_2": "左转",
    "MEOS_MOVE_DIRECTION_3": "右转",
    "meos_move": "[ICON] [DIRECTION] 以动力 [POWER] %",
    "meos_move_with_motors": "[ICON] 移动 左轮以动力 [LEFT_POWER] % 右轮 [RIGHT_POWER] %",
    "meos_move_stop": "[ICON] 停止运动",
    "MEOS_ROCKY_KEEP_ABSOLUTE_RUN_DIRECTION_0": "前进",
    "MEOS_ROCKY_KEEP_ABSOLUTE_RUN_DIRECTION_1": "后退",
    "meos_rocky_keep_absolute_run": "[ICON] 保持绝对 [DIRECTION] 以动力 [POWER] %，持续 [TIME] 秒",
    "CATEGORY_ACTION": "运动",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_0": "A",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_1": "B",
    "MEOS_EVENT_BUTTON_PRESSED_BUTTONS_2": "C",
    "meos_event_button_pressed": "[ICON] 按钮 [BUTTONS] 被按下？",
    "meos_event_connect_rocky": "[ICON] 小程接入小奔？",
    "meos_detect_potentiometer": "[ICON] 齿轮电位器读数",
    "meos_detect_volume": "[ICON] 响度",
    "meos_detect_lightness": "[ICON] 环境光强度",
    "meos_dump_energy": "[ICON] 剩余电量百分比",
    "meos_event_is_shaked": "[ICON] 被摇晃？",
    "meos_detect_shaked_strength": "[ICON] 摇晃强度",
    "MEOS_EVENT_IS_TILT_DIRECTION_0": "向左",
    "MEOS_EVENT_IS_TILT_DIRECTION_1": "向右",
    "MEOS_EVENT_IS_TILT_DIRECTION_2": "耳朵向上",
    "MEOS_EVENT_IS_TILT_DIRECTION_3": "耳朵向下",
    "meos_event_is_tilt": "[ICON]小程 [DIRECTION]倾斜？",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_0": "正面向上",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_1": "背面向上",
    "MEOS_EVENT_IS_ORIENTATE_TO_ORIENTATE_2": "直立在桌面",
    "meos_event_is_orientate_to": "[ICON]小程的姿态为 [ORIENTATE]？",
    "meos_detect_gyro_roll_angle": "[ICON]  翻滚角 角度°",
    "meos_detect_gyro_pitch_angle": "[ICON]  俯仰角 角度°",
    "meos_detect_rotatex_angle": "[ICON]  绕 x 轴转过的角度°",
    "meos_detect_rotatey_angle": "[ICON]  绕 y 轴转过的角度°",
    "meos_detect_rotatez_angle": "[ICON]  绕 z 轴转过的角度°",
    "MEOS_RESET_ANGLE_AXIS_0": "x轴",
    "MEOS_RESET_ANGLE_AXIS_1": "y轴",
    "MEOS_RESET_ANGLE_AXIS_2": "z轴",
    "MEOS_RESET_ANGLE_AXIS_3": "所有轴",
    "meos_reset_angle": "[ICON] 重置 [AXIS] 转过的角度°",
    "meos_detect_time": "[ICON] 计时器",
    "meos_show_reset_time": "[ICON] 重置计时器",
    "meos_rocky_event_obstacles_ahead": "[ICON] 检测到物体？",
    "MEOS_EVENT_IS_COLOR_COLOR_0": "红色",
    "MEOS_EVENT_IS_COLOR_COLOR_1": "绿色",
    "MEOS_EVENT_IS_COLOR_COLOR_2": "蓝色",
    "MEOS_EVENT_IS_COLOR_COLOR_3": "黄色",
    "MEOS_EVENT_IS_COLOR_COLOR_4": "青色",
    "MEOS_EVENT_IS_COLOR_COLOR_5": "紫色",
    "MEOS_EVENT_IS_COLOR_COLOR_6": "黑色",
    "MEOS_EVENT_IS_COLOR_COLOR_7": "白色",
    "meos_event_is_color": "[ICON] 检测到的颜色是 [COLOR] ？",
    "meos_rocky_detect_rgb": "[ICON] 检测到的 [RGB] 色值",
    "meos_rocky_detect_lightness": "[ICON] 颜色红外传感器 环境光强度",
    "meos_rocky_detect_reflection": "[ICON] 颜色红外传感器 反射光强度",
    "meos_rocky_detect_ir_reflection": "[ICON] 颜色红外传感器 红外反射光强度",
    "meos_rocky_detect_grey": "[ICON] 颜色红外传感器 灰度值",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_0": "x轴",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_1": "y轴",
    "MEOS_DETECT_ROTATE_ANGLE_AXIS_2": "z轴",
    "meos_detect_rotate_angle": "[ICON] 绕 [AXIS] 转过的角度",
    "MEOS_DETECT_GYRO_ANGLE_AXIS_0": "滚转角",
    "MEOS_DETECT_GYRO_ANGLE_AXIS_1": "俯仰角",
    "meos_detect_gyro_angle": "[ICON] [AXIS] 角度°",
    "CATEGORY_SENSOR": "感知",
    "meos_comm_send_ir": "[ICON] 发送红外消息 [STRING]",
    "meos_comm_receive_ir": "[ICON] 接收的红外消息",
    "meos_comm_learn_with_time": "[ICON] 录制家电遥控器信号3秒",
    "meos_comm_send_learn_result": "[ICON] 发送家电遥控器信号",
    "CATEGORY_COMM": "红外通讯",
    "meos_when_board_launch": "当小程启动",
    "meos_when_button_press": "当按下按钮 [BUTTONS]",
    "meos_when_board_shake": "当小程摇晃时",
    "meos_when_board_tilt": "当小程 [DIRECTION]倾斜",
    "MEOS_WHEN_VOLUME_OVER_MENU_LIST_0": "响度",
    "MEOS_WHEN_VOLUME_OVER_MENU_LIST_1": "计时器",
    "meos_when_volume_over": "当 [MENU_LIST] > [SOUNDVOLUME]",
    "meos_when_brightness_less": "当环境光强度 < [BRIGHTNESS]",
    "firmwares_version_470858d0": "Makeblock App 兼容固件",
    "status_device_state": "设备状态",
    "status_firmware_versions": "固件版本：",
    "status_mac_address": "MAC_地址：",
    "status_page_close": "关闭"
};