export default {
    "codeyneuron": "Neuron",
    "extensionName": "Neuron",
    "extensionDescription": "Connectez Codey à Neuron pour créer des applications plus intéressantes!",
    "codey_neuron_set_ledpanel_with_time": "[ICON] le panneau LED [ID] affiche l'image [PANEL] pendant [TIME] secondes",
    "codey_neuron_set_ledpanel_face": "[ICON] le panneau LED [ID] afficher l'image [PANEL]",
    "codey_neuron_set_ledpanel_text": "[ICON] le panneau de LED [ID] affiche [TEXT]",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_0": "rouge",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_1": "orange",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_2": "jaune",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_3": "vert",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_4": "cyan",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_5": "bleu",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_6": "violet",
    "codey_neuron_set_ledpanel_position_color": "[ICON] le panneau LED [ID] s'allume à la position x : [X] y : [Y] en [COLOR]",
    "codey_neuron_set_ledpanel_postion_rgb": "[ICON] le panneau LED [ID] s'allume à la position x : [X] y : [Y] en rouge [R] vert [G] bleu [B]",
    "codey_neuron_turn_off_ledpanel_position": "[ICON] le panneau LED [ID] s'éteint en x: [X] y: [Y]",
    "codey_neuron_turn_off_ledpanel": "[ICON] le panneau LED [ID] s'éteint",
    "codey_neuron_set_ledstrip_mode": "[ICON] ruban LED[ID] s’allume [STRIP]",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_0": "rouge",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_1": "orange",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_2": "jaune",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_3": "vert",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_4": "cyan",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_5": "bleu",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_6": "violet",
    "codey_neuron_set_ledstrip_with_color": "[ICON] La ruban LED [ID] s'allume [POSITION] avec la couleur [COLORLIST]",
    "codey_neuron_set_ledstrip_with_rgb": "[ICON] la ruban LED [ID] s'allume [POSITION] avec la couleur rouge [R] verte [G] bleue [B]",
    "CODEY_NEURON_PLAY_TONE_TONE_0": "C7",
    "CODEY_NEURON_PLAY_TONE_TONE_1": "C2",
    "CODEY_NEURON_PLAY_TONE_TONE_2": "D2",
    "CODEY_NEURON_PLAY_TONE_TONE_3": "E2",
    "CODEY_NEURON_PLAY_TONE_TONE_4": "F2",
    "CODEY_NEURON_PLAY_TONE_TONE_5": "G2",
    "CODEY_NEURON_PLAY_TONE_TONE_6": "A2",
    "CODEY_NEURON_PLAY_TONE_TONE_7": "B2",
    "CODEY_NEURON_PLAY_TONE_TONE_8": "C3",
    "CODEY_NEURON_PLAY_TONE_TONE_9": "D3",
    "CODEY_NEURON_PLAY_TONE_TONE_10": "E3",
    "CODEY_NEURON_PLAY_TONE_TONE_11": "F3",
    "CODEY_NEURON_PLAY_TONE_TONE_12": "G3",
    "CODEY_NEURON_PLAY_TONE_TONE_13": "A3",
    "CODEY_NEURON_PLAY_TONE_TONE_14": "B3",
    "CODEY_NEURON_PLAY_TONE_TONE_15": "C4",
    "CODEY_NEURON_PLAY_TONE_TONE_16": "D4",
    "CODEY_NEURON_PLAY_TONE_TONE_17": "E4",
    "CODEY_NEURON_PLAY_TONE_TONE_18": "F4",
    "CODEY_NEURON_PLAY_TONE_TONE_19": "G4",
    "CODEY_NEURON_PLAY_TONE_TONE_20": "A4",
    "CODEY_NEURON_PLAY_TONE_TONE_21": "B4",
    "CODEY_NEURON_PLAY_TONE_TONE_22": "C5",
    "CODEY_NEURON_PLAY_TONE_TONE_23": "D5",
    "CODEY_NEURON_PLAY_TONE_TONE_24": "E5",
    "CODEY_NEURON_PLAY_TONE_TONE_25": "F5",
    "CODEY_NEURON_PLAY_TONE_TONE_26": "G5",
    "CODEY_NEURON_PLAY_TONE_TONE_27": "A5",
    "CODEY_NEURON_PLAY_TONE_TONE_28": "B5",
    "CODEY_NEURON_PLAY_TONE_TONE_29": "C6",
    "CODEY_NEURON_PLAY_TONE_TONE_30": "D6",
    "CODEY_NEURON_PLAY_TONE_TONE_31": "E6",
    "CODEY_NEURON_PLAY_TONE_TONE_32": "F6",
    "CODEY_NEURON_PLAY_TONE_TONE_33": "G6",
    "CODEY_NEURON_PLAY_TONE_TONE_34": "A6",
    "CODEY_NEURON_PLAY_TONE_TONE_35": "B6",
    "CODEY_NEURON_PLAY_TONE_TONE_36": "D7",
    "CODEY_NEURON_PLAY_TONE_TONE_37": "E7",
    "CODEY_NEURON_PLAY_TONE_TONE_38": "F7",
    "CODEY_NEURON_PLAY_TONE_TONE_39": "G7",
    "CODEY_NEURON_PLAY_TONE_TONE_40": "A7",
    "CODEY_NEURON_PLAY_TONE_TONE_41": "B7",
    "CODEY_NEURON_PLAY_TONE_TONE_42": "C8",
    "CODEY_NEURON_PLAY_TONE_TONE_43": "D8",
    "codey_neuron_play_tone": "[ICON] le buzzer [ID] joue la note [TONE] pendant [BEAT] temps",
    "codey_neuron_play_hz": "[ICON] le buzzer [ID] joue à une fréquence de [HZ] pendant [TIME] secondes",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_0": "tout",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_1": "emplacement1",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_2": "emplacement2",
    "codey_neuron_run_dcmotor_with_speed_time": "[ICON] DC Motor [ID] [SLOT] rotates at power [POWER]% for [TIME] secs",
    "codey_neuron_run_dcmotor_with_speed": "[ICON] le moteur CC [ID] [SLOT] tourne à la puissance [POWER]%",
    "codey_neuron_run_dcmotor_wheel": "[ICON] DC Motor [ID] slot1 rotates at power [POWER_LEFT]% slot2 rotates at power [POWER_RIGHT]%",
    "codey_neuron_run_servo": "[ICON] servo [ID] [SLOT] tourne de [ANGLE] degrés",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_0": "bleu",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_1": "jaune",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_2": "rouge",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_3": "vert",
    "codey_neuron_event_touch_color": "[ICON] le port Funny Touch [ID] [COLOR] est touché ?",
    "codey_neuron_detect_ultrasonic": "[ICON] distance (cm) mesurée par le capteur ultrasons [ID]",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_0": "en avant",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_1": "en arrière",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_2": "vers la gauche",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_3": "vers la droite",
    "codey_neuron_event_tilt": "[ICON] le capteur gyroscopique [ID] est incliné en [DIRECTION] ?",
    "codey_neuron_event_shaked": "[ICON] le capteur gyroscopique [ID] bouge-t-il ?",
    "CODEY_NEURON_DETECT_GYRO_ANGLE_COORDINATE_0": "angle de roulis",
    "CODEY_NEURON_DETECT_GYRO_ANGLE_COORDINATE_1": "angle de tangage",
    "codey_neuron_detect_gyro_angle": "[ICON] le senseur gyroscopique [ID] est à un angle de [COORDINATE] (°)",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_0": "x",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_1": "y",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_2": "z",
    "codey_neuron_detect_gyro_speed": "[ICON] le senseur gyroscopique [ID][COORDINATE] à une accélération en m/s²",
    "codey_neuron_event_pir": "[ICON] capteur de présence [ID] détecte-t-il des personnes ?",
    "codey_neuron_detect_humidity": "[ICON] humidité du senseur d'humidité [ID]",
    "codey_neuron_button": "[ICON] le bouton [ID] est-il enfoncé？",
    "codey_neuron_rgb_led_show_with_time": "[ICON] Les LED RGB [ID] s'allument en [color_1] pendant [time] secondes",
    "codey_neuron_rgb_led_show": "[ICON] La LED RGB [ID] s'allume en [color_1]",
    "codey_neuron_rgb_led_set_rgb": "[ICON] passer les LED RGB [ID] en Rouge [R] Vert [G] Bleu [B]",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_0": "normal",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_1": "somnolent",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_2": "triste",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_3": "heureux",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_4": "lunettes",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_5": "en colère",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_6": "dévisage",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_7": "louche",
    "codey_neuron_display_show_image_with_time": "[ICON] l'afficheur [ID] montre l'émotion [emoji] pendant [time] secondes",
    "codey_neuron_display_show_image": "[ICON] l'afficheur [ID] montre l'émotion [emoji]",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_0": "air",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_1": "coche",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_2": "nuage",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_3": "cœur",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_4": "lune",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_5": "pluie",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_6": "anneau circulaire",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_7": "règle",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_8": "course",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_9": "sourire",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_10": "neige",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_11": "soleil",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_12": "thermomètre",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_13": "goutte d'eau",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_14": "aucun",
    "codey_neuron_display_show_string": "[ICON] l'afficheur [ID] montre l'icone [icon] texte [text]",
    "codey_neuron_display_show_string_in_mutiple_lines": "[ICON] l'afficheur [ID] montre l'icone [icon] texte [text] sur la ligne du haut et affiche l'icone [icon2] texte [text2] sur la ligne d'en dessous",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_0": "emplacement1",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_1": "emplacement2",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_2": "slot 3",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_3": "slot 4",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_4": "tout",
    "codey_neuron_el_wire_on": "[ICON] EL [ID] s'allume en [output]",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_0": "emplacement1",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_1": "emplacement2",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_2": "slot 3",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_3": "slot 4",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_4": "tout",
    "codey_neuron_el_wire_off": "[ICON] EL [ID] s'éteint en [output]",
    "codey_neuron_knob_get_value": "[ICON] valeur du bouton à [ID]",
    "codey_neuron_joystic_get_dir": "[ICON] joystick [ID] bouge-t-il vers [direction] ?",
    "CODEY_NEURON_JOYSTIC_GET_VALUE_AXIS_0": "x",
    "CODEY_NEURON_JOYSTIC_GET_VALUE_AXIS_1": "y",
    "codey_neuron_joystic_get_value": "[ICON] Joystick [ID] [axis]",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_0": "gauche",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_1": "droite",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_2": "tout",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_3": "aucun",
    "codey_neuron_dual_ir_is_active": "[ICON] détecteur double infrarouge [ID] [option] déclenché ?",
    "codey_neuron_light_sensor_get_value": "[ICON] intensité mesurée par le capteur de lumière [ID]",
    "codey_neuron_temperature_sensor_get_celsius": "[ICON] capteur de température [ID] dégrées (°C)",
    "codey_neuron_humiture_sensor_get_humidity": "[ICON] capteur humidité [ID] humidité (%)",
    "codey_neuron_humiture_sensor_get_celsius": "[ICON] capteur d'humidité [ID] degrées (°C)",
    "codey_neuron_humiture_sensor_get_fahrenheit": "[ICON] capteur d'humidité [ID] degrées (°F)",
    "codey_neuron_ranging_sensor_get_distance": "[ICON] distance (cm) mesurée par le capteur ultrasons [ID]",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_0": "rouge",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_1": "vert",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_2": "bleu",
    "codey_neuron_color_sensor_get_value": "[ICON] valeur [color] pour capteur de couleur [ID]",
    "CATEGORY_NEURON": "Neuron"
};