export default {
    "codeyneuron": "Neuron",
    "extensionName": "Neuron",
    "extensionDescription": "Connetti Codey a Neuron per creare applicazioni più divertenti!",
    "codey_neuron_set_ledpanel_with_time": "[ICON] pannello LED [ID] mostra immagine[PANEL] per[TIME] secondi",
    "codey_neuron_set_ledpanel_face": "[ICON] pannello LED [ID] mostra immagine[PANEL]",
    "codey_neuron_set_ledpanel_text": "[ICON] pannello LED [ID] mostra [TEXT]",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_0": "rosso",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_1": "arancione",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_2": "giallo",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_3": "green",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_4": "ciano",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_5": "blu",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_6": "viola",
    "codey_neuron_set_ledpanel_position_color": "[ICON] pannello LED [ID] si accende a x: [X] y: [Y] con colore [COLOR]",
    "codey_neuron_set_ledpanel_postion_rgb": "[ICON] pannello LED [ID] si accende a x: [X] y: [Y] con rosso [R] verde [G] blu [B]",
    "codey_neuron_turn_off_ledpanel_position": "[ICON] pannello LED [ID] si spegne a x: [X] y: [Y]",
    "codey_neuron_turn_off_ledpanel": "[ICON] pannello LED [ID] si spegne",
    "codey_neuron_set_ledstrip_mode": "[ICON] striscia LED [ID] si illumina [STRIP]",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_0": "rosso",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_1": "arancione",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_2": "giallo",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_3": "green",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_4": "ciano",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_5": "blu",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_6": "viola",
    "codey_neuron_set_ledstrip_with_color": "[ICON] striscia LED [ID] si illumina a [POSITION] con colore [COLORLIST]",
    "codey_neuron_set_ledstrip_with_rgb": "[ICON] striscia LED [ID] si illumina a [POSITION] con colore rosso [R] verde [G] blu [B]",
    "CODEY_NEURON_PLAY_TONE_TONE_0": "C7",
    "CODEY_NEURON_PLAY_TONE_TONE_1": "C2",
    "CODEY_NEURON_PLAY_TONE_TONE_2": "D2",
    "CODEY_NEURON_PLAY_TONE_TONE_3": "E2",
    "CODEY_NEURON_PLAY_TONE_TONE_4": "F2",
    "CODEY_NEURON_PLAY_TONE_TONE_5": "G2",
    "CODEY_NEURON_PLAY_TONE_TONE_6": "A2",
    "CODEY_NEURON_PLAY_TONE_TONE_7": "B2",
    "CODEY_NEURON_PLAY_TONE_TONE_8": "C3",
    "CODEY_NEURON_PLAY_TONE_TONE_9": "D3",
    "CODEY_NEURON_PLAY_TONE_TONE_10": "E3",
    "CODEY_NEURON_PLAY_TONE_TONE_11": "F3",
    "CODEY_NEURON_PLAY_TONE_TONE_12": "G3",
    "CODEY_NEURON_PLAY_TONE_TONE_13": "A3",
    "CODEY_NEURON_PLAY_TONE_TONE_14": "B3",
    "CODEY_NEURON_PLAY_TONE_TONE_15": "C4",
    "CODEY_NEURON_PLAY_TONE_TONE_16": "D4",
    "CODEY_NEURON_PLAY_TONE_TONE_17": "E4",
    "CODEY_NEURON_PLAY_TONE_TONE_18": "F4",
    "CODEY_NEURON_PLAY_TONE_TONE_19": "G4",
    "CODEY_NEURON_PLAY_TONE_TONE_20": "A4",
    "CODEY_NEURON_PLAY_TONE_TONE_21": "B4",
    "CODEY_NEURON_PLAY_TONE_TONE_22": "C5",
    "CODEY_NEURON_PLAY_TONE_TONE_23": "D5",
    "CODEY_NEURON_PLAY_TONE_TONE_24": "E5",
    "CODEY_NEURON_PLAY_TONE_TONE_25": "F5",
    "CODEY_NEURON_PLAY_TONE_TONE_26": "G5",
    "CODEY_NEURON_PLAY_TONE_TONE_27": "A5",
    "CODEY_NEURON_PLAY_TONE_TONE_28": "B5",
    "CODEY_NEURON_PLAY_TONE_TONE_29": "C6",
    "CODEY_NEURON_PLAY_TONE_TONE_30": "D6",
    "CODEY_NEURON_PLAY_TONE_TONE_31": "E6",
    "CODEY_NEURON_PLAY_TONE_TONE_32": "F6",
    "CODEY_NEURON_PLAY_TONE_TONE_33": "G6",
    "CODEY_NEURON_PLAY_TONE_TONE_34": "A6",
    "CODEY_NEURON_PLAY_TONE_TONE_35": "B6",
    "CODEY_NEURON_PLAY_TONE_TONE_36": "D7",
    "CODEY_NEURON_PLAY_TONE_TONE_37": "E7",
    "CODEY_NEURON_PLAY_TONE_TONE_38": "F7",
    "CODEY_NEURON_PLAY_TONE_TONE_39": "G7",
    "CODEY_NEURON_PLAY_TONE_TONE_40": "A7",
    "CODEY_NEURON_PLAY_TONE_TONE_41": "B7",
    "CODEY_NEURON_PLAY_TONE_TONE_42": "C8",
    "CODEY_NEURON_PLAY_TONE_TONE_43": "D8",
    "codey_neuron_play_tone": "[ICON] altoparlante [ID] riproduce la nota [TONE] per [BEAT] battute",
    "codey_neuron_play_hz": "[ICON] altoparlante [ID] riproduce la frequenza di [HZ] per [TIME] secs",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_0": "tutti",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_1": "slot1",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_2": "slot2",
    "codey_neuron_run_dcmotor_with_speed_time": "[ICON]Motore DC [ID] [SLOT] ruota a potenza [POWER] % per [TIME] secondi",
    "codey_neuron_run_dcmotor_with_speed": "[ICON] Motore CC [ID] [SLOT] ruota a potenza [POWER]%",
    "codey_neuron_run_dcmotor_wheel": "[ICON] Motore DC [ID] slot1 ruota alla potenza [POWER_LEFT]% slot2 ruota a potenza [POWER_RIGHT]%",
    "codey_neuron_run_servo": "[ICON] servo [ID] [SLOT] ruota a [ANGLE] gradi",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_0": "blu",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_1": "giallo",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_2": "rosso",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_3": "green",
    "codey_neuron_event_touch_color": "[ICON] sensore di contatto [ID] slot [COLOR] è toccato?",
    "codey_neuron_detect_ultrasonic": "[ICON] sensore ultrasuoni [ID] distanza (cm)",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_0": "avanti",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_1": "indietro",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_2": "ruota verso sinistra",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_3": "ruota verso destra",
    "codey_neuron_event_tilt": "[ICON] sensore giroscopio [ID] è inclinato verso [DIRECTION]?",
    "codey_neuron_event_shaked": "[ICON] sensore giroscopio [ID] agitato?",
    "CODEY_NEURON_DETECT_GYRO_ANGLE_COORDINATE_0": "angolo di rotazione °",
    "CODEY_NEURON_DETECT_GYRO_ANGLE_COORDINATE_1": "angolo del beccheggio",
    "codey_neuron_detect_gyro_angle": "[ICON] sensore giroscopio [ID] angolo [COORDINATE] (°)",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_0": "x",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_1": "y",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_2": "z",
    "codey_neuron_detect_gyro_speed": "[ICON] sensore giroscopio [ID] accelerazione [COORDINATE] m/s²",
    "codey_neuron_event_pir": "[ICON] sensore PIR [ID] riconosce persone?",
    "codey_neuron_detect_humidity": "[ICON] sensore di umidità del suolo [ID] umidità",
    "codey_neuron_button": "[ICON] il pulsante [ID] è premuto？",
    "codey_neuron_rgb_led_show_with_time": "[ICON] RGB LED [ID] si accende [color_1] per [time] secondi",
    "codey_neuron_rgb_led_show": "[ICON] RGB LED [ID] acceso [color_1]",
    "codey_neuron_rgb_led_set_rgb": "[ICON] imposta RGB LED [ID] rosso [R] verde [G] blu [B]",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_0": "normale",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_1": "sonnolenza",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_2": "triste",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_3": "felice",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_4": "occhiali",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_5": "arrabbiato",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_6": "fissare",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_7": "strabico",
    "codey_neuron_display_show_image_with_time": "[ICON] display [ID] mostra emozione[emoji] per[time] secs",
    "codey_neuron_display_show_image": "[ICON] display [ID] mostra emozione[emoji]",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_0": "aria",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_1": "segni di spunta",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_2": "nuvola",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_3": "cuore",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_4": "luna",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_5": "pioggia",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_6": "anello circolare",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_7": "righello",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_8": "in esecuzione",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_9": "sorriso",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_10": "neve",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_11": "sole",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_12": "termometro",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_13": "goccia d'acqua",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_14": "nessuno",
    "codey_neuron_display_show_string": "[ICON] mostra[ID] mostra icona [icon] testo [text]",
    "codey_neuron_display_show_string_in_mutiple_lines": "[ICON] display [ID] mostra icona [icon] testo[text] sulla riga superiore mostra l'icona [icon2] testo [text2] sulla riga inferiore",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_0": "slot1",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_1": "slot2",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_2": "slot3",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_3": "slot4",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_4": "all",
    "codey_neuron_el_wire_on": "[ICON] EL [ID] accendi in [output]",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_0": "slot1",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_1": "slot2",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_2": "slot3",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_3": "slot4",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_4": "tutti",
    "codey_neuron_el_wire_off": "[ICON] EL [ID] spegni in [output]",
    "codey_neuron_knob_get_value": "[ICON] Manopola [ID] Valore",
    "codey_neuron_joystic_get_dir": "[ICON] joystick [ID] [direction] agitato?",
    "CODEY_NEURON_JOYSTIC_GET_VALUE_AXIS_0": "x",
    "CODEY_NEURON_JOYSTIC_GET_VALUE_AXIS_1": "y",
    "codey_neuron_joystic_get_value": "[ICON] joystick [ID] [axis] valore",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_0": "sinistra",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_1": "destra",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_2": "all",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_3": "nessuno",
    "codey_neuron_dual_ir_is_active": "[ICON] doppio rilevatore [ID] [option] attivato?",
    "codey_neuron_light_sensor_get_value": "[ICON] sensore di luce [ID] intensità luminosa",
    "codey_neuron_temperature_sensor_get_celsius": "[ICON] temperatura sensore [ID] gradi (℃)",
    "codey_neuron_humiture_sensor_get_humidity": "[ICON] sensore di umidità del suolo [ID] umidità (%)",
    "codey_neuron_humiture_sensor_get_celsius": "[ICON]sensore di umidità [ID]  temperatura (° c)",
    "codey_neuron_humiture_sensor_get_fahrenheit": "[ICON] sensore di umidità [ID] temperatura (°F)",
    "codey_neuron_ranging_sensor_get_distance": "[ICON] sensore di distanza[ID] distanza (cm)",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_0": "rosso",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_1": "green",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_2": "blu",
    "codey_neuron_color_sensor_get_value": "[ICON]valore sensore di colore [ID] [color]",
    "CATEGORY_NEURON": "Neuron"
};