export default {
    "codeyneuron": "Neuron",
    "extensionName": "Neuron",
    "extensionDescription": "CodeyをNeuronにせつぞくして、よりみりょくてきなアプリケーションをさくせいする",
    "codey_neuron_set_ledpanel_with_time": "[ICON] LEDパネル[ID] のがぞう [PANEL] を[TIME] びょうひょうじする",
    "codey_neuron_set_ledpanel_face": "[ICON]LEDパネル[ID] にがぞう [PANEL] をひょうじする",
    "codey_neuron_set_ledpanel_text": "[ICON] LEDパネル[ID] を[TEXT] でひょうじする",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_0": "あか",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_1": "オレンジ",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_2": "きいろ",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_3": "みどり",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_4": "シアン",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_5": "あお",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_6": "むらさき",
    "codey_neuron_set_ledpanel_position_color": "[ICON]LED パネル[ID] の x: [X] y: [Y] をカラー[COLOR] でてんとうする",
    "codey_neuron_set_ledpanel_postion_rgb": "[ICON]LED パネル[ID] を x: [X] y: [Y] にあか [R] みどり [G] あお [B] でてんとうする",
    "codey_neuron_turn_off_ledpanel_position": "[ICON]LEDパネル [ID] をX: [X] y: [Y] でしょうとうする",
    "codey_neuron_turn_off_ledpanel": "[ICON]LEDパネル[ID] をしょうとうする",
    "codey_neuron_set_ledstrip_mode": "[ICON]LED ストリップ [ID][STRIP] がてんとうする",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_0": "あか",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_1": "オレンジ",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_2": "きいろ",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_3": "みどり",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_4": "シアン",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_5": "あお",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_6": "むらさき",
    "codey_neuron_set_ledstrip_with_color": "[ICON] LED ストリップ [ID] すべて[POSITION] のカラーを[COLORLIST] で てんとうする",
    "codey_neuron_set_ledstrip_with_rgb": "[ICON] LEDストリップ [ID] の[POSITION] をあか [R] みどり[G] あお [B] でてんとうする",
    "CODEY_NEURON_PLAY_TONE_TONE_0": "C7",
    "CODEY_NEURON_PLAY_TONE_TONE_1": "C2",
    "CODEY_NEURON_PLAY_TONE_TONE_2": "D2",
    "CODEY_NEURON_PLAY_TONE_TONE_3": "E2",
    "CODEY_NEURON_PLAY_TONE_TONE_4": "F2",
    "CODEY_NEURON_PLAY_TONE_TONE_5": "G2",
    "CODEY_NEURON_PLAY_TONE_TONE_6": "A2",
    "CODEY_NEURON_PLAY_TONE_TONE_7": "B2",
    "CODEY_NEURON_PLAY_TONE_TONE_8": "C3",
    "CODEY_NEURON_PLAY_TONE_TONE_9": "D3",
    "CODEY_NEURON_PLAY_TONE_TONE_10": "E3",
    "CODEY_NEURON_PLAY_TONE_TONE_11": "F3",
    "CODEY_NEURON_PLAY_TONE_TONE_12": "G3",
    "CODEY_NEURON_PLAY_TONE_TONE_13": "A3",
    "CODEY_NEURON_PLAY_TONE_TONE_14": "B3",
    "CODEY_NEURON_PLAY_TONE_TONE_15": "C4",
    "CODEY_NEURON_PLAY_TONE_TONE_16": "D4",
    "CODEY_NEURON_PLAY_TONE_TONE_17": "E4",
    "CODEY_NEURON_PLAY_TONE_TONE_18": "F4",
    "CODEY_NEURON_PLAY_TONE_TONE_19": "G4",
    "CODEY_NEURON_PLAY_TONE_TONE_20": "A4",
    "CODEY_NEURON_PLAY_TONE_TONE_21": "B4",
    "CODEY_NEURON_PLAY_TONE_TONE_22": "C5",
    "CODEY_NEURON_PLAY_TONE_TONE_23": "D5",
    "CODEY_NEURON_PLAY_TONE_TONE_24": "E5",
    "CODEY_NEURON_PLAY_TONE_TONE_25": "F5",
    "CODEY_NEURON_PLAY_TONE_TONE_26": "G5",
    "CODEY_NEURON_PLAY_TONE_TONE_27": "A5",
    "CODEY_NEURON_PLAY_TONE_TONE_28": "B5",
    "CODEY_NEURON_PLAY_TONE_TONE_29": "C6",
    "CODEY_NEURON_PLAY_TONE_TONE_30": "D6",
    "CODEY_NEURON_PLAY_TONE_TONE_31": "E6",
    "CODEY_NEURON_PLAY_TONE_TONE_32": "F6",
    "CODEY_NEURON_PLAY_TONE_TONE_33": "G6",
    "CODEY_NEURON_PLAY_TONE_TONE_34": "A6",
    "CODEY_NEURON_PLAY_TONE_TONE_35": "B6",
    "CODEY_NEURON_PLAY_TONE_TONE_36": "D7",
    "CODEY_NEURON_PLAY_TONE_TONE_37": "E7",
    "CODEY_NEURON_PLAY_TONE_TONE_38": "F7",
    "CODEY_NEURON_PLAY_TONE_TONE_39": "G7",
    "CODEY_NEURON_PLAY_TONE_TONE_40": "A7",
    "CODEY_NEURON_PLAY_TONE_TONE_41": "B7",
    "CODEY_NEURON_PLAY_TONE_TONE_42": "C8",
    "CODEY_NEURON_PLAY_TONE_TONE_43": "D8",
    "codey_neuron_play_tone": "[ICON] ブザー[ID] が[TONE] のおとを[BEAT] はくでさいせいする",
    "codey_neuron_play_hz": "[ICON] [HZ] Hzのしゅうはすうでブザー [ID] のおとを[TIME] びょうならす",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_0": "すべて",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_1": "スロット1",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_2": "スロット2",
    "codey_neuron_run_dcmotor_with_speed_time": "[ICON] DCモーター [ID] [SLOT] が [POWER]% のはやさで [TIME] びょうまわる",
    "codey_neuron_run_dcmotor_with_speed": "[ICON] DC モーター [ID] [SLOT] を[POWER] %のはやさでかいてんする",
    "codey_neuron_run_dcmotor_wheel": "[ICON] DCモーター [ID] のスロット 1は [POWER_LEFT]% のはやさでかいてんして、スロット2は [POWER_RIGHT]% のはやさでかいてんする",
    "codey_neuron_run_servo": "[ICON] サーボモーター[ID] [SLOT] が[ANGLE] のかくどまでかいてんする",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_0": "あお",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_1": "きいろ",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_2": "あか",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_3": "みどり",
    "codey_neuron_event_touch_color": "[ICON]ファニータッチ[ID] スロット[COLOR] にふれたか？",
    "codey_neuron_detect_ultrasonic": "[ICON]ちょうおんぱセンサー [ID] のきょり (cm)",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_0": "まえ",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_1": "うしろ",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_2": "ひだり",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_3": "みぎ",
    "codey_neuron_event_tilt": "[ICON] ジャイロセンサー[ID] が[DIRECTION] にかたむいている",
    "codey_neuron_event_shaked": "[ICON] ジャイロセンサー[ID] がゆれているか？",
    "CODEY_NEURON_DETECT_GYRO_ANGLE_COORDINATE_0": "ロールかくど",
    "CODEY_NEURON_DETECT_GYRO_ANGLE_COORDINATE_1": "ピッチングかくど\n",
    "codey_neuron_detect_gyro_angle": "[ICON] ジャイロセンサー[ID][COORDINATE] かくど（°）",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_0": "x",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_1": "y",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_2": "z",
    "codey_neuron_detect_gyro_speed": "[ICON] ジャイロ センサー [ID] [COORDINATE] のかそくど m/s ²",
    "codey_neuron_event_pir": "[ICON]PIR センサー[ID]がひとをけんしゅつする？",
    "codey_neuron_detect_humidity": "[ICON] どじょうすいぶんセンサー [ID] しつど",
    "codey_neuron_button": "[ICON] ボタン[ID] がおされたか？",
    "codey_neuron_rgb_led_show_with_time": "[ICON] RGB LED[ID] を[color_1] いろで[time] びょうてんとうする",
    "codey_neuron_rgb_led_show": "[ICON] RGB LED[ID] を[color_1] いろでてんとうする",
    "codey_neuron_rgb_led_set_rgb": "[ICON] RGB LED [ID] をあか[R] みどり[G] あお[B] にする",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_0": "せいじょう",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_1": "ねむい",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_2": "かなしい",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_3": "たのしい",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_4": "Goggle",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_5": "いかり",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_6": "ぎょうし",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_7": "しゃし",
    "codey_neuron_display_show_image_with_time": "[ICON] ディスプレイ[ID] にかんじょう [emoji] を[time] びょうひょうじする",
    "codey_neuron_display_show_image": "[ICON] ディスプレイ[ID] にかんじょう [emoji] をひょうじする",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_0": "くうき",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_1": "チェック マーク",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_2": "くも",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_3": "ハート",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_4": "つき",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_5": "あめ",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_6": "えんかん",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_7": "じょうぎ",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_8": "ランニング",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_9": "えがお",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_10": "ゆき",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_11": "たいよう",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_12": "おんどけい",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_13": "すいてき",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_14": "なし",
    "codey_neuron_display_show_string": "[ICON] ディスプレイ[ID] にアイコン[icon] とテキスト[text] をひょうじする",
    "codey_neuron_display_show_string_in_mutiple_lines": "[ICON] ディスプレイ [ID] にアイコン [icon] とテキスト [text] をうえのぎょうに、アイコン [icon2] とテキスト [text2] をしたのぎょうにひょうじする",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_0": "スロット1",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_1": "スロット2",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_2": "スロット3\n",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_3": "スロット4",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_4": "すべて",
    "codey_neuron_el_wire_on": "[ICON] ELワイヤ [ID] の [output] をてんとうする",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_0": "スロット1",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_1": "スロット2",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_2": "スロット3\n",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_3": "スロット4",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_4": "すべて",
    "codey_neuron_el_wire_off": "[ICON] ELワイヤ [ID] の[output] をしょうとうする",
    "codey_neuron_knob_get_value": "[ICON] ノブ[ID] のち",
    "codey_neuron_joystic_get_dir": "[ICON] ジョイスティック [ID] が[direction] ほうこうにゆれている",
    "CODEY_NEURON_JOYSTIC_GET_VALUE_AXIS_0": "x",
    "CODEY_NEURON_JOYSTIC_GET_VALUE_AXIS_1": "y",
    "codey_neuron_joystic_get_value": "[ICON] ジョイスティック [ID] [axis] のち",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_0": "ひだり",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_1": "みぎ",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_2": "すべて",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_3": "なし",
    "codey_neuron_dual_ir_is_active": "[ICON] デュアルIRけんしゅつき [ID] [option] がトリガーされた",
    "codey_neuron_light_sensor_get_value": "[ICON] ひかりセンサー [ID] のあかるさ",
    "codey_neuron_temperature_sensor_get_celsius": "[ICON] おんどセンサー [ID] のおんど (℃)",
    "codey_neuron_humiture_sensor_get_humidity": "[ICON] おんしつどセンサー [ID] のしつど (%)",
    "codey_neuron_humiture_sensor_get_celsius": "[ICON]おんしつどセンサー [ID]のおんど (℃)",
    "codey_neuron_humiture_sensor_get_fahrenheit": "[ICON] おんしつどセンサー [ID] のおんど (°F)",
    "codey_neuron_ranging_sensor_get_distance": "[ICON] そっきょセンサー[ID] のきょり (cm)",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_0": "あか",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_1": "みどり",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_2": "あお",
    "codey_neuron_color_sensor_get_value": "[ICON]カラーセンサー [ID] [color] のち",
    "CATEGORY_NEURON": "Neuron"
};