export default {
    "codeyneuron": "Neuron",
    "extensionName": "Neuron",
    "extensionDescription": "CodeyをNeuronに接続して、より魅力的なアプリケーションを作成する",
    "codey_neuron_set_ledpanel_with_time": "[ICON] LEDパネル[ID] の画像 [PANEL] を[TIME] 秒表示する",
    "codey_neuron_set_ledpanel_face": "[ICON]LEDパネル[ID] に画像 [PANEL] を表示する",
    "codey_neuron_set_ledpanel_text": "[ICON]LEDパネル[ID] を[TEXT] で表示する",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_0": "赤",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_1": "オレンジ",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_2": "黄",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_3": "緑",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_4": "シアン",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_5": "青",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_6": "紫",
    "codey_neuron_set_ledpanel_position_color": "[ICON]LED パネル[ID] の x: [X] y: [Y] をカラー[COLOR] で点灯する",
    "codey_neuron_set_ledpanel_postion_rgb": "[ICON]LED パネル[ID] を x: [X] y: [Y] に赤 [R] 緑 [G] 青 [B] で点灯する",
    "codey_neuron_turn_off_ledpanel_position": "[ICON]LEDパネル [ID] をX: [X] y: [Y] で消灯する",
    "codey_neuron_turn_off_ledpanel": "[ICON]LEDパネル[ID] を消灯する",
    "codey_neuron_set_ledstrip_mode": "[ICON] LED ストリップ [ID][STRIP] を点灯する",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_0": "赤",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_1": "オレンジ",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_2": "黄",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_3": "緑",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_4": "シアン",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_5": "青",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_6": "紫",
    "codey_neuron_set_ledstrip_with_color": "[ICON] LED ストリップ [ID] すべて[POSITION] のカラーを[COLORLIST] で 点灯する",
    "codey_neuron_set_ledstrip_with_rgb": "[ICON] LEDストリップ [ID] の[POSITION] を赤 [R] 緑[G] 青 [B] で点灯する",
    "CODEY_NEURON_PLAY_TONE_TONE_0": "C7",
    "CODEY_NEURON_PLAY_TONE_TONE_1": "C2",
    "CODEY_NEURON_PLAY_TONE_TONE_2": "D2",
    "CODEY_NEURON_PLAY_TONE_TONE_3": "E2",
    "CODEY_NEURON_PLAY_TONE_TONE_4": "F2",
    "CODEY_NEURON_PLAY_TONE_TONE_5": "G2",
    "CODEY_NEURON_PLAY_TONE_TONE_6": "A2",
    "CODEY_NEURON_PLAY_TONE_TONE_7": "B2",
    "CODEY_NEURON_PLAY_TONE_TONE_8": "C3",
    "CODEY_NEURON_PLAY_TONE_TONE_9": "D3",
    "CODEY_NEURON_PLAY_TONE_TONE_10": "E3",
    "CODEY_NEURON_PLAY_TONE_TONE_11": "F3",
    "CODEY_NEURON_PLAY_TONE_TONE_12": "G3",
    "CODEY_NEURON_PLAY_TONE_TONE_13": "A3",
    "CODEY_NEURON_PLAY_TONE_TONE_14": "B3",
    "CODEY_NEURON_PLAY_TONE_TONE_15": "C4",
    "CODEY_NEURON_PLAY_TONE_TONE_16": "D4",
    "CODEY_NEURON_PLAY_TONE_TONE_17": "E4",
    "CODEY_NEURON_PLAY_TONE_TONE_18": "F4",
    "CODEY_NEURON_PLAY_TONE_TONE_19": "G4",
    "CODEY_NEURON_PLAY_TONE_TONE_20": "A4",
    "CODEY_NEURON_PLAY_TONE_TONE_21": "B4",
    "CODEY_NEURON_PLAY_TONE_TONE_22": "C5",
    "CODEY_NEURON_PLAY_TONE_TONE_23": "D5",
    "CODEY_NEURON_PLAY_TONE_TONE_24": "E5",
    "CODEY_NEURON_PLAY_TONE_TONE_25": "F5",
    "CODEY_NEURON_PLAY_TONE_TONE_26": "G5",
    "CODEY_NEURON_PLAY_TONE_TONE_27": "A5",
    "CODEY_NEURON_PLAY_TONE_TONE_28": "B5",
    "CODEY_NEURON_PLAY_TONE_TONE_29": "C6",
    "CODEY_NEURON_PLAY_TONE_TONE_30": "D6",
    "CODEY_NEURON_PLAY_TONE_TONE_31": "E6",
    "CODEY_NEURON_PLAY_TONE_TONE_32": "F6",
    "CODEY_NEURON_PLAY_TONE_TONE_33": "G6",
    "CODEY_NEURON_PLAY_TONE_TONE_34": "A6",
    "CODEY_NEURON_PLAY_TONE_TONE_35": "B6",
    "CODEY_NEURON_PLAY_TONE_TONE_36": "D7",
    "CODEY_NEURON_PLAY_TONE_TONE_37": "E7",
    "CODEY_NEURON_PLAY_TONE_TONE_38": "F7",
    "CODEY_NEURON_PLAY_TONE_TONE_39": "G7",
    "CODEY_NEURON_PLAY_TONE_TONE_40": "A7",
    "CODEY_NEURON_PLAY_TONE_TONE_41": "B7",
    "CODEY_NEURON_PLAY_TONE_TONE_42": "C8",
    "CODEY_NEURON_PLAY_TONE_TONE_43": "D8",
    "codey_neuron_play_tone": "[ICON] ブザー[ID] が[TONE] の音を[BEAT] 拍再生する",
    "codey_neuron_play_hz": "[ICON] [HZ] Hzの周波数でブザー [ID] の音を[TIME] 秒鳴らす",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_0": "全て",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_1": "スロット1",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_2": "スロット2",
    "codey_neuron_run_dcmotor_with_speed_time": "[ICON] DCモーター [ID] [SLOT] が [POWER]% の速さで [TIME] 秒回る",
    "codey_neuron_run_dcmotor_with_speed": "[ICON] DC モーター [ID] [SLOT] を[POWER] %の速さで回転する",
    "codey_neuron_run_dcmotor_wheel": "[ICON] DCモーター [ID] のスロット1は [POWER_LEFT]%の速さで回転して、スロット2は [POWER_RIGHT]%の速さで回転する",
    "codey_neuron_run_servo": "[ICON] サーボモーター[ID] [SLOT] を[ANGLE] 度まで回転する",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_0": "青色",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_1": "黄",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_2": "赤色",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_3": "緑色",
    "codey_neuron_event_touch_color": "[ICON]ファニータッチ[ID] スロットが[COLOR] に触れた",
    "codey_neuron_detect_ultrasonic": "[ICON] 超音波センサー [ID] の値 (cm)",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_0": "前",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_1": "後ろ",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_2": "左",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_3": "右",
    "codey_neuron_event_tilt": "[ICON] ジャイロセンサー[ID] が[DIRECTION] に傾いている",
    "codey_neuron_event_shaked": "[ICON] ジャイロセンサー[ID] が揺れている",
    "CODEY_NEURON_DETECT_GYRO_ANGLE_COORDINATE_0": "ロール角度",
    "CODEY_NEURON_DETECT_GYRO_ANGLE_COORDINATE_1": "ピッチング角度",
    "codey_neuron_detect_gyro_angle": "[ICON] ジャイロセンサー[ID][COORDINATE] 角度（°）",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_0": "x",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_1": "y",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_2": "z",
    "codey_neuron_detect_gyro_speed": "[ICON] ジャイロ センサー [ID] [COORDINATE] の加速度 m/s ²",
    "codey_neuron_event_pir": "[ICON] PIR センサー[ID] が人を検出する",
    "codey_neuron_detect_humidity": "[ICON] 土壌水分センサー [ID] 値",
    "codey_neuron_button": "[ICON] ボタン[ID] が押された",
    "codey_neuron_rgb_led_show_with_time": "[ICON] RGB LED[ID] を[color_1] 色で[time] 秒点灯する",
    "codey_neuron_rgb_led_show": "[ICON] RGB LED[ID] を[color_1] 色で点灯する",
    "codey_neuron_rgb_led_set_rgb": "[ICON] RGB LED [ID] を赤[R] 緑[G] 青[B] にする",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_0": "正常",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_1": "眠い",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_2": "悲しい",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_3": "楽しい",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_4": "Goggle",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_5": "怒る",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_6": "凝視",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_7": "斜視",
    "codey_neuron_display_show_image_with_time": "[ICON] ディスプレイ[ID] に感情 [emoji] を[time] 秒表示する",
    "codey_neuron_display_show_image": "[ICON] ディスプレイ[ID] に感情 [emoji] を表示する",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_0": "空気",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_1": "チェック マーク",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_2": "雲",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_3": "心",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_4": "月",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_5": "雨",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_6": "円形リング",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_7": "定規",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_8": "ラーニング",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_9": "笑顔",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_10": "雪",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_11": "太陽",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_12": "温度計",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_13": "水滴",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_14": "なし",
    "codey_neuron_display_show_string": "[ICON] ディスプレイ[ID] にアイコン[icon] とテキスト[text] を表示する",
    "codey_neuron_display_show_string_in_mutiple_lines": "[ICON] ディスプレイ [ID] にアイコン [icon] とテキスト [text] を上の行に、アイコン [icon2] とテキスト [text2] を下の行に表示する",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_0": "スロット1",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_1": "スロット2",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_2": "スロット3",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_3": "スロット4",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_4": "両方のセンサーで検知する",
    "codey_neuron_el_wire_on": "[ICON] ELワイヤ [ID] の [output] を点灯する",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_0": "スロット1",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_1": "スロット2",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_2": "スロット3",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_3": "スロット4",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_4": "両方のセンサーで検知する",
    "codey_neuron_el_wire_off": "[ICON] ELワイヤ [ID] の[output] を消灯する",
    "codey_neuron_knob_get_value": "[ICON] ノブ[ID] の値",
    "codey_neuron_joystic_get_dir": "[ICON] ジョイスティック [ID] が[direction] 方向に揺れている",
    "CODEY_NEURON_JOYSTIC_GET_VALUE_AXIS_0": "x",
    "CODEY_NEURON_JOYSTIC_GET_VALUE_AXIS_1": "y",
    "codey_neuron_joystic_get_value": "[ICON] ジョイスティック [ID] [axis] の値",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_0": "左",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_1": "右",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_2": "両方のセンサーで検知する",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_3": "なし",
    "codey_neuron_dual_ir_is_active": "[ICON] デュアルIR検出器 [ID] [option] がトリガーされた",
    "codey_neuron_light_sensor_get_value": "[ICON] 光センサー [ID] の値",
    "codey_neuron_temperature_sensor_get_celsius": "[ICON] 温度センサー [ID] の値 (℃)",
    "codey_neuron_humiture_sensor_get_humidity": "[ICON] 温湿度センサー [ID] の湿度 (%)",
    "codey_neuron_humiture_sensor_get_celsius": "[ICON]温湿度センサー [ID]の温度 (℃)",
    "codey_neuron_humiture_sensor_get_fahrenheit": "[ICON] 温湿度センサー [ID] の温度(°F)",
    "codey_neuron_ranging_sensor_get_distance": "[ICON] 測距センサー[ID] の距離 (cm)",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_0": "赤",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_1": "緑",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_2": "青",
    "codey_neuron_color_sensor_get_value": "[ICON]カラーセンサー [ID] [color] の値",
    "CATEGORY_NEURON": "Neuron"
};