export default {
    "codeyneuron": "Neuron",
    "extensionName": "Neuron",
    "extensionDescription": "Daha ilgi çekici uygulamalar oluşturmak için Codey'i Neuron'a bağlayın!",
    "codey_neuron_set_ledpanel_with_time": "[ICON] LED panel [ID] resim göster [PANEL] de [TIME] saniye",
    "codey_neuron_set_ledpanel_face": "[ICON] LED panel [ID] resim göster [PANEL]",
    "codey_neuron_set_ledpanel_text": "[ICON] LED panel [ID] yazı göster [TEXT]",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_0": "kırmızı",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_1": "turuncu",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_2": "sarı",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_3": "yeşil",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_4": "camgöbeği",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_5": "mavi",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_6": "mor",
    "codey_neuron_set_ledpanel_position_color": "[ICON] LED panel [ID] ışıkları yak x: [X] Y: [Y] [COLOR] renkte",
    "codey_neuron_set_ledpanel_postion_rgb": "[ICON] LED panel [ID] ışıkları yak x: [X] y: [Y] kırmızı [R] yeşil [G] mavi [B] renkte",
    "codey_neuron_turn_off_ledpanel_position": "[ICON] LED panel  [ID] ışıkları kapat x: [X] Y: [Y]",
    "codey_neuron_turn_off_ledpanel": "[ICON] LED panel [ID] ışıkları söndür",
    "codey_neuron_set_ledstrip_mode": "[ICON] LED şerit [ID] ışıkları yak [STRIP]",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_0": "kırmızı",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_1": "turuncu",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_2": "sarı",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_3": "yeşil",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_4": "camgöbeği",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_5": "mavi",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_6": "mor",
    "codey_neuron_set_ledstrip_with_color": "[ICON] LED şerit [ID] ışıkları yak [POSITION] [COLORLIST] renkte",
    "codey_neuron_set_ledstrip_with_rgb": "[ICON] LED şerit [ID] ışıkları yak [POSITION] kırmızı [R] yeşil [G] mavi [B] renkte",
    "CODEY_NEURON_PLAY_TONE_TONE_0": "C7",
    "CODEY_NEURON_PLAY_TONE_TONE_1": "C2",
    "CODEY_NEURON_PLAY_TONE_TONE_2": "D2",
    "CODEY_NEURON_PLAY_TONE_TONE_3": "E2",
    "CODEY_NEURON_PLAY_TONE_TONE_4": "F2",
    "CODEY_NEURON_PLAY_TONE_TONE_5": "G2",
    "CODEY_NEURON_PLAY_TONE_TONE_6": "A2",
    "CODEY_NEURON_PLAY_TONE_TONE_7": "B2",
    "CODEY_NEURON_PLAY_TONE_TONE_8": "C3",
    "CODEY_NEURON_PLAY_TONE_TONE_9": "D3",
    "CODEY_NEURON_PLAY_TONE_TONE_10": "E3",
    "CODEY_NEURON_PLAY_TONE_TONE_11": "F3",
    "CODEY_NEURON_PLAY_TONE_TONE_12": "G3",
    "CODEY_NEURON_PLAY_TONE_TONE_13": "A3",
    "CODEY_NEURON_PLAY_TONE_TONE_14": "B3",
    "CODEY_NEURON_PLAY_TONE_TONE_15": "C4",
    "CODEY_NEURON_PLAY_TONE_TONE_16": "D4",
    "CODEY_NEURON_PLAY_TONE_TONE_17": "E4",
    "CODEY_NEURON_PLAY_TONE_TONE_18": "F4",
    "CODEY_NEURON_PLAY_TONE_TONE_19": "G4",
    "CODEY_NEURON_PLAY_TONE_TONE_20": "A4",
    "CODEY_NEURON_PLAY_TONE_TONE_21": "B4",
    "CODEY_NEURON_PLAY_TONE_TONE_22": "C5",
    "CODEY_NEURON_PLAY_TONE_TONE_23": "D5",
    "CODEY_NEURON_PLAY_TONE_TONE_24": "E5",
    "CODEY_NEURON_PLAY_TONE_TONE_25": "F5",
    "CODEY_NEURON_PLAY_TONE_TONE_26": "G5",
    "CODEY_NEURON_PLAY_TONE_TONE_27": "A5",
    "CODEY_NEURON_PLAY_TONE_TONE_28": "B5",
    "CODEY_NEURON_PLAY_TONE_TONE_29": "C6",
    "CODEY_NEURON_PLAY_TONE_TONE_30": "D6",
    "CODEY_NEURON_PLAY_TONE_TONE_31": "E6",
    "CODEY_NEURON_PLAY_TONE_TONE_32": "F6",
    "CODEY_NEURON_PLAY_TONE_TONE_33": "G6",
    "CODEY_NEURON_PLAY_TONE_TONE_34": "A6",
    "CODEY_NEURON_PLAY_TONE_TONE_35": "B6",
    "CODEY_NEURON_PLAY_TONE_TONE_36": "D7",
    "CODEY_NEURON_PLAY_TONE_TONE_37": "E7",
    "CODEY_NEURON_PLAY_TONE_TONE_38": "F7",
    "CODEY_NEURON_PLAY_TONE_TONE_39": "G7",
    "CODEY_NEURON_PLAY_TONE_TONE_40": "A7",
    "CODEY_NEURON_PLAY_TONE_TONE_41": "B7",
    "CODEY_NEURON_PLAY_TONE_TONE_42": "C8",
    "CODEY_NEURON_PLAY_TONE_TONE_43": "D8",
    "codey_neuron_play_tone": "[ICON] vızırtı [ID] [TONE] notasını çal [BEAT] vuruş",
    "codey_neuron_play_hz": "[ICON] vızırtı [ID] [HZ] frekansını çal [TIME] saniye",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_0": "hepsi",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_1": "yuva1",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_2": "yuva2",
    "codey_neuron_run_dcmotor_with_speed_time": "[ICON] DC Motor [ID] [SLOT] dönsün [POWER]% güçte [TIME] saniye",
    "codey_neuron_run_dcmotor_with_speed": "[ICON] DC motor [ID] [SLOT] dönsün [POWER]% güçte",
    "codey_neuron_run_dcmotor_wheel": "[ICON] DC Motor [ID] yuva1 [POWER_LEFT]% güçte dönsün, yuva2 [POWER_RIGHT]% güçte dönsün",
    "codey_neuron_run_servo": "[ICON] servo [ID] [SLOT] dönsün [ANGLE] derece",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_0": "mavi",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_1": "sarı",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_2": "kırmızı",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_3": "yeşil",
    "codey_neuron_event_touch_color": "[ICON] Komik Dokunuş [ID] yuva [COLOR] dokunuldu mu?",
    "codey_neuron_detect_ultrasonic": "[ICON] ultrasonik algılayıcı [ID] mesafe (cm)",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_0": "ileri",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_1": "geri",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_2": "sola doğru",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_3": "sağa doğru",
    "codey_neuron_event_tilt": "[ICON] [ID] cayro algılayıcı [DIRECTION] eğilmiş?",
    "codey_neuron_event_shaked": "[ICON] cayro algılayıcı [ID] sallanıyor?",
    "CODEY_NEURON_DETECT_GYRO_ANGLE_COORDINATE_0": "dönüş açısı",
    "CODEY_NEURON_DETECT_GYRO_ANGLE_COORDINATE_1": "eğim açısı",
    "codey_neuron_detect_gyro_angle": "[ICON] cayroskop [ID] [COORDINATE] açı(°)",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_0": "x",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_1": "y",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_2": "z",
    "codey_neuron_detect_gyro_speed": "[ICON] [ID] cayro algılayıcı [COORDINATE] hızlanma m/s²",
    "codey_neuron_event_pir": "[ICON] PIR algılayıcı [ID] insan algıladı?",
    "codey_neuron_detect_humidity": "[ICON] toprak nem algılayıcı [ID] nem",
    "codey_neuron_button": "[ICON] düğme [ID] basıldı？",
    "codey_neuron_rgb_led_show_with_time": "[ICON] RGB LED [ID] ışığını yak [color_1] renkte [time] saniye",
    "codey_neuron_rgb_led_show": "[ICON] RGB LED [ID] ışığını yak [color_1] renkte",
    "codey_neuron_rgb_led_set_rgb": "[ICON] RGB LED [ID] ışığını kırmızı [R] yeşil [G] mavi [B] yap",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_0": "normal",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_1": "uykulu",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_2": "üzgün",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_3": "mutlu",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_4": "gözlüklü",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_5": "kızgın",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_6": "dik dik",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_7": "şaşı",
    "codey_neuron_display_show_image_with_time": "[ICON] ekran [ID] duygu göster [emoji] [time] saniye",
    "codey_neuron_display_show_image": "[ICON] [ID] ekranda [emoji] ifadesini göster",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_0": "hava",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_1": "onay işaretleri",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_2": "bulut veri",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_3": "kalp",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_4": "ay",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_5": "yağmur",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_6": "yüzük",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_7": "cetvel",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_8": "koşu",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_9": "gülücük",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_10": "kar",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_11": "güneş",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_12": "termometre",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_13": "su damlası",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_14": "hiçbiri",
    "codey_neuron_display_show_string": "[ICON] [ID] ekranda [icon] simgesini [text] yazısını göster",
    "codey_neuron_display_show_string_in_mutiple_lines": "[ICON] [ID] ekranında üst satırda [icon] simgesini ve [text] yazısını göster, alt satırda [icon2] simgesini ve [text2] yazısını göster",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_0": "yuva1",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_1": "yuva2",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_2": "yuva3",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_3": "yuva4",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_4": "hepsi",
    "codey_neuron_el_wire_on": "[ICON]  [ID] EL [output] ışıkları yak",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_0": "yuva1",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_1": "yuva2",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_2": "yuva3",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_3": "yuva4",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_4": "hepsi",
    "codey_neuron_el_wire_off": "[ICON] EL [ID] [output] ışıkları kapat",
    "codey_neuron_knob_get_value": "[ICON] topuz [ID] değer",
    "codey_neuron_joystic_get_dir": "[ICON] [ID] oyun kolu [direction] sallanıyor?",
    "CODEY_NEURON_JOYSTIC_GET_VALUE_AXIS_0": "x",
    "CODEY_NEURON_JOYSTIC_GET_VALUE_AXIS_1": "y",
    "codey_neuron_joystic_get_value": "[ICON] oyun kolu [ID] [axis] değer",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_0": "sol",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_1": "sağ",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_2": "hepsi",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_3": "hiçbiri",
    "codey_neuron_dual_ir_is_active": "[ICON] [ID] çift kızılötesi algılayıcı [option] tetiklendi?",
    "codey_neuron_light_sensor_get_value": "[ICON] ışık algılayıcı [ID] ışık şiddeti",
    "codey_neuron_temperature_sensor_get_celsius": "[ICON] sıcaklık algılayıcı [ID]  sıcaklık (℃)",
    "codey_neuron_humiture_sensor_get_humidity": "[ICON] nem algılayıcı [ID] nem (%)",
    "codey_neuron_humiture_sensor_get_celsius": "[ICON] nem algılayıcı [ID] sıcaklık (℃)",
    "codey_neuron_humiture_sensor_get_fahrenheit": "[ICON] nem algılayıcı [ID] sıcaklık (°F)",
    "codey_neuron_ranging_sensor_get_distance": "[ICON] mesafe algılayıcı [ID] mesafe(cm)",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_0": "kırmızı",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_1": "yeşil",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_2": "mavi",
    "codey_neuron_color_sensor_get_value": "[ICON] [ID] renk algılayıcı [color] değer",
    "CATEGORY_NEURON": "Neuron"
};