export default {
    "codeyneuron": "神经元",
    "extensionName": "神经元",
    "extensionDescription": "小程可以连接神经元，实现更多好玩又有趣的应用~",
    "codey_neuron_set_ledpanel_with_time": "[ICON] LED面板 [ID] 显示图案 [PANEL]  持续 [TIME] 秒",
    "codey_neuron_set_ledpanel_face": "[ICON] LED面板 [ID] 显示图案 [PANEL]",
    "codey_neuron_set_ledpanel_text": "[ICON] LED面板 [ID] 显示 [TEXT]",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_0": "红色",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_1": "橙色",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_2": "黄色",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_3": "绿色",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_4": "青色",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_5": "蓝色",
    "CODEY_NEURON_SET_LEDPANEL_POSITION_COLOR_COLOR_6": "紫色",
    "codey_neuron_set_ledpanel_position_color": "[ICON] LED面板 [ID] 点亮x: [X]  y: [Y] ，颜色为 [COLOR]",
    "codey_neuron_set_ledpanel_postion_rgb": "[ICON] LED面板 [ID] 点亮x: [X]  y: [Y] ，颜色为红 [R] 绿 [G]  蓝 [B]",
    "codey_neuron_turn_off_ledpanel_position": "[ICON] LED面板 [ID] 熄灭x: [X]  y: [Y]",
    "codey_neuron_turn_off_ledpanel": "[ICON] LED面板 [ID] 熄灭",
    "codey_neuron_set_ledstrip_mode": "[ICON] 灯带 [ID] 亮起 [STRIP]",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_0": "红色",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_1": "橙色",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_2": "黄色",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_3": "绿色",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_4": "青色",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_5": "蓝色",
    "CODEY_NEURON_SET_LEDSTRIP_WITH_COLOR_COLORLIST_6": "紫色",
    "codey_neuron_set_ledstrip_with_color": "[ICON] 灯带 [ID] 亮起 [POSITION] 灯，颜色为 [COLORLIST]",
    "codey_neuron_set_ledstrip_with_rgb": "[ICON] 灯带 [ID] 亮起 [POSITION] 灯，颜色为红 [R] 绿 [G] 蓝 [B]",
    "CODEY_NEURON_PLAY_TONE_TONE_0": "C7",
    "CODEY_NEURON_PLAY_TONE_TONE_1": "C2",
    "CODEY_NEURON_PLAY_TONE_TONE_2": "D2",
    "CODEY_NEURON_PLAY_TONE_TONE_3": "E2",
    "CODEY_NEURON_PLAY_TONE_TONE_4": "F2",
    "CODEY_NEURON_PLAY_TONE_TONE_5": "G2",
    "CODEY_NEURON_PLAY_TONE_TONE_6": "A2",
    "CODEY_NEURON_PLAY_TONE_TONE_7": "B2",
    "CODEY_NEURON_PLAY_TONE_TONE_8": "C3",
    "CODEY_NEURON_PLAY_TONE_TONE_9": "D3",
    "CODEY_NEURON_PLAY_TONE_TONE_10": "E3",
    "CODEY_NEURON_PLAY_TONE_TONE_11": "F3",
    "CODEY_NEURON_PLAY_TONE_TONE_12": "G3",
    "CODEY_NEURON_PLAY_TONE_TONE_13": "A3",
    "CODEY_NEURON_PLAY_TONE_TONE_14": "B3",
    "CODEY_NEURON_PLAY_TONE_TONE_15": "C4",
    "CODEY_NEURON_PLAY_TONE_TONE_16": "D4",
    "CODEY_NEURON_PLAY_TONE_TONE_17": "E4",
    "CODEY_NEURON_PLAY_TONE_TONE_18": "F4",
    "CODEY_NEURON_PLAY_TONE_TONE_19": "G4",
    "CODEY_NEURON_PLAY_TONE_TONE_20": "A4",
    "CODEY_NEURON_PLAY_TONE_TONE_21": "B4",
    "CODEY_NEURON_PLAY_TONE_TONE_22": "C5",
    "CODEY_NEURON_PLAY_TONE_TONE_23": "D5",
    "CODEY_NEURON_PLAY_TONE_TONE_24": "E5",
    "CODEY_NEURON_PLAY_TONE_TONE_25": "F5",
    "CODEY_NEURON_PLAY_TONE_TONE_26": "G5",
    "CODEY_NEURON_PLAY_TONE_TONE_27": "A5",
    "CODEY_NEURON_PLAY_TONE_TONE_28": "B5",
    "CODEY_NEURON_PLAY_TONE_TONE_29": "C6",
    "CODEY_NEURON_PLAY_TONE_TONE_30": "D6",
    "CODEY_NEURON_PLAY_TONE_TONE_31": "E6",
    "CODEY_NEURON_PLAY_TONE_TONE_32": "F6",
    "CODEY_NEURON_PLAY_TONE_TONE_33": "G6",
    "CODEY_NEURON_PLAY_TONE_TONE_34": "A6",
    "CODEY_NEURON_PLAY_TONE_TONE_35": "B6",
    "CODEY_NEURON_PLAY_TONE_TONE_36": "D7",
    "CODEY_NEURON_PLAY_TONE_TONE_37": "E7",
    "CODEY_NEURON_PLAY_TONE_TONE_38": "F7",
    "CODEY_NEURON_PLAY_TONE_TONE_39": "G7",
    "CODEY_NEURON_PLAY_TONE_TONE_40": "A7",
    "CODEY_NEURON_PLAY_TONE_TONE_41": "B7",
    "CODEY_NEURON_PLAY_TONE_TONE_42": "C8",
    "CODEY_NEURON_PLAY_TONE_TONE_43": "D8",
    "codey_neuron_play_tone": "[ICON] 蜂鸣器 [ID] 播放音符 [TONE] 以 [BEAT] 拍",
    "codey_neuron_play_hz": "[ICON] 蜂鸣器 [ID] 播放声音以频率 [HZ] ， 持续 [TIME]  秒",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_0": "全部",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_1": "插头1",
    "CODEY_NEURON_RUN_DCMOTOR_WITH_SPEED_TIME_SLOT_2": "插头2",
    "codey_neuron_run_dcmotor_with_speed_time": "[ICON] 直流电机 [ID] [SLOT] 转动以动力 [POWER] %，持续 [TIME] 秒",
    "codey_neuron_run_dcmotor_with_speed": "[ICON] 直流电机 [ID] [SLOT] 转动以动力 [POWER] %",
    "codey_neuron_run_dcmotor_wheel": "[ICON] 直流电机 [ID] 插头1转动以动力 [POWER_LEFT] %，插头2转动以动力 [POWER_RIGHT] %",
    "codey_neuron_run_servo": "[ICON] 舵机 [ID] [SLOT] 转动至 [ANGLE] 度",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_0": "蓝",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_1": "黄",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_2": "红",
    "CODEY_NEURON_EVENT_TOUCH_COLOR_COLOR_3": "绿",
    "codey_neuron_event_touch_color": "[ICON] 触摸开关 [ID] 插头[COLOR] 被触摸？",
    "codey_neuron_detect_ultrasonic": "[ICON] 超声波传感器 [ID] 距离cm",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_0": "向前",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_1": "向后",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_2": "向左",
    "CODEY_NEURON_EVENT_TILT_DIRECTION_3": "向右",
    "codey_neuron_event_tilt": "[ICON] 陀螺仪传感器 [ID] 感受到 [DIRECTION] 倾斜？",
    "codey_neuron_event_shaked": "[ICON] 陀螺仪传感器 [ID] 感受到摇晃？",
    "CODEY_NEURON_DETECT_GYRO_ANGLE_COORDINATE_0": "滚转角",
    "CODEY_NEURON_DETECT_GYRO_ANGLE_COORDINATE_1": "俯仰角",
    "codey_neuron_detect_gyro_angle": "[ICON] 陀螺仪传感器 [ID] [COORDINATE] 角度°",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_0": "x",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_1": "y",
    "CODEY_NEURON_DETECT_GYRO_SPEED_COORDINATE_2": "z",
    "codey_neuron_detect_gyro_speed": "[ICON] 陀螺仪传感器 [ID] [COORDINATE] 轴加速度m/s²",
    "codey_neuron_event_pir": "[ICON] 人体红外传感器 [ID] 检测到人？",
    "codey_neuron_detect_humidity": "[ICON] 土壤湿度传感器 [ID] 湿度",
    "codey_neuron_button": "[ICON] 按钮 [ID] 被按下？",
    "codey_neuron_rgb_led_show_with_time": "[ICON]  RGB灯 [ID]  亮起 [color_1] ，持续 [time]  秒",
    "codey_neuron_rgb_led_show": "[ICON]  RGB灯 [ID]  亮起 [color_1] ",
    "codey_neuron_rgb_led_set_rgb": "[ICON] 设置RGB灯 [ID] 的RGB值为 红 [R]  绿 [G] 蓝 [B] ",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_0": "普通",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_1": "困倦",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_2": "悲伤",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_3": "高兴",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_4": "瞪眼",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_5": "生气",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_6": "盯着",
    "CODEY_NEURON_DISPLAY_SHOW_IMAGE_WITH_TIME_EMOJI_7": "眯眼",
    "codey_neuron_display_show_image_with_time": "[ICON] 显示屏 [ID] 的显示表情为 [emoji] 持续 [time] 秒",
    "codey_neuron_display_show_image": "[ICON] 显示屏 [ID] 的显示表情为 [emoji] ",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_0": "气态",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_1": "复选标记",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_2": "云",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_3": "心",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_4": "月亮",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_5": "雨",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_6": "圆环",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_7": "直尺",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_8": "赛跑",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_9": "微笑",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_10": "雪",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_11": "太阳",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_12": "温度计",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_13": "水滴",
    "CODEY_NEURON_DISPLAY_SHOW_STRING_ICON_14": "无",
    "codey_neuron_display_show_string": "[ICON] 显示屏 [ID] 的显示图标 [icon] 文字 [text] ",
    "codey_neuron_display_show_string_in_mutiple_lines": "[ICON] 在显示屏 [ID] 上行显示图标 [icon] 文字 [text] ，下行显示 [icon2]  文字 [text2] ",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_0": "插头1",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_1": "插头2",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_2": "插头3",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_3": "插头4",
    "CODEY_NEURON_EL_WIRE_ON_OUTPUT_4": " 全部",
    "codey_neuron_el_wire_on": "[ICON] 冷光线 [ID] 点亮  [output]",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_0": "插头1",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_1": "插头2",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_2": "插头3",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_3": "插头4",
    "CODEY_NEURON_EL_WIRE_OFF_OUTPUT_4": "全部",
    "codey_neuron_el_wire_off": "[ICON] 冷光线 [ID] 熄灭 [output]",
    "codey_neuron_knob_get_value": "[ICON] 旋钮 [ID] 数值",
    "codey_neuron_joystic_get_dir": "[ICON] 摇杆 [ID] [direction] 摇动？",
    "CODEY_NEURON_JOYSTIC_GET_VALUE_AXIS_0": " x",
    "CODEY_NEURON_JOYSTIC_GET_VALUE_AXIS_1": "y",
    "codey_neuron_joystic_get_value": "[ICON] 摇杆 [ID] [axis] 轴读数",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_0": "左",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_1": "右",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_2": "全部",
    "CODEY_NEURON_DUAL_IR_IS_ACTIVE_OPTION_3": "没有",
    "codey_neuron_dual_ir_is_active": "[ICON] 双路红外开关 [ID] [option] 被触发？",
    "codey_neuron_light_sensor_get_value": "[ICON] 光线传感器 [ID]  光线强度",
    "codey_neuron_temperature_sensor_get_celsius": "[ICON] 温度传感器 [ID]  温度 (℃)",
    "codey_neuron_humiture_sensor_get_humidity": "[ICON] 温湿度传感器 [ID] 湿度 (%)",
    "codey_neuron_humiture_sensor_get_celsius": "[ICON] 温湿度传感器 [ID]  温度 (℃)",
    "codey_neuron_humiture_sensor_get_fahrenheit": "[ICON] 温湿度传感器 [ID]  温度 (°F)",
    "codey_neuron_ranging_sensor_get_distance": "[ICON] 测距传感器 [ID] 距离 (cm)",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_0": "红色",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_1": "绿色",
    "CODEY_NEURON_COLOR_SENSOR_GET_VALUE_COLOR_2": "蓝色",
    "codey_neuron_color_sensor_get_value": "[ICON] 颜色识别传感器 [ID] [color] 色值",
    "CATEGORY_NEURON": "神经元"
};