export default {
    "mbuild_science_sensor": "科学传感器",
    "extensionName": "科学传感器",
    "extensionDescription": "集成多个传感器元器件的多功能模块",
    "MBUILD_MULTIPLE_SENSOR_GET_PIR_STA_INDEX_0": "1",
    "MBUILD_MULTIPLE_SENSOR_GET_PIR_STA_INDEX_1": "2",
    "MBUILD_MULTIPLE_SENSOR_GET_PIR_STA_INDEX_2": "3",
    "MBUILD_MULTIPLE_SENSOR_GET_PIR_STA_INDEX_3": "4",
    "MBUILD_MULTIPLE_SENSOR_GET_PIR_STA_INDEX_4": "5",
    "MBUILD_MULTIPLE_SENSOR_GET_PIR_STA_INDEX_5": "6",
    "MBUILD_MULTIPLE_SENSOR_GET_PIR_STA_INDEX_6": "7",
    "MBUILD_MULTIPLE_SENSOR_GET_PIR_STA_INDEX_7": "8",
    "mbuild_multiple_sensor_get_pir_sta": "科学传感器 [index] 检测到人体运动？",
    "MBUILD_MULTIPLE_SENSOR_SET_HEARTRATE_SWITCH_CONDUCTION_0": "开启",
    "MBUILD_MULTIPLE_SENSOR_SET_HEARTRATE_SWITCH_CONDUCTION_1": "关闭",
    "mbuild_multiple_sensor_set_heartrate_switch": "科学传感器 [index]  [conduction] 心率检测 ",
    "mbuild_multiple_sensor_get_check_result": "科学传感器 [index] 心率检测完成？",
    "mbuild_multiple_sensor_get_heartrate": "科学传感器 [index] 检测到的每分钟心率 (BPM)",
    "mbuild_multiple_sensor_get_soil_humidity": "科学传感器 [index] 检测到的土壤湿度",
    "mbuild_multiple_sensor_get_soil_resistance_value": "科学传感器 [index] 土壤湿度传感器极耳间的电阻值 (kΩ)",
    "mbuild_multiple_sensor_get_soil_conduction": "科学传感器 [index] 土壤湿度传感器极耳被导通？",
    "mbuild_multiple_sensor_get_touch_conduction": "科学传感器 [index] 触点被触摸？",
    "mbuild_multiple_sensor_get_touch_resistance_value": "科学传感器 [index] 触点检测到的电阻值 (kΩ) ",
    "mbuild_multiple_sensor_get_temperature": "科学传感器 [index] 检测到的空气温度 ℃",
    "mbuild_multiple_sensor_get_humidity": "科学传感器 [index] 检测到的空气湿度 (%)",
    "mbuild_multiple_sensor_get_atmospheric_pressure": "科学传感器 [index] 检测到的大气压强 (Pa)",
    "mbuild_multiple_sensor_get_atmospheric_altitude": "科学传感器 [index] 预估的海拔高度 (m)",
    "MBUILD_MULTIPLE_SENSOR_SET_MQ2_THRESHOLD_AND_SWITCH_SENSITIVITY_0": "(0.1)低",
    "MBUILD_MULTIPLE_SENSOR_SET_MQ2_THRESHOLD_AND_SWITCH_SENSITIVITY_1": "(0.2)",
    "MBUILD_MULTIPLE_SENSOR_SET_MQ2_THRESHOLD_AND_SWITCH_SENSITIVITY_2": "(0.3)",
    "MBUILD_MULTIPLE_SENSOR_SET_MQ2_THRESHOLD_AND_SWITCH_SENSITIVITY_3": "(0.4)",
    "MBUILD_MULTIPLE_SENSOR_SET_MQ2_THRESHOLD_AND_SWITCH_SENSITIVITY_4": "(0.5)",
    "MBUILD_MULTIPLE_SENSOR_SET_MQ2_THRESHOLD_AND_SWITCH_SENSITIVITY_5": "(0.6)",
    "MBUILD_MULTIPLE_SENSOR_SET_MQ2_THRESHOLD_AND_SWITCH_SENSITIVITY_6": "(0.7)",
    "MBUILD_MULTIPLE_SENSOR_SET_MQ2_THRESHOLD_AND_SWITCH_SENSITIVITY_7": "(0.8)",
    "MBUILD_MULTIPLE_SENSOR_SET_MQ2_THRESHOLD_AND_SWITCH_SENSITIVITY_8": "(0.9)",
    "MBUILD_MULTIPLE_SENSOR_SET_MQ2_THRESHOLD_AND_SWITCH_SENSITIVITY_9": "(1.0)高",
    "MBUILD_MULTIPLE_SENSOR_SET_MQ2_THRESHOLD_AND_SWITCH_CONDUCTION_0": "打开",
    "MBUILD_MULTIPLE_SENSOR_SET_MQ2_THRESHOLD_AND_SWITCH_CONDUCTION_1": "关闭",
    "mbuild_multiple_sensor_set_mq2_threshold_and_switch": "科学传感器 [index]  在 [sensitivity] 灵敏度下 [conduction] MQ2 传感器",
    "mbuild_multiple_sensor_get_mq2_value": "科学传感器 [index] 检测到可燃性气体值",
    "mbuild_multiple_sensor_get_mq2_sta": "科学传感器 [index] 检测到可燃性气体？",
    "mbuild_multiple_sensor_get_flame_value": "科学传感器 [index] 检测到火焰值",
    "mbuild_multiple_sensor_get_flame_sta": "科学传感器 [index] 检测到火焰？",
    "mbuild_multiple_sensor_compass_sum_value": "科学传感器 [index] 是否检测到磁？",
    "mbuild_multiple_sensor_get_compass_angle": "科学传感器 [index] 检测到的指南针方向(°)",
    "MBUILD_MULTIPLE_SENSOR_GET_COMPASS_AXIS_0": "x",
    "MBUILD_MULTIPLE_SENSOR_GET_COMPASS_AXIS_1": "y",
    "MBUILD_MULTIPLE_SENSOR_GET_COMPASS_AXIS_2": "z",
    "mbuild_multiple_sensor_get_compass": "科学传感器 [index] [axis] 轴方向上检测到的磁通量 (Φ/G)",
    "mbuild_multiple_sensor_set_compass_switch": "科学传感器 [index]  [conduction] 校正",
    "cate_e1586647": "科学传感器",
    "BLOCK_1560256139660": "土壤湿度传感器 [index] 湿度"
};