export default {
    "mcore_perception_gizmos": "Aparatos de detección",
    "extensionName": "Aparatos de detección",
    "extensionDescription": "En los 5 proyectos de extensión para mBot, puedes consultar varios ejemplos que te ayudarán a aprender cómo se usan los sensores y a dominar los fundamentos de la electrónica.",
    "MCORE_RUN_FAN_PORT_0": "puerto1",
    "MCORE_RUN_FAN_PORT_1": "puerto2",
    "MCORE_RUN_FAN_PORT_2": "puerto3",
    "MCORE_RUN_FAN_PORT_3": "puerto4",
    "MCORE_RUN_FAN_FAN_ROTATE_0": "hacia la derecha",
    "MCORE_RUN_FAN_FAN_ROTATE_1": "hacia la izquierda",
    "MCORE_RUN_FAN_FAN_ROTATE_2": "(no gira)",
    "mcore_run_fan": "[ICON] ventilador [PORT] gira [FAN_ROTATE]",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_0": "puerto3",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_1": "puerto4",
    "mcore_detect_external_loudness": "[ICON] volumen del sensor de sonido [PORT]",
    "MCORE_DETEC_TEMPERATURE_SLOT_0": "conexión 1",
    "MCORE_DETEC_TEMPERATURE_SLOT_1": "conexión 2",
    "mcore_detec_temperature": "[ICON] sensor de temperatura [PORT] [SLOT] grados (℃)",
    "mcore_detect_potentiometer": "[ICON] valor del potenciómetro [PORT]",
    "CATEGORY_PERCEPTION": "Aparatos"
};