export default {
    "Cognitive": "Servicios cognitivos",
    "extensionName": "Servicios cognitivos",
    "extensionDescription": "La API de servicios cognitivos permite a los usuarios añadir otras características, por ejemplo, video, voz, lenguaje y conocimiento.",
    "BEGINSPEECHTOTEXT_LANGUAGE_0": "Mandarin(simplified)",
    "BEGINSPEECHTOTEXT_LANGUAGE_1": "Cantonese(traditional)",
    "BEGINSPEECHTOTEXT_LANGUAGE_2": "Mandarin_Taiwan(traditional)",
    "BEGINSPEECHTOTEXT_LANGUAGE_3": "Inglés",
    "BEGINSPEECHTOTEXT_LANGUAGE_4": "Francés",
    "BEGINSPEECHTOTEXT_LANGUAGE_5": "Alemán",
    "BEGINSPEECHTOTEXT_LANGUAGE_6": "Italiano",
    "BEGINSPEECHTOTEXT_LANGUAGE_7": "Español",
    "BEGINSPEECHTOTEXT_LANGUAGE_8": "Japanese",
    "BEGINSPEECHTOTEXT_LANGUAGE_9": "Korean",
    "BEGINSPEECHTOTEXT_LANGUAGE_10": "Dutch",
    "BEGINSPEECHTOTEXT_LANGUAGE_11": "Polish",
    "BEGINSPEECHTOTEXT_LANGUAGE_12": "Portuguese",
    "BEGINSPEECHTOTEXT_LANGUAGE_13": "Russian",
    "BEGINSPEECHTOTEXT_LANGUAGE_14": "Turkish",
    "BEGINSPEECHTOTEXT_LANGUAGE_15": "Thai",
    "BEGINSPEECHTOTEXT_LANGUAGE_16": "Czech",
    "BEGINSPEECHTOTEXT_LANGUAGE_17": "Arabic",
    "BEGINSPEECHTOTEXT_TIMER_0": "2",
    "BEGINSPEECHTOTEXT_TIMER_1": "5",
    "BEGINSPEECHTOTEXT_TIMER_2": "10",
    "beginSpeechToText": "recognize speech in [LANGUAGE] for [TIMER] secs",
    "BLOCK_1596095748995_ISHIDESIGNAL_0": "display",
    "BLOCK_1596095748995_ISHIDESIGNAL_1": "oculta",
    "BLOCK_1596095748995": "set speech recognition result to [isHideSignal] punctuation marks",
    "speechToTextResult": "resultado del reconocimiento de voz",
    "BEGINIMAGETOTEXT_LANGUAGE_0": "Chino (Simplificado)",
    "BEGINIMAGETOTEXT_LANGUAGE_1": "Chino (Tradicional)",
    "BEGINIMAGETOTEXT_LANGUAGE_2": "Inglés",
    "BEGINIMAGETOTEXT_LANGUAGE_3": "Francés",
    "BEGINIMAGETOTEXT_LANGUAGE_4": "Alemán",
    "BEGINIMAGETOTEXT_LANGUAGE_5": "Italiano",
    "BEGINIMAGETOTEXT_LANGUAGE_6": "Español",
    "BEGINIMAGETOTEXT_LANGUAGE_7": "Japanese",
    "BEGINIMAGETOTEXT_LANGUAGE_8": "Korean",
    "BEGINIMAGETOTEXT_LANGUAGE_9": "Dutch",
    "BEGINIMAGETOTEXT_LANGUAGE_10": "Polish",
    "BEGINIMAGETOTEXT_LANGUAGE_11": "Portuguese",
    "BEGINIMAGETOTEXT_LANGUAGE_12": "Russian",
    "BEGINIMAGETOTEXT_LANGUAGE_13": "Turkish",
    "BEGINIMAGETOTEXT_LANGUAGE_14": "Czech",
    "BEGINIMAGETOTEXT_LANGUAGE_15": "Arabic",
    "beginImageToText": "recognize printed [LANGUAGE] text after [TIMER] secs",
    "beginHandwrittenToText": "recognize handwritten English text after [TIMER] secs",
    "imageToTextResult": "texto reconocido",
    "BLOCK_1566749887154_TIMER_0": "1",
    "BLOCK_1566749887154_TIMER_1": "2",
    "BLOCK_1566749887154_TIMER_2": "3",
    "BLOCK_1566749887154_TYPE_0": "Reconocimiento de imagen",
    "BLOCK_1566749887154_TYPE_1": "marca",
    "BLOCK_1566749887154_TYPE_2": "famoso",
    "BLOCK_1566749887154_TYPE_3": "monumento",
    "BLOCK_1566749887154_TYPE_4": "descripción de la imagen",
    "BLOCK_1566749887154": "recognize[TYPE] in image after [TIMER] secs",
    "BLOCK_1566750695965_TYPE_0": "Reconocimiento de imagen",
    "BLOCK_1566750695965_TYPE_1": "marca",
    "BLOCK_1566750695965_TYPE_2": "famoso",
    "BLOCK_1566750695965_TYPE_3": "monumento",
    "BLOCK_1566750695965_TYPE_4": "descripción de la imagen",
    "BLOCK_1566750695965": "resultado del reconocimiento de [TYPE]",
    "BLOCK_1590654305900": "recognize common object in image after[TIMER]secs",
    "BLOCK_1590654307561": "common object recognition result(serial)",
    "beginFaceDetection": "recognize people's age after [TIMER] secs",
    "faceDetectionResult": "resultado del reconocimiento de edad",
    "beginEmotionRecognition": "recognize emotion after [TIMER] secs",
    "EMOTIONVALUE_TYPE_0": "feliz",
    "EMOTIONVALUE_TYPE_1": "neutral",
    "EMOTIONVALUE_TYPE_2": "sorprendido",
    "EMOTIONVALUE_TYPE_3": "triste",
    "EMOTIONVALUE_TYPE_4": "ira",
    "EMOTIONVALUE_TYPE_5": "menosprecio",
    "EMOTIONVALUE_TYPE_6": "aversión",
    "EMOTIONVALUE_TYPE_7": "miedo",
    "emotionValue": "emotion[TYPE]intensity",
    "emotionType": "¿emoción es [TYPE] ?",
    "beginFaceToGender": "recognize gender after [TIMER] secs",
    "faceToGenderResult": "resultado del reconocimiento de género",
    "beginFaceToGlassType": "recognize glasses type after [TIMER] secs",
    "FACETOGLASSTYPERESULT_TYPE_0": "gafas de sol",
    "FACETOGLASSTYPERESULT_TYPE_1": "gafas de lectura",
    "FACETOGLASSTYPERESULT_TYPE_2": "gafas de natación",
    "FACETOGLASSTYPERESULT_TYPE_3": "sin gafas",
    "faceToGlassTypeResult": "vistiendo [TYPE] ?",
    "beginFaceToIsSmile": "recognize smile score after [TIMER] secs",
    "faceToIsSmileResult": "resultado reconocimiento de sonrisa",
    "beginFaceToHeadPose": "recognize head gesture after [TIMER] secs",
    "FACETOHEADPOSERESULT_TYPE_0": "rodando",
    "FACETOHEADPOSERESULT_TYPE_1": "desvío",
    "FACETOHEADPOSERESULT_TYPE_2": "tono",
    "faceToHeadPoseResult": "cabeza en ángulo [TYPE] (°) ",
    "BLOCK_1590547868949": "recognize hair color after[TIMER]secs",
    "BLOCK_1590547872342": "hair color",
    "BLOCK_1590548187016": "recognize facial blocking after [TIMER]secs",
    "BLOCK_1590548264613_TYPE_0": "forehead",
    "BLOCK_1590548264613_TYPE_1": "eyes",
    "BLOCK_1590548264613_TYPE_2": "mouth",
    "BLOCK_1590548264613": "[TYPE]being blocked?",
    "BLOCK_1590548416527_LANG_0": "Chino",
    "BLOCK_1590548416527_LANG_1": "Inglés",
    "BLOCK_1590548416527_LANG_2": "Francés",
    "BLOCK_1590548416527_LANG_3": "Alemán",
    "BLOCK_1590548416527_LANG_4": "Italiano",
    "BLOCK_1590548416527_LANG_5": "Español",
    "BLOCK_1590548416527_LANG_6": "Japanese",
    "BLOCK_1590548416527_LANG_7": "Dutch",
    "BLOCK_1590548416527_LANG_8": "Polish",
    "BLOCK_1590548416527_LANG_9": "Portuguese",
    "BLOCK_1590548416527_LANG_10": "Russian",
    "BLOCK_1590548416527_LANG_11": "Turkish",
    "BLOCK_1590548416527": "analyze [lang] text sentiment[text]",
    "BLOCK_1590548515617": "sentiment analysis result",
    "BLOCK_1590548564704": "recognize language:[text]",
    "BLOCK_1590548610070": "language recognition result",
    "cate_0969f72b": "Servicios cognitivos",
    "err_network": "Error de red. Comprueba tu conexión",
    "input_info_error": "Information input error. Please try again.",
    "err_count_limit": "Esta cuenta ha sido usada hoy más de 200 veces",
    "err_request_fail": "Error en llamada a interfaz, inténtalo otra vez",
    "err_not_login": "No has iniciado sesión, tienes que identificarte",
    "RECOGNITION.WINDOW.TITLE": "Recognition window",
    "NO_VIDEO_DEVICE": "No camera detected",
    "NO_AUDIO_DEVICE": "No microphone detected",
    "NO_PERMISSION_MEDIA_DEVICE": "Permission denied",
    "err_request_timeout": "Request timeout",
    "MEDIA_HELP_DOC": "Please check the help document"
};