export default {
    "Cognitive": "Services Cognitifs",
    "extensionName": "Services Cognitifs",
    "extensionDescription": "L’API permet aux utilisateurs d’ajouter d’autres fonctionnalités, par exemple, vidéo, parole, langage et connaissance.",
    "BEGINSPEECHTOTEXT_LANGUAGE_0": "Mandarin(simplified)",
    "BEGINSPEECHTOTEXT_LANGUAGE_1": "Cantonese(traditional)",
    "BEGINSPEECHTOTEXT_LANGUAGE_2": "Mandarin_Taiwan(traditional)",
    "BEGINSPEECHTOTEXT_LANGUAGE_3": "Anglais",
    "BEGINSPEECHTOTEXT_LANGUAGE_4": "Français ",
    "BEGINSPEECHTOTEXT_LANGUAGE_5": "Allemand",
    "BEGINSPEECHTOTEXT_LANGUAGE_6": "Italien",
    "BEGINSPEECHTOTEXT_LANGUAGE_7": "Espagnol",
    "BEGINSPEECHTOTEXT_LANGUAGE_8": "Japonais",
    "BEGINSPEECHTOTEXT_LANGUAGE_9": "Coréen",
    "BEGINSPEECHTOTEXT_LANGUAGE_10": "Dutch",
    "BEGINSPEECHTOTEXT_LANGUAGE_11": "Polish",
    "BEGINSPEECHTOTEXT_LANGUAGE_12": "Portugais",
    "BEGINSPEECHTOTEXT_LANGUAGE_13": "Russe",
    "BEGINSPEECHTOTEXT_LANGUAGE_14": "Turkish",
    "BEGINSPEECHTOTEXT_LANGUAGE_15": "Thai",
    "BEGINSPEECHTOTEXT_LANGUAGE_16": "Czech",
    "BEGINSPEECHTOTEXT_LANGUAGE_17": "Arabic",
    "BEGINSPEECHTOTEXT_TIMER_0": "2",
    "BEGINSPEECHTOTEXT_TIMER_1": "5",
    "BEGINSPEECHTOTEXT_TIMER_2": "10",
    "beginSpeechToText": "recognize speech in [LANGUAGE] for [TIMER] secs",
    "BLOCK_1596095748995_ISHIDESIGNAL_0": "display",
    "BLOCK_1596095748995_ISHIDESIGNAL_1": "cacher",
    "BLOCK_1596095748995": "set speech recognition result to [isHideSignal] punctuation marks",
    "speechToTextResult": "résultat de la reconnaissance vocale",
    "BEGINIMAGETOTEXT_LANGUAGE_0": "Chinois (simplifié)",
    "BEGINIMAGETOTEXT_LANGUAGE_1": "Chinois (traditionnel)",
    "BEGINIMAGETOTEXT_LANGUAGE_2": "Anglais",
    "BEGINIMAGETOTEXT_LANGUAGE_3": "Français ",
    "BEGINIMAGETOTEXT_LANGUAGE_4": "Allemand",
    "BEGINIMAGETOTEXT_LANGUAGE_5": "Italien",
    "BEGINIMAGETOTEXT_LANGUAGE_6": "Espagnol",
    "BEGINIMAGETOTEXT_LANGUAGE_7": "Japonais",
    "BEGINIMAGETOTEXT_LANGUAGE_8": "Coréen",
    "BEGINIMAGETOTEXT_LANGUAGE_9": "Dutch",
    "BEGINIMAGETOTEXT_LANGUAGE_10": "Polish",
    "BEGINIMAGETOTEXT_LANGUAGE_11": "Portugais",
    "BEGINIMAGETOTEXT_LANGUAGE_12": "Russe",
    "BEGINIMAGETOTEXT_LANGUAGE_13": "Turkish",
    "BEGINIMAGETOTEXT_LANGUAGE_14": "Czech",
    "BEGINIMAGETOTEXT_LANGUAGE_15": "Arabic",
    "beginImageToText": "recognize printed [LANGUAGE] text after [TIMER] secs",
    "beginHandwrittenToText": "recognize handwritten English text after [TIMER] secs",
    "imageToTextResult": "résultat de la reconnaissance de texte",
    "BLOCK_1566749887154_TIMER_0": "1",
    "BLOCK_1566749887154_TIMER_1": "2",
    "BLOCK_1566749887154_TIMER_2": "3",
    "BLOCK_1566749887154_TYPE_0": "Reconnaissance d'image",
    "BLOCK_1566749887154_TYPE_1": "Marque",
    "BLOCK_1566749887154_TYPE_2": "Célébrité",
    "BLOCK_1566749887154_TYPE_3": "Landmark",
    "BLOCK_1566749887154_TYPE_4": "description de l'image",
    "BLOCK_1566749887154": "reconnaître[TYPE] dans l'image après [TIMER] secondes",
    "BLOCK_1566750695965_TYPE_0": "Reconnaissance d'image",
    "BLOCK_1566750695965_TYPE_1": "Marque",
    "BLOCK_1566750695965_TYPE_2": "Célébrité",
    "BLOCK_1566750695965_TYPE_3": "Landmark",
    "BLOCK_1566750695965_TYPE_4": "description de l'image",
    "BLOCK_1566750695965": "[TYPE] résultat de reconnaissance",
    "BLOCK_1590654305900": "recognize common object in image after[TIMER]secs",
    "BLOCK_1590654307561": "common object recognition result(serial)",
    "beginFaceDetection": "reconnaître l'âge des personnes après [TIMER] secondes",
    "faceDetectionResult": "Résultat de la reconnaissance de l'âge",
    "beginEmotionRecognition": "recognize emotion after [TIMER] secs",
    "EMOTIONVALUE_TYPE_0": "heureux",
    "EMOTIONVALUE_TYPE_1": "calme",
    "EMOTIONVALUE_TYPE_2": "surpris",
    "EMOTIONVALUE_TYPE_3": "triste",
    "EMOTIONVALUE_TYPE_4": "colère",
    "EMOTIONVALUE_TYPE_5": "mépris",
    "EMOTIONVALUE_TYPE_6": "dégoût",
    "EMOTIONVALUE_TYPE_7": "peur",
    "emotionValue": "emotion[TYPE]intensity",
    "emotionType": "le type d'émotion est [TYPE] ?",
    "beginFaceToGender": "recognize gender after [TIMER] secs",
    "faceToGenderResult": "résultat de reconnaissance du genre H/F",
    "beginFaceToGlassType": "recognize glasses type after [TIMER] secs",
    "FACETOGLASSTYPERESULT_TYPE_0": "des lunettes de soleil",
    "FACETOGLASSTYPERESULT_TYPE_1": "lunettes de lecture",
    "FACETOGLASSTYPERESULT_TYPE_2": "lunettes de natation",
    "FACETOGLASSTYPERESULT_TYPE_3": "pas de lunettes",
    "faceToGlassTypeResult": "porte [TYPE] ?",
    "beginFaceToIsSmile": "recognize smile score after [TIMER] secs",
    "faceToIsSmileResult": "résultat de reconnaissance du sourire",
    "beginFaceToHeadPose": "recognize head gesture after [TIMER] secs",
    "FACETOHEADPOSERESULT_TYPE_0": "rotation",
    "FACETOHEADPOSERESULT_TYPE_1": "lacet",
    "FACETOHEADPOSERESULT_TYPE_2": "tangage",
    "faceToHeadPoseResult": "tête [TYPE] angle () ",
    "BLOCK_1590547868949": "recognize hair color after[TIMER]secs",
    "BLOCK_1590547872342": "hair color",
    "BLOCK_1590548187016": "recognize facial blocking after [TIMER]secs",
    "BLOCK_1590548264613_TYPE_0": "forehead",
    "BLOCK_1590548264613_TYPE_1": "eyes",
    "BLOCK_1590548264613_TYPE_2": "mouth",
    "BLOCK_1590548264613": "[TYPE]being blocked?",
    "BLOCK_1590548416527_LANG_0": "Chinois",
    "BLOCK_1590548416527_LANG_1": "Anglais",
    "BLOCK_1590548416527_LANG_2": "Français ",
    "BLOCK_1590548416527_LANG_3": "Allemand",
    "BLOCK_1590548416527_LANG_4": "Italien",
    "BLOCK_1590548416527_LANG_5": "Espagnol",
    "BLOCK_1590548416527_LANG_6": "Japonais",
    "BLOCK_1590548416527_LANG_7": "Dutch",
    "BLOCK_1590548416527_LANG_8": "Polish",
    "BLOCK_1590548416527_LANG_9": "Portugais",
    "BLOCK_1590548416527_LANG_10": "Russe",
    "BLOCK_1590548416527_LANG_11": "Turkish",
    "BLOCK_1590548416527": "analyze [lang] text sentiment[text]",
    "BLOCK_1590548515617": "résultat de l'analyse des sentiments",
    "BLOCK_1590548564704": "recognize language:[text]",
    "BLOCK_1590548610070": "language recognition result",
    "cate_0969f72b": "Services Cognitifs",
    "err_network": "Aucune connexion réseau, veuillez vérifier vos paramètres réseau",
    "input_info_error": "Erreur de saisie des informations. Veuillez réessayer.",
    "err_count_limit": "Le compte courant a été appelé plus de 200 fois aujourd'hui",
    "err_request_fail": "Connexion échouée, veuillez réessayer",
    "err_not_login": "Vous n’êtes pas connecté, veuillez ouvrir une session",
    "RECOGNITION.WINDOW.TITLE": "Fenêtre de reconnaissance",
    "NO_VIDEO_DEVICE": "Pas de caméra détectée",
    "NO_AUDIO_DEVICE": "Pas de micro détecté",
    "NO_PERMISSION_MEDIA_DEVICE": "Permission refusée",
    "err_request_timeout": "Request timeout",
    "MEDIA_HELP_DOC": "Please check the help document"
};