export default {
    "Cognitive": "Servizi cognitivi",
    "extensionName": "Servizi cognitivi",
    "extensionDescription": "Le API dei servizi conoscitivo consente agli utenti di aggiungere altre funzionalità, ad esempio, Video, discorso, linguaggio e conoscenza.",
    "BEGINSPEECHTOTEXT_LANGUAGE_0": "Mandarino (semplificato)",
    "BEGINSPEECHTOTEXT_LANGUAGE_1": "Cantonese(tradizionale)",
    "BEGINSPEECHTOTEXT_LANGUAGE_2": "Mandarino_Taiwan(tradizionale)",
    "BEGINSPEECHTOTEXT_LANGUAGE_3": "Inglese",
    "BEGINSPEECHTOTEXT_LANGUAGE_4": "Francese",
    "BEGINSPEECHTOTEXT_LANGUAGE_5": "Tedesco",
    "BEGINSPEECHTOTEXT_LANGUAGE_6": "Italiano",
    "BEGINSPEECHTOTEXT_LANGUAGE_7": "Spagnolo",
    "BEGINSPEECHTOTEXT_LANGUAGE_8": "Giapponese",
    "BEGINSPEECHTOTEXT_LANGUAGE_9": "Coreano",
    "BEGINSPEECHTOTEXT_LANGUAGE_10": "Olandese",
    "BEGINSPEECHTOTEXT_LANGUAGE_11": "Polacco",
    "BEGINSPEECHTOTEXT_LANGUAGE_12": "Portoghese",
    "BEGINSPEECHTOTEXT_LANGUAGE_13": "Russo",
    "BEGINSPEECHTOTEXT_LANGUAGE_14": "Turco",
    "BEGINSPEECHTOTEXT_LANGUAGE_15": "Tailandese",
    "BEGINSPEECHTOTEXT_LANGUAGE_16": "Ceco",
    "BEGINSPEECHTOTEXT_LANGUAGE_17": "Arabo",
    "BEGINSPEECHTOTEXT_TIMER_0": "2",
    "BEGINSPEECHTOTEXT_TIMER_1": "5",
    "BEGINSPEECHTOTEXT_TIMER_2": "10",
    "beginSpeechToText": "riconoscimento vocale in [LANGUAGE] per [TIMER] seconds",
    "BLOCK_1596095748995_ISHIDESIGNAL_0": "display",
    "BLOCK_1596095748995_ISHIDESIGNAL_1": "nascondi",
    "BLOCK_1596095748995": "imposta il risultato del riconoscimento vocale a [isHideSignal] segni di punteggiatura",
    "speechToTextResult": "risultato riconoscimento vocale",
    "BEGINIMAGETOTEXT_LANGUAGE_0": "Cinese (semplificato)",
    "BEGINIMAGETOTEXT_LANGUAGE_1": "Cinese (tradizionale)",
    "BEGINIMAGETOTEXT_LANGUAGE_2": "Inglese",
    "BEGINIMAGETOTEXT_LANGUAGE_3": "Francese",
    "BEGINIMAGETOTEXT_LANGUAGE_4": "Tedesco",
    "BEGINIMAGETOTEXT_LANGUAGE_5": "Italiano",
    "BEGINIMAGETOTEXT_LANGUAGE_6": "Spagnolo",
    "BEGINIMAGETOTEXT_LANGUAGE_7": "Giapponese",
    "BEGINIMAGETOTEXT_LANGUAGE_8": "Coreano",
    "BEGINIMAGETOTEXT_LANGUAGE_9": "Olandese",
    "BEGINIMAGETOTEXT_LANGUAGE_10": "Polacco",
    "BEGINIMAGETOTEXT_LANGUAGE_11": "Portoghese",
    "BEGINIMAGETOTEXT_LANGUAGE_12": "Russo",
    "BEGINIMAGETOTEXT_LANGUAGE_13": "Turco",
    "BEGINIMAGETOTEXT_LANGUAGE_14": "Ceco",
    "BEGINIMAGETOTEXT_LANGUAGE_15": "Arabo",
    "beginImageToText": "riconoscere il testo stampato [LANGUAGE] dopo [TIMER] secondi",
    "beginHandwrittenToText": "riconoscere testo scritto a mano in inglese dopo [TIMER] secondi",
    "imageToTextResult": "risultato riconoscimento testo",
    "BLOCK_1566749887154_TIMER_0": "1",
    "BLOCK_1566749887154_TIMER_1": "2",
    "BLOCK_1566749887154_TIMER_2": "3",
    "BLOCK_1566749887154_TYPE_0": "Riconoscimento immagine",
    "BLOCK_1566749887154_TYPE_1": "marchio",
    "BLOCK_1566749887154_TYPE_2": "celebrità",
    "BLOCK_1566749887154_TYPE_3": "pietra miliare",
    "BLOCK_1566749887154_TYPE_4": "descrizione immagine",
    "BLOCK_1566749887154": "riconoscere[TYPE] nell'immagine dopo [TIMER] sec",
    "BLOCK_1566750695965_TYPE_0": "Riconoscimento immagine",
    "BLOCK_1566750695965_TYPE_1": "marchio",
    "BLOCK_1566750695965_TYPE_2": "celebrità",
    "BLOCK_1566750695965_TYPE_3": "pietra miliare",
    "BLOCK_1566750695965_TYPE_4": "descrizione immagine",
    "BLOCK_1566750695965": "[TYPE] risultato di riconoscimento",
    "BLOCK_1590654305900": "riconoscere l'oggetto comune nell'immagine dopo[TIMER]secondi",
    "BLOCK_1590654307561": "risultato del riconoscimento dell’oggetto comune (seriale)",
    "beginFaceDetection": "riconoscere l'età delle persone dopo [TIMER] sec",
    "faceDetectionResult": "risultato del riconoscimento di età",
    "beginEmotionRecognition": "riconoscere l'emozione dopo [TIMER] secondi",
    "EMOTIONVALUE_TYPE_0": "felice",
    "EMOTIONVALUE_TYPE_1": "neutro",
    "EMOTIONVALUE_TYPE_2": "sorpreso",
    "EMOTIONVALUE_TYPE_3": "triste",
    "EMOTIONVALUE_TYPE_4": "rabbia",
    "EMOTIONVALUE_TYPE_5": "disprezzo",
    "EMOTIONVALUE_TYPE_6": "disgusto",
    "EMOTIONVALUE_TYPE_7": "paura",
    "emotionValue": "intensità emozione[TYPE]",
    "emotionType": "l'emozione è [TYPE]?",
    "beginFaceToGender": "riconoscere il genere dopo [TIMER] sec",
    "faceToGenderResult": "risultato di riconoscimento di genere",
    "beginFaceToGlassType": "riconoscere il tipo di occhiali dopo [TIMER] secondi",
    "FACETOGLASSTYPERESULT_TYPE_0": "occhiali da sole",
    "FACETOGLASSTYPERESULT_TYPE_1": "occhiali da lettura",
    "FACETOGLASSTYPERESULT_TYPE_2": "occhiali per il nuoto",
    "FACETOGLASSTYPERESULT_TYPE_3": "senza occhiali",
    "faceToGlassTypeResult": "indossando [TYPE] ?",
    "beginFaceToIsSmile": "riconoscere il punteggio del sorriso dopo [TIMER] secondi",
    "faceToIsSmileResult": "risultato di riconoscimento sorriso",
    "beginFaceToHeadPose": "riconoscere il gesto della testa dopo [TIMER] secondi",
    "FACETOHEADPOSERESULT_TYPE_0": "rotolo",
    "FACETOHEADPOSERESULT_TYPE_1": "imbardata",
    "FACETOHEADPOSERESULT_TYPE_2": "beccheggio",
    "faceToHeadPoseResult": "testa [TYPE] angolo (°) a ",
    "BLOCK_1590547868949": "riconoscere il colore dei capelli dopo[TIMER]secondi",
    "BLOCK_1590547872342": "colore dei capelli",
    "BLOCK_1590548187016": "riconoscere il blocco del viso dopo [TIMER]secondi",
    "BLOCK_1590548264613_TYPE_0": "fronte",
    "BLOCK_1590548264613_TYPE_1": "occhi",
    "BLOCK_1590548264613_TYPE_2": "bocca",
    "BLOCK_1590548264613": "[TYPE]bloccato?",
    "BLOCK_1590548416527_LANG_0": "Cinese",
    "BLOCK_1590548416527_LANG_1": "Inglese",
    "BLOCK_1590548416527_LANG_2": "Francese",
    "BLOCK_1590548416527_LANG_3": "Tedesco",
    "BLOCK_1590548416527_LANG_4": "Italiano",
    "BLOCK_1590548416527_LANG_5": "Spagnolo",
    "BLOCK_1590548416527_LANG_6": "Giapponese",
    "BLOCK_1590548416527_LANG_7": "Olandese",
    "BLOCK_1590548416527_LANG_8": "Polacco",
    "BLOCK_1590548416527_LANG_9": "Portoghese",
    "BLOCK_1590548416527_LANG_10": "Russo",
    "BLOCK_1590548416527_LANG_11": "Turco",
    "BLOCK_1590548416527": "analizzare[lang] il sentimento [text] del testo",
    "BLOCK_1590548515617": "risultato analisi deli sentimenti",
    "BLOCK_1590548564704": "riconoscere la lingua:[text]",
    "BLOCK_1590548610070": "risultato del riconoscimento linguistico",
    "cate_0969f72b": "Servizi cognitivi",
    "err_network": "Anomalie di rete, si prega di controllare la rete",
    "input_info_error": "Errore di immissione delle informazioni. Riprovare.",
    "err_count_limit": "Il seguente account è stato caricato più di 200 volte oggi",
    "err_request_fail": "Errore nella chiamata dell'interfaccia, riprova",
    "err_not_login": "Non sei loggato, effettua il login",
    "RECOGNITION.WINDOW.TITLE": "Finestra di riconoscimento",
    "NO_VIDEO_DEVICE": "Nessuna videocamera rilevata",
    "NO_AUDIO_DEVICE": "Microfono non rilevato",
    "NO_PERMISSION_MEDIA_DEVICE": "Permesso negato",
    "err_request_timeout": "Timeout richiesta",
    "MEDIA_HELP_DOC": "Per favore, controlla il documento di aiuto"
};