export default {
    "Cognitive": "Serviços Cognitivos",
    "extensionName": "Serviços Cognitivos",
    "extensionDescription": "A API de serviços cognitivos permite que os utilizadores adicionem outros recursos, por exemplo, Vídeo, Fala, Idioma e Conhecimento.",
    "BEGINSPEECHTOTEXT_LANGUAGE_0": "Mandarin(simplified)",
    "BEGINSPEECHTOTEXT_LANGUAGE_1": "Cantonese(traditional)",
    "BEGINSPEECHTOTEXT_LANGUAGE_2": "Mandarin_Taiwan(traditional)",
    "BEGINSPEECHTOTEXT_LANGUAGE_3": "Inglês",
    "BEGINSPEECHTOTEXT_LANGUAGE_4": "Francês",
    "BEGINSPEECHTOTEXT_LANGUAGE_5": "Alemão",
    "BEGINSPEECHTOTEXT_LANGUAGE_6": "Italiano",
    "BEGINSPEECHTOTEXT_LANGUAGE_7": "Espanhol",
    "BEGINSPEECHTOTEXT_LANGUAGE_8": "Japanese",
    "BEGINSPEECHTOTEXT_LANGUAGE_9": "Korean",
    "BEGINSPEECHTOTEXT_LANGUAGE_10": "Dutch",
    "BEGINSPEECHTOTEXT_LANGUAGE_11": "Polish",
    "BEGINSPEECHTOTEXT_LANGUAGE_12": "Portuguese",
    "BEGINSPEECHTOTEXT_LANGUAGE_13": "Russian",
    "BEGINSPEECHTOTEXT_LANGUAGE_14": "Turkish",
    "BEGINSPEECHTOTEXT_LANGUAGE_15": "Thai",
    "BEGINSPEECHTOTEXT_LANGUAGE_16": "Czech",
    "BEGINSPEECHTOTEXT_LANGUAGE_17": "Arabic",
    "BEGINSPEECHTOTEXT_TIMER_0": "2",
    "BEGINSPEECHTOTEXT_TIMER_1": "5",
    "BEGINSPEECHTOTEXT_TIMER_2": "10",
    "beginSpeechToText": "recognize speech in [LANGUAGE] for [TIMER] secs",
    "BLOCK_1596095748995_ISHIDESIGNAL_0": "display",
    "BLOCK_1596095748995_ISHIDESIGNAL_1": "ocultar",
    "BLOCK_1596095748995": "set speech recognition result to [isHideSignal] punctuation marks",
    "speechToTextResult": "resultado do reconhecimento de voz",
    "BEGINIMAGETOTEXT_LANGUAGE_0": "Chinês (Simplificado)",
    "BEGINIMAGETOTEXT_LANGUAGE_1": "Chinês (tradicional)",
    "BEGINIMAGETOTEXT_LANGUAGE_2": "Inglês",
    "BEGINIMAGETOTEXT_LANGUAGE_3": "Francês",
    "BEGINIMAGETOTEXT_LANGUAGE_4": "Alemão",
    "BEGINIMAGETOTEXT_LANGUAGE_5": "Italiano",
    "BEGINIMAGETOTEXT_LANGUAGE_6": "Espanhol",
    "BEGINIMAGETOTEXT_LANGUAGE_7": "Japanese",
    "BEGINIMAGETOTEXT_LANGUAGE_8": "Korean",
    "BEGINIMAGETOTEXT_LANGUAGE_9": "Dutch",
    "BEGINIMAGETOTEXT_LANGUAGE_10": "Polish",
    "BEGINIMAGETOTEXT_LANGUAGE_11": "Portuguese",
    "BEGINIMAGETOTEXT_LANGUAGE_12": "Russian",
    "BEGINIMAGETOTEXT_LANGUAGE_13": "Turkish",
    "BEGINIMAGETOTEXT_LANGUAGE_14": "Czech",
    "BEGINIMAGETOTEXT_LANGUAGE_15": "Arabic",
    "beginImageToText": "recognize printed [LANGUAGE] text after [TIMER] secs",
    "beginHandwrittenToText": "recognize handwritten English text after [TIMER] secs",
    "imageToTextResult": "resultado do reconhecimento de texto",
    "BLOCK_1566749887154_TIMER_0": "1",
    "BLOCK_1566749887154_TIMER_1": "2",
    "BLOCK_1566749887154_TIMER_2": "3",
    "BLOCK_1566749887154_TYPE_0": "Reconhecimento de imagem",
    "BLOCK_1566749887154_TYPE_1": "Marca",
    "BLOCK_1566749887154_TYPE_2": "Celebridade",
    "BLOCK_1566749887154_TYPE_3": "Marco",
    "BLOCK_1566749887154_TYPE_4": "descrição da imagem",
    "BLOCK_1566749887154": "recognize[TYPE] in image after [TIMER] secs",
    "BLOCK_1566750695965_TYPE_0": "Reconhecimento de imagem",
    "BLOCK_1566750695965_TYPE_1": "Marca",
    "BLOCK_1566750695965_TYPE_2": "Celebridade",
    "BLOCK_1566750695965_TYPE_3": "Marco",
    "BLOCK_1566750695965_TYPE_4": "descrição da imagem",
    "BLOCK_1566750695965": "[TYPE] resultado do reconhecimento",
    "BLOCK_1590654305900": "recognize common object in image after[TIMER]secs",
    "BLOCK_1590654307561": "common object recognition result(serial)",
    "beginFaceDetection": "recognize people's age after [TIMER] secs",
    "faceDetectionResult": "resultado do reconhecimento de idade",
    "beginEmotionRecognition": "recognize emotion after [TIMER] secs",
    "EMOTIONVALUE_TYPE_0": "feliz",
    "EMOTIONVALUE_TYPE_1": "neutro",
    "EMOTIONVALUE_TYPE_2": "surpreso",
    "EMOTIONVALUE_TYPE_3": "triste",
    "EMOTIONVALUE_TYPE_4": "raiva",
    "EMOTIONVALUE_TYPE_5": "desprezo",
    "EMOTIONVALUE_TYPE_6": "desgosto",
    "EMOTIONVALUE_TYPE_7": "medo",
    "emotionValue": "emotion[TYPE]intensity",
    "emotionType": "emoção é [TYPE] ?",
    "beginFaceToGender": "recognize gender after [TIMER] secs",
    "faceToGenderResult": "resultado de reconhecimento de gênero",
    "beginFaceToGlassType": "recognize glasses type after [TIMER] secs",
    "FACETOGLASSTYPERESULT_TYPE_0": "óculos de sol",
    "FACETOGLASSTYPERESULT_TYPE_1": "óculos de leitura",
    "FACETOGLASSTYPERESULT_TYPE_2": "óculos de natação",
    "FACETOGLASSTYPERESULT_TYPE_3": "sem óculos",
    "faceToGlassTypeResult": "usando [TYPE] ?",
    "beginFaceToIsSmile": "recognize smile score after [TIMER] secs",
    "faceToIsSmileResult": "resultado de reconhecimento de sorriso",
    "beginFaceToHeadPose": "recognize head gesture after [TIMER] secs",
    "FACETOHEADPOSERESULT_TYPE_0": "rolagem",
    "FACETOHEADPOSERESULT_TYPE_1": "ângulo de guinada",
    "FACETOHEADPOSERESULT_TYPE_2": "tom",
    "faceToHeadPoseResult": "cabeça [TYPE] ângulo (°) ",
    "BLOCK_1590547868949": "recognize hair color after[TIMER]secs",
    "BLOCK_1590547872342": "hair color",
    "BLOCK_1590548187016": "recognize facial blocking after [TIMER]secs",
    "BLOCK_1590548264613_TYPE_0": "forehead",
    "BLOCK_1590548264613_TYPE_1": "eyes",
    "BLOCK_1590548264613_TYPE_2": "mouth",
    "BLOCK_1590548264613": "[TYPE]being blocked?",
    "BLOCK_1590548416527_LANG_0": "Chinês",
    "BLOCK_1590548416527_LANG_1": "Inglês",
    "BLOCK_1590548416527_LANG_2": "Francês",
    "BLOCK_1590548416527_LANG_3": "Alemão",
    "BLOCK_1590548416527_LANG_4": "Italiano",
    "BLOCK_1590548416527_LANG_5": "Espanhol",
    "BLOCK_1590548416527_LANG_6": "Japanese",
    "BLOCK_1590548416527_LANG_7": "Dutch",
    "BLOCK_1590548416527_LANG_8": "Polish",
    "BLOCK_1590548416527_LANG_9": "Portuguese",
    "BLOCK_1590548416527_LANG_10": "Russian",
    "BLOCK_1590548416527_LANG_11": "Turkish",
    "BLOCK_1590548416527": "analyze [lang] text sentiment[text]",
    "BLOCK_1590548515617": "sentiment analysis result",
    "BLOCK_1590548564704": "recognize language:[text]",
    "BLOCK_1590548610070": "language recognition result",
    "cate_0969f72b": "Serviços Cognitivos",
    "err_network": "Exceção de rede. Por favor, verifica a tua rede",
    "input_info_error": "Information input error. Please try again.",
    "err_count_limit": "A conta atual foi utilizada mais do que 200 vezes hoje",
    "err_request_fail": "Falha na interface de chamada. Por favor, tenta novamente",
    "err_not_login": "Não tens a sessão iniciada. Por favor, inicia a sessão",
    "RECOGNITION.WINDOW.TITLE": "Recognition window",
    "NO_VIDEO_DEVICE": "No camera detected",
    "NO_AUDIO_DEVICE": "No microphone detected",
    "NO_PERMISSION_MEDIA_DEVICE": "Permission denied",
    "err_request_timeout": "Request timeout",
    "MEDIA_HELP_DOC": "Please check the help document"
};