export default {
    "Cognitive": "Kognitiw Hyzmatlar",
    "extensionName": "Kognitiw Hyzmatlar",
    "extensionDescription": "API kognitiw hyzmatlar ulanyjylara wideo, gepleşik, dil we bilim ýaly beýleki aýratynlyklary goşmaga rugsat berýar.",
    "BEGINSPEECHTOTEXT_LANGUAGE_0": "Mandarin (aňsatlaşdyrylan)",
    "BEGINSPEECHTOTEXT_LANGUAGE_1": "Kanton dili (Milli)",
    "BEGINSPEECHTOTEXT_LANGUAGE_2": "Mandarin_Taiwan (milli)",
    "BEGINSPEECHTOTEXT_LANGUAGE_3": "Iňlisçe",
    "BEGINSPEECHTOTEXT_LANGUAGE_4": "Fransuzça",
    "BEGINSPEECHTOTEXT_LANGUAGE_5": "Nemesçe",
    "BEGINSPEECHTOTEXT_LANGUAGE_6": "Italýança",
    "BEGINSPEECHTOTEXT_LANGUAGE_7": "Ispança",
    "BEGINSPEECHTOTEXT_LANGUAGE_8": "Ýaponça",
    "BEGINSPEECHTOTEXT_LANGUAGE_9": "Koreýçe",
    "BEGINSPEECHTOTEXT_LANGUAGE_10": "Gollandça",
    "BEGINSPEECHTOTEXT_LANGUAGE_11": "Polýakça",
    "BEGINSPEECHTOTEXT_LANGUAGE_12": "Portugalça",
    "BEGINSPEECHTOTEXT_LANGUAGE_13": "Rusça",
    "BEGINSPEECHTOTEXT_LANGUAGE_14": "Türkçe",
    "BEGINSPEECHTOTEXT_LANGUAGE_15": "Taýça",
    "BEGINSPEECHTOTEXT_LANGUAGE_16": "Çehçe",
    "BEGINSPEECHTOTEXT_LANGUAGE_17": "Arapça",
    "BEGINSPEECHTOTEXT_TIMER_0": "2",
    "BEGINSPEECHTOTEXT_TIMER_1": "5",
    "BEGINSPEECHTOTEXT_TIMER_2": "10",
    "beginSpeechToText": "[LANGUAGE] dilinde gepleşigi [TIMER] sekunt boýunça kesgitle",
    "BLOCK_1596095748995_ISHIDESIGNAL_0": "displeý",
    "BLOCK_1596095748995_ISHIDESIGNAL_1": "gizle",
    "BLOCK_1596095748995": "gepleşigi tanamak netijesini belläň [isHideSignal] dyngy belgileri",
    "speechToTextResult": "gepleşik kesgitleýişiniň netijesi",
    "BEGINIMAGETOTEXT_LANGUAGE_0": "Hytaý dili (Aňsatlaşdyrylan)",
    "BEGINIMAGETOTEXT_LANGUAGE_1": "Hytaý dili (Milli)",
    "BEGINIMAGETOTEXT_LANGUAGE_2": "Iňlisçe",
    "BEGINIMAGETOTEXT_LANGUAGE_3": "Fransuzça",
    "BEGINIMAGETOTEXT_LANGUAGE_4": "Nemesçe",
    "BEGINIMAGETOTEXT_LANGUAGE_5": "Italýança",
    "BEGINIMAGETOTEXT_LANGUAGE_6": "Ispança",
    "BEGINIMAGETOTEXT_LANGUAGE_7": "Ýaponça",
    "BEGINIMAGETOTEXT_LANGUAGE_8": "Koreýçe",
    "BEGINIMAGETOTEXT_LANGUAGE_9": "Gollandça",
    "BEGINIMAGETOTEXT_LANGUAGE_10": "Polýakça",
    "BEGINIMAGETOTEXT_LANGUAGE_11": "Portugalça",
    "BEGINIMAGETOTEXT_LANGUAGE_12": "Rusça",
    "BEGINIMAGETOTEXT_LANGUAGE_13": "Türkçe",
    "BEGINIMAGETOTEXT_LANGUAGE_14": "Çehçe",
    "BEGINIMAGETOTEXT_LANGUAGE_15": "Arapça",
    "beginImageToText": "[LANGUAGE] dilinde ýazylan haty [TIMER] sekunt soňra kesgitle",
    "beginHandwrittenToText": "[TIMER] sekunt soňra el bilen Iňlis dilinde ýazylan haty kesgitle",
    "imageToTextResult": "hat kesgitleýişiniň netijesi",
    "BLOCK_1566749887154_TIMER_0": "1",
    "BLOCK_1566749887154_TIMER_1": "2",
    "BLOCK_1566749887154_TIMER_2": "3",
    "BLOCK_1566749887154_TYPE_0": "Şekil Anyklama",
    "BLOCK_1566749887154_TYPE_1": "söwda belgisi",
    "BLOCK_1566749887154_TYPE_2": "tanymal",
    "BLOCK_1566749887154_TYPE_3": "belli ýer",
    "BLOCK_1566749887154_TYPE_4": "şekil kesgitlemesi",
    "BLOCK_1566749887154": "şekildäki [TYPE] görnüşini [TIMER] sekuntdan soňra anykla",
    "BLOCK_1566750695965_TYPE_0": "Şekil Anyklama",
    "BLOCK_1566750695965_TYPE_1": "söwda belgisi",
    "BLOCK_1566750695965_TYPE_2": "tanymal",
    "BLOCK_1566750695965_TYPE_3": "belli ýer",
    "BLOCK_1566750695965_TYPE_4": "şekil kesgitlemesi",
    "BLOCK_1566750695965": "[TYPE] anyklamanyň netijesi",
    "BLOCK_1590654305900": "[TIMER] sekunt soňra şekildäki adaty zady kesgitle",
    "BLOCK_1590654307561": "adaty zat kesgitleýiş netijesi (seriýa)",
    "beginFaceDetection": "adamlaryň ýaşyny [TIMER] sekunt soňra kesgitle",
    "faceDetectionResult": "ýaş kesgitleýişiniň netijesi",
    "beginEmotionRecognition": "duýgulary [TIMER] sekunt soňra kesgitle",
    "EMOTIONVALUE_TYPE_0": "şadyýan",
    "EMOTIONVALUE_TYPE_1": "neýtral",
    "EMOTIONVALUE_TYPE_2": "geň galan",
    "EMOTIONVALUE_TYPE_3": "gynançly",
    "EMOTIONVALUE_TYPE_4": "gahar",
    "EMOTIONVALUE_TYPE_5": "göwni ýetmezçilikli",
    "EMOTIONVALUE_TYPE_6": "ýigrenç bilen",
    "EMOTIONVALUE_TYPE_7": "gorky",
    "emotionValue": "duýgy [TYPE] intensiwligi",
    "emotionType": "duýgy şumy [TYPE] ?",
    "beginFaceToGender": "jynsy [TIMER] sekunt soňra kesgitle",
    "faceToGenderResult": "jyns kesgitleýişiniň netijesi",
    "beginFaceToGlassType": "[TIMER] sekunt soňra äýnek görnüşini anykla",
    "FACETOGLASSTYPERESULT_TYPE_0": "güne garşy äýnek",
    "FACETOGLASSTYPERESULT_TYPE_1": "okamak üçin äýnek",
    "FACETOGLASSTYPERESULT_TYPE_2": "ýüzmek üçin äýnek",
    "FACETOGLASSTYPERESULT_TYPE_3": "äýneksiz",
    "faceToGlassTypeResult": "dakylýan [TYPE] ?",
    "beginFaceToIsSmile": "[TIMER] sek soňra ýylgyryşyň bahasyny anyklamak",
    "faceToIsSmileResult": "ýylgyryş kesgitleýişiniň netijesi",
    "beginFaceToHeadPose": "[TIMER] sekunt soňra kelle hereketini kesgitle",
    "FACETOHEADPOSERESULT_TYPE_0": "togalamak",
    "FACETOHEADPOSERESULT_TYPE_1": "kaňkap ýörmek",
    "FACETOHEADPOSERESULT_TYPE_2": "ýapgyt burçy",
    "faceToHeadPoseResult": "baş [TYPE] derejesi (°) ",
    "BLOCK_1590547868949": "[TIMER] sek soňra saçyň reňkini anyklamak",
    "BLOCK_1590547872342": "saç reňki",
    "BLOCK_1590548187016": "[TIMER] sekunt soňra ýüz çäklendirmesini anyklamak",
    "BLOCK_1590548264613_TYPE_0": "maňlaý",
    "BLOCK_1590548264613_TYPE_1": "gözler",
    "BLOCK_1590548264613_TYPE_2": "agyz",
    "BLOCK_1590548264613": "[TYPE] çäklendirilenmi?",
    "BLOCK_1590548416527_LANG_0": "Hytaý",
    "BLOCK_1590548416527_LANG_1": "Iňlisçe",
    "BLOCK_1590548416527_LANG_2": "Fransuzça",
    "BLOCK_1590548416527_LANG_3": "Nemesçe",
    "BLOCK_1590548416527_LANG_4": "Italýança",
    "BLOCK_1590548416527_LANG_5": "Ispança",
    "BLOCK_1590548416527_LANG_6": "Ýaponça",
    "BLOCK_1590548416527_LANG_7": "Gollandça",
    "BLOCK_1590548416527_LANG_8": "Polýakça",
    "BLOCK_1590548416527_LANG_9": "Portugalça",
    "BLOCK_1590548416527_LANG_10": "Rusça",
    "BLOCK_1590548416527_LANG_11": "Türkçe",
    "BLOCK_1590548416527": "[lang] seljermek [text] ýazgynyň ýagdaýy",
    "BLOCK_1590548515617": "keýp ýagdaýynyň seljerişiniň netijesi",
    "BLOCK_1590548564704": "dili anyklamak: [text]",
    "BLOCK_1590548610070": "dil kesgitleýişiniň netijesi",
    "cate_0969f72b": "Kognitiw Hyzmatlar",
    "err_network": "Tor näsazlygy, toruňyzy barlap görüň",
    "input_info_error": "Maglumat girişinde säwlik. Täzeden synanyşyp görüň.",
    "err_count_limit": "Şu hasapdan gündelik 200 gezek jaň etmek çäginden geçildi",
    "err_request_fail": "Jäň interfeýsinde näsazlyk, täzeden synanyşyň",
    "err_not_login": "Siz ulgama giriş etmediňiz, ulgama giriň",
    "RECOGNITION.WINDOW.TITLE": "Anyklaýyş penjiresi",
    "NO_VIDEO_DEVICE": "Kamera anyklanmady",
    "NO_AUDIO_DEVICE": "Mikrofon anyklanmady",
    "NO_PERMISSION_MEDIA_DEVICE": "Rugsat inkär edildi",
    "err_request_timeout": "Talabyň güýjüni ýitirme wagty",
    "MEDIA_HELP_DOC": "Kömek resminamasyny barlaň"
};