export default {
    "weather": "Datos del clima",
    "extensionName": "Datos climáticos",
    "extensionDescription": "La extensión te da fácil acceso a datos del clima en tiempo real.",
    "widget_e7b76771": "ciudad",
    "max_temperature_c": "[CITY] temperatura más alta (ºC)",
    "min_temperature_c": "[CITY] temperatura más baja (ºC)",
    "max_temperature_f": "[CITY] temperatura más alta (ºF)",
    "min_temperature_f": "[CITY] temperatura más baja (ºF)",
    "humidity": "[CITY] humedad (%)",
    "temperature": "[CITY] temperatura",
    "SUNRISE_TIME_0": "Hora",
    "SUNRISE_TIME_1": "Minuto",
    "sunrise": "[CITY] hora de salida del sol [TIME]",
    "sunset": "[CITY] hora de puesta del sol [TIME]",
    "widget_b25ca5f4": "Ubicación",
    "METEOROLOGICAL_AIRQUALITY_0": "ICA",
    "METEOROLOGICAL_AIRQUALITY_1": "PM2.5",
    "METEOROLOGICAL_AIRQUALITY_2": "PM10",
    "METEOROLOGICAL_AIRQUALITY_3": "CO",
    "METEOROLOGICAL_AIRQUALITY_4": "SO2",
    "METEOROLOGICAL_AIRQUALITY_5": "NO2",
    "meteorological": "[METEOROLOGICAL] calidad del aire: índice [AIRQUALITY]",
    "7c2d3f67-d983-4639-80da-d58db2e1e06d": "Datos del clima",
    "CHOOSE_CITY": "Elige una ciudad",
    "CHOOSE_METEOR": "Elige una ubicación"
};