export default {
    "weather": "נתוני אקלים",
    "extensionName": "נתוני אקלים",
    "extensionDescription": "הרחבה זו תיתן לכם גישה לנתוני אקלים בזמן אמת.",
    "widget_e7b76771": "עיר",
    "max_temperature_c": "[CITY] הטמפרטורה הכי גבוהה（℃）",
    "min_temperature_c": "[CITY] הטמפרטורה הכי נמוכה（℃）",
    "max_temperature_f": "[CITY] הטמפרטורה הכי גבוהה（℉）",
    "min_temperature_f": "[CITY] הטמפרטורה הכי נמוכה（℉）",
    "humidity": "[CITY] לחות （%）",
    "temperature": "[CITY] מזג אויר",
    "SUNRISE_TIME_0": "שעה",
    "SUNRISE_TIME_1": "דקה",
    "sunrise": "[CITY] שעת זריחה [TIME]",
    "sunset": "[CITY] שעת שקיעה [TIME]",
    "widget_b25ca5f4": "מיקום",
    "METEOROLOGICAL_AIRQUALITY_0": "AQI",
    "METEOROLOGICAL_AIRQUALITY_1": "PM2.5",
    "METEOROLOGICAL_AIRQUALITY_2": "PM10",
    "METEOROLOGICAL_AIRQUALITY_3": "CO",
    "METEOROLOGICAL_AIRQUALITY_4": "SO2",
    "METEOROLOGICAL_AIRQUALITY_5": "NO2",
    "meteorological": "[METEOROLOGICAL]מדד איכות אויר [AIRQUALITY]",
    "7c2d3f67-d983-4639-80da-d58db2e1e06d": "נתוני אקלים",
    "CHOOSE_CITY": "בחר עיר",
    "CHOOSE_METEOR": "בחירת מיקום"
};