export default {
    "weather": "Data iklim",
    "extensionName": "Data iklim",
    "extensionDescription": "Ekstensi memberi Anda akses cepat ke data real-time iklim.",
    "widget_e7b76771": "Kota",
    "max_temperature_c": "[CITY] tertinggi temperature(℃)",
    "min_temperature_c": "[CITY] temperature(℃) terendah",
    "max_temperature_f": "[CITY] tertinggi temperature(℉)",
    "min_temperature_f": "[CITY] temperature(℉) terendah",
    "humidity": "[CITY] Humidity(%)",
    "temperature": "[CITY] Cuaca",
    "SUNRISE_TIME_0": "jam",
    "SUNRISE_TIME_1": "menit",
    "sunrise": "[CITY] waktu matahari terbit [TIME]",
    "sunset": "[CITY] waktu matahari terbenam [TIME]",
    "widget_b25ca5f4": "Lokasi",
    "METEOROLOGICAL_AIRQUALITY_0": "AQI",
    "METEOROLOGICAL_AIRQUALITY_1": "PM2.5",
    "METEOROLOGICAL_AIRQUALITY_2": "PM10",
    "METEOROLOGICAL_AIRQUALITY_3": "CO",
    "METEOROLOGICAL_AIRQUALITY_4": "SO2",
    "METEOROLOGICAL_AIRQUALITY_5": "NO2",
    "meteorological": "[METEOROLOGICAL]kualitas udara [AIRQUALITY] Indeks",
    "7c2d3f67-d983-4639-80da-d58db2e1e06d": "Data iklim",
    "CHOOSE_CITY": "Pilih kota",
    "CHOOSE_METEOR": "Memilih lokasi"
};