export default {
    "weather": "Dati climatici",
    "extensionName": "Dati climatici",
    "extensionDescription": "L'estensione consente di accedere rapidamente ai dati climatici in tempo reale.",
    "widget_e7b76771": "città",
    "max_temperature_c": "[CITY] temperatura massima (℃)",
    "min_temperature_c": "[CITY] temperatura minima (℃)",
    "max_temperature_f": "[CITY] temperatura massima (℉)",
    "min_temperature_f": "[CITY] temperatura minima (℉)",
    "humidity": "[CITY] umidità (%)",
    "temperature": "[CITY] Meteo",
    "SUNRISE_TIME_0": "Ora",
    "SUNRISE_TIME_1": "Minuti",
    "sunrise": "[CITY] ora di alba [TIME]",
    "sunset": "[CITY] tempo di tramonto [TIME]",
    "widget_b25ca5f4": "Posizione",
    "METEOROLOGICAL_AIRQUALITY_0": "AQI",
    "METEOROLOGICAL_AIRQUALITY_1": "PM 2.5",
    "METEOROLOGICAL_AIRQUALITY_2": "PM10",
    "METEOROLOGICAL_AIRQUALITY_3": "CO",
    "METEOROLOGICAL_AIRQUALITY_4": "SO2",
    "METEOROLOGICAL_AIRQUALITY_5": "NO2",
    "meteorological": "[METEOROLOGICAL]qualità dell'aria [AIRQUALITY] Indice",
    "7c2d3f67-d983-4639-80da-d58db2e1e06d": "Dati climatici",
    "CHOOSE_CITY": "Scegli una città",
    "CHOOSE_METEOR": "Scegli una località"
};