export default {
    "weather": "Климатические показатели",
    "extensionName": "Климатические показатели",
    "extensionDescription": "Расширение предоставляет быстрый доступ к климатическим данным в реальном времени.",
    "widget_e7b76771": "город",
    "max_temperature_c": "[CITY] максимальная температура (°C)",
    "min_temperature_c": "[CITY] минимальная температура (°C)",
    "max_temperature_f": "[CITY] максимальная температура (°F)",
    "min_temperature_f": "[CITY] максимальная температура (°F)",
    "humidity": "[CITY] влажность (%)",
    "temperature": "[CITY] погода",
    "SUNRISE_TIME_0": "час",
    "SUNRISE_TIME_1": "минута",
    "sunrise": "[CITY] восход солнца [TIME]",
    "sunset": "[CITY] закат солнца [TIME]",
    "widget_b25ca5f4": "Местоположение",
    "METEOROLOGICAL_AIRQUALITY_0": "ИКВ",
    "METEOROLOGICAL_AIRQUALITY_1": "УДЧ PM2.5",
    "METEOROLOGICAL_AIRQUALITY_2": "УДЧ PM10",
    "METEOROLOGICAL_AIRQUALITY_3": "CO",
    "METEOROLOGICAL_AIRQUALITY_4": "SO2",
    "METEOROLOGICAL_AIRQUALITY_5": "NO2",
    "meteorological": "[METEOROLOGICAL]показатель качества воздуха [AIRQUALITY]",
    "7c2d3f67-d983-4639-80da-d58db2e1e06d": "Климатические показатели",
    "CHOOSE_CITY": "Выбрать город",
    "CHOOSE_METEOR": "Выбрать местоположение"
};