export default {
    "mcore_all": "Platforma výrobce",
    "extensionName": "Platforma výrobce",
    "extensionDescription": "kolekce rozšíření mBot",
    "MCORE_RUN_SHUTTER_PORT_0": "port1",
    "MCORE_RUN_SHUTTER_PORT_1": "port2",
    "MCORE_RUN_SHUTTER_PORT_2": "port3",
    "MCORE_RUN_SHUTTER_PORT_3": "port4",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_0": "stiskni",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_1": "uvolni",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_2": "zaměř",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_3": "zastavit zaměření",
    "mcore_run_shutter": "[ICON] Závěrka [PORT] [SHUTTER_ACTION]",
    "MCORE_RUN_MOTOR_PORT_0": "motor port1",
    "MCORE_RUN_MOTOR_PORT_1": "motor port2",
    "MCORE_RUN_MOTOR_ROTATE_0": "po směru hodinových ručiček",
    "MCORE_RUN_MOTOR_ROTATE_1": "proti směru hodinových ručiček",
    "mcore_run_motor": "[ICON] DC motor [PORT] [ROTATE] výkon [POWER] %",
    "MCORE_RUN_SERVO_SLOT_0": "slot 1",
    "MCORE_RUN_SERVO_SLOT_1": "slot 2",
    "mcore_run_servo": "[ICON] servo [PORT] [SLOT] nastavit úhel [DEGREE]",
    "MCORE_RUN_FAN_FAN_ROTATE_0": "po směru hodinových ručiček",
    "MCORE_RUN_FAN_FAN_ROTATE_1": "proti směru hodinových ručiček",
    "MCORE_RUN_FAN_FAN_ROTATE_2": "zastavit",
    "mcore_run_fan": "[ICON] Ventilátor [PORT] [FAN_ROTATE] otáček",
    "mcore_show_face_time": "[ICON] LED panel [PORT] zobrazí obrázek [FACE_PANEL] na [TIME] sekund",
    "mcore_show_face": "[ICON] LED panel [PORT] zobrazí obrázek [FACE_PANEL]",
    "mcore_show_face_position": "[ICON] LED panel [PORT] zobrazí obrázek [FACE_PANEL] na pozici x: [X] y: [Y]",
    "mcore_show_text": "[ICON] LED panel [PORT] zobrazí text [TEXT]",
    "mcore_show_text_position": "[ICON] LED panel [PORT] zobrazí text [TEXT] na pozici x: [X] Y: [Y]",
    "mcore_show_number": "[ICON] LED panel [PORT] zobrazí číslo [NUMBER]",
    "mcore_show_time": "[ICON] LED panel [PORT] zobrazí čas [NUMBER1]: [NUMBER2]",
    "mcore_show_face_off": "[ICON] LED panel [PORT] vymaže obrazovku",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "vše",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] RGB LED [PORT] rozsvítí [LED_POSTION]  barvou [COLOR] na [TIME] sekund",
    "mcore_show_external_led": "[ICON] RGB LED [PORT] rozsvítí [LED_POSTION] barvou [COLOR]",
    "mcore_show_external_led_rgb": "[ICON] RGB LED [PORT] rozsvítí [LED_POSTION] barvou červená [R], zelená [G], modrá [B]",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "červená",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "oranžová",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "žlutá",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "zelená",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "azurová",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "modrá",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "purpurová",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "černá",
    "mcore_show_all_ledstrip_color": "[ICON]LED pásek [PORT] [SLOT] vše svítí barvou [COLOR_LIST]",
    "mcore_show_ledstrip_color": "[ICON] LED pásek [PORT] [SLOT] [POS] svítí barvou [COLOR_LIST]",
    "mcore_show_ledstrip_rbg": "[ICON] LED pásek [PORT] [SLOT] [POS] svítí barvou červená [R], zelená [G], modrá [B]",
    "mcore_show_7segments_number": "[ICON] sedmisegmentový displej [PORT] zobrazí číslo [NUMBER]",
    "mcore_detect_external_ultrasonic": "[ICON] ultrazvukový senzor [PORT] vzdálenost",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_0": "port3",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_1": "port4",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_2": "palubní",
    "mcore_detect_external_light": "[ICON]Světelný senzor [PORT] Intenzita světla",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_0": "port3",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_1": "port4",
    "mcore_detect_external_loudness": "[ICON] senzor zvuku [PORT] hlasitost",
    "mcore_detect_external_linefollower": "[ICON] senzor sledování čáry [PORT]  hodnota",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "levá strana",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "pravá strana",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "vše",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "nic",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "černá",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "bílá",
    "mcore_event_external_linefollower": "[ICON] Detekuje senzor sledování čáry [PORT] [LINEFOLLOW_STATE] barvu [BLACK_WHITE]?",
    "mcore_detec_temperature": "[ICON] teplotní čído [PORT] [SLOT] teplota (℃)",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_0": "vlhkost",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_1": "teplota",
    "mcore_detect_humiture": "[ICON] senzor vlhkosti [PORT] [TEMP_HUMITURE]",
    "mcore_event_touch": "[ICON] dotykové čidlo [PORT] je dotyk?",
    "mcore_detect_compass": "[ICON] Elektronický kompas [PORT] směrem na sever",
    "mcore_detect_flame": "[ICON] senzor plamene [PORT] hodnota",
    "mcore_detect_gas": "[ICON] senzor plynu [PORT] hodnota",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_0": "osa-x",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_1": "osa-y",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_2": "osa Z",
    "mcore_detect_gyro_angle": "[ICON]Gyroskop [AXIS] Úhel",
    "mcore_detect_gyro_angle_1": "[ICON] gyroskop (na jakémkoli bílém portu) [GyroAxis] úhel",
    "mcore_event_pir_motion": "[ICON] Senzor PIR [PORT] detekuje lidský pohyb",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_0": "tlačítko1",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_1": "tlačítko 2",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_2": "tlačítko 3",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_3": "tlačítko 4",
    "mcore_event_button_press": "[ICON]je tlačítko [PORT] [FOUR_KEY] stisknuto?",
    "mcore_event_limit_switch": "[ICON] je omezovací spínač [PORT] [SLOT] stisknut?",
    "mcore_detect_potentiometer": "[ICON] potenciometr [PORT] hodnota",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_0": "osa-x",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_1": "osa-y",
    "mcore_detect_joystick": "[ICON] joystick [PORT] [AXIS_X_Y] hodnota",
    "mcore_detect_infrared": "[ICON] IR příjímač [PORT]",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_0": "PM1.0",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_1": "PM2.5",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_2": "PM10",
    "auriga_detect_pm25_sensor": "[ICON] senzor kvality ovzduší[PORT], [OPTION] (μg/m³)",
    "mbot_all": "Platforma výrobce"
};