export default {
    "mcore_all": "メイカープラットフォーム",
    "extensionName": "メイカープラットフォーム",
    "extensionDescription": "mBot  拡張機能のコレクション",
    "MCORE_RUN_SHUTTER_PORT_0": "ポート1",
    "MCORE_RUN_SHUTTER_PORT_1": "ポート2",
    "MCORE_RUN_SHUTTER_PORT_2": "ポート3",
    "MCORE_RUN_SHUTTER_PORT_3": "ポート4",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_0": "押す",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_1": "離す",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_2": "フォーカスオン",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_3": "フォーカスオフ",
    "mcore_run_shutter": "[ICON] カメラのシャッター [PORT] を[SHUTTER_ACTION]",
    "MCORE_RUN_MOTOR_PORT_0": "モーター ポート1",
    "MCORE_RUN_MOTOR_PORT_1": "モーター ポート2",
    "MCORE_RUN_MOTOR_ROTATE_0": "時計回り",
    "MCORE_RUN_MOTOR_ROTATE_1": "反時計回り",
    "mcore_run_motor": "[ICON] DCモーター [PORT] の速さを[POWER] %で[ROTATE] にする",
    "MCORE_RUN_SERVO_SLOT_0": "スロット1",
    "MCORE_RUN_SERVO_SLOT_1": "スロット2",
    "mcore_run_servo": "[ICON] サーボ[PORT] の[SLOT] の角度を[DEGREE] にする",
    "MCORE_RUN_FAN_FAN_ROTATE_0": "時計回り",
    "MCORE_RUN_FAN_FAN_ROTATE_1": "反時計回り",
    "MCORE_RUN_FAN_FAN_ROTATE_2": "を止める",
    "mcore_run_fan": "[ICON] ファン [PORT] を[FAN_ROTATE] にする",
    "mcore_show_face_time": "[ICON]LEDパネル[PORT]に [FACE_PANEL]を[TIME]秒表示する",
    "mcore_show_face": "[ICON]LEDパネル[PORT] に[FACE_PANEL] を表示する",
    "mcore_show_face_position": "[ICON] LEDパネル[PORT] に [FACE_PANEL] をx: [X] y: [Y] で表示する",
    "mcore_show_text": "[ICON] LEDパネル [PORT] に [TEXT] を表示する",
    "mcore_show_text_position": "[ICON] LEDパネル[PORT] に[TEXT] をx: [X] y: [Y] で表示する",
    "mcore_show_number": "[ICON] LEDパネル[PORT] に[NUMBER] を表示する",
    "mcore_show_time": "[ICON] LEDパネル[PORT] に[NUMBER1] 時[NUMBER2] 分を表示する",
    "mcore_show_face_off": "[ICON] LEDパネル[PORT] の表示を消す",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "全て",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] RGB[PORT] の[LED_POSTION] のLEDを[COLOR] 色で[TIME] 秒点灯する",
    "mcore_show_external_led": "[ICON] RGB[PORT] の[LED_POSTION] のLEDを[COLOR] 色で点灯する",
    "mcore_show_external_led_rgb": "[ICON] RGB[PORT] の[LED_POSTION] のLEDを赤 [R] 緑[G] 青 [B] で点灯する",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "赤",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "オレンジ",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "黄",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "緑",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "シアン",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "青",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "紫",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "黒",
    "mcore_show_all_ledstrip_color": "[ICON] LED ストリップ[PORT] の[SLOT] を[COLOR_LIST] 色で点灯する",
    "mcore_show_ledstrip_color": "[ICON] LED ストリップ[PORT] の[SLOT] の[POS] 番目を[COLOR_LIST] 色で点灯する",
    "mcore_show_ledstrip_rbg": "[ICON]LED ストリップ[PORT] の[SLOT] の[POS] 番目を赤 [R] 緑 [G] 青 [B] で点灯する",
    "mcore_show_7segments_number": "[ICON] 7セグメントディスプレイ[PORT] に[NUMBER] を表示する",
    "mcore_detect_external_ultrasonic": "[ICON] 超音波センサー[PORT] の値",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_0": "ポート3",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_1": "ポート4",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_2": "ボード上の光センサー",
    "mcore_detect_external_light": "[ICON]光センサー [PORT] の値",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_0": "ポート3",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_1": "ポート4",
    "mcore_detect_external_loudness": "[ICON]音声センサー [PORT] の値",
    "mcore_detect_external_linefollower": "[ICON] ライントレースセンサー [PORT] の 値",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "左のセンサーで検知する",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "右のセンサーで検知する",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "両方のセンサーで検知する",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "両方のセンサーで検知しない",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "黒",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "白",
    "mcore_event_external_linefollower": "[ICON]ライントレースセンサー [PORT] が[BLACK_WHITE] を[LINEFOLLOW_STATE]",
    "mcore_detec_temperature": "[ICON]温度センサー[PORT] の[SLOT] の値 (℃)",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_0": "湿度",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_1": "温度",
    "mcore_detect_humiture": "[ICON]温湿度センサー[PORT] [TEMP_HUMITURE]",
    "mcore_event_touch": "[ICON] タッチセンサー [PORT]",
    "mcore_detect_compass": "[ICON] 電子コンパス [PORT] の値",
    "mcore_detect_flame": "[ICON]火炎センサー [PORT] の値",
    "mcore_detect_gas": "[ICON]ガスセンサー [PORT] の値",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_0": "x軸",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_1": "y軸",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_2": "z軸",
    "mcore_detect_gyro_angle": "[ICON]3軸ジャイロの[AXIS] の値",
    "mcore_detect_gyro_angle_1": "[ICON] ジャイロスコープ (任意のホワイトポート上) [GyroAxis] の角度",
    "mcore_event_pir_motion": "[ICON] PIRモーションセンサー[PORT]",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_0": "KEY1",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_1": "KEY2",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_2": "KEY3",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_3": "KEY4\n",
    "mcore_event_button_press": "[ICON] [PORT] の[FOUR_KEY] ボタンが押された",
    "mcore_event_limit_switch": "[ICON]リミットスイッチ[PORT] の[SLOT]",
    "mcore_detect_potentiometer": "[ICON]ポテンショメータ [PORT] の値",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_0": "x軸",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_1": "y軸",
    "mcore_detect_joystick": "[ICON] ジョイスティック[PORT]の[AXIS_X_Y] の値",
    "mcore_detect_infrared": "[ICON]赤外線レシーバー [PORT]の値",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_0": "PM1.0",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_1": "PM2.5",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_2": "PM10",
    "auriga_detect_pm25_sensor": "[ICON] 空気品質センサー[PORT], [OPTION] (μg/m³)",
    "mbot_all": "メイカープラットフォーム"
};