export default {
    "mcore_all": "Plataforma do Criador",
    "extensionName": "Plataforma do Criador",
    "extensionDescription": "Coleção de Extensões mBot",
    "MCORE_RUN_SHUTTER_PORT_0": "porta1",
    "MCORE_RUN_SHUTTER_PORT_1": "porta2",
    "MCORE_RUN_SHUTTER_PORT_2": "porta3",
    "MCORE_RUN_SHUTTER_PORT_3": "porta4",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_0": "pressionar",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_1": "soltar",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_2": "focar",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_3": "parar de focar",
    "mcore_run_shutter": "[ICON] obturador [PORT] [SHUTTER_ACTION]",
    "MCORE_RUN_MOTOR_PORT_0": "motor porta1",
    "MCORE_RUN_MOTOR_PORT_1": "motor porta2",
    "MCORE_RUN_MOTOR_ROTATE_0": "sentido horário",
    "MCORE_RUN_MOTOR_ROTATE_1": "sentido anti-horário",
    "mcore_run_motor": "[ICON] Motor de corrente contínua [PORT] [ROTATE] gira na potência [POWER] %",
    "MCORE_RUN_SERVO_SLOT_0": "ranhura1",
    "MCORE_RUN_SERVO_SLOT_1": "ranhura2",
    "mcore_run_servo": "[ICON] servo [PORT] [SLOT] posicionado no ângulo [DEGREE]",
    "MCORE_RUN_FAN_FAN_ROTATE_0": "sentido horário",
    "MCORE_RUN_FAN_FAN_ROTATE_1": "sentido anti-horário",
    "MCORE_RUN_FAN_FAN_ROTATE_2": "parar",
    "mcore_run_fan": "[ICON] ventilador [PORT] [FAN_ROTATE] gira",
    "mcore_show_face_time": "[ICON]Painel de LED [PORT] mostra a imagem [FACE_PANEL] durante [TIME] segundo(s)",
    "mcore_show_face": "[ICON]Painel de LED [PORT] mostra a imagem [FACE_PANEL]",
    "mcore_show_face_position": "[ICON] Painel de LED [PORT] mostra a imagem [FACE_PANEL] em x: [X] y: [Y]",
    "mcore_show_text": "[ICON] Painel de LED [PORT] mostra o texto [TEXT]",
    "mcore_show_text_position": "[ICON]Painel de LED [PORT] mostra o texto [TEXT] em x: [X] y: [Y]",
    "mcore_show_number": "[ICON] Painel de LED [PORT] mostra o número [NUMBER]",
    "mcore_show_time": "[ICON] Painel de LED [PORT] mostra a hora [NUMBER1]: [NUMBER2]",
    "mcore_show_face_off": "[ICON] Painel de LED [PORT] limpa o ecrã",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "todos",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] LED RGB [PORT] ligado [LED_POSTION] com a luz de cor [COLOR] durante [TIME] segundo(s)",
    "mcore_show_external_led": "[ICON] LED RGB [PORT] ligado [LED_POSTION]com a luz de cor [COLOR]",
    "mcore_show_external_led_rgb": "[ICON] LED RGB [PORT] ligado [LED_POSTION] com cor vermelha [R] verde [G] azul [B]",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "vermelho",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "laranja",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "amarelo",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "verde",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "ciano",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "azul",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "roxo",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "preto",
    "mcore_show_all_ledstrip_color": "[ICON]banda de LED [PORT] [SLOT] com todas as luzes de cor [COLOR_LIST]",
    "mcore_show_ledstrip_color": "[ICON] banda de LED [PORT] [SLOT] [POS] com a luz de cor [COLOR_LIST]",
    "mcore_show_ledstrip_rbg": "[ICON] banda de LED [PORT] [SLOT] [POS] ligada com cor vermelha [R] verde [G] azul [B]",
    "mcore_show_7segments_number": "[ICON] sete segmentos [PORT] exibe o número [NUMBER]",
    "mcore_detect_external_ultrasonic": "[ICON] sensor de ultrassom [PORT] distância",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_0": "porta3",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_1": "porta4",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_2": "integrado",
    "mcore_detect_external_light": "[ICON]sensor de luz [PORT] intensidade de luz",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_0": "porta3",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_1": "porta4",
    "mcore_detect_external_loudness": "[ICON] sensor de som [PORT] volume",
    "mcore_detect_external_linefollower": "[ICON] sensor de seguimento de linha [PORT] mostra o valor",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "lado esquerdo",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "lado direito",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "todos",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "nenhum",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "preto",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "branco",
    "mcore_event_external_linefollower": "[ICON]sensor de seguimento de linha [PORT] deteta [LINEFOLLOW_STATE] para ser [BLACK_WHITE] ?",
    "mcore_detec_temperature": "[ICON] sensor de temperatura [PORT] [SLOT]temperatura (℃)",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_0": "humidade",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_1": "temperatura",
    "mcore_detect_humiture": "[ICON] sensor de humidade [PORT] [TEMP_HUMITURE]",
    "mcore_event_touch": "[ICON]sensor de toque [PORT] foi tocado ?",
    "mcore_detect_compass": "[ICON] bússola eletrónica [PORT] em direção a norte",
    "mcore_detect_flame": "[ICON] sensor de chama [PORT]valor",
    "mcore_detect_gas": "[ICON]sensor de gás[PORT] valor",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_0": "eixo x",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_1": "eixo y",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_2": "eixo z",
    "mcore_detect_gyro_angle": "[ICON]giroscópio [AXIS] ângulo",
    "mcore_detect_gyro_angle_1": "[ICON] gyroscope(one any white port) [GyroAxis] angle",
    "mcore_event_pir_motion": "[ICON] sensor de movimento [PORT] deteta movimento humano",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_0": "botão1",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_1": "botão2",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_2": "botão3",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_3": "botão4",
    "mcore_event_button_press": "[ICON]botão [PORT] [FOUR_KEY] está pressionado?",
    "mcore_event_limit_switch": "[ICON]interruptor de limite [PORT] [SLOT] está pressionado?",
    "mcore_detect_potentiometer": "[ICON]potenciómetro [PORT] mostra o valor",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_0": "eixo x",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_1": "eixo y",
    "mcore_detect_joystick": "[ICON] joystick [PORT] [AXIS_X_Y] valor",
    "mcore_detect_infrared": "[ICON] Recetor de infravermelhos [PORT]",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_0": "PM1.0",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_1": "PM2.5",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_2": "PM10",
    "auriga_detect_pm25_sensor": "[ICON] air quality sensor [PORT] ， [OPTION] (μg/m³)",
    "mbot_all": "Plataforma do Criador"
};