export default {
    "mcore_all": "Döredijiler üçin platforma",
    "extensionName": "Döredijiler üçin platforma",
    "extensionDescription": "mBot Giňeldişler kolleksiýasy",
    "MCORE_RUN_SHUTTER_PORT_0": "port1",
    "MCORE_RUN_SHUTTER_PORT_1": "port2",
    "MCORE_RUN_SHUTTER_PORT_2": "port3",
    "MCORE_RUN_SHUTTER_PORT_3": "port4",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_0": "bas",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_1": "goýber",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_2": "fokus",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_3": "fokuslamagy duruz",
    "mcore_run_shutter": "[ICON] sürgi [PORT] [SHUTTER_ACTION]",
    "MCORE_RUN_MOTOR_PORT_0": "hereketlendiriji port1",
    "MCORE_RUN_MOTOR_PORT_1": "hereketlendiriji port2",
    "MCORE_RUN_MOTOR_ROTATE_0": "sagadyň öwrüliş ugrunda",
    "MCORE_RUN_MOTOR_ROTATE_1": "sagadyň öwrüliş ugrunyň tersine",
    "mcore_run_motor": "[ICON] [PORT] belgili DC tok bilen işleýän hereketlendiriji [ROTATE] [POWER]% kuwwatlylyk bilen öwrülýär",
    "MCORE_RUN_SERVO_SLOT_0": "slot1",
    "MCORE_RUN_SERVO_SLOT_1": "slot2",
    "mcore_run_servo": "[ICON] serwo-hereketlendiriji [PORT] [SLOT] [DEGREE] derejelik burç bilen dur",
    "MCORE_RUN_FAN_FAN_ROTATE_0": "sagadyň öwrüliş ugrunda",
    "MCORE_RUN_FAN_FAN_ROTATE_1": "sagadyň öwrüliş ugrunyň tersine",
    "MCORE_RUN_FAN_FAN_ROTATE_2": "dur",
    "mcore_run_fan": "[ICON] [PORT] wentilýatory [FAN_ROTATE] aýlanýar",
    "mcore_show_face_time": "[ICON] [PORT]Yşyk-diot paneli [TIME] sek. boýunça [FACE_PANEL] şeklini görkezýär",
    "mcore_show_face": "[ICON] [PORT]Yşyk-diot paneli [FACE_PANEL] şeklini görkezýär",
    "mcore_show_face_position": "[ICON] [PORT] Yşyk-diot paneli x: [X] y: [Y] nokadynda [FACE_PANEL] şeklini görkezýär",
    "mcore_show_text": "[ICON] [PORT] Yşyk-diot paneli [TEXT] ýazgysyny görkezýär",
    "mcore_show_text_position": "[ICON] [PORT]Yşyk-diot paneli x: [X] y: [Y] nokadynda [TEXT] ýazgysyny görkezýär",
    "mcore_show_number": "[ICON] [PORT] Yşyk-diot paneli [NUMBER] belgisini görkezýär",
    "mcore_show_time": "[ICON] [PORT] Yşyk-diot paneli [NUMBER1]：[NUMBER2] wagtyny görkezýär",
    "mcore_show_face_off": "[ICON] [PORT] Yşyk-diot paneli ekrany arassalaýar",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "ählisi",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] RGB LED [PORT] çyrasy [LED_POSTION] [COLOR] reňki bilen [TIME] sek. boçunça ýanýar",
    "mcore_show_external_led": "[ICON]RGB LED [PORT] çyrasy [LED_POSTION] [COLOR] reňki bilen ýanýar",
    "mcore_show_external_led_rgb": "[ICON] RGB LED [PORT] çyrasy [LED_POSTION] [R] gyzyl [G] ýaşyl [B] gök reňler bilen ýanýar",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "gyzyl",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "mämişi",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "sary",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "ýaşyl",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "pöwrize",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "gök",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "benewşe",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "gara",
    "mcore_show_all_ledstrip_color": "[ICON] Yşyk-diot lentasy [PORT][SLOT] ähli çyralary bilen [COLOR_LIST] reňkinde ýanýar",
    "mcore_show_ledstrip_color": "[ICON] Yşyk-diot lentasynyň [PORT][SLOT][POS] çyrasy [COLOR_LIST] reňkinde ýanýar",
    "mcore_show_ledstrip_rbg": "[ICON] Yşyk-diot lentasynyň [PORT][SLOT][POS] çyrasy [R] gyzyl [G] ýaşyl [B] gök reňler bilen ýanýar",
    "mcore_show_7segments_number": "[ICON] 7-segmentli displeý [PORT] şu belgini görkezýär: [NUMBER]",
    "mcore_detect_external_ultrasonic": "[ICON] ultrases duýujy enjamy [PORT] aralygy",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_0": "port3",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_1": "port4",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_2": "platanyň özünde",
    "mcore_detect_external_light": "[ICON]ýagtylygy duýujy enjam [PORT] ýagtylygyň kuwwatlylygy",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_0": "port3",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_1": "port4",
    "mcore_detect_external_loudness": "[ICON] ses duýujy enjam [PORT] sesiň kuwwatlylygy",
    "mcore_detect_external_linefollower": "[ICON] çyzyk yzarlaýjy duýujy enjam [PORT] sany görkezýär",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "çep tarap",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "sag tarap",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "ählisi",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "hiçisi",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "gara",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "ak",
    "mcore_event_external_linefollower": "[ICON]çyzyk yzarlaýjy duýujy enjam [PORT] [BLACK_WHITE] [LINEFOLLOW_STATE] ýagdaýyny anyklaýar",
    "mcore_detec_temperature": "[ICON] gyzgynlyk derejesini duýujy enjam [PORT] [SLOT] gyzgynlyk derejesi (℃)",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_0": "çyglylyk",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_1": "gyzgynlyk derejesi",
    "mcore_detect_humiture": "[ICON] gyzgynlyk/çyglylyk derejesiniň duýujy enjamy [PORT] [TEMP_HUMITURE]",
    "mcore_event_touch": "[ICON] galtaşmany duýujy enjam [PORT] işjeňmi?",
    "mcore_detect_compass": "[ICON] elektron kompas [PORT] demirgazyk tarapa",
    "mcore_detect_flame": "[ICON] ot duýujy enjam [PORT] belgini anyklaýar",
    "mcore_detect_gas": "[ICON] gaz duýujy enjam [PORT] belgini anyklaýar",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_0": "X oky",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_1": "Y oky",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_2": "Z oky",
    "mcore_detect_gyro_angle": "[ICON]giroskop [AXIS] burç",
    "mcore_detect_gyro_angle_1": "[ICON] giroskobyň (islendik ak portunda) [GyroAxis] burçy",
    "mcore_event_pir_motion": "[ICON] hereketi duýujy enjam [PORT] adam hereketini anyklaýar?",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_0": "düwme 1",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_1": "düwme 2",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_2": "düwme 3",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_3": "düwme 4",
    "mcore_event_button_press": "[ICON] düwme [PORT] [FOUR_KEY] basylanmy?",
    "mcore_event_limit_switch": "[ICON]çäklendiriji düwme [PORT] [SLOT] basylanmy?",
    "mcore_detect_potentiometer": "[ICON]potensiometr [PORT] belgini görkezýär",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_0": "X oky",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_1": "Y oky",
    "mcore_detect_joystick": "[ICON]joýstigiň [AXIS_X_Y] okunyň görkezýän mukdary [PORT]",
    "mcore_detect_infrared": "[ICON]Infragyzyl signal alyjy enjam [PORT]",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_0": "PM1.0",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_1": "Ultradispers bölejikler görkezijisi PM2.5",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_2": "Ultradispers bölejikler görkezijisi PM10",
    "auriga_detect_pm25_sensor": "[ICON] howanyň hil derejesini duýujy enjamyň [PORT] porty, [OPTION] (μg/m³)",
    "mbot_all": "Döredijiler üçin platforma"
};