export default {
    "mcore_all": "Nền tảng của Maker",
    "extensionName": "Nền tảng của Maker",
    "extensionDescription": "bộ sưu tập phần mở rộng mBot",
    "MCORE_RUN_SHUTTER_PORT_0": "port1",
    "MCORE_RUN_SHUTTER_PORT_1": "port2",
    "MCORE_RUN_SHUTTER_PORT_2": "port3",
    "MCORE_RUN_SHUTTER_PORT_3": "port4",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_0": "nhấn",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_1": "thả",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_2": "tập trung",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_3": "ngừng tập trung",
    "mcore_run_shutter": "[ICON] Shutter [PORT] [SHUTTER_ACTION]",
    "MCORE_RUN_MOTOR_PORT_0": "động cơ port1",
    "MCORE_RUN_MOTOR_PORT_1": "động cơ port2",
    "MCORE_RUN_MOTOR_ROTATE_0": "chiều kim đồng hồ",
    "MCORE_RUN_MOTOR_ROTATE_1": "ngược kim đồng hồ",
    "mcore_run_motor": "động cơ DC [PORT] [ROTATE] quay với sức mạnh [POWER] %",
    "MCORE_RUN_SERVO_SLOT_0": "vị trí 1",
    "MCORE_RUN_SERVO_SLOT_1": "vị trí 2",
    "mcore_run_servo": "động cơ servo [PORT] [SLOT] đặt tại góc [DEGREE] độ",
    "MCORE_RUN_FAN_FAN_ROTATE_0": "chiều kim đồng hồ",
    "MCORE_RUN_FAN_FAN_ROTATE_1": "ngược kim đồng hồ",
    "MCORE_RUN_FAN_FAN_ROTATE_2": "dừng lại",
    "mcore_run_fan": "[ICON] quạt [PORT] [FAN_ROTATE] Quay",
    "mcore_show_face_time": "bảng LED [PORT] hiển thị hình ảnh [FACE_PANEL] trong [TIME] giây",
    "mcore_show_face": "bảng LED [PORT] hiển thị hình ảnh [FACE_PANEL]",
    "mcore_show_face_position": "bảng LED [PORT] hiển thị hình ảnh [FACE_PANEL] tại x: [X] y:[Y]",
    "mcore_show_text": "bảng LED [PORT] hiển thị văn bản [TEXT]",
    "mcore_show_text_position": "bảng LED [PORT] hiển thị văn bản [TEXT] tại x: [X] y:[Y]",
    "mcore_show_number": "bảng LED [PORT] hiển thị số [NUMBER]",
    "mcore_show_time": "bảng LED [PORT] hiển thị thời gian [NUMBER1]: [NUMBER2]",
    "mcore_show_face_off": "[ICON] Bảng LED [PORT] xóa màn hình",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "tất cả",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] ĐÈN LED RGB [PORT] sáng lên [LED_POSTION]  với màu [COLOR] trong [TIME] Giây",
    "mcore_show_external_led": "[ICON] ĐÈN LED RGB [PORT] sáng lên [LED_POSTION] với màu [COLOR]",
    "mcore_show_external_led_rgb": "RGB LED [PORT] bật [LED_POSTION] với màu đỏ [R] xanh lá [G] xanh lam [B]",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "đỏ",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "cam",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "vàng",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "xanh lá",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "lục lam",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "lam",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "màu tím",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "đen",
    "mcore_show_all_ledstrip_color": "dải LED [PORT] [SLOT] [POS] bật với màu [COLOR_LIST]",
    "mcore_show_ledstrip_color": "dải LED [PORT] [SLOT] [POS] bật với màu [COLOR_LIST]",
    "mcore_show_ledstrip_rbg": "dải LED [PORT] [SLOT] [POS] bật với màu đỏ [R] xanh lá [G] xanh lam [B]",
    "mcore_show_7segments_number": "[ICON] led bảy đoạn [PORT] Hiển thị số [NUMBER]",
    "mcore_detect_external_ultrasonic": "[ICON] cảm biến siêu âm [PORT] khoảng cách",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_0": "port3",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_1": "port4",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_2": "trên bo",
    "mcore_detect_external_light": "[ICON]cảm biến ánh sáng [PORT] cường độ ánh sáng",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_0": "port3",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_1": "port4",
    "mcore_detect_external_loudness": "[ICON] cảm biến âm thanh [PORT] Khối lượng",
    "mcore_detect_external_linefollower": "[ICON] cảm biến dò đường [PORT] giá trị",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "phía bên trái",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "phía bên phải",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "tất cả",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "không",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "đen",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "trắng",
    "mcore_event_external_linefollower": "cảm biến dò đường [PORT] phát hiện [LINEFOLLOW_STATE] là [BLACK_WHITE]",
    "mcore_detec_temperature": "[ICON] cảm biến nhiệt độ [PORT] [SLOT]nhiêt độ (° c)",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_0": "độ ẩm",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_1": "nhiệt độ",
    "mcore_detect_humiture": "[ICON] cảm biến nhiệt độ-độ ẩm[PORT] [TEMP_HUMITURE]",
    "mcore_event_touch": "[ICON] cảm biến chạm cảm ứng [PORT] được chạm ？",
    "mcore_detect_compass": "[ICON] cảm biến la bàn [PORT] về hướng bắc",
    "mcore_detect_flame": "[ICON] cảm biến lửa [PORT] giá trị",
    "mcore_detect_gas": "[ICON]cảm biến khí gas [PORT] giá trị",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_0": "trục x",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_1": "trục y",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_2": "trục z",
    "mcore_detect_gyro_angle": "[ICON] con quay hồi chuyển [AXIS] Góc",
    "mcore_detect_gyro_angle_1": "[ICON] gyroscope(one any white port) [GyroAxis] angle",
    "mcore_event_pir_motion": "[ICON] Cảm biến chuyển động PIR [PORT] phát hiện chuyển động của con người ？",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_0": "nút 1",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_1": "nút 2",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_2": "nút 3",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_3": "nút 4",
    "mcore_event_button_press": "[ICON] nút nhấn [PORT] [FOUR_KEY] đang nhấn？",
    "mcore_event_limit_switch": "[ICON] công tắc hành trình [PORT] [SLOT] được nhấn",
    "mcore_detect_potentiometer": "[ICON] đo điện thế [PORT] giá trị",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_0": "trục x",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_1": "trục y",
    "mcore_detect_joystick": "[ICON] giá trị Joystick [PORT] [AXIS_X_Y]",
    "mcore_detect_infrared": "[ICON]Đầu thu IR [PORT]",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_0": "PM1.0",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_1": "PM 2.5",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_2": "PM10",
    "auriga_detect_pm25_sensor": "[ICON] air quality sensor [PORT] ， [OPTION] (μg/m³)",
    "mbot_all": "Nền tảng của Maker"
};