export default {
    "mcore_all": "創客平台",
    "extensionName": "創客平台",
    "extensionDescription": "mBot 擴展中心",
    "MCORE_RUN_SHUTTER_PORT_0": "連接埠1",
    "MCORE_RUN_SHUTTER_PORT_1": "連接埠2",
    "MCORE_RUN_SHUTTER_PORT_2": "連接埠3",
    "MCORE_RUN_SHUTTER_PORT_3": "連接埠4",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_0": "按下",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_1": "鬆開",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_2": "對焦",
    "MCORE_RUN_SHUTTER_SHUTTER_ACTION_3": "停止對焦",
    "mcore_run_shutter": "[ICON] 快門 [PORT] [SHUTTER_ACTION]",
    "MCORE_RUN_MOTOR_PORT_0": "馬達連接埠1",
    "MCORE_RUN_MOTOR_PORT_1": "馬達連接埠 2",
    "MCORE_RUN_MOTOR_ROTATE_0": "順時針",
    "MCORE_RUN_MOTOR_ROTATE_1": "逆時針",
    "mcore_run_motor": "[ICON] 直流馬達 [PORT] [ROTATE] 旋轉，功率 [POWER] %",
    "MCORE_RUN_SERVO_SLOT_0": "插座1",
    "MCORE_RUN_SERVO_SLOT_1": "插座2",
    "mcore_run_servo": "[ICON] 伺服馬達 [PORT] [SLOT] 定位在 [DEGREE] 度",
    "MCORE_RUN_FAN_FAN_ROTATE_0": "順時針",
    "MCORE_RUN_FAN_FAN_ROTATE_1": "逆時針",
    "MCORE_RUN_FAN_FAN_ROTATE_2": "停止",
    "mcore_run_fan": "[ICON] 小風扇 [PORT] [FAN_ROTATE] 轉動",
    "mcore_show_face_time": "[ICON]表情面板 [PORT] 顯示圖案 [FACE_PANEL] 持續 [TIME] 秒",
    "mcore_show_face": "[ICON]表情面板 [PORT] 顯示圖案 [FACE_PANEL]",
    "mcore_show_face_position": "[ICON] 表情面板 [PORT] 顯示圖案 [FACE_PANEL] 於 x: [X] y: [Y]",
    "mcore_show_text": "[ICON] 表情面板 [PORT] 顯示文字 [TEXT]",
    "mcore_show_text_position": "[ICON] 表情面板 [PORT] 顯示文字 [TEXT] 位置 x: [X] y: [Y]",
    "mcore_show_number": "[ICON] 表情面板 [PORT] 顯示數字 [NUMBER]",
    "mcore_show_time": "[ICON] 表情面板 [PORT] 顯示時間 [NUMBER1]：[NUMBER2]",
    "mcore_show_face_off": "[ICON] 表情面板 [PORT] 清除畫面",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_0": "全部",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_1": "1",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_2": "2",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_3": "3",
    "MCORE_SHOW_EXTERNAL_LED_TIME_LED_POSTION_4": "4",
    "mcore_show_external_led_time": "[ICON] LED 燈 [PORT] 位置 [LED_POSTION] 的顏色設為 [COLOR]，持續 [TIME] 秒",
    "mcore_show_external_led": "[ICON] LED 燈 [PORT] 位置 [LED_POSTION] 的顏色設為 [COLOR]",
    "mcore_show_external_led_rgb": "[ICON] LED 燈 [PORT] 位置 [LED_POSTION] 的配色數值為 紅[R] 綠[G] 藍[B]",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_0": "紅",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_1": "橘色",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_2": "黃色",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_3": "綠色",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_4": "青色",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_5": "藍色",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_6": "紫色",
    "MCORE_SHOW_ALL_LEDSTRIP_COLOR_COLOR_LIST_7": "黑",
    "mcore_show_all_ledstrip_color": "[ICON] LED 燈條 [PORT] [SLOT] 全部顏色設為 [COLOR_LIST]",
    "mcore_show_ledstrip_color": "[ICON] LED 燈條 [PORT] [SLOT] 位置 [POS] 的顏色設為 [COLOR_LIST]",
    "mcore_show_ledstrip_rbg": "[ICON] LED 燈條 [PORT] [SLOT] 位置 [POS] 的配色數值為 紅 [R] 綠[G] 藍[B]",
    "mcore_show_7segments_number": "[ICON] 七段顯示器 [PORT] 顯示數字 [NUMBER]",
    "mcore_detect_external_ultrasonic": "[ICON] 超音波感測器 [PORT] 距離",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_0": "連接埠3",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_1": "連接埠4",
    "MCORE_DETECT_EXTERNAL_LIGHT_PORT_2": "板載",
    "mcore_detect_external_light": "[ICON] 光線感測器 [PORT] 光線強度值",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_0": "連接埠3",
    "MCORE_DETECT_EXTERNAL_LOUDNESS_PORT_1": "連接埠4",
    "mcore_detect_external_loudness": "[ICON] 聲音感測器 [PORT] 音量",
    "mcore_detect_external_linefollower": "[ICON] 循線感測器 [PORT] 數值",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_0": "左邊",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_1": "右邊",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_2": "全部",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_LINEFOLLOW_STATE_3": "沒有",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_0": "黑色",
    "MCORE_EVENT_EXTERNAL_LINEFOLLOWER_BLACK_WHITE_1": "白色",
    "mcore_event_external_linefollower": "[ICON] 循線感測器 [PORT] 偵測到 [LINEFOLLOW_STATE] 為 [BLACK_WHITE]？",
    "mcore_detec_temperature": "[ICON] 溫度感測器 [PORT] [SLOT] 溫度 (℃)",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_0": "濕度",
    "MCORE_DETECT_HUMITURE_TEMP_HUMITURE_1": "溫度",
    "mcore_detect_humiture": "[ICON] 溫濕度感測器 [PORT] [TEMP_HUMITURE]",
    "mcore_event_touch": "[ICON] 觸摸感測器 [PORT] 被觸摸？",
    "mcore_detect_compass": "[ICON] 電子羅盤 [PORT] 指向北方",
    "mcore_detect_flame": "[ICON] 火焰感測器 [PORT]數值",
    "mcore_detect_gas": "[ICON]氣體感測器 [PORT]  數值",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_0": "x 軸",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_1": "y 軸",
    "MCORE_DETECT_GYRO_ANGLE_AXIS_2": "z 軸",
    "mcore_detect_gyro_angle": "[ICON]陀螺儀 [AXIS] 角度",
    "mcore_detect_gyro_angle_1": "[ICON] 陀螺儀 (任何白色埠) [GyroAxis] 角度",
    "mcore_event_pir_motion": "[ICON] 人體紅外線感測器 [PORT] 偵測人的移動？",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_0": "按鈕1",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_1": "按鈕2",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_2": "按鈕3",
    "MCORE_EVENT_BUTTON_PRESS_FOUR_KEY_3": "按鈕4",
    "mcore_event_button_press": "[ICON] 按鍵模組 [PORT] [FOUR_KEY] 被按下？",
    "mcore_event_limit_switch": "[ICON] 極限開關[PORT] [SLOT] 已按下？",
    "mcore_detect_potentiometer": "[ICON] 旋轉電位器 [PORT] 數值",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_0": "x 軸",
    "MCORE_DETECT_JOYSTICK_AXIS_X_Y_1": "y 軸",
    "mcore_detect_joystick": "[ICON] 搖桿 [PORT] [AXIS_X_Y] 軸數值",
    "mcore_detect_infrared": "[ICON]紅外線接收器 [PORT]",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_0": "PM1.0",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_1": "PM2.5",
    "AURIGA_DETECT_PM25_SENSOR_OPTION_2": "PM10",
    "auriga_detect_pm25_sensor": "[ICON] 空氣品質感測器 [PORT]，[OPTION] (μg/m³)",
    "mbot_all": "創客平台"
};